Repository ballerina-platform/ballerina-lang, pull requests merged in 2018-12, with the labels that each got.

#12216 Disable failing tests and add them to broken group as L1 for release
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinfunctions/FreezeAndIsFrozenTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/nativeimpl/functions/ReflectEqualsTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredRecordPatternsTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableLiteralSyntaxTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableLiteralTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
Labels: L1/L2 for December

#12246 Fix testgen with new syntax changes
  composer/packages/api-designer/package-lock.json
  composer/tools/composer-cli/package-lock.json
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/TestGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/AbstractTestTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/RootTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/FunctionTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/HttpResourceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/HttpServiceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/WSClientServiceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/WSServiceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/position/PositionTreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/TreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/definition/DefinitionTreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/SymbolFindVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/references/ReferencesTreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureTreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/symbols/SymbolFindingVisitor.java
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpResource.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpsService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wsClientService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wsService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wssClientService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wssService.bal
Labels: Component/LanguageServer

#12230 Refactor how services are modeled in compiler.
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BlockingNativeCallableUnit.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/BLangConnectorSPIUtil.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/connector/api/Service.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/connector/impl/ResourceImpl.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/connector/impl/ServiceImpl.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/PackageInfo.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/PackageInfoReader.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/ServiceInfo.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/ServiceNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompiledPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangAnonymousModelHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/SymTag.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangService.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/PackageInfoWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/ServiceInfo.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/mock/nonlistening/NonListeningRegister.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/serviceendpoint/Register.java
  stdlib/reflect/src/main/java/org/ballerinalang/stdlib/reflect/nativeimpl/GetServiceAnnotations.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/balo/annotation/AnnotationTests.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/endpoint/ServiceTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/services/basics/SignatureTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/service/ServiceTypeTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/balo/test_balo/annotations/annotation.bal
  tests/ballerina-unit-test/src/test/resources/test-src/endpoint/new/service_basic_negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/endpoint/new/service_init_negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/endpoint/new/service_init_panic_negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/endpoint/new/service_multiple.bal
Labels: L1/L2 for December

#12274 Fix dataflow analyzer test cases
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/balo/object/ObjectInBaloTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/DataflowAnalysisTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/fieldaccess/SafeNavigationTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/object/AbstractObjectTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/object/AnonymousObjectTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/SealedArrayTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/dataflow/analysis/dataflow-analysis-negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal
  tests/ballerina-unit-test/src/test/resources/test-src/object/object_values_for_defaultable_field.bal
  tests/ballerina-unit-test/src/test/resources/test-src/object/object_with_non_defaultable_negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/statements/arrays/arraysofarrays/negative-sealed-arrays-of-arrays.bal
  tests/ballerina-unit-test/src/test/resources/test-src/structs/structs-negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_negative_test.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Component/Compiler, L1/L2 for December

#12214 Fix table is check/type assertion.
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BTableType.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typeassertion/TypeAssertionExpressionsTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/typeassertion/type_assertion_expr.bal
  tests/ballerina-unit-test/src/test/resources/test-src/types/table/table_nillable_mapping_negative.bal
Labels: L1/L2 for December

#12139 Enable JSON constraining using open records
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/ClosedRecordConstrainedJSONTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/OpenRecordConstrainedJSONNegativeTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/OpenRecordConstrainedJSONTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/types/jsontype/open_record_constrained_json.bal
  tests/ballerina-unit-test/src/test/resources/test-src/types/jsontype/open_record_constrained_json_negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/types/jsontype/open_record_constrained_json_negative_test.bal
Labels: L1/L2 for December

#12267 Fix native conversion and error test cases
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BLangVMErrors.java
  stdlib/runtime/src/main/ballerina/runtime/errors.bal
  stdlib/runtime/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/GetCallStack.java
  stdlib/runtime/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/GetErrorCallStackFrame.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionNegativeTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionWithStampTypesTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/nativeimpl/functions/RuntimeTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion--compile-negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal
  tests/ballerina-unit-test/src/test/resources/test-src/nativeimpl/functions/runtime-error.bal
  tests/ballerina-unit-test/src/test/resources/test-src/nativeimpl/functions/runtime-test.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: L1/L2 for December

#12300 Fix service test generation issues
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/TestGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/RootTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/HttpServiceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/WSServiceTemplate.java
  language-server/modules/langserver-core/src/main/resources/testgen/template/wsService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wssService.bal
Labels: Component/LanguageServer

#12087 Handle error returns in wait for any expression and add native method in runtime for timeout
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/SafeStrandCallback.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/WaitCallbackHandler.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.tokens
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  stdlib/runtime/src/main/ballerina/runtime/runtime.bal
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAnyActionsTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForOneActionsTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/workers/actions-negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/wait-for-any-actions.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/wait-for-one-actions.bal
Labels: L1/L2 for December

#12284 Improve error handling in BVM
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVMScheduler.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/util/XMLValidationUtils.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BXMLItem.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jdbc/SQLActionsTest.java
Labels: L1/L2 for December

#12293 Fix updating a type guarded variable
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BVarSymbol.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Component/Compiler, L1/L2 for December

#12287 Add socket module to document generation
  distribution/zip/ballerina-tools/pom.xml
Labels: Component/stdlib

#12327 Editable diagram: Native SVG Dropdown
  composer/packages/diagram/src/diagram/diagram-context.ts
  composer/packages/diagram/src/diagram/diagram.tsx
  composer/packages/diagram/src/diagram/editable-diagram.tsx
  composer/packages/diagram/src/views/components/add-worker-or-endpoint-menu.tsx
  composer/packages/diagram/src/views/components/svg-circle-button.tsx
  composer/packages/diagram/src/views/components/svg-dropdown-menu-trigger.tsx
  composer/packages/diagram/src/views/components/svg-dropdown-menu.tsx
  composer/packages/theme/src/definitions/views/diagram.less
  composer/packages/theme/src/themes/default/composer/views/diagram.variables
Labels: Component/Composer

#12313 Fix error in compile full-project for single bal files
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompiler.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/TextDocumentFormatUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddAllDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateObjectInitializerExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateTestExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/ImportModuleExecutor.java
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction.json
Labels: Component/LanguageServer

#12304 Fix renaming, goto def, find all references for constants
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/LSNodeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/position/PositionTreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/TreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/definition/DefinitionTreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/definition/util/DefinitionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/references/ReferencesTreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/symbols/SymbolFindingVisitor.java
Labels: Component/LanguageServer, Type/Bug

#12319 [WebSub] Change hub startup function signature
  stdlib/websub/src/main/ballerina/websub/commons.bal
  stdlib/websub/src/main/ballerina/websub/hub_configuration.bal
  stdlib/websub/src/main/ballerina/websub/hub_service.bal
  stdlib/websub/src/main/ballerina/websub/natives.bal
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/hub/Hub.java
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/nativeimpl/StartUpHubService.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/websub/WebSubCoreFunctionalityTestCase.java
  tests/ballerina-integration-test/src/test/resources/websub/services/01_websub_publisher.bal
  tests/ballerina-integration-test/src/test/resources/websub/services/02_redirection_publishers.bal
  tests/ballerina-integration-test/src/test/resources/websub/test_different_content_type_subscribers.bal
  tests/ballerina-integration-test/src/test/resources/websub/test_multiple_subscribers.bal
  tests/ballerina-integration-test/src/test/resources/websub/test_unsubscription_client.bal
  tests/ballerina-unit-test/src/test/resources/test-src/net/websub/hub/test_hub_startup.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Component/WebSub, Component/stdlib, Type/Improvement

#12050 Add LS support for typed binding pattern of the foreach statement
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/DocumentServiceKeys.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/UtilSymbolKeys.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
Labels: Component/LanguageServer

#12331 Improve iterating arrays with null values
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BMap.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/statements/foreach/ForeachArrayTests.java
  tests/ballerina-unit-test/src/test/resources/test-src/statements/foreach/foreach-arrays.bal
Labels: L1/L2 for December

#12352 Fix error stack trace
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BLangVMErrors.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: L1/L2 for December

#12339 Add '--experimental' flag to enable experimental features
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/Main.java
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/util/BCompileUtil.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/BuilderUtils.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/PushUtils.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/InstallCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/PushCommand.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/CompilerOptionName.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  misc/lib-creator/src/main/java/org/ballerinalang/stdlib/utils/GenerateBalo.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/BTestRunner.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestCmd.java
  misc/testerina/modules/testerina-core/src/test/java/org/ballerinalang/testerina/test/GroupFilterTest.java
  misc/testerina/modules/testerina-core/src/test/java/org/ballerinalang/testerina/test/ListGroupsTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/balo/BaloCreator.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/entry/function/ArgumentParserPositiveTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ExperimentalFeaturesTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/parser/experimental-features-negative.bal
Labels: L1/L2 for December

#12355 Improve LSCompiler error handling
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompiler.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/TextDocumentFormatUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddAllDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateObjectInitializerExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateTestExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/ImportModuleExecutor.java
Labels: Component/LanguageServer, Type/Improvement

#12401 Style tweaks on diagram if/else, while condition statements
  composer/packages/diagram/src/config/default.ts
  composer/packages/diagram/src/diagram/controllers/zoom-controllers.tsx
  composer/packages/diagram/src/diagram/diagram-utils.tsx
  composer/packages/diagram/src/views/components/action-invocation.tsx
  composer/packages/diagram/src/views/components/arrow-head.tsx
  composer/packages/diagram/src/views/components/block.tsx
  composer/packages/diagram/src/views/components/condition.tsx
  composer/packages/diagram/src/views/components/foreach.tsx
  composer/packages/diagram/src/views/components/if.tsx
  composer/packages/diagram/src/views/components/while.tsx
  composer/packages/diagram/src/visitors/sizing-visitor.ts
  composer/packages/theme/src/definitions/views/diagram.less
  composer/packages/theme/src/themes/default/composer/views/diagram.variables
  composer/packages/theme/src/themes/default/semantic-overrides/globals/site.variables
Labels: Component/Composer

#12400 Add binding pattern BBEs
  examples/index.json
  examples/match-expression/match_expression.bal
  examples/match-expression/match_expression.description
  examples/match-expression/match_expression.out
  examples/match/match.bal
  examples/match/match.out
  examples/match/tests/match.bal
  examples/record-destructure-binding-pattern/record_destructure_binding_pattern.bal
  examples/record-destructure-binding-pattern/record_destructure_binding_pattern.description
  examples/record-destructure-binding-pattern/record_destructure_binding_pattern.out
  examples/record-destructure-binding-pattern/tests/record_destructure_binding_pattern.bal
  examples/record-match-statement/record_match_statement.bal
  examples/record-match-statement/record_match_statement.description
  examples/record-match-statement/record_match_statement.out
  examples/record-match-statement/tests/record_match_statement_test.bal
  examples/record-type-binding-pattern/record_type_binding_pattern.bal
  examples/record-type-binding-pattern/record_type_binding_pattern.description
  examples/record-type-binding-pattern/record_type_binding_pattern.out
  examples/record-type-binding-pattern/tests/record_type_binding_pattern.bal
  examples/tuple-destructure-binding-pattern/tests/tuple_destructure_test.bal
  examples/tuple-destructure-binding-pattern/tuple_destructure.bal
  examples/tuple-destructure-binding-pattern/tuple_destructure.description
  examples/tuple-destructure-binding-pattern/tuple_destructure.out
  examples/tuple-match-statement/tests/tuple_match_statement_test.bal
  examples/tuple-match-statement/tuple_match_statement.bal
  examples/tuple-match-statement/tuple_match_statement.description
  examples/tuple-match-statement/tuple_match_statement.out
  examples/tuple-type-binding-pattern/tests/tuple_type_binding_pattern_test.bal
  examples/tuple-type-binding-pattern/tuple_type_binding_pattern.bal
  examples/tuple-type-binding-pattern/tuple_type_binding_pattern.description
  examples/tuple-type-binding-pattern/tuple_type_binding_pattern.out
Labels: Component/Examples, L1/L2 for December

#12403 Fix for generating API docs with docerina
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangErrorType.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  misc/docerina/src/test/java/org/ballerinalang/docgen/docs/HtmlDocTest.java
Labels: L1/L2 for December

#12413 Fix expression gets visited twice in type checker
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangExpression.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion.bal
Labels: L1/L2 for December

#12486 Fix csv-io error message
  examples/csv-io/csv_io.bal
Labels: Component/stdlib

#12299 Match error subtypes from receive with send
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerReceive.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerActionsNegativeTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFlushTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerSyncSendTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/workers/actions-negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/flush-workers.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/invalid-receive-with-error-return.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/sync-send.bal
Labels: L1/L2 for December

#12376 Fix single letter compilation issue in LSCompiler
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/CompletionCustomErrorStrategy.java
Labels: Component/LanguageServer

#12499 Fix LS code snippets generation for services
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/Snippet.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/filters/StatementTemplateFilter.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionTest.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation/resourceAnnotation1.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation/resourceAnnotation2.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation/serviceAnnotation1.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation/serviceAnnotation2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/anonFunctionSnippetSuggestion1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/anonFunctionSnippetSuggestion2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/anonFunctionSnippetSuggestion3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionAfterReturn.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionBeforeIfElse.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionBeforeWhile.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinElse.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinElseIf.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinIf.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinTransaction.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinTransactionOnRetry.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinWhile.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinWorkersInResource.json
  language-server/modules/langserver-core/src/test/resources/completion/function/emptyLinePrimitiveDataTypes.json
  language-server/modules/langserver-core/src/test/resources/completion/function/functionCompletionWithMissingImport.json
  language-server/modules/langserver-core/src/test/resources/completion/function/functionPointerAsParameter.json
  language-server/modules/langserver-core/src/test/resources/completion/function/importPackagesEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/function/importPackagesNonEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions10.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions5.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions6.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions7.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions8.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions9.json
  language-server/modules/langserver-core/src/test/resources/completion/function/nonEmptyLinePrimitiveDataTypes.json
  language-server/modules/langserver-core/src/test/resources/completion/function/suggestionsInWorkersWithinFunction.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/allVisibleSymbolsEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/allVisibleSymbolsNonEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore3.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/emptyLinePrimitiveDataTypes.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/nonEmptyLinePrimitiveDataTypes.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/userDefinedFunctionsEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/userDefinedFunctionsNonEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/userDefinedRecordEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/userDefinedRecordNonEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/service/serviceEndpointBind3.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/allTopLevelItemSkip.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/globalVarDef1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelEmptyFirstLine.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelFirstLineWithPublicDefStart.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelFirstLineWithPublicKeyword.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelNonEmptyFirstLine.json
Labels: Component/LanguageServer, Type/Bug

#12513 Flush and sync send fix
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/Context.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/NativeCallContext.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/SafeStrandCallback.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/WaitCallbackHandler.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/WorkerDataChannel.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BCallableFuture.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/PackageInfoReader.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/observability/ObservabilityUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/codegen/CodeGenerator.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerSyncSendTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/workers/sync-send.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/wait-for-any-actions.bal
Labels: L1/L2 for December

#12498 Fix JSON test cases
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/BJSONValueTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/types/jsontype/json-value.bal
Labels: L1/L2 for December

#12482 Fix xml literal tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/codegen/CodeGenerator.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-with-namespaces.bal
Labels: L1/L2 for December

#12485 Fix and update failing test cases
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectEquivalencyTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/services/basics/ServiceTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/task/AppointmentTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/task/TimerTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/object/object-equivalency.bal
  tests/ballerina-unit-test/src/test/resources/test-src/object/object_function_pointer.bal
  tests/ballerina-unit-test/src/test/resources/test-src/task/app-workers.bal
  tests/ballerina-unit-test/src/test/resources/test-src/task/timer-workers.bal
Labels: L1/L2 for December

#12452 Add test cases for worker interactions in fork and wait
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAnyActionsTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/workers/invalid-actions-in-fork.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/wait-for-any-actions.bal
Labels: L1/L2 for December

#12537 Update BBEs for core/lang error reason/detail changes
  examples/check/check.out
  examples/immutable-values/immutable_values.bal
  examples/type-assertion/type_assertion.bal
Labels: Component/Examples, L1/L2 for December

#12531 Fix run function for Windows
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/Main.java
Labels: Component/CLI, L1/L2 for December

#12554 Fix worker-interactions BBE
  examples/worker-interaction/worker_interaction.bal
  examples/worker-interaction/worker_interaction.out
Labels: L1/L2 for December

#12532 Handle network logs listener connection reset error
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/traces/Listener.java
Labels: Component/VScode plugin

#12587 Fix XMLAccessTest testcase
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
Labels: L1/L2 for December

#12496 Fix issues with BBEs
  examples/explicitly-typed-expressions/explicitly_typed_expressions.bal
  examples/explicitly-typed-expressions/explicitly_typed_expressions.description
  examples/explicitly-typed-expressions/explicitly_typed_expressions.out
  examples/explicitly-typed-expressions/tests/explicitly_typed_expressions_test.bal
  examples/index.json
  examples/local-transactions-with-participants/local_transactions_with_participants.bal
  examples/local-transactions-with-participants/local_transactions_with_participants.description
  examples/local-transactions-with-participants/local_transactions_with_participants.out
  examples/locks/locks.description
  examples/panic/panic.out
  examples/tuple-destructure-binding-pattern/tuple_destructure_binding_pattern.bal
  examples/tuple-destructure-binding-pattern/tuple_destructure_binding_pattern.description
  examples/tuple-destructure-binding-pattern/tuple_destructure_binding_pattern.out
Labels: Component/Examples, L1/L2 for December

#12585 Update record binding pattern BBEs
  examples/record-destructure-binding-pattern/record_destructure_binding_pattern.bal
  examples/record-destructure-binding-pattern/record_destructure_binding_pattern.description
  examples/record-destructure-binding-pattern/record_destructure_binding_pattern.out
  examples/record-destructure-binding-pattern/tests/record_destructure_binding_pattern.bal
  examples/record-type-binding-pattern/record_type_binding_pattern.bal
  examples/record-type-binding-pattern/record_type_binding_pattern.description
  examples/record-type-binding-pattern/record_type_binding_pattern.out
  examples/record-type-binding-pattern/tests/record_type_binding_pattern.bal
Labels: Component/Examples, L1/L2 for December

#12572 Fix for when no WebSocket service name
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketService.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/WebSocketAutoPingPongTest.java
  tests/ballerina-integration-test/src/test/resources/websocket/wsservices/17_simple_proxy_server.bal
  tests/ballerina-integration-test/src/test/resources/websocket/wsservices/18_simple_server_without_ping_resource.bal
Labels: Component/WebSocket, Component/stdlib

#12545 Make failure in client handshake go to onError
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketClientConnectorListener.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketClientHandshakeListener.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketOpenConnectionInfo.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketServerConnectorListener.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Close.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Ready.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocketclientendpoint/InitEndpoint.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/ClientInitializationFailureTest.java
  tests/ballerina-integration-test/src/test/resources/websocket/wsservices/09_client_failure.bal
Labels: Component/WebSocket, Component/stdlib

#12597 Add LS fixes for changing `create()`->`convert()`
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/Snippet.java
Labels: Component/LanguageServer, L1/L2 for December, Type/Bug

#12593 Add `listener` keyword for the top-level completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/TopLevelResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/Snippet.java
Labels: Component/LanguageServer, Type/Bug

#12565 Fix windows issue in language-server not starting up for the zip distro
  distribution/zip/ballerina-tools/resources/language-server-launcher.bat
Labels: Component/LanguageServer, OS/Windows, Type/Bug

#12601 Fix package prefix not added automatically for some BTypes
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/ValueSpaceGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation5.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation6.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions4.json
Labels: Component/LanguageServer, Type/Bug

#12626 Add compile time validation for resource return values
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/AbstractTransportCompilerPlugin.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/HttpServiceCompilerPlugin.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/ResourceSignatureValidator.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/services/basics/SignatureTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/services/signature/invalid-return.bal
Labels: L1/L2 for December

#12607 Add worker related fixes
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/SafeStrandCallback.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/Strand.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/WDChannels.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/WaitCallbackHandler.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/WorkerDataChannel.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/CallableUnitInfo.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/Instruction.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/PackageInfoReader.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/NotSoBasicWorkerTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFlushTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerSyncSendTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/workers/flush-workers.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/invalid-receive-with-check.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/invalid-receive-with-trap.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/sync-send.bal
  tests/ballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: L1/L2 for December

#12625 Compile all imports of the testable package if tests are enabled
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/util/BCompileUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/codegen/CodeGenerator.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompilerUtil.java
Labels: L1/L2 for December

#12635 Add default values to ldap trust configurations
  stdlib/auth/src/main/ballerina/auth/ldap_auth_store_provider.bal
Labels: L1/L2 for December

#12637 Fix source gen issue with binding patterns
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingNodeTree.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingSourceGen.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/bindingPatterns.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedBindingPatterns.bal
Labels: Component/LanguageServer, Type/Bug

#12651 Add fix for parent strand to child strand error propagation
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVMExecutor.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/SafeStrandCallback.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/StrandCallback.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/StrandResourceCallback.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/StrandWaitCallback.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/WaitCallbackHandler.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BCallableFuture.java
  stdlib/runtime/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/GetErrorCallStackFrame.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: L1/L2 for December

#12659 Fix testsgen issues
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/TestGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/HttpResourceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/HttpServiceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/position/PositionTreeVisitor.java
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpResource.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpsService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wsService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wssService.bal
Labels: Component/LanguageServer, Type/Bug

#12670 Fix source gen issue with rendering var def
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingSourceGen.java
Labels: L1/L2 for December

#12672 Fix duplicate import statement issue in language server
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/AbstractItemResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/filters/DelimiterBasedContentFilter.java
Labels: L1/L2 for December

#12674 Fix BBE file names
  examples/anydata-type/anydata_type.out
  examples/byte-type/byte_type.out
Labels: L1/L2 for December

#12680 Fix tests generation for the records
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/ValueSpaceGenerator.java
Labels: Component/LanguageServer, L1/L2 for December, Type/Bug

#12716 Add maxFrameSize config for client
  pom.xml
  stdlib/http/src/main/ballerina/http/annotation.bal
  stdlib/http/src/main/ballerina/http/websocket/websocket_client.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketService.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocketclientendpoint/InitEndpoint.java
Labels: Component/WebSocket, Component/stdlib

#12820 Enable source gen tests
  examples/http-forwarded-extension/http_forwarded_extension.bal
  examples/http-forwarded-extension/http_forwarded_extension.client.out
  examples/http-forwarded-extension/http_forwarded_extension.description
  examples/http-forwarded-extension/http_forwarded_extension.server.out
  examples/http-forwarded-extension/tests/http_forwarded_extension_test.bal
  examples/mb-simple-durable-topic-message-subscriber/mb_simple_durable_topic_message_subscriber.bal
  examples/mb-simple-durable-topic-message-subscriber/mb_simple_durable_topic_message_subscriber.description
  examples/mb-simple-durable-topic-message-subscriber/mb_simple_durable_topic_message_subscriber.out
  examples/mb-simple-queue-message-producer/mb_simple_queue_message_producer.bal
  examples/mb-simple-queue-message-producer/mb_simple_queue_message_producer.description
  examples/mb-simple-queue-message-producer/mb_simple_queue_message_producer.out
  examples/mb-simple-queue-message-receiver/mb_simple_queue_message_receiver.bal
  examples/mb-simple-queue-message-receiver/mb_simple_queue_message_receiver.description
  examples/mb-simple-queue-message-receiver/mb_simple_queue_message_receiver.out
  examples/mb-simple-topic-message-publisher/mb_simple_topic_message_publisher.bal
  examples/mb-simple-topic-message-publisher/mb_simple_topic_message_publisher.description
  examples/mb-simple-topic-message-publisher/mb_simple_topic_message_publisher.out
  examples/mb-simple-topic-message-subscriber/mb_simple_topic_message_subscriber.bal
  examples/mb-simple-topic-message-subscriber/mb_simple_topic_message_subscriber.description
  examples/mb-simple-topic-message-subscriber/mb_simple_topic_message_subscriber.out
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/sourcegen/SourceGenTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/TaintedStatusPropagationTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_stmt_basic.bal
  tests/ballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/fork-join-negative.bal
  tests/ballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/fork-join.bal
Labels: Component/Compiler, Component/LanguageServer

#12846 Add json to csv transform example
  examples/index.json
  examples/json-csv/json_csv.bal
  examples/json-csv/json_csv.description
  examples/json-csv/json_csv.out
Labels: Component/stdlib

#12858 Fix doc comments
  examples/json-csv/json_csv.bal
  examples/json-csv/json_csv.description
Labels: Component/stdlib

#12711 Replace foreach with a while loop in cache expiry
  stdlib/cache/src/main/ballerina/cache/cache.bal
Labels: Component/stdlib, Type/Bug

#12864 Fix goto definition and references fails for multi-modules
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/definition/util/DefinitionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/references/ReferencesTreeVisitor.java
Labels: Component/LanguageServer, Type/Bug

#12872 Fix test generation for the websocket service
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/WSServiceTemplate.java
  language-server/modules/langserver-core/src/main/resources/testgen/template/wsService.bal
Labels: Component/LanguageServer, Type/Bug

#12898 Update header/content based routing BBEs
  examples/content-based-routing/content_based_routing.bal
  examples/header-based-routing/header_based_routing.bal
Labels: Component/Examples

#12903 Adjust the code to close tables properly in TableTests
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/types/table/table_type.bal
  tests/ballerina-unit-test/src/test/resources/test-src/types/table/table_type_negative.bal
Labels: Component/Data, Component/stdlib
