Repository ballerina-platform/ballerina-lang, pull requests merged in 2019-04, with the labels that each got.

#14812 Allow clone/freeze on pure typed structures and clone and freeze the error detail
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BLangVMErrors.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BError.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BValue.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/transactions/TransactionUtils.java
  cli/ballerina-cli-utils/src/main/java/org/ballerinalang/cli/utils/BVMEmbeddedExecutor.java
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  stdlib/database/mysql/build.gradle
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/utils/TestCallableUnitCallback.java
  stdlib/jms/build.gradle
  stdlib/jms/pom.xml
  stdlib/utils/src/main/java/org/ballerinalang/utils/Clone.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Freeze.java
  tests/ballerina-spec-conformance-tests/S05_structured_values/tests/deviations/error.bal
  tests/ballerina-spec-conformance-tests/S05_structured_values/tests/error.bal
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinfunctions/FreezeAndIsFrozenTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/CloneOperationTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionNegativeTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/JSONStampInbuiltFunctionTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/MapStampInbuiltFunctionTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/RecordStampInbuiltFunctionTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExprTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsAndNilTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/MainFunctionsTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/nativeimpl/functions/regex/RegexTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectInitializerTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/services/testutils/TestCallableUnitCallback.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/TransactionBlockTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/JSONTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/map/ConstrainedMapTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/var/VarDeclaredAssignmentStmtTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAnyActionsTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFlushTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerSyncSendTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/clone-operation.bal
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal
Labels: Component/Compiler

#14759 Support panic and trap for jvm target
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BErrorType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/BuilderUtils.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/java/org/ballerinalang/compiler/backend/jvm/JVMCodeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGenEnv.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  stdlib/jvm/src/main/ballerina/jvm/types.bal
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/methodvisitor/VisitTryCatchBlock.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/errors.bal
Labels: Component/jBallerina, Type/New Feature

#14762 Fix issue with union type params in object __init()
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/object/object_type_union.bal
  tests/ballerina-unit-test/src/test/resources/test-src/object/object_type_union_negative.bal
Labels: Component/Compiler

#14833 Fix error equality and clone and freeze default error detail
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  misc/testerina/modules/testerina-core/src/main/ballerina/test/assert.bal
  stdlib/privacy/build.gradle
  stdlib/privacy/pom.xml
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/error/error_test.bal
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation_negative.bal
Labels: Component/Compiler

#14807 Fix code not found on Show Examples command
  tool-plugins/vscode/src/extension.ts
Labels: Component/VScode plugin

#14814 Display local client endpoints in diagram
  composer/packages/ast-model/src/ast-interfaces.ts
  composer/packages/diagram/src/views/components/block.tsx
  composer/packages/diagram/src/views/components/foreach.tsx
  composer/packages/diagram/src/views/components/if.tsx
  composer/packages/diagram/src/views/components/life-line.tsx
  composer/packages/diagram/src/views/components/while.tsx
  composer/packages/diagram/src/views/components/worker.tsx
  composer/packages/diagram/src/visitors/init-visitor.ts
  composer/packages/diagram/src/visitors/positioning-visitor.ts
  composer/packages/diagram/src/visitors/sizing-visitor.ts
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/common/modal/SymbolMetaInfo.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/TextDocumentFormatUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/EndpointFindVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentServiceImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/VisibleEndpointVisitor.java
Labels: Component/Diagram

#14763 Fix endpoint code lense for client endpoints in blocks
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/EndpointFindVisitor.java
Labels: Component/LanguageServer

#14788 [NATS] Add close connection
  examples/nats-basic-client/publisher.bal
  examples/nats-basic-client/subscriber.bal
  stdlib/nats/pom.xml
  stdlib/nats/src/main/ballerina/nats/connection/connection.bal
  stdlib/nats/src/main/ballerina/nats/consumer/listener.bal
  stdlib/nats/src/main/ballerina/nats/producer/producer.bal
  stdlib/nats/src/main/java/org/ballerinalang/nats/nativeimpl/connection/Close.java
Labels: Component/Messaging

#14859 Fix is check for closed array as open array
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
Labels: Component/Compiler

#14845 Add recursive union and object types for BIR
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/serializer.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
  stdlib/bir/src/test/java/org/ballerinalang/stdlib/io/bir/TypeGenTest.java
  stdlib/bir/src/test/resources/test-src/bir/types.bal
Labels: Component/jBallerina, Type/Task

#14789 Add formatting support for lock
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingNodeTree.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/Tokens.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFunction.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedIntegerRangeExpression.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedLock.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedWhile.bal
  language-server/modules/langserver-core/src/test/resources/formatting/integerRangeExpression.bal
  language-server/modules/langserver-core/src/test/resources/formatting/lock.bal
  language-server/modules/langserver-core/src/test/resources/formatting/while.bal
Labels: Component/Formatting

#14830 Fix build failure in travis due spot bug issue
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/proto/ServiceProtoBuilder.java
Labels: Component/gRPC, Component/stdlib

#14627 Allow addition and compound assigment of string and xml
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/util/XMLUtils.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BXMLItem.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BXMLSequence.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/xmllib/Elements.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/closures/VarMutabilityClosureTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/AddOperationTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/LengthOperationTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLNativeFunctionTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation.bal
  tests/ballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal
  tests/ballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals.bal
  tests/ballerina-unit-test/src/test/resources/test-src/types/xml/xml-native-functions.bal
Labels: Component/Compiler

#14786 Update worker interaction syncing algorithm
  composer/packages/ast-model/src/model-utils.ts
  composer/packages/diagram/src/visitors/sizing-visitor.ts
Labels: Component/Diagram

#14832 Fix testgen code action not working for functions with `error` params
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateTestExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/TestGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/ValueSpaceGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/FunctionTemplate.java
  language-server/modules/langserver-core/src/main/resources/testgen/template/voidFunction.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/voidFunctionNoParams.bal
Labels: Component/LanguageServer, Type/Bug

#14834 Add gRPC service snippet for Language Server
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/subproviders/AbstractSubCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/Snippet.java
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelCompletionAfterDocumentation.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelEmptyFirstLine.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelNonEmptyFirstLine.json
Labels: Component/LanguageServer, Type/Improvement

#14840 Add a code action to ignore return value from a function
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/DocsCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddAllDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateObjectInitializerExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateTestExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateVariableExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/IgnoreReturnExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/ImportModuleExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/PullModuleExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CommandExecutionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/ignoreReturnValueCodeAction.json
  language-server/modules/langserver-core/src/test/resources/command/ignoreReturnValue.json
Labels: Component/LanguageServer, Type/New Feature

#14893 Update Module.md
  stdlib/database/h2/src/main/ballerina/h2/Module.md
  stdlib/database/mysql/src/main/ballerina/mysql/Module.md
Labels: Component/Data, Component/stdlib, Type/Docs

#14904 Update WebSub module.md with basic auth support
  stdlib/websub/src/main/ballerina/websub/Module.md
Labels: Component/WebSub, Component/stdlib, Type/Docs

#14910 Fix windows test failure due to new line
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/nativeimpl/request/RequestNativeFunctionNegativeTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/nativeimpl/response/ResponseNativeFunctionNegativeTest.java
Labels: Component/HTTP, Component/stdlib, Type/Bug

#14946 Fix issues with new examples
  examples/artemis-anycast-session-consumer/artemis_anycast_session_consumer.description
  examples/artemis-multicast-consumer/artemis_multicast_consumer.description
  examples/filepath/filepath.description
  examples/index.json
  examples/nats-basic-client/nats_basic_client.description
  examples/rabbitmq-simple-consumer/rabbitmq_simple_consumer.bal
  examples/rabbitmq-simple-consumer/rabbitmq_simple_consumer.description
  examples/rabbitmq-simple-consumer/rabbitmq_simple_consumer.out
  examples/rabbitmq-simple-producer/rabbitmq_simple_producer.bal
  examples/rabbitmq-simple-producer/rabbitmq_simple_producer.description
  examples/rabbitmq-simple-producer/rabbitmq_simple_producer.out
Labels: Component/Examples

#14920 Update BBEs for 0.991.0
  examples/anydata-type/anydata_type.bal
  examples/anydata-type/anydata_type.description
  examples/clone/clone.bal
  examples/clone/clone.description
  examples/documentation/documentation.bal
  examples/elvis-operator/elvis_operator.bal
  examples/elvis-operator/elvis_operator.description
  examples/hello-world-client/hello_world_client.bal
  examples/hello-world/hello_world.description
  examples/immutable-values/immutable_values.bal
  examples/index.json
  examples/the-main-function/the_main_function.bal
  examples/type-check-expression/type_check_expression.description
  examples/type-guard/tests/type_guard_test.bal
  examples/type-guard/type_guard.bal
  examples/type-guard/type_guard.description
  examples/type-guard/type_guard.out
  examples/type-test-expression/tests/type_test_expression_test.bal
  examples/type-test-expression/type_test_expression.bal
  examples/type-test-expression/type_test_expression.description
  examples/type-test-expression/type_test_expression.out
  examples/var/var.description
Labels: Component/Examples

#14911 Update bbes for 0.991.0
  examples/closures/closures.bal
  examples/closures/closures.out
  examples/closures/tests/closures_test.bal
  examples/constants/constants.bal
  examples/constants/constants.description
  examples/foreach/foreach.bal
  examples/function-pointers/function_pointers.bal
  examples/functional-iteration/functional_iteration.bal
  examples/length/length.bal
  examples/length/length.description
  examples/locks/locks.bal
  examples/locks/locks.description
  examples/match/match.bal
  examples/record-match-statement/record_match_statement.bal
  examples/record-match-statement/record_match_statement.description
  examples/tuple-match-statement/tuple_match_statement.bal
  examples/tuple-match-statement/tuple_match_statement.description
  examples/tuple-type-binding-pattern/tuple_type_binding_pattern.bal
  examples/xml-access/xml_access.bal
  examples/xml-access/xml_access.description
  examples/xml-attributes/xml_attributes.bal
  examples/xml-attributes/xml_attributes.out
  examples/xml-literal/xml_literal.bal
  examples/xml-literal/xml_literal.description
  examples/xml-namespaces/xml_namespaces.bal
  examples/xml-to-json-conversion/xml_to_json_conversion.description
Labels: Component/Examples

#14952 Add new BBEs
  examples/checkpanic/checkpanic.bal
  examples/checkpanic/checkpanic.description
  examples/checkpanic/checkpanic.out
  examples/checkpanic/tests/checkpanic_test.bal
  examples/error-destructure-binding-pattern/error_destructure_binding_pattern.bal
  examples/error-destructure-binding-pattern/error_destructure_binding_pattern.description
  examples/error-destructure-binding-pattern/error_destructure_binding_pattern.out
  examples/error-destructure-binding-pattern/tests/error_destructure_binding_pattern.bal
  examples/error-match-statement/error_match_statement.bal
  examples/error-match-statement/error_match_statement.description
  examples/error-match-statement/error_match_statement.out
  examples/error-match-statement/tests/error_match_statement_test.bal
  examples/error-type-binding-pattern/error_type_binding_pattern.bal
  examples/error-type-binding-pattern/error_type_binding_pattern.description
  examples/error-type-binding-pattern/error_type_binding_pattern.out
  examples/error-type-binding-pattern/tests/error_type_binding_pattern.bal
  examples/index.json
Labels: Component/Examples

#14948 Add object support for jballerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ObjectValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/VarKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/classwriter/BallerinaClassWriter.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/classwriter/Init.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/classwriter/Visit.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/objects.bal
Labels: Component/jBallerina, Type/New Feature

#14939 Remove andes client and update examples
  distribution/zip/ballerina/build.gradle
  distribution/zip/ballerina/pom.xml
  distribution/zip/ballerina/src/assembly/bin.xml
  examples/jms-durable-topic-message-subscriber/jms_durable_topic_message_subscriber.bal
  examples/jms-durable-topic-message-subscriber/jms_durable_topic_message_subscriber.out
  examples/jms-headers-and-properties/jms_headers_and_properties.bal
  examples/jms-headers-and-properties/jms_headers_and_properties.out
  examples/jms-queue-message-producer/jms_queue_message_producer.bal
  examples/jms-queue-message-producer/jms_queue_message_producer.description
  examples/jms-queue-message-producer/jms_queue_message_producer.out
  examples/jms-queue-message-receiver-with-client-acknowledgment/jms_queue_message_receiver_with_client_acknowledgment.bal
  examples/jms-queue-message-receiver-with-client-acknowledgment/jms_queue_message_receiver_with_client_acknowledgment.out
  examples/jms-queue-message-receiver/jms_queue_message_receiver.bal
  examples/jms-queue-message-receiver/jms_queue_message_receiver.description
  examples/jms-queue-message-receiver/jms_queue_message_receiver.out
  examples/jms-simple-durable-topic-message-subscriber/jms_simple_durable_topic_message_subscriber.bal
  examples/jms-simple-durable-topic-message-subscriber/jms_simple_durable_topic_message_subscriber.out
  examples/jms-simple-queue-message-producer/jms_simple_queue_message_producer.bal
  examples/jms-simple-queue-message-producer/jms_simple_queue_message_producer.out
  examples/jms-simple-queue-message-receiver/jms_simple_queue_message_receiver.bal
  examples/jms-simple-queue-message-receiver/jms_simple_queue_message_receiver.out
  examples/jms-simple-topic-message-producer/jms_simple_topic_message_producer.bal
  examples/jms-simple-topic-message-producer/jms_simple_topic_message_producer.out
  examples/jms-simple-topic-message-subscriber/jms_simple_topic_message_subscriber.bal
  examples/jms-simple-topic-message-subscriber/jms_simple_topic_message_subscriber.out
  examples/jms-synchronous-queue-message-receiver/jms_synchronous_queue_message_receiver.bal
  examples/jms-synchronous-queue-message-receiver/jms_synchronous_queue_message_receiver.out
  examples/jms-topic-message-producer/jms_topic_message_producer.bal
  examples/jms-topic-message-producer/jms_topic_message_producer.description
  examples/jms-topic-message-subscriber/jms_topic_message_subscriber.bal
  examples/jms-topic-message-subscriber/jms_topic_message_subscriber.out
  examples/send-jms-message-to-http-endpoint/send_jms_message_to_http_endpoint.bal
  examples/send-jms-message-to-http-endpoint/send_jms_message_to_http_endpoint.out
  examples/transactional-queue-message-producer/transactional_queue_message_producer.bal
  examples/transactional-queue-message-producer/transactional_queue_message_producer.out
  pom.xml
  stdlib/jms/src/main/ballerina/jms/Module.md
  stdlib/jms/src/main/ballerina/jms/durable_topic_subscriber.bal
  stdlib/jms/src/main/ballerina/jms/queue_receiver.bal
  stdlib/jms/src/main/ballerina/jms/session.bal
  stdlib/jms/src/main/ballerina/jms/topic_subscriber.bal
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/JmsConstants.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/JmsUtils.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/common/CloseConsumerHandler.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/common/StartNonDaemonThreadHandler.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/connection/CreateConnection.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/queue/receiver/CreateQueueReceiver.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/queue/receiver/Start.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/topic/durable/subscriber/Start.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/topic/subscriber/Start.java
Labels: Component/Messaging, Component/jms, Component/stdlib

#14917 Update the object initializer BBE
  examples/object-initializer/object_initializer.bal
  examples/object-initializer/object_initializer.description
  examples/object-initializer/object_initializer.out
Labels: Component/Examples

#14922 Improve BBEs
  examples/abstract-objects/abstract_objects.bal
  examples/abstract-objects/abstract_objects.description
  examples/anonymous-objects/anonymous_objects.bal
  examples/index.json
  examples/object-assignability/object_assignability.bal
  examples/object-assignability/object_assignability.description
  examples/object-member-functions/object_member_functions.description
  examples/object-methods/object_methods.bal
  examples/object-methods/object_methods.description
  examples/object-methods/object_methods.out
  examples/object-methods/tests/object_methods_test.bal
  examples/object-type-reference/object_type_reference.bal
  examples/object-type-reference/object_type_reference.description
  examples/objects/objects.bal
  examples/objects/objects.description
  examples/objects/tests/objects_test.bal
  examples/record-optional-fields/record_optional_fields.bal
  examples/record-optional-fields/tests/record_optional_fields_test.bal
  examples/records/records.bal
Labels: Component/Examples

#14975 Add named args and rest args support for function invocation
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/jvm/JBallerinaInMemoryClassLoader.java
  tests/ballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#14787 Remove llvm dependency from distribution
  distribution/zip/ballerina-tools/LICENSE
  distribution/zip/ballerina-tools/build.gradle
  distribution/zip/ballerina-tools/pom.xml
  distribution/zip/ballerina-tools/src/assembly/bin.xml
Labels: Component/Distribution

#14982 Add anonymous objects support
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/exceptions/BLangRuntimeException.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  tests/ballerina-unit-test/src/test/resources/test-src/object/anon_object.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#14994 Fix compilation fails on errors for the incomplete code
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/Compiler.java
Labels: Component/Compiler, Component/LanguageServer, Type/Bug

#14958 Support Freeze and clone builtin methods for JVM target
  bvm/ballerina-core/src/main/java/org/ballerinalang/natives/NativeUnitLoader.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  stdlib/utils/build.gradle
  stdlib/utils/pom.xml
  stdlib/utils/src/main/ballerina/utils/built-in-methods.bal
  stdlib/utils/src/main/java/org/ballerinalang/utils/Clone.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Convert.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Freeze.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/SimpleValueConvert.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Stamp.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/BuiltinMethodTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/builtin-methods.bal
Labels: Component/jBallerina

#14989 Add support for object annotation reading
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/AnnotationUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/AnnotatableType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/AttachedFunction.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BFunctionType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BObjectType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BRecordType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BStructureType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ObjectValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
Labels: Component/jBallerina, Type/New Feature

#14995 Support calling attached functions from attached functions in BIR
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/BuilderUtils.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/main.bal
  compiler/ballerina-backend-jvm/src/main/java/org/ballerinalang/compiler/backend/jvm/JVMCodeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/classwriter/BallerinaClassWriter.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
Labels: Component/jBallerina

#14972 Add strand based scheduler
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Scheduler.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Strand.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FutureValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
Labels: Component/jBallerina

#14701 Remove MB subscriptions in streams
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BStream.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/streams/DefaultStreamSubscription.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/streams/SiddhiStreamSubscription.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/streams/StreamSubscription.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/streams/StreamSubscriptionManager.java
  stdlib/socket/src/test/java/org/ballerinalang/stdlib/socket/ClientSocketTest.java
  stdlib/streams/src/main/ballerina/streams/scheduler.bal
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/BallerinaStreamsV2HoppingWindowTest.java
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/BallerinaStreamsV2TimeAccumulatingWindowTest.java
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/BallerinaStreamsV2TimeLengthWindowTest.java
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/BallerinaStreamsV2TimeOrderWindowTest.java
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/nativeimpl/BallerinaStreamsV2SelectAggregationTest.java
Labels: Component/BVM

#15016 Fix package init and void return functions for strand scheduler
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Scheduler.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  stdlib/jvm/src/main/ballerina/jvm/types.bal
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/methodvisitor/VisitInvokeDynamicInsn.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/types.bal
Labels: Component/jBallerina

#15004 Enable basic object test cases
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BUnionType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#15025 Fix CodeLenses not visible when if condition is in source
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/EndpointFindVisitor.java
Labels: Component/LanguageServer, Severity/Critical, Type/Bug

#15026 Add APIs for runtime value creation at JVM side
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ValueCreator.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
Labels: Component/jBallerina, Type/New Feature

#15040 Add --siddhiruntime flag to build command
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/BuilderUtils.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/PushUtils.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
Labels: Component/BVM, Component/Compiler, Type/Bug

#15018 Fix self referencing records and objects types
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/errors.bal
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/objects.bal
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/types.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#15051 Add Wait instruction support
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Scheduler.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FutureValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/types.bal
Labels: Component/jBallerina

#15045 Discontinue using BOM method for Gradle dependency management
  bvm/ballerina-runtime/build.gradle
  gradle/javaProject.gradle
  gradle/wrapper/gradle-wrapper.properties
  misc/ballerina-maven-plugins/docerina-maven-plugin/build.gradle
  misc/openapi-ballerina/modules/ballerina-client-generator/build.gradle
  misc/openapi-ballerina/modules/ballerina-to-openapi-generator/build.gradle
  stdlib/messaging/activemq-artemis/build.gradle
  stdlib/nats/build.gradle
  stdlib/test-common/build.gradle
  tests/ballerina-compiler-plugin-test/build.gradle
  tests/ballerina-integration-test/build.gradle
  tests/ballerina-test-utils/build.gradle
  tests/ballerina-tools-integration-test/build.gradle
  tests/ballerina-unit-test/build.gradle
Labels: Component/Build

#15082 Add BIR gen for anonymous functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
Labels: Component/jBallerina, Type/New Feature

#14973 Introduce meaningful sub types to BType category in suggestions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/Compiler.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/BTypeCompletionItemBuilder.java
  language-server/modules/langserver-core/src/test/resources/completion/function/completionAfterIf1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionAfterIf2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionBeforeIfElse.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionBeforeWhile.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinElse.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinElseIf.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinIf.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinTransactionOnRetry.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinWhile.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinWorkersInResource.json
  language-server/modules/langserver-core/src/test/resources/completion/function/emptyLinePrimitiveDataTypes.json
  language-server/modules/langserver-core/src/test/resources/completion/function/functionCompletionWithMissingImport.json
  language-server/modules/langserver-core/src/test/resources/completion/function/functionPointerAsParameter.json
  language-server/modules/langserver-core/src/test/resources/completion/function/importPackagesEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/function/importPackagesNonEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions10.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions5.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions6.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions7.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions8.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions9.json
  language-server/modules/langserver-core/src/test/resources/completion/function/nonEmptyLinePrimitiveDataTypes.json
  language-server/modules/langserver-core/src/test/resources/completion/function/objectAttachFunctionImpl1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/objectAttachFunctionImpl2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/suggestionsInWorkersWithinFunction.json
  language-server/modules/langserver-core/src/test/resources/completion/function/typeguardDestruct1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/userDefinedRecordEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/function/userDefinedRecordNonEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/object/objectTest1.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/allVisibleSymbolsEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/allVisibleSymbolsNonEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore1.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore3.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/emptyLinePrimitiveDataTypes.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/userDefinedFunctionsEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/userDefinedFunctionsNonEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/userDefinedRecordEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/userDefinedRecordNonEmptyLine.json
  language-server/modules/langserver-core/src/test/resources/completion/service/serviceBodyCompletion1.json
  language-server/modules/langserver-core/src/test/resources/completion/service/serviceBodyCompletion2.json
  language-server/modules/langserver-core/src/test/resources/completion/service/serviceBodyCompletion5.json
  language-server/modules/langserver-core/src/test/resources/completion/service/serviceEndpointBind3.json
  language-server/modules/langserver-core/src/test/resources/completion/service/serviceEndpointBind4.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/allTopLevelItemSkip.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/globalVarDefPackageContent.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/recordTest1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/recordTest2.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelCompletionAfterDocumentation.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelCompletionAfterFinalKeyword1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelCompletionAfterFinalKeyword2.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelCompletionAfterListenerKeyword1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelCompletionAfterListenerKeyword2.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelCompletionAfterListenerKeyword3.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelEmptyFirstLine.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelNonEmptyFirstLine.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelPackageContentAccess.json
Labels: Component/LanguageServer, Type/Improvement

#14929 Move CompletionContext classes into a single enum
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/LSDefaultCompletionItemProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/BLangAnnotationAttachmentContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/BLangMatchContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/BLangMatchExpressionContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/BLangRecordContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/BLangRecordLiteralContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/BlockStatementContextContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/CompletionItemsContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/FunctionContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/ObjectTypeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/PackageNameContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/ParameterContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/ResourceContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/ServiceContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/StatementContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/TopLevelContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/EndpointDeclarationContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleAnnotationAttachmentContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleAssignmentStatementContextContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleAttachmentPointContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleConditionalClauseContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleDefinitionContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleExpressionContextContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleFunctionDefinitionContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleGlobalVariableDefinitionContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleMatchStatementContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRulePanicStatementContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleReturnStatementContextContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleServiceDefinitionContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleServiceEndpointAttachmentContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleStatementContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleTriggerWorkerContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleVariableDefinitionStatementContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleWorkerInteractionContextContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/resolvers/parsercontext/ParserRuleWorkerReplyContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/CompletionItemResolver.java
Labels: Component/LanguageServer, Type/Improvement

#15122 Update README with gradle build instructions
  README.md
Labels: Type/Docs

#15118 Fix Test Generation Tests
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/source/testgen/module1/functions.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/source/testgen/module2/services.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/testGenFunctionCodeAction.json
  language-server/modules/langserver-core/src/test/resources/command/source/testgen/module1/functions.bal
  language-server/modules/langserver-core/src/test/resources/command/testGenerationForFunctions.json
Labels: Component/LanguageServer, Type/Improvement

#15121 Disable failing vscode tests
  gradle.properties
  tool-plugins/vscode/build.gradle
  tool-plugins/vscode/test/language-server/lang-client.test.ts
Labels: Component/VScode plugin

#15123 Support positions info and source file name to code generation
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BLangVMErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/services/ErrorHandlerUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_error_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/main.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompiledPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangRecordLiteral.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/jvm/src/main/ballerina/jvm/types.bal
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/classwriter/VisitSource.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/methodvisitor/VisitLineNumber.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BFileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/CompileResult.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/TestConstant.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/jvm/JBallerinaInMemoryClassLoader.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ModuleTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/Ballerina.toml
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/module-test.bal
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/test.math/complexOp.bal
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/test.math/simpleOp.bal
Labels: Component/jBallerina, Type/New Feature

#15077 Add abstract object support to jballerina
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina, Type/Task

#15139 Add requested formatting guideline changes
  docs/style_guide/README.md
  docs/style_guide/definitions.md
  docs/style_guide/expressions.md
  docs/style_guide/operators_keywords_and_types.md
  docs/style_guide/statements.md
Labels: Component/Formatting, Type/Docs

#15135 Fix typecast issue with error
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BRecordType.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
Labels: Component/jBallerina, Type/Improvement

#15151 Skip extern function from jvm codegen
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/Compiler.java
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
Labels: Component/jBallerina, Type/Task

#15154 Support Ballerina run command to run jar files
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ProjectDirConstants.java
  tests/ballerina-tools-integration-test/src/test/java/org/ballerinalang/test/run/JarRunFunctionPositiveTestCase.java
  tests/ballerina-tools-integration-test/src/test/resources/run/jar/test_main_for_jvm_target.bal
Labels: Component/jBallerina, Type/NewFeature

#15063 Add basic xml support to jballerina
  bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BTypes.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BXMLAttributesType.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/TypeConstants.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/TypeTags.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BXMLAttributes.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BXMLQName.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/persistence/Serializer.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLFactory.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLQName.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/types/TypeKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/TypeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLAttributesType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeTags.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
  tests/ballerina-test-utils/build.gradle
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/sampleXML.txt
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/xml-literals-with-namespaces.bal
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/xml.bal
Labels: Component/jBallerina, Type/NewFeature

#15169 Add requested changes to formatting guide
  docs/style_guide/README.md
  docs/style_guide/annotations_documentation_and_comments.md
  docs/style_guide/definitions.md
  docs/style_guide/operators_keywords_and_types.md
Labels: Component/Formatting

#15177 Fix Object type not suggested for constrained maps
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/subproviders/parsercontext/ParserRuleGlobalVariableDefinitionCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/TopLevelNodeCompletionTest.java
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/mapTest1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/source/mapTest1.bal
Labels: Component/LanguageServer, Type/Bug

#15178 Requested changes from the final review of the formatting guide
  docs/style_guide/README.md
  docs/style_guide/definitions.md
  docs/style_guide/expressions.md
  docs/style_guide/operators_keywords_and_types.md
  docs/style_guide/statements.md
Labels: Component/Formatting

#15174 Formatting tool fixes to close the gap between tool and guide
  CHANGELOG.md
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingNodeTree.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingSourceGen.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/arrayLiteralExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/bindingPatterns.bal
  language-server/modules/langserver-core/src/test/resources/formatting/blockExpandOnDemand.bal
  language-server/modules/langserver-core/src/test/resources/formatting/constrainedType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/documentation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/errorConstructor.bal
  language-server/modules/langserver-core/src/test/resources/formatting/errorType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/errorVariableDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedArrayLiteralExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedAsyncExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedBindingPatterns.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedBlockExpandOnDemand.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedConstrainedType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedDocumentation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorVariableReference.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFunction.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedImportOrder.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedIndexBasedAccess.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedLock.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedMatchStmt.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedRecordLiteralExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedReturn.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTable.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTableQuery.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTernaryExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTrap.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTupleType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTypeGuard.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedUnionType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedWait.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedWorkerInteractions.bal
  language-server/modules/langserver-core/src/test/resources/formatting/function.bal
  language-server/modules/langserver-core/src/test/resources/formatting/importOrder.bal
  language-server/modules/langserver-core/src/test/resources/formatting/indexBasedAccess.bal
  language-server/modules/langserver-core/src/test/resources/formatting/matchStmt.bal
  language-server/modules/langserver-core/src/test/resources/formatting/recordLiteralExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/return.bal
  language-server/modules/langserver-core/src/test/resources/formatting/table.bal
  language-server/modules/langserver-core/src/test/resources/formatting/tableQuery.bal
  language-server/modules/langserver-core/src/test/resources/formatting/ternaryExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/trap.bal
  language-server/modules/langserver-core/src/test/resources/formatting/tupleType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/unionType.bal
Labels: Component/Formatting

#15161 Add function pointer support for jBallerina
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/AnonymousFunctionsTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/anon-funcs.bal
Labels: Component/jBallerina, Type/Improvement
