Repository ballerina-platform/ballerina-lang, pull requests merged in 2019-07, with the labels that each got.

#16091 Fix native lambda invocation
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/BuilderUtils.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BootstrapRunner.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersTest.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#16011 Add Quick Fix Code Actions for Resolving Functions Related Issues in Objects
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/ChangeAbstractTypeObjExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CommandExecutionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/changeAbstractTypeObj1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/changeAbstractTypeObj2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/source/changeAbstractType.bal
  language-server/modules/langserver-core/src/test/resources/command/changeAbstractTypeObj1.json
  language-server/modules/langserver-core/src/test/resources/command/changeAbstractTypeObj2.json
  language-server/modules/langserver-core/src/test/resources/command/source/changeAbstractType.bal
Labels: Area/Tooling, Component/LanguageServer, Type/NewFeature

#16122 Fix nested loops termination issue
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/foreach/NestedForeachTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/whilestatement/WhileStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/foreach/nested-foreach.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/whilestatement/while-stmt.bal
Labels: Component/jBallerina

#16125 Fix windows build for gradle in jBallerina branch
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BootstrapRunner.java
  distribution/bootstrapper/src/main/resources/ballerina.bat
  gradle/baloProject.gradle
  gradle/birProject.gradle
Labels: Component/jBallerina

#16140 Revert adding no cache build for travis
  .travis.yml
Labels: Component/jBallerina

#16138 Fix printing null value in main
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
Labels: Component/jBallerina

#16132 Enable integration test framework
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/BLangConstants.java
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/util/BFileUtil.java
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/util/JBallerinaInMemoryClassLoader.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/ballerina-test-utils/build.gradle
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#16015 Update api doc generator to reflect tuple syntax change
  misc/docerina/src/main/java/org/ballerinalang/docgen/Writer.java
Labels: Area/Tooling

#16093 Improve Ballerina SQL error
  stdlib/database/h2/src/main/ballerina/h2/endpoint.bal
  stdlib/database/h2/src/test/java/org/ballerinalang/stdlib/database/sql/SQLActionsTest.java
  stdlib/database/h2/src/test/resources/test-src/h2/h2_actions_test.bal
  stdlib/database/h2/src/test/resources/test-src/sql/sql_actions_negative_test.bal
  stdlib/database/h2/src/test/resources/test-src/sql/sql_actions_test.bal
  stdlib/database/mysql/src/main/ballerina/mysql/endpoint.bal
  stdlib/database/sql/src/main/ballerina/sql/abstract_endpoint.bal
  stdlib/database/sql/src/main/ballerina/sql/endpoint.bal
  stdlib/database/sql/src/main/ballerina/sql/types.bal
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/Constants.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/SQLDataIterator.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/SQLDatasource.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/SQLDatasourceUtils.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/actions/BatchUpdate.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/actions/Call.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/actions/Close.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/actions/Select.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/actions/Update.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/exceptions/ApplicationException.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/exceptions/DatabaseException.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/statement/AbstractSQLStatement.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/statement/BatchUpdateStatement.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/statement/CallStatement.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/statement/SelectStatement.java
  stdlib/database/sql/src/main/java/org/ballerinalang/database/sql/statement/UpdateStatement.java
Labels: Area/StandardLibs

#16133 Refactor System module for JBallerina
  stdlib/system/src/main/ballerina/system/file_info.bal
  stdlib/system/src/main/ballerina/system/system.bal
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Copy.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/CreateDir.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/CreateFile.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Exists.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetCurrentDirectory.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetEnv.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetFileInfo.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUserHome.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUsername.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/ReadDir.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Remove.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Rename.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/TempDir.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Uuid.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/utils/SystemConstants.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/utils/SystemUtils.java
  stdlib/system/src/test/java/org/ballerinalang/stdlib/system/FileSystemTest.java
  stdlib/system/src/test/resources/test-src/file-system-test.bal
  stdlib/system/src/test/resources/test-src/system-test.bal
Labels: Area/StandardLibs, Component/System

#16144 Fix and enable variabledef stmt tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/VariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/global-var-order.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/globalcycle/simple/file01.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/globalcycle/simple/file02.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/multiFileReference/file01.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/multiFileReference/file02.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/variable-definition-stmt.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#16172 Move type-init logic to separate functions
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
Labels: Component/jBallerina

#16002 Validate in-object definitions of referenced functions
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/Symbols.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  stdlib/jms/src/main/ballerina/jms/durable_topic_subscriber.bal
  stdlib/jms/src/main/ballerina/jms/queue_receiver.bal
  stdlib/jms/src/main/ballerina/jms/topic_subscriber.bal
  stdlib/messaging/activemq-artemis/src/main/ballerina/artemis/listener.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel_listener.bal
  stdlib/nats/src/main/ballerina/nats/consumer/listener.bal
  stdlib/observability/build.gradle
  stdlib/observability/src/test/java/org/ballerinalang/observe/CounterTest.java
  stdlib/observability/src/test/java/org/ballerinalang/observe/RegistryTest.java
  tests/ballerina-integration-test/src/test/resources/websub/test_custom_subscribers.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTypeReferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/endpoint/new/service_multiple.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_func_reference_neg.bal
Labels: Area/Language

#16169 Fix formatting support for service attached expr
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/ServiceConstructorNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangServiceConstructorExpr.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/sourcegen/FormattingSourceGen.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedService.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedServiceConstruct.bal
  language-server/modules/langserver-core/src/test/resources/formatting/service.bal
  language-server/modules/langserver-core/src/test/resources/formatting/serviceConstruct.bal
Labels: Area/Tooling, Component/Formatting

#15964 Enable CodeAction Tests
  language-server/modules/langserver-core/build.gradle
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/source/fixReturnType.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/source/testgen/module1/functions.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/source/testgen/module2/services.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Area/Tooling, Component/LanguageServer

#16086 Refactor Time module for JBallerina
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/AbstractTimeFunction.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/AddDuration.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/CreateTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/CurrentTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Day.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Format.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/GetDate.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/GetTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Hour.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/MilliSecond.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Minute.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Month.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/NanoTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Parse.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Second.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/SubtractDuration.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/ToString.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/ToTimeZone.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/WeekDay.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Year.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/util/TimeUtils.java
Labels: Area/StandardLibs, Component/Time

#16182 include kid in JWT Header
  stdlib/jwt/src/main/ballerina/jwt/jwt_issuer.bal
Labels: Area/StandardLibs, Component/JWT, Type/Bug

#16176 Fix tuple syntax for match-stmt tests
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_error_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_match_patterns_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_match_patterns_unreachable_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_record_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_tuple_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/unreachable_static_match_patterns_negative.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#16199 Add starting up capability for observability at the start of a program
  bvm/ballerina-runtime/build.gradle
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/launch/LaunchUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/observability/metrics/MetricsLaunchListener.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/observability/metrics/noop/NoOpMetricProvider.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/observability/metrics/noop/NoOpMetricReporter.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/observability/tracer/TracingLaunchListener.java
  bvm/ballerina-runtime/src/main/resources/META-INF/services/org.ballerinalang.jvm.launch.LaunchListener
  bvm/ballerina-runtime/src/main/resources/META-INF/services/org.ballerinalang.jvm.observability.metrics.spi.MetricProvider
  bvm/ballerina-runtime/src/main/resources/META-INF/services/org.ballerinalang.jvm.observability.metrics.spi.MetricReporter
  cli/ballerina-launcher/build.gradle
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  misc/metrics-extensions/modules/ballerina-metrics-extension/src/main/java/org/ballerinalang/observe/metrics/extension/defaultimpl/DefaultMetricProvider.java
  misc/metrics-extensions/modules/ballerina-metrics-extension/src/main/resources/META-INF/services/org.ballerinalang.jvm.observability.metrics.spi.MetricProvider
  misc/metrics-extensions/modules/ballerina-prometheus-extension/src/main/resources/META-INF/services/org.ballerinalang.jvm.observability.metrics.spi.MetricReporter
  misc/tracing-extensions/modules/ballerina-jaeger-extension/build.gradle
  misc/tracing-extensions/modules/ballerina-jaeger-extension/src/main/java/org/ballerinalang/observe/trace/extension/jaeger/OpenTracingExtension.java
  misc/tracing-extensions/modules/ballerina-jaeger-extension/src/main/resources/META-INF/services/org.ballerinalang.jvm.observability.tracer.OpenTracer
Labels: Component/jBallerina

#16008 Implement toString() for values
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FPValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FutureValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/IteratorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/lang.value/src/main/ballerina/lang.value/value.bal
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/ToString.java
Labels: Area/Language, Component/Compiler, Type/SpecDeviation

#16001 Implement cloneReadOnly function
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FPValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FutureValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/IteratorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/RefValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLAttributes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLQName.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  langlib/lang.value/src/main/ballerina/lang.value/value.bal
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/Clone.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneAsReadOnly.java
Labels: Area/Language, Component/Compiler, Type/SpecDeviation

#16208 Fix TableTest issues in jballerina
  tests/jballerina-unit-test/build.gradle
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_nillable_mapping.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_to_json_service_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_type.bal
Labels: Area/StandardLibs, Component/Data, Type/Task

#16230 Support default arguments in Ballerina external functions
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_desugar_phase.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_external_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
Labels: Component/jBallerina

#16233 Change delimited identifiers syntax
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  tests/ballerina-spec-conformance-tests/S05_structured_values/tests/mappings/records/record_field_types.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/IdentifierLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/debugger/test_identifier_literals.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-service.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-success.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-undefined-variable-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-wrong-character-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/pkg.main/identifier-literal-pkg.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/pkg.variable/variable-def.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/map/constrained-map.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal
Labels: Area/Language, Type/GrammarDeviation

#16209 Fix LS signature help does not work for unclosed parenthesis
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureTreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/sourceprune/AbstractTokenTraverser.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/sourceprune/LHSTokenTraverser.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/annotations/AnnotationAttachmentsCompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/FunctionDefinitionCompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/signature/SignatureHelpTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/sourceprune/SourcePruneTest.java
  language-server/modules/langserver-core/src/test/resources/signature/signatureWithinAnnotation.json
  language-server/modules/langserver-core/src/test/resources/signature/source/functionInSameFile.bal
  language-server/modules/langserver-core/src/test/resources/signature/source/signatureWithinAnnotations.bal
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#16248 Fix and enable match stmt tests
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTupleType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangConstantValue.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/NumericConversionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredRecordPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/BJSONValueTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_error_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_match_patterns_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_match_patterns_unreachable_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/jsontype/json-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#16249 Sync auth integration tests
  tests/jballerina-integration-test/src/test/resources/auth/authservices/01_authn_config_inheritance_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/02_authz_config_inheritance_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/03_resource_level_auth_config_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/04_service_level_auth_config_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/05_auth_test_without_annotations_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/06_authn_with_multiple_handlers.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/07_authz_with_cache_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/08_authn_with_expired_certificate_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/09_authn_with_expired_certificate_with_no_expiry_validation.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/10_token_propagation_disabled_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/11_token_propagation_basic_auth_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/12_token_propagation_jwt_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/13_token_propagation_jwt_reissuing_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/14_token_propagation_jwt_reissuing_negative_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/15_ldap_auth_store_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/16_ldap_auth_store_authz_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/17_auth_with_custom_providers_handlers.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/18_oauth2_client_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/19_authn_config_pattern_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/20_authz_config_pattern_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/21_authn_with_oauth2_test.bal
Labels: Area/StandardLibs, Type/Improvement

#16116 Socket module migration to JBallerina
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Register.java
  stdlib/ldap/pom.xml
  stdlib/mime/pom.xml
  stdlib/socket/build.gradle
  stdlib/socket/src/main/ballerina/socket/client_socket.bal
  stdlib/socket/src/main/ballerina/socket/udp_client_socket.bal
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Close.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/InitEndpoint.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Read.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/ShutdownRead.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/ShutdownWrite.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Start.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Write.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/InitServer.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/Register.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/Start.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/Stop.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/Close.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/InitEndpoint.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/ReceiveFrom.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/SendTo.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/ChannelRegisterCallback.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/ReadPendingCallback.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SelectorDispatcher.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SelectorManager.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SocketService.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SocketUtils.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/TCPSocketCallback.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/TCPSocketReadCallback.java
  stdlib/socket/src/test/java/org/ballerinalang/stdlib/socket/ClientSocketTest.java
  stdlib/socket/src/test/java/org/ballerinalang/stdlib/socket/ClientUdpSocketTest.java
  stdlib/socket/src/test/java/org/ballerinalang/stdlib/socket/MockSocketServer.java
  stdlib/socket/src/test/java/org/ballerinalang/stdlib/socket/ServerSocketTest.java
  stdlib/socket/src/test/resources/test-src/client_socket.bal
  stdlib/socket/src/test/resources/test-src/server_socket.bal
  stdlib/socket/src/test/resources/test-src/udp_client_socket.bal
  stdlib/socket/src/test/resources/testng.xml
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/BaloCreator.java
  tool-plugins/vscode/package-lock.json
  tool-plugins/vscode/package.json
Labels: Area/StandardLibs, Component/jBallerina

#16281 File Listener cleanup for JBallerina
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/DirectoryCallback.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/DirectoryListenerCallback.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/FSListener.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/InitEndpoint.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Register.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Start.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/utils/FileUtils.java
  stdlib/file/src/test/java/org/ballerinalang/stdlib/file/DirectoryListenerConnectorTest.java
Labels: Area/StandardLibs, Component/jBallerina

#16174 Update the data type of JWT audience
  examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.bal
  examples/secured-service-with-jwt/secured_service_with_jwt.bal
  stdlib/jwt/src/main/ballerina/jwt/Module.md
  stdlib/jwt/src/main/ballerina/jwt/jwt_common.bal
  stdlib/jwt/src/main/ballerina/jwt/jwt_issuer.bal
  stdlib/jwt/src/main/ballerina/jwt/jwt_validator.bal
  stdlib/jwt/src/test/java/org.ballerinalang.stdlib.jwt/JwtIssuerAndValidatorTest.java
  stdlib/jwt/src/test/resources/test-src/jwt-auth-provider-test.bal
  stdlib/jwt/src/test/resources/test-src/jwt-issuer-and-validator-test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/06_authn_with_multiple_handlers.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/07_authz_with_cache_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/08_authn_with_expired_certificate_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/09_authn_with_expired_certificate_with_no_expiry_validation.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/10_token_propagation_disabled_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/11_token_propagation_basic_auth_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/12_token_propagation_jwt_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/13_token_propagation_jwt_reissuing_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/14_token_propagation_jwt_reissuing_negative_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/19_authn_config_pattern_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/06_authn_with_multiple_handlers.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/07_authz_with_cache_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/08_authn_with_expired_certificate_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/09_authn_with_expired_certificate_with_no_expiry_validation.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/10_token_propagation_disabled_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/19_authn_config_pattern_test.bal
Labels: Area/StandardLibs, Component/JWT, Type/Improvement

#16311 Fix error type symbol not appearing due to error constructor change
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FilterUtils.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/BTypeCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/contextproviders/InvocationArgsContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/ObjectTypeNodeScopeProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/RecordTypeNodeScopeProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/spi/LSCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/index/DTOUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/index/dataholder/BLangPackageContent.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/index/tools/IndexGenerator.java
  language-server/modules/langserver-core/src/test/resources/completion/function/completionAfterIf1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionAfterIf2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionAfterReturn.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionBeforeIfElse.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionBeforeWhile.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinElse.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinElseIf.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinIf.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinTransaction.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinTransactionOnRetry.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinWhile.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinWorkersInResource.json
  language-server/modules/langserver-core/src/test/resources/completion/function/emptyLineCompletion.json
  language-server/modules/langserver-core/src/test/resources/completion/function/ifWhileConditionContextCompletion1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/ifWhileConditionContextCompletion2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/ifWhileConditionContextCompletion5.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions10.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions5.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions6.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions7.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions8.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions9.json
  language-server/modules/langserver-core/src/test/resources/completion/function/nonEmptyLineCompletion.json
  language-server/modules/langserver-core/src/test/resources/completion/function/panicStatementErrorSuggestions.json
  language-server/modules/langserver-core/src/test/resources/completion/function/suggestionsInWorkersWithinFunction.json
  language-server/modules/langserver-core/src/test/resources/completion/function/typeguardDestruct1.json
  language-server/modules/langserver-core/src/test/resources/completion/object/objectTest1.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore3.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/emptyLineCompletion.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/nonEmptyLineCompletion.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/allTopLevelItemSkip.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/mapTest1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/recordTest1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/recordTest2.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelCompletionAfterDocumentation.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelEmptyFirstLine.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelNonEmptyFirstLine.json
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#16320 Fix windows gradle build issues
  distribution/zip/jballerina/bin/jballerina.bat
  gradle/birProject.gradle
Labels: Component/jBallerina

#16272 Add TLS support for RabbitMQ connection
  stdlib/messaging/rabbitmq/build.gradle
  stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/rabbitmq_commons.bal
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/RabbitMQConstants.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/Start.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java
Labels: Area/StandardLibs, Component/Messaging

#16361 Exclude JBallerina intermittent failing test class
  .travis.yml
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserPositiveTest.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAllActionsTest.java
Labels: Area/Language

#16419 Disable JBallerina ArgumentParserPositiveTest
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserPositiveTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserPositiveTest.java
Labels: Area/Language, Type/Bug

#16301 Fix union of arrays declaration issue
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayFillTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/arraysofarrays/ArraysOfArraysTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-fill-test-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-fill-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/arraysofarrays/arrays-of-arrays.bal
Labels: Area/Language

#16359 Fix blockedList accumulation in Scheduler
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Scheduler.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Strand.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#16344 Refactor Crypto and Encoding Modules
  stdlib/crypto/src/main/ballerina/crypto/crypto.bal
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/CryptoUtils.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecodePrivateKey.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecodePublicKey.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecryptRsaEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/EncryptRsaEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaMd5.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha1.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha256.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha384.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha512.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaMd5Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha1Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha256Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha384Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha512Signature.java
  stdlib/crypto/src/test/java/org/ballerinalang/stdlib/crypto/CryptoTest.java
  stdlib/crypto/src/test/java/org/ballerinalang/stdlib/crypto/KeyParsingTest.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/EncodingUtil.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/ByteArrayToString.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/DecodeBase64.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/DecodeBase64Url.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/DecodeHex.java
  stdlib/encoding/src/test/java/org/ballerinalang/stdlib/encoding/EncodingTest.java
Labels: Area/StandardLibs, Component/Crypto, Component/Encoding, Type/Improvement

#16358 Refactor and enable auth integration tests
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthWithCustomProvidersHandlersTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnConfigPatternTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnWithOAuth2Test.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthzConfigPatternTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/TokenPropagationTest.java
  tests/jballerina-integration-test/src/test/resources/auth/authservices/10_token_propagation_disabled_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/11_token_propagation_basic_auth_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/12_token_propagation_jwt_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/13_token_propagation_jwt_reissuing_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/14_token_propagation_jwt_reissuing_negative_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/17_auth_with_custom_providers_handlers.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/17_authn_with_custom_handlers.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#16473 [WIP]Update stdlib with new syntax
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/basics/ServiceTest.java
  stdlib/http/src/test/resources/test-src/services/echo-service.bal
  stdlib/oauth2/build.gradle
  stdlib/oauth2/src/main/ballerina/oauth2/inbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/oauth2/outbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/oauth2/utils.bal
  stdlib/observability/build.gradle
  stdlib/socket/build.gradle
  stdlib/socket/src/main/ballerina/socket/listener_endpoint.bal
  stdlib/socket/src/test/resources/test-src/client_socket.bal
  stdlib/socket/src/test/resources/test-src/server_socket.bal
  stdlib/socket/src/test/resources/test-src/udp_client_socket.bal
  stdlib/streams/build.gradle
  stdlib/streams/src/main/ballerina/streams/aggregator/distinct-count-aggregator.bal
  stdlib/streams/src/main/ballerina/streams/pattern/and-operator-processor.bal
  stdlib/streams/src/main/ballerina/streams/pattern/compound-pattern-processor.bal
  stdlib/streams/src/main/ballerina/streams/pattern/followed-by-processor.bal
  stdlib/streams/src/main/ballerina/streams/pattern/not-operator-processor.bal
  stdlib/streams/src/main/ballerina/streams/pattern/or-operator-processor.bal
  stdlib/streams/src/main/ballerina/streams/processor/order-by-processor.bal
  stdlib/streams/src/main/ballerina/streams/processor/output-processor.bal
  stdlib/streams/src/main/ballerina/streams/processor/select-processor.bal
  stdlib/streams/src/main/ballerina/streams/processor/stream-join-processor.bal
  stdlib/streams/src/main/ballerina/streams/processor/table-join-processor.bal
  stdlib/streams/src/main/ballerina/streams/util/collections.bal
  stdlib/streams/src/main/ballerina/streams/util/scheduler.bal
  stdlib/streams/src/main/ballerina/streams/util/snapshot.bal
  stdlib/streams/src/main/ballerina/streams/util/stream-event.bal
  stdlib/streams/src/main/ballerina/streams/window/delay-window.bal
  stdlib/streams/src/main/ballerina/streams/window/external-time-batch-window.bal
  stdlib/streams/src/main/ballerina/streams/window/hopping-window.bal
  stdlib/streams/src/main/ballerina/streams/window/length-batch-window.bal
  stdlib/streams/src/main/ballerina/streams/window/sort-window.bal
  stdlib/streams/src/main/ballerina/streams/window/time-accumulating-window.bal
  stdlib/streams/src/main/ballerina/streams/window/time-batch-window.bal
  stdlib/streams/src/main/ballerina/streams/window/time-length-window.bal
  stdlib/streams/src/main/ballerina/streams/window/unique-length-window.bal
Labels: Area/StandardLibs

#16496 Fix worker action syntax error
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Area/Language

#16390 Remove Channel syntax
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompiledPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BBuiltInRefType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BChannelType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeTags.java
  examples/channels-correlation/channels_correlation.bal
  examples/channels-correlation/channels_correlation.client.out
  examples/channels-correlation/channels_correlation.description
  examples/channels-correlation/channels_correlation.server.out
  examples/channels-correlation/tests/channels_correlation_test.bal
  examples/channels-workers/channels_workers.bal
  examples/channels-workers/channels_workers.description
  examples/channels-workers/channels_workers.out
  examples/channels-workers/tests/channels_workers_test.bal
  examples/index.json
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/channel/ChannelsResourcesTest.java
  tests/jballerina-integration-test/src/test/resources/channels/channel-service.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/channels/BasicChannelsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/channels/ChannelsDBTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/channels/ChannelsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ExperimentalFeaturesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/channels/channel-in-resources.bal
  tests/jballerina-unit-test/src/test/resources/test-src/channels/channel-negative-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/channels/channel-worker-interactions.bal
Labels: Area/Language, Component/Compiler

#16405 Add type guard code action for the function invocations
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateVariableExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/BFunctionCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/ReferencesUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/SymbolReferenceFindingVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/SymbolReferencesModel.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/source/typeGuard.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/typeGuardCodeAction1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/typeGuardCodeAction2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/typeGuardCodeAction3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/typeGuardCodeAction4.json
Labels: Area/Tooling, Component/LanguageServer, Type/NewFeature

#16470 Add test cases for map lib functions
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/utils/ArrayUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/utils/GetFunction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Enumerate.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Filter.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/ForEach.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/IndexOf.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Map.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Pop.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Push.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Reduce.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Remove.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Reverse.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Shift.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Slice.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Sort.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Unshift.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Entries.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Filter.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/ForEach.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Map.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Reduce.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibMapTest.java
  langlib/langlib-test/src/test/resources/test-src/maplib_test.bal
  langlib/langlib-test/src/test/resources/testng.xml
  stdlib/utils/build.gradle
Labels: Area/Language

#16512 Disable auth integration tests and fix an IO unit test
  tests/jballerina-integration-test/src/test/resources/auth/authservices/08_authn_with_expired_certificate_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/17_auth_with_custom_providers_handlers.bal
  tests/jballerina-integration-test/src/test/resources/auth/authservices/21_authn_with_oauth2_test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/connectors/character-io-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/connectors/character-io.bal
Labels: Area/StandardLibs, Component/Auth

#16442 Introduce new semantic changes from the spec R2 to foreach loop
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/BLangBuiltInMethod.java
  langlib/lang.array/src/main/ballerina/lang.array/array.bal
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java
  langlib/lang.map/src/main/ballerina/lang.map/map.bal
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Next.java
  langlib/lang.string/build.gradle
  langlib/lang.string/src/main/ballerina/lang.string/string.bal
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/Next.java
  langlib/lang.table/src/main/ballerina/lang.table/table.bal
  langlib/lang.table/src/main/java/org/ballerinalang/langlib/table/Next.java
  langlib/lang.xml/src/main/ballerina/lang.xml/xml.bal
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Next.java
  langlib/langlib-test/build.gradle
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachArrayTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachArrayTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachComplexTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachErrorBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachJSONTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachJSONTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachMapTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachMapTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachNegativeTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachRecordTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachStringTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachTableTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachTupleTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachXMLTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachXMLTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/NestedForeachTest.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-arrays-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-arrays.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-complex.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-json-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-json.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-maps-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-maps.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-negative.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-record-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-string-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-table-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-xml-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-xml.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_errors.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_errors_negative.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_tuples.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_tuples_negative.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/nested-foreach.bal
  langlib/langlib-test/src/test/resources/testng.xml
  stdlib/io/src/test/java/org/ballerinalang/stdlib/io/IOPrintTest.java
  stdlib/messaging/activemq-artemis/src/main/ballerina/artemis/connection.bal
Labels: Area/Language, Component/Compiler, Type/SpecDeviation

#16410 Improve query param access
  examples/query-path-matrix-param/query_path_matrix_param.bal
  examples/websocket-chat-application/websocket_chat_application.bal
  stdlib/http/src/main/ballerina/http/http_request.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/request/GetQueryParams.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/URIUtil.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/dispatching/UriTemplateBestMatchTest.java
  stdlib/http/src/test/resources/test-src/services/dispatching/uri-matrix-param-matching.bal
  stdlib/http/src/test/resources/test-src/services/dispatching/uri-template-matching.bal
  stdlib/http/src/test/resources/test-src/services/dispatching/uri-template.bal
  stdlib/websub/src/main/ballerina/websub/commons.bal
  stdlib/websub/src/main/ballerina/websub/hub_service.bal
  tests/ballerina-integration-test/src/test/resources/http/httpservices/11_http_redirects.bal
  tests/ballerina-integration-test/src/test/resources/http2/http2services/02_http_2.0_redirect.bal
  tests/ballerina-integration-test/src/test/resources/websocket/wsservices/14_query_and_path_param_support.bal
  tests/ballerina-integration-test/src/test/resources/websocket/wsservices/15_resource_failure.bal
  tests/ballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/http-service.bal
  tests/ballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/service-level-variables-negative.bal
  tests/jballerina-integration-test/src/test/resources/http/httpservices/11_http_redirects.bal
  tests/jballerina-integration-test/src/test/resources/http2/http2services/02_http_2.0_redirect.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/14_query_and_path_param_support.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/15_resource_failure.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/http-service.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/listener-taintedness-propagation-tainted-listener.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/listener-taintedness-propagation-untainted-listener.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/service-level-variables-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/service-level-variables.bal
Labels: Area/StandardLibs, Component/HTTP, Type/Bug, Type/Improvement

#16397 Add a doc comment for newly introduced function
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java
Labels: Area/StandardLibs

#16499 Remove loadToMemory option in jdbc select remote function
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.bal
  stdlib/jdbc/src/main/ballerina/jdbc/Module.md
  stdlib/jdbc/src/main/ballerina/jdbc/client_endpoint.bal
  stdlib/jdbc/src/main/ballerina/jdbc/jdbc_client.bal
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/actions/Select.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/SelectStatement.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/SQLActionsTest.java
  stdlib/jdbc/src/test/resources/test-src/sql/sql_actions_test.bal
Labels: Area/StandardLibs

#16498 Upgrade transport version
  distribution/zip/ballerina/build.gradle
  distribution/zip/jballerina/build.gradle
  gradle/javaProject.gradle
  pom.xml
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/InboundMessage.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ServerCall.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/BHttpUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/AbstractHTTPAction.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/pipelining/PipeliningHandler.java
Labels: Area/StandardLibs

#16387 Introduce ballerina-xslt module
  distribution/zip/ballerina-tools/pom.xml
  distribution/zip/ballerina/build.gradle
  distribution/zip/ballerina/pom.xml
  distribution/zip/ballerina/src/assembly/bin.xml
  distribution/zip/jballerina/build.gradle
  pom.xml
  settings.gradle
  stdlib/xslt/assembly/balo.xml
  stdlib/xslt/assembly/source.xml
  stdlib/xslt/build.gradle
  stdlib/xslt/pom.xml
  stdlib/xslt/spotbugs-exclude.xml
  stdlib/xslt/src/main/ballerina/Ballerina.toml
  stdlib/xslt/src/main/ballerina/xslt/Module.md
  stdlib/xslt/src/main/ballerina/xslt/natives.bal
  stdlib/xslt/src/main/java/org.ballerinalang.xslt/XsltTransformer.java
  stdlib/xslt/src/test/java/org/ballerinalang/xslt/XSLTTest.java
  stdlib/xslt/src/test/resources/datafiles/cd_catalog.xml
  stdlib/xslt/src/test/resources/datafiles/cd_catalog.xsl
  stdlib/xslt/src/test/resources/datafiles/cd_catalog_multi.xsl
  stdlib/xslt/src/test/resources/datafiles/source.xml
  stdlib/xslt/src/test/resources/datafiles/source.xsl
  stdlib/xslt/src/test/resources/test-src/read-from-file.bal
  stdlib/xslt/src/test/resources/testng.xml
Labels: Area/StandardLibs, Type/Task

#16529 Fix jballerina distribution dependencies issues
  distribution/zip/jballerina/build.gradle
  misc/docerina/src/main/java/org/ballerinalang/docgen/docs/BallerinaDocGenerator.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language

#16465 Update examples for Jdbc client error changes
  examples/jdbc-client-batch-update/jdbc_client_batch_update.bal
  examples/jdbc-client-call-procedures/jdbc_client_call_procedures.bal
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.bal
  examples/jdbc-streaming-big-dataset/data_setup.bal
  stdlib/jdbc/src/main/ballerina/jdbc/Module.md
  stdlib/jdbc/src/main/ballerina/jdbc/error.bal
  stdlib/jdbc/src/main/ballerina/jdbc/jdbc_types.bal
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/SQLActionsTest.java
  stdlib/jdbc/src/test/resources/test-src/sql/sql_actions_negative_test.bal
Labels: Area/StandardLibs, Component/Data

#16541 Enable jballerina unit tests in travis
  .travis.yml
Labels: Component/jBallerina

#16402 Update const type validation for annots to check only for anydata
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationDeclarationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annots_with_invalid_consts.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annots_with_invalid_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annots_with_list_consts.bal
Labels: Area/Language

#16554 Remove file APIs from internal module
  cli/ballerina-cli-utils/src/main/ballerina/packaging_pull/packaging_pull.bal
  compiler/ballerina-backend-jvm/build.gradle
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/main.bal
  stdlib/crypto/build.gradle
  stdlib/encoding/build.gradle
  stdlib/file/build.gradle
  stdlib/internal/src/main/ballerina/internal/compression.bal
  stdlib/internal/src/main/ballerina/internal/file.bal
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/Constants.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/compression/Compress.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/compression/CompressToByteArray.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/compression/Decompress.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/compression/DecompressFromByteArray.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/CopyTo.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/CreateDirectory.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/CreateFile.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/Delete.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/GetExtension.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/GetModifiedTime.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/GetName.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/GetParentDirectory.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/GetPathValue.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/Init.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/IsDirectory.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/List.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/MoveTo.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/PathExists.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/Resolve.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/file/ToAbsolutePath.java
  stdlib/internal/src/main/java/org/ballerinalang/stdlib/internal/utils/Constants.java
  stdlib/internal/src/test/java/org/ballerinalang/internal/file/InternalFileTest.java
  stdlib/internal/src/test/resources/test-src/compression/compression.bal
  stdlib/internal/src/test/resources/test-src/file/file-test.bal
  stdlib/streams/build.gradle
  stdlib/streams/src/main/ballerina/streams/util/snapshot.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/connectors/character-io-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/connectors/character-io.bal
Labels: Area/StandardLibs

#16556 Enable disabled tests
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ReadJson.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/constant/SimpleConstantAccessInBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/constant/SimpleConstantInBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/globalvar/GlobalVarFunctionInBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantInTypeDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/JSONTest.java
Labels: Component/jBallerina

#16559 Rename io:IoError to io:Error
  stdlib/file/src/test/resources/test-src/file_ops.bal
  stdlib/internal/src/test/resources/test-src/file/file-test.bal
  stdlib/io/src/main/ballerina/io/io_error.bal
  stdlib/io/src/main/ballerina/io/open.bal
  stdlib/io/src/main/ballerina/io/readable_byte_channel.bal
  stdlib/io/src/main/ballerina/io/readable_character_channel.bal
  stdlib/io/src/main/ballerina/io/readable_csv_channel.bal
  stdlib/io/src/main/ballerina/io/readable_data_channel.bal
  stdlib/io/src/main/ballerina/io/readable_record_channel.bal
  stdlib/io/src/main/ballerina/io/strings.bal
  stdlib/io/src/main/ballerina/io/writable_byte_channel.bal
  stdlib/io/src/main/ballerina/io/writable_character_channel.bal
  stdlib/io/src/main/ballerina/io/writable_csv_channel.bal
  stdlib/io/src/main/ballerina/io/writable_data_channel.bal
  stdlib/io/src/main/ballerina/io/writable_record_channel.bal
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CreateReadableDelimitedRecordChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CreateWritableDelimitedRecordChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/utils/IOConstants.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/utils/IOUtils.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/utils/Utils.java
  stdlib/io/src/test/resources/test-src/io/bytes_io.bal
  stdlib/io/src/test/resources/test-src/io/char_io.bal
  stdlib/io/src/test/resources/test-src/io/csv_io.bal
  stdlib/io/src/test/resources/test-src/io/data_io.bal
  stdlib/io/src/test/resources/test-src/io/record_io.bal
  stdlib/socket/src/test/resources/test-src/client_socket.bal
  stdlib/socket/src/test/resources/test-src/server_socket.bal
  stdlib/socket/src/test/resources/test-src/udp_client_socket.bal
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/connectors/IOTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/io/csv_io.bal
  tests/ballerina-unit-test/src/test/resources/test-src/taintchecking/connectors/file-read-negative.bal
  tests/jballerina-integration-test/src/test/resources/socket/services/01_client_callback.bal
  tests/jballerina-unit-test/src/test/resources/test-src/io/csv_io.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/connectors/file-read-negative.bal
Labels: Area/StandardLibs

#16561 Rename JdbcClientError to Error
  examples/jdbc-client-batch-update/jdbc_client_batch_update.bal
  examples/jdbc-client-call-procedures/jdbc_client_call_procedures.bal
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.bal
  examples/jdbc-streaming-big-dataset/data_setup.bal
  stdlib/jdbc/src/main/ballerina/jdbc/client_endpoint.bal
  stdlib/jdbc/src/main/ballerina/jdbc/error.bal
  stdlib/jdbc/src/main/ballerina/jdbc/jdbc_client.bal
  stdlib/jdbc/src/test/resources/test-src/sql/sql_actions_negative_test.bal
Labels: Area/StandardLibs, Component/Data

#16548 Fix compilation failures and tests
  stdlib/config-api/src/test/java/org/ballerinalang/stdlib/config/EnvVarConfigTest.java
  stdlib/file/src/test/java/org/ballerinalang/stdlib/file/DirectoryListenerConnectorTest.java
  stdlib/streams/src/main/ballerina/streams/processor/output-processor.bal
  stdlib/streams/src/main/ballerina/streams/processor/select-processor.bal
  stdlib/streams/src/main/ballerina/streams/processor/stream-join-processor.bal
  stdlib/streams/src/main/ballerina/streams/util/snapshot.bal
  stdlib/streams/src/main/ballerina/streams/util/stream-event.bal
  stdlib/streams/src/main/ballerina/streams/window/unique-length-window.bal
  stdlib/time/src/test/java/org.ballerinalang.stdlib.time/TimeTest.java
Labels: Area/Language

#16238 [WIP]Add the server name in the response header
  stdlib/http/src/main/ballerina/http/service_endpoint.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/configuration/AcceptEncodingHeaderTestCase.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HTTPHeaderServerTestCase.java
  tests/ballerina-integration-test/src/test/resources/http/httpservices/02_accept_encoding_test.bal
  tests/ballerina-integration-test/src/test/resources/http/httpservices/05_echo_service.bal
  tests/ballerina-integration-test/src/test/resources/http/httpservices/28_resource_function_return.bal
  tests/ballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/configuration/AcceptEncodingHeaderTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HTTPHeaderServerTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/httpservices/02_accept_encoding_test.bal
  tests/jballerina-integration-test/src/test/resources/http/httpservices/05_echo_service.bal
  tests/jballerina-integration-test/src/test/resources/http/httpservices/28_resource_function_return.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#16571 Fix jballerina constant, ifelse, while statement unit tests
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/StartsWith.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/IfElseStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/whilestatement/while-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/map-literal-constant-as-expressions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/map-literal-constant-equality.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/map-literal-constant-panic.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/map-literal-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/Compiler, Component/UnitTest

#16570 Refactor Integer range expression according to the R2 spec
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  gradle/baseNativeStdLibProject.gradle
  langlib/lang.__internal/src/main/ballerina/lang.__internal/int-range.bal
  langlib/langlib-test/build.gradle
  stdlib/utils/build.gradle
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/integer_range_operators.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/Compiler, Type/GrammarDeviation

#16575 Change MimeError to Error
  stdlib/mime/src/main/ballerina/mime/mime_errors.bal
Labels: Area/StandardLibs

#16569 Fix file path tests
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/UtilsTest.java
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/nativeimpl/PathTest.java
  stdlib/streams/src/main/ballerina/streams/processor/stream-join-processor.bal
Labels: Area/Language

#16581 [WebSub] Enable WebSub integration test cases
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubConnectorListener.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websub/basic/WebSubCoreFunctionalityTestCase.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-integration-test/src/test/resources/websub/services/01_websub_publisher.bal
Labels: Area/StandardLibs, Component/WebSub, Type/Task

#16583 Fix compilation failures of integration test services
  tests/ballerina-integration-test/src/test/resources/mutualSSL/mutual_ssl_client.bal
  tests/jballerina-integration-test/src/test/resources/http/httpservices/17_passthrough_service.bal
  tests/jballerina-integration-test/src/test/resources/http/httpservices/19_test_reusability_of_request.bal
  tests/jballerina-integration-test/src/test/resources/http/httpservices/21_http_payload.bal
  tests/jballerina-integration-test/src/test/resources/http/httpservices/25_http_status_codes.bal
  tests/jballerina-integration-test/src/test/resources/http/httpservices/26_http_retry_status_codes.bal
  tests/jballerina-integration-test/src/test/resources/http/httpservices/31_keep_alive_test.bal
Labels: Area/Language

#16403 Fix main with rest args
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserPositiveTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_function_rest_args.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_rest_args_missing.bal
Labels: Area/Language, Component/jBallerina

#16592 Update error types of Crypto, Encoding, Auth, JWT, LDAP and OAuth2
  stdlib/auth/src/main/ballerina/auth/auth_errors.bal
  stdlib/auth/src/main/ballerina/auth/inbound_auth_provider.bal
  stdlib/auth/src/main/ballerina/auth/inbound_basic_auth_provider.bal
  stdlib/auth/src/main/ballerina/auth/outbound_auth_provider.bal
  stdlib/auth/src/main/ballerina/auth/outbound_basic_auth_provider.bal
  stdlib/auth/src/main/ballerina/auth/utils.bal
  stdlib/crypto/src/main/ballerina/crypto/crypto.bal
  stdlib/crypto/src/main/ballerina/crypto/crypto_errors.bal
  stdlib/crypto/src/test/resources/test-src/crypto-test.bal
  stdlib/crypto/src/test/resources/test-src/keyparsing-test.bal
  stdlib/encoding/src/main/ballerina/encoding/encoding.bal
  stdlib/encoding/src/main/ballerina/encoding/encoding_errors.bal
  stdlib/encoding/src/test/resources/test-src/encoding-test.bal
  stdlib/http/src/test/resources/test-src/auth/basic-auth-handler-test.bal
  stdlib/http/src/test/resources/test-src/auth/bearer-auth-handler-test.bal
  stdlib/jwt/src/main/ballerina/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/jwt/jwt_errors.bal
  stdlib/jwt/src/main/ballerina/jwt/jwt_issuer.bal
  stdlib/jwt/src/main/ballerina/jwt/jwt_validator.bal
  stdlib/jwt/src/main/ballerina/jwt/outbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/jwt/utils.bal
  stdlib/jwt/src/test/resources/test-src/jwt-auth-provider-test.bal
  stdlib/jwt/src/test/resources/test-src/jwt-issuer-and-validator-test.bal
  stdlib/ldap/src/main/ballerina/ldap/inbound_ldap_auth_provider.bal
  stdlib/oauth2/src/main/ballerina/oauth2/inbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/oauth2/oauth2_errors.bal
  stdlib/oauth2/src/main/ballerina/oauth2/outbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/oauth2/utils.bal
Labels: Area/StandardLibs, Type/Improvement

#16593 Decouple LDAP functionality from InboundLdapAuthProvider
  stdlib/ldap/src/main/ballerina/ldap/inbound_ldap_auth_provider.bal
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/LdapConstants.java
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/nativeimpl/Authenticate.java
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/nativeimpl/GetGroups.java
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/nativeimpl/InitLdapConnectionContext.java
Labels: Area/StandardLibs, Component/LDAP, Type/Improvement

#16604 Fix checkstyle issues in filepath module
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/UtilsTest.java
Labels: Area/Language

#16588 Enable Transaction and Async tests
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/async/BasicAsyncOperationsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/async/basic-async-operations.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina

#16601 Enable TableTest, fixes issues, disables some / Fix issues in migration logic
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableIterator.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValue.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/PoolOptionsWrapper.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/SQLDataIterator.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/SQLDatasource.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/SQLDatasourceUtils.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/SQLTransactionContext.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/exceptions/PanickingApplicationException.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/exceptions/PanickingDatabaseException.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/AbstractSQLStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/CallStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/table/BCursorTable.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/table/TableTest.java
  stdlib/jdbc/src/test/resources/test-src/sql/table/table_nillable_mapping_negative.bal
  stdlib/jdbc/src/test/resources/test-src/sql/table/table_type.bal
  stdlib/jdbc/src/test/resources/testng.xml
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
Labels: Area/StandardLibs

#16603 Add handle type
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BHandleType.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BTypes.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/TypeConstants.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/TypeTags.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BHandleValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BHandleType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/TypeConstants.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/TypeTags.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/HandleValue.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeUtils.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/types/TypeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BootstrapRunner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/TypeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BHandleType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDescriptor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeTags.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  stdlib/bir-old/src/main/ballerina/bir/bir_model.bal
  stdlib/bir-old/src/main/ballerina/bir/type_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
  stdlib/http/src/main/ballerina/http/auth/authn_filter.bal
  stdlib/http/src/main/ballerina/http/auth/authz_filter.bal
  stdlib/http/src/main/ballerina/http/auth/authz_handler.bal
  stdlib/http/src/main/ballerina/http/auth/basic_auth_handler.bal
  stdlib/http/src/main/ballerina/http/auth/bearer_auth_handler.bal
  stdlib/http/src/main/ballerina/http/auth/inbound_auth_handler.bal
  stdlib/http/src/test/resources/test-src/auth/basic-auth-handler-test.bal
  stdlib/http/src/test/resources/test-src/auth/bearer-auth-handler-test.bal
  stdlib/llvm/src/main/ballerina/llvm/staticfunc.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/17_auth_with_custom_providers_handlers.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/handle/OpaqueHandleTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/handle/handle-type.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/Compiler, Component/jBallerina

#16586 Add socket error
  stdlib/socket/src/main/ballerina/socket/client_socket.bal
  stdlib/socket/src/main/ballerina/socket/socket_error.bal
  stdlib/socket/src/main/ballerina/socket/udp_client_socket.bal
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/SocketConstants.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Close.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/InitEndpoint.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Read.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/ShutdownRead.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/ShutdownWrite.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Start.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Write.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/InitServer.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/Register.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/Start.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/Stop.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/Close.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/InitEndpoint.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/ReceiveFrom.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/SendTo.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SelectorManager.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SocketUtils.java
  stdlib/socket/src/test/java/org/ballerinalang/stdlib/socket/ServerSocketTest.java
  stdlib/socket/src/test/resources/test-src/client_socket.bal
  stdlib/socket/src/test/resources/test-src/server_socket.bal
  stdlib/socket/src/test/resources/test-src/udp_client_socket.bal
  tests/jballerina-integration-test/src/test/resources/socket/services/01_client_callback.bal
  tests/jballerina-integration-test/src/test/resources/socket/services/02_server_socket_join_departure.bal
  tests/jballerina-integration-test/src/test/resources/socket/services/03_server_read_timeout.bal
Labels: Area/StandardLibs

#16637 Fix socket module tests
  stdlib/socket/src/test/resources/test-src/client_socket.bal
  stdlib/socket/src/test/resources/test-src/server_socket.bal
  stdlib/socket/src/test/resources/test-src/udp_client_socket.bal
Labels: Area/Language

#16649 Fix WebSub compile errors
  stdlib/websub/src/main/ballerina/websub/commons.bal
  stdlib/websub/src/main/ballerina/websub/hub_service.bal
Labels: Area/StandardLibs, Component/WebSub, Type/Task

#16639 Enable String Unit Tests
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/IndexOf.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-test.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/Compiler, Type/GrammarDeviation, Type/SpecDeviation

#16671 Fix compilation issues in socket integration test resources
  tests/jballerina-integration-test/src/test/resources/socket/services/01_client_callback.bal
  tests/jballerina-integration-test/src/test/resources/socket/services/02_server_socket_join_departure.bal
  tests/jballerina-integration-test/src/test/resources/socket/services/03_server_read_timeout.bal
Labels: Area/Language

#16638 Fix and enable error tests
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language

#16693 Enable xml and var tests
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/MapUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLFactory.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/var/VarDeclaredAssignmentStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLNativeFunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/var/var-type-assign-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attributes.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-native-functions.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language

#16686 Rename RabbitMQ Error to match with Ballerina Error Types Conventions
  stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/message.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/rabbitmq_commons.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/rabbitmq_errors.bal
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/RabbitMQConstants.java
Labels: Area/StandardLibs, Component/Messaging

#16715 Enable taint, any, anydata tests
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/TaintedStatusPropagationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/connectors/HttpClientTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/connectors/IOTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/any/BAnyTypeInvalidCastError.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/anydata/AnydataNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/anydata/AnydataTernaryConvTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/anydata/AnydataTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/connectors/character-io-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/call-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/call.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/compound-assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/iterable-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/iterable.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/json-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/json.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/lambda-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/lambda.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/map-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/map.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/recursions/multiple-cyclic-calls-complex.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/any/any-type-native-success.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/any/any-type-success.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_invalid_closed_record_assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_invalid_open_record_assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_negative_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_test.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language

#16709 Enable JVM unit tests
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/BuiltinMethodTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/anon-funcs.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/builtin-methods.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/foreach-maps.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/Compiler, Type/GrammarDeviation, Type/SpecDeviation

#16678 Fix HTTP resiliency jballerina integration tests
  stdlib/http/src/main/ballerina/http/resiliency/failover_client_endpoint.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/resiliency/HttpResiliencyTest.java
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/01_http_failover.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/02_http_failover.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/03_http_failover.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/04_http_failover.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/05_http_failover.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/06_http_failover.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/07_http_circuit_breaker.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/08_http_circuit_breaker.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/09_http_circuit_breaker.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/10_http_circuit_breaker.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/11_http_circuit_breaker.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/12_http_circuit_breaker.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/13_http_circuit_breaker.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/14_http_load_balancer.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/15_http2_failover.bal
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/16_http2_circuit_breaker.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Type/Improvement

#16719 Fix WebSocket integration test failures
  stdlib/http/src/main/ballerina/http/websocket/websocket_caller.bal
  stdlib/http/src/main/ballerina/http/websocket/websocket_client.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/03_push_and_onText.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/07_pushText_failure.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/09_client_failure.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/10_custom_header_client.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/12_error_log_service.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/13_ping_pong.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/14_query_and_path_param_support.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/15_resource_failure.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/17_simple_proxy_server.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/19_client_service.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/20_ssl_proxy.bal
  tests/jballerina-integration-test/src/test/resources/websocket/wsservices/21_ssl_echo.bal
Labels: Area/StandardLibs, Component/WebSocket

#16728 Fix http/2 tests
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2GenericScenarioTestCase.java
  tests/jballerina-integration-test/src/test/resources/http2/http2services/01_http_2.0_server_push_test.bal
  tests/jballerina-integration-test/src/test/resources/http2/http2services/02_http_2.0_redirect.bal
  tests/jballerina-integration-test/src/test/resources/http2/http2services/03_http_2.0_to_http_1.0_fallback_test.bal
  tests/jballerina-integration-test/src/test/resources/http2/http2services/04_http_2.0_prior_knowledge_test.bal
  tests/jballerina-integration-test/src/test/resources/http2/http2services/05_http_2.0_general_test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/HTTP2

#16755 Update Artemis Error
  stdlib/messaging/activemq-artemis/src/main/ballerina/artemis/artemis_errors.bal
  stdlib/messaging/activemq-artemis/src/main/ballerina/artemis/message.bal
  stdlib/messaging/activemq-artemis/src/main/ballerina/artemis/producer.bal
  stdlib/messaging/activemq-artemis/src/main/ballerina/artemis/session.bal
  stdlib/messaging/activemq-artemis/src/main/java/org/ballerinalang/messaging/artemis/ArtemisConstants.java
  stdlib/messaging/activemq-artemis/src/main/java/org/ballerinalang/messaging/artemis/ArtemisResourceValidator.java
  stdlib/messaging/activemq-artemis/src/test/java/org/ballerinalang/messaging/artemis/ArtemisCompilationTest.java
  stdlib/messaging/activemq-artemis/src/test/resources/test-src/artemis_mandatory_on_message_resource.bal
  stdlib/messaging/activemq-artemis/src/test/resources/test-src/artemis_mandatory_service_annotation.bal
  stdlib/messaging/activemq-artemis/src/test/resources/test-src/artemis_more_resources.bal
  stdlib/messaging/activemq-artemis/src/test/resources/test-src/data-binding/unsupported_map_type.bal
  stdlib/messaging/activemq-artemis/src/test/resources/test-src/data-binding/unsupported_type.bal
Labels: Area/StandardLibs, Component/Messaging

#16762 Rename EncodingError to Error
  stdlib/encoding/src/main/ballerina/encoding/encoding_errors.bal
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/Constants.java
Labels: Area/StandardLibs

#16763 Update root error constants of Crypto, Auth, JWT and OAuth2 modules
  stdlib/auth/src/main/ballerina/auth/auth_errors.bal
  stdlib/crypto/src/main/ballerina/crypto/crypto_errors.bal
  stdlib/jwt/src/main/ballerina/jwt/jwt_errors.bal
  stdlib/oauth2/src/main/ballerina/oauth2/oauth2_errors.bal
Labels: Area/StandardLibs, Type/Improvement

#16764 Fix https integration tests
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  tests/jballerina-integration-test/src/test/resources/mutualSSL/ssl_client_with_weak_cipher.bal
  tests/jballerina-integration-test/src/test/resources/proxy/proxyClient.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#16766 Enable jballerina tests
  stdlib/privacy/src/main/ballerina/privacy/h2_pii_store.bal
  stdlib/privacy/src/main/ballerina/privacy/mysql_pii_store.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#16783 Introduce error types for cache package
  stdlib/cache/src/main/ballerina/cache/cache.bal
  stdlib/cache/src/main/ballerina/cache/cache_errors.bal
Labels: Area/StandardLibs

#16791 Cleanup NATS module
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Register.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Start.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Stop.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/CloseConnection.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Publish.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Request.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/Close.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Attach.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Subscribe.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/message/Ack.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/producer/CloseConnection.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/producer/CreateStreamingConnection.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/producer/Publish.java
  stdlib/nats/src/main/ballerina/nats/producer/producer.bal
  stdlib/socket/src/main/ballerina/socket/client_socket.bal
  stdlib/socket/src/main/ballerina/socket/listener_endpoint.bal
  stdlib/socket/src/main/ballerina/socket/udp_client_socket.bal
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/SocketConstants.java
  tests/jballerina-integration-test/src/test/resources/socket/services/03_server_read_timeout.bal
Labels: Area/StandardLibs

#16800 Enable Freeze and isFrozen tests
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  langlib/lang.value/src/main/ballerina/lang.value/value.bal
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/IsReadOnly.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinfunctions/FreezeAndIsFrozenTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language

#16772 Update HTTP/2 resiliency tests
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/resiliency/HttpResiliencyTest.java
  tests/jballerina-integration-test/src/test/resources/resiliency/resiliencyservices/15_http2_failover.bal
Labels: Area/StandardLibs, Type/Bug

#16804 Update filepath error
  stdlib/filepath/src/main/ballerina/filepath/file_path.bal
  stdlib/filepath/src/main/ballerina/filepath/file_path_errors.bal
  stdlib/filepath/src/main/ballerina/filepath/unix_file_path.bal
  stdlib/filepath/src/main/ballerina/filepath/windows_file_path.bal
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/Constants.java
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/Utils.java
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/UtilsTest.java
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/nativeimpl/PathTest.java
Labels: Area/StandardLibs

#16809 Add time:Error type to ballerina/time modules
  stdlib/time/src/main/ballerina/time/time_errors.bal
  stdlib/time/src/main/ballerina/time/timelib.bal
  stdlib/time/src/test/resources/test-src/time-type.bal
Labels: Area/StandardLibs, Type/Improvement

#16794 Enable WebSub integration tests
  stdlib/cache/src/main/ballerina/cache/cache.bal
  stdlib/websub/src/main/ballerina/websub/commons.bal
  stdlib/websub/src/main/ballerina/websub/subscriber_service_endpoint.bal
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/nativeimpl/GetSubscribers.java
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/nativeimpl/RetrieveSubscriptionParameters.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websub/basic/WebSubCoreFunctionalityTestCase.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-integration-test/src/test/resources/websub/advanced_services/01_websub_publisher.bal
  tests/jballerina-integration-test/src/test/resources/websub/services/01_websub_publisher.bal
  tests/jballerina-integration-test/src/test/resources/websub/test_custom_subscribers.bal
  tests/jballerina-integration-test/src/test/resources/websub/test_unsubscription_client.bal
Labels: Area/StandardLibs, Component/WebSub, Type/Task

#16425 Improve Ballerina WebSocket error
  stdlib/http/src/main/ballerina/http/websocket/websocke_error.bal
  stdlib/http/src/main/ballerina/src/http/http_connection.bal
  stdlib/http/src/main/ballerina/src/http/websocket/websocket_caller.bal
  stdlib/http/src/main/ballerina/src/http/websocket/websocket_client.bal
  stdlib/http/src/main/ballerina/src/http/websocket/websocket_connector.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketClientConnectorListener.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketService.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketServicesRegistry.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Close.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Ping.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Pong.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/PushBinary.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/PushText.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Ready.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/exception/WebSocketException.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/AcceptWebSocketUpgrade.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/CancelWebSocketUpgrade.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocketclientendpoint/InitEndpoint.java
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/01_isOpen.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/02_upgrade_resource_without_handshake.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/03_push_and_onText.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/05_missing_resources.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/06_on_binary_continuation.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/07_pushText_failure.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/08_cancel_websocket_upgrade.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/10_custom_header_client.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/11_custom_header_server.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/12_error_log_service.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/13_ping_pong.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/14_query_and_path_param_support.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/17_simple_proxy_server.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/19_client_service.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/20_ssl_proxy.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/21_ssl_echo.bal
Labels: Area/StandardLibs, Component/WebSocket

#16815 Fix formatting tests to support new language changes
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/InvocationNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangInvocation.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/annotation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedAnnotation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFunction.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTable.bal
  language-server/modules/langserver-core/src/test/resources/formatting/function.bal
  language-server/modules/langserver-core/src/test/resources/formatting/table.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Area/Tooling, Component/Formatting

#16827 Fix table type tests
  bvm/ballerina-core/src/main/java/org/ballerinalang/model/TableJSONDataSource.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableLiteralIterableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableLiteralSyntaxTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_literal.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_literal_iterable.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_literal_syntax.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_literal_syntax_negative1.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_literal_syntax_negative2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_literal_unconstrained_table_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_test_helper.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language

#16732 Fix not notifying failure when resource return an error
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_value_gen.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/service/ServiceTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/service/service_test.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#16721 Include ballerina tool for testerina
  cli/ballerina-tool/build.gradle
  cli/ballerina-tool/src/main/java/org/ballerinalang/tool/Main.java
  cli/ballerina-tool/src/main/resources/META-INF/launcher.properties
  cli/ballerina-tool/src/main/resources/META-INF/tool.properties
  distribution/zip/jballerina/build.gradle
  misc/testerina/modules/testerina-core/build.gradle
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/BTestRunner.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestAnnotationProcessor.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestCmd.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/test/StartServiceSkeleton.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/util/BTestUtil.java
  misc/testerina/modules/testerina-core/src/test/java/org/ballerinalang/testerina/test/AssertTest.java
  misc/testerina/modules/testerina-core/src/test/java/org/ballerinalang/testerina/test/BeforeAfterTest.java
  misc/testerina/modules/testerina-core/src/test/java/org/ballerinalang/testerina/test/DataProviderTest.java
  misc/testerina/modules/testerina-core/src/test/java/org/ballerinalang/testerina/test/DependsOnTest.java
  misc/testerina/modules/testerina-core/src/test/java/org/ballerinalang/testerina/test/utils/BTestUtils.java
Labels: Area/Tooling

#16845 Introduce Error to Math module
  stdlib/math/src/main/ballerina/src/math/math_errors.bal
  stdlib/math/src/main/ballerina/src/math/natives.bal
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/FloorDiv.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/FloorMod.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NegateExact.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/RandomInRange.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/org/ballerinalang/stdlib/math/Constant.java
  stdlib/math/src/test/resources/test-src/math/math.bal
Labels: Area/StandardLibs

#16819 Rename jballerina command to ballerina
  distribution/zip/jballerina/bin/ballerina
  distribution/zip/jballerina/bin/ballerina.bat
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/Constant.java
Labels: Area/Tooling

#16205 Revert "Change the ballerina command to jballerina in vscode extension"
  tool-plugins/vscode/src/core/extension.ts
Labels: Area/Tooling

#16833 Enable Transaction tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/TransactionLocalParticipantFunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/transaction-local-participant-function.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transaction_block_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transaction_stmt.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language

#16849 Fix and enable TableToXMLStreamingTestCase
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/data/streaming/TableToXMLStreamingTestCase.java
  tests/jballerina-integration-test/src/test/resources/data/streaming/xml_streaming_test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#16834 Sync langlib into master
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/StreamingCodeDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/StreamsQuerySemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  distribution/zip/ballerina/build.gradle
  distribution/zip/jballerina/build.gradle
  language-server/modules/langserver-core/build.gradle
  settings.gradle
  stdlib/streams/build.gradle
  stdlib/streams/src/main/ballerina/src/streams/pattern/and-operator-processor.bal
  stdlib/streams/src/main/ballerina/src/streams/pattern/compound-pattern-processor.bal
  stdlib/streams/src/main/ballerina/src/streams/pattern/followed-by-processor.bal
  stdlib/streams/src/main/ballerina/src/streams/pattern/operand-processor.bal
  stdlib/streams/src/main/ballerina/src/streams/pattern/or-operator-processor.bal
  stdlib/streams/src/main/ballerina/src/streams/processor/stream-join-processor.bal
  stdlib/streams/src/main/ballerina/src/streams/util/scheduler.bal
  stdlib/streams/src/main/ballerina/src/streams/util/utils.bal
  stdlib/streams/src/main/ballerina/src/streams/window/delay-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/external-time-batch-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/external-time-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/hopping-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/length-batch-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/length-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/sort-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/time-accumulating-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/time-batch-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/time-length-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/time-order-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/time-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/unique-length-window.bal
  stdlib/streams/src/main/ballerina/src/streams/window/window.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-aggregation-groupby-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-aggregation-unit-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-external-window-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-filter-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-having-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-orderby-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-simple-counting-pattern-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-simple-not-pattern-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-simple-pattern-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-stream-join-test.bal
  stdlib/streams/src/test/resources/test-src/native/streamingv2-native-table-join-test.bal
  stdlib/streams/src/test/resources/test-src/streamingv2-custom-window-test.bal
  stdlib/streams/src/test/resources/test-src/streamingv2-select-with-library-function-test.bal
  stdlib/streams/src/test/resources/test-src/throttler/time-batch.bal
  stdlib/streams/src/test/resources/testng.xml
  stdlib/task/src/test/java/org/ballerinalang/stdlib/task/scheduler/TimerSchedulerTest.java
  stdlib/task/src/test/resources/testng.xml
  tests/ballerina-unit-test/build.gradle
Labels: Area/Language

#16606 Fix -o path support for jBallerina build command
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/BuilderUtils.java
Labels: Area/Language, Component/Packerina, Component/jBallerina

#16801 Add markdown documentations to BIR
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  stdlib/bir-old/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/bir-old/src/main/ballerina/bir/type_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_pkg_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/type_parser.bal
Labels: Area/Language, Component/jBallerina

#16848 Enable auth integration tests
  stdlib/http/src/main/ballerina/src/http/auth/authn_filter.bal
  stdlib/http/src/main/ballerina/src/http/auth/authz_filter.bal
  stdlib/http/src/main/ballerina/src/http/auth/authz_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/basic_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/bearer_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/inbound_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/outbound_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/http_secure_client.bal
  stdlib/http/src/main/ballerina/src/http/service_endpoint.bal
  stdlib/http/src/test/java/org/ballerinalang/stdlib/auth/BasicAuthHandlerTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/auth/BearerAuthHandlerTest.java
  stdlib/http/src/test/resources/test-src/auth/basic-auth-handler-test.bal
  stdlib/http/src/test/resources/test-src/auth/bearer-auth-handler-test.bal
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/nativeimpl/Authenticate.java
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/nativeimpl/InitLdapConnectionContext.java
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
  tests/ballerina-integration-test/src/test/resources/auth/src/authservices/17_auth_with_custom_providers_handlers.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthWithCustomProvidersHandlersTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnConfigPatternTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/LdapAuthStoreTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/OAuth2ConfigTest.java
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/10_token_propagation_disabled_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/11_token_propagation_basic_auth_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/12_token_propagation_jwt_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/13_token_propagation_jwt_reissuing_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/14_token_propagation_jwt_reissuing_negative_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/17_auth_with_custom_providers_handlers.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/18_oauth2_client_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/oauth2-mock-server.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Type/Improvement

#16853 Enable Table SQL query tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/Compiler

#16854 Update the error to WebSocketError in the resources file
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/07_pushText_failure.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/10_custom_header_client.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/17_simple_proxy_server.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/19_client_service.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/20_ssl_proxy.bal
Labels: Area/StandardLibs

#16852 Remove renaming pack
  distribution/zip/jballerina-tools/build.gradle
Labels: Area/Build

#16868 Fix LS project resolving issue with packerina changes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/SourceDirectoryManager.java
  language-server/modules/langserver-compiler/spotbugs-exclude.xml
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompiler.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompilerUtil.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/common/LSDocument.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/TextDocumentFormatUtil.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocumentManagerImpl.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/repository/LSPathConverter.java
  language-server/modules/langserver-compiler/src/test/java/org/ballerinalang/langserver/compiler/LSPackageCacheTest.java
  language-server/modules/langserver-compiler/src/test/java/org/ballerinalang/langserver/compiler/workspace/repository/WorkspacePackageRepositoryTest.java
  language-server/modules/langserver-compiler/src/test/resources/testng.xml
  language-server/modules/langserver-core/build.gradle
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateTestExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/references/ReferencesTreeVisitor.java
  misc/ballerina-formatter/src/main/java/org/ballerinalang/format/FormatUtil.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/CodeGenerator.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenServiceCmd.java
Labels: Area/Tooling

#16857 Fix too many open files issue when running jBallerina tests
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/UninstallUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/FileSystemProgramDirectory.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/FileSystemProjectDirectory.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/PathConverter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/ZipConverter.java
Labels: Area/Language

#16870 Include tool command help content
  cli/ballerina-tool/src/main/java/org/ballerinalang/tool/Main.java
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-install.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-remove.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-sdks.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-update.help
Labels: Area/Tooling

#16877 Remove unnecessary imports in RabbitMQ module
  examples/rabbitmq-producer/rabbitmq_producer.bal
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/AbortChannel.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/BasicPublish.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/Close.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/CreateChannel.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/ExchangeDeclare.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/ExchangeDelete.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/GetConnection.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/QueueBind.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/QueueDeclare.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/QueueDelete.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/QueuePurge.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/AbortConnection.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/Close.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/CreateConnection.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/IsClosed.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/GetChannel.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/RegisterListener.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/SetQosSettings.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/Start.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/Stop.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/BasicAck.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/BasicNack.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetByteArrayContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetDeliveryTag.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetFloatContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetIntContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetJSONContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetProperties.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetTextContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetXMLContent.java
Labels: Area/StandardLibs

#16856 Add suport for using rest params as closure vars
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal
Labels: Area/Language, Component/Compiler

#16875 Update Jdbc examples
  examples/jdbc-client-batch-update/jdbc_client_batch_update.bal
  examples/jdbc-client-call-procedures/jdbc_client_call_procedures.bal
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.bal
  examples/jdbc-streaming-big-dataset/big_data_service.bal
  examples/jdbc-streaming-big-dataset/data_setup.bal
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/Module.md
Labels: Area/StandardLibs, Component/Data

#16858 Taint analysis langlib
  cli/ballerina-cli-module-pull/src/main/ballerina/src/module_pull/module_pull.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  stdlib/jdbc/src/test/resources/test-src/sql/table/table_type.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/TaintedStatusPropagationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/lang-lib-function-negative.bal
Labels: Area/Language

#16882 Fix JDBC BBE issues
  examples/jdbc-client-batch-update/jdbc_client_batch_update.bal
  examples/jdbc-client-batch-update/jdbc_client_batch_update.description
  examples/jdbc-client-call-procedures/jdbc_client_call_procedures.bal
  examples/jdbc-client-call-procedures/jdbc_client_call_procedures.description
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.bal
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.description
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.out
  examples/jdbc-streaming-big-dataset/big_data_service.bal
  examples/jdbc-streaming-big-dataset/data_setup.bal
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/Module.md
Labels: Area/StandardLibs

#16872 Make log-api printError function argument public
  stdlib/log-api/src/main/ballerina/src/log/natives.bal
  stdlib/test-common/src/test/java/org/ballerinalang/stdlib/common/CommonTestUtils.java
Labels: Area/StandardLibs, Type/Improvement

#16860 Add run command fix to ballerina tool module
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java
  cli/ballerina-tool/src/main/java/org/ballerinalang/tool/LauncherUtils.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
Labels: Area/Language, Component/jBallerina

#16871 Avoid NoSuchMethodError when Ballerina.toml exist with .bal file
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_package_gen.bal
Labels: Area/Language, Component/jBallerina

#16873 Fix ballerina.bat file for build cmd
  distribution/zip/jballerina/bin/ballerina.bat
Labels: Area/Language, Component/jBallerina

#16874 Sync packerina-dev with master
  cli/ballerina-launcher/src/main/resources/cli-help/ballerina-help.help
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/BuilderUtils.java
  cli/ballerina-tool/src/main/java/org/ballerinalang/tool/LauncherUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRFileWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/SourceDirectoryManager.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ProjectDirConstants.java
Labels: Area/Build, Component/Packerina

#16749 Update plugin version and release note
  tool-plugins/intellij/build.gradle
  tool-plugins/intellij/src/main/resources/META-INF/plugin.xml
Labels: Area/Tooling

#16881 Fix test command
  misc/testerina/modules/testerina-core/src/main/resources/META-INF/services/org.ballerinalang.tool.BLauncherCmd
Labels: Area/Tooling

#16889 Fix function generator fails for attached functions of the objects
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/DocumentServiceKeys.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateVariableExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/IgnoreReturnExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
Labels: Area/Tooling, Type/Bug

#16886 Fix formatter cli tool
  misc/ballerina-formatter/build.gradle
  misc/ballerina-formatter/src/main/java/org/ballerinalang/format/FormatCmd.java
  misc/ballerina-formatter/src/main/java/org/ballerinalang/format/FormatUtil.java
  misc/ballerina-formatter/src/main/resources/META-INF/services/org.ballerinalang.tool.BLauncherCmd
  misc/ballerina-formatter/src/test/java/org/ballerinalang/format/FormatCmdTest.java
  tool-plugins/vscode/package-lock.json
  tool-plugins/vscode/package.json
Labels: Area/Tooling

#15969 Enable Tests for Code Actions and Command Executions
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpsService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/voidFunctionNoParams.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wsService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wssService.bal
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CommandExecutionTest.java
  language-server/modules/langserver-core/src/test/resources/command/source/createVariable.bal
Labels: Area/Tooling, Component/LanguageServer

#16832 Enable variabledef tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachErrorBindingPatternsTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_errors.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ErrorVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ForwardReferencingGlobalDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/TestProj/src/globalcycle/src/simple/file01.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/TestProj/src/globalcycle/src/simple/file02.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/TestProj/src/globalcycle/src/viafunc/file01.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/TestProj/src/globalcycle/src/viaservice/file01.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/TestProj/src/inFunctionGlobalRef/file01.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt_negative.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
  tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/grammar/BallerinaLexer.tokens
Labels: Area/Language

#16859 Handle listener startup failures
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_error_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_error_gen.bal
  stdlib/http/src/main/ballerina/src/http/non_listening_service_endpoint.bal
  stdlib/http/src/main/ballerina/src/http/service_endpoint.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpErrorType.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/mock/nonlistening/NonListeningStart.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/serviceendpoint/Start.java
Labels: Area/Language, Component/jBallerina

#16880 Append error detail for panicked errors
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Scheduler.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
Labels: Area/StandardLibs, Component/HTTP

#16895 Fix test failures
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/PassthroughServiceSampleTestCase.java
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/17_authn_with_custom_handlers.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/28_resource_function_return.bal
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/01_http_2.0_server_push_test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#16884 Fix and enable disabled database tests/ Cleanup
  examples/jdbc-streaming-big-dataset/data_setup.bal
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/Module.md
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/actions/BatchUpdate.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/actions/Call.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/actions/Select.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/actions/Update.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/datasource/SQLDatasource.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/functions/Close.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/functions/CreateClient.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/functions/InitGlobalPoolContainer.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/H2ClientActionsTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/SQLConnectorInitTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/table/TableTest.java
  stdlib/jdbc/src/test/resources/test-src/h2/h2_actions_test.bal
  stdlib/jdbc/src/test/resources/test-src/sql/sql_connector_init_test.bal
  stdlib/jdbc/src/test/resources/test-src/sql/table/table_type.bal
Labels: Area/StandardLibs

#16896 Fix integration tests
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/01_isOpen.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/04_client_close.bal
Labels: Area/StandardLibs

#16894 Sync Tooling dev with master
  composer/packages/diagram/src/views/components/hidden-block.tsx
  distribution/zip/ballerina-tools/build.gradle
  distribution/zip/ballerina-tools/src/assembly/bin.xml
  distribution/zip/jballerina-tools/build.gradle
  distribution/zip/jballerina-tools/src/assembly/bin.xml
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/DocumentServiceKeys.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateVariableExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/IgnoreReturnExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/spi/LSCompletionProvider.java
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/httpsService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/voidFunctionNoParams.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wsService.bal
  language-server/modules/langserver-core/src/main/resources/testgen/template/wssService.bal
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CommandExecutionTest.java
  language-server/modules/langserver-core/src/test/resources/command/source/createVariable.bal
  misc/ballerina-formatter/build.gradle
  misc/ballerina-formatter/src/main/java/org/ballerinalang/format/FormatCmd.java
  misc/ballerina-formatter/src/main/java/org/ballerinalang/format/FormatUtil.java
  misc/ballerina-formatter/src/main/resources/META-INF/services/org.ballerinalang.tool.BLauncherCmd
  misc/ballerina-formatter/src/test/java/org/ballerinalang/format/FormatCmdTest.java
  settings.gradle
  tool-plugins/intellij/gradle.properties
  tool-plugins/vscode/package-lock.json
  tool-plugins/vscode/package.json
  tool-plugins/vscode/src/overview/activator.ts
  tool-plugins/vscode/src/project-tree-view/project-overview.ts
Labels: Area/Tooling

#16876 Rename `ballerinna-launcher` module as `ballerina-tool`
  misc/ballerina-gradle-plugins/docerina-gradle-plugin/build.gradle
  misc/ballerina-gradle-plugins/docerina-gradle-plugin/src/main/java/org/ballerinalang/plugin/gradle/doc/DocerinaGen.java
  misc/ballerina-maven-plugins/docerina-maven-plugin/build.gradle
  misc/ballerina-maven-plugins/docerina-maven-plugin/src/main/java/org/ballerinalang/plugin/maven/doc/DocerinaMojo.java
  misc/docerina/build.gradle
  misc/docerina/src/main/java/org/ballerinalang/docgen/cmd/BallerinaDocCmd.java
  misc/lib-creator-milestone/build.gradle
  misc/lib-creator-milestone/src/main/java/org/ballerinalang/stdlib/utils/GenerateBalo.java
  misc/lib-creator/build.gradle
  misc/lib-creator/src/main/java/org/ballerinalang/stdlib/utils/GenerateBalo.java
  misc/metrics-extensions/modules/ballerina-prometheus-extension/build.gradle
  misc/metrics-extensions/modules/ballerina-prometheus-extension/src/main/java/org/ballerinalang/observe/metrics/prometheus/PrometheusReporter.java
  misc/openapi-ballerina/modules/ballerina-to-openapi-generator/build.gradle
  misc/openapi-ballerina/modules/ballerina-to-openapi-generator/src/main/java/org/ballerinalang/ballerina/openapi/convertor/service/OpenApiConverterUtils.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/build.gradle
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/CodeGenerator.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenClientCmd.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenContractCmd.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenServiceCmd.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/resources/META-INF/services/org.ballerinalang.tool.BLauncherCmd
  misc/protobuf-ballerina/build.gradle
  misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/cmd/GrpcCmd.java
  tests/jballerina-integration-test/build.gradle
Labels: Area/Tooling

#16898 Fix integration tests
  tests/jballerina-integration-test/src/test/resources/socket/src/services/03_server_read_timeout.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#16899 Enable multipart integration test
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/PassthroughServiceSampleTestCase.java
Labels: Area/StandardLibs

#16901 Fix spotbug issue in formatter tool
  misc/ballerina-formatter/src/main/java/org/ballerinalang/format/FormatUtil.java
  misc/ballerina-formatter/src/test/java/org/ballerinalang/format/FormatCmdTest.java
Labels: Area/Tooling

#16913 Update port range of auth integration tests
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthWithCustomProvidersHandlersTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnConfigInheritanceTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnConfigPatternTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnWithCustomHandlersTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnWithMultipleHandlersTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnWithOAuth2Test.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnWithoutHTTPAnnotationsTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthzCacheTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthzConfigInheritanceTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthzConfigPatternTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/LdapAuthStoreTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/OAuth2ConfigTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/ResourceLevelAuthTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/ServiceLevelAuthnTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/TokenPropagationTest.java
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/01_authn_config_inheritance_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/02_authz_config_inheritance_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/03_resource_level_auth_config_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/04_service_level_auth_config_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/05_auth_test_without_annotations_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/06_authn_with_multiple_handlers.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/07_authz_with_cache_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/08_authn_with_expired_certificate_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/09_authn_with_expired_certificate_with_no_expiry_validation.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/10_token_propagation_disabled_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/11_token_propagation_basic_auth_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/12_token_propagation_jwt_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/13_token_propagation_jwt_reissuing_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/14_token_propagation_jwt_reissuing_negative_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/15_ldap_auth_store_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/16_ldap_auth_store_authz_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/17_auth_with_custom_providers_handlers.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/18_oauth2_client_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/19_authn_config_pattern_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/20_authz_config_pattern_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/21_authn_with_oauth2_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/oauth2-mock-server.bal
Labels: Area/StandardLibs, Type/Improvement

#16914 Change ports used in the WebSocket tests
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/CancelWebSocketUpgradeTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/ClientCloseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/ClientInitializationFailureTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/ClientServiceTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/CustomHeaderClientSupportTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/CustomHeaderServerSupportTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/IsOpenTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/MissingResourcesTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/OnBinaryContinuationTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/OnErrorWebSocketTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/PingPongSupportTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/PushAndOnTextResourceTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/PushTextFailureTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/ResourceFailureTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/SslEchoTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/UpgradeResourceFailureTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/UpgradeResourceWithoutHandshakeTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/WebSocketAutoPingPongTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/WebSocketContinuationAndAggregationTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/WebSocketQueryAndPathParamSupportTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/WebSocketServiceNotFoundTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/WebSocketSimpleProxyTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/WebSocketSslProxyTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/WebSocketTestCommons.java
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/01_isOpen.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/02_upgrade_resource_without_handshake.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/03_push_and_onText.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/04_client_close.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/05_missing_resources.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/06_on_binary_continuation.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/07_pushText_failure.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/08_cancel_websocket_upgrade.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/09_client_failure.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/10_custom_header_client.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/11_custom_header_server.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/12_error_log_service.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/13_ping_pong.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/14_query_and_path_param_support.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/15_resource_failure.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/16_service_not_found.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/17_simple_proxy_server.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/18_simple_server_without_ping_resource.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/19_client_service.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/20_ssl_proxy.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/21_ssl_echo.bal
Labels: Area/StandardLibs, Component/WebSocket

#16909 Update webSocket examples
  examples/websocket-basic-sample/tests/websocket_basic_sample_test.bal
  examples/websocket-basic-sample/websocket_basic_sample.bal
  examples/websocket-chat-application/tests/websocket_chat_application_test.bal
  examples/websocket-chat-application/websocket_chat_application.bal
  examples/websocket-proxy-server/tests/websocket_proxy_server_test.bal
  examples/websocket-proxy-server/websocket_proxy_server.bal
Labels: Area/StandardLibs, Component/WebSocket

#16911 Fix Artemis test failures and make fields public
  stdlib/messaging/activemq-artemis/src/main/ballerina/src/artemis/connection.bal
  stdlib/messaging/activemq-artemis/src/main/ballerina/src/artemis/message.bal
  stdlib/messaging/activemq-artemis/src/main/ballerina/src/artemis/producer.bal
  stdlib/messaging/activemq-artemis/src/main/ballerina/src/artemis/session.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/messaging/artemis/ArtemisTestCommons.java
  tests/jballerina-integration-test/src/test/resources/messaging/artemis/src/producers/close.bal
  tests/jballerina-integration-test/src/test/resources/messaging/artemis/src/producers/simple_producer.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/Messaging

#16918 Add tests for converting table to json and streaming
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/data/streaming/TableDataStreamingTestCase.java
  tests/jballerina-integration-test/src/test/resources/data/streaming/streaming_test.bal
  tests/jballerina-integration-test/src/test/resources/data/streaming/xml_streaming_test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs
