Repository ballerina-platform/ballerina-lang, pull requests merged in 2019-09, with the labels that each got.

#18347 Make variable definition of 'foreach' loop final
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachNegativeTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-negative.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-record-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_tuples.bal
  langlib/langlib-test/src/test/resources/testng.xml
  stdlib/http/src/main/ballerina/src/http/http_request.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-receive-in-fork.bal
Labels: Area/Language

#18408 Enable distributed transaction tests
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FutureValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangInvocation.java
  examples/transactions-distributed/initiator.bal
  examples/transactions-distributed/participant.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/AbstractHTTPAction.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Delete.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Execute.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Forward.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Get.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Head.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Options.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Patch.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Post.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Put.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/Submit.java
  stdlib/transactions/src/main/ballerina/src/transactions/service_initiator.bal
  stdlib/transactions/src/main/ballerina/src/transactions/service_participant_2pc.bal
  stdlib/transactions/src/main/ballerina/src/transactions/transaction_block.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/transaction/RemoteParticipantTransactionTest.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-integration-test/src/test/resources/transaction/src/participantservice/01_remote_participant.bal
  tests/jballerina-integration-test/src/test/resources/transaction/src/transactionservices/01_initiator.bal
  tests/jballerina-integration-test/src/test/resources/transaction/src/transactionservices/03_participant2.bal
Labels: Area/JBallerina

#18407 Allow accessing function annotations at runtime
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/AnnotationUtils.java
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/annotations/annotation.bal
Labels: Area/JBallerina, Area/Language

#18416 Fix xml literal tag validation
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
Labels: Area/Language

#18422 Fix the logger not printing the stacktrace
  bvm/ballerina-logging/src/main/java/org/ballerinalang/logging/formatters/BallerinaLogFormatter.java
  bvm/ballerina-logging/src/main/resources/logging.properties
Labels: Area/StandardLibs

#18424 Fixes related to balo, lock file and push modules
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/PushUtils.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/writer/BaloFileWriter.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/model/LockFileImport.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/parser/LockFileProcessor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/LockFileWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/PackageLoader.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/URIDryConverter.java
Labels: Area/BuildTools, Component/Packerina

#18429 Use round-to-even rounding
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeConverter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/SimpleTypeCastExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/simple-type-cast.bal
Labels: Area/JBallerina

#18446 Log HTTP Listener errors as warnings
  stdlib/http/src/main/ballerina/src/http/resiliency/failover_connector.bal
  stdlib/http/src/main/ballerina/src/http/resiliency/http_load_balancer.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/BallerinaHTTPConnectorListener.java
Labels: Area/StandardLibs, Component/HTTP, Type/Bug

#18415 Fix WebSocket exception related issues
  examples/websocket-basic-sample/websocket_basic_sample.bal
  examples/websocket-chat-application/websocket_chat_application.bal
  examples/websocket-client/websocket_client.bal
  examples/websocket-proxy-server/websocket_proxy_server.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/actionInvocationSuggestion1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/actionInvocationSuggestion2.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/actionInvocationSuggestion1.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/actionInvocationSuggestion2.json
  stdlib/http/src/main/ballerina/src/http/http_connection.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketClientConnectorListener.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketService.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketServicesRegistry.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Close.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Ping.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Pong.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/PushBinary.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/PushText.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Ready.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/WebSocketResourceValidator.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/exception/WebSocketException.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/AcceptWebSocketUpgrade.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/CancelWebSocketUpgrade.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/serviceendpoint/Register.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocketclientendpoint/InitEndpoint.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/websocket/WebSocketCompilationTest.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/MimeUtil.java
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/12_custom_header_server.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/13_error_log_service.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/14_ping_pong.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/15_query_and_path_param_support.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/16_resource_failure.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/17_service_not_found.bal
Labels: Area/StandardLibs, Component/WebSocket

#18496 Fix duplicate stacktrace log #18484
  bvm/ballerina-rt/build.gradle
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/scheduling/Scheduler.java
  distribution/zip/jballerina/build.gradle
Labels: Area/JBallerina

#18476 Fix authn/authz filter error messages
  stdlib/http/src/main/ballerina/src/http/auth/authn_filter.bal
  stdlib/http/src/main/ballerina/src/http/auth/authz_filter.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
Labels: Area/StandardLibs, Component/JWT, Type/Improvement

#18479 Fix class not found issue when run grpc service as uber java.
  stdlib/grpc/src/main/ballerina/Ballerina.toml
Labels: Area/StandardLibs

#18453 Fix retry request implementation of OAuth2 outbound authentication
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/OAuth2ConfigTest.java
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/18_oauth2_client_test.bal
Labels: Area/StandardLibs, Component/OAuth2, Type/Bug

#18353 Enable disabled tests
  language-server/modules/langserver-core/src/test/resources/completion/function/functionCompletionWithMissingImport.json
  language-server/modules/langserver-core/src/test/resources/completion/function/returnParameterContextSuggestion3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/returnParameterContextSuggestion6.json
  language-server/modules/langserver-core/src/test/resources/completion/function/returnParameterContextSuggestion9.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore1.json
  stdlib/io/src/main/ballerina/src/io/open.bal
  stdlib/system/src/test/java/org/ballerinalang/stdlib/system/SystemTest.java
  stdlib/time/src/test/java/org.ballerinalang.stdlib.time/TimeTest.java
  stdlib/time/src/test/resources/test-src/time-type.bal
Labels: Area/StandardLibs

#18492 Add integration tests for log API
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/logging/LogAPITestCase.java
  tests/jballerina-integration-test/src/test/resources/logging/log-project/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/logging/log-project/src/bar/bar.bal
  tests/jballerina-integration-test/src/test/resources/logging/log-project/src/baz/baz.bal
  tests/jballerina-integration-test/src/test/resources/logging/log-project/src/foo/foo.bal
  tests/jballerina-integration-test/src/test/resources/logging/log-project/src/mainmod/main.bal
  tests/jballerina-integration-test/src/test/resources/logging/log_level_test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/nativeimpl/functions/LoggerTest.java
Labels: Area/StandardLibs

#18490 Fix expression order of precedence
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserBaseListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserListener.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/integer/BIntegerValueNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTemplateLiteralNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal
Labels: Area/Language

#18488 Revisit CLI help messages
  cli/ballerina-launcher/src/main/resources/cli-help/ballerina-default.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-help.help
Labels: Type/Docs

#18532 Fix task scheduler timer example
  examples/task-scheduler-timer/task_scheduler_timer.bal
  examples/task-scheduler-timer/task_scheduler_timer.out
  examples/task-scheduler-timer/tests/task_scheduler_timer_test.bal
Labels: Area/StandardLibs, Component/Examples

#18542 Fix gRPC BBEs in beta release
  examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal
  examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.out
  examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service_client.out
  examples/grpc-client-streaming/grpc_client_streaming_service.out
  examples/grpc-client-streaming/grpc_client_streaming_service_client.out
  examples/grpc-secured-unary/grpc_secured_unary_service.out
  examples/grpc-secured-unary/grpc_secured_unary_service_client.bal
  examples/grpc-secured-unary/grpc_secured_unary_service_client.out
  examples/grpc-server-streaming/grpc_server_streaming_service.out
  examples/grpc-server-streaming/grpc_server_streaming_service_client.bal
  examples/grpc-server-streaming/grpc_server_streaming_service_client.out
  examples/grpc-unary-blocking/grpc_unary_blocking_service.out
  examples/grpc-unary-blocking/grpc_unary_blocking_service_client.out
  examples/grpc-unary-non-blocking/grpc_unary_non_blocking_service.out
  examples/grpc-unary-non-blocking/grpc_unary_non_blocking_service_client.bal
  examples/grpc-unary-non-blocking/grpc_unary_non_blocking_service_client.out
Labels: Area/StandardLibs

#18462 Fix vscode cmd for building a project
  tool-plugins/vscode/src/project/cli-cmds/build.ts
Labels: Area/Tooling

#18507 Fix NATS BBEs
  examples/nats-streaming-client/subscriber.bal
  examples/nats-streaming-consumer-with-data-binding/subscriber.bal
  examples/nats-streaming-durable-subscriptions/subscriber.bal
  examples/nats-streaming-queue-group/queue-group.bal
  examples/nats-streaming-start-position/subscriber.bal
Labels: Area/StandardLibs

#18528 Fix HTTP-Redirects BBE
  examples/http-redirects/http_redirects.bal
  examples/http-redirects/http_redirects.client.out
  examples/http-redirects/http_redirects.out
Labels: Area/StandardLibs, Component/Examples

#18534 Fix secured clients and services BBEs and crypto BBE
  examples/crypto/crypto.bal
  examples/secured-client-with-basic-auth/sample-users.toml
  examples/secured-client-with-basic-auth/secured_client_with_basic_auth.bal
  examples/secured-client-with-basic-auth/secured_service_with_basic_auth.bal
  examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.bal
  examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.description
  examples/secured-client-with-jwt-auth/secured_service_with_jwt_auth.bal
  examples/secured-client-with-oauth2/secured_client_with_oauth2.bal
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.client.out
  examples/secured-service-with-jwt/secured_service_with_jwt.bal
  examples/secured-service-with-jwt/secured_service_with_jwt.client.out
Labels: Area/StandardLibs, Component/Auth, Component/Crypto

#18530 Update Stream queries and table queries BBEs with beta changes
  examples/join-multiple-streams/join_multiple_streams.bal
  examples/streams/streams.out
  examples/table-queries/table_queries.out
  examples/temporal-aggregations-and-windows/temporal_aggregations_and_windows.bal
Labels: Component/Examples

#18541 Fix HTTP BBEs
  examples/http-cors/http_cors.bal
  examples/http-data-binding/http_data_binding.bal
  examples/restrict-by-media-type/restrict_by_media_type.bal
Labels: Area/StandardLibs, Component/Examples

#18114 Add test cases for http-cache
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/HttpBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HTTPCachingTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/37_no_cache_service.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/38_max_age_cache_service.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/39_must_revalidate_cache_service.bal
Labels: Area/StandardLibs

#18529 Fix client endpoint BBE
  examples/http-client-endpoint/http_client_endpoint.bal
  examples/http-client-endpoint/http_client_endpoint.out
Labels: Area/StandardLibs

#18569 Update JSON-IO and socket BBE
  examples/json-io/json_io.bal
  examples/tcp-socket-listener-client/tcp_socket_listener.bal
Labels: Area/StandardLibs

#18536 Fix BBEs
  examples/different-payload-types/different_payload_types.bal
  examples/header-based-routing/header_based_routing.bal
Labels: Area/StandardLibs

#18573 Update http resiliency examples
  examples/http-circuit-breaker/http_circuit_breaker.bal
  examples/http-circuit-breaker/http_circuit_breaker.client.out
  examples/http-circuit-breaker/http_circuit_breaker.server.out
  examples/http-failover/http_failover.bal
  examples/http-load-balancer/http_load_balancer.bal
  examples/http-retry/http_retry.bal
  examples/http-retry/http_retry.server.out
  examples/http-timeout/http_timeout.bal
  examples/http-timeout/http_timeout.server.out
Labels: Area/StandardLibs, Component/Examples, Type/Improvement

#18579 Update http resiliency examples
  examples/http-circuit-breaker/http_circuit_breaker.client.out
  examples/http-circuit-breaker/http_circuit_breaker.server.out
  examples/http-failover/http_failover.client.out
  examples/http-load-balancer/http_load_balancer.client.out
  examples/http-retry/http_retry.client.out
  examples/http-timeout/http_timeout.client.out
Labels: Area/StandardLibs, Component/Examples, Type/Improvement

#18590 Update client generation out file and description
  examples/client-generation/client_generation.description
  examples/client-generation/client_generation.out
Labels: Component/Examples, Type/Docs

#18596 Update ballerina to openapi BBE
  examples/ballerina-to-openapi/ballerina_to_openapi.description
  examples/ballerina-to-openapi/ballerina_to_openapi.out
Labels: Component/Examples, Type/Docs

#18575 Add new BBE for ballerina/file module
  examples/file/file.bal
  examples/file/file.description
  examples/file/file.out
  examples/index.json
  stdlib/file/src/main/ballerina/src/file/Module.md
Labels: Area/StandardLibs

#18599 Update openapi-to-ballerina BBE
  examples/openapi-to-ballerina/openapi_to_ballerina.description
  examples/openapi-to-ballerina/openapi_to_ballerina.out
Labels: Component/Examples, Type/Docs

#18506 Fix XML serialization issue
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
Labels: Area/StandardLibs

#18567 Fix test failure in windows
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/utils/SQLDBUtils.java
Labels: Area/StandardLibs

#18603 Remove RabbitMQ and WebSub modules from the distribution
  distribution/zip/jballerina/build.gradle
  examples/index.json
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#18585 Fix error construct and external annotation formatting
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/ErrorVariableReferenceNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangErrorVarRef.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/resources/formatting/errorVariableDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/errorVariableReference.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorVariableDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorVariableReference.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFunction.bal
  language-server/modules/langserver-core/src/test/resources/formatting/function.bal
Labels: Area/Tooling, Component/Formatting

#18540 Update versions of NATS and Kafka modules
  distribution/zip/jballerina/build.gradle
  gradle/javaProject.gradle
  stdlib/messaging/kafka/src/main/ballerina/Ballerina.toml
  stdlib/messaging/nats/src/main/ballerina/Ballerina.toml
Labels: Area/StandardLibs

#18572 Add regex module
  distribution/zip/jballerina/build.gradle
  settings.gradle
  stdlib/regex/build.gradle
  stdlib/regex/src/main/ballerina/Ballerina.toml
  stdlib/regex/src/main/ballerina/src/regex/natives.bal
  stdlib/regex/src/test/java/org/ballerinalang/stdlib/regex/RegexTest.java
  stdlib/regex/src/test/resources/test-src/regex.bal
  stdlib/regex/src/test/resources/testng.xml
Labels: Area/StandardLibs

#18606 Fix PushText for JSON
  stdlib/http/src/main/ballerina/src/http/websocket/websocket_connector.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Ping.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Pong.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/PushBinary.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/PushText.java
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/03_push_and_onText.bal
Labels: Area/StandardLibs, Component/WebSocket

#18474 Add jsonutils module.
  distribution/zip/jballerina/build.gradle
  settings.gradle
  stdlib/jsonutils/build.gradle
  stdlib/jsonutils/src/main/ballerina/Ballerina.toml
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/json-to-xml.bal
  stdlib/jsonutils/src/main/java/org/ballerinalang/stdlib/jsonutils/JSONToXMLConverter.java
  stdlib/jsonutils/src/main/java/org/ballerinalang/stdlib/jsonutils/ToXML.java
  stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java
  stdlib/jsonutils/src/test/resources/test-src/json-to-xml-test.bal
  stdlib/jsonutils/src/test/resources/testng.xml
Labels: Area/StandardLibs

#18481 Remove length return value from byte channel read
  cli/ballerina-cli-module-pull/src/main/ballerina/src/module_pull/module_pull.bal
  cli/ballerina-cli-module-push/src/main/ballerina/src/module_push/module_push.bal
  examples/byte-io/byte_io.bal
  examples/http-streaming/http_streaming.bal
  examples/response-with-multiparts/response_with_multiparts.bal
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/FunctionDefinitionCompletionTest.java
  stdlib/bir/src/main/ballerina/src/bir/channel_io.bal
  stdlib/io/src/main/ballerina/src/io/Module.md
  stdlib/io/src/main/ballerina/src/io/readable_byte_channel.bal
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/ReadBytes.java
  stdlib/io/src/test/resources/test-src/io/bytes_io.bal
  stdlib/system/build.gradle
  stdlib/system/src/main/ballerina/src/system/process.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/11_grpc_byte_client.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/TransactionLocalParticipantFunctionTest.java
Labels: Area/StandardLibs

#18613 Refactor log messages of crypto module
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/CryptoUtils.java
  stdlib/crypto/src/test/java/org/ballerinalang/stdlib/crypto/CryptoTest.java
Labels: Area/StandardLibs, Component/Crypto, Type/Improvement

#18549 Fix filepath:resolve() error messages
  stdlib/filepath/src/main/ballerina/src/filepath/file_path.bal
  stdlib/filepath/src/main/ballerina/src/filepath/file_path_errors.bal
  stdlib/filepath/src/main/ballerina/src/filepath/windows_file_path.bal
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/Constants.java
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/Utils.java
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/nativeimpl/Absolute.java
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/nativeimpl/Matches.java
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/nativeimpl/Resolve.java
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/UtilsTest.java
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/nativeimpl/PathTest.java
Labels: Area/StandardLibs

#18609 Change ballerinaException to ErrorValue
  examples/http-client-endpoint/http_client_endpoint.bal
  examples/http-client-endpoint/http_client_endpoint.out
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpErrorType.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/clientendpoint/CreateSimpleHttpClient.java
Labels: Area/StandardLibs

#18633 Remove -e , --config and --observe options
  bvm/ballerina-config/src/main/java/org/ballerinalang/config/ConfigRegistry.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/launch/LaunchUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/observability/ObservabilityConstants.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/BLangConstants.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/RunCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateJarTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/logging/LogAPITestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/tracing/TracingTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websub/advanced/WebSubAdvancedBaseTest.java
Labels: Area/JBallerina

#18626 Make the root logger off by default
  bvm/ballerina-logging/src/main/resources/logging.properties
Labels: Area/StandardLibs

#18634 Rename ballerina/regex module into ballerina/stringutils
  distribution/zip/jballerina/build.gradle
  settings.gradle
  stdlib/stringutils/build.gradle
  stdlib/stringutils/src/main/ballerina/Ballerina.toml
  stdlib/stringutils/src/main/ballerina/src/stringutils/natives.bal
  stdlib/stringutils/src/test/java/org/ballerinalang/stdlib/stringutils/StringUtilsTest.java
  stdlib/stringutils/src/test/resources/test-src/string-utils-test.bal
  stdlib/stringutils/src/test/resources/testng.xml
Labels: Area/StandardLibs, Type/Improvement

#18619 Remove unused encoding module dependencies
  cli/ballerina-cli-utils/build.gradle
  compiler/ballerina-backend-jvm/build.gradle
  misc/metrics-extensions/modules/ballerina-prometheus-extension/build.gradle
  stdlib/auth/build.gradle
  stdlib/bir/build.gradle
  stdlib/cache/build.gradle
  stdlib/config-api/build.gradle
  stdlib/filepath/build.gradle
  stdlib/http/build.gradle
  stdlib/internal/build.gradle
  stdlib/jdbc/build.gradle
  stdlib/jwt/build.gradle
  stdlib/ldap/build.gradle
  stdlib/messaging/kafka/build.gradle
  stdlib/messaging/nats/build.gradle
  stdlib/mime/build.gradle
  stdlib/oauth2/build.gradle
  stdlib/transactions/build.gradle
  tests/jballerina-integration-test/build.gradle
Labels: Area/StandardLibs, Component/Encoding, Type/Improvement

#18436 Add xmlutils module
  distribution/zip/jballerina/build.gradle
  settings.gradle
  stdlib/xmlutils/build.gradle
  stdlib/xmlutils/src/main/ballerina/Ballerina.toml
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/xml-to-json.bal
  stdlib/xmlutils/src/main/java/org/ballerinalang/stdlib/xmlutils/ToJSON.java
  stdlib/xmlutils/src/test/java/org/ballerinalang/stdlib/xmlutils/XmlUtilsTest.java
  stdlib/xmlutils/src/test/resources/test-src/xml-to-json-test.bal
  stdlib/xmlutils/src/test/resources/testng.xml
Labels: Area/StandardLibs

#18653 Remove unnecessary error creation in Failover client
  stdlib/http/src/main/ballerina/src/http/resiliency/failover_client_endpoint.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/resiliency/HttpResiliencyTest.java
Labels: Area/StandardLibs, Component/HTTP, Type/Improvement

#18644 Adjust connection timeout expected error message
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/connection/ConnectionPoolTest.java
Labels: Area/StandardLibs

#18659 Fix filepath:filename() issue in windows platform
  stdlib/filepath/src/main/ballerina/src/filepath/file_path.bal
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/nativeimpl/PathTest.java
Labels: Area/StandardLibs

#18628 Change usage of BallerinaException to ErrorValue
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/channels/FileIOChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CreateReadableCharacterChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CreateReadableDataChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CreateReadableDelimitedRecordChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CreateWritableCharacterChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CreateWritableDataChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/CreateWritableDelimitedRecordChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/GetTable.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/OpenWritableFile.java
Labels: Area/StandardLibs

#18664 Resiliency client fixes
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinInvocationArgs3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/delimiterBasedCompletionForCompleteSource1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/ifWhileConditionContextCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/workerDeclarationContext4.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport1.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport2.json
  language-server/modules/langserver-core/src/test/resources/completion/service/serviceBodyCompletion5.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/globalVarDefPackageContent.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelPackageContentAccess.json
  stdlib/http/src/main/ballerina/src/http/resiliency/http_circuit_breaker.bal
  stdlib/http/src/main/ballerina/src/http/resiliency/http_round_robin_rule.bal
  stdlib/http/src/main/ballerina/src/http/resiliency/load_balance_client_endpoint.bal
Labels: Area/StandardLibs, Component/HTTP, Type/Bug

#18632 Refactor and reformat json utils module
  stdlib/jsonutils/build.gradle
  stdlib/jsonutils/src/main/java/org/ballerinalang/stdlib/jsonutils/JSONToXMLConverter.java
  stdlib/jsonutils/src/test/resources/testng.xml
Labels: Area/StandardLibs, Type/Improvement

#18498 Make it illegal to refer peer works as futures
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/actions-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/var-mutability-with-workers.bal
Labels: Area/Language

#18624 Fix round-to-even for decimal values
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/DecimalValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/SimpleTypeCastExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/simple-type-cast.bal
Labels: Area/JBallerina

#18621 Improve NATS Connector
  pom.xml
  stdlib/messaging/nats/pom.xml
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/annotation.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/subscriber.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/commons.bal
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/Constants.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/NatsBasicConsumerServiceCompilerPlugin.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/DefaultMessageHandler.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/ErrorHandler.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/GracefulStop.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/ImmediateStop.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Register.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Start.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/CloseConnection.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Publish.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Request.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/Close.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/DefaultConnectionListener.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/DefaultErrorListener.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Attach.java
Labels: Area/StandardLibs

#18620 Use ErrorValue instead of BallerinaException in MIME
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/ParseHeader.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/basics/ServiceTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/dispatching/DataBindingTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/nativeimpl/ParseHeaderNegativeTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/nativeimpl/request/RequestNativeFunctionNegativeTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/nativeimpl/response/ResponseNativeFunctionNegativeTest.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/AbstractGetPayloadHandler.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/ByteArrayToString.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/GetBodyParts.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/GetBodyPartsAsChannel.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/GetByteArray.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/GetByteChannel.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/GetJson.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/GetMediaType.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/GetText.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/GetXml.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/headers/GetHeader.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/headers/GetHeaders.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/EntityBodyHandler.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/HeaderUtil.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/MimeConstants.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/MimeUtil.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/MultipartDecoder.java
  stdlib/mime/src/test/java/org/ballerinalang/stdlib/mime/HeaderTest.java
  stdlib/mime/src/test/java/org/ballerinalang/stdlib/mime/MimeUtilityFunctionTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HttpPayloadTestCase.java
Labels: Area/StandardLibs

#18682 Fix native lib copying during ballerina build
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyNativeLibTask.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JInterop.java
Labels: Area/BuildTools, Component/Packerina

#18658 Improve union type perf
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BUnionType.java
Labels: Area/JBallerina

#18630 Update/Improve error messages
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/datasource/PoolKey.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/datasource/SQLDatasource.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/datasource/SQLDatasourceUtils.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/AbstractSQLStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/CallStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/ProcessedStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/SelectStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/table/BCursorTable.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/table/SQLDataIterator.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/transaction/SQLTransactionContext.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/BatchUpdateTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/H2ActionsTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/SelectTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/UpdateTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/connection/ConnectorInitTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/table/TableTypeTest.java
Labels: Area/StandardLibs

#18656 Modify the array sort to sort in-place
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Sort.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Area/Language

#18591 Add stdlib module versions
  observelib/observe/src/main/ballerina/Ballerina.toml
  stdlib/auth/src/main/ballerina/Ballerina.toml
  stdlib/cache/src/main/ballerina/Ballerina.toml
  stdlib/config-api/src/main/ballerina/Ballerina.toml
  stdlib/crypto/src/main/ballerina/Ballerina.toml
  stdlib/encoding/src/main/ballerina/Ballerina.toml
  stdlib/file/src/main/ballerina/Ballerina.toml
  stdlib/filepath/src/main/ballerina/Ballerina.toml
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/io/src/main/ballerina/Ballerina.toml
  stdlib/jwt/src/main/ballerina/Ballerina.toml
  stdlib/ldap/src/main/ballerina/Ballerina.toml
  stdlib/log-api/src/main/ballerina/Ballerina.toml
  stdlib/math/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/reflect/src/main/ballerina/Ballerina.toml
  stdlib/runtime-api/src/main/ballerina/Ballerina.toml
  stdlib/socket/src/main/ballerina/Ballerina.toml
  stdlib/streams/src/main/ballerina/Ballerina.toml
  stdlib/system/src/main/ballerina/Ballerina.toml
  stdlib/task/src/main/ballerina/Ballerina.toml
  stdlib/time/src/main/ballerina/Ballerina.toml
  stdlib/transactions/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
  stdlib/xslt/src/main/ballerina/Ballerina.toml
Labels: Area/StandardLibs

#18623 Fix async action invocation on remote object
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/RuntimeUtils.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/08_http_client_actions.bal
Labels: Area/JBallerina

#18690 Refactor tests to check duplicate stacktraces
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/execution/ModuleExecutionFlowTests.java
Labels: Area/JBallerina

#18689 Enable few disabled tests under "brokenOnJBallerina"
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/connectors/SQLTest.java
Labels: Area/JBallerina

#18533 BallerinaConnectorException replace by the WebSocketException
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketUtil.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#18495 Fix "Lambda functions can be invoked without passing the params"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/negative/fp_invocation_with_missing_args.bal
Labels: Area/Language, Component/Compiler

#18694 Remove array of endpoints from service config
  stdlib/http/src/main/ballerina/src/http/annotation.bal
  stdlib/http/src/main/ballerina/src/http/client_endpoint.bal
Labels: Area/StandardLibs

#18688 Make the listener stop graceful on program exit
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_error_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ListenerLifeCycleTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/listner-lifecycle-functions.bal
Labels: Area/JBallerina

#18616 Limit service functions from invoking outside self and having access modifiers
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/endpoint/ServiceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/endpoint/new/service_basic_negative.bal
Labels: Area/Language

#18701 Fix missing '`' char in error match stmt example
  examples/error-match-statement/error_match_statement.bal
Labels: Type/Docs

#18681 Improve worker reference validation
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/actions-negative.bal
Labels: Area/Language

#18657 Replace internal:split and internal:replace usages with stringutils module
  cli/ballerina-cli-module-pull/build.gradle
  cli/ballerina-cli-module-pull/src/main/ballerina/src/module_pull/module_pull.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/build.gradle
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_observability_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_package_gen.bal
  language-server/modules/langserver-core/build.gradle
  stdlib/auth/build.gradle
  stdlib/auth/src/main/ballerina/src/auth/inbound_basic_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/utils.bal
  stdlib/config-api/build.gradle
  stdlib/config-api/src/main/ballerina/src/config/config.bal
  stdlib/http/build.gradle
  stdlib/http/src/main/ballerina/src/http/caching/caching_commons.bal
  stdlib/http/src/main/ballerina/src/http/http_request.bal
  stdlib/jwt/build.gradle
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/oauth2/build.gradle
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
  stdlib/streams/build.gradle
  stdlib/streams/src/main/ballerina/src/streams/processor/output-processor.bal
  stdlib/streams/src/main/ballerina/src/streams/processor/stream-join-processor.bal
  stdlib/streams/src/main/ballerina/src/streams/util/stream-event.bal
  stdlib/websub/build.gradle
  stdlib/websub/src/main/ballerina/src/websub/commons.bal
  stdlib/websub/src/main/ballerina/src/websub/hub_service.bal
  tests/jballerina-integration-test/build.gradle
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/oauth2-mock-server.bal
Labels: Area/StandardLibs, Type/Improvement

#18702 Fix task examples for 1.0
  examples/task-scheduler-timer/task_scheduler_timer.bal
  examples/task-service-appointment/task_service_appointment.bal
  examples/task-service-appointment/task_service_appointment.out
  examples/task-service-timer/task_service_timer.bal
  examples/task-service-timer/task_service_timer.out
Labels: Area/StandardLibs, Component/Examples, Type/Improvement

#18611 Fix formatter CLI and Formatting functionality issues
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/statements/VariableDefinitionNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangErrorVariableDef.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangRecordVariableDef.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangSimpleVariableDef.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangTupleVariableDef.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/sourcegen/FormattingSourceGen.java
  language-server/modules/langserver-core/src/test/resources/formatting/asyncExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedAsyncExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedWorker.bal
  language-server/modules/langserver-core/src/test/resources/formatting/worker.bal
  misc/ballerina-formatter/src/main/java/org/ballerinalang/format/FormatUtil.java
Labels: Area/Tooling, Component/Formatting

#18691 Add an API doc warning to the ballerina runtime value classes
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/CollectionValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/DecimalValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FPValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FutureValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/HandleValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/IteratorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/RefValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamingJsonValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableIterator.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLAttributes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLIterator.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLQName.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLValue.java
Labels: Area/JBallerina

#18711 Fix line count exceed issue in file BBE
  examples/file/file.bal
  examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal
  examples/grpc-client-streaming/grpc_client_streaming_service.bal
  examples/grpc-client-streaming/grpc_client_streaming_service_client.bal
  examples/grpc-secured-unary/grpc_secured_unary_service.bal
  examples/grpc-server-streaming/grpc_server_streaming_service.bal
  examples/nats-basic-client/publisher.bal
  examples/nats-streaming-client/publisher.bal
  examples/nats-streaming-consumer-with-data-binding/publisher.bal
  examples/nats-streaming-consumer-with-data-binding/subscriber.bal
  examples/nats-streaming-durable-subscriptions/publisher.bal
  examples/nats-streaming-queue-group/publisher.bal
  examples/nats-streaming-queue-group/queue-group.bal
  examples/nats-streaming-start-position/publisher.bal
  examples/nats-streaming-start-position/subscriber.bal
Labels: Area/StandardLibs

#18715 Fix import formatting
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedImport.bal
  language-server/modules/langserver-core/src/test/resources/formatting/import.bal
Labels: Area/Tooling, Component/Formatting

#18700 Update error messages in socket module
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/compiler/SocketCompilerPlugin.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Close.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/InitEndpoint.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Read.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/ShutdownRead.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/ShutdownWrite.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Start.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Write.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/InitServer.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/Start.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/Stop.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/Close.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/InitEndpoint.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/ReceiveFrom.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/SendTo.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/ReadPendingCallback.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SelectorManager.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SocketUtils.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/TCPSocketCallback.java
  stdlib/socket/src/test/java/org/ballerinalang/stdlib/socket/ClientSocketTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/socket/SocketClientCallbackServiceTestCase.java
Labels: Area/StandardLibs

#18721 Add string utils functions from internal module
  stdlib/stringutils/src/main/ballerina/src/stringutils/natives.bal
  stdlib/stringutils/src/test/java/org/ballerinalang/stdlib/stringutils/StringUtilsTest.java
  stdlib/stringutils/src/test/resources/test-src/string-utils-test.bal
Labels: Area/StandardLibs, Component/stringutils, Type/Improvement

#18447 Avoid trying to obtain generated keys in Oracle/SQL Server batch update / Remove BallerinaException usages
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/JSONUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableJSONDataSource.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamingJsonValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableIterator.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/Constants.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java
Labels: Area/StandardLibs

#18699 Add Kafka examples
  examples/index.json
  examples/kafka_message_consumer_group_service/kafka_message_consumer_group_service.bal
  examples/kafka_message_consumer_group_service/kafka_message_consumer_group_service.description
  examples/kafka_message_consumer_group_service/kafka_message_consumer_group_service.out
  examples/kafka_message_consumer_service/kafka_message_consumer_service.bal
  examples/kafka_message_consumer_service/kafka_message_consumer_service.description
  examples/kafka_message_consumer_service/kafka_message_consumer_service.out
  examples/kafka_message_consumer_simple/kafka_message_consumer_simple.bal
  examples/kafka_message_consumer_simple/kafka_message_consumer_simple.description
  examples/kafka_message_consumer_simple/kafka_message_consumer_simple.out
  examples/kafka_message_producer/kafka_message_producer.bal
  examples/kafka_message_producer/kafka_message_producer.description
  examples/kafka_message_producer/kafka_message_producer.out
  examples/kafka_message_producer_transactional/kafka_message_producer_transactional.bal
  examples/kafka_message_producer_transactional/kafka_message_producer_transactional.description
  examples/kafka_message_producer_transactional/kafka_message_producer_transactional.out
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaConstants.java
Labels: Area/StandardLibs

#18725 Remove ldap from distribution
  distribution/zip/jballerina/build.gradle
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/15_ldap_auth_store_test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/LDAP

#18737 Upgrade transport version
  distribution/zip/jballerina/build.gradle
  gradle/javaProject.gradle
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/CipherStrengthSSLTestCase.java
Labels: Area/StandardLibs

#18735 Fix tuple rest param and tuple variable whitespace issue
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/TupleVariableNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/TupleVariableReferenceNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/statements/TupleDestructureNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/types/TupleTypeNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangTupleVariable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTupleVarRef.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangTupleDestructure.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangTupleTypeNode.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTupleDestructure.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTupleType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTupleTypeRest.bal
  language-server/modules/langserver-core/src/test/resources/formatting/tupleDestructure.bal
  language-server/modules/langserver-core/src/test/resources/formatting/tupleType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/tupleTypeRest.bal
Labels: Area/Tooling, Component/Compiler, Component/Formatting, Priority/Blocker

#18724 Fix and enable async BBE
  examples/async/async.bal
  examples/async/async.out
  examples/index.json
Labels: Component/Examples

#18708 Refactor examples and modules with run command flag change
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/BLangConstants.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/RunCommand.java
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-run.help
  examples/config-api/config_api.out
  examples/counter-metrics/counter_metrics.bal
  examples/counter-metrics/counter_metrics.description
  examples/counter-metrics/counter_metrics.server.out
  examples/gauge-metrics/gauge_metric.server.out
  examples/gauge-metrics/gauge_metrics.bal
  examples/gauge-metrics/gauge_metrics.description
  examples/http-access-logs/http_access_logs.server.out
  examples/http-caching-client/http_caching_client.server.out
  examples/http-trace-logs/http_trace_logs.server.out
  examples/log-api/log_api.bal
  examples/log-api/log_api.out
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.server.out
  examples/tracing/tracing.bal
  examples/tracing/tracing.description
  examples/tracing/tracing.server.out
  observelib/observe/src/main/ballerina/src/observe/Module.md
  stdlib/config-api/src/main/ballerina/src/config/Module.md
  stdlib/log-api/src/main/ballerina/src/log/Module.md
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/tracing/TracingTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websub/advanced/WebSubAdvancedBaseTest.java
Labels: Area/BuildTools, Type/Docs

#18750 Hide internal module apis
  language-server/modules/langserver-core/src/test/resources/testng.xml
  stdlib/internal/src/main/ballerina/src/internal/old_builtin.bal
Labels: Area/StandardLibs, Type/Improvement

#18769 Unblock strand when an error occurs in HTTP respond
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/scheduling/Scheduler.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java
Labels: Area/JBallerina, Area/StandardLibs

#18692 Refactor returned/thrown error values
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/AbstractHTTPAction.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/clientendpoint/CreateSimpleHttpClient.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/ParseHeader.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/ResponseWriter.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/request/GetQueryParams.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/nativeimpl/Resolve.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/MimeConstants.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/ResourceFunctionReturnTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/transaction/RemoteParticipantTransactionTest.java
Labels: Area/StandardLibs

#18757 Add toolingCompilation compiler option
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/CompilerOptionName.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  composer/package-lock.json
Labels: Area/Language, Area/Tooling

#18797 Fix observability enable flag
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/launch/LaunchUtils.java
Labels: Component/Observability, Priority/Blocker

#18782 Remove StdLib builtin
  stdlib/builtin/assembly/balo.xml
  stdlib/builtin/assembly/source.xml
  stdlib/builtin/build.gradle
  stdlib/builtin/pom.xml
  stdlib/builtin/spotbugs-exclude.xml
  stdlib/builtin/src/main/ballerina/Ballerina.toml
  stdlib/builtin/src/main/ballerina/src/builtin/jsonlib.bal
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/asynclib/IsCancelled.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/asynclib/IsDone.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/jsonlib/ToXML.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/Contains.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/ErrorUtils.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/FindAll.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/HashCode.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/IndexOf.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/Length.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/REGEXConstants.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/Substring.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/ToLower.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/ToUpper.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/stringlib/Trim.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/lang/utils/Constants.java
  stdlib/builtin/src/main/java/org/ballerinalang/util/BuiltInUtils.java
Labels: Area/StandardLibs

#18755 Update gRPC cli tool help text
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-grpc.help
  examples/grpc-client-streaming/grpc_client_streaming_service_client.bal
  stdlib/grpc/build.gradle
  stdlib/grpc/src/main/ballerina/src/grpc/client_endpoint.bal
  stdlib/grpc/src/main/ballerina/src/grpc/service_endpoint.bal
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/GrpcUtil.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/clientendpoint/Init.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/clientendpoint/InitGlobalPool.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/serviceendpoint/InitEndpoint.java
Labels: Area/StandardLibs

#18835 Update Kafka Module.md
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/Module.md
Labels: Area/StandardLibs

#18785 Handle empty entity body in HTTP response
  stdlib/http/src/main/ballerina/src/http/http_commons.bal
Labels: Area/StandardLibs

#18840 Update module md related to security modules
  stdlib/crypto/src/main/ballerina/src/crypto/Module.md
  stdlib/encoding/src/main/ballerina/src/encoding/Module.md
  stdlib/jwt/src/main/ballerina/src/jwt/Module.md
  stdlib/oauth2/src/main/ballerina/src/oauth2/Module.md
Labels: Area/StandardLibs, Component/Auth, Component/Crypto, Component/Encoding, Component/JWT, Component/LDAP, Component/OAuth2, Type/Improvement

#18795 Fix BBEs
  examples/header-based-routing/header_based_routing.bal
  examples/http-streaming/http_streaming.bal
Labels: Area/StandardLibs

#18774 Fix examples
  examples/http-filters/http_filters.server.out
  examples/http-to-websocket-upgrade/http_to_websocket_upgrade.out
  examples/websocket-basic-sample/websocket_basic_sample.out
  examples/websocket-chat-application/websocket_chat_application.out
  examples/websocket-client/websocket_client.out
  examples/websocket-proxy-server/websocket_proxy_server.out
Labels: Area/StandardLibs

#18802 Improve Module.md of JDBC module
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/Module.md
Labels: Area/StandardLibs

#18832 Fix resiliency BBE server logs
  examples/http-circuit-breaker/http_circuit_breaker.server.out
  examples/http-retry/http_retry.server.out
  examples/http-timeout/http_timeout.server.out
  stdlib/http/src/main/ballerina/src/http/Module.md
Labels: Area/StandardLibs

#18773 Fix table related issues
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableConstants.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableProvider.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableIterator.java
  distribution/zip/jballerina/src/assembly/bin.xml
  examples/join-multiple-streams/join_multiple_streams.bal
  examples/temporal-aggregations-and-windows/temporal_aggregations_and_windows.bal
  langlib/lang.typedesc/src/main/java/org/ballerinalang/langlib/typedesc/ConstructFrom.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  stdlib/jdbc/build.gradle
  stdlib/jdbc/src/test/resources/test-src/actions/h2_actions_test.bal
  stdlib/jdbc/src/test/resources/test-src/connection/connector_init_test.bal
  stdlib/jdbc/src/test/resources/test-src/table/table_type_test.bal
  stdlib/jsonutils/build.gradle
  stdlib/jsonutils/src/main/ballerina/Ballerina.toml
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/json-to-xml.bal
  stdlib/jsonutils/src/main/java/org/ballerinalang/stdlib/jsonutils/FromTable.java
  stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java
  stdlib/jsonutils/src/test/resources/test-src/json-to-xml-test.bal
  stdlib/xmlutils/build.gradle
  stdlib/xmlutils/src/main/ballerina/Ballerina.toml
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/xml-to-json.bal
  stdlib/xmlutils/src/main/java/org/ballerinalang/stdlib/xmlutils/FromTable.java
  stdlib/xmlutils/src/test/java/org/ballerinalang/stdlib/xmlutils/XmlUtilsTest.java
  stdlib/xmlutils/src/test/resources/test-src/xml-to-json-test.bal
  tests/jballerina-integration-test/build.gradle
  tests/jballerina-integration-test/src/test/resources/data/streaming/streaming_test.bal
  tests/jballerina-integration-test/src/test/resources/observability/metrics/metrics-test.bal
  tests/jballerina-unit-test/build.gradle
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/execution/ModuleExecutionFlowTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_literal_syntax.bal
Labels: Area/StandardLibs

#18740 Fix intermittent transaction test failures
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/transaction/RemoteParticipantTransactionTest.java
  tests/jballerina-integration-test/src/test/resources/transaction/src/participantSepProc/01_remote_participant_sep_proc.bal
  tests/jballerina-integration-test/src/test/resources/transaction/src/participantservice/01_remote_participant.bal
Labels: Area/JBallerina

#18823 Add listener/endpoint configuration population logic to grpc module.
  examples/grpc-client-streaming/grpc_client_streaming_service_client.bal
  stdlib/grpc/build.gradle
  stdlib/grpc/src/main/ballerina/src/grpc/client_endpoint.bal
  stdlib/grpc/src/main/ballerina/src/grpc/service_endpoint.bal
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/GrpcUtil.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/clientendpoint/Init.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/clientendpoint/InitGlobalPool.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/serviceendpoint/InitEndpoint.java
Labels: Area/StandardLibs

#18775 Fix adding additional space
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/resources/formatting/constrainedType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedConstrainedType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedIndexBasedAccess.bal
  language-server/modules/langserver-core/src/test/resources/formatting/indexBasedAccess.bal
Labels: Area/Tooling, Component/Formatting

#18841 Fix "Already-Registered" error when calling same participant multiple times
  examples/transactions-distributed/initiator.bal
  stdlib/transactions/src/main/ballerina/src/transactions/commons.bal
Labels: Area/JBallerina

#18847 Fix config passing in build and test commands
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/CompileCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/TestCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunTestsTask.java
  cli/ballerina-tool/src/main/java/org/ballerinalang/tool/Main.java
Labels: Area/BuildTools

#18866 Fix BBE for OpenAPI tooling
  examples/ballerina-to-openapi/tests/ballerina_to_openapi_test.bal
  examples/client-generation/client_generation.description
  examples/openapi-to-ballerina/openapi_to_ballerina.description
  examples/openapi-to-ballerina/openapi_to_ballerina.out
Labels: Area/Tooling, Component/Examples

#18855 Improve lang lib Module.md fie
  langlib/lang.array/src/main/ballerina/src/lang.array/Module.md
  langlib/lang.decimal/src/main/ballerina/src/lang.decimal/Module.md
  langlib/lang.error/src/main/ballerina/src/lang.error/Module.md
  langlib/lang.float/src/main/ballerina/src/lang.float/Module.md
  langlib/lang.future/src/main/ballerina/src/lang.future/Module.md
  langlib/lang.int/src/main/ballerina/src/lang.int/Module.md
  langlib/lang.map/src/main/ballerina/src/lang.map/Module.md
  langlib/lang.object/src/main/ballerina/src/lang.object/Module.md
  langlib/lang.stream/src/main/ballerina/src/lang.stream/Module.md
  langlib/lang.string/src/main/ballerina/src/lang.string/Module.md
  langlib/lang.table/src/main/ballerina/src/lang.table/Module.md
  langlib/lang.typedesc/src/main/ballerina/src/lang.typedesc/Module.md
  langlib/lang.value/src/main/ballerina/src/lang.value/Module.md
  langlib/lang.xml/src/main/ballerina/src/lang.xml/Module.md
Labels: Area/Language

#18878 Update future cancelled error message
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
Labels: Area/JBallerina

#18890 Fix tuples getting round brackets instead of square brackets
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/spi/LSCompletionProvider.java
  language-server/modules/langserver-core/src/test/resources/completion/testablepackage/topLevelCompletion.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelCompletionAfterDocumentation.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelEmptyFirstLine.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelNonEmptyFirstLine.json
Labels: Area/Tooling, Component/LanguageServer, Priority/High, Type/Bug

#18904 Improve encoding module md
  stdlib/encoding/src/main/ballerina/src/encoding/Module.md
Labels: Area/StandardLibs, Component/Encoding, Type/Improvement

#18908 Update module.md
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/Module.md
  stdlib/stringutils/src/main/ballerina/src/stringutils/Module.md
  stdlib/time/src/main/ballerina/src/time/Module.md
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/Module.md
  stdlib/xslt/src/main/ballerina/src/xslt/Module.md
Labels: Area/StandardLibs

#18894 Update module md for math and mime
  stdlib/math/src/main/ballerina/src/math/Module.md
  stdlib/mime/src/main/ballerina/src/mime/Module.md
Labels: Area/StandardLibs

#18903 Update module.md files samples
  stdlib/config-api/src/main/ballerina/src/config/Module.md
  stdlib/log-api/src/main/ballerina/src/log/Module.md
  stdlib/transactions/src/main/ballerina/src/transactions/Module.md
  stdlib/websub/src/main/ballerina/src/websub/Module.md
Labels: Area/StandardLibs, Type/Improvement

#18876 Improve 'new', 'add', 'push', and 'pull' command help texts
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/AddCommandTest.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/NewCommandTest.java
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-add.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-build.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-clean.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-doc.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-encrypt.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-format.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-grpc.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-new.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-pull.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-push.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-run.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-search.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-test.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-version.help
Labels: Area/BuildTools, Type/Improvement

#18891 Fix XML attribute map toString() method
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLAttributes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attributes.bal
Labels: Area/JBallerina

#18920 Exclude examples test folders from distribution
  distribution/zip/jballerina-tools/build.gradle
Labels: Area/Build

#18915 Stdlib modulemd updates
  stdlib/auth/src/main/ballerina/src/auth/Module.md
  stdlib/cache/src/main/ballerina/src/cache/Module.md
  stdlib/config-api/src/main/ballerina/src/config/Module.md
  stdlib/encoding/src/main/ballerina/src/encoding/Module.md
  stdlib/file/src/main/ballerina/src/file/Module.md
  stdlib/filepath/src/main/ballerina/src/filepath/Module.md
  stdlib/grpc/src/main/ballerina/src/grpc/Module.md
  stdlib/http/src/main/ballerina/src/http/Module.md
  stdlib/io/src/main/ballerina/src/io/Module.md
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/Module.md
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/Module.md
  stdlib/jwt/src/main/ballerina/src/jwt/Module.md
  stdlib/log-api/src/main/ballerina/src/log/Module.md
  stdlib/math/src/main/ballerina/src/math/Module.md
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/Module.md
  stdlib/messaging/nats/src/main/ballerina/src/nats/Module.md
  stdlib/mime/src/main/ballerina/src/mime/Module.md
  stdlib/oauth2/src/main/ballerina/src/oauth2/Module.md
  stdlib/openapi/src/main/ballerina/src/openapi/Module.md
  stdlib/reflect/src/main/ballerina/src/reflect/Module.md
  stdlib/runtime-api/src/main/ballerina/src/runtime/Module.md
  stdlib/socket/src/main/ballerina/src/socket/Module.md
  stdlib/stringutils/src/main/ballerina/src/stringutils/Module.md
  stdlib/system/src/main/ballerina/src/system/Module.md
  stdlib/task/src/main/ballerina/src/task/Module.md
  stdlib/time/src/main/ballerina/src/time/Module.md
  stdlib/transactions/src/main/ballerina/src/transactions/Module.md
  stdlib/websub/src/main/ballerina/src/websub/Module.md
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/Module.md
  stdlib/xslt/src/main/ballerina/src/xslt/Module.md
Labels: Area/StandardLibs, Type/Improvement

#18906 Improve HTTP/2 server down test case
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/05_http_2.0_general_test.bal
Labels: Area/StandardLibs

#18901 Add information on configuring the thread pool size
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/Module.md
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/Module.md
  stdlib/messaging/nats/src/main/ballerina/src/nats/Module.md
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/Module.md
Labels: Type/Docs

#18932 Fix failing code action tests
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/typeGuardCodeAction1.json
Labels: Area/Tooling

#18933 Fix init split logic in testable modules
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Area/JBallerina

#18950 Fix completion issue with package alias
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/spi/LSCompletionProvider.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/FunctionDefinitionCompletionTest.java
  language-server/modules/langserver-core/src/test/resources/completion/function/source/varDefStmt1.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/source/varDefStmt2.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/varDefStmt1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/varDefStmt2.json
Labels: Area/Tooling

#18957 Update json-to-xml-convertion BBE
  examples/json-to-xml-conversion/json_to_xml_conversion.bal
  examples/json-to-xml-conversion/json_to_xml_conversion.description
  examples/json-to-xml-conversion/json_to_xml_conversion.out
  examples/json-to-xml-conversion/tests/json_to_xml_conversion_test.bal
Labels: Area/StandardLibs, Component/Examples

#18967 Update data-io bbe
  examples/data-io/data_io.bal
  examples/data-io/data_io.out
Labels: Area/StandardLibs

#18965 Upgrade transport version
  distribution/zip/jballerina-tools/LICENSE
  distribution/zip/jballerina/LICENSE
  distribution/zip/jballerina/build.gradle
  gradle/javaProject.gradle
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
Labels: Area/StandardLibs

#18985 Fix type creation failure issue
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Area/JBallerina

#18754 Cleanup compiler plugin
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/AbstractTransportCompilerPlugin.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/proto/ServiceProtoBuilder.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/WebSocketDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Close.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/HttpServiceCompilerPlugin.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/ResourceSignatureValidator.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/websocket/WebSocketClientResourceValidator.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/websocket/WebSocketClientServiceCompilerPlugin.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/websocket/WebSocketResourceValidator.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/websocket/WebSocketServiceCompilerPlugin.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/websocket/WebSocketServiceResourceValidator.java
  stdlib/http/src/main/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaServiceCompilerPlugin.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/AbstractNatsConsumerServiceCompilerPlugin.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/RabbitMQResourceValidator.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/RabbitMQServiceCompilerPlugin.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/compiler/SocketCompilerPlugin.java
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/compiler/WebSubServiceCompilerPlugin.java
Labels: Area/StandardLibs

#19013 Validate JDBC URL
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/functions/CreateClient.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/connection/ConnectorInitTest.java
  stdlib/jdbc/src/test/resources/test-src/connection/connector_init_test.bal
Labels: Area/StandardLibs, Component/Data, Type/Bug

#19031 Update docs of modules Cache, NATS and Kafka
  stdlib/cache/src/main/ballerina/src/cache/cache.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/Module.md
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/commons.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/kafka_errors.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/producer.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/Module.md
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/annotation.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/message.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/producer.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/subscriber.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/commons.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/connection/config.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/connection/connection.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/error.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/annotation.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/config.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/message.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/producer.bal
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/Constants.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/CloseConnection.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Publish.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Request.java
Labels: Area/StandardLibs

#19024 Fix missing docs of xslt and reflect module
  stdlib/reflect/src/main/ballerina/src/reflect/reflect.bal
  stdlib/xslt/src/main/ballerina/src/xslt/Module.md
  stdlib/xslt/src/main/ballerina/src/xslt/natives.bal
Labels: Area/StandardLibs, Type/Docs

#19023 Add missing documentation for Time module
  stdlib/time/src/main/ballerina/src/time/time_errors.bal
  stdlib/time/src/main/ballerina/src/time/timelib.bal
Labels: Area/StandardLibs, Component/Time

#19022 Add Documentation for WebSocket errors
  stdlib/http/src/main/ballerina/src/http/websocket/websocket_error.bal
Labels: Area/StandardLibs, Component/WebSocket

#19011 Update doc API in IO, Socket
  stdlib/io/src/main/ballerina/src/io/Module.md
  stdlib/io/src/main/ballerina/src/io/constants.bal
  stdlib/io/src/main/ballerina/src/io/io_error.bal
  stdlib/io/src/main/ballerina/src/io/print.bal
  stdlib/io/src/main/ballerina/src/io/readable_byte_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_byte_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_data_channel.bal
  stdlib/socket/src/main/ballerina/src/socket/Module.md
  stdlib/socket/src/main/ballerina/src/socket/socket_error.bal
Labels: Area/StandardLibs

#19007 Update config-api docs
  stdlib/config-api/src/main/ballerina/src/config/Module.md
Labels: Area/StandardLibs

#19001 MIME doc changes and make mime encode and decode functions private
  stdlib/http/src/test/java/org/ballerinalang/stdlib/multipart/MultipartDecoderTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/multipart/MultipartEncoderTest.java
  stdlib/http/src/test/resources/test-src/multipart/bytechannel-base64.bal
  stdlib/mime/src/main/ballerina/src/mime/Module.md
  stdlib/mime/src/main/ballerina/src/mime/mime_errors.bal
  stdlib/mime/src/main/ballerina/src/mime/natives.bal
  stdlib/mime/src/test/java/org/ballerinalang/stdlib/mime/MimeUtilityFunctionTest.java
  stdlib/mime/src/test/resources/test-src/mime-test.bal
Labels: Area/StandardLibs

#19002 Fix some http api doc issues
  stdlib/http/src/main/ballerina/src/http/Module.md
  stdlib/http/src/main/ballerina/src/http/service_endpoint.bal
Labels: Area/StandardLibs

#19004 Fix doc issues in System module
  stdlib/system/src/main/ballerina/src/system/Module.md
  stdlib/system/src/main/ballerina/src/system/process.bal
  stdlib/system/src/main/ballerina/src/system/system.bal
  stdlib/system/src/main/ballerina/src/system/system_errors.bal
Labels: Area/StandardLibs

#19005 Refactor file/filepath/grpc api docs
  stdlib/file/src/main/ballerina/src/file/file_errors.bal
  stdlib/filepath/src/main/ballerina/src/filepath/file_path_errors.bal
  stdlib/grpc/src/main/ballerina/src/grpc/annotation.bal
  stdlib/grpc/src/main/ballerina/src/grpc/client_endpoint.bal
  stdlib/grpc/src/main/ballerina/src/grpc/error_codes.bal
  stdlib/grpc/src/main/ballerina/src/grpc/grpc_commons.bal
  stdlib/grpc/src/main/ballerina/src/grpc/grpc_errors.bal
  stdlib/grpc/src/main/ballerina/src/grpc/service_endpoint.bal
  stdlib/grpc/src/main/ballerina/src/grpc/streaming_client.bal
Labels: Area/StandardLibs, Type/Docs

#19003 Update ballerina task, stringutils, jsonutils and xmlutils documents
  examples/index.json
  examples/json-to-xml-conversion/json_to_xml_conversion.bal
  examples/task-scheduler-appointment/task_scheduler_appointment.bal
  examples/task-scheduler-timer/task_scheduler_timer.bal
  examples/task-service-timer/task_service_timer.bal
  stdlib/http/src/main/ballerina/src/http/http_errors.bal
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/Module.md
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/jsonutils.bal
  stdlib/stringutils/src/main/ballerina/src/stringutils/Module.md
  stdlib/stringutils/src/main/ballerina/src/stringutils/natives.bal
  stdlib/stringutils/src/test/java/org/ballerinalang/stdlib/stringutils/StringUtilsTest.java
  stdlib/task/src/main/ballerina/src/task/Module.md
  stdlib/task/src/main/ballerina/src/task/commons.bal
  stdlib/task/src/main/ballerina/src/task/listener.bal
  stdlib/task/src/main/ballerina/src/task/scheduler.bal
  stdlib/task/src/main/ballerina/src/task/task_errors.bal
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/Module.md
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/xmlutils.bal
Labels: Area/StandardLibs, Component/Task, Type/Docs

#19000 Fix the Api doc issues in Encoding module
  stdlib/encoding/src/main/ballerina/src/encoding/Module.md
  stdlib/encoding/src/main/ballerina/src/encoding/encoding.bal
  stdlib/encoding/src/main/ballerina/src/encoding/encoding_errors.bal
Labels: Area/StandardLibs

#19009 Improve docs related to security related modules
  stdlib/auth/src/main/ballerina/src/auth/Module.md
  stdlib/auth/src/main/ballerina/src/auth/auth_errors.bal
  stdlib/auth/src/main/ballerina/src/auth/inbound_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/inbound_basic_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/outbound_basic_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/utils.bal
  stdlib/crypto/src/main/ballerina/src/crypto/Module.md
  stdlib/crypto/src/main/ballerina/src/crypto/crypto.bal
  stdlib/crypto/src/main/ballerina/src/crypto/crypto_errors.bal
  stdlib/http/src/main/ballerina/src/http/auth/authn_filter.bal
  stdlib/http/src/main/ballerina/src/http/auth/authz_filter.bal
  stdlib/http/src/main/ballerina/src/http/auth/basic_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/bearer_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/inbound_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/outbound_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/utils.bal
  stdlib/http/src/main/ballerina/src/http/client_endpoint.bal
  stdlib/http/src/main/ballerina/src/http/service_endpoint.bal
  stdlib/jwt/src/main/ballerina/src/jwt/Module.md
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_common.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_issuer.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/ldap/src/main/ballerina/src/ldap/inbound_ldap_auth_provider.bal
  stdlib/ldap/src/main/ballerina/src/ldap/ldap_errors.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/oauth2_errors.bal
Labels: Area/StandardLibs, Type/Docs, Type/Improvement

#19057 Add a test case for serialization of a complex XML
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/HttpClientRequest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/HttpBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/SerializeComplexXmlTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/ComplexTestXmlSample.xml
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/41_serialize_xml.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#19081 Fix the issue of created ErrorValues getting replaced by GenericListenerError
  stdlib/http/src/main/java/org/ballerinalang/net/http/serviceendpoint/InitEndpoint.java
Labels: Area/StandardLibs
