Repository ballerina-platform/ballerina-lang, pull requests merged in 2019-05, with the labels that each got.

#15185 Support service type with BIR
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
Labels: Area/Language, Component/jBallerina, Type/Task

#15187 Set codeAction Kind for QuickFixes
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#15095 Update testerina.md with the latest language changes
  misc/testerina/README.md
Labels: Type/Improvement

#15183 Add finite types support for jballerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BFiniteType.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/FiniteTypeTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/finite-type.bal
Labels: Area/Language, Component/jBallerina

#15176 Add initial implementation of Table's BIR Model
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BFutureType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/TypeVisitor.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  stdlib/bir/src/main/ballerina/bir/serializer.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
  stdlib/bir/src/test/resources/test-src/bir/types.bal
  tests/ballerina-unit-test/src/test/resources/test-src/bir/bir_model.bal
Labels: Area/Language, Component/jBallerina, Type/NewFeature

#15197 Add closures support in jBallerina
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/jvm/src/main/ballerina/jvm/types.bal
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/ASMUtil.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/methodvisitor/VisitInvokeDynamicInsn.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/AnonymousFunctionsTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/anon-funcs.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15194 Introduce typeof operator
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypedescType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/symbols/SymbolKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/OperatorKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typeof/TypeofOverLiteralExpressionTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/expressions/typeof/typeof.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/Compiler, Component/jBallerina

#15198 Move extern function filter logic within function generation
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/main.bal
Labels: Area/Language, Component/jBallerina, Type/Improvement

#15200 Support unary not operator
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina, Type/Task

#15113 Fix generating invalid data provider value
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/ValueSpaceGenerator.java
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#15209 Add workers support in jBallerina
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/AnonymousFunctionsTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/anon-funcs.bal
Labels: Area/Language, Component/jBallerina

#15218 Fix OAuth2 Client Integration Tests
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthBaseTest.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/auth/OAuthConfigTest.java
  tests/ballerina-integration-test/src/test/resources/auth/authservices/18_oauth_client_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/mock-oauth-service.bal
  tests/ballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Type/Improvement

#15245 Enable unit tests written for Elvis and mod operators in jBallerina
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  tests/ballerina-unit-test/src/test/resources/testng.xml
Labels: Component/UnitTest, Component/jBallerina

#15226 Add Table related value classes to JVM backend
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/ColumnDefinition.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/DataIterator.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableConstants.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableProvider.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableResourceManager.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTableType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/CollectionValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableIterator.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/ballerina-unit-test/src/test/resources/test-src/jvm/types.bal
Labels: Area/Language, Component/jBallerina

#15243 Add formatting support for named args, Rest args and record destructure
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingNodeTree.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/Tokens.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/bindingPatterns.bal
  language-server/modules/langserver-core/src/test/resources/formatting/errorVariableDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/errorVariableReference.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedBindingPatterns.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorVariableDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorVariableReference.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedNamedArgsExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedRecordDestructure.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedRestArgsExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/namedArgsExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/recordDestructure.bal
  language-server/modules/langserver-core/src/test/resources/formatting/restArgsExpr.bal
Labels: Component/Formatting

#15259 Initial Jballerina runtime and Tools Distributions
  bvm/ballerina-core/src/main/java/org/ballerinalang/util/BLangConstants.java
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  distribution/zip/jballerina-tools/COPYRIGHT
  distribution/zip/jballerina-tools/LICENSE
  distribution/zip/jballerina-tools/README.md
  distribution/zip/jballerina-tools/bin/version.txt
  distribution/zip/jballerina-tools/build.gradle
  distribution/zip/jballerina-tools/conf/log4j2.xml
  distribution/zip/jballerina-tools/conf/netty-transports.yml
  distribution/zip/jballerina-tools/pom.xml
  distribution/zip/jballerina-tools/resources/language-server-launcher.bat
  distribution/zip/jballerina-tools/resources/language-server-launcher.sh
  distribution/zip/jballerina-tools/src/assembly/bin.xml
  distribution/zip/jballerina-tools/src/assembly/filter.properties
  distribution/zip/jballerina/COPYRIGHT
  distribution/zip/jballerina/LICENSE
  distribution/zip/jballerina/README.md
  distribution/zip/jballerina/bin/jballerina
  distribution/zip/jballerina/bin/jballerina.bat
  distribution/zip/jballerina/bin/version.txt
  distribution/zip/jballerina/build.gradle
  distribution/zip/jballerina/pom.xml
  distribution/zip/jballerina/resources/security/ballerinaKeystore.p12
  distribution/zip/jballerina/resources/security/ballerinaTruststore.p12
  distribution/zip/jballerina/src/assembly/bin.xml
  distribution/zip/jballerina/src/assembly/filter.properties
  pom.xml
  settings.gradle
Labels: Component/jBallerina, Type/Task

#15263 Fix filepath test failures in windows
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/nativeimpl/Resolve.java
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/nativeimpl/PathTest.java
Labels: Area/StandardLibs

#15251 Update records BBE to comply with the latest spec changes
  examples/records/records.bal
  examples/records/tests/records_test.bal
Labels: Component/Examples, Type/Docs, Type/Improvement

#15270 Add worker send/receive support in jBallerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Scheduler.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Strand.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/WDChannels.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/WorkerDataChannel.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/WorkerUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ChannelDetails.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangWorkerSend.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/ballerina-tools-integration-test/src/test/java/org/ballerinalang/test/run/JarRunFunctionPositiveTestCase.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/jBal-workers.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15268 Fix XML qname
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  stdlib/system/src/test/java/org/ballerinalang/stdlib/system/SystemTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/xml.bal
Labels: Area/Language, Component/jBallerina

#15260 Add streams values and types for JBallerina implementation
  bvm/ballerina-runtime/build.gradle
  bvm/ballerina-runtime/pom.xml
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/streams/DefaultStreamSubscription.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/streams/SiddhiStreamSubscription.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/streams/StreamSubscription.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/streams/StreamSubscriptionManager.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BStreamType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/TypeVisitor.java
  stdlib/bir/build.gradle
  stdlib/bir/pom.xml
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  stdlib/bir/src/main/ballerina/bir/serializer.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
  stdlib/bir/src/test/resources/test-src/bir/types.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/ballerina-unit-test/src/test/resources/test-src/bir/bir_model.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir_model.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal
Labels: Area/Language, Component/jBallerina

#15261 Add socket read timeout implementation
  CHANGELOG.md
  stdlib/socket/build.gradle
  stdlib/socket/pom.xml
  stdlib/socket/src/main/ballerina/socket/client_socket.bal
  stdlib/socket/src/main/ballerina/socket/listener_endpoint.bal
  stdlib/socket/src/main/ballerina/socket/udp_client_socket.bal
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/SocketConstants.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/InitEndpoint.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/client/Read.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/InitServer.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/tcp/server/Register.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/InitEndpoint.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/endpoint/udp/client/ReceiveFrom.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/ReadPendingCallback.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/ReadPendingSocketMap.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/ReadReadySocketMap.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SelectorManager.java
  stdlib/socket/src/main/java/org/ballerinalang/stdlib/socket/tcp/SocketService.java
  stdlib/socket/src/test/java/org/ballerinalang/stdlib/socket/ServerSocketTest.java
  stdlib/socket/src/test/resources/test-src/server_socket.bal
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/socket/SocketBaseTest.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/socket/SocketClientCallbackServiceTestCase.java
  tests/ballerina-integration-test/src/test/resources/socket/services/03_server_read_timeout.bal
Labels: Area/StandardLibs, Type/Improvement

#15289 Add support for ternary expression and string-template literals in jballerina
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15288 Add formatting for checkpanic and expand anon record
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingNodeTree.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingSourceGen.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/Tokens.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/anonRecord.bal
  language-server/modules/langserver-core/src/test/resources/formatting/check.bal
  language-server/modules/langserver-core/src/test/resources/formatting/checkPanic.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedAnonRecord.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedCheck.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedCheckPanic.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedInvocation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedRecord.bal
  language-server/modules/langserver-core/src/test/resources/formatting/invocation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/record.bal
  language-server/modules/langserver-core/src/test/resources/formatting/wait.bal
Labels: Area/Tooling, Component/Formatting

#15297 Remove runtime dependency getting packed into generated jar
  compiler/ballerina-backend-jvm/src/main/java/org/ballerinalang/compiler/backend/jvm/JVMCodeGen.java
Labels: Component/jBallerina, Type/Task

#15258 Fix language server not picking up pre-shipped jvm
  distribution/zip/ballerina-tools/resources/language-server-launcher.bat
  distribution/zip/ballerina-tools/resources/language-server-launcher.sh
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#15302 Support reference equality binary operator (===, !==) in jBallerina
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina, Type/Task

#15313 Fix ClientInitializationFailureTest failing on Windows
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/ClientInitializationFailureTest.java
Labels: Area/StandardLibs

#15306 Add Sync send support in jBallerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/WorkerDataChannel.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/jBal-workers.bal
Labels: Area/Language, Component/jBallerina

#15298 LS Add A Code Action To Fix Return Type Signature
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fixReturnType1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fixReturnType2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fixReturnType3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignoreReturnValueCodeAction.json
  language-server/modules/langserver-core/src/test/resources/codeaction/source/fixReturnType.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/undefinedFunctionCodeAction.json
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction.json
Labels: Area/Tooling, Component/LanguageServer, Type/NewFeature

#15312 Support Stamp,convert,length and error related built in methods
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLFactory.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BRecordType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/BLangConstants.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/exceptions/BallerinaErrorReasons.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/IteratorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/RefValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLAttributes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLQName.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Clone.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Convert.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Detail.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Freeze.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/IsFrozen.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Length.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Reason.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/SimpleValueConvert.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Stamp.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typeof/TypeofOverLiteralExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ModuleTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15305 Add constant reference support for jballerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BServiceType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ValueCreator.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BFileUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantAccessTest.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15325 Support object, array equivalency along with tests
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BFiniteType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BObjectType.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina, Type/Task

#15326 Add Flush action support in jBallerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Strand.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/WorkerDataChannel.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/jBal-workers.bal
Labels: Area/Language, Component/jBallerina

#15318 Rearranging BBE and wordings
  examples/index.json
Labels: Component/Examples

#15317 Refactor inbound authentication
  stdlib/auth/src/main/ballerina/auth/config_auth_store_provider.bal
  stdlib/auth/src/main/ballerina/auth/jwt_auth_provider.bal
  stdlib/auth/src/main/ballerina/auth/ldap_auth_store_provider.bal
  stdlib/auth/src/main/java/org/ballerinalang/auth/ldap/nativeimpl/Authenticate.java
  stdlib/auth/src/main/java/org/ballerinalang/auth/ldap/nativeimpl/GetLdapScopesOfUser.java
  stdlib/auth/src/main/java/org/ballerinalang/auth/ldap/nativeimpl/InitLdapConnectionContext.java
  stdlib/auth/src/test/java/org/ballerinalang/stdlib/auth/jwt/JwtTest.java
  stdlib/http/src/main/ballerina/http/auth/basic_authn_handler.bal
  stdlib/http/src/main/ballerina/http/auth/jwt_authn_handler.bal
Labels: Area/StandardLibs, Type/Improvement

#15342 Introduce blockedOnExtern flag to handle block/resume in externs
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Strand.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/NonBlockingCallback.java
  cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
Labels: Component/jBallerina, Type/Task

#15300 Add decimal type and value support to Ballerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/DecimalValueKind.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/DecimalValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/serializer.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
  stdlib/bir/src/test/resources/test-src/bir/types.bal
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/maplib/GetKeys.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir_model.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_value.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15339 Migrate Math module into JVM types/values
  stdlib/math/build.gradle
  stdlib/math/pom.xml
  stdlib/math/src/main/ballerina/math/natives.bal
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/AbsFloat.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/AbsInt.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Acos.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Asin.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Atan.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Atan2.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Cbrt.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Ceil.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/CopySign.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Cos.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Cosh.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Exp.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Expm1.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Exponent.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Floor.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/FloorDiv.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/FloorMod.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Hypot.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/IEEERemainder.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Log.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Log10.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Log1p.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NegateExact.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NextAfter.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NextDown.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NextUp.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Pow.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Random.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/RandomInRange.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Rint.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Round.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Scalb.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Signum.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Sin.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Sinh.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Sqrt.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Tan.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Tanh.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/ToDegrees.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/ToRadians.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Ulp.java
Labels: Area/StandardLibs, Component/jBallerina

#15340 Migrate System module into JVM types/values
  stdlib/system/build.gradle
  stdlib/system/pom.xml
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetCurrentDirectory.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetEnv.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUserHome.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUsername.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Uuid.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/utils/SystemUtils.java
Labels: Area/StandardLibs, Component/jBallerina

#15341 Migrate Encoding module into JVM types/values
  stdlib/encoding/build.gradle
  stdlib/encoding/pom.xml
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/EncodingUtil.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/ByteArrayToString.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/DecodeBase64.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/DecodeBase64Url.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/DecodeHex.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/EncodeBase64.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/EncodeBase64Url.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/EncodeHex.java
Labels: Area/StandardLibs, Component/jBallerina

#15349 Migrate Time module into JVM types/values
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  stdlib/time/build.gradle
  stdlib/time/pom.xml
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/AbstractTimeFunction.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/AddDuration.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/CreateTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/CurrentTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Day.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Format.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/GetDate.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/GetTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Hour.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/MilliSecond.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Minute.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Month.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/NanoTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Parse.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Second.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/SubtractDuration.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/ToString.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/ToTimeZone.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/WeekDay.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Year.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/util/TimeUtils.java
Labels: Area/StandardLibs, Component/jBallerina

#15350 Fix object attached extern function non-blocking logic generation
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
Labels: Component/jBallerina, Type/Task

#15335 Migrate Auth module into JVM types/values
  stdlib/auth/build.gradle
  stdlib/auth/pom.xml
  stdlib/auth/src/main/java/org/ballerinalang/auth/ldap/nativeimpl/Authenticate.java
  stdlib/auth/src/main/java/org/ballerinalang/auth/ldap/nativeimpl/GetLdapScopesOfUser.java
  stdlib/auth/src/main/java/org/ballerinalang/auth/ldap/nativeimpl/InitLdapConnectionContext.java
Labels: Area/StandardLibs, Component/jBallerina

#15338 Migrate Config API module into JVM types/values
  stdlib/config-api/build.gradle
  stdlib/config-api/pom.xml
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/Contains.java
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/GetConfig.java
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/SetConfig.java
Labels: Area/StandardLibs, Component/jBallerina

#15328 Add formatting support for fork
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  language-server/modules/langserver-core/build.gradle
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingNodeTree.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/Tokens.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedForkJoin.bal
  language-server/modules/langserver-core/src/test/resources/formatting/forkJoin.bal
Labels: Area/Tooling, Component/Formatting

#15337 Migrate File module into JVM types/values
  bvm/ballerina-runtime/spotbugs-exclude.xml
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Strand.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/exceptions/BallerinaConnectorException.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/CallableUnitCallback.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/Executor.java
  stdlib/file/build.gradle
  stdlib/file/pom.xml
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/DirectoryCallback.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/FSListener.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/InitEndpoint.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Register.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/service/endpoint/Start.java
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/utils/FileUtils.java
Labels: Area/StandardLibs, Component/jBallerina

#15346 Migrate Crypto module into JVM types/values
  stdlib/crypto/build.gradle
  stdlib/crypto/pom.xml
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/CryptoUtils.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Crc32b.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecodePrivateKey.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecodePublicKey.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecryptAesCbc.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecryptAesEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecryptAesGcm.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecryptRsaEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/EncryptAesCbc.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/EncryptAesEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/EncryptAesGcm.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/EncryptRsaEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashMd5.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashSha1.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashSha256.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashSha384.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashSha512.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacMd5.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacSha1.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacSha256.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacSha384.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacSha512.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaMd5.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha1.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha256.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha384.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha512.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaMd5Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha1Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha256Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha384Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha512Signature.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/util/TimeUtils.java
Labels: Area/StandardLibs, Component/jBallerina

#15369 Fix and enable function pointer tests
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
Labels: Component/jBallerina, Type/Task

#15368 Migrate Log-API module into JVM types/values
  stdlib/log-api/build.gradle
  stdlib/log-api/pom.xml
  stdlib/log-api/src/main/java/org/ballerinalang/stdlib/log/AbstractLogFunction.java
  stdlib/log-api/src/main/java/org/ballerinalang/stdlib/log/LogDebug.java
  stdlib/log-api/src/main/java/org/ballerinalang/stdlib/log/LogError.java
  stdlib/log-api/src/main/java/org/ballerinalang/stdlib/log/LogInfo.java
  stdlib/log-api/src/main/java/org/ballerinalang/stdlib/log/LogTrace.java
  stdlib/log-api/src/main/java/org/ballerinalang/stdlib/log/LogWarn.java
Labels: Area/StandardLibs, Component/jBallerina

#15371 Migrate Reflect module into JVM types/values
  stdlib/reflect/build.gradle
  stdlib/reflect/pom.xml
  stdlib/reflect/src/main/java/org/ballerinalang/stdlib/reflect/nativeimpl/AbstractAnnotationReader.java
  stdlib/reflect/src/main/java/org/ballerinalang/stdlib/reflect/nativeimpl/GetFieldAnnotations.java
  stdlib/reflect/src/main/java/org/ballerinalang/stdlib/reflect/nativeimpl/GetFunctionAnnotations.java
  stdlib/reflect/src/main/java/org/ballerinalang/stdlib/reflect/nativeimpl/GetResourceAnnotations.java
  stdlib/reflect/src/main/java/org/ballerinalang/stdlib/reflect/nativeimpl/GetServiceAnnotations.java
  stdlib/reflect/src/main/java/org/ballerinalang/stdlib/reflect/nativeimpl/GetStructAnnotations.java
Labels: Area/StandardLibs, Component/jBallerina

#15365 Migrate Runtime-API module into JVM types/values
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  stdlib/runtime-api/build.gradle
  stdlib/runtime-api/pom.xml
  stdlib/runtime-api/src/main/ballerina/runtime/errors.bal
  stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/AuthenticationContext.java
  stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/GetCallStack.java
  stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/GetErrorCallStackFrame.java
  stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/GetInvocationContext.java
  stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/GetProperty.java
  stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/InvocationContext.java
  stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/InvocationContextUtils.java
  stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/Sleep.java
  stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl/UserPrincipal.java
Labels: Area/StandardLibs, Component/jBallerina

#15347 Migrate Task module into JVM types/values
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/Executor.java
  stdlib/task/build.gradle
  stdlib/task/pom.xml
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/DetachService.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Pause.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Resume.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/impl/TaskServerConnectorImpl.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/AbstractTask.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/Appointment.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/ServiceWithParameters.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/Task.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/Timer.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/service/Init.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/service/Register.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/service/Start.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/service/Stop.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/ResourceFunctionHolder.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/TaskExecutor.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/TaskJob.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/Utils.java
Labels: Area/StandardLibs, Component/jBallerina

#15359 Add prior knowledge support to ballerina HTTP/2 client
  distribution/zip/ballerina/build.gradle
  distribution/zip/jballerina/build.gradle
  gradle/javaProject.gradle
  pom.xml
  stdlib/http/src/main/ballerina/http/client_endpoint.bal
  stdlib/http/src/main/ballerina/http/http_headers.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/clientendpoint/CreateSimpleHttpClient.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2PriorKnowledgeTestCase.java
  tests/ballerina-integration-test/src/test/resources/http2/http2services/http_2.0_prior_knowledge_test.bal
  tests/ballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/HTTP2

#15336 Add constants to BIR with basic literal support
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
Labels: Component/jBallerina, Type/NewFeature

#15383 Fix function invocation issue with lock param and enable few tests
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/IOBasicTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/io-basics.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina, Type/Task

#15393 Support range operator
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15343 Handle exceptions occurred via scheduler in main method
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_error_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
Labels: Area/Language, Component/jBallerina, Type/Improvement

#15406 Add formatting support for typedesc expression and anon types
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingNodeTree.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/formatting/FormattingSourceGen.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/anonObject.bal
  language-server/modules/langserver-core/src/test/resources/formatting/anonRecord.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedAnonObject.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedAnonRecord.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFunction.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedObject.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTypeDesc.bal
  language-server/modules/langserver-core/src/test/resources/formatting/function.bal
  language-server/modules/langserver-core/src/test/resources/formatting/object.bal
  language-server/modules/langserver-core/src/test/resources/formatting/typeDesc.bal
Labels: Area/Tooling, Component/Formatting

#15401 Fix stdlib test modules by using ballerina-test-utils dependency for jBallerina based tests
  cli/ballerina-packerina/build.gradle
  cli/ballerina-packerina/pom.xml
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/BuilderUtils.java
  compiler/ballerina-backend-jvm/build.gradle
  compiler/ballerina-backend-jvm/pom.xml
  compiler/ballerina-backend-jvm/src/main/java/org/ballerinalang/compiler/backend/jvm/JVMCodeGen.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/spi/CompilerBackendCodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BackendCodeGeneratorProvider.java
  stdlib/io/build.gradle
  stdlib/io/pom.xml
  stdlib/io/src/test/java/org/ballerinalang/stdlib/io/IOPrintTest.java
  stdlib/io/src/test/java/org/ballerinalang/stdlib/io/IOTest.java
  stdlib/io/src/test/java/org/ballerinalang/stdlib/io/data/DataChannelTest.java
  stdlib/io/src/test/java/org/ballerinalang/stdlib/io/records/CsvChannelTest.java
  tests/ballerina-test-utils/build.gradle
  tests/ballerina-test-utils/pom.xml
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bir/BIRModelTest.java
Labels: Component/jBallerina, Type/Task

#15407 Enable all the tests for JVM backed Decimal Type
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/DecimalValue.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_value.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15408 Support untaint and add unary ops with tests enabled
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLFactory.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/tablelib/Add.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/BinaryExprEvalPrecedenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/DivisionOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/ModOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina, Type/Task

#15409 Support tool integration tests to run on jballerina distribution.
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BServerInstance.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BalServer.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/Constant.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/listener/JBallerinaTestInitializer.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/ballerina-tools-integration-test/build.gradle
  tests/ballerina-tools-integration-test/pom.xml
  tests/ballerina-tools-integration-test/src/test/java/org/ballerinalang/test/JBallerinaBaseTest.java
  tests/ballerina-tools-integration-test/src/test/java/org/ballerinalang/test/jvm/JarRunFunctionPositiveTestCase.java
  tests/ballerina-tools-integration-test/src/test/resources/run/jar/test_main_for_jvm_target.bal
  tests/ballerina-tools-integration-test/src/test/resources/testng.xml
  tests/ballerina-unit-test/src/test/resources/testng.xml
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/utils/JBallerinaTestInitializer.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina, Type/Improvement

#15415 Enable builtin operation package unit tests for jballerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  stdlib/builtin/src/main/java/org/ballerinalang/nativeimpl/builtin/tablelib/Add.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Clone.java
  stdlib/utils/src/main/java/org/ballerinalang/utils/Detail.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/CloneOperationTest.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina, Type/Improvement

#15416 Fix jar is not creating properly when source file name and module name is equal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/test.math/test.math.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/test.math/test.math2.bal
Labels: Area/Language, Component/jBallerina, Type/Bug

#15420 Fix LS test failure
  language-server/modules/langserver-core/src/test/resources/workspace/project/.ballerina/readme.txt
  language-server/modules/langserver-core/src/test/resources/workspace/project/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/workspace/project/pkg1/pkg1Source.bal
  language-server/modules/langserver-core/src/test/resources/workspace/project/pkg2/pkg2Source.bal
  language-server/modules/langserver-core/src/test/resources/workspace/workspaceSymbol.json
  language-server/modules/langserver-core/src/test/resources/workspace/workspaceSymbolWithQuery.json
Labels: Area/Tooling, Component/LanguageServer

#15423 Fix sender config issue with multiple clients defined in global scope
  stdlib/http/src/main/java/org/ballerinalang/net/http/clientendpoint/CreateSimpleHttpClient.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/HttpBaseTest.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/MultipleHTTPClientsTestCase.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2BaseTest.java
  tests/ballerina-integration-test/src/test/resources/http/httpservices/30_multiple_http_clients.bal
  tests/ballerina-integration-test/src/test/resources/http2/http2services/04_http_2.0_prior_knowledge_test.bal
  tests/ballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/HTTP

#15422 Add support for bitwise operations &, |, ^, ~, >>, <<, >>>
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
Labels: Component/jBallerina, Type/Task

#15424 [JMS] Rename Receiver/Subscriber to Listener
  examples/jms-durable-topic-message-subscriber/jms_durable_topic_message_subscriber.bal
  examples/jms-headers-and-properties/jms_headers_and_properties.bal
  examples/jms-queue-message-receiver-with-client-acknowledgment/jms_queue_message_receiver_with_client_acknowledgment.bal
  examples/jms-queue-message-receiver/jms_queue_message_receiver.bal
  examples/jms-simple-durable-topic-message-subscriber/jms_simple_durable_topic_message_subscriber.bal
  examples/jms-simple-queue-message-receiver/jms_simple_queue_message_receiver.bal
  examples/jms-simple-topic-message-subscriber/jms_simple_topic_message_subscriber.bal
  examples/jms-synchronous-queue-message-receiver/jms_synchronous_queue_message_receiver.bal
  examples/jms-topic-message-subscriber/jms_topic_message_subscriber.bal
  examples/send-jms-message-to-http-endpoint/send_jms_message_to_http_endpoint.bal
  stdlib/jms/src/main/ballerina/jms/Module.md
  stdlib/jms/src/main/ballerina/jms/durable_topic_subscriber.bal
  stdlib/jms/src/main/ballerina/jms/queue_receiver.bal
  stdlib/jms/src/main/ballerina/jms/topic_subscriber.bal
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/JmsConstants.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/queue/receiver/Start.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/topic/durable/subscriber/Start.java
  stdlib/jms/src/main/java/org/ballerinalang/net/jms/nativeimpl/endpoint/topic/subscriber/Start.java
Labels: Area/StandardLibs, Component/Messaging

#15363 Introduce Configuration Pattern for Authn Handlers and Scopes
  stdlib/http/src/main/ballerina/http/annotation.bal
  stdlib/http/src/main/ballerina/http/auth/authn_filter.bal
  stdlib/http/src/main/ballerina/http/auth/authz_filter.bal
  stdlib/http/src/main/ballerina/http/auth/authz_handler.bal
  stdlib/http/src/main/ballerina/http/auth/utils.bal
  stdlib/http/src/main/ballerina/http/service_endpoint.bal
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthBaseTest.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnConfigPatternTest.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthzCacheTest.java
  tests/ballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthzConfigPatternTest.java
  tests/ballerina-integration-test/src/test/resources/auth/authservices/02_authz_config_inheritance_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/07_authz_with_cache_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/19_authn_config_pattern_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/authservices/20_authz_config_pattern_test.bal
  tests/ballerina-integration-test/src/test/resources/auth/ballerina.conf
  tests/ballerina-integration-test/src/test/resources/testng.xml
  tests/ballerina-integration-test/src/test/resources/websub/advanced_services/01_websub_publisher.bal
Labels: Area/StandardLibs, Type/Improvement

#15421 Enable possible IO module test cases
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  stdlib/io/build.gradle
  stdlib/io/pom.xml
  stdlib/io/src/test/java/org/ballerinalang/stdlib/io/IOTest.java
  stdlib/io/src/test/java/org/ballerinalang/stdlib/io/data/DataChannelTest.java
  stdlib/io/src/test/java/org/ballerinalang/stdlib/io/records/CsvChannelTest.java
  stdlib/io/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15377 Add wait for all and wait for alternate future support in jBallerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Scheduler.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Strand.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/WorkerDataChannel.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FutureValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/NonBlockingCallback.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/WorkerTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/NotSoBasicWorkerTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAnyActionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFlushTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/jBal-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/flush-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Component/jBallerina

#15437 Add support for optional flags in BIR for records, objects
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/MapUtils.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/Visibility.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/VisibilityFlags.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/bir/src/main/ballerina/bir/type_parser.bal
Labels: Component/jBallerina, Type/Task

#15440 Support expressions for function argument default values
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_desugar_phase.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGenEnv.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BVarSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangExpression.java
  stdlib/bir/build.gradle
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/bir_pkg_parser.bal
  stdlib/bir/src/main/ballerina/bir/channel_io.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableArguments.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectFunctionsWithDefaultableArguments.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_functions_with_default_parameters.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/jBallerina, Type/NewFeature

#15443 Fix ternary operator
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/bir/ins_codes.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/Compiler, Component/jBallerina

#15451 Add support for service type object generation
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/Strand.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/AttachedFunction.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/Executor.java
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  stdlib/bir/src/main/ballerina/bir/bir_emitter.bal
  stdlib/bir/src/main/ballerina/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/bir/bir_model.bal
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/DetachService.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ObjectSubtypingTest.java
Labels: Component/jBallerina, Type/Task

#15454 Fix the issue related to records fields gone missing
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java
Labels: Component/jBallerina
