Repository ballerina-platform/ballerina-lang, pull requests merged in 2019-11, with the labels that each got.

#19646 Allow overridding the generated CMD of Dockerfile
  stdlib/docker/src/main/ballerina/src/docker/annotation.bal
  stdlib/kubernetes/src/main/ballerina/src/kubernetes/annotation.bal
Labels: Area/BuildTools

#19672 [WebSub] Introduce improvements
  stdlib/websub/src/main/ballerina/src/websub/commons.bal
  stdlib/websub/src/main/ballerina/src/websub/hub_service.bal
  stdlib/websub/src/main/ballerina/src/websub/natives.bal
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/hub/Hub.java
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/nativeimpl/RemoveNativeSubscription.java
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/nativeimpl/StopHubService.java
  stdlib/websub/src/test/java/org.ballerinalang.net.websub/WebSubHubStartTest.java
  stdlib/websub/src/test/resources/test-src/hub/test_hub_startup.bal
  stdlib/websub/src/test/resources/testng.xml
Labels: Area/StandardLibs

#19676 Add test for subscription removal via websub:Hub
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websub/basic/WebSubCoreFunctionalityTestCase.java
  tests/jballerina-integration-test/src/test/resources/websub/publisher/src/services/01_websub_publisher.bal
Labels: Area/StandardLibs

#19677 Improve logs and fix concurrent modification issue
  stdlib/websub/src/main/ballerina/src/websub/annotation.bal
  stdlib/websub/src/main/ballerina/src/websub/commons.bal
  stdlib/websub/src/main/ballerina/src/websub/hub_service.bal
  stdlib/websub/src/main/ballerina/src/websub/subscriber_service_endpoint.bal
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberConstants.java
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/hub/Hub.java
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/nativeimpl/RetrieveSubscriptionParameters.java
Labels: Area/StandardLibs, Component/WebSub, Type/Improvement

#19685 Fix a bug in authz
  stdlib/auth/src/main/ballerina/src/auth/utils.bal
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
Labels: Area/StandardLibs, Type/Bug

#19700 Update websub BBEs
  examples/websub-hub-client-sample/publisher.bal
  examples/websub-hub-client-sample/publisher.out
  examples/websub-hub-client-sample/subscriber_service.bal
  examples/websub-hub-client-sample/subscriber_service.out
  examples/websub-hub-client-sample/subscription_change_client.bal
  examples/websub-internal-hub-sample/publisher.bal
  examples/websub-internal-hub-sample/publisher.out
  examples/websub-internal-hub-sample/subscriber.out
  examples/websub-remote-hub-sample/hub.bal
  examples/websub-remote-hub-sample/hub.out
  examples/websub-remote-hub-sample/publisher.bal
  examples/websub-remote-hub-sample/subscriber.out
  examples/websub-service-integration-sample/order_mgmt_service.server.out
  examples/websub-service-integration-sample/subscriber.out
  stdlib/websub/src/main/ballerina/src/websub/commons.bal
  stdlib/websub/src/test/resources/test-src/hub/test_hub_startup.bal
  stdlib/websub/src/test/resources/test-src/specific_subscriber/test_specific_subscriber.bal
Labels: Area/StandardLibs, Component/Examples, Component/WebSub

#19636 Review HTTP-Related BBEs
  examples/http-disable-chunking/http_disable_chunking.bal
  examples/http-disable-chunking/http_disable_chunking.client.out
  examples/http-disable-chunking/http_disable_chunking.description
  examples/http-disable-chunking/http_disable_chunking.server.out
  examples/https-listener/https_listener.bal
  examples/https-listener/https_listener.client.out
  examples/https-listener/https_listener.server.out
  examples/mutual-ssl/mutual_ssl.description
  examples/mutual-ssl/mutual_ssl_service.bal
  examples/mutual-ssl/mutual_ssl_service.out
  examples/mutual-ssl/ssl_client.bal
  examples/mutual-ssl/ssl_client.out
  examples/restrict-by-media-type/restrict_by_media_type.bal
  examples/restrict-by-media-type/restrict_by_media_type.client.out
  examples/restrict-by-media-type/restrict_by_media_type.description
  examples/restrict-by-media-type/restrict_by_media_type.server.out
Labels: Type/Docs

#19664 Add the --experimental Flag to Help Text
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-build.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-run.help
Labels: Type/Docs

#19491 Fix issues with worker receive
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerSyncSendExpr.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerSyncSendTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-receive-with-check.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-receive-with-trap.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid_receive_with_checkpanic_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/sync-send.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/sync_send_receive_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Area/Language

#19729 Update nats docs
  examples/nats-basic-client/publisher.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/Module.md
Labels: Area/StandardLibs, Component/Messaging

#19532 Add missing pos and WS to identifier node
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangIdentifier.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangXMLQName.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/proto/ServiceProtoBuilder.java
Labels: Area/Language, Type/Improvement

#19750 Fix a bug in basic auth secured service bbe
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.description
Labels: Area/StandardLibs, Component/Auth, Type/Bug

#19584 Allow record binding patterns within a tuple binding pattern
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangAnonymousModelHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleDestructureTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal
Labels: Area/Language

#19805 Update link to NATS Installation
  examples/nats-basic-client/nats_basic_client.description
Labels: Area/StandardLibs, Type/Docs

#19789 Upgrade http-transport version
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
Labels: Area/StandardLibs

#19801 Fix ConcurrentModificationException found in Jaeger tracing
  bvm/ballerina-rt/build.gradle
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  misc/tracing-extensions/modules/ballerina-jaeger-extension/build.gradle
  misc/tracing-extensions/modules/ballerina-jaeger-extension/src/main/java/org/ballerinalang/observe/trace/extension/jaeger/OpenTracingExtension.java
Labels: Area/Observability

#19787 Add RabbitMQ examples to the json file
  examples/index.json
Labels: Area/StandardLibs, Component/Messaging

#19776 Migrate encoding module into java interoperability
  gradle/birProject.gradle
  stdlib/encoding/build.gradle
  stdlib/encoding/src/main/ballerina/Ballerina.toml
  stdlib/encoding/src/main/ballerina/src/encoding/encoding.bal
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/DecodeBase64Url.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/DecodeUriComponent.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/EncodeBase64Url.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/EncodeUriComponent.java
  stdlib/jwt/build.gradle
  stdlib/websub/build.gradle
Labels: Area/StandardLibs, Component/Encoding, Type/Improvement

#19817 Update github actions script
  .github/workflows/gradle.yml
Labels: Type/Improvement

#19820 Fix CSV reading with double quoted values
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/channels/base/DelimitedRecordChannel.java
  stdlib/io/src/main/java/org/ballerinalang/stdlib/io/csv/Format.java
  stdlib/io/src/test/java/org/ballerinalang/stdlib/io/records/CsvChannelTest.java
  stdlib/io/src/test/resources/datafiles/io/records/sampleRfc.csv
Labels: Area/StandardLibs

#19630 Improve taint propagation analysis for 'check' expressions
  cli/ballerina-cli-module-pull/src/main/ballerina/src/module_pull/module_pull.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  stdlib/http/src/main/ballerina/src/http/resiliency/http_retry_client.bal
  stdlib/http/src/test/resources/test-src/services/echo-service.bal
  stdlib/io/src/test/resources/test-src/io/char_io.bal
  stdlib/io/src/test/resources/test-src/io/data_io.bal
  stdlib/io/src/test/resources/test-src/io/record_io.bal
  stdlib/jdbc/src/test/resources/test-src/table/table_type_test.bal
  stdlib/transactions/src/main/ballerina/src/transactions/2pc_participant.bal
  stdlib/transactions/src/main/ballerina/src/transactions/commons.bal
  stdlib/transactions/src/main/ballerina/src/transactions/connector_initiator.bal
  stdlib/transactions/src/main/ballerina/src/transactions/connector_participant_2pc.bal
  tests/jballerina-integration-test/src/test/resources/websub/subscriber/test_subscribers_at_basic_auth_secured_hub.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/TaintedStatusPropagationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/check-expression-negative.bal
Labels: Area/Language

#19781 Fix semantic analysis and narrowed type resetting for binding patterns
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/ErrorVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/RecordVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/TupleVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/error_variable_reference_semantics_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/tuple-variable-reference-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Area/Language

#19855 Handle toml syntax errors for Ballerina.toml
  compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/parser/ManifestProcessor.java
  compiler/ballerina-lang/src/test/java/org/ballerinalang/toml/TomlFileToManifestTest.java
  compiler/ballerina-lang/src/test/resources/invalid-ballerina.toml
Labels: Area/BuildTools, Component/Packerina

#19807 Make sync send-receive mismatch an error
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
Labels: Area/Language

#19867 Disable multi-line strings
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTest.java
Labels: Area/Language

#19293 Add observability metrics, logging and tracing for WebSockets
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/observability/ObserveUtils.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Close.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Ping.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Pong.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/PushBinary.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/PushText.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/websocketconnector/Ready.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketResourceCallback.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketResourceDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/client/InitEndpoint.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/client/WebSocketClientConnectorListener.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/client/WebSocketClientHandshakeListener.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/observability/WebSocketMetricsUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/observability/WebSocketObservabilityConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/observability/WebSocketObservabilityUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/observability/WebSocketObserverContext.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/observability/WebSocketTracingUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/server/WebSocketServerListener.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java
  tests/jballerina-integration-test/src/test/resources/observability/metrics/websocket-metrics-test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#19795 Make Error Details Public
  language-server/modules/langserver-core/src/test/resources/completion/function/functionCompletionWithMissingImport.json
  language-server/modules/langserver-core/src/test/resources/completion/function/returnParameterContextSuggestion3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/returnParameterContextSuggestion6.json
  language-server/modules/langserver-core/src/test/resources/completion/function/returnParameterContextSuggestion9.json
  language-server/modules/langserver-core/src/test/resources/completion/function/varDefStmt1.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore1.json
  stdlib/auth/src/main/ballerina/src/auth/auth_errors.bal
  stdlib/cache/src/main/ballerina/src/cache/cache_errors.bal
  stdlib/crypto/src/main/ballerina/src/crypto/crypto_errors.bal
  stdlib/encoding/src/main/ballerina/src/encoding/encoding_errors.bal
  stdlib/file/src/main/ballerina/src/file/file_errors.bal
  stdlib/filepath/src/main/ballerina/src/filepath/file_path_errors.bal
  stdlib/io/src/main/ballerina/src/io/io_error.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_errors.bal
  stdlib/math/src/main/ballerina/src/math/math_errors.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/error.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/rabbitmq_errors.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/oauth2_errors.bal
  stdlib/socket/src/main/ballerina/src/socket/socket_error.bal
  stdlib/system/src/main/ballerina/src/system/system_errors.bal
  stdlib/task/src/main/ballerina/src/task/task_errors.bal
  stdlib/time/src/main/ballerina/src/time/time_errors.bal
Labels: Area/Tooling, Points/0.5, Type/Docs

#19848 Fix null passing in gRPC service dispatch
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/Message.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/MessageParser.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ServiceDefinition.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/client/InitStub.java
Labels: Area/StandardLibs

#19854 Update error message in run command
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/DocCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/RunCommand.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/CompileFlagWithBuildCommandTest.java
Labels: Area/BuildTools, Component/Packerina, Type/Improvement

#19870 Use java defaults when user hasn't provided trusted certs
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
Labels: Area/StandardLibs, Component/HTTP

#19839 Replace white-spaces in client URL with percent encoding
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/AbstractHTTPAction.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HTTPClientActionsTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/08_http_client_actions.bal
Labels: Area/StandardLibs, Type/Bug

#19783 Fix executable jar creates internal jars with type inflated
  bvm/ballerina-rt/build.gradle
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateExecutableTask.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
  cli/ballerina-packerina/src/test/resources/test-resources/stored-jar-dependency-project/Ballerina.toml
  cli/ballerina-packerina/src/test/resources/test-resources/stored-jar-dependency-project/lib/storedJar.jar
  cli/ballerina-packerina/src/test/resources/test-resources/stored-jar-dependency-project/src/mymodule/main.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/SpiServicesTestCase.java
Labels: Area/BuildTools

#19901 Change toString of BArrayType to use * instead of !.. for closed arrays
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BArrayType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/SealedArrayTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed-array-semantics-negative.bal
Labels: Area/Language

#19875 Improve tuple binding pattern related error messages
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition-negative.bal
Labels: Area/Language, Component/CompilerDiagnostics

#19912 Add error messages to openapi validator
  misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ErrorMessages.java
  misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ValidatorUtil.java
Labels: Area/Tooling

#19880 Fix ballerina run failed to load sql drivers
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/buildcontext/BuildContext.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/model/ExecutableJar.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CompileTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyModuleJarTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyNativeLibTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateBaloTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateExecutableTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateJarTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunTestsTask.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BootstrapRunner.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/util/TestarinaClassLoader.java
  tests/jballerina-integration-test/build.gradle
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/SpiServicesTestCase.java
  tests/jballerina-integration-test/src/test/resources/packaging/spi/TestProject/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/spi/TestProject/libs/drivers.jar
  tests/jballerina-integration-test/src/test/resources/packaging/spi/TestProject/src/module/funcs.bal
Labels: Area/BuildTools

#19909 Upgrade transport version
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
Labels: Area/StandardLibs, Component/HTTP

#19907 [NATS] Migrate native functions to java interoperability
  stdlib/messaging/nats/build.gradle
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/producer.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/subscriber.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/connection/connection.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/listener.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/message.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/producer.bal
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/DefaultMessageHandler.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Detach.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/ErrorHandler.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/GracefulStop.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/ImmediateStop.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Register.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Start.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/CloseConnection.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Publish.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Request.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/Close.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Attach.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Detach.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Subscribe.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/message/Ack.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/producer/CloseConnection.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/producer/CreateStreamingConnection.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/producer/Publish.java
Labels: Area/StandardLibs, Component/Messaging

#19906 Migrate task functions to inter-op
  cli/ballerina-cli-module-pull/build.gradle
  cli/ballerina-cli-module-push/build.gradle
  cli/ballerina-cli-module-search/build.gradle
  cli/ballerina-cli-module-token-update/build.gradle
  misc/metrics-extensions/modules/ballerina-prometheus-extension/build.gradle
  stdlib/auth/build.gradle
  stdlib/cache/build.gradle
  stdlib/cache/src/test/java/org/ballerinalang/stdlib/cache/CacheTest.java
  stdlib/http/build.gradle
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/table/TableTypeTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/transaction/LocalTransactionsTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/transaction/XATransactionsTest.java
  stdlib/jwt/build.gradle
  stdlib/ldap/build.gradle
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/transactions/KafkaProducerTransactionsTest.java
  stdlib/oauth2/build.gradle
  stdlib/streams/build.gradle
  stdlib/task/build.gradle
  stdlib/task/src/main/ballerina/src/task/listener.bal
  stdlib/task/src/main/ballerina/src/task/scheduler.bal
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Detach.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Pause.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Resume.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/TaskActions.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/ServiceInformation.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/service/Init.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/service/Register.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/service/Start.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/service/Stop.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/TaskExecutor.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/Utils.java
  stdlib/transactions/build.gradle
  stdlib/websub/build.gradle
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
Labels: Area/StandardLibs, Component/Task, Type/Improvement

#19926 Add default values to generated record types
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/Message.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/BallerinaFileBuilder.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/components/Field.java
  stdlib/grpc/src/main/resources/templates/skeleton/message.mustache
Labels: Area/StandardLibs, Component/gRPC

#19908 Add rest parameter support for function pointers
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/symbols/SymbolKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompiledPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserBaseListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BInvokableTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/Symbols.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BInvokableType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFunctionTypeNode.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  stdlib/bir-old/src/main/ballerina/src/bir/type_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/type_parser.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/function-pointers-with-optional-args-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/function-pointers-with-optional-args.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/function-pointers.bal
Labels: Area/Language, Area/jBallerina, Type/SpecDeviation

#19936 [NATS] Fix obtaining the runtime
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/DefaultMessageHandler.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/ErrorHandler.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/consumer/Register.java
Labels: Area/StandardLibs, Component/Messaging, Priority/High

#19864 Allow only encoded paths to be mentioned in the path segments
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpService.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/parser/URITemplateParser.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/dispatching/UriTemplateBestMatchTest.java
  stdlib/http/src/test/resources/test-src/services/dispatching/uri-matrix-param-matching.bal
  stdlib/http/src/test/resources/test-src/services/dispatching/uri-template-matching.bal
  stdlib/http/src/test/resources/test-src/services/dispatching/uri-template.bal
Labels: Area/StandardLibs

#19919 Convert JsonUtils module to java inter ops
  stdlib/jdbc/build.gradle
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/H2ActionsTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/connection/ConnectorInitTest.java
  stdlib/jsonutils/build.gradle
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/jsonutils.bal
  stdlib/jsonutils/src/main/java/org/ballerinalang/stdlib/jsonutils/FromTable.java
  stdlib/jsonutils/src/main/java/org/ballerinalang/stdlib/jsonutils/FromXML.java
Labels: Area/StandardLibs, Type/Task

#19834 Add annotation to mark concurrent strands
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/AttachPoint.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  langlib/lang.annotations/src/main/ballerina/src/lang.annotations/annotations.bal
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/FunctionDefinitionCompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/ObjectTypeCompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/ResourceDefinitionCompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/TestablePackageCompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/packageimport/PackageImportCompletionTest.java
  stdlib/bir-old/src/main/ballerina/src/bir/bir_func_body_parser.bal
  stdlib/bir-old/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir-old/src/main/ballerina/src/bir/bir_pkg_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_pkg_parser.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationDeclarationTest.java
Labels: Area/jBallerina

#19956 Regenerate lexer grammar
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
Labels: Type/Bug

#19962 Add default values to optional fields to generated record types
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/Message.java
  stdlib/grpc/src/main/resources/templates/skeleton/message.mustache
  stdlib/grpc/src/main/resources/templates/skeleton/stub.mustache
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java
Labels: Area/StandardLibs, Component/gRPC

#19968 Fix JSON and union support in java-interop
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JMethodResolver.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/method_sig_not_match12.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/method_sig_not_match13.bal
Labels: Area/jBallerina

#19964 [RabbitMQ] Fix dependency issue
  stdlib/messaging/rabbitmq/src/main/ballerina/Ballerina.toml
Labels: Area/StandardLibs, Component/Messaging

#19973 Migrate Math library to inter-op
  cli/ballerina-cli-module-pull/build.gradle
  cli/ballerina-cli-module-push/build.gradle
  cli/ballerina-cli-module-search/build.gradle
  cli/ballerina-cli-module-token-update/build.gradle
  misc/metrics-extensions/modules/ballerina-prometheus-extension/build.gradle
  stdlib/http/build.gradle
  stdlib/math/build.gradle
  stdlib/math/src/main/ballerina/src/math/natives.bal
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/AbsFloat.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/AbsInt.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Acos.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Asin.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Atan.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Atan2.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Cbrt.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Ceil.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/CopySign.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Cos.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Cosh.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Exp.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Expm1.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Exponent.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/ExternMethods.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Floor.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/FloorDiv.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/FloorMod.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Hypot.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/IEEERemainder.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Log.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Log10.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Log1p.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NegateExact.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NextAfter.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NextDown.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NextUp.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Pow.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Random.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/RandomInRange.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Rint.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Round.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Scalb.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Signum.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Sin.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Sinh.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Sqrt.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Tan.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Tanh.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/ToDegrees.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/ToRadians.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Ulp.java
  stdlib/oauth2/build.gradle
  stdlib/streams/build.gradle
  stdlib/transactions/build.gradle
  stdlib/websub/build.gradle
Labels: Area/StandardLibs, Component/Math, Type/Improvement

#19969 Convert XMLUtils module to java inter-ops
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/jsonutils.bal
  stdlib/xmlutils/build.gradle
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/xmlutils.bal
  stdlib/xmlutils/src/main/java/org/ballerinalang/stdlib/xmlutils/ConvertUtils.java
  stdlib/xmlutils/src/main/java/org/ballerinalang/stdlib/xmlutils/FromJSON.java
  stdlib/xmlutils/src/main/java/org/ballerinalang/stdlib/xmlutils/FromTable.java
Labels: Area/StandardLibs

#19991 Fix reftype varags for interops
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/interop/interop_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/interop/interop_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_error_gen.bal
  stdlib/jvm-old/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JInterop.java
  stdlib/jvm-old/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/varargs/JavaVarargsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/varargs/java_varargs_tests.bal
Labels: Area/jBallerina

#19974 Fix json returns for interop
  stdlib/jvm-old/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JMethodResolver.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JMethodResolver.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/method_sig_not_match12.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/method_sig_not_match13.bal
Labels: Area/jBallerina

#19615 Warning when an array is passed for rest argument on function pointers
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/symbols/SymbolKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BInvokableTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/Symbols.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/negative/fp_rest_warning_test.bal
Labels: Area/Language

#20005 Improve ballerina streams performance
  stdlib/streams/src/main/ballerina/src/streams/util/stream-event.bal
  stdlib/streams/src/main/ballerina/src/streams/window/time-batch-window.bal
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/nativeimpl/BallerinaStreamsV2CountingPatternTest.java
Labels: Area/StandardLibs, Component/Streams

#20013 Improve ballerina streams performance
  stdlib/streams/src/main/ballerina/src/streams/util/stream-event.bal
  stdlib/streams/src/main/ballerina/src/streams/window/time-batch-window.bal
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/nativeimpl/BallerinaStreamsV2CountingPatternTest.java
Labels: Area/StandardLibs, Component/Streams

#19959 Improve JDBC client implementation
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/client.bal
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/client_endpoint.bal
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/types.bal
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/Constants.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/actions/Call.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/actions/Select.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/actions/Update.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/functions/Close.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/functions/CreateClient.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/functions/InitGlobalPoolContainer.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/MetricsTestCase.java
Labels: Area/StandardLibs

#20022 Migrate Math library to inter-op
  cli/ballerina-cli-module-pull/build.gradle
  cli/ballerina-cli-module-push/build.gradle
  cli/ballerina-cli-module-search/build.gradle
  cli/ballerina-cli-module-token-update/build.gradle
  misc/metrics-extensions/modules/ballerina-prometheus-extension/build.gradle
  stdlib/http/build.gradle
  stdlib/math/build.gradle
  stdlib/math/src/main/ballerina/src/math/natives.bal
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/AbsFloat.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/AbsInt.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Acos.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Asin.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Atan.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Atan2.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Cbrt.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Ceil.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/CopySign.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Cos.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Cosh.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Exp.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Expm1.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Exponent.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/ExternMethods.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Floor.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/FloorDiv.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/FloorMod.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Hypot.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/IEEERemainder.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Log.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Log10.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Log1p.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NegateExact.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NextAfter.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NextDown.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/NextUp.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Pow.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Random.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/RandomInRange.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Rint.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Round.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Scalb.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Signum.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Sin.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Sinh.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Sqrt.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Tan.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Tanh.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/ToDegrees.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/ToRadians.java
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/Ulp.java
  stdlib/oauth2/build.gradle
  stdlib/streams/build.gradle
  stdlib/transactions/build.gradle
  stdlib/websub/build.gradle
Labels: Area/StandardLibs, Component/Math, Type/Improvement

#19888 Fix Broken Links in API Docs
  stdlib/docker/src/main/ballerina/src/docker/annotation.bal
  stdlib/io/src/main/ballerina/src/io/Module.md
  stdlib/kubernetes/src/main/ballerina/src/kubernetes/annotation.bal
Labels: Area/Tooling, Component/Docerina, Type/Docs

#20041 Add call operation test cases for JDBC module
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/CallTest.java
  stdlib/jdbc/src/test/resources/datafiles/sql/actions/call_test_data.sql
  stdlib/jdbc/src/test/resources/test-src/actions/call_test.bal
  stdlib/jdbc/src/test/resources/testng.xml
Labels: Area/StandardLibs

#20047 Fix task and math issues
  stdlib/math/src/main/java/org/ballerinalang/stdlib/math/nativeimpl/ExternMethods.java
  stdlib/task/src/main/ballerina/Ballerina.toml
  stdlib/task/src/main/ballerina/src/task/listener.bal
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/TaskActions.java
  stdlib/task/src/test/java/org/ballerinalang/stdlib/task/service/AppointmentServiceTest.java
  stdlib/task/src/test/java/org/ballerinalang/stdlib/task/service/ListenerServiceValidationTest.java
  stdlib/task/src/test/java/org/ballerinalang/stdlib/task/service/TimerServiceTest.java
Labels: Area/StandardLibs, Component/Math, Component/Task, Type/Improvement

#20042 Fix ballerina service test failures in unit tests
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
Labels: Component/UnitTest, Type/Improvement, Type/TestFailure

#20045 Remove reverse DNS look-up
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
Labels: Area/StandardLibs, Component/HTTP, Priority/High

#19965 [RabbitMQ] Fix dependency issue
  stdlib/messaging/rabbitmq/src/main/ballerina/Ballerina.toml
Labels: Area/StandardLibs, Component/Messaging

#20054 Fix pipelining limit test failure
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HttpPipeliningTestCase.java
Labels: Area/StandardLibs

#20046 Remove reverse DNS look-up
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
Labels: Area/StandardLibs, Component/HTTP, Priority/High

#20057 Fix pipelining limit test failure - master
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HttpPipeliningTestCase.java
Labels: Area/StandardLibs

#20073 Enable disabled task tests
  stdlib/task/src/test/java/org/ballerinalang/stdlib/task/service/AppointmentServiceTest.java
  stdlib/task/src/test/java/org/ballerinalang/stdlib/task/service/ListenerServiceValidationTest.java
  stdlib/task/src/test/java/org/ballerinalang/stdlib/task/service/TimerServiceTest.java
Labels: Area/StandardLibs, Component/Task, Type/Bug

#20074 Move xmlutils module to java interop
  stdlib/xmlutils/build.gradle
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/xmlutils.bal
  stdlib/xmlutils/src/main/java/org/ballerinalang/stdlib/xmlutils/ConvertUtils.java
  stdlib/xmlutils/src/main/java/org/ballerinalang/stdlib/xmlutils/FromJSON.java
  stdlib/xmlutils/src/main/java/org/ballerinalang/stdlib/xmlutils/FromTable.java
Labels: Area/StandardLibs

#20072 Move jsonutils module to java interop
  stdlib/jdbc/build.gradle
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/H2ActionsTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/connection/ConnectorInitTest.java
  stdlib/jsonutils/build.gradle
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/jsonutils.bal
  stdlib/jsonutils/src/main/java/org/ballerinalang/stdlib/jsonutils/FromTable.java
  stdlib/jsonutils/src/main/java/org/ballerinalang/stdlib/jsonutils/FromXML.java
Labels: Area/StandardLibs

#20052 [Filepath] Migrate native functions to java interoperability
  cli/ballerina-cli-module-pull/build.gradle
  stdlib/filepath/build.gradle
  stdlib/filepath/src/main/ballerina/src/filepath/file_path.bal
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/nativeimpl/Absolute.java
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/nativeimpl/FilePathUtils.java
  stdlib/filepath/src/main/java/org/ballerinalang/stdlib/filepath/nativeimpl/Matches.java
  stdlib/messaging/kafka/build.gradle
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/ssl/KafkaConsumerAndProducerWithSSLTest.java
  stdlib/streams/build.gradle
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/BallerinaStreamsV2AggregatorWithGroupByAndWindowTest.java
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/nativeimpl/BallerinaStreamsV2SimplePatternTest.java
Labels: Area/StandardLibs

#20071 Migrate time library to inter-op
  cli/ballerina-cli-module-pull/build.gradle
  cli/ballerina-cli-module-push/build.gradle
  cli/ballerina-cli-module-search/build.gradle
  cli/ballerina-cli-module-token-update/build.gradle
  compiler/ballerina-backend-jvm/build.gradle
  language-server/modules/langserver-core/src/test/resources/completion/function/varDefStmt1.json
  misc/metrics-extensions/modules/ballerina-prometheus-extension/build.gradle
  stdlib/auth/build.gradle
  stdlib/cache/build.gradle
  stdlib/crypto/build.gradle
  stdlib/crypto/src/test/java/org/ballerinalang/stdlib/crypto/CryptoTest.java
  stdlib/crypto/src/test/java/org/ballerinalang/stdlib/crypto/KeyParsingTest.java
  stdlib/file/build.gradle
  stdlib/file/src/test/java/org/ballerinalang/stdlib/file/DirectoryListenerConnectorTest.java
  stdlib/file/src/test/java/org/ballerinalang/stdlib/file/FileTest.java
  stdlib/grpc/build.gradle
  stdlib/grpc/src/test/java/org/ballerinalang/net/grpc/ResourceReturnTypeTest.java
  stdlib/grpc/src/test/java/org/ballerinalang/net/grpc/UnsupportedFieldTypesTest.java
  stdlib/http/build.gradle
  stdlib/jwt/build.gradle
  stdlib/ldap/build.gradle
  stdlib/messaging/nats/build.gradle
  stdlib/messaging/rabbitmq/build.gradle
  stdlib/oauth2/build.gradle
  stdlib/streams/build.gradle
  stdlib/time/build.gradle
  stdlib/time/src/main/ballerina/src/time/time_errors.bal
  stdlib/time/src/main/ballerina/src/time/timelib.bal
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/AbstractTimeFunction.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/AddDuration.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/CreateTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/CurrentTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Day.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/ExternMethods.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Format.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/GetDate.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/GetTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Hour.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/MilliSecond.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Minute.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Month.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/NanoTime.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Parse.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Second.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/SubtractDuration.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/ToString.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/ToTimeZone.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/WeekDay.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/nativeimpl/Year.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/util/Constants.java
  stdlib/time/src/main/java/org/ballerinalang/stdlib/time/util/TimeUtils.java
  stdlib/time/src/test/java/org.ballerinalang.stdlib.time/TimeTest.java
  stdlib/transactions/build.gradle
  stdlib/websub/build.gradle
Labels: Area/StandardLibs, Component/Time, Type/Improvement

#20075 [Kafka] Migrate native functions to java interoperability
  stdlib/messaging/kafka/build.gradle
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/producer.bal
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Assign.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Close.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Commit.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/CommitOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Connect.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetAssignment.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetAvailableTopics.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetBeginningOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetCommittedOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetEndOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetPausedPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetPositionOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetSubscription.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Pause.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Poll.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Resume.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Seek.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SeekToBeginning.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SeekToEnd.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Subscribe.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SubscribeToPattern.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Unsubscribe.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Close.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/CommitConsumer.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/CommitConsumerOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/FlushRecords.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Init.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Send.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/service/Register.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/service/Start.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/service/Stop.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/consumer/KafkaConsumerSubscribeToPatternTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/consumer/KafkaConsumerTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/transactions/KafkaProducerTransactionsTest.java
Labels: Area/StandardLibs, Component/Messaging

#20088 Bump version to 1.1.0-SNAPSHOT
  composer/lerna.json
  composer/package-lock.json
  composer/package.json
  composer/packages/api-designer/package.json
  composer/packages/ast-model/package.json
  composer/packages/bbe/package.json
  composer/packages/diagram/package.json
  composer/packages/distribution/package.json
  composer/packages/documentation/package.json
  composer/packages/font/package.json
  composer/packages/lang-service/package.json
  composer/packages/syntax-highlighter/package.json
  composer/packages/theme/package.json
  composer/packages/tracing/package.json
  composer/tools/composer-cli/package.json
  gradle.properties
  tool-plugins/vscode/package.json
Labels: Area/Build

#20089 Enable task windows tests
  .travis.yml
Labels: Area/StandardLibs, Component/Task

#20053 [RabbitMQ] Migrate native functions to java interoperability
  examples/rabbitmq-producer/rabbitmq_producer.bal
  stdlib/messaging/rabbitmq/build.gradle
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/Module.md
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/channel.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/connection.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/listener.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/message.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/rabbitmq_commons.bal
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/MessageDispatcher.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/RabbitMQConstants.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/AbortChannel.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/BasicGet.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/BasicPublish.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/Close.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/CreateChannel.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/ExchangeDeclare.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/ExchangeDelete.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/GetConnection.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/QueueBind.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/QueueDeclare.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/QueueDelete.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/QueuePurge.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/AbortConnection.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/Close.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/CreateConnection.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/IsClosed.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/Detach.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/GetChannel.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/RegisterListener.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/SetQosSettings.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/Start.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/listener/Stop.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/BasicAck.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/BasicNack.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetByteArrayContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetDeliveryTag.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetFloatContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetIntContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetJSONContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetProperties.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetTextContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/message/GetXMLContent.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ChannelUtils.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ListenerUtils.java
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/MessageUtils.java
Labels: Area/StandardLibs, Component/Messaging

#20028 Fix test dependencies are not resolved when running single module
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/buildcontext/BuildContext.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyNativeLibTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateBirTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateJarTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunTestsTask.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PathDependencyTestCase.java
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/test-dependency/src/baz/main.bal
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/test-dependency/src/baz/tests/main_test.bal
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/test-dependency/src/daz/main.bal
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/test-dependency/src/daz/tests/main_test.bal
Labels: Area/BuildTools

#20032 Migrate config-api to inter-op
  cli/ballerina-cli-module-pull/build.gradle
  cli/ballerina-cli-module-push/build.gradle
  cli/ballerina-cli-module-search/build.gradle
  cli/ballerina-cli-module-token-update/build.gradle
  misc/metrics-extensions/modules/ballerina-prometheus-extension/build.gradle
  stdlib/auth/build.gradle
  stdlib/config-api/src/main/ballerina/src/config/natives.bal
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/Contains.java
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/GetConfig.java
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/SetConfig.java
  stdlib/grpc/build.gradle
  stdlib/http/build.gradle
  stdlib/jdbc/build.gradle
  stdlib/jwt/build.gradle
  stdlib/ldap/build.gradle
  stdlib/oauth2/build.gradle
  stdlib/streams/build.gradle
  stdlib/transactions/build.gradle
  stdlib/websub/build.gradle
Labels: Area/StandardLibs

#20095 Migrate System to inter-op
  cli/ballerina-cli-module-pull/build.gradle
  cli/ballerina-cli-module-push/build.gradle
  cli/ballerina-cli-module-search/build.gradle
  cli/ballerina-cli-module-token-update/build.gradle
  misc/metrics-extensions/modules/ballerina-prometheus-extension/build.gradle
  stdlib/auth/build.gradle
  stdlib/cache/build.gradle
  stdlib/config-api/build.gradle
  stdlib/filepath/build.gradle
  stdlib/grpc/build.gradle
  stdlib/http/build.gradle
  stdlib/jdbc/build.gradle
  stdlib/jwt/build.gradle
  stdlib/ldap/build.gradle
  stdlib/messaging/kafka/build.gradle
  stdlib/oauth2/build.gradle
  stdlib/streams/build.gradle
  stdlib/system/build.gradle
  stdlib/system/src/main/ballerina/src/system/process.bal
  stdlib/system/src/main/ballerina/src/system/system.bal
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Destroy.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Exec.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/ExitCode.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetEnv.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUserHome.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUsername.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Stderr.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Stdin.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Stdout.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Uuid.java
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/WaitForExit.java
  stdlib/transactions/build.gradle
  stdlib/websub/build.gradle
Labels: Area/StandardLibs

#19830 Migrate crypto module into java interoperability
  cli/ballerina-cli-module-pull/build.gradle
  cli/ballerina-cli-module-push/build.gradle
  cli/ballerina-cli-module-search/build.gradle
  cli/ballerina-cli-module-token-update/build.gradle
  cli/ballerina-cli-utils/build.gradle
  misc/metrics-extensions/modules/ballerina-prometheus-extension/build.gradle
  stdlib/auth/build.gradle
  stdlib/crypto/build.gradle
  stdlib/crypto/src/main/ballerina/src/crypto/crypto.bal
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Crc32b.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecodePrivateKey.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecodePublicKey.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecryptAesCbc.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecryptAesEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecryptAesGcm.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/DecryptRsaEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/EncryptAesCbc.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/EncryptAesEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/EncryptAesGcm.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/EncryptRsaEcb.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashMd5.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashSha1.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashSha256.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashSha384.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HashSha512.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacMd5.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacSha1.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacSha256.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacSha384.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/HmacSha512.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaMd5.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha1.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha256.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha384.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/SignRsaSha512.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaMd5Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha1Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha256Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha384Signature.java
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/VerifyRsaSha512Signature.java
  stdlib/grpc/build.gradle
  stdlib/http/build.gradle
  stdlib/jwt/build.gradle
  stdlib/ldap/build.gradle
  stdlib/messaging/nats/build.gradle
  stdlib/messaging/rabbitmq/build.gradle
  stdlib/oauth2/build.gradle
  stdlib/streams/build.gradle
  stdlib/transactions/build.gradle
  stdlib/websub/build.gradle
Labels: Area/StandardLibs, Component/Crypto, Type/Improvement
