Repository ballerina-platform/ballerina-lang, pull requests merged in 2020-03, with the labels that each got.

#21377 Fix java interop unit tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/AnnotationProc.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JInterop.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethod.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodRequest.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JTypeTags.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JavaField.java
Labels: Area/jBallerina

#21335 Send vscode client configuration during initialization
  tool-plugins/vscode/src/diagram/activator.ts
  tool-plugins/vscode/src/extension.ts
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#21418 Allow configs changes without language server restart
  language-server/modules/langserver-cli/src/main/java/org/ballerinalang/langserver/cmd/LangServerStartCmd.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSClientLogger.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompilerUtil.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSModuleCompiler.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/config/CodeLensConfig.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/config/ConfigChangeListener.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/config/GoToDefinitionConfig.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/config/LSClientConfig.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/config/LSClientConfigHolder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSGlobalContextKeys.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/LSCodeLensesProviderHolder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/DocsCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/EndpointsCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/ServicesBasedCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/definition/DefinitionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/ReferencesUtil.java
  tool-plugins/vscode/.vscode/launch.json
  tool-plugins/vscode/src/core/extension.ts
  tool-plugins/vscode/src/extension.ts
  tool-plugins/vscode/src/server/server.ts
  tool-plugins/vscode/test/language-server/lang-client.test.ts
Labels: Area/Tooling, Component/LanguageServer, Type/Improvement

#21207 Allow spread operators in mapping constructor expressions
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/RecordLiteralNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangRecordLiteral.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Constants.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/LSNodeVisitor.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/ProtoBuilderTestCase.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field_constant_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field_semantic_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field_taint_analysis_negative.bal
Labels: Area/Language

#21448 Fix Create local variable code-action not working for action invocations
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/CollectDiagnosticListener.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompilerCache.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSContextManager.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSModuleCompiler.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractCodeActionProvider.java
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#21451 Enable VSCode configuration sync with LS
  tool-plugins/vscode/src/core/extension.ts
  tool-plugins/vscode/src/extension.ts
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#21439 Remove spaces between pipe and type in union
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/Tokens.java
  language-server/modules/langserver-core/src/test/resources/formatting/bindingPatterns.bal
  language-server/modules/langserver-core/src/test/resources/formatting/check.bal
  language-server/modules/langserver-core/src/test/resources/formatting/checkPanic.bal
  language-server/modules/langserver-core/src/test/resources/formatting/constant.bal
  language-server/modules/langserver-core/src/test/resources/formatting/documentation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/elvisExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/errorConstructor.bal
  language-server/modules/langserver-core/src/test/resources/formatting/errorVariableDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/errorVariableReference.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedBindingPatterns.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedCheck.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedCheckPanic.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedConstant.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedDocumentation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedElvisExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorConstructor.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorVariableDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorVariableReference.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFieldBasedAccess.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedForkJoin.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedMatchStmt.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedNegativeEOF.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedObject.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedPanic.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedRecordDestructure.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedReturn.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedService.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTernaryExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTrap.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTypeDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTypeDesc.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTypeGuard.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedUnionType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedWait.bal
  language-server/modules/langserver-core/src/test/resources/formatting/fieldBasedAccess.bal
  language-server/modules/langserver-core/src/test/resources/formatting/forkJoin.bal
  language-server/modules/langserver-core/src/test/resources/formatting/matchStmt.bal
  language-server/modules/langserver-core/src/test/resources/formatting/negativeEOF.bal
  language-server/modules/langserver-core/src/test/resources/formatting/object.bal
  language-server/modules/langserver-core/src/test/resources/formatting/panic.bal
  language-server/modules/langserver-core/src/test/resources/formatting/recordDestructure.bal
  language-server/modules/langserver-core/src/test/resources/formatting/return.bal
  language-server/modules/langserver-core/src/test/resources/formatting/service.bal
  language-server/modules/langserver-core/src/test/resources/formatting/ternaryExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/trap.bal
  language-server/modules/langserver-core/src/test/resources/formatting/typeDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/typeDesc.bal
  language-server/modules/langserver-core/src/test/resources/formatting/typeGuard.bal
  language-server/modules/langserver-core/src/test/resources/formatting/unionType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/wait.bal
Labels: Area/Tooling, Component/Formatting

#21209 Add support for let expression
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/LetExpressionNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserBaseListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BLetSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/SymTag.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangLetExpression.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangLetVariable.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentPointTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/DataflowAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/let/LetExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/TaintedStatusPropagationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteArrayValueNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/dataflow-analysis-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-not-supported.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/let-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/let.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language, Type/NewFeature

#21466 Fix Diagram Overview not working when there's an invalid import in the code
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/VisibleEndpointVisitor.java
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#21297 Support object initialization for args with default values
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectInitializerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/ObjectProject/src/init/object-initializer.bal
Labels: Area/Language

#21320 Fix Compilation error when function has a function typed param with only rest params
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal
Labels: Area/Language

#21375 Add toArray() method to map lang library
  langlib/lang.map/src/main/ballerina/src/lang.map/map.bal
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/ToArray.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibMapTest.java
  langlib/langlib-test/src/test/resources/test-src/maplib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/groupedExpressionSuggestion1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/typeGuardSuggestions4.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest14.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest2.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest3.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest4.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest8.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest9.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/exprFunctionBodyCompletion3.json
Labels: Area/Language

#21479 Add signatureHelp support for spread operator as mapping constructor
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/position/PositionTreeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/util/HoverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/sourceprune/LHSSignatureTokenTraverser.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/sourceprune/SignatureTokenTraverserFactory.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/signature/SignatureHelpTest.java
  language-server/modules/langserver-core/src/test/resources/signature/signatureSpreadOperator.json
  language-server/modules/langserver-core/src/test/resources/signature/source/signatureSpreadOperator.bal
Labels: Area/Tooling, Component/LanguageServer, Type/NewFeature

#21410 Support multiple attachments in Ballerina task scheduler
  examples/task-scheduler-timer/task_scheduler_timer.bal
  examples/task-scheduler-timer/task_scheduler_timer.description
  stdlib/task/src/main/ballerina/Ballerina.toml
  stdlib/task/src/main/ballerina/src/task/listener.bal
  stdlib/task/src/main/ballerina/src/task/scheduler.bal
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/TaskActions.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/ServiceInformation.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/TaskConstants.java
  stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/TaskExecutor.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/task/MultipleAttachmentTest.java
  tests/jballerina-integration-test/src/test/resources/task/src/multipleattachments/01_multiple_attachments.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/Task, Type/Improvement

#21493 Fix MetricsTestCase broken by jballerina migration
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/MetricsTestCase.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/jBallerina

#21428 Fix custom error type description not being defined.
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/SymTag.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/typedesc/TypedescTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typedesc/typedesc_positive.bal
Labels: Area/Language, Type/Bug

#21502 Fix LocalVariable table not having the var name
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmMethodGen.java
Labels: Area/jBallerina

#21343 Implement XML cycle detection and align xml namespace handling with the spec
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLFactory.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachXMLTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachXMLTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  stdlib/bir-old/src/main/ballerina/src/bir/bir_func_body_parser.bal
  stdlib/bir-old/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/src/bir/emitter/bir_instruction_emitter.bal
  stdlib/xmlutils/src/main/java/org/ballerinalang/stdlib/xmlutils/JSONToXMLConverter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsWithVarMutabilityTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributesTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLNativeFunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/sampleXML.txt
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/too-large-method.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/too-large-object-field.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/too-large-object-method.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/too-large-package-variable.bal
Labels: Area/Language, Spec/2020R1, Type/NewFeature

#21485 Disable force rerun gradle tasks from travis.yaml
  .travis.yml
  appveyor.yml
Labels: Area/Build, Type/Task

#21472 Add unit tests for binary expressions
  compiler/ballerina-parser/build.gradle
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserListener.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/SyntaxKind.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/TestParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/expressions/AbstractExpressionsTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/expressions/BinaryExpressionsTest.java
  compiler/ballerina-parser/src/test/resources/expressions/binary-expr/binary_expr_op_precedence_assert_1.json
  compiler/ballerina-parser/src/test/resources/expressions/binary-expr/binary_expr_op_precedence_assert_2.json
  compiler/ballerina-parser/src/test/resources/expressions/binary-expr/binary_expr_op_precedence_assert_3.json
  compiler/ballerina-parser/src/test/resources/expressions/binary-expr/binary_expr_op_precedence_assert_4.json
  compiler/ballerina-parser/src/test/resources/expressions/binary-expr/simple_binary_expr_assert_1.json
  compiler/ballerina-parser/src/test/resources/expressions/binary-expr/simple_binary_expr_assert_2.json
  compiler/ballerina-parser/src/test/resources/testng.xml
Labels: Area/Language, Component/Parser

#21430 Add lastIndexOf method
  langlib/lang.array/src/main/ballerina/src/lang.array/array.bal
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/LastIndexOf.java
  langlib/lang.string/src/main/ballerina/src/lang.string/string.bal
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/LastIndexOf.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion5.json
  language-server/modules/langserver-core/src/test/resources/completion/function/delimiterBasedCompletionForCompleteSource2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/typeGuardSuggestions2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions4.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport3.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/exprFunctionBodyCompletion5.json
Labels: Area/Language

#21517 Fix transaction test cases
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmMethodGen.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/jBallerina

#21525 Add xml reference equality support
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/RefEqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/ref_equal_and_not_equal_operation.bal
Labels: Area/Language

#21536 Improve XML freeze support and reference equality
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/RefEqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinfunctions/FreezeAndIsFrozenTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/ref_equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal
Labels: Area/Language

#21531 Fix byte[] cast to int[]
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/ByteAsIntTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_as_int_test.bal
Labels: Area/Language

#21544 Fix NodeCloner issue in let expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
Labels: Area/Language

#21537 Fix referencing constants with int subtypes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibSubTypeTest.java
  langlib/langlib-test/src/test/resources/test-src/int_subtype_assignment_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/subtypes/int_subtypes_test.bal
Labels: Area/Language

#21490 Add retry functionality to gRPC unary blocking client
  stdlib/grpc/src/main/ballerina/src/grpc/client_endpoint.bal
  stdlib/grpc/src/main/ballerina/src/grpc/grpc_errors.bal
  stdlib/grpc/src/main/ballerina/src/grpc/utils.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/GrpcBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/UnaryBlockingRetryTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/22_unary_blocking_retry_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/22_retry_service.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/gRPC, Type/Improvement

#21529 Allow metadata on record/object fields
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/AttachPoint.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/AttachPoints.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  examples/anonymous-records/anonymous_records.bal
  language-server/modules/langserver-core/src/test/resources/sourceprune/expected/src_prune_expected10.bal
  language-server/modules/langserver-core/src/test/resources/sourceprune/sources/src_prune_source10.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/src/bir/emitter/bir_instruction_emitter.bal
  stdlib/bir/src/main/ballerina/src/bir/serializer.bal
  stdlib/jdbc/src/test/resources/test-src/table/table_type_test_nillable_mapping_negative.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentPointTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationDeclarationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationRuntimeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDocumentationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_availability.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/constant/simple-literal-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/src/foo/simple-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/ObjectProject/src/ObjectEquivalencyTest/object-equivalency.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_documentation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/record_access_with_index.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/record_documentation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/chained-invocations-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/global-object-functions-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/global-object-functions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/object-tainted-assigment-to-untainted-objref.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-for-all-actions.bal
Labels: Area/Language

#21564 Fix ignore code action breaks for inline records
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateVariableCodeAction.java
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#21487 Block new strand generation within locks.
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BLock.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BLockStore.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/exceptions/BallerinaErrorReasons.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ExperimentalFeaturesTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-functions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker-in-lock.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Area/Language

#21555 [NATS] Improve how connection urls are specified
  examples/nats-basic-client/subscriber.bal
  examples/nats-streaming-client/publisher.bal
  examples/nats-streaming-client/subscriber.bal
  examples/nats-streaming-consumer-with-data-binding/publisher.bal
  examples/nats-streaming-consumer-with-data-binding/subscriber.bal
  examples/nats-streaming-durable-subscriptions/publisher.bal
  examples/nats-streaming-durable-subscriptions/subscriber.bal
  examples/nats-streaming-queue-group/publisher.bal
  examples/nats-streaming-queue-group/queue-group.bal
  examples/nats-streaming-start-position/publisher.bal
  examples/nats-streaming-start-position/subscriber.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/commons.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/connection/connection.bal
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/Utils.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/CloseConnection.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Publish.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/Close.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/Init.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/observability/NatsTracingUtil.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Attach.java
  stdlib/messaging/nats/src/test/resources/test-src/basic/nats_invalid_on_error_paramters.bal
  stdlib/messaging/nats/src/test/resources/test-src/basic/nats_invalid_on_message_parameter.bal
  stdlib/messaging/nats/src/test/resources/test-src/basic/nats_missing_annotation.bal
  stdlib/messaging/nats/src/test/resources/test-src/basic/nats_missing_on_error_parameters.bal
  stdlib/messaging/nats/src/test/resources/test-src/basic/nats_missing_on_message_parameter.bal
  stdlib/messaging/nats/src/test/resources/test-src/basic/nats_valid_subscriber.bal
  stdlib/messaging/nats/src/test/resources/test-src/databinding/nats_data_binding_unsupported_type.bal
  stdlib/messaging/nats/src/test/resources/test-src/databinding/nats_data_binding_valid.bal
Labels: Area/StandardLibs, Component/Messaging

#21577 Fix a bug in crypto interop API [1.1.x]
  stdlib/crypto/src/main/ballerina/src/crypto/crypto.bal
Labels: Area/StandardLibs, Type/Bug

#21579 [NATS] Improve error printed for a request time out
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/basic/producer/Request.java
Labels: Area/StandardLibs, Component/Messaging

#21600 Add formatting support for xml navigation expression
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/XMLElementAccess.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/XMLNavigationAccess.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangXMLElementAccess.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangXMLNavigationAccess.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedXMLElementLiteral.bal
  language-server/modules/langserver-core/src/test/resources/formatting/xmlElementLiteral.bal
Labels: Area/Tooling, Component/Formatting

#21608 Add support for iterator errors
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangFromClause.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangForeach.java
Labels: Area/Language

#21595 Add formatting support for Let expression
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/LetExpressionNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangLetExpression.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/TextDocumentFormatUtil.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/Tokens.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedLetExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/letExpr.bal
Labels: Area/Tooling, Component/Formatting

#21566 Refactor syntax/semantics related to stdlib security modules
  language-server/modules/langserver-core/src/test/resources/completion/function/delimiterBasedCompletionForCompleteSource1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/ifWhileConditionContextCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/workerDeclarationContext4.json
  language-server/modules/langserver-core/src/test/resources/completion/object/objectTest13.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/globalVarDefPackageContent.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/statementWithMissingSemiColon2.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/statementWithMissingSemiColon3.json
  stdlib/auth/src/main/ballerina/src/auth/inbound_basic_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/outbound_basic_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/utils.bal
  stdlib/http/src/main/ballerina/src/http/auth/authn_filter.bal
  stdlib/http/src/main/ballerina/src/http/auth/authz_filter.bal
  stdlib/http/src/main/ballerina/src/http/auth/authz_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/basic_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/bearer_auth_handler.bal
  stdlib/http/src/main/ballerina/src/http/auth/utils.bal
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_issuer.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/jwt/src/main/ballerina/src/jwt/outbound_jwt_auth_provider.bal
  stdlib/ldap/src/main/ballerina/src/ldap/inbound_ldap_auth_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Type/Improvement

#21576 Fix a bug in crypto interop API [master]
  stdlib/crypto/src/main/ballerina/src/crypto/crypto.bal
Labels: Area/StandardLibs, Type/Bug

#21611 Fix expr not being cloned in xml nav access
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
Labels: Area/Language

#21632 Introduce a syntax-tree-JSON generator for parser test assertions
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/SyntaxKind.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestConstants.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/SyntaxTreeJSONGenerator.java
Labels: Component/Parser

#21476 Implement get generated keys only if supported by JDBC
  examples/jdbc-client-batch-update/jdbc_client_batch_update.bal
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.bal
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/client.bal
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/methods/ExternActions.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/methods/ExternFunctions.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/BatchUpdateTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/UpdateTest.java
  stdlib/jdbc/src/test/resources/test-src/actions/batch_update_test.bal
  stdlib/jdbc/src/test/resources/test-src/actions/h2_actions_test.bal
  stdlib/jdbc/src/test/resources/test-src/actions/update_test.bal
  stdlib/jdbc/src/test/resources/test-src/table/table_type_test.bal
  stdlib/jdbc/src/test/resources/test-src/table/table_type_test_nillable_mapping.bal
  stdlib/jdbc/src/test/resources/test-src/transaction/local_transaction_test.bal
Labels: Area/StandardLibs

#21618 Add tests for iterator errors
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachIterableObjectTest.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-iterable-object-negative.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-iterable-objects.bal
Labels: Area/Language

#21615 Fix xml sequence serialization for xml fragments
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Area/Language

#21626 Add ballerina docs for JWT error
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_errors.bal
Labels: Area/StandardLibs, Component/JWT, Type/Improvement

#21620 Fix issue in jsonutils:fromXML()
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/jsonutils.bal
  stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java
  stdlib/jsonutils/src/test/resources/test-src/jsonutils_test.bal
Labels: Area/StandardLibs

#21308 Implement Ballerina Cache API (v2.0.0) [master]
  examples/cache/cache.bal
  examples/cache/cache.description
  examples/cache/cache.out
  examples/cache/tests/cache_test.bal
  examples/index.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinInvocationArgs3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/delimiterBasedCompletionForCompleteSource1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/ifWhileConditionContextCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/statementWithMissingSemicolon2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/workerDeclarationContext4.json
  language-server/modules/langserver-core/src/test/resources/completion/object/objectTest13.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport1.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport2.json
  language-server/modules/langserver-core/src/test/resources/completion/service/serviceBodyCompletion5.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/globalVarDefPackageContent.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/statementWithMissingSemiColon2.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/statementWithMissingSemiColon3.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelPackageContentAccess.json
  stdlib/auth/src/main/ballerina/src/auth/utils.bal
  stdlib/cache/build.gradle
  stdlib/cache/src/main/ballerina/Ballerina.toml
  stdlib/cache/src/main/ballerina/src/cache/Module.md
  stdlib/cache/src/main/ballerina/src/cache/abstract_cache.bal
  stdlib/cache/src/main/ballerina/src/cache/abstract_eviction_policy.bal
  stdlib/cache/src/main/ballerina/src/cache/cache.bal
  stdlib/cache/src/main/ballerina/src/cache/cache_errors.bal
  stdlib/cache/src/main/ballerina/src/cache/linked_list.bal
  stdlib/cache/src/main/ballerina/src/cache/lru_eviction_policy.bal
  stdlib/cache/src/test/java/org/ballerinalang/stdlib/cache/CacheTest.java
  stdlib/cache/src/test/java/org/ballerinalang/stdlib/cache/util/JBallerinaTestInitializer.java
  stdlib/cache/src/test/resources/test-src/cache-test.bal
  stdlib/cache/src/test/resources/test-src/cache/cache-test.bal
  stdlib/cache/src/test/resources/testng.xml
  stdlib/http/src/main/ballerina/src/http/caching/http_cache.bal
  stdlib/http/src/main/ballerina/src/http/caching/http_caching_client.bal
  stdlib/http/src/main/ballerina/src/http/service_endpoint.bal
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
  stdlib/transactions/src/main/ballerina/src/transactions/commons.bal
  stdlib/websub/src/main/ballerina/src/websub/hub_configuration.bal
  stdlib/websub/src/main/ballerina/src/websub/hub_service.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/cache/CacheBaseTest.java
  tests/jballerina-integration-test/src/test/resources/cache/.gitignore
  tests/jballerina-integration-test/src/test/resources/cache/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/cache/src/cacheservices/01_cache_expiry_service.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Type/Improvement

#21497 Add xml validation when parsing xml
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLTreeBuilder.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLParserNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-def-negative.bal
Labels: Area/Language

#21629 Provide the mutual ssl status result in the request
  gradle/javaLibsProject.gradle
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2MutualSslTestCase.java
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/09_http_2.0_mutual_ssl.bal
Labels: Area/StandardLibs, Type/Improvement

#21588 Add support for deprecation
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/MarkdownDocumentationNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkDownDocumentationDeprecationAttributeNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserBaseListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangMarkdownDocumentation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangMarkDownDeprecationDocumentation.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  langlib/lang.annotations/src/main/ballerina/src/lang.annotations/annotations.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecation_annotation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecation_annotation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/annotations/deprecation_annotation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/src/foo/deprecation_annotation.bal
Labels: Area/Language

#21641 Fix ballerina docs for oauth2 module
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Component/OAuth2, Type/Improvement

#21598 Allow xml as a namespace prefix in xml attribute access
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/FunctionDefinitionCompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/ObjectTypeCompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/TestablePackageCompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/TopLevelNodeCompletionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributeAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-lax-behavior.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-syntax.bal
Labels: Area/Language

#21568 Disallow method invocation directly after xml navigation access expression.
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangXMLNavigationAccess.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-xml-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-xml.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable-with-variable-mutability.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-native-functions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-nav-access-negative.bal
Labels: Area/Language

#21646 Refactor error files of stdlib security modules
  stdlib/auth/src/main/ballerina/src/auth/auth_errors.bal
  stdlib/auth/src/main/ballerina/src/auth/utils.bal
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_errors.bal
  stdlib/jwt/src/main/ballerina/src/jwt/utils.bal
  stdlib/ldap/src/main/ballerina/src/ldap/ldap_errors.bal
  stdlib/ldap/src/main/ballerina/src/ldap/utils.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/oauth2_errors.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/utils.bal
Labels: Area/StandardLibs, Type/Improvement

#21606 Bug Fix: Return the value assigned to the http header even if it is empty
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/EntityHeaders.java
  stdlib/mime/src/test/java/org/ballerinalang/stdlib/mime/HeaderTest.java
Labels: Area/StandardLibs, Component/HTTP, Type/Bug

#21442 Fix error building modules with periods in the module name
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/BTestRunner.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PackagingTestCase.java
Labels: Area/BuildTools

#21501 Add filling-read operation for lvalue arrays
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TupleValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BArray.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayFillTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayLValueFillTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleLValueFillTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-fill-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_lvalue_fill_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_lvalue_fill_test.bal
Labels: Area/Language

#21622 Add the Missing Descriptions of the IO Module in API Docs
  stdlib/io/src/main/ballerina/src/io/constants.bal
  stdlib/io/src/main/ballerina/src/io/readable_character_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_csv_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_record_channel.bal
Labels: Component/Docerina, Type/Docs

#21594 Add the Missing Descriptions of the File Module in API Docs
  stdlib/file/src/main/ballerina/src/file/file_info.bal
Labels: Component/Docerina, Type/Docs

#21520 Add func pointer as defaultable param
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangLambdaFunction.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectInitializerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/function-pointers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/ObjectProject/src/init/object-initializer.bal
Labels: Area/Language

#21511 add string:equalsIgnoreCaseAscii langlib method
  langlib/lang.string/src/main/ballerina/src/lang.string/string.bal
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/EqualsIgnoreCaseAscii.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/delimiterBasedCompletionForCompleteSource2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/typeGuardSuggestions2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions4.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport3.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/exprFunctionBodyCompletion5.json
Labels: Area/Language

#21260 Implement Function mocking
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/PackageLoader.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangTestablePackage.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestAnnotationProcessor.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TesterinaReport.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BaseTestCase.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/MockTest.java
  tests/testerina-integration-test/src/test/resources/mock-tests/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/mock-tests/src/Mock/main.bal
  tests/testerina-integration-test/src/test/resources/mock-tests/src/Mock/tests/main_test.bal
  tests/testerina-integration-test/src/test/resources/mock-tests/src/SubtractModule/main.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Area/BuildTools, Area/TestFramework, Component/Testerina, Type/Improvement

#21581 Implement testerina code coverage
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/TestCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunTestsTask.java
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-test.help
  distribution/zip/jballerina-tools/build.gradle
  distribution/zip/jballerina-tools/lib/jacocoagent.jar
  misc/testerina/modules/testerina-runtime/build.gradle
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/CoverageMain.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/Main.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/ModuleCoverage.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/ModuleStatus.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TestReport.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TesterinaReport.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/CodeCoverageUtils.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java
Labels: Area/BuildTools, Area/TestFramework

#21654 Sync stdlib-1.2.0 with master
  stdlib/auth/src/main/ballerina/src/auth/auth_errors.bal
  stdlib/auth/src/main/ballerina/src/auth/utils.bal
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_errors.bal
  stdlib/jwt/src/main/ballerina/src/jwt/utils.bal
  stdlib/ldap/src/main/ballerina/src/ldap/ldap_errors.bal
  stdlib/ldap/src/main/ballerina/src/ldap/utils.bal
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/EntityHeaders.java
  stdlib/mime/src/test/java/org/ballerinalang/stdlib/mime/HeaderTest.java
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/oauth2_errors.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/utils.bal
Labels: Area/StandardLibs, Type/Task

#21678 Fix an intermittent test failure
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/ImapSimpleSecureEmailReceiveTest.java
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/PopSimpleSecureEmailReceiveTest.java
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/SmtpSimpleSecureEmailSendTest.java
Labels: Area/StandardLibs

#21199 Enable gRPC command to support oneof using optional fields
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/Message.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/components/Message.java
  stdlib/grpc/src/main/resources/templates/skeleton/message.mustache
  stdlib/grpc/src/main/resources/templates/skeleton/oneoffield.mustache
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/UnaryBlockingOneofFieldTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/15_grpc_oneof_field_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/15_grpc_oneof_field_service.bal
Labels: Area/StandardLibs, Component/gRPC

#21687 Fix kafka custom serializer creation NPE issue
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/serdes/BallerinaKafkaDeserializer.java
Labels: Area/StandardLibs, Component/Kafka, Type/Bug

#21549 Code cleanup and remove redundant checks
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmErrorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/Main.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/grammar/BallerinaLexer.tokens
Labels: Area/jBallerina

#21703 Update travis.yml
  .travis.yml
Labels: Area/Build, Type/Task

#21695 Delete the JSONVariable.gif Image
  docs/images/JSONVariable.gif
  docs/tutorials/passthrough-service.md
Labels: Type/Docs

#21708 Fix bytecode verification issues when importing modules via balo path
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateJarTask.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/LockFileTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PathDependencyTestCase.java
Labels: Area/jBallerina

#21702 Refactor auth usages in http module
  stdlib/http/src/main/ballerina/src/http/annotation.bal
  stdlib/http/src/main/ballerina/src/http/http_secure_client.bal
  stdlib/http/src/main/ballerina/src/http/service_endpoint.bal
Labels: Area/StandardLibs, Type/Improvement

#21701 Update log level of cache related operations
  stdlib/auth/src/main/ballerina/src/auth/utils.bal
  stdlib/http/src/main/ballerina/src/http/caching/http_cache.bal
  stdlib/http/src/main/ballerina/src/http/caching/http_caching_client.bal
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
  stdlib/transactions/src/main/ballerina/src/transactions/commons.bal
  stdlib/websub/src/main/ballerina/src/websub/hub_service.bal
Labels: Area/StandardLibs, Type/Bug

#21699 Move PR #21692 to stage branch
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecation_annotation.bal
Labels: Area/Language

#21727 Fix bytecode verification issues when importing modules via balo path
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateJarTask.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/LockFileTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PathDependencyTestCase.java
Labels: Area/jBallerina

#21706 Fix lang-server breaks for --std-libs param for old SDKs
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/config/LSClientConfig.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  tool-plugins/vscode/src/core/extension.ts
  tool-plugins/vscode/src/extension.ts
  tool-plugins/vscode/src/server/server.ts
Labels: Area/Tooling, Component/VScodePlugin, Type/Bug

#21734 Migrate Objects to use BString
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/MapUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/BmpStringValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/NonBmpStringValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BObject.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  langlib/lang.error/src/main/java/org/ballerinalang/langlib/error/StackTrace.java
  tests/jballerina-bstring-unit-test/build.gradle
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/types/string/BStringObjectTest.java
  tests/jballerina-bstring-unit-test/src/test/resources/test-src/types/string/bstring-object-test.bal
Labels: Area/jBallerina

#21729 Change return type of getAsMap() to map<anydata>
  language-server/modules/langserver-core/src/test/resources/completion/annotation/annotationBodyCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinInvocationArgs10.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinInvocationArgs9.json
  stdlib/config-api/src/main/ballerina/src/config/config.bal
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/GetConfig.java
  stdlib/config-api/src/test/resources/test-src/config.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/packageimport/PackageImportTest.java
Labels: Area/StandardLibs

#21718 Fix type checking issue in let expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/let/LetExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/ExprBodiedFunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/expr_bodied_functions.bal
Labels: Area/Language

#21669 Fix issue in defining anonymous record types in a tuple type desc
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/BasicTupleTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_basic_test.bal
Labels: Area/Language

#21712 Add Ballerina by example guide to Email Connector
  examples/index.json
  examples/send-and-receive-emails/send-and-receive-emails-1-smtp.bal
  examples/send-and-receive-emails/send-and-receive-emails-1-smtp.out
  examples/send-and-receive-emails/send-and-receive-emails-2-pop.bal
  examples/send-and-receive-emails/send-and-receive-emails-2-pop.out
  examples/send-and-receive-emails/send-and-receive-emails-3-imap.bal
  examples/send-and-receive-emails/send-and-receive-emails-3-imap.out
  examples/send-and-receive-emails/send-and-receive-emails.description
Labels: Area/StandardLibs, Type/Docs

#21738 Fix issues in shift operator and add tests
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/ShiftUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibSubTypeTest.java
  langlib/langlib-test/src/test/resources/test-src/subtypes/int_subtypes_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java
Labels: Area/Language

#21661 Add a BBE for expression-bodied functions
  examples/expression-bodied-functions/expression_bodied_functions.bal
  examples/expression-bodied-functions/expression_bodied_functions.description
  examples/expression-bodied-functions/expression_bodied_functions.out
  examples/index.json
Labels: Area/Language

#21672 Remove error support form foreach
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangFromClause.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangForeach.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachIterableObjectTest.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-iterable-objects.bal
Labels: Area/Language, Component/Streams

#21668 Fix optimize code action removes comments
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/OptimizeAllImportsCodeAction.java
  language-server/modules/langserver-core/src/test/resources/codeaction/optimizeImports.json
  language-server/modules/langserver-core/src/test/resources/codeaction/source/optimizeImports.bal
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#21737 Update Crypto & Auth BBEs
  examples/crypto/crypto.out
  examples/index.json
  examples/secured-client-with-basic-auth/secured_client_with_basic_auth.out
  examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.out
Labels: Area/StandardLibs, Type/Improvement

#21749 Fix kafka avro consumer error
  gradle/javaProject.gradle
  stdlib/messaging/kafka/build.gradle
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/Module.md
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/kafka_constants.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/kafka_errors.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/producer.bal
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/SendAvroValues.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaConstants.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaUtils.java
Labels: Area/StandardLibs, Component/Kafka, Priority/Blocker, Type/Bug

#21587 Add the "Building from Source" Section to the README
  README.md
Labels: Type/Docs

#21731 [gRPC] Fix oneof field as a message error
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/Message.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/UnaryBlockingOneofFieldTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/15_grpc_oneof_field_client.bal
Labels: Area/StandardLibs, Component/gRPC

#21812 Add xml BBEs to ignore list
  tests/ballerina-examples-test/build.gradle
Labels: Priority/Blocker

#21783 Fix Kafka BBEs
  examples/kafka_message_consumer_group_service/kafka_message_consumer_group_service.bal
  examples/kafka_message_consumer_service/kafka_message_consumer_service.bal
  examples/kafka_message_consumer_service/kafka_message_consumer_service.out
  examples/kafka_message_consumer_simple/kafka_message_consumer_simple.bal
  examples/kafka_message_producer_transactional/kafka_message_producer_transactional.out
Labels: Area/StandardLibs

#21827 Rename file names as directory names.
  examples/send-and-receive-emails/send_and_receive_emails.description
  examples/send-and-receive-emails/send_and_receive_emails_1_smtp.bal
  examples/send-and-receive-emails/send_and_receive_emails_1_smtp.out
  examples/send-and-receive-emails/send_and_receive_emails_2_pop.bal
  examples/send-and-receive-emails/send_and_receive_emails_2_pop.out
  examples/send-and-receive-emails/send_and_receive_emails_3_imap.bal
  examples/send-and-receive-emails/send_and_receive_emails_3_imap.out
Labels: Area/StandardLibs

#21816 Fix JSON to CSV Transform example with Ballerina 1.2.0 release
  examples/json-csv/json_csv.bal
Labels: Area/StandardLibs

#21775 Update Access Control BBEs
  examples/index.json
  examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.description
  examples/secured-client-with-jwt-auth/secured_service_with_jwt_auth.bal
  examples/secured-client-with-oauth2/secured_client_with_oauth2.out
  examples/secured-service-with-basic-auth/sample-users.toml
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.client.out
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.description
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.server.out
  examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.bal
  examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.client.out
  examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.description
  examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.server.out
  examples/secured-service-with-jwt-auth/tests/secured_service_with_jwt_auth_test.bal
Labels: Area/StandardLibs, Type/Improvement

#21814 Remove module alias usage in BBEs
  examples/check/check.bal
  examples/checkpanic/checkpanic.bal
  examples/crypto/crypto.bal
  examples/function-pointers/function_pointers.bal
  examples/strings/strings.bal
  examples/type-conversion/type_conversion.bal
  examples/values/values.bal
Labels: Area/Language, Component/Examples

#21810 Fix error in the 'Tuple Match' BBE src file
  examples/tuple-match-statement/tuple_match_statement.bal
Labels: Area/Language

#21440 Add Let Expression BBE
  examples/index.json
  examples/let-expression/let_expression.bal
  examples/let-expression/let_expression.description
  examples/let-expression/let_expression.out
Labels: Area/Language

#21819 Add BBE to JDBC and MySQL Connectors
  examples/index.json
  examples/jdbc2-complex-type-queries/jdbc2_complex_type_queries.bal
  examples/jdbc2-complex-type-queries/jdbc2_complex_type_queries.description
  examples/jdbc2-complex-type-queries/jdbc2_complex_type_queries.out
  examples/jdbc2-execute-operation/jdbc2_execute_operation.bal
  examples/jdbc2-execute-operation/jdbc2_execute_operation.description
  examples/jdbc2-execute-operation/jdbc2_execute_operation.out
  examples/jdbc2-init-options/jdbc2_init_options.bal
  examples/jdbc2-init-options/jdbc2_init_options.description
  examples/jdbc2-init-options/jdbc2_init_options.out
  examples/jdbc2-query-operation/jdbc2_query_operation.bal
  examples/jdbc2-query-operation/jdbc2_query_operation.description
  examples/jdbc2-query-operation/jdbc2_query_operation.out
  examples/mysql-complex-type-queries/mysql_complex_type_queries.bal
  examples/mysql-complex-type-queries/mysql_complex_type_queries.description
  examples/mysql-complex-type-queries/mysql_complex_type_queries.out
  examples/mysql-execute-operation/mysql_execute_operation.bal
  examples/mysql-execute-operation/mysql_execute_operation.description
  examples/mysql-execute-operation/mysql_execute_operation.out
  examples/mysql-init-options/mysql_init_options.bal
  examples/mysql-init-options/mysql_init_options.description
  examples/mysql-init-options/mysql_init_options.out
  examples/mysql-query-operation/mysql_query_operation.bal
  examples/mysql-query-operation/mysql_query_operation.description
  examples/mysql-query-operation/mysql_query_operation.out
Labels: Component/Database

#21745 Fix BBE related to Lock statement
  examples/index.json
  examples/locks/locks.out
Labels: Area/Language

#21776 Update examples for mapping constructor changes
  examples/maps/maps.bal
  examples/maps/maps.out
  examples/records/records.bal
  examples/records/records.out
Labels: Area/Language

#21828 Add @tainted for the return param of query operation
  stdlib/database/jdbc2/src/main/ballerina/src/java.jdbc/client.bal
  stdlib/database/jdbc2/src/test/java/org/ballerinalang/jdbc/query/ComplexTypesQueryTest.java
  stdlib/database/jdbc2/src/test/resources/test-src/execute/execute-basic-test.bal
  stdlib/database/jdbc2/src/test/resources/test-src/query/complex-query-test.bal
  stdlib/database/jdbc2/src/test/resources/test-src/query/numerical-query-test.bal
  stdlib/database/mysql/src/main/ballerina/src/mysql/client.bal
  stdlib/database/mysql/src/test/resources/test-src/execute/execute-basic-test.bal
  stdlib/database/mysql/src/test/resources/test-src/query/complex-query-test.bal
  stdlib/database/mysql/src/test/resources/test-src/query/numerical-query-test.bal
  stdlib/database/sql/src/main/ballerina/src/sql/client.bal
Labels: Component/Database

#21784 Enable few disabled xml tests
  langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserPositiveTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/xml.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_multiple_typed_params.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal
Labels: Area/Language

#21710 Add BBE for deprecation
  examples/basic-documentation/basic_documentation.bal
  examples/basic-documentation/basic_documentation.description
  examples/basic-documentation/basic_documentation.out
  examples/deprecation/deprecation.bal
  examples/deprecation/deprecation.description
  examples/deprecation/deprecation.out
  examples/index.json
Labels: Area/Language, Type/Docs

#21782 Add record type definition support
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/AbstractTokenReader.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserListener.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/LexerTerminals.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/TokenReader.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/incremental/HybridTokenReader.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STModuleTypeDefinition.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRecordField.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRecordFieldWithDefaultValue.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRecordRestDescriptor.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRecordTypeDescriptor.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRecordTypeReference.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/BLModules.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/LocalVariableDeclaration.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordFieldNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordFieldWithDefaultValueNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordRestDescriptorNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordTypeDescriptorNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordTypeReferenceNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TypeDefinitionNode.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/SyntaxTreeJSONGenerator.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/declarations/RecordTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_01.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_02.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_03.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_04.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_05.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_06.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_07.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_08.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_09.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_10.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_11.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_12.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_13.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_14.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_15.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_01.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_02.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_03.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_04.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_05.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_06.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_07.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_08.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_09.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_10.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_11.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_12.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_13.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_14.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_15.bal
  compiler/ballerina-parser/src/test/resources/test4.bal
Labels: Component/Parser

#21837 Fix taint checking BBE
  examples/taint-checking/taint_checking.bal
  examples/taint-checking/taint_checking.out
Labels: Area/Language

#21769 Fix shift and bitwise operations for int subtypes
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/ShiftUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeTags.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibSubTypeTest.java
  langlib/langlib-test/src/test/resources/test-src/subtypes/int_subtypes_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java
Labels: Area/Language, Priority/Blocker

#21808 Add BBEs for shift expressions and binary bitwise expressions
  examples/binary-bitwise-expressions/binary_bitwise_expressions.bal
  examples/binary-bitwise-expressions/binary_bitwise_expressions.description
  examples/binary-bitwise-expressions/binary_bitwise_expressions.out
  examples/index.json
  examples/shift-expressions/shift_expressions.bal
  examples/shift-expressions/shift_expressions.description
  examples/shift-expressions/shift_expressions.out
Labels: Area/Language

#21795 Fix empty space print for error with empty details
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
Labels: Area/Language

#21824 Fix vscode dist auto detection
  tool-plugins/vscode/src/core/extension.ts
Labels: Area/Tooling, Component/VScodePlugin, Priority/Blocker, Type/Bug

#21815 Fix importing modules with ballerina org name throws NoclassDef exception
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/buildcontext/BuildContext.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyNativeLibTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateBirTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateJarTask.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ProjectDirConstants.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PathDependencyTestCase.java
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case10/TestProject1/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case10/TestProject1/bar-2020r1-any-0.1.0.balo
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case10/TestProject1/src/mod1/main.bal
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case10/TestProject1/src/mod1/tests/main_test.bal
Labels: Area/BuildTools, Component/Packerina

#21774 Fix error logs of cache module
  stdlib/cache/src/main/ballerina/src/cache/cache.bal
  stdlib/cache/src/main/ballerina/src/cache/cache_errors.bal
Labels: Area/StandardLibs, Priority/High, Type/Bug

#21838 Fix displaying bullet points
  examples/object-assignability/object_assignability.description
Labels: Type/Docs

#21836 Disable http caching by default
  examples/http-caching-client/http_caching_client.bal
  examples/http-caching-client/http_caching_client.description
  stdlib/http/src/main/ballerina/src/http/caching/http_caching_client.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/34_http_caching.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/37_no_cache_service.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/38_max_age_cache_service.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/39_must_revalidate_cache_service.bal
Labels: Area/StandardLibs, Component/HTTP

#21847 Use error detail instead of reason
  examples/async/async.bal
  examples/http-1.1-to-2.0-protocol-switch/http_1.1_to_2.0_protocol_switch.bal
  examples/http-caching-client/http_caching_client.bal
  examples/http-client-endpoint/http_client_endpoint.bal
Labels: Component/Examples, Type/Improvement

#21841 Fix service lifecycle method addition to the testable's package's functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
Labels: Area/Language, Priority/Blocker

#21839 Fix un-prefixed xml import bad-sad error
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributeAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-lax-behavior.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-syntax.bal
Labels: Area/Language, Priority/Blocker

#21722 Add the Missing Descriptions of the File Module in API Docs
  stdlib/file/src/main/ballerina/src/file/file_info.bal
Labels: Component/Docerina, Type/Docs

#21860 Change the CLA Signing Section in the Contribution.md File
  CONTRIBUTING.md
Labels: Type/Docs

#21856 BBE for the new @strand annotation
  examples/index.json
  examples/threads-and-strands/threads-and-strands.bal
  examples/threads-and-strands/threads-and-strands.description
  examples/threads-and-strands/threads-and-strands.out
Labels: Component/Examples

#21866 Revert JDBC client change
  examples/jdbc-client-batch-update/jdbc_client_batch_update.bal
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.bal
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/client.bal
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/datasource/SQLDatasource.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/methods/ExternActions.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/methods/ExternFunctions.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/BatchUpdateTest.java
  stdlib/jdbc/src/test/java/org/ballerinax/jdbc/actions/UpdateTest.java
  stdlib/jdbc/src/test/resources/test-src/actions/batch_update_test.bal
  stdlib/jdbc/src/test/resources/test-src/actions/h2_actions_test.bal
  stdlib/jdbc/src/test/resources/test-src/actions/update_test.bal
  stdlib/jdbc/src/test/resources/test-src/table/table_type_test.bal
  stdlib/jdbc/src/test/resources/test-src/table/table_type_test_nillable_mapping.bal
  stdlib/jdbc/src/test/resources/test-src/transaction/local_transaction_test.bal
Labels: Area/StandardLibs, Component/Data

#21872 Flush output stream upon xml serialization
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLFactory.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
Labels: Area/Language

#21877 Fix Empty message replication issue
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/BallerinaFileBuilder.java
Labels: Area/StandardLibs, Component/gRPC

#21883 Apply fix #21872 to all xml items
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLNonElementItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLValue.java
Labels: Area/Language

#21858 Add the Missing Descriptions of the IO Module in API Docs
  language-server/modules/langserver-core/src/test/resources/completion/function/returnParameterContextSuggestion3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/returnParameterContextSuggestion6.json
  language-server/modules/langserver-core/src/test/resources/completion/function/returnParameterContextSuggestion9.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelTypeDesc2.json
  stdlib/io/src/main/ballerina/src/io/constants.bal
  stdlib/io/src/main/ballerina/src/io/readable_character_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_csv_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_record_channel.bal
Labels: Component/Docerina, Type/Docs

#21876 Add func call parsing support
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STFunctionCallExpression.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNamedArg.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STPositionalArg.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRestArg.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/FunctionArgumentNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/FunctionCallNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NamedArgumentNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/PositionalArgumentNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordTypeDescriptorNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RestArgumentNode.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/expressions/FuncCallExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_04.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_05.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_06.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_07.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_08.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_09.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_10.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_11.json
Labels: Area/Language, Component/Parser

#21886 Update threads-and-strands.description
  examples/threads-and-strands/threads-and-strands.description
Labels: Component/Examples

#21884 Fix new line issue in Deprecation
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecation_annotation_crlf.bal
Labels: Area/Language

#21935 Update access control BBEs
  examples/secured-client-with-basic-auth/secured_client_with_basic_auth.bal
  examples/secured-client-with-basic-auth/secured_client_with_basic_auth.out
  examples/secured-client-with-basic-auth/secured_service_with_basic_auth.bal
  examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.bal
  examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.out
  examples/secured-client-with-jwt-auth/secured_service_with_jwt_auth.bal
  examples/secured-client-with-oauth2/secured_client_with_oauth2.bal
  examples/secured-client-with-oauth2/secured_client_with_oauth2.out
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.bal
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.client.out
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.server.out
  examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.bal
  examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.client.out
  examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.server.out
  examples/secured-service-with-oauth2/secured_service_with_oauth2.bal
  examples/secured-service-with-oauth2/secured_service_with_oauth2.client.out
  examples/secured-service-with-oauth2/secured_service_with_oauth2.server.out
Labels: Area/StandardLibs, Type/Improvement

#21908 Fix style guide changes for union type
  docs/style_guide/README.md
  docs/style_guide/definitions.md
  docs/style_guide/operators_keywords_and_types.md
  docs/style_guide/statements.md
Labels: Area/Tooling, Type/Docs

#21939 Disable busy wait locks
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/lock/LocksInMainTest.java
Labels: Area/Language

#21940 Fix deprecation BBE output
  examples/deprecation/deprecation.out
Labels: Area/Language

#21937 Add 0.75, 0.95, 0.999 percentile values to gauge based BBE
  examples/gauge-metrics/gauge_metric.server.out
Labels: Area/Observability, Component/Observability

#21900 Remove ballerina.home property usages
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/BidiStreamingTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/Http2GatewayTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/CipherStrengthSSLTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/DisableSslTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/MutualSSLTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/MutualSSLWithCertsTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/SslProtocolTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2BaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2MutualSslTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websub/advanced/WebSubAdvancedBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/util/websocket/client/WebSocketTestClient.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/util/websocket/server/WebSocketRemoteServerInitializer.java
  tests/jballerina-integration-test/src/test/resources/ballerina.home/bre/security/ballerinaKeystore.p12
  tests/jballerina-integration-test/src/test/resources/ballerina.home/bre/security/ballerinaTruststore.p12
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/03_bidirectional_streaming_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/17_bidirectional_chat_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/03_bidirectional_streaming_service.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/16_http2_passthrough_service.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/11_http_redirects.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/15_https_echo_service.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/27_mutual_ssl_server_with_default_ciphers.bal
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/03_http_2.0_to_http_1.0_fallback_test.bal
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/09_http_2.0_mutual_ssl.bal
  tests/jballerina-integration-test/src/test/resources/security/keystore/ballerinaKeystore.p12
  tests/jballerina-integration-test/src/test/resources/security/keystore/ballerinaTruststore.p12
  tests/jballerina-integration-test/src/test/resources/ssl/disable_ssl_client.bal
  tests/jballerina-integration-test/src/test/resources/ssl/http2_mutual_ssl_client.bal
  tests/jballerina-integration-test/src/test/resources/ssl/mutual_ssl_client.bal
  tests/jballerina-integration-test/src/test/resources/ssl/mutual_ssl_client_with_cert.bal
  tests/jballerina-integration-test/src/test/resources/ssl/ssl_client_with_strong_cipher.bal
  tests/jballerina-integration-test/src/test/resources/ssl/ssl_client_with_weak_cipher.bal
  tests/jballerina-integration-test/src/test/resources/ssl/ssl_protocol_client.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-integration-test/src/test/resources/websub/publisher/src/advanced_services/01_websub_publisher.bal
Labels: Area/StandardLibs, Type/Improvement

#21946 Improve and fix a bug in the Ballerina bindgen tool
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-bindgen.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-help.help
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/components/JMethod.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenConstants.java
  misc/ballerina-bindgen/src/main/resources/templates/bridge_class.mustache
Labels: Priority/Blocker

#21955 Fix kafka consumer record throwing exception when value is BString
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaUtils.java
Labels: Area/StandardLibs, Component/Kafka, Type/Bug

#21956 Fix xml BBE output
  examples/xml-functions/xml_functions.out
  examples/xml-literal/xml_literal.out
Labels: Area/Language, Component/Examples, Type/Docs

#21934 Fix output file in expr bodied function BBE
  examples/expression-bodied-functions/expression_bodied_functions.out
Labels: Area/Language

#21909 Update local_transactions.out to match 1.2.0
  examples/local-transactions/local_transactions.out
Labels: Area/Language

#21901 Update local_transactions_with_participants.out
  examples/local-transactions-with-participants/local_transactions_with_participants.out
Labels: Area/Language

#21898 Update langlib module versions
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  langlib/lang.array/src/main/ballerina/Ballerina.toml
  langlib/lang.array/src/main/ballerina/src/lang.array/array.bal
  langlib/lang.int/src/main/ballerina/Ballerina.toml
  langlib/lang.map/src/main/ballerina/Ballerina.toml
  langlib/lang.map/src/main/ballerina/src/lang.map/map.bal
  langlib/lang.stream/src/main/ballerina/Ballerina.toml
  langlib/lang.string/src/main/ballerina/Ballerina.toml
  langlib/lang.string/src/main/ballerina/src/lang.string/string.bal
  langlib/lang.xml/src/main/ballerina/Ballerina.toml
  langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Get.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion5.json
  language-server/modules/langserver-core/src/test/resources/completion/function/groupedExpressionSuggestion1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/iterableOperation4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/typeGuardSuggestions4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions2.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest14.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest2.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest3.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest4.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest8.json
  language-server/modules/langserver-core/src/test/resources/completion/record/recordTest9.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/exprFunctionBodyCompletion3.json
Labels: Area/Language

#21961 Fix Bad, sad error when there's an HTTP service in the tests folder
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PathDependencyTestCase.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BaseTestCase.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/ServicesTest.java
  tests/testerina-integration-test/src/test/resources/services-tests/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/services-tests/src/mod1/main.bal
  tests/testerina-integration-test/src/test/resources/services-tests/src/mod1/tests/main_test.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Area/BuildTools

#21952 Disallow indexing expression within xml nav expr
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLNonElementItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-nav-access-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-navigation-access.bal
Labels: Area/Language

#21932 Fix stringValue for errors when details is an empty map
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HttpPayloadTestCase.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/varargs/JavaVarargsTest.java
Labels: Area/Language

#21897 Add the Missing Descriptions of the File Module in API Docs
  stdlib/file/src/main/ballerina/src/file/file_info.bal
Labels: Type/Docs

#21969 Fix cannot open file issue in Debugger DAP client
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java
Labels: Area/Tooling, Component/Debugger, Priority/Blocker, Type/Bug

#21970 Improve usability of the bindgen tool
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/components/JClass.java
  misc/ballerina-bindgen/src/main/resources/templates/bridge_class.mustache
  misc/ballerina-bindgen/src/main/resources/templates/jobject.mustache
Labels: Priority/Blocker

#21976 Fix Bad, sad error when transitive dependency of a module is not resolved
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/Compiler.java
Labels: Area/BuildTools

#21966 Add support for Avro records array
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/NonBlockingCallback.java
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/kafka_errors.bal
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/SendAvroValues.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaUtils.java
Labels: Area/StandardLibs, Component/Kafka, Type/Improvement

#21996 Fix issue with pulling modules with 'ballerina' org name
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/PullCommand.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/PackageLoader.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/repo/BirRepo.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/repo/NonSysRepo.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/repo/RemoteRepo.java
Labels: Area/BuildTools

#21998 Fix doc gen in the build
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
Labels: Priority/Blocker
