Repository ballerina-platform/ballerina-lang, pull requests merged in 2020-04, with the labels that each got.

#22316 [master] Add support for record -> json assignment
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/JSONUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/RecordToJSONTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/jsontype/record_to_json.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/jsontype/record_to_json_negative.bal
Labels: Area/Language

#22193 [1.2.x] Fix compiler crashing issue when other fields are referenced in record field default values
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangRecordTypeNode.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/negative/field_ref_in_own_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record.bal
Labels: Area/Language

#22217 [master] Fix compiler crashing issue when other fields are referenced in record field default values
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangRecordTypeNode.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/negative/field_ref_in_own_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record.bal
Labels: Area/Language

#22319 Fix 21259 taint analyzer issue: patch branch PR
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/23_proxy_server.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/TaintedStatusPropagationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/lambda-func.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/named-arg-to-new.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/object-tainted-assigment-to-untainted-objref.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/rest-args.bal
Labels: Area/Language, Priority/High

#22267 Fix memory leak issue in observability with payload content(1.2.x)
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/GrpcConstants.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/caller/FunctionUtils.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/client/FunctionUtils.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/nativeimpl/streamingclient/FunctionUtils.java
Labels: Area/StandardLibs

#22286 Fix taint analyze bad-sad issue 21259
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/23_proxy_server.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/TaintedStatusPropagationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/lambda-func.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/named-arg-to-new.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/object-tainted-assigment-to-untainted-objref.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/rest-args.bal
Labels: Area/Language, Priority/High

#22293 Add missing descriptions in JDBC API Docs(1.2.x)
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/client.bal
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/error.bal
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/types.bal
Labels: Area/StandardLibs, Type/Docs

#19996 Add an example for failover client
  examples/index.json
  examples/websocket-failover/websocket_failover.bal
  examples/websocket-failover/websocket_failover.description
  examples/websocket-failover/websocket_failover.out
  examples/websocket-failover/websocket_service_9094.bal
  examples/websocket-failover/websocket_service_9094.out
  examples/websocket-failover/websocket_service_9095.bal
  examples/websocket-failover/websocket_service_9095.out
Labels: Area/StandardLibs, Component/WebSocket

#22374 Fix unwanted listener endpoint creation and record creation failure for multiple services
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/BallerinaFileBuilder.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/components/ServiceFile.java
  stdlib/grpc/src/main/resources/templates/skeleton/service_sample.mustache
  stdlib/grpc/src/main/resources/templates/skeleton/service_stub_file.mustache
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/tool/multipleServices.proto
Labels: Area/StandardLibs, Component/gRPC

#22400 Mark deprecated APIs in api-docs
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/Writer.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/docs/BallerinaDocGenerator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Annotation.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Client.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Constant.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Construct.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/DefaultableVariable.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Error.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/FiniteType.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Function.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Listener.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Object.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Record.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Type.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/UnionType.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Variable.java
  misc/docerina/src/main/resources/html-template-resources/styles/css/styles.css
  misc/docerina/src/main/resources/template/html/constants.hbs
  misc/docerina/src/main/resources/template/html/errors.hbs
  misc/docerina/src/main/resources/template/html/fields.hbs
  misc/docerina/src/main/resources/template/html/functions.hbs
  misc/docerina/src/main/resources/template/html/method.hbs
  misc/docerina/src/main/resources/template/html/methodSignature.hbs
  misc/docerina/src/main/resources/template/html/module.hbs
  misc/docerina/src/main/resources/template/html/object.hbs
  misc/docerina/src/main/resources/template/html/record.hbs
  misc/docerina/src/main/resources/template/html/types.hbs
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/DeprecatedAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/FieldLevelDocsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/deprecated_annotation_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/deprecated_annotation_project/src/test_module/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/record_object_fields_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/record_object_fields_project/src/test_module/main.bal
Labels: Area/BuildTools, Component/Docerina

#22367 Fix casting error while executing process(1.2.x)
  stdlib/system/src/main/java/org/ballerinalang/stdlib/system/utils/SystemConstants.java
  stdlib/system/src/test/java/org/ballerinalang/stdlib/system/SystemTest.java
  stdlib/system/src/test/resources/test-src/system-test.bal
Labels: Area/StandardLibs

#22393 Add subtyping feature and improvements to the Ballerina bindgen tool
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-bindgen.help
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindingsGenerator.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/components/JMethod.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/components/JParameter.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/exceptions/BindgenException.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JClass.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JConstructor.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JField.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JMethod.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JParameter.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenConstants.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenUtils.java
  misc/ballerina-bindgen/src/main/resources/templates/array_utils.mustache
  misc/ballerina-bindgen/src/main/resources/templates/bridge_class.mustache
  misc/ballerina-bindgen/src/main/resources/templates/constants.mustache
  misc/ballerina-bindgen/src/main/resources/templates/empty_object.mustache
Labels: Area/BuildTools

#22394 Adds string literal expression parsing
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/LexerTerminals.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/SyntaxKind.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QuotedStringLiteralTest.java
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/quoted_string_literal_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/quoted_string_literal_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/quoted_string_literal_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/quoted_string_literal_source_02.bal
Labels: Component/Parser

#22373 Fix slice on tuple with rest descriptor
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Slice.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Area/Language

#22396 Avoid creating new types each time in StdLib extern implementations
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BValueCreator.java
  language-server/modules/langserver-core/src/test/resources/completion/function/errorLiftingSuggestions1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/typeGuardSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore2.json
  stdlib/database/sql/src/main/java/org/ballerinalang/sql/utils/Utils.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Decode.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/Message.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/proto/ServiceProtoUtils.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/stubs/BlockingStub.java
  stdlib/http/src/main/ballerina/src/http/http_request.bal
  stdlib/http/src/main/ballerina/src/http/http_response.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpResourceDataElement.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/websocket/WebSocketResourceValidator.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/ExternPushPromise.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/ExternRequest.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/ParseHeader.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketResourceCallback.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketResourceDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/observability/WebSocketObservabilityUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/URITemplate.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/URIUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/parser/Literal.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/parser/Node.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/parser/SimpleStringExpression.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/parser/Variable.java
  stdlib/http/src/test/resources/test-src/services/cors/cors-test.bal
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/AbstractSQLStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java
  stdlib/jvm-old/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JInterop.java
  stdlib/jvm-old/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JMethod.java
  stdlib/jvm-old/src/main/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JInterop.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JMethod.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/ConsumerInformationHandler.java
  stdlib/mime/src/main/ballerina/src/mime/natives.bal
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/EntityHeaders.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/EntityBodyHandler.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/HeaderUtil.java
  stdlib/websub/src/main/ballerina/src/websub/commons.bal
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/nativeimpl/SubscriberNativeOperationHandler.java
Labels: Area/StandardLibs

#22404 Prioritise filed-level docs over object/record def-level docs
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/FieldLevelDocsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/record_object_fields_project/src/test_module/main.bal
Labels: Area/BuildTools, Component/Docerina

#22314 Throw unused import error along with semantic errors
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/Compiler.java
Labels: Area/BuildTools

#22366 Add Object method mocking functionality
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestAnnotationProcessor.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/MockTest.java
  tests/testerina-integration-test/src/test/resources/project-based-tests/mock-tests/src/Mock/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/mock-tests/src/Mock/tests/main_test.bal
Labels: Area/TestFramework, Component/Testerina

#22290 Fix the issue in proto compiler when proto filepath contains white space(master)
  misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/cmd/GrpcCmd.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/BallerinaFileBuilder.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/tool/a b/helloWorld.proto
Labels: Area/StandardLibs, Component/gRPC

#22384 Revert "[1.2.x] Add support for map -> record assignment"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/MapToRecordAssignabilityTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/negative/map_to_record_negative.bal
Labels: Area/Language

#22263 Refactor api doc generation for std libs
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateDocsTask.java
  distribution/zip/jballerina-tools/build.gradle
  distribution/zip/jballerina/build.gradle
  gradle/balNativeLibProject.gradle
  gradle/javaProjectWithExtBalo.gradle
  misc/ballerina-gradle-plugins/docerina-gradle-plugin/src/main/java/org/ballerinalang/plugin/gradle/doc/DocerinaGen.java
  misc/docerina/build.gradle
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/docs/BallerinaDocGenerator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/docs/utils/BallerinaDocUtils.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Module.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Type.java
  misc/lib-creator/build.gradle
  misc/lib-creator/src/main/java/org/ballerinalang/stdlib/utils/GenerateBalo.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/Main.java
Labels: Area/BuildTools, Component/Docerina

#22287 [1.2.x] Add deprecation support
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/MarkdownDocumentationNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkDownDocumentationDeprecatedParametersAttributeNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserBaseListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangMarkdownDocumentation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangMarkDownDeprecatedParametersDocumentation.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  langlib/lang.annotations/src/main/ballerina/src/lang.annotations/annotations.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/connectors/SQLTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecation_annotation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecation_annotation_negative.bal
Labels: Area/Language

#22327 [1.2.x] Add markdown doc for annotation
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/documentation/DocumentationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/documentation/test_documentation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_documentation/src/test/test_documentation_symbol.bal
Labels: Area/Language

#22407 Avoid creating new types each time in StdLib extern implementations[master]
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BValueCreator.java
  language-server/modules/langserver-core/src/test/resources/completion/function/errorLiftingSuggestions1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/typeGuardSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore2.json
  stdlib/database/sql/src/main/java/org/ballerinalang/sql/utils/Utils.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Decode.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/Message.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/proto/ServiceProtoUtils.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/stubs/BlockingStub.java
  stdlib/http/src/main/ballerina/src/http/http_request.bal
  stdlib/http/src/main/ballerina/src/http/http_response.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpResourceDataElement.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/websocket/WebSocketResourceValidator.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/ExternPushPromise.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/ExternRequest.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/ParseHeader.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketResourceCallback.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketResourceDispatcher.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/observability/WebSocketObservabilityUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/URITemplate.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/URIUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/parser/Literal.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/parser/Node.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/parser/SimpleStringExpression.java
  stdlib/http/src/main/java/org/ballerinalang/net/uri/parser/Variable.java
  stdlib/http/src/test/resources/test-src/services/cors/cors-test.bal
  stdlib/jvm-old/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JInterop.java
  stdlib/jvm-old/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JMethod.java
  stdlib/jvm-old/src/main/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JInterop.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/interop/JMethod.java
  stdlib/jvm/src/main/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/ConsumerInformationHandler.java
  stdlib/mime/src/main/ballerina/src/mime/natives.bal
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/EntityHeaders.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/EntityBodyHandler.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/HeaderUtil.java
  stdlib/websub/src/main/ballerina/src/websub/commons.bal
  stdlib/websub/src/main/java/org/ballerinalang/net/websub/nativeimpl/SubscriberNativeOperationHandler.java
Labels: Area/StandardLibs

#22406 Add mapping constructor expression parsing support
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STComputedNameField.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STMappingConstructorExpression.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STMappingField.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STSpecificField.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STSpreadField.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ComputedNameField.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/MappingConstructorExpression.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SpecificField.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SpreadField.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxNodeVisitor.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/MappingConstructorTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QuotedStringLiteralTest.java
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/quoted_string_literal_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/quoted_string_literal_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/quoted_string_literal_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_04.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_05.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_06.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_07.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_08.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_09.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_10.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_11.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_12.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_13.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_14.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_15.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_16.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_17.json
Labels: Component/Parser

#22417 Fix missing identifier after dot in member access
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/AccessExpressionsTest.java
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/member_access_expr_assert_06.json
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/member_access_expr_assert_07.json
Labels: Component/Parser

#22313 Throw unused import error along with semantic errors
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/Compiler.java
Labels: Area/BuildTools

#22449 Improve NodeList API to get nodes
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/FunctionDefinitionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ModulePart.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeList.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/TreeTraversalAPITest.java
Labels: Component/Parser

#22271 [master] Add deprecation support
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/MarkdownDocumentationNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkDownDocumentationDeprecatedParametersAttributeNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.tokens
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserBaseListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangMarkdownDocumentation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangMarkDownDeprecatedParametersDocumentation.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  langlib/lang.annotations/src/main/ballerina/src/lang.annotations/annotations.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationExpressionCodeAnalysisNegative.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/connectors/SQLTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachment_expression_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecation_annotation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecation_annotation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_documentation/src/test/test_documentation_symbol.bal
Labels: Area/Language

#22461 Add service decl parsing support
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/LexerTerminals.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STExpressionListItem.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STServiceBody.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STServiceDeclaration.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ExpressionListItem.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ServiceBody.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ServiceDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxNodeVisitor.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ServiceDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_01.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_02.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_03.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_04.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_05.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_06.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_07.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_08.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_09.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_10.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_11.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_12.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_01.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_02.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_03.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_04.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_05.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_06.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_07.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_08.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_09.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_10.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_11.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_12.bal
  compiler/ballerina-parser/src/test/resources/types/simple-types/simple_types_assert_01.json
Labels: Component/Parser

#22464 Update performance test results for Ballerina v1.2.1
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Area/StandardLibs, Type/Task

#22323 Add support for xml constraint type
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BXMLType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeTags.java
  langlib/lang.typedesc/src/main/java/org/ballerinalang/langlib/typedesc/ConstructFrom.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/SetChildren.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_constrained_negative_test.bal
  langlib/langlib-test/src/test/resources/test-src/xmllib_constrained_test.bal
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/RefEqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/CloneOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/LengthOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsWithVarMutabilityTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/AnydataStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/StampInbuiltFunctionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/UnionTypeStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/XMLStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/ExprBodiedFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLNativeFunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/ref_equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/clone-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/length-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable-with-variable-mutability.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_infer_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language

#22388 Add subtyping feature and improvements to the Ballerina bindgen tool
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-bindgen.help
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindingsGenerator.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/components/JMethod.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/components/JParameter.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/exceptions/BindgenException.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JClass.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JConstructor.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JField.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JMethod.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JParameter.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenConstants.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenUtils.java
  misc/ballerina-bindgen/src/main/resources/templates/array_utils.mustache
  misc/ballerina-bindgen/src/main/resources/templates/bridge_class.mustache
  misc/ballerina-bindgen/src/main/resources/templates/constants.mustache
  misc/ballerina-bindgen/src/main/resources/templates/empty_object.mustache
Labels: Area/BuildTools

#22467 Add code-action support for xml constraint type
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CursorSymbolFindingVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementFunctionsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateTestExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/TestGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/ValueSpaceGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/AbstractTestTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/RootTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/FunctionTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/HttpResourceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/HttpServiceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/template/type/WSServiceTemplate.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/ImportsAcceptor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TokensUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/definition/LSStandardLibCache.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/definition/LSStdLibCacheUtil.java
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction11.json
Labels: Area/Tooling, Component/LanguageServer, Type/NewFeature

#22511 Fix direct return of byte binary operation in a lambda
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-value.bal
Labels: Area/jBallerina

#22512 Fix direct return of byte binary operation in a lambda
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-value.bal
Labels: Area/jBallerina

#22490 Refactor API docs in config-api module
  stdlib/config-api/src/main/ballerina/src/config/Module.md
  stdlib/config-api/src/main/ballerina/src/config/config.bal
Labels: Area/StandardLibs, Type/Docs

#22495 Update API docs for Ballerina cache module
  stdlib/cache/src/main/ballerina/src/cache/Module.md
  stdlib/cache/src/main/ballerina/src/cache/abstract_cache.bal
  stdlib/cache/src/main/ballerina/src/cache/abstract_eviction_policy.bal
  stdlib/cache/src/main/ballerina/src/cache/cache.bal
  stdlib/cache/src/main/ballerina/src/cache/cache_errors.bal
  stdlib/cache/src/main/ballerina/src/cache/linked_list.bal
  stdlib/cache/src/main/ballerina/src/cache/lru_eviction_policy.bal
Labels: Area/StandardLibs, Component/Cache, Type/Docs

#22508 Refactor the XSLT module API doc
  examples/index.json
  examples/xslt-transformation/xslt_transformation.bal
  examples/xslt-transformation/xslt_transformation.description
  examples/xslt-transformation/xslt_transformation.out
  stdlib/xslt/src/main/ballerina/src/xslt/Module.md
  stdlib/xslt/src/main/ballerina/src/xslt/natives.bal
Labels: Area/StandardLibs, Type/Docs

#22554 Add missing example code snippets
  stdlib/config-api/src/main/ballerina/src/config/natives.bal
Labels: Area/StandardLibs

#22544 Update API docs and module.md file in jsonutils
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/Module.md
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/jsonutils.bal
Labels: Area/StandardLibs, Type/Docs

#22545 Refactor the JWT module API doc
  examples/index.json
  examples/jwt-issue-validate/jwt-issue-validate.bal
  examples/jwt-issue-validate/jwt-issue-validate.description
  examples/jwt-issue-validate/jwt-issue-validate.out
  stdlib/jwt/src/main/ballerina/src/jwt/Module.md
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_errors.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_issuer.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/jwt/src/main/ballerina/src/jwt/outbound_jwt_auth_provider.bal
Labels: Area/StandardLibs, Type/Docs

#22569 Populate caller remote IP and introduce function to get remote hostname
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionAvoidRemoteFunctions.json
  stdlib/http/src/main/ballerina/src/http/http_connection.bal
  stdlib/http/src/main/ballerina/src/http/service_endpoint.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/GetRemoteHostName.java
Labels: Area/StandardLibs, Component/HTTP, Type/Bug

#22589 Fix line length of BBEs with truststore and keystore
  examples/basic-https-listener-client/basic_https_listener.bal
  examples/basic-https-listener-client/https_client.bal
  examples/crypto/crypto.bal
  examples/grpc-secured-unary/grpc_secured_unary_service.bal
  examples/https-listener/https_listener.bal
  examples/mutual-ssl/mutual_ssl_service.bal
  examples/mutual-ssl/ssl_client.bal
  examples/secured-client-with-basic-auth/secured_client_with_basic_auth.bal
  examples/secured-client-with-basic-auth/secured_service_with_basic_auth.bal
  examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.bal
  examples/secured-client-with-jwt-auth/secured_service_with_jwt_auth.bal
  examples/secured-client-with-oauth2/secured_client_with_oauth2.bal
  examples/secured-service-with-basic-auth/secured_service_with_basic_auth.bal
  examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.bal
  examples/secured-service-with-oauth2/secured_service_with_oauth2.bal
Labels: Area/StandardLibs, Type/Improvement

#22548 Fix API Docs in crypto module
  stdlib/crypto/src/main/ballerina/src/crypto/Module.md
  stdlib/crypto/src/main/ballerina/src/crypto/crypto.bal
  stdlib/crypto/src/main/ballerina/src/crypto/crypto_errors.bal
Labels: Area/StandardLibs, Type/Docs

#22581 Update API of Docs in module, Time
  stdlib/time/src/main/ballerina/src/time/Module.md
  stdlib/time/src/main/ballerina/src/time/time_errors.bal
  stdlib/time/src/main/ballerina/src/time/timelib.bal
Labels: Area/StandardLibs, Type/Docs

#22590 Move JWT module.md content into relevant objects
  examples/jwt-issue-validate/jwt-issue-validate.bal
  stdlib/jwt/src/main/ballerina/src/jwt/Module.md
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/outbound_jwt_auth_provider.bal
Labels: Area/StandardLibs, Type/Docs

#22586 Fix API docs in LDAP module
  distribution/zip/jballerina-tools/build.gradle
  examples/index.json
  examples/secured-service-with-ldap/secured_service_with_ldap.bal
  examples/secured-service-with-ldap/secured_service_with_ldap.client.out
  examples/secured-service-with-ldap/secured_service_with_ldap.description
  examples/secured-service-with-ldap/secured_service_with_ldap.server.out
  stdlib/ldap/src/main/ballerina/src/ldap/Module.md
  stdlib/ldap/src/main/ballerina/src/ldap/inbound_ldap_auth_provider.bal
  stdlib/ldap/src/main/ballerina/src/ldap/ldap_errors.bal
Labels: Area/StandardLibs, Type/Docs

#22576 Fix API docs in OAuth2 module
  stdlib/oauth2/src/main/ballerina/src/oauth2/Module.md
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/oauth2_errors.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Type/Docs

#22562 Refactor names of the auth related internal functions [1.2.x]
  stdlib/auth/src/main/ballerina/src/auth/outbound_basic_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/outbound_jwt_auth_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Type/Improvement

#22563 Refactor names of the auth related internal functions [master]
  stdlib/auth/src/main/ballerina/src/auth/outbound_basic_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/outbound_jwt_auth_provider.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Type/Improvement

#22564 Fix API docs of module-system
  stdlib/system/src/main/ballerina/src/system/Module.md
  stdlib/system/src/main/ballerina/src/system/process.bal
  stdlib/system/src/main/ballerina/src/system/system.bal
  stdlib/system/src/main/ballerina/src/system/system_errors.bal
Labels: Type/Docs

#22560 Fix API docs of module-java.arrays
  stdlib/java.arrays/src/main/ballerina/src/java.arrays/Module.md
  stdlib/java.arrays/src/main/ballerina/src/java.arrays/java_array_utils.bal
Labels: Type/Docs

#22557 Integrate the new parser to the current compiler supporting a simple helloWorld
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/RunCommand.java
  compiler/ballerina-lang/build.gradle
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/CompilerOptionName.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/PackageLoader.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangCompUnitGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/Parser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ImportDeclaration.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeList.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/PositionalArgument.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TreeModifier.java
Labels: Component/Parser, Type/NewFeature

#22599 Introducing the `treegen` tool - Generate Ballerina syntax tree nodes
  compiler/ballerina-parser/build.gradle
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STOptionalTypeDescriptor.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/OptionalTypeDescriptor.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-treegen/README.md
  compiler/ballerina-treegen/build.gradle
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/TreeGen.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/TreeGenConfig.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/TreeGenException.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/json/SyntaxNode.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/json/SyntaxNodeAttribute.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/json/SyntaxTree.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/template/Field.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/template/ImportClass.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/template/TreeNodeClass.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/template/TreeNodeVisitorClass.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/SourceText.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/Target.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/node/AbstractNodeTarget.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/node/ExternalNodeTarget.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/node/InternalNodeTarget.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/nodevisitor/AbstractNodeVisitorTarget.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/nodevisitor/ExternalNodeVisitorTarget.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/nodevisitor/NodeFactoryTarget.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/nodevisitor/NodeTransformerTarget.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/nodevisitor/STNodeFactoryTarget.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/nodevisitor/TreeModifierTarget.java
  compiler/ballerina-treegen/src/main/resources/external_node_factory_template.mustache
  compiler/ballerina-treegen/src/main/resources/external_node_template.mustache
  compiler/ballerina-treegen/src/main/resources/external_node_transformer_template.mustache
  compiler/ballerina-treegen/src/main/resources/external_node_visitor_template.mustache
  compiler/ballerina-treegen/src/main/resources/external_tree_modifier_template.mustache
  compiler/ballerina-treegen/src/main/resources/internal_node_factory_template.mustache
  compiler/ballerina-treegen/src/main/resources/internal_node_template.mustache
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  compiler/ballerina-treegen/src/main/resources/treegen_config.properties
  gradle/javaProject.gradle
  settings.gradle
Labels: Component/Parser

#22584 Support backtic documentation with tab
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_doc_inline_triple.bal
Labels: Area/Language

#22534 Fix API docs in runtime-api module
  stdlib/runtime-api/src/main/ballerina/src/runtime/Module.md
  stdlib/runtime-api/src/main/ballerina/src/runtime/errors.bal
  stdlib/runtime-api/src/main/ballerina/src/runtime/invocation-context.bal
  stdlib/runtime-api/src/main/ballerina/src/runtime/runtime.bal
Labels: Area/StandardLibs, Type/Docs

#22566 Update doc API for module, Filepath
  stdlib/filepath/src/main/ballerina/src/filepath/Module.md
  stdlib/filepath/src/main/ballerina/src/filepath/file_path.bal
  stdlib/filepath/src/main/ballerina/src/filepath/file_path_errors.bal
Labels: Area/StandardLibs, Type/Docs

#22188 Change undefined function error message
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibNegativeTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/nativeimpl/request/RequestNativeFunctionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/object/ObjectInBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/BuiltinOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/LengthOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/StringFunctionInvocationExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableArrowExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/UndefinedFunctionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/undefined-functions.bal
Labels: Area/Language

#22577 Update API docs and Module.md file in xmlutils module
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/Module.md
  stdlib/xmlutils/src/main/ballerina/src/xmlutils/xmlutils.bal
Labels: Area/StandardLibs, Type/Docs

#22493 Fix API docs in encoding and MIME modules
  examples/index.json
  examples/url-encode-decode/url_encode_decode.bal
  examples/url-encode-decode/url_encode_decode.description
  examples/url-encode-decode/url_encode_decode.out
  stdlib/encoding/src/main/ballerina/src/encoding/Module.md
  stdlib/encoding/src/main/ballerina/src/encoding/encoding.bal
  stdlib/encoding/src/main/ballerina/src/encoding/encoding_errors.bal
  stdlib/mime/src/main/ballerina/src/mime/Module.md
  stdlib/mime/src/main/ballerina/src/mime/media-types.bal
  stdlib/mime/src/main/ballerina/src/mime/mime_errors.bal
  stdlib/mime/src/main/ballerina/src/mime/natives.bal
Labels: Area/StandardLibs, Type/Docs

#22527 Refactor log api docs
  stdlib/log-api/src/main/ballerina/src/log/Module.md
  stdlib/log-api/src/main/ballerina/src/log/natives.bal
Labels: Area/StandardLibs, Type/Docs

#22556 Fix API docs in java module
  stdlib/java/src/main/ballerina/src/java/Module.md
  stdlib/java/src/main/ballerina/src/java/annotations.bal
  stdlib/java/src/main/ballerina/src/java/ballerina_values_to_Java.bal
Labels: Type/Docs

#22582 Improve API Docs in email module
  stdlib/email/src/main/ballerina/src/email/Module.md
  stdlib/email/src/main/ballerina/src/email/commons.bal
  stdlib/email/src/main/ballerina/src/email/email_errors.bal
  stdlib/email/src/main/ballerina/src/email/imap_client_endpoint.bal
  stdlib/email/src/main/ballerina/src/email/pop_client_endpoint.bal
  stdlib/email/src/main/ballerina/src/email/smtp_client_endpoint.bal
Labels: Area/StandardLibs, Type/Docs

#22629 Add api doc templates for website
  misc/docerina/src/main/resources/template/html/bioHead.hbs
Labels: Area/Tooling, Component/Docerina

#22593 Improve API Docs in gRPC module
  stdlib/grpc/src/main/ballerina/src/grpc/Module.md
  stdlib/grpc/src/main/ballerina/src/grpc/annotation.bal
  stdlib/grpc/src/main/ballerina/src/grpc/caller.bal
  stdlib/grpc/src/main/ballerina/src/grpc/client_connection_pool.bal
  stdlib/grpc/src/main/ballerina/src/grpc/client_endpoint.bal
  stdlib/grpc/src/main/ballerina/src/grpc/grpc_errors.bal
  stdlib/grpc/src/main/ballerina/src/grpc/headers.bal
  stdlib/grpc/src/main/ballerina/src/grpc/service_endpoint.bal
  stdlib/grpc/src/main/ballerina/src/grpc/streaming_client.bal
Labels: Area/StandardLibs, Component/gRPC, Type/Docs

#22549 [1.2.x] Fix member type checking issue when inferring type for list
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_infer_type.bal
Labels: Area/Language

#22551 Improve API Docs in NATS Module
  stdlib/messaging/nats/src/main/ballerina/src/nats/Module.md
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/annotation.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/message.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/producer.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/basic/subscriber.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/connection/config.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/connection/connection.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/error.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/annotation.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/config.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/listener.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/message.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/streaming/producer.bal
Labels: Area/StandardLibs, Type/Docs

#22528 Refactor the socket module API doc
  stdlib/socket/src/main/ballerina/src/socket/Module.md
  stdlib/socket/src/main/ballerina/src/socket/client_socket.bal
  stdlib/socket/src/main/ballerina/src/socket/listener_endpoint.bal
  stdlib/socket/src/main/ballerina/src/socket/socket_error.bal
  stdlib/socket/src/main/ballerina/src/socket/udp_client_socket.bal
Labels: Area/StandardLibs, Type/Docs

#22572 Update stringutils doc APIs to comply with the guidelines
  stdlib/stringutils/src/main/ballerina/src/stringutils/Module.md
  stdlib/stringutils/src/main/ballerina/src/stringutils/natives.bal
Labels: Area/StandardLibs, Component/stringutils, Type/Docs

#22630 Populate caller remote IP and introduce function to get remote hostname[1.2.x]
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionAvoidRemoteFunctions.json
  stdlib/http/src/main/ballerina/src/http/http_connection.bal
  stdlib/http/src/main/ballerina/src/http/service_endpoint.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/GetRemoteHostName.java
Labels: Area/StandardLibs, Component/HTTP

#22580 Fix API docs in module Kafka
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/Module.md
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/commons.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/deserializer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/kafka_constants.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/kafka_errors.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/producer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/serializer.bal
Labels: Area/StandardLibs, Type/Docs

#22559 Fix API docs in task module
  stdlib/task/src/main/ballerina/src/task/Module.md
  stdlib/task/src/main/ballerina/src/task/commons.bal
  stdlib/task/src/main/ballerina/src/task/listener.bal
  stdlib/task/src/main/ballerina/src/task/scheduler.bal
  stdlib/task/src/main/ballerina/src/task/task_errors.bal
  stdlib/task/src/test/java/org/ballerinalang/stdlib/task/service/AppointmentServiceTest.java
Labels: Area/StandardLibs, Type/Docs

#22565 Fix API docs in Auth module
  stdlib/auth/src/main/ballerina/src/auth/Module.md
  stdlib/auth/src/main/ballerina/src/auth/auth_errors.bal
  stdlib/auth/src/main/ballerina/src/auth/inbound_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/inbound_basic_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/outbound_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/outbound_basic_auth_provider.bal
  stdlib/auth/src/main/ballerina/src/auth/utils.bal
Labels: Area/StandardLibs, Type/Docs

#22606 Improve Ballerina-file API doc
  stdlib/file/src/main/ballerina/src/file/Module.md
  stdlib/file/src/main/ballerina/src/file/file.bal
  stdlib/file/src/main/ballerina/src/file/file_info.bal
  stdlib/file/src/main/ballerina/src/file/service_endpoint.bal
Labels: Area/StandardLibs, Type/Docs

#22608 Refactor the Websub API doc
  stdlib/websub/src/main/ballerina/src/websub/Module.md
  stdlib/websub/src/main/ballerina/src/websub/commons.bal
  stdlib/websub/src/main/ballerina/src/websub/errors.bal
  stdlib/websub/src/main/ballerina/src/websub/hub_configuration.bal
  stdlib/websub/src/main/ballerina/src/websub/hub_persistence.bal
  stdlib/websub/src/main/ballerina/src/websub/hub_service.bal
  stdlib/websub/src/main/ballerina/src/websub/natives.bal
  stdlib/websub/src/main/ballerina/src/websub/publisher_client.bal
  stdlib/websub/src/main/ballerina/src/websub/subscriber_client.bal
  stdlib/websub/src/main/ballerina/src/websub/subscriber_service_caller.bal
  stdlib/websub/src/main/ballerina/src/websub/subscriber_service_endpoint.bal
Labels: Area/StandardLibs, Type/Docs

#22568 Improve API Docs in RabbitMQ module
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/Module.md
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/channel.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/connection.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/listener.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/message.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/rabbitmq_commons.bal
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/rabbitmq_errors.bal
Labels: Area/StandardLibs, Type/Docs

#22468 Align xml default namespace behavior for attributes
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaXMLSerializer.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/types/string/StringValueXmlTest.java
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-with-namespaces.bal
Labels: Area/Language

#22603 Improve Ballerina-IO API docs
  examples/index.json
  stdlib/io/src/main/ballerina/src/io/Module.md
  stdlib/io/src/main/ballerina/src/io/io_error.bal
  stdlib/io/src/main/ballerina/src/io/open.bal
  stdlib/io/src/main/ballerina/src/io/print.bal
  stdlib/io/src/main/ballerina/src/io/read.bal
  stdlib/io/src/main/ballerina/src/io/readable_byte_channel.bal
  stdlib/io/src/main/ballerina/src/io/readable_character_channel.bal
  stdlib/io/src/main/ballerina/src/io/readable_csv_channel.bal
  stdlib/io/src/main/ballerina/src/io/readable_data_channel.bal
  stdlib/io/src/main/ballerina/src/io/readable_record_channel.bal
  stdlib/io/src/main/ballerina/src/io/strings.bal
  stdlib/io/src/main/ballerina/src/io/writable_byte_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_character_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_csv_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_data_channel.bal
  stdlib/io/src/main/ballerina/src/io/writable_record_channel.bal
Labels: Area/StandardLibs, Type/Docs

#22182 Add compiler test suite
  langlib/lang.test/build.gradle
  langlib/lang.test/src/main/ballerina/Ballerina.toml
  langlib/lang.test/src/main/ballerina/src/lang.test/test_functions.bal
  langlib/lang.test/src/main/java/org/ballerinalang/langlib/test/AssertError.java
  langlib/lang.test/src/main/java/org/ballerinalang/langlib/test/AssertFalse.java
  langlib/lang.test/src/main/java/org/ballerinalang/langlib/test/AssertNotError.java
  langlib/lang.test/src/main/java/org/ballerinalang/langlib/test/AssertTrue.java
  langlib/lang.test/src/main/java/org/ballerinalang/langlib/test/AssertValueEqual.java
  langlib/langlib-test/build.gradle
  langlib/langlib-test/src/test/resources/test-src/subtypes/char_subtypes_test.bal
  langlib/langlib-test/src/test/resources/test-src/subtypes/int_subtypes_test.bal
  settings.gradle
Labels: Area/Language

#22522 Add caller actions for HTTP error status codes
  language-server/modules/langserver-core/src/test/resources/completion/resource/actionInvocationSuggestion1.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/actionInvocationSuggestion2.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionAvoidRemoteFunctions.json
  stdlib/http/src/main/ballerina/src/http/http_connection.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/HttpClientRequest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HttpStatusCodeTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/25_http_status_codes.bal
Labels: Area/StandardLibs, Component/HTTP

#22364 [1.2.2] Fix hasfiller value for BFiniteType created for const literals
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/SealedArrayTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_fill_runtime_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_listexpr_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_semantics_negative.bal
Labels: Area/Language

#22518 Implements MIME in Email Connector
  stdlib/email/build.gradle
  stdlib/email/src/main/ballerina/src/email/commons.bal
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/client/SmtpClient.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/CommonUtil.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/SmtpUtil.java
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/ImapComplexEmailReceiveTest.java
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/PopComplexEmailReceiveTest.java
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/SmtpComplexEmailSendTest.java
  stdlib/email/src/test/resources/datafiles/corona_virus.jpg
  stdlib/email/src/test/resources/datafiles/file.xml
  stdlib/email/src/test/resources/datafiles/test.tmp
  stdlib/email/src/test/resources/test-src/ImapComplexEmailReceive.bal
  stdlib/email/src/test/resources/test-src/ImapSimpleSecureEmailReceive.bal
  stdlib/email/src/test/resources/test-src/PopComplexEmailReceive.bal
  stdlib/email/src/test/resources/test-src/PopSimpleSecureEmailReceive.bal
  stdlib/email/src/test/resources/test-src/SmtpComplexEmailSend.bal
Labels: Area/StandardLibs, Type/NewFeature

#22609 Add is expression support
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/LexerTerminals.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STIsExpression.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/IsExpression.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/IsExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_04.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_05.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_06.json
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
Labels: Component/Parser

#22401 Add MIME features to Email Connector
  stdlib/email/build.gradle
  stdlib/email/src/main/ballerina/src/email/commons.bal
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/client/SmtpClient.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/CommonUtil.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/SmtpUtil.java
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/ImapComplexEmailReceiveTest.java
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/PopComplexEmailReceiveTest.java
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/SmtpComplexEmailSendTest.java
  stdlib/email/src/test/resources/datafiles/corona_virus.jpg
  stdlib/email/src/test/resources/datafiles/file.xml
  stdlib/email/src/test/resources/datafiles/test.tmp
  stdlib/email/src/test/resources/test-src/ImapComplexEmailReceive.bal
  stdlib/email/src/test/resources/test-src/ImapSimpleSecureEmailReceive.bal
  stdlib/email/src/test/resources/test-src/PopComplexEmailReceive.bal
  stdlib/email/src/test/resources/test-src/PopSimpleSecureEmailReceive.bal
  stdlib/email/src/test/resources/test-src/SmtpComplexEmailSend.bal
Labels: Area/StandardLibs, Type/NewFeature

#22622 Write and read only the top level symbol info in BIR
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/CPEntry.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/ConstantPool.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/DocAttachmentWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/ProgramFileConstants.java
Labels: Area/jBallerina

#22289 Fix hasfiller value for BFiniteType created for const literals
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/SealedArrayTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_fill_runtime_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_listexpr_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_semantics_negative.bal
Labels: Area/Language

#22380 Fix change abstract type code-action generates invalid code
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ChangeAbstractTypeObjCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementFunctionsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/IncompatibleTypesCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/OptimizeAllImportsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TaintedParamCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/ChangeAbstractTypeObjExecutor.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CommandExecutionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/changeAbstractTypeObj1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/changeAbstractTypeObj2.json
  language-server/modules/langserver-core/src/test/resources/command/source/changeAbstractType.bal
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#22550 Fix member type checking issue when inferring type for list
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_infer_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_negative.bal
Labels: Area/Language

#22710 Replace the file name by "_"
  examples/jwt-issue-validate/jwt_issue_validate.bal
  examples/jwt-issue-validate/jwt_issue_validate.description
  examples/jwt-issue-validate/jwt_issue_validate.out
Labels: Area/StandardLibs

#22714 Limit descriptions to one sentence
  misc/docerina/src/main/java/org/ballerinalang/docgen/Writer.java
  misc/docerina/src/main/resources/template/html/module.hbs
Labels: Component/Docerina, Type/Bug

#22716 Tabularize the record configs docs
  language-server/modules/langserver-core/src/test/resources/completion/function/delimiterBasedCompletionForCompleteSource1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/ifWhileConditionContextCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/workerDeclarationContext4.json
  language-server/modules/langserver-core/src/test/resources/completion/object/objectTest13.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/globalVarDefPackageContent.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/statementWithMissingSemiColon2.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/statementWithMissingSemiColon3.json
  stdlib/http/src/main/ballerina/src/http/client_endpoint.bal
  stdlib/http/src/main/ballerina/src/http/resiliency/failover_client_endpoint.bal
  stdlib/http/src/main/ballerina/src/http/resiliency/load_balance_client_endpoint.bal
  stdlib/java/src/main/ballerina/src/java/ballerina_values_to_Java.bal
Labels: Area/StandardLibs, Type/Bug, Type/Docs

#22713 Add module overview title back to API Docs
  stdlib/auth/src/main/ballerina/src/auth/Module.md
  stdlib/cache/src/main/ballerina/src/cache/Module.md
  stdlib/config-api/src/main/ballerina/src/config/Module.md
  stdlib/crypto/src/main/ballerina/src/crypto/Module.md
  stdlib/email/src/main/ballerina/src/email/Module.md
  stdlib/encoding/src/main/ballerina/src/encoding/Module.md
  stdlib/file/src/main/ballerina/src/file/Module.md
  stdlib/filepath/src/main/ballerina/src/filepath/Module.md
  stdlib/grpc/src/main/ballerina/src/grpc/Module.md
  stdlib/http/src/main/ballerina/src/http/Module.md
  stdlib/java.arrays/src/main/ballerina/src/java.arrays/Module.md
  stdlib/java/src/main/ballerina/src/java/Module.md
  stdlib/jsonutils/src/main/ballerina/src/jsonutils/Module.md
  stdlib/jwt/src/main/ballerina/src/jwt/Module.md
  stdlib/ldap/src/main/ballerina/src/ldap/Module.md
  stdlib/log-api/src/main/ballerina/src/log/Module.md
  stdlib/math/src/main/ballerina/src/math/Module.md
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/Module.md
  stdlib/messaging/nats/src/main/ballerina/src/nats/Module.md
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/Module.md
  stdlib/mime/src/main/ballerina/src/mime/Module.md
  stdlib/oauth2/src/main/ballerina/src/oauth2/Module.md
  stdlib/runtime-api/src/main/ballerina/src/runtime/Module.md
  stdlib/socket/src/main/ballerina/src/socket/Module.md
  stdlib/task/src/main/ballerina/src/task/Module.md
  stdlib/time/src/main/ballerina/src/time/Module.md
  stdlib/websub/src/main/ballerina/src/websub/Module.md
  stdlib/xslt/src/main/ballerina/src/xslt/Module.md
Labels: Area/StandardLibs, Type/Bug, Type/Docs

#22525 Fix alignment and formatting issues
  misc/docerina/src/main/resources/html-template-resources/styles/css/styles.css
  misc/docerina/src/main/resources/template/html/functions.hbs
  misc/docerina/src/main/resources/template/html/method.hbs
  misc/docerina/src/main/resources/template/html/methodSignature.hbs
Labels: Area/BuildTools, Component/Docerina

#22666 Fix type narrowing logic to handle compile errors in type tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeTags.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
Labels: Area/Language

#22447 Remove `isFieldAnalyseRequired` from code
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangStructureTypeNode.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/AnonymousObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/AnonymousOpenRecordTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/anon_object.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/anon_record.bal
Labels: Area/Language

#22746 Use Java Optional<T> to represent optional child nodes in external syntax tree nodes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangCompUnitGen.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STAbstractNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STEmptyNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STEmptyToken.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/SyntaxUtils.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/AbstractNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/AnnotationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ChildNodeEntry.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ChildNodeList.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/FunctionDefinitionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/IfElseStatementNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ImportDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ListenerDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/MetadataNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ModuleVariableDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NonTerminalNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TypeDefinitionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/VariableDeclarationNode.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/ChildNodeListTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/SyntaxTreeModifierTest.java
  compiler/ballerina-parser/src/test/resources/tree/child_node_list_test_01.bal
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/json/SyntaxNodeAttribute.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/template/Field.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/template/TreeNodeClass.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/Target.java
  compiler/ballerina-treegen/src/main/resources/external_node_factory_template.mustache
  compiler/ballerina-treegen/src/main/resources/external_node_template.mustache
  compiler/ballerina-treegen/src/main/resources/external_tree_modifier_template.mustache
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
Labels: Component/Parser

#22730 Fix intermittent WebSocket failover test failure
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/FailoverClientTest.java
Labels: Area/StandardLibs, Component/WebSocket

#22631 [master] Support backtic documentation with White-space
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaLexer.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaLexer.g4
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_doc_inline_triple.bal
Labels: Area/Language

#22399 Fix commented LS code action test
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
Labels: Area/Tooling, Component/LanguageServer, Type/Task

#22621 Update xml langlib methods
  langlib/lang.__internal/src/main/ballerina/src/lang.__internal/xml-internal.bal
  langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Children.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/ElementChildren.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Elements.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
Labels: Area/Language

#22756 Add NodeTransformer support for Functions, Vars, Record, Mapping Constructor
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangCompUnitGen.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STDefaultableParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STObjectFieldNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRecordFieldNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRecordFieldWithDefaultValueNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRecordRestDescriptorNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRequiredParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STRestParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STTypeReferenceNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/DefaultableParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ImportDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ObjectFieldNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordFieldNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordFieldWithDefaultValueNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordRestDescriptorNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RequiredParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RestParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TypeReferenceNode.java
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
Labels: Area/Language, Component/Parser, Type/NewFeature

#22759 Update performance test results for Ballerina v1.2.2
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Area/StandardLibs, Type/Task

#22499 Fix server streaming issue when there is custom record type in Ballerina(master)
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ServiceDefinition.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/GrpcBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/ServerStreamingTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/23_server_streaming_with_record_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/23_server_streaming_with_record_type.bal
Labels: Area/StandardLibs, Component/gRPC

#22498 Fix server streaming issue when there is custom record type in Ballerina(1.2.x)
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ServiceDefinition.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/GrpcBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/ServerStreamingTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/23_server_streaming_with_record_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/23_server_streaming_with_record_type.bal
Labels: Area/StandardLibs, Component/gRPC

#22776 Populate caller remote IP and introduce function to get remote hostname[master]
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionAvoidRemoteFunctions.json
  stdlib/http/src/main/ballerina/src/http/http_connection.bal
  stdlib/http/src/main/ballerina/src/http/service_endpoint.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/GetRemoteHostName.java
Labels: Area/StandardLibs, Component/HTTP, Type/Bug

#22766 Update performance test results for Ballerina v1.1.5
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Area/StandardLibs, Type/Task

#22770 Add untracked node module directory to .gitignore
  .gitignore
Labels: Area/Build

#22798 Introduce SeparatedNodeList class that represents separated syntax node list
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STSubModuleNameNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/DefaultableParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ImportDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeList.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ObjectFieldNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordFieldNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordFieldWithDefaultValueNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RecordRestDescriptorNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RequiredParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/RestParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SeparatedNodeList.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SubModuleNameNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TypeReferenceNode.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/SeparatedNodeListTest.java
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_02.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_03.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_04.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_05.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_06.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_07.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_08.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_18.json
  compiler/ballerina-parser/src/test/resources/tree/separated_node_list_import_decl.bal
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/OccurrenceKind.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/json/SyntaxNodeAttribute.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/model/template/Field.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/Target.java
  compiler/ballerina-treegen/src/main/java/io/ballerinalang/compiler/internal/treegen/targets/nodevisitor/NodeFactoryTarget.java
  compiler/ballerina-treegen/src/main/resources/external_node_factory_template.mustache
  compiler/ballerina-treegen/src/main/resources/external_node_template.mustache
  compiler/ballerina-treegen/src/main/resources/external_tree_modifier_template.mustache
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
Labels: Component/Parser

#22318 Issue an error on stack and queue method calls on fixed-length lists
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Pop.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Push.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/arraylib_test_negative.bal
Labels: Area/Language

#22779 Add caller actions for HTTP error status codes
  language-server/modules/langserver-core/src/test/resources/completion/resource/actionInvocationSuggestion1.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/actionInvocationSuggestion2.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionAvoidRemoteFunctions.json
  stdlib/http/src/main/ballerina/src/http/http_connection.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/HttpClientRequest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HttpStatusCodeTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/25_http_status_codes.bal
Labels: Area/StandardLibs, Component/HTTP, Type/Improvement

#22760 Add deprecation tag in API docs for source annotation, function param, and object field
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  misc/docerina/src/main/resources/template/html/annotations.hbs
  misc/docerina/src/main/resources/template/html/method.hbs
  misc/docerina/src/main/resources/template/html/module.hbs
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/DeprecatedAnnotationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/deprecated_annotation_project/src/test_module/main.bal
Labels: Area/BuildTools, Component/Docerina

#22640 Fix issue of initializing hex literals to decimal type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/NumericLiteralSupport.java
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueTest.java
  tests/jballerina-bstring-unit-test/src/test/resources/test-src/types/decimal/decimal_value.bal
  tests/jballerina-bstring-unit-test/src/test/resources/test-src/types/decimal/decimal_value_negative_literal.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_value_negative_literal.bal
Labels: Area/Language

#22825 Add Line Breaks to the Paragraph with the API Docs link
  examples/maps/maps.description
  examples/streams/streams.description
  examples/table/table.description
  examples/tuple-type/tuple_type.description
  examples/xml-functions/xml_functions.description
Labels: Type/Docs

#22320 Enable parallel run of strands where global locks arent shared inside locks
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BLockStore.java
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIRLockOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/cyclefind/GlobalVariableRefAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BInvokableSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangLock.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/lock/LocksInMainTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-imports-test/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-imports-test/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-imports-test/src/mod1/Module.md
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-imports-test/src/mod1/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-imports-test/src/mod1/resources/.keep
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-imports-test/src/mod2/Module.md
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-imports-test/src/mod2/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-imports-test/src/mod2/resources/.keep
  tests/jballerina-unit-test/src/test/resources/test-src/lock/parallel-run-lock.bal
Labels: Area/Language

#22838 Add support for field-access, type-reference and inclusive record-defitions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangCompUnitGen.java
Labels: Area/Language, Component/Parser, Type/NewFeature

#22823 Refactor JWT module internals [master]
  stdlib/jwt/src/main/ballerina/src/jwt/Module.md
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_issuer.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/jwt/src/test/java/org.ballerinalang.stdlib.jwt/JwtIssuerAndValidatorTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/TokenPropagationTest.java
Labels: Area/StandardLibs, Component/JWT, Type/Improvement

#22795 Fixed bugs relating to generation of service file for gRPC [1.2.x]
  stdlib/grpc/src/main/resources/templates/skeleton/service_sample.mustache
Labels: Area/StandardLibs, Component/gRPC

#22850 Remove exclusion of LDAP module
  gradle/balNativeLibProject.gradle
Labels: Area/StandardLibs, Component/LDAP, Type/Improvement

#22812 Fix issues in API Docs
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/Writer.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/docs/BallerinaDocGenerator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Annotation.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Client.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Constant.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Construct.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/DefaultableVariable.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Error.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/FiniteType.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Function.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Listener.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Object.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Record.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Type.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/UnionType.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Variable.java
  misc/docerina/src/main/resources/html-template-resources/styles/css/styles.css
  misc/docerina/src/main/resources/template/html/constants.hbs
  misc/docerina/src/main/resources/template/html/errors.hbs
  misc/docerina/src/main/resources/template/html/fields.hbs
  misc/docerina/src/main/resources/template/html/functions.hbs
  misc/docerina/src/main/resources/template/html/method.hbs
  misc/docerina/src/main/resources/template/html/methodSignature.hbs
  misc/docerina/src/main/resources/template/html/module.hbs
  misc/docerina/src/main/resources/template/html/object.hbs
  misc/docerina/src/main/resources/template/html/record.hbs
  misc/docerina/src/main/resources/template/html/types.hbs
  tests/jballerina-unit-test/build.gradle
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/DeprecatedAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/FieldLevelDocsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/deprecated_annotation_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/deprecated_annotation_project/src/test_module/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/record_object_fields_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/record_object_fields_project/src/test_module/main.bal
Labels: Area/BuildTools, Component/Docerina

#22854 Add try-catch statement to the body of generated main method
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmErrorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  settings.gradle
  tests/jballerina-integration-test/build.gradle
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/listener/LaunchListenerTestCase.java
  tests/jballerina-integration-test/src/test/resources/listener/hello_world.bal
  tests/jballerina-integration-test/src/test/resources/listener/hello_world_service.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/launch-listener-test-util-libs/test-launch-listener-01/build.gradle
  tests/launch-listener-test-util-libs/test-launch-listener-01/src/main/java/org/ballerina/test/listener/TestLaunchListener.java
  tests/launch-listener-test-util-libs/test-launch-listener-01/src/main/resources/META-INF/services/org.ballerinalang.jvm.launch.LaunchListener
  tests/launch-listener-test-util-libs/test-launch-listener-02/build.gradle
  tests/launch-listener-test-util-libs/test-launch-listener-02/src/main/java/org/ballerina/test/listener/TestLaunchListener.java
  tests/launch-listener-test-util-libs/test-launch-listener-02/src/main/resources/META-INF/services/org.ballerinalang.jvm.launch.LaunchListener
  tests/launch-listener-test-util-libs/test-launch-listener-03/build.gradle
  tests/launch-listener-test-util-libs/test-launch-listener-03/src/main/java/org/ballerina/test/listener/TestLaunchListener.java
  tests/launch-listener-test-util-libs/test-launch-listener-03/src/main/resources/META-INF/services/org.ballerinalang.jvm.launch.LaunchListener
  tests/launch-listener-test-util-libs/test-launch-listener-04/build.gradle
  tests/launch-listener-test-util-libs/test-launch-listener-04/src/main/java/org/ballerina/test/listener/TestLaunchListener.java
  tests/launch-listener-test-util-libs/test-launch-listener-04/src/main/resources/META-INF/services/org.ballerinalang.jvm.launch.LaunchListener
Labels: Area/jBallerina

#22691 Runtime API for asynchronously executing function pointers from native functions
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/AsyncFunctionCallback.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BRuntime.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FPValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BFunctionPointer.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/AsyncFunctionCallBack.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Filter.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/ForEach.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Map.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Reduce.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Sort.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Filter.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/ForEach.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Map.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Reduce.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Filter.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/ForEach.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Map.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibMapTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/maplib_test.bal
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeWithBValueAPITests.java
Labels: Area/jBallerina

#22777 Fix NPE in API doc gen when typedesc default values are used
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangSimpleVarRef.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
Labels: Area/Language, Area/Tooling

#22833 Update grammar of simple-const-expr according to 2020R1 specification
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/types/finite/FiniteTypeTest.java
  tests/jballerina-bstring-unit-test/src/test/resources/test-src/types/finite/finite-type.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finite/FiniteTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/finite/finite-type.bal
Labels: Area/Language

#22847 Refactor JWT module internals [1.2.x]
  stdlib/jwt/src/main/ballerina/src/jwt/Module.md
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_issuer.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/jwt/src/test/java/org.ballerinalang.stdlib.jwt/JwtIssuerAndValidatorTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/TokenPropagationTest.java
Labels: Area/StandardLibs, Component/JWT, Type/Improvement

#22879 Add deprecation tag in API docs for source annotation, function param, and object field
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  misc/docerina/src/main/resources/template/html/annotations.hbs
  misc/docerina/src/main/resources/template/html/method.hbs
  misc/docerina/src/main/resources/template/html/module.hbs
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/DeprecatedAnnotationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/deprecated_annotation_project/src/test_module/main.bal
Labels: Area/BuildTools, Component/Docerina

#22889 Add NodeTransformer support for nil-literal, global-var-def, optional and if-else
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/Parser.java
Labels: Area/Language, Component/Parser, Type/NewFeature

#22904 Fix typos of JWT API docs [master]
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_issuer.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/jwt/src/main/ballerina/src/jwt/outbound_jwt_auth_provider.bal
Labels: Area/StandardLibs, Component/JWT, Type/Docs

#22903 Fix typos of JWT API docs [1.2.x]
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_issuer.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/jwt/src/main/ballerina/src/jwt/outbound_jwt_auth_provider.bal
Labels: Area/StandardLibs, Component/JWT, Type/Docs

#22861 Remove the old TOML parser
  bvm/ballerina-config/build.gradle
  bvm/ballerina-config/src/main/java/org/ballerinalang/bcl/parser/BConfigLangListener.java
  bvm/ballerina-rt/build.gradle
  cli/ballerina-cli-module/build.gradle
  cli/ballerina-packerina/build.gradle
  compiler/ballerina-lang/build.gradle
  misc/toml-parser/build.gradle
  misc/toml-parser/spotbugs-exclude.xml
  misc/toml-parser/src/main/java/org/ballerinalang/toml/antlr4/Toml.tokens
  misc/toml-parser/src/main/java/org/ballerinalang/toml/antlr4/TomlBaseListener.java
  misc/toml-parser/src/main/java/org/ballerinalang/toml/antlr4/TomlErrorListener.java
  misc/toml-parser/src/main/java/org/ballerinalang/toml/antlr4/TomlLexer.java
  misc/toml-parser/src/main/java/org/ballerinalang/toml/antlr4/TomlLexer.tokens
  misc/toml-parser/src/main/java/org/ballerinalang/toml/antlr4/TomlListener.java
  misc/toml-parser/src/main/java/org/ballerinalang/toml/antlr4/TomlParser.java
  misc/toml-parser/src/main/java/org/ballerinalang/toml/antlr4/TomlProcessor.java
  misc/toml-parser/src/main/resources/Toml.g4
  settings.gradle
Labels: Area/BuildTools

#22860 Add support for fork statement incremental parser
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/LexerTerminals.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STForkStatementNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ForkStatementNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/BlockStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/ForkStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/LockStatementTest.java
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_assert_01.json
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_assert_02.json
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_assert_03.json
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_assert_04.json
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_assert_05.json
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_assert_07.json
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_assert_08.json
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_source_01.bal
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_source_02.bal
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_source_03.bal
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_source_04.bal
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_source_05.bal
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_source_06.bal
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_source_07.bal
  compiler/ballerina-parser/src/test/resources/statements/fork-stmt/fork_stmt_source_08.bal
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
Labels: Component/Parser

#22352 Allow passing args for non-rest params via the vararg
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Slice.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
  tests/jballerina-bstring-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/functions/FunctionSignatureInBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleRestDescriptorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/functions/test_different_function_signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/functions/test_different_function_signatures_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/src/foo/different_function_signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function_call_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/method_call_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_negative.bal
Labels: Area/Language

#22734 Refactor record, tuple and error var desugar logic
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
Labels: Area/Language

#22827 Add floating point literal support
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/FloatLiteralTest.java
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_assert_04.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_assert_05.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_source_01.bal
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_source_02.bal
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_source_03.bal
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_source_04.bal
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_source_05.bal
Labels: Component/Parser

#22916 [1.2.x] Add start and complete methods to Compiler Plugins
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/plugins/AbstractCompilerPlugin.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/plugins/CompilerPlugin.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/ballerina-compiler-plugin-test/build.gradle
  tests/ballerina-compiler-plugin-test/src/test/java/io/ballerina/test/compiler/plugins/CompilerPluginTest.java
  tests/ballerina-compiler-plugin-test/src/test/java/io/ballerina/test/compiler/plugins/FunctionsTestCompilerPlugin.java
  tests/ballerina-compiler-plugin-test/src/test/java/io/ballerina/test/compiler/plugins/TestCompilerPlugin.java
  tests/ballerina-compiler-plugin-test/src/test/java/io/ballerina/test/compiler/plugins/TestEvent.java
  tests/ballerina-compiler-plugin-test/src/test/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/compiler_plugin_test.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/formats/yaml/yaml.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/images/gif/jms.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/images/jpeg/http.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/images/png/ws.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin_test.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/test-project/Ballerina.toml
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/test-project/src/functions/data.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/test-project/src/services/data.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/test-project/src/types/data.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/testng.xml
  tests/ballerina-test-utils/spotbugs-exclude.xml
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/balo/BaloCreator.java
Labels: Area/Language

#22791 Add types with a type-parameter
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/LexerTerminals.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STParameterizedTypeDescriptorNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/ParameterizedTypeDescriptorNode.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/ParameterizedTypeTest.java
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_01.bal
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_02.bal
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_02.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_03.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_04.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_05.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_06.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_07.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_08.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_09.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_10.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_11.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_12.json
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
Labels: Component/Parser

#22943 Fix LDAP SSL configurations [1.2.x]
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/LdapConstants.java
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/nativeimpl/InitLdapConnectionContext.java
Labels: Area/StandardLibs, Component/LDAP, Type/Bug

#22867 Fix NPE while retrieving certificate with invalid alias [1.2.x]
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Decode.java
Labels: Area/StandardLibs, Component/Crypto, Type/Bug

#22868 Fix NPE while retrieving certificate with invalid alias [master]
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Decode.java
Labels: Area/StandardLibs, Component/Crypto, Type/Bug

#22945 Fix LDAP SSL configurations [master]
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/LdapConstants.java
  stdlib/ldap/src/main/java/org/ballerinalang/stdlib/ldap/nativeimpl/InitLdapConnectionContext.java
Labels: Area/StandardLibs, Component/LDAP, Type/Bug

#22918 Add start and complete methods to Compiler Plugins
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/plugins/AbstractCompilerPlugin.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/plugins/CompilerPlugin.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/ballerina-compiler-plugin-test/build.gradle
  tests/ballerina-compiler-plugin-test/src/test/java/io/ballerina/test/compiler/plugins/CompilerPluginTest.java
  tests/ballerina-compiler-plugin-test/src/test/java/io/ballerina/test/compiler/plugins/FunctionsTestCompilerPlugin.java
  tests/ballerina-compiler-plugin-test/src/test/java/io/ballerina/test/compiler/plugins/TestCompilerPlugin.java
  tests/ballerina-compiler-plugin-test/src/test/java/io/ballerina/test/compiler/plugins/TestEvent.java
  tests/ballerina-compiler-plugin-test/src/test/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/compiler_plugin_test.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/formats/yaml/yaml.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/images/gif/jms.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/images/jpeg/http.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin/images/png/ws.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/compiler_plugin_test.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/test-project/Ballerina.toml
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/test-project/src/functions/data.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/test-project/src/services/data.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/test-src/test-project/src/types/data.bal
  tests/ballerina-compiler-plugin-test/src/test/resources/testng.xml
  tests/ballerina-test-utils/spotbugs-exclude.xml
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/balo/BaloCreator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/BaloCreator.java
Labels: Area/Language

#22946 Fix LDAP BBE [1.2.x]
  examples/secured-service-with-ldap/secured_service_with_ldap.bal
Labels: Area/StandardLibs, Component/LDAP, Type/Bug

#22768 Fix issue in RabbitMQ compiler plugin
  stdlib/messaging/rabbitmq/build.gradle
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/RabbitMQResourceValidator.java
  stdlib/messaging/rabbitmq/src/main/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin
  stdlib/messaging/rabbitmq/src/test/java/org/ballerinalang/rabbitmq/JBallerinaTestInitializer.java
  stdlib/messaging/rabbitmq/src/test/java/org/ballerinalang/rabbitmq/RabbitMQServiceCompilationTest.java
  stdlib/messaging/rabbitmq/src/test/resources/test-src/invalid_data_binding.bal
  stdlib/messaging/rabbitmq/src/test/resources/test-src/invalid_on_error.bal
  stdlib/messaging/rabbitmq/src/test/resources/test-src/invalid_on_message.bal
  stdlib/messaging/rabbitmq/src/test/resources/test-src/missing_annotations.bal
  stdlib/messaging/rabbitmq/src/test/resources/test-src/valid_consumer.bal
  stdlib/messaging/rabbitmq/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/Messaging

#22928 Improve Table isAssignable check
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTableType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangTableTypeNode.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal
  langlib/langlib-test/src/test/resources/test-src/tablelib_test_negative.bal
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureNegativeTest.java
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/taintchecking/connectors/SQLTest.java
  tests/jballerina-bstring-unit-test/src/test/resources/test-src/functions/different-function-signatures-semantics-negative.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/lock/LocksInMainTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/connectors/SQLTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-value.bal
Labels: Area/Language

#22947 Fix LDAP BBE [master]
  examples/secured-service-with-ldap/secured_service_with_ldap.bal
Labels: Area/StandardLibs, Component/LDAP, Type/Bug

#22906 Split `newMap` instruction into `newType` and `newMap`
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypedescType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BTypedesc.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BValueCreator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/InstructionEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeWithBValueAPITests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeWithBValueAPITests.java
Labels: Area/Language

#22909 Move JWT caching operations to validation logic [master]
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
Labels: Area/StandardLibs, Component/JWT, Type/Improvement

#22917 Introduce new API to validate OAuth2 tokens & move OAuth2 caching operations to validation logic [master]
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
Labels: Area/StandardLibs, Component/OAuth2, Type/Improvement

#22890 Add API to generate public key from JWKs parameters [master]
  bvm/ballerina-core/build.gradle
  gradle/javaLibsProject.gradle
  stdlib/crypto/build.gradle
  stdlib/crypto/src/main/ballerina/src/crypto/crypto.bal
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Decode.java
Labels: Area/StandardLibs, Component/Crypto, Type/NewFeature

#22843 Add listener functionality to receive emails
  stdlib/email/build.gradle
  stdlib/email/src/main/ballerina/src/email/imap_client_endpoint.bal
  stdlib/email/src/main/ballerina/src/email/listener_endpoint.bal
  stdlib/email/src/main/ballerina/src/email/pop_client_endpoint.bal
  stdlib/email/src/main/ballerina/src/email/smtp_client_endpoint.bal
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/client/EmailAccessClient.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/server/EmailConnector.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/server/EmailConnectorException.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/server/EmailConnectorFactory.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/server/EmailConsumer.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/server/EmailEvent.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/server/EmailListener.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/server/EmailListenerHelper.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/service/compiler/EmailListenerCompilerPlugin.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/CommonUtil.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java
  stdlib/email/src/main/java/org/ballerinalang/stdlib/email/util/SmtpUtil.java
  stdlib/email/src/main/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/ListenerImapReceiveTest.java
  stdlib/email/src/test/java/org/ballerinalang/stdlib/email/ListenerPopReceiveTest.java
  stdlib/email/src/test/resources/test-src/ListenerImapReceive.bal
  stdlib/email/src/test/resources/test-src/ListenerPopReceive.bal
  stdlib/email/src/test/resources/test-src/SmtpComplexEmailSend.bal
  stdlib/email/src/test/resources/testng.xml
Labels: Area/StandardLibs, Type/NewFeature
