Repository ballerina-platform/ballerina-lang, pull requests merged in 2020-02, with the labels that each got.

#20789 Implement code coverage report generation for Testerina.
  cli/ballerina-packerina/build.gradle
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/TestCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CreateJsonTask.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunTestsTask.java
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-build.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-test.help
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ProjectDirConstants.java
  distribution/zip/jballerina-tools/build.gradle
  distribution/zip/jballerina-tools/jacoco/jacocoagent.jar
  distribution/zip/jballerina-tools/jacoco/jacococli.jar
  misc/testerina/modules/testerina-code-coverage/build.gradle
  misc/testerina/modules/testerina-code-coverage/src/main/java/org/ballerinalang/coverage/CoverageConstants.java
  misc/testerina/modules/testerina-code-coverage/src/main/java/org/ballerinalang/coverage/ExecutionCoverageBuilder.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/BTestRunner.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TesterinaConstants.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/entity/TestJsonData.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/entity/TestMetaData.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/entity/TestSuite.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/entity/TesterinaFunction.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/util/TesterinaUtils.java
  misc/testerina/modules/testerina-launcher/build.gradle
  misc/testerina/modules/testerina-launcher/src/main/java/org/ballerinalang/testerina/Executor.java
  settings.gradle
Labels: Area/Tooling, Component/LanguageServer, Type/NewFeature

#20817 Fix `Create local variable` code action breaks code
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/source/createVariable2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction5.json
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#19723 Implement retry for webSocket endpoint
  language-server/modules/langserver-core/src/test/resources/completion/function/delimiterBasedCompletionForCompleteSource1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/ifWhileConditionContextCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/matchStatementSuggestions4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/workerDeclarationContext4.json
  language-server/modules/langserver-core/src/test/resources/completion/object/objectTest13.json
  language-server/modules/langserver-core/src/test/resources/completion/packageimport/packageImport1.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/globalVarDefPackageContent.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/statementWithMissingSemiColon2.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/statementWithMissingSemiColon3.json
  language-server/modules/langserver-core/src/test/resources/completion/toplevel/topLevelPackageContentAccess.json
  stdlib/http/src/main/ballerina/src/http/websocket/websocket_client.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketException.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketUtil.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/client/InitEndpoint.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/client/RetryContext.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/client/WebSocketClientConnectorListener.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/client/WebSocketClientHandshakeListener.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/client/WebSocketClientHandshakeListenerForRetry.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/server/WebSocketServerService.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/ClientErrorsTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/RetryClientTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/SimpleProxyTestCommons.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/WebSocketTestCommons.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/util/websocket/server/WebSocketRemoteServer.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/27_client_exceptions.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/30_retry_client.bal
  tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/31_retry_client_with_configurations.bal
Labels: Area/StandardLibs, Component/WebSocket, Type/Improvement

#19998 Add an example for webSocket retry
  examples/websocket-retry/websocket_retry.bal
  examples/websocket-retry/websocket_retry.description
  examples/websocket-retry/websocket_retry.out
  examples/websocket-retry/websocket_service.bal
  examples/websocket-retry/websocket_service.out
Labels: Area/StandardLibs, Component/WebSocket

#20818 Fix `Create local variable` code action breaks code
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/source/createVariable2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction5.json
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#20860 Fix "Create Local Variable" code action not working for object fields
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#20859 Fix "Create Local Variable" code action not working for object fields
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#20849 Avoid suggesting non-public object fields
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FilterUtils.java
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion2.json
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/errorLiftingSuggestions1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/source/chainCompletion2.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/source/chainCompletion3.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/typeGuardSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore2.json
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#20778 Fix lang-xml.isElement() function
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/IsElement.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
Labels: Area/Language

#20852 Trim the scope string [1.1.x]
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Component/OAuth2, Type/Bug

#20853 Trim the scope string [master]
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Component/OAuth2, Type/Bug

#20866 Add the Security Policy Link to the 1.1.x README.md File
  README.md
Labels: Type/Docs

#20835 Add the Security Policy Link to the 1.1.x README.md File
  README.md
Labels: Type/Docs

#20831 Add the Latest Content from the security.md of the Staging Website Repo
  security.md
Labels: Type/Docs

#20908 Add import module version support for the code action
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/command/CommandArgument.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddAllDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ChangeAbstractTypeObjCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ChangeAbstractTypeObjExecutorCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTestCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTestExecutorCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImportModuleExecutorCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/IncompatibleTypesCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/PullModeExecutorCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/PullModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TaintedParamCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/VariableAssignmentCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/DocsCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/ServicesBasedCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/ImportModuleExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/MessageExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/PullModuleExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CommandExecutionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/packagePull1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/packagePull2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/source/packagePull.bal
Labels: Area/Tooling, Component/LanguageServer, Type/Improvement

#20926 Fix function-generation with nested-arrays and function types not working
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CommandExecutionTest.java
  language-server/modules/langserver-core/src/test/resources/command/createUndefinedFunction7.json
  language-server/modules/langserver-core/src/test/resources/command/source/createUndefinedFunction5.bal
Labels: Area/Tooling

#20911 Add import module version support for the code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/packagePull1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/packagePull2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/source/packagePull.bal
Labels: Area/Tooling, Component/LanguageServer, Type/Improvement

#20928 Fix function-generation with nested-arrays and function types not working
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CommandExecutionTest.java
  language-server/modules/langserver-core/src/test/resources/command/createUndefinedFunction7.json
  language-server/modules/langserver-core/src/test/resources/command/source/createUndefinedFunction5.bal
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#20910 Align the function and object method related grammar with the spec
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserBaseListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserListener.java
  compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormatterCustomErrorStrategy.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/SubRuleParserErrorStrategy.java
  language-server/modules/langserver-core/src/test/resources/formatting/arrowExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedArrowExpr.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/InvalidSyntaxParserTest.java
Labels: Area/Language

#20854 Handle Ballerina reserved literal name when generating code from proto(1.1.x)
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/components/Field.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/tool/helloWorldWithReservedNames.proto
Labels: Area/StandardLibs, Component/gRPC

#20847 Handle Ballereina reserved literal name when generating code from proto
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/components/Field.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/tool/helloWorldWithReservedNames.proto
Labels: Area/StandardLibs

#20833 Add the Security Policy Link to the README.md File
  README.md
Labels: Type/Docs

#20940 Update the index.json file
  examples/index.json
  examples/websocket-retry/websocket_retry.bal
  examples/websocket-retry/websocket_retry.description
  examples/websocket-retry/websocket_retry.out
  examples/websocket-retry/websocket_service.bal
  examples/websocket-retry/websocket_service.out
Labels: Area/StandardLibs

#20747 Prevent compiling of test bal files when not required
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/RunCommand.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
  cli/ballerina-packerina/src/test/resources/test-resources/project-with-test-errors/Ballerina.toml
  cli/ballerina-packerina/src/test/resources/test-resources/project-with-test-errors/src/module1/Module.md
  cli/ballerina-packerina/src/test/resources/test-resources/project-with-test-errors/src/module1/main.bal
  cli/ballerina-packerina/src/test/resources/test-resources/project-with-test-errors/src/module1/tests/main_test.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/FilterSearch.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/PathConverter.java
Labels: Area/BuildTools

#20946 Fix cleaning of entire target directory during a single module build
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CleanTargetDirTask.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
Labels: Area/BuildTools

#20827 Prevent compiling of test bal files when not required
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/RunCommand.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
  cli/ballerina-packerina/src/test/resources/test-resources/project-with-test-errors/Ballerina.toml
  cli/ballerina-packerina/src/test/resources/test-resources/project-with-test-errors/src/module1/Module.md
  cli/ballerina-packerina/src/test/resources/test-resources/project-with-test-errors/src/module1/main.bal
  cli/ballerina-packerina/src/test/resources/test-resources/project-with-test-errors/src/module1/tests/main_test.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/FilterSearch.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/PathConverter.java
Labels: Area/BuildTools

#20944 Fix function type rest param formatting
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/types/FunctionTypeNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFunctionTypeNode.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFunctionType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/functionType.bal
Labels: Area/Tooling, Component/Formatting

#20887 Migrate generateNewXML* to use StringValue
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLFactory.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/BmpStringValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/DecimalValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FPValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FutureValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/HandleValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/NonBmpStringValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamingJsonValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TupleValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLIterator.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLQName.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/utils/StringUtils.java
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_terminator_gen.bal
  gradle/birProject.gradle
  langlib/lang.error/src/main/java/org/ballerinalang/langlib/error/StackTrace.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneReadOnly.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/ToString.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/MultipartDataSource.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringValueXmlTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-value-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-value-xml-test.bal
Labels: Area/jBallerina

#20949 Fix cleaning of entire target directory during a single module build
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CleanTargetDirTask.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
Labels: Area/BuildTools

#20891 Add missing license statement and fix function type rest param formatting issue
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/types/FunctionTypeNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFunctionTypeNode.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFunctionType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/functionType.bal
  misc/ballerina-formatter/src/main/java/org/ballerinalang/format/Messages.java
  misc/ballerina-formatter/src/test/java/org/ballerinalang/format/FormatCmdTest.java
  misc/openapi-ballerina/modules/ballerina-to-openapi-generator/src/main/java/org/ballerinalang/ballerina/openapi/convertor/service/OpenApiEndpointMapper.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenContractCmd.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenServiceCmd.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiComponent.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiOperation.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiParameter.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiPath.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiRequestBody.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiSchema.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiType.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/utils/TypeExtractorUtil.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/test/java/org/ballerinalang/openapi/cmd/OpenApiGenServiceCmdTest.java
Labels: Area/Tooling, Component/ToolSwagger

#20962 Add support for line break in array literal
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorVariableDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFieldBasedAccess.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedListConstructorExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedMatchStmt.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedReturn.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTupleType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedXMLElementLiteral.bal
  language-server/modules/langserver-core/src/test/resources/formatting/listConstructorExpr.bal
Labels: Area/Tooling

#20874 Implement test functionality for single test files
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/TestCommand.java
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-test.help
  examples/testerina-assertions/testerina_assertions.out
  examples/testerina-before-and-after-suite/testerina_before_and_after_suite.out
  examples/testerina-before-and-after-test/testerina_before_and_after_test.out
  examples/testerina-before-each-test/testerina_before_each_test.out
  examples/testerina-data-driven-tests/testerina_data_driven_tests.out
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/BTestRunner.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/entity/TesterinaReport.java
Labels: Area/BuildTools, Area/TestFramework

#20804 Return error for already used http:Responses
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/HttpBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HTTPCallerActionsTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/45_dirty_response.bal
Labels: Area/StandardLibs

#20820 Add HTTP/1.1 trailer test cases
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore2.json
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/src/http/http_request.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/HttpBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/TrailingHeadersTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2TrailingHeadersTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/45_trailing_headers.bal
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/12_http_2.0_trailing_headers.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/HTTP, Type/Improvement

#20970 Migrate generateStringLoadIns to use StringValue
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/StringUtils.java
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringValueBasicsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-value-test.bal
Labels: Area/jBallerina

#20681 Fix an issue in top level variable definition
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/SymTag.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/Symbols.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/proto/ServiceProtoBuilder.java
  stdlib/jvm-old/src/main/ballerina/src/jvm/jtypes.bal
  stdlib/jvm/src/main/ballerina/src/jvm/jtypes.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/AssignStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/variable/shadowing/ShadowingNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/variable/shadowing/ShadowingTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/var-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/variable/shadowing/shadowing.bal
  tests/jballerina-unit-test/src/test/resources/test-src/variable/shadowing/shadowing_negative.bal
Labels: Area/Language

#20872 Fix 'function not defined' error
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/TypeConstants.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java
  langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Next.java
  langlib/lang.stream/src/main/java/org/ballerinalang/langlib/stream/Next.java
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/Next.java
  langlib/lang.table/src/main/java/org/ballerinalang/langlib/table/Next.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Next.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Area/Language

#20783 Review the Java File and Help Text of the Build Command
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/CompileFlagWithBuildCommandTest.java
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-build.help
Labels: Type/Docs

#20991 Return error for already used http:Responses
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/HttpBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HTTPCallerActionsTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/46_dirty_response.bal
Labels: Area/StandardLibs, Component/HTTP

#20999 Update performance test results for Ballerina v1.1.1
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Area/StandardLibs, Type/Task

#20992 Add HTTP/1.1 trailer test cases(master)
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore2.json
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/src/http/http_request.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/HttpBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HTTPCallerActionsTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/TrailingHeadersTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2TrailingHeadersTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/45_dirty_response.bal
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/45_trailing_headers.bal
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/12_http_2.0_trailing_headers.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/HTTP

#20909 Provide proper error message if JAVA_HOME is invalid on Windows
  distribution/zip/jballerina/bin/ballerina.bat
Labels: Area/BuildTools

#20969 Add support for line break in array literal
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/formatting/FormattingTest.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedErrorVariableDefinition.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedFieldBasedAccess.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedListConstructorExpr.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedMatchStmt.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedReturn.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTupleType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedXMLElementLiteral.bal
  language-server/modules/langserver-core/src/test/resources/formatting/listConstructorExpr.bal
Labels: Area/Tooling, Component/Formatting

#20750 Fix issue of not showing errors of `Settings.toml`
  compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/parser/SettingsProcessor.java
  compiler/ballerina-lang/src/test/java/org/ballerinalang/toml/InvalidSettingsTomlTest.java
  compiler/ballerina-lang/src/test/resources/invalid-settings.toml
Labels: Area/BuildTools

#20895 Handle the exception thrown when user lacks permission to bal files
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ProjectDirs.java
Labels: Area/BuildTools

#21029 Fix OpenAPI client generation doesn't generate the specify module directory
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/CodeGenerator.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenClientCmd.java
Labels: Area/Tooling, Component/ToolSwagger

#21026 Fix OpenApi plugin issues
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/SourceDirectoryManager.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenServiceCmd.java
  misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenAPIValidatorPlugin.java
Labels: Area/Tooling, Component/ToolSwagger

#20996 Include resources to module jar
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/RunCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/TestCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyResourcesTask.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
  cli/ballerina-packerina/src/test/resources/test-resources/valid-project/src/mymodule/resources/myresource/insideDirectory.txt
Labels: Area/BuildTools

#20917 Make listener variables final
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/InvalidSyntaxParserTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finaltypes/FinalAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/finaltypes/final-field-test-negative.bal
Labels: Area/Language

#20980 Improve reading array of values via config API
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/GetConfig.java
  stdlib/config-api/src/test/java/org/ballerinalang/stdlib/config/ConfigTest.java
  stdlib/config-api/src/test/resources/datafiles/array_negative.conf
  stdlib/config-api/src/test/resources/datafiles/array_negative2.conf
  stdlib/config-api/src/test/resources/datafiles/default/ballerina.conf
  stdlib/config-api/src/test/resources/test-src/config.bal
Labels: Area/StandardLibs

#20937 Support inferring types for mapping constructor expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/anydata/AnydataNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/uniontypes/UnionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor_infer_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor_infer_record_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/var_name_field.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-semantics-native.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_negative_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/uniontypes/union_types_basic.bal
Labels: Area/Language

#20998 Improve reading array of values via config API
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/GetConfig.java
  stdlib/config-api/src/test/java/org/ballerinalang/stdlib/config/ConfigTest.java
  stdlib/config-api/src/test/resources/datafiles/array_negative.conf
  stdlib/config-api/src/test/resources/datafiles/array_negative2.conf
  stdlib/config-api/src/test/resources/datafiles/default/ballerina.conf
  stdlib/config-api/src/test/resources/test-src/config.bal
Labels: Area/StandardLibs

#21034 Include resources to module jar
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/RunCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/TestCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyResourcesTask.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
  cli/ballerina-packerina/src/test/resources/test-resources/valid-project/src/mymodule/resources/myresource/insideDirectory.txt
Labels: Area/BuildTools

#20981 Add Kafka observability integration tests
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Send.java
  tests/jballerina-integration-test/build.gradle
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/KafkaMetricsTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/util/MetricsTestUtil.java
  tests/jballerina-integration-test/src/test/resources/observability/metrics/kafka-consumer-metrics-test.bal
  tests/jballerina-integration-test/src/test/resources/observability/metrics/kafka-error-metrics-test.bal
  tests/jballerina-integration-test/src/test/resources/observability/metrics/kafka-producer-metrics-test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/Kafka, Type/Improvement

#21019 Link the Code of Conduct in Bio from the CODE-OF-CONDUCT.md File
  CODE_OF_CONDUCT.md
Labels: Type/Docs

#21044 Fix invocation whitepsace issue in formatting
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedInvocation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/invocation.bal
Labels: Area/Tooling, Component/Formatting

#21056 Fix formatting issue for tuple variable
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTupleType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/tupleType.bal
Labels: Area/Tooling, Component/Formatting

#21055 Fix tuple variable formatting issue
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedTupleType.bal
  language-server/modules/langserver-core/src/test/resources/formatting/tupleType.bal
Labels: Area/Tooling, Component/Formatting

#21050 Fix invocation formatting issue for string
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  language-server/modules/langserver-core/src/test/resources/formatting/expected/expectedInvocation.bal
  language-server/modules/langserver-core/src/test/resources/formatting/invocation.bal
Labels: Area/Tooling, Component/Formatting

#20985 Link the Download and Install Section of the README File to B.io
  README.md
Labels: Type/Docs

#21021 Link the Security Policy in Bio from the SECURITY.md File
  SECURITY.md
Labels: Type/Docs

#21090 Fix program crashes in nats
  stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/connection/Init.java
  stdlib/messaging/nats/src/test/java/org/ballerinalang/nats/streaming/NatsStreamingSubscriberCompilationTest.java
  stdlib/messaging/nats/src/test/resources/test-src/basic/nats_invalid_url.bal
Labels: Area/StandardLibs

#21108 Fix error handling bug
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Decode.java
Labels: Area/StandardLibs, Component/Crypto, Type/Bug

#21105 Upgrade Netty version to 4.1.45
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
Labels: Area/StandardLibs, Type/Task

#21126 Update performance test results for Ballerina v1.1.2
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Area/StandardLibs, Type/Task

#21017 Add custom serializer / deserializer support for Ballerina Kafka module
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BRuntime.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/connector/NonBlockingCallback.java
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  stdlib/messaging/kafka/src/main/ballerina/Ballerina.toml
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/Module.md
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/commons.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/deserializer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/producer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/serializer.bal
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Poll.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/ProducerActions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Send.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/SendAnyKeys.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/SendAnyValues.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/observability/KafkaMetricsUtil.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/serdes/BallerinaKafkaDeserializer.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/serdes/BallerinaKafkaSerializer.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaConstants.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaUtils.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/consumer/KafkaConsumerTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/producer/KafkaProducerTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/serdes/KafkaSerializerDeserializerTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/ssl/KafkaConsumerAndProducerWithSSLTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/utils/KafkaTestUtils.java
  stdlib/messaging/kafka/src/test/resources/test-src/consumer/kafka_consumer.bal
  stdlib/messaging/kafka/src/test/resources/test-src/serdes/kafka_serializer.bal
  stdlib/messaging/kafka/src/test/resources/test-src/services/kafka_service_advanced.bal
  stdlib/messaging/kafka/src/test/resources/testng.xml
  tests/jballerina-integration-test/build.gradle
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/kafka/KafkaSerializerDeserializerTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/KafkaMetricsTestCase.java
  tests/jballerina-integration-test/src/test/resources/messaging/kafka/kafka_custom_serdes_test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/Kafka, Type/Improvement

#21144 Fix the Code of Conduct Bio Page Link in the code-of-conduct.md File
  CODE_OF_CONDUCT.md
Labels: Type/Docs

#21005 Add Back the Contribution Guide in B.io to the Contributing.MD File
  CONTRIBUTING.md
  SECURITY.md
Labels: Type/Docs

#21117 Execute ballerina commands even if there are spaces in the path
  distribution/zip/jballerina/bin/ballerina
  distribution/zip/jballerina/bin/ballerina.bat
Labels: Area/BuildTools

#21145 Add quick fix for abstract object implementation
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ChangeAbstractTypeObjCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTestCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementFunctionsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/VariableAssignmentCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/ChangeAbstractTypeObjExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateTestExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateVariableExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/TestGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/sourceprune/SourcePruner.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TokensUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/ReferencesKeys.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/ReferencesSubRuleParser.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/ReferencesUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/SymbolReferenceFindingVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/SymbolReferencesModel.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CommandExecutionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fixReturnType1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fixReturnType2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fixReturnType3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignoreReturnValueCodeAction.json
  language-server/modules/langserver-core/src/test/resources/codeaction/implementFuncObj.json
  language-server/modules/langserver-core/src/test/resources/codeaction/markUntaintedCodeAction1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/markUntaintedCodeAction2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/source/implementFuncObj.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/typeGuardCodeAction1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/typeGuardCodeAction2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/typeGuardCodeAction3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/typeGuardCodeAction4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/variableAssignmentRequiredCodeAction7.json
Labels: Area/Tooling, Component/LanguageServer, Type/NewFeature

#21172 Fix integration test failure in observability test suite
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/KafkaMetricsTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/MetricsTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/tracing/TracingTestCase.java
  tests/jballerina-integration-test/src/test/resources/observability/metrics/metrics-test.bal
  tests/jballerina-integration-test/src/test/resources/observability/metrics/websocket-metrics-test.bal
Labels: Area/StandardLibs

#21174 Fix integration test failure in observability test suite(1.1.x)
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/MetricsTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/tracing/TracingTestCase.java
  tests/jballerina-integration-test/src/test/resources/observability/metrics/metrics-test.bal
  tests/jballerina-integration-test/src/test/resources/observability/metrics/websocket-metrics-test.bal
Labels: Area/StandardLibs

#21189 Fix NPE while decoding private key with invalid alias [master]
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Decode.java
Labels: Area/StandardLibs, Component/Crypto, Type/Bug

#21190 Fix NPE while decoding private key with invalid alias [1.1.x]
  stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Decode.java
Labels: Area/StandardLibs, Component/Crypto, Type/Bug

#21119 Remove unused compile error
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
Labels: Area/Language

#20809 Create single global lock, program wide, for the phase one of lock stabilisation.
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BLock.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BLockStore.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGenEnv.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIROptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangLock.java
  stdlib/bir-old/src/main/ballerina/src/bir/bir_func_body_parser.bal
  stdlib/bir-old/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir-old/src/main/ballerina/src/bir/emitter/bir_instruction_emitter.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_func_body_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/src/bir/emitter/bir_instruction_emitter.bal
Labels: Area/Language

#20740 Refactor the type def model for locally defined record types
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/types/StructureTypeNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangStructureTypeNode.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingConstants.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/format/FormattingNodeTree.java
Labels: Area/Language

#21204 [RabbitMQ TestGrid] Fix issue in consuming messages with data binding
  stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/MessageDispatcher.java
Labels: Area/StandardLibs, Type/Bug

#20995 Add a compiler phase to propagate constants before annotation process
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/CompilerPhase.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangConstRef.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangSimpleVarRef.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/ExtendedLSCompiler.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompilerUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/LSNodeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/SymbolReferenceFindingVisitor.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/compiler/ResourceSignatureValidator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annotations_constant_propagation.bal
Labels: Area/Language

#21024 Improve the grpc command to only create essentials in client and service modes
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/BallerinaFileBuilder.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/components/AbstractStub.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/components/ServiceFile.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/components/StubFile.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/builder/utils/BalGenConstants.java
  stdlib/grpc/src/main/resources/templates/skeleton/service_sample.mustache
  stdlib/grpc/src/main/resources/templates/skeleton/service_stub_file.mustache
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java
Labels: Area/StandardLibs, Component/gRPC

#21217 Add path component to file:FileInfo
  stdlib/file/src/main/ballerina/src/file/file_info.bal
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/utils/FileUtils.java
  stdlib/file/src/test/java/org/ballerinalang/stdlib/file/FileTest.java
Labels: Area/StandardLibs, Type/Improvement

#21227 Add path component to file:FileInfo
  stdlib/file/src/main/ballerina/src/file/file_info.bal
  stdlib/file/src/main/java/org/ballerinalang/stdlib/file/utils/FileUtils.java
  stdlib/file/src/test/java/org/ballerinalang/stdlib/file/FileTest.java
Labels: Area/StandardLibs, Type/Improvement

#21240 Make constructNonBlockingDataSource API public for MGW usage
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/AbstractGetPayloadHandler.java
Labels: Area/StandardLibs, Type/Improvement

#21234 Respond 404 when services are not attached to a listener
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpDispatcher.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/dispatching/UriTemplateDispatcherTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/utils/MessageUtils.java
  stdlib/http/src/test/resources/test-src/services/dispatching/uri-template.bal
Labels: Area/StandardLibs, Type/Bug

#20749 Fill-in missing values by list constructor
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BArrayType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValueImpl.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BFiniteType.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/testgen/ValueSpaceGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Type.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/proto/ServiceProtoUtils.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayFillTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayFillTestRuntime.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/SealedArrayTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-fill-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_fill_runtime_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed-array-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed-array.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_listexpr_negative.bal
Labels: Area/Language

#21250 Make the TransactionParticipantConfig Type Public in Master
  stdlib/transactions/src/main/ballerina/src/transactions/annotation.bal
Labels: Type/Docs

#21253 Make the TransactionParticipantConfig Type Public in 1.1.x
  stdlib/transactions/src/main/ballerina/src/transactions/annotation.bal
Labels: Component/Docerina, Type/Docs

#21255 Make the TransactionParticipantConfig Type Public in 1.0.x
  stdlib/transactions/src/main/ballerina/src/transactions/annotation.bal
Labels: Component/Docerina, Type/Docs

#21155 Fix dynamic service registration issue in gRPC(1.1.x)
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ServicesBuilderUtils.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/GrpcBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/ServiceUnavailableTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/UnaryAnonymousServiceTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/20_unary_client_for_anonymous_service.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/03_bidirectional_streaming_service.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/04_client_streaming_service.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/20_grpc_anonymous_service.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#21154 Fix dynamic service registration issue in gRPC
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ServicesBuilderUtils.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/GrpcBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/ServiceUnavailableTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/UnaryAnonymousServiceTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/20_unary_client_for_anonymous_service.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/03_bidirectional_streaming_service.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/04_client_streaming_service.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/20_grpc_anonymous_service.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#21271 Disable syntax highlighting feature in vscode
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  tool-plugins/vscode/src/extension.ts
Labels: Area/Tooling, Component/LanguageServer, Type/Task

#21280 Allow HTTP trailer for empty payloads
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/TrailingHeadersTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2TrailingHeadersTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/45_trailing_headers.bal
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/12_http_2.0_trailing_headers.bal
Labels: Area/StandardLibs, Type/Bug

#21277 Fix gRPC gzip compression issue
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/InboundMessage.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/MessageFramer.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ProtoUtils.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/GrpcBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/UnaryGZipEncodingTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/21_grpc_gzip_encoding_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/21_grpc_gzip_encoding_service.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/gRPC

#21185 Add "Optimize All Imports" code action
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/CodeActionKeys.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/CodeActionNodeType.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/spi/LSCodeActionProvider.java
  language-server/modules/langserver-compiler/src/test/resources/testng.xml
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/DocumentServiceOperationContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionProvidersHolder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddAllDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ChangeAbstractTypeObjCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTestCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementFunctionsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/IncompatibleTypesCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/OptimizeAllImportsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/PullModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TaintedParamCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/VariableAssignmentCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/semantichighlighter/SemanticHighlightProvider.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/test/resources/codeaction/optimizeImports.json
  language-server/modules/langserver-core/src/test/resources/codeaction/source/optimizeImports.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#21295 Respond 404 when services are not attached to a listener[master]
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpDispatcher.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/dispatching/UriTemplateDispatcherTest.java
  stdlib/http/src/test/java/org/ballerinalang/stdlib/utils/MessageUtils.java
  stdlib/http/src/test/resources/test-src/services/dispatching/uri-template.bal
Labels: Area/StandardLibs, Type/Bug

#21296 Allow HTTP trailer for empty payloads [master]
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/AbstractGetPayloadHandler.java
  stdlib/websub/src/main/ballerina/Ballerina.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/TrailingHeadersTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2TrailingHeadersTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/45_trailing_headers.bal
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/12_http_2.0_trailing_headers.bal
Labels: Area/StandardLibs, Type/Bug

#21137 Fix duplicate declarations in ballerina tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case7/TestProject1/src/foo/tests/main_test.bal
  tests/jballerina-unit-test/build.gradle
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/testerina/TopLevelNodesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/testerina/TopLevelNodesDupTest/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/testerina/TopLevelNodesDupTest/src/duptest/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/testerina/TopLevelNodesDupTest/src/duptest/tests/main_test.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Area/Language

#21279 Fix gRPC gzip compression issue
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/InboundMessage.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/MessageFramer.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ProtoUtils.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/GrpcBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/UnaryGZipEncodingTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/21_grpc_gzip_encoding_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/grpcservices/21_grpc_gzip_encoding_service.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/gRPC

#21278 Fix typetest equality check in TypeChecker
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypedescType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typedesc/typedesc_positive.bal
Labels: Area/Language

#21334 Improve error reporting in BallerinaDocumentService and BallerinaExampleService
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentServiceImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/example/BallerinaExampleServiceImpl.java
Labels: Area/Tooling, Component/LanguageServer, Type/Improvement
