Repository ballerina-platform/ballerina-lang, pull requests merged in 2020-01, with the labels that each got.

#20503 Add constant for NATS default URL
  examples/nats-basic-client/publisher.bal
  examples/nats-basic-client/subscriber.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/commons.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/connection/connection.bal
Labels: Area/StandardLibs, Component/Messaging

#20494 Add constant for NATS default URL
  examples/nats-basic-client/publisher.bal
  examples/nats-basic-client/subscriber.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/commons.bal
  stdlib/messaging/nats/src/main/ballerina/src/nats/connection/connection.bal
Labels: Area/StandardLibs, Component/Messaging

#20491 Update performance test results for Ballerina v1.1.0
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Area/Language, Type/Task

#20507 Update performance test results for Ballerina v1.1.0
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Area/Language, Type/Task

#20489 Update taint-checking BBE
  examples/taint-checking/taint_checking.bal
Labels: Area/Language, Type/Bug

#20510 Update taint-checking BBE
  examples/taint-checking/taint_checking.bal
Labels: Area/Language, Type/Bug

#20518 Update performance test results for Ballerina v1.1.0
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Area/Language, Type/Task

#20539 Add the Security Policy
  SECURITY.md
Labels: Type/Docs

#20525 Fix ballerina test debug mode does not print debug suspended msg
  distribution/zip/jballerina/bin/ballerina
  distribution/zip/jballerina/bin/ballerina.bat
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  tool-plugins/vscode/src/server/server.ts
Labels: Area/Tooling, Component/CLI, Component/LanguageServer, Type/Improvement

#20432 Fix tests in debug mode doesn't give any output until a remote debug client is connected
  distribution/zip/jballerina/bin/ballerina
  distribution/zip/jballerina/bin/ballerina.bat
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  tool-plugins/vscode/src/server/server.ts
Labels: Area/Tooling, Component/CLI, Component/LanguageServer, Type/Improvement

#19951 Implement Invoking subscription functions in Ballerina
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/streams/DefaultStreamSubscription.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/streams/StreamSubscription.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/streams/StreamSubscriptionManager.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  langlib/lang.stream/build.gradle
  langlib/lang.stream/src/main/ballerina/src/lang.stream/internal.bal
  langlib/lang.stream/src/main/ballerina/src/lang.stream/stream.bal
  langlib/lang.stream/src/main/java/org/ballerinalang/langlib/stream/AddSubscriptionFunc.java
  langlib/lang.stream/src/main/java/org/ballerinalang/langlib/stream/GetSubscriptionFuncs.java
  langlib/lang.stream/src/main/java/org/ballerinalang/langlib/stream/Publish.java
  langlib/lang.stream/src/main/java/org/ballerinalang/langlib/stream/Subscribe.java
  stdlib/streams/src/test/java/org/ballerinalang/stdlib/streams/nativeimpl/BallerinaStreamsV2SimplePatternTest.java
Labels: Area/Language

#20506 Fix NPE on duplicate field in record declaration
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/negative/duplicate-key-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_duplicated_key.bal
Labels: Area/Language

#20514 [1.1.x] Fix NPE on duplicate field in record declaration
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/negative/duplicate-key-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_duplicated_key.bal
Labels: Area/Language

#20519 Fix wrong position in defaultable parameters
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
Labels: Area/Language, Component/Compiler, Component/CompilerDiagnostics

#20523 [1.1.x] Fix wrong position in defaultable parameters
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java
Labels: Area/Language

#20537 Fix NPE found on list constructor type checking
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_negative.bal
Labels: Area/Language

#20536 Fix NPE found on list constructor type checking
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_negative.bal
Labels: Area/Language

#20550 Fix cannot debug language server with BAL_DEBUG_OPTS
  tool-plugins/vscode/src/server/server.ts
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#20549 Fix cannot debug language server with BAL_DEBUG_OPTS
  tool-plugins/vscode/src/server/server.ts
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#20562 Fix SignatureHelp source pruner not getting reset
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#20563 Fix SignatureHelp source pruner not getting reset
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
Labels: Area/Tooling, Component/LanguageServer, Type/Bug

#20122 Use '/modules/info' REST endpoint to find latest module version
  compiler/ballerina-lang/build.gradle
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/URIConverter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/URIDryConverter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/RepoUtils.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PackagingTestCase.java
Labels: Area/BuildTools

#20520 Refactor OAuth2 outbound cache
  stdlib/oauth2/src/main/ballerina/Ballerina.toml
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Component/OAuth2, Type/Improvement

#20511 Hide Ballerina cache usage for JWT cache
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
Labels: Area/StandardLibs, Component/JWT, Type/Improvement

#20385 Fix message information issue in OpenAPI tooling
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/CodeGenerator.java
  misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/OpenApiMesseges.java
Labels: Area/Tooling, Component/ToolSwagger

#20241 Add default init function to object to hold fields
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BObjectType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BServiceType.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangObjectTypeNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  stdlib/bir-old/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir-old/src/main/ballerina/src/bir/type_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/src/bir/type_parser.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectInitializerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/ObjectProject/src/init/object-initializer.bal
Labels: Area/Language

#20586 Add wildcard CORS config tests
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/cors/HTTPCorsTest.java
  stdlib/http/src/test/resources/test-src/services/cors/cors-test.bal
Labels: Area/StandardLibs, Component/HTTP, Type/Bug

#20567 Fix NPE found with list constructor var ref
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor.bal
Labels: Area/Language

#20564 Fix NPE found with list constructor var ref
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor.bal
Labels: Area/Language

#20596 [gRPC] Refactor generated stub code
  stdlib/grpc/src/main/resources/templates/skeleton/stub.mustache
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/01_advanced_type_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/02_array_field_type_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/03_bidirectional_streaming_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/04_client_streaming_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/05_invalid_resource_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/06_server_streaming_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/07_unary_blocking_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/07_unary_nonblocking_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/08_unary_client_with_headers.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/09_grpc_secured_unary_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/10_grpc_ssl_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/11_grpc_byte_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/12_grpc_enum_test_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/13_unary_client_with_error_return.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/14_grpc_client_socket_timeout.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/15_grpc_oneof_field_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/16_unavailable_service_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/17_bidirectional_chat_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/18_grpc_optional_field_client.bal
Labels: Area/StandardLibs, Component/gRPC

#20591 Fix position calculation for chained invocations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibNegativeTest.java
  langlib/langlib-test/src/test/resources/test-src/langlib_test_negative.bal
  langlib/langlib-test/src/test/resources/testng.xml
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/BuiltinOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/StringFunctionInvocationExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableArrowExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
Labels: Area/Language

#20592 Fix position calculation for chained invocations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibNegativeTest.java
  langlib/langlib-test/src/test/resources/test-src/langlib_test_negative.bal
  langlib/langlib-test/src/test/resources/testng.xml
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/BuiltinOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/StringFunctionInvocationExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableArrowExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
Labels: Area/Language

#20611 Fix the variable name consistency
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
Labels: Area/StandardLibs, Component/JWT, Type/Improvement

#20605 Fix invalid sentence in Constants BBE
  examples/constants/constants.bal
Labels: Area/Language, Component/Examples, Type/Bug

#20600 Fix invalid sentence in Constants example in BBE
  examples/constants/constants.bal
Labels: Area/Language, Type/Improvement

#20606 Add wildcard CORS config tests
  stdlib/http/src/test/java/org/ballerinalang/stdlib/services/cors/HTTPCorsTest.java
  stdlib/http/src/test/resources/test-src/services/cors/cors-test.bal
Labels: Area/StandardLibs, Component/HTTP, Type/Bug

#20571 Fix concurrency issue in gRPC client streaming pattern(master)
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ClientCall.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/OutboundMessage.java
Labels: Area/StandardLibs

#20593 Update Travis Config
  .travis.yml
Labels: Area/Build, Type/Improvement

#20590 Update Travis Config
  .travis.yml
Labels: Area/Build, Type/Improvement

#20587 [ballerina-1.1.x] Fix HandleValue getting wrapped by another HandleValue in interop
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/interop/interop_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_desugar_phase.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal
Labels: Area/jBallerina

#20615 Improve BBE : Anonymous Record
  examples/anonymous-records/anonymous_records.bal
Labels: Area/Language, Component/Examples

#20628 Change protoc compiler download url to have secured connection(master)
  misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/BalGenerationConstants.java
  misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/utils/BalFileGenerationUtils.java
Labels: Area/StandardLibs, Component/gRPC

#20629 Change protoc compiler download url to have secured connection(1.1.x)
  misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/BalGenerationConstants.java
  misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/utils/BalFileGenerationUtils.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ClientCall.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/OutboundMessage.java
Labels: Area/StandardLibs, Component/gRPC

#20570 Fix concurrency issue in gRPC client streaming pattern(1.1.x)
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ClientCall.java
  stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/OutboundMessage.java
Labels: Area/StandardLibs

#20626 Fix copyDir test case bug
  stdlib/file/src/test/java/org/ballerinalang/stdlib/file/FileTest.java
Labels: Area/StandardLibs

#20603 Fix copyDir test case bug
  stdlib/file/src/test/java/org/ballerinalang/stdlib/file/FileTest.java
Labels: Area/StandardLibs

#20622 Fix the variable name consistency
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Component/OAuth2, Type/Improvement

#20621 Update docs of time related parameters
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_common.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/oauth2/src/main/ballerina/src/oauth2/outbound_oauth2_provider.bal
Labels: Area/StandardLibs, Type/Improvement

#20640 Change protoc compiler download url to have secured connection(1.0.x)
  misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/BalGenerationConstants.java
  misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/utils/BalFileGenerationUtils.java
Labels: Area/StandardLibs, Component/gRPC

#20625 Handling double slashes in the HTTP client and server
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpConstants.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpResource.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpService.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/actions/httpclient/HttpClientAction.java
  stdlib/http/src/main/java/org/ballerinalang/net/http/clientendpoint/CreateSimpleHttpClient.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/HttpBaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/HttpUrlTestCase.java
  tests/jballerina-integration-test/src/test/resources/http/src/httpservices/44_http_url.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs

#20620 Update docs of time related parameters
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_common.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
Labels: Area/StandardLibs, Type/Improvement

#20633 Update Travis Config
  .travis.yml
Labels: Area/Build, Type/Improvement

#20508 Move the changes in PR #20241 to 1.1.x
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BObjectType.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BServiceType.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangObjectTypeNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  stdlib/bir-old/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir-old/src/main/ballerina/src/bir/type_parser.bal
  stdlib/bir/src/main/ballerina/src/bir/bir_model.bal
  stdlib/bir/src/main/ballerina/src/bir/type_parser.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectInitializerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/ObjectProject/src/init/object-initializer.bal
Labels: Area/Language

#20555 Fix "Compiler extensions not working for custom annotations" in master
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/PackageCache.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSPackageCache.java
Labels: Area/Language

#20554 Fix "Compiler extensions not working for custom annotations"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/PackageCache.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSPackageCache.java
Labels: Area/Language, Component/Compiler, Component/CompilerExtensions

#20582 Fix metric name and label value escaping for prometheus
  misc/metrics-extensions/modules/ballerina-prometheus-extension/src/main/ballerina/src/prometheus/reporter.bal
Labels: Area/Observability, Component/Observability

#20583 Fix metric name and label value escaping for prometheus
  misc/metrics-extensions/modules/ballerina-prometheus-extension/src/main/ballerina/src/prometheus/reporter.bal
Labels: Area/Observability, Component/Observability

#20588 [master] Fix HandleValue getting wrapped by another HandleValue in interop
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/interop/interop_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_constants.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_desugar_phase.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal
Labels: Area/jBallerina

#20637 Refactor generated gRPC client stub code
  stdlib/grpc/src/main/resources/templates/skeleton/stub.mustache
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/01_advanced_type_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/02_array_field_type_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/03_bidirectional_streaming_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/04_client_streaming_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/05_invalid_resource_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/06_server_streaming_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/07_unary_blocking_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/07_unary_nonblocking_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/08_unary_client_with_headers.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/09_grpc_secured_unary_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/10_grpc_ssl_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/11_grpc_byte_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/12_grpc_enum_test_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/13_unary_client_with_error_return.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/14_grpc_client_socket_timeout.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/15_grpc_oneof_field_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/16_unavailable_service_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/17_bidirectional_chat_client.bal
  tests/jballerina-integration-test/src/test/resources/grpc/src/clients/18_grpc_optional_field_client.bal
Labels: Area/StandardLibs, Component/gRPC

#20665 Fix metrics tests (1.1.x)
  misc/metrics-extensions/modules/ballerina-prometheus-extension/src/main/ballerina/src/prometheus/reporter.bal
Labels: Area/Observability, Component/Observability

#20664 Fix metrics tests (master)
  misc/metrics-extensions/modules/ballerina-prometheus-extension/src/main/ballerina/src/prometheus/reporter.bal
Labels: Area/Observability, Component/Observability

#20657 [NATS-Streaming] Fix issue in acknowledging messages in auto-ack mode
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/Constants.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Attach.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/StreamingListener.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/message/Ack.java
Labels: Area/StandardLibs, Component/Messaging

#20658 [NATS-Streaming] Fix issue in acknowledging messages in auto-ack mode
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/Constants.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/Attach.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/consumer/StreamingListener.java
  stdlib/messaging/nats/src/main/java/org/ballerinalang/nats/streaming/message/Ack.java
Labels: Area/StandardLibs, Component/Messaging

#20201 Add code action API
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/BallerinaCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/BallerinaCodeActionProviderFactory.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/BallerinaCodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddAllDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ChangeAbstractTypeObjExecutorCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTestExecutorCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImportModuleExecutorCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/IncompatibleTypesCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/PullModeExecutorCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TaintedParamCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/VariableAssignmentCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/ExecuteCommandKeys.java
Labels: Area/Tooling

#20580 Review the Docker annotation BAL file
  stdlib/docker/src/main/ballerina/src/docker/annotation.bal
Labels: Type/Docs

#20597 Review the Docker annotation BAL File in 1.1.x Branch
  stdlib/docker/src/main/ballerina/src/docker/annotation.bal
Labels: Type/Docs

#20581 Add support reading array of values via config API
  bvm/ballerina-config/src/main/java/org/ballerinalang/config/ConfigRegistry.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation/annotationBodyCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinInvocationArgs10.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinInvocationArgs9.json
  stdlib/config-api/src/main/ballerina/src/config/config.bal
  stdlib/config-api/src/main/ballerina/src/config/natives.bal
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/GetConfig.java
  stdlib/config-api/src/test/java/org/ballerinalang/stdlib/config/ConfigRegistryTest.java
  stdlib/config-api/src/test/java/org/ballerinalang/stdlib/config/ConfigTest.java
  stdlib/config-api/src/test/resources/datafiles/default/ballerina.conf
  stdlib/config-api/src/test/resources/test-src/config.bal
Labels: Area/StandardLibs, Type/Improvement

#20601 Add support reading array of values via config API
  bvm/ballerina-config/src/main/java/org/ballerinalang/config/ConfigRegistry.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation/annotationBodyCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinInvocationArgs10.json
  language-server/modules/langserver-core/src/test/resources/completion/function/completionWithinInvocationArgs9.json
  stdlib/config-api/src/main/ballerina/src/config/config.bal
  stdlib/config-api/src/main/ballerina/src/config/natives.bal
  stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/GetConfig.java
  stdlib/config-api/src/test/java/org/ballerinalang/stdlib/config/ConfigRegistryTest.java
  stdlib/config-api/src/test/java/org/ballerinalang/stdlib/config/ConfigTest.java
  stdlib/config-api/src/test/resources/datafiles/default/ballerina.conf
  stdlib/config-api/src/test/resources/test-src/config.bal
Labels: Area/StandardLibs, Type/Improvement

#20541 Add observability (metrics and tracing) to Kafka connector
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaListenerImpl.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Assign.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Close.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Commit.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/CommitOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Connect.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetAssignment.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetAvailableTopics.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetBeginningOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetCommittedOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetEndOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetPausedPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetPositionOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetSubscription.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Pause.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Poll.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Resume.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Seek.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SeekToBeginning.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SeekToEnd.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Subscribe.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SubscribeToPattern.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SubscribeWithPartitionRebalance.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Unsubscribe.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Close.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/CommitConsumer.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/CommitConsumerOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/FlushRecords.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Init.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Send.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/observability/KafkaMetricsUtil.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/observability/KafkaObservabilityConstants.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/observability/KafkaObserverContext.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/observability/KafkaTracingUtil.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaConstants.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaUtils.java
Labels: Area/StandardLibs, Component/Messaging

#20649 Fix filepath:extension bug
  stdlib/filepath/src/main/ballerina/src/filepath/file_path.bal
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/nativeimpl/PathTest.java
Labels: Area/StandardLibs

#20651 Fix filepath:extension bug
  stdlib/filepath/src/main/ballerina/src/filepath/file_path.bal
  stdlib/filepath/src/test/java/org/ballerinalang/stdlib/filepath/nativeimpl/PathTest.java
Labels: Area/StandardLibs

#20652 Add default serialisers and deserialisers to Kafka module
  stdlib/messaging/kafka/src/main/ballerina/Ballerina.toml
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/commons.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/kafka_errors.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/producer.bal
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaListenerImpl.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaPollCycleFutureListener.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaRecordConsumer.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaServerConnectorImpl.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaTransactionContext.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Assign.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Close.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Commit.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/CommitOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Connect.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetAssignment.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetAvailableTopics.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetBeginningOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetCommittedOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetEndOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetPausedPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetPositionOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetSubscription.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Pause.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Poll.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Resume.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Seek.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SeekToBeginning.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SeekToEnd.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Subscribe.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SubscribeToPattern.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SubscribeWithPartitionRebalance.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Unsubscribe.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Close.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/CommitConsumer.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/CommitConsumerOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/FlushRecords.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Send.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/observability/KafkaMetricsUtil.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/service/Register.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaConstants.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaUtils.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/TransactionUtils.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/consumer/KafkaConsumerTopicsTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/services/KafkaServiceTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/ssl/KafkaConsumerAndProducerWithSSLTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/transactions/KafkaProducerTransactionsTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/utils/KafkaTestUtils.java
  stdlib/messaging/kafka/src/test/resources/test-src/services/kafka_service_advanced.bal
  stdlib/messaging/kafka/src/test/resources/test-src/ssl/kafka_ssl.bal
Labels: Area/StandardLibs, Component/Kafka, Type/NewFeature

#20624 Fix intermittent WebSocketMetricsTestCase failure
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java
Labels: Area/StandardLibs

#20182 Make string langlib compatible with StringValue
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BObject.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/interop/external_method_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_value_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/interop/external_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_cast_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_package_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_value_gen.bal
  gradle/birProject.gradle
  langlib/lang.error/src/main/java/org/ballerinalang/langlib/error/StackTrace.java
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/Length.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringValueBasicsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-value-test.bal
Labels: Area/jBallerina

#20655 Fix issue with including libraries in resources directory
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyNativeLibTask.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PathDependencyTestCase.java
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/.gitignore
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/src/toml4j/funcs.bal
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/src/toml4j/resources/libs/gson-2.8.1.jar
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/src/toml4j/resources/libs/toml4j-0.7.2.jar
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject2/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject2/src/baz/impl.bal
Labels: Area/BuildTools

#20700 Fix kafka issues in ballerina 1.1.x
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetAssignment.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetPausedPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetSubscription.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Poll.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SubscribeWithPartitionRebalance.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Send.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaUtils.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/consumer/KafkaConsumerTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/transactions/KafkaProducerTransactionsTest.java
Labels: Area/StandardLibs, Component/Kafka, Type/Bug, Type/Improvement

#20368 Add knative module to stdLib
  distribution/zip/jballerina/build.gradle
  gradle/balNativeLibProject.gradle
  gradle/javaLibsProject.gradle
  settings.gradle
  stdlib/knative/build.gradle
  stdlib/knative/src/main/ballerina/Ballerina.toml
  stdlib/knative/src/main/ballerina/src/knative/Module.md
  stdlib/knative/src/main/ballerina/src/knative/annotation.bal
Labels: Area/BuildTools, Type/NewFeature

#20683 Fix few bugs related to JWT - [1.1.x]
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/jwt/src/test/java/org.ballerinalang.stdlib.jwt/JwtIssuerAndValidatorTest.java
  stdlib/jwt/src/test/resources/test-src/jwt-issuer-and-validator-test.bal
Labels: Area/StandardLibs, Component/JWT, Type/Bug

#20645 Fix intermittent WebSocketMetricsTestCase failure
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java
Labels: Area/StandardLibs

#20697 Remove padding for base64 url encode - [1.1.x]
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Encode.java
  stdlib/encoding/src/test/java/org/ballerinalang/stdlib/encoding/Base64UrlEncodingTest.java
  stdlib/jwt/src/test/java/org.ballerinalang.stdlib.jwt/JwtAuthProviderTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnConfigPatternTest.java
Labels: Area/StandardLibs, Component/Encoding, Type/Bug

#20696 Fix few bugs related to JWT - [master]
  stdlib/jwt/src/main/ballerina/src/jwt/inbound_jwt_auth_provider.bal
  stdlib/jwt/src/main/ballerina/src/jwt/jwt_validator.bal
  stdlib/jwt/src/test/java/org.ballerinalang.stdlib.jwt/JwtIssuerAndValidatorTest.java
  stdlib/jwt/src/test/resources/test-src/jwt-issuer-and-validator-test.bal
Labels: Area/StandardLibs, Component/JWT, Type/Bug

#20708 Remove padding for base64 url encode - [master]
  stdlib/encoding/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Encode.java
  stdlib/encoding/src/test/java/org/ballerinalang/stdlib/encoding/Base64UrlEncodingTest.java
  stdlib/jwt/src/test/java/org.ballerinalang.stdlib.jwt/JwtAuthProviderTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/AuthnConfigPatternTest.java
Labels: Area/StandardLibs, Component/Encoding, Type/Bug

#20607 Implement cache for OAuth2 inbound authentication - [1.1.x]
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
Labels: Area/StandardLibs, Component/OAuth2, Type/Improvement

#20688 Implement cache for OAuth2 inbound authentication - [master]
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
Labels: Area/StandardLibs, Component/OAuth2, Type/Improvement

#20716 [master] Move record init function creation to Desugar
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
Labels: Area/Language

#20604 Fix incorrect array length when sliced
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Slice.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Area/Language

#20679 Fix several issues with type guards
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Area/Language

#20705 Improve bbe code formatting
  examples/object-methods/object_methods.bal
  examples/record-type-reference/record_type_reference.bal
Labels: Type/Docs

#20755 Fix typo in kafka module
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
Labels: Area/StandardLibs, Component/Kafka, Type/Docs

#20754 Fix a spelling mistake in kafka module
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
Labels: Area/StandardLibs, Component/Kafka, Type/Docs

#20627 Improve BBE : Anonymous Record
  examples/anonymous-records/anonymous_records.bal
Labels: Area/Language, Component/Examples

#20707 Add HTTP2 trailer support
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  gradle/repositories.gradle
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion4.json
  language-server/modules/langserver-core/src/test/resources/completion/function/chainCompletion5.json
  language-server/modules/langserver-core/src/test/resources/completion/function/errorLiftingSuggestions1.json
  language-server/modules/langserver-core/src/test/resources/completion/function/typeGuardSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/function/variableBoundItemSuggestions3.json
  language-server/modules/langserver-core/src/test/resources/completion/resource/completionBeforeUnderscore2.json
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/src/http/http_request.bal
  stdlib/http/src/main/ballerina/src/http/http_response.bal
  stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/src/mime/constants.bal
  stdlib/mime/src/main/ballerina/src/mime/natives.bal
  stdlib/mime/src/main/java/org/ballerinalang/mime/nativeimpl/EntityHeaders.java
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/MimeConstants.java
  stdlib/mime/src/test/java/org/ballerinalang/stdlib/mime/HeaderTest.java
  stdlib/mime/src/test/resources/test-src/header-test.bal
  stdlib/websub/src/main/ballerina/Ballerina.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2BaseTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http2/Http2TrailingHeadersTestCase.java
  tests/jballerina-integration-test/src/test/resources/http2/src/http2services/12_http_2.0_trailing_headers.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/HTTP, Component/HTTP2, Type/Improvement

#20695 Fix build and run commands with relative path
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/BuildCommand.java
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/RunCommand.java
  cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java
  cli/ballerina-packerina/src/test/resources/test-resources/valid-bal-file/relative/testBal/hello_world.bal
  cli/ballerina-packerina/src/test/resources/test-resources/valid-bal-file/relative/testDir/hello_world_test.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/SingleBalFileTestCase.java
  tests/jballerina-integration-test/src/test/resources/packaging/singleBalFile/relative/testBal/hello_world.bal
  tests/jballerina-integration-test/src/test/resources/packaging/singleBalFile/relative/testDir/hello_world_test.bal
Labels: Area/BuildTools

#20782 Fix issue with including libraries in resources directory
  cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyNativeLibTask.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PathDependencyTestCase.java
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/.gitignore
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/src/toml4j/funcs.bal
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/src/toml4j/resources/libs/gson-2.8.1.jar
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject1/src/toml4j/resources/libs/toml4j-0.7.2.jar
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject2/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/balopath/case9/TestProject2/src/baz/impl.bal
Labels: Area/BuildTools

#20709 Get generated keys only if supported by JDBC
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/datasource/SQLDatasource.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java
  stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java
Labels: Area/StandardLibs, Component/Data, Type/Bug

#20781 Migrate to BString for ErrorValue
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BError.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/api/BValueCreator.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_terminator_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_instruction_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_terminator_gen.bal
  gradle/birProject.gradle
  langlib/lang.error/src/main/java/org/ballerinalang/langlib/error/Reason.java
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/Length.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringValueBasicsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-value-test.bal
Labels: Area/jBallerina

#20698 Fix Kafka module styling issues and bring similar java methods to single classes
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/consumer.bal
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/producer.bal
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaListenerImpl.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaPollCycleFutureListener.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaRecordConsumer.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaServerConnectorImpl.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/impl/KafkaTransactionContext.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Assign.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/BrokerConnection.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Close.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Commit.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/CommitOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Connect.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/ConsumerInformationHandler.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetAssignment.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetAvailableTopics.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetBeginningOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetCommittedOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetEndOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetPausedPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetPositionOffset.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetSubscription.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Pause.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Poll.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Resume.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Seek.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SeekToBeginning.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SeekToEnd.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Subscribe.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SubscribeToPattern.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/SubscriptionHandler.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/consumer/Unsubscribe.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Close.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/CommitConsumer.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/CommitConsumerOffsets.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/FlushRecords.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/GetTopicPartitions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Init.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/ProducerActions.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/nativeimpl/producer/Send.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/observability/KafkaMetricsUtil.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaConstants.java
  stdlib/messaging/kafka/src/main/java/org/ballerinalang/messaging/kafka/utils/KafkaUtils.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/consumer/KafkaConsumerPauseResumeTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/consumer/KafkaConsumerTest.java
  stdlib/messaging/kafka/src/test/java/org/ballerinalang/messaging/kafka/transactions/KafkaProducerTransactionsTest.java
  stdlib/messaging/kafka/src/test/resources/testng.xml
Labels: Area/StandardLibs, Component/Kafka, Type/Improvement

#20659 Improve arrays:slice method to use `system.arraycopy` instead of adding values
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValueImpl.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Slice.java
Labels: Area/Language

#20779 Enable LS Workspace Symbol tests
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/WorkspaceTest.java
  language-server/modules/langserver-core/src/test/resources/workspace/workspaceSymbol.json
Labels: Area/Tooling, Component/LanguageServer, Type/Task

#20801 Enable Workspace Symbol tests
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/WorkspaceTest.java
  language-server/modules/langserver-core/src/test/resources/workspace/workspaceSymbol.json
Labels: Area/Tooling, Component/LanguageServer, Type/Task
