Repository ballerina-platform/ballerina-lang, pull requests merged in 2020-11, with the labels that each got.

#26691 Update performance test results for Ballerina v1.2.9
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Team/StandardLibs, Type/Task

#26698 Make TypeSymbol an extension of Symbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/AbstractTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/BallerinaTypeDescTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/types/TypeSymbol.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/impl/ErrorTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/impl/IgnoreReturnCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/impl/TypeGuardCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/VariableAssignmentRequiredCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/AnnotationUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/SymbolUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/completion/BLangRecordLiteralUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/FunctionCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/TypeCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ArrayTypeDescriptorNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BlockNodeContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ErrorTypeParamsNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FieldAccessContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ListenerDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#26680 Fix completion within annotation mapping
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ExplicitAnonymousFunctionExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FieldAccessContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionSignatureNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/AnnotationTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/ExpressionContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/new/annotation_ctx/config/functionAnnotation5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/annotation_ctx/config/functionAnnotation6.json
  language-server/modules/langserver-core/src/test/resources/completion/new/annotation_ctx/source/functionAnnotation5.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/annotation_ctx/source/functionAnnotation6.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/anon_func_expr_ctx_config5a.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/anon_func_expr_ctx_source5a.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/field_access_ctx_source7.bal
Labels: Area/LanguageServer

#26629 Fix spec conformity for error detail type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-iterable-object-negative.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/source/errorUnionSuggestion1.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/src/errors/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/distinct_error_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/distinct_error_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_destructure_binding_pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_operator_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/checked_expr_operator_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Team/CompilerFE

#26705 Enable debug test cases
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/CallStackDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/ControlFlowDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/LanguageConstructDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/build/MultiModuleBuildDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationNegativeTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/run/MultiModuleRunDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/run/SingleBalFileRunDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/test/MultiModuleTestDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/remote/BallerinaBuildRemoteDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/remote/BallerinaRunRemoteDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/remote/BallerinaTestRemoteDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/basic-project/src/hello-world/hello_world.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/basic-project/src/hello-world/tests/hello_world_test.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/breakpoint-tests/src/controlFlow/mainControlFlow.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/breakpoint-tests/src/foo/helloBal/hello.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/breakpoint-tests/src/foo/mainBal/main.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/breakpoint-tests/src/foo/tests/main_test.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/breakpoint-tests/src/languageConstruct/mainLangConstruct.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/breakpoint-tests/src/worker/mainWorker.bal
  tests/jballerina-debugger-integration-test/src/test/resources/single-file-tests/hello_world.bal
Labels: Component/Debugger, Team/DevTools

#26098 Add distinct type support to object type defn
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTypeIdSet.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/DistinctObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/klass/distinct-class-def.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/distinct_objects_negative.bal
Labels: Team/CompilerFE, Type/Improvement

#26673 Remove version parsing support from import declaration
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STImportDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STImportVersionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STTreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ImportDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ImportVersionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ImportDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_04.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_05.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_06.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_08.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_14.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_16.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_19.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_21.json
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/impl/OptimizeImportsCodeAction.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/assert/import_declaration_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/source/import_declaration_1.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/imports/ImportsTests.java
Labels: Area/Parser, Team/CompilerFE

#26754 Convert TypesFactory and SymbolFactory to per-context instances
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypesFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/AbstractTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaArrayTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFieldSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFutureTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMapTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaModule.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaNilTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaRecordTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaServiceSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSimpleTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSingletonTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaStreamTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTupleTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeDescTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSModuleCompiler.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSAnnotationCache.java
Labels: Area/SemanticAPI, Team/CompilerFE

#26703 Add support for Class symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypesFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaClassSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFieldSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaModule.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ClassSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/FieldSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ModuleSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/QNameReferenceUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/SymbolUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/FunctionCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BlockNodeContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ListenerDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModulePartNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RecordFieldWithDefaultValueNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RecordTypeDescriptorNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ReturnTypeDescriptorNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SortingUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source10.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source2.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source3.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source4.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source6.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source7.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source8.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/new_expr_ctx_source9.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/class_symbols_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/test-project/src/foo/type_defs.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#26773 Add let clause completion support
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/LetClauseNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/LetVariableDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_let_clause_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source10.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source11.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source2.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source3.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source4.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source6.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source7.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source8.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/query_expr_ctx_let_clause_source9.bal
Labels: Area/LanguageServer

#26795 Improve completion support within mapping constructor
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/mapping_expr_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/mapping_expr_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/mapping_expr_ctx_source14.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/mapping_expr_ctx_source15.bal
Labels: Area/LanguageServer

#26756 Fix incorrect public type creation issue for inferred record types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expressions_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#26812 Fix jballerina-unit-tests
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/constant/MapConstantEqualityInBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/functions/FunctionSignatureInBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/object/ObjectIncludeOverrideBaloTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/functions/test_different_function_signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/functions/test_different_function_signatures_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/object/object_override_includes.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/annotations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/class-definitions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/client_object.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/deprecation_annotation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/different_function_signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/global_arrays.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/global_function_pointers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/global_vars.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/map-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/bar/map-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/errors/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/readonly_objects/constructs.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/records/closed_record_type_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/records/common_models.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/records/immutability.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/records/open_record_type_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/records/rest_fields.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/returntypes/interop_funcs.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/selectively_immutable/constructs.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/subtyping/equi_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/modules/utils/utils.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/object_definitions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/object_type_inclusion_overrides.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/object_type_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project/simple-constant.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/ProjectAPI, Team/DevTools

#26660 Allow function-call-exprs with function parameters annotated with `@isolatedParam` in isolated functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
Labels: Team/CompilerFE

#26829 Fix the addition of multiple whitespaces through missing tokens
  compiler/ballerina-parser/src/test/resources/actions/commit-action/commit_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/commit-action/commit_action_source_02.bal
  compiler/ballerina-parser/src/test/resources/declarations/enum-decl/enum_decl_assert_07.json
  compiler/ballerina-parser/src/test/resources/declarations/enum-decl/enum_decl_source_07.bal
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_12.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_12.bal
  compiler/ballerina-parser/src/test/resources/expressions/check-expr/check_expr_assert_04.json
  compiler/ballerina-parser/src/test/resources/expressions/check-expr/check_expr_source_04.bal
  compiler/ballerina-parser/src/test/resources/expressions/transactional-expr/transactional_expr_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/transactional-expr/transactional_expr_source_02.bal
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_28.json
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_source_28.bal
  compiler/ballerina-parser/src/test/resources/statements/if-else/if_else_assert_07.json
  compiler/ballerina-parser/src/test/resources/statements/if-else/if_else_source_07.bal
  compiler/ballerina-parser/src/test/resources/statements/xmlns-decl-stmt/xmlns_decl_stmt_assert_03.json
  compiler/ballerina-parser/src/test/resources/statements/xmlns-decl-stmt/xmlns_decl_stmt_source_03.bal
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingEnv.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  misc/formatter/modules/formatter-core/src/test/resources/expressions/query/assert/query_expression_4.bal
Labels: Component/Formatting, Team/Tooling, Type/Improvement

#26810 Fix 'testDocNativeFunction' in 'MarkdownDocumentationTest'
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_native_function.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Component/ProjectAPI, Team/DevTools

#26805 Implement API for getting the lang lib functions allowed by method call expr
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/Qualifiers.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/AbstractTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaClassSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/TypeDescKind.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/TypeSymbol.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/VariableAssignmentRequiredCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FieldAccessContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config7.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/langlib_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#26834 Add api to check two types are same at runtime
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java
Labels: Team/jBallerina

#26268 Remove transaction internal module and add desugar changes for transactional services
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionLocalContext.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/PackageID.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BLangCompilerConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/TransactionDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  langlib/lang.transaction/src/main/ballerina/src/lang.transaction/constants.bal
  langlib/lang.transaction/src/main/ballerina/src/lang.transaction/internal.bal
  langlib/lang.transaction/src/main/ballerina/src/lang.transaction/transaction_errors.bal
  langlib/lang.transaction/src/main/java/org/ballerinalang/langlib/transaction/AbortResourceManagers.java
  langlib/lang.transaction/src/main/java/org/ballerinalang/langlib/transaction/CommitResourceManagers.java
  langlib/lang.transaction/src/main/java/org/ballerinalang/langlib/transaction/CurrentTime.java
  langlib/lang.transaction/src/main/java/org/ballerinalang/langlib/transaction/GetAvailablePort.java
  langlib/lang.transaction/src/main/java/org/ballerinalang/langlib/transaction/PrepareResourceManagers.java
  langlib/lang.transaction/src/main/java/org/ballerinalang/langlib/transaction/RollbackTransaction.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/TransactionalResourceFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/NestedRetryTransactionStmtsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/NestedTransactionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/RetryTransactionBlockStmtOutcomesTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/RetryTransactionStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/SetRollbackOnlyTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/TransactionOnFailTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/TransactionStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/TransactionalWorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/nested_retry_transaction_stmts.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/nested_transaction_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/retry_transaction_block_stmt_outcomes.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/retry_transaction_stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transaction_handlers_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transaction_on_fail.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transaction_on_fail_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transaction_stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transaction_stmt_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transaction_with_setrollbackonly_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transaction_with_setrollbackonly_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/transaction/transactional_worker.bal
  tests/jballerina-unit-test/src/test/resources/testng-jballerina.xml
  tests/jballerina-unit-test/src/test/resources/testng-new-parser.xml
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#26847 Update performance test results for Ballerina v1.2.10
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Team/StandardLibs, Type/Task

#26871 Remove stored resources support and fix resource func qualifiers
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ServiceDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_11.json
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_source_11.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_05.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_14.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_15.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_05.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_10.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_14.bal
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_15.bal
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object_constructor_assert_09.json
Labels: Team/CompilerFE

#26897 Remove unused/unnecessary fields in worker related nodes
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/statements/WorkerReceiveNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/statements/WorkerSendNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerReceive.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangWorkerSend.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
Labels: Team/CompilerFE

#26908 Fix initialising token updater for every cli command
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PullCommand.java
Labels: Component/ProjectAPI, Team/DevTools

#26920 Disable central client tests to fix hanging issue
  cli/central-client/src/test/resources/testng.xml
Labels: Component/ProjectAPI, Team/DevTools

#26878 Improve error handling in environment loading and Ballerina.toml reading sections
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunExecutableTask.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/RunCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/TestCommandTest.java
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ProjectException.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/balo/BaloFiles.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/balo/BaloProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/SingleFileProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/EnvironmentBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BallerinaTomlProcessor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BaloFiles.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/DocumentData.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ModuleData.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageConfigCreator.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageData.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ProjectFiles.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/BallerinaDistribution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/repos/BallerinaDistributionRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/testsuite/TesterinaRegistry.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBallerinaTomlProcessor.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestSingleFileProject.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestTarget.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
Labels: Component/ProjectAPI

#26950 Fix bir-cache loading issue for single-file-proj
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/repos/TempDirCompilationCache.java
Labels: Area/LanguageServer, Team/jBallerina, Type/Bug

#26930 Mark relevant stream/query lang lib methods and `StreamImplementor` methods as `isolated`
  bvm/ballerina-runtime/src/main/java/module-info.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BLangCompilerConstants.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  docs/bir-spec/src/test/resources/test-src/types_and_operations.bal
  docs/bir-spec/src/test/resources/test-src/values.bal
  langlib/lang.__internal/src/main/ballerina/src/lang.__internal/stream-utils.bal
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/InvokeAsExternal.java
  langlib/lang.query/src/main/ballerina/src/lang.query/types.bal
  langlib/lang.stream/src/main/ballerina/src/lang.stream/internal.bal
  langlib/lang.stream/src/main/ballerina/src/lang.stream/stream.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStreamTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-iterable-object-negative.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-iterable-objects.bal
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
  langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal
  langlib/langlib-test/src/test/resources/test-src/tablelib_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal
  misc/formatter/modules/formatter-core/src/test/resources/expressions/range/assert/range_expression_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/expressions/range/source/range_expression_2.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/basic-project/src/advanced/main.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-exp-iterable-objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Language/Streams

#26949 Temporary tackle module-var-decl CCEs
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
Labels: Team/CompilerFE

#26966 Update Semantic API test cases with the Project API changes
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleCompilationState.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/ProjectLoader.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/CompilerPhaseRunner.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DiagnosticsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/WorkspaceSymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/util/SemanticAPITestUtils.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
Labels: Component/ProjectAPI

#26688 Allow dependently-typed object method declarations and fix subtyping
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ParameterizedType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BParameterizedType.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BParameterizedType.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  docs/bir-spec/src/test/resources/test-src/types_and_operations.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/VariableReturnType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/VariableReturnTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/variable_return_type_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/variable_return_type_test.bal
Labels: Team/CompilerFE

#26725 Support API to get current module from runtime
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Environment.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/InstanceMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/InstanceMethodTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/StaticMethodTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/instance_method_tests.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/object_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
Labels: Team/jBallerina

#26981 Fix NPE issue when looking up undefined constructs
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_undefined_constructs_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#26974 Fix parser crashes for incomplete function-type in tuple-type
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_assert_04.json
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_source_04.bal
Labels: Area/Parser, Team/CompilerFE

#27006 Refactor package resolution
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DependencyGraph.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBaloWriter.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JarResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Module.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Package.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageConfig.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageManifest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageCache.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageLoadRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BallerinaTomlProcessor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BaloFiles.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageConfigCreator.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ProjectFiles.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/EnvironmentPackageCache.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/LangLibResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/ProjectPackageCache.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/model/PackageJson.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/repos/FileSystemCache.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSPackageLoader.java
  misc/lib-creator/src/main/java/org/ballerinalang/stdlib/utils/BuildLangLib.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBallerinaTomlProcessor.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestFileSystemRepository.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/CompileResult.java
Labels: Component/ProjectAPI

#27025 Improvements to LS diagnostics, hover and import statement suggestions
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/AbstractTypeSymbol.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/HoverContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/ContextConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/CompletionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/ContextBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/HoverContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/CompletionTestNew.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/ImportDeclarationTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/diagnostics/DiagnosticsTest.java
  language-server/modules/langserver-core/src/test/resources/completion/new/function_def/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/function_def/config/config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/config/config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/config/config5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/config/config7.json
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/source7.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/listener_decl/config/config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/module_part_context/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/module_var_context/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/module_var_context/config/config4.json
  language-server/modules/langserver-core/src/test/resources/diagnostics/configs/project_diagnostics1.json
  language-server/modules/langserver-core/src/test/resources/diagnostics/configs/single_file_diagnostics1.json
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/diag_project/.gitignore
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/diag_project/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/diag_project/Package.md
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/diag_project/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/diag_project/modules/module1/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/diag_project/modules/module2/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/diag_project/modules/module3/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/single_source.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Area/LanguageServer

#26959 Fix annotation declaration parsing with "const"
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/AnnotationDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/declarations/annot-decl/annot_decl_assert_11.json
  compiler/ballerina-parser/src/test/resources/declarations/annot-decl/annot_decl_source_11.bal
Labels: Team/CompilerFE

#26880 Fix diagnostics for module-no-init-var-decl with isolated
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ModuleVarDeclTest.java
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_12.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_12.bal
Labels: Team/CompilerFE

#26727 Fix isolation flag for bound methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis_semantic_negative.bal
Labels: Team/CompilerFE

#27023 Fix semantic API tests
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#26970 Add 'code' and 'messageTemplate' to the DiagnosticInfo
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticWarningCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropValidator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JInterop.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JInteropException.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethod.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnostic.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLog.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/cyclefind/GlobalVariableRefAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/TaintRecord.java
  compiler/ballerina-lang/src/test/java/org/ballerinalang/util/DiagnosticCodeTest.java
  compiler/ballerina-lang/src/test/resources/testng.xml
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticMessageHelper.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticWarningCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/SyntaxDiagnostic.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeDiagnostic.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/diagnostics/DiagnosticCodeTest.java
  compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/diagnostics/DiagnosticCode.java
  misc/lib-creator/src/main/java/org/ballerinalang/stdlib/utils/GenerateBalo.java
  misc/toml-parser/src/main/java/io/ballerina/toml/internal/diagnostics/DiagnosticErrorCode.java
  misc/toml-parser/src/main/java/io/ballerina/toml/semantic/diagnostics/DiagnosticLog.java
  misc/toml-parser/src/test/java/toml/parser/test/diagnostics/DiagnosticCodeTest.java
Labels: Area/DiagnosticAPI, Team/CompilerFE

#26828 Add support for isolated variables
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedVariableTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables_semantic_negative.bal
Labels: Team/CompilerFE

#27003 Fix position of AST node for start action
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expressions_test.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/tracing/ConcurrencyTestCase.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/SelectivelyImmutableTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
Labels: Team/CompilerFE, Type/Bug

#27058 Fix an issue related to transitive dependencies
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
Labels: Component/ProjectAPI

#27062 Fix raw template symbol flag being updated
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/CompilerFE

#27045 Fix zero-based error line and column numbers printing when compiling
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CompileTask.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java
Labels: Area/DiagnosticAPI, Team/CompilerFE

#27005 Add an API to get type inclusions of record/object types
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaClassSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaRecordTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/RecordTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BStructureType.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#27067 Fix langserver test failure
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaAnnotationSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaClassSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaConstantSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMethodSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeDefinitionSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaVariableSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/Qualifiable.java
Labels: Area/LanguageServer, Team/Tooling, Type/Task

#27055 Add an API to check type compatibility in type symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/AbstractTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaClassSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/TypeSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypeAssignabilityTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type_assignability_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#27071 Rename getType() -> type()
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#26996 Fix error-arg-list-BP recovery issues
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ModuleVarDeclTest.java
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_13.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_13.bal
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_17.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_18.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_19.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_assert_03.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_source_03.bal
Labels: Area/Parser, Team/CompilerFE

#27076 Add import auto-completion support for new project structure
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/DocumentServiceContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetBlock.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/ImportsAcceptor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/AnnotationUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/completion/BLangRecordLiteralUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AnnotationAccessExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AnnotationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ArrayTypeDescriptorNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BlockNodeContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ErrorTypeParamsNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ExplicitNewExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FieldAccessContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FlushActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/IfElseStatementNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImplicitNewExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ListenerDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ObjectConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/OnFailClauseNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/PanicStatementNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ReceiveActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RecordFieldWithDefaultValueNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RightArrowActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ServiceDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/SyncSendActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/WaitActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/WaitFieldsListNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/WhileStatementNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/CompletionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SortingUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/AbstractDocumentServiceContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/config/config10.json
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/config/config8.json
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/config/config9.json
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/lsproject/.gitignore
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/lsproject/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/lsproject/Package.md
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/lsproject/main.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/lsproject/modules/module1/source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/lsproject/modules/module1/source2.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/lsproject/modules/module1/source3.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/lsproject/modules/module2/main.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/import_decl/source/lsproject/modules/module3/main.bal
Labels: Area/LanguageServer

#27052 Add test case for looking up constant refs
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#27085 Fix import issue with current project modules
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
Labels: Area/LanguageServer

#26826 Add support for configurable
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/Flag.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/Flags.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/LexerTerminals.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STRequiredExpressionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STTreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/RequiredExpressionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ModuleVarDeclTest.java
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_14.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_15.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_14.bal
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_15.bal
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  langlib/lang.__internal/src/main/ballerina/configurable.bal
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/Configurable.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_global_var_decl_negative.bal
Labels: Team/CompilerFE

#27089 Consider the flags for function shapes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BInvokableType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
Labels: Area/BIR, Priority/Blocker, Team/jBallerina

#26764 Add test cases for Range Formatting
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatter.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/misc/RangesTest.java
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/assert/ranges_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/assert/ranges_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/assert/ranges_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/assert/ranges_4.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/assert/ranges_5.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/source/ranges_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/source/ranges_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/source/ranges_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/source/ranges_4.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/source/ranges_5.bal
Labels: Component/Formatting, Team/Tooling

#27011 Add support for implicit and explicit isolated object constructor expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/object/ObjectConstructorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_expression.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_expression_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_semantic_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
Labels: Team/CompilerFE

#27073 Fix decimal to anydata cast error when using cloneWithType
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionWithStampTypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal
Labels: Team/CompilerFE

#26992 Set detail map as immutable
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ErrorCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/JsonUtils.java
Labels: Team/CompilerFE

#27107 Deprecate ls-compiler and doc-manager
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/CompileFileContextOperation.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/ExtendedLSCompiler.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompilerCache.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompilerOperationContext.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompilerUtil.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSContextManager.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSModuleCompiler.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/exception/CompilationFailedException.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/ExtendedWorkspaceDocumentManagerImpl.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocument.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocumentManagerImpl.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/repository/LSInMemorySourceEntry.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/repository/LSPathConverter.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/repository/LangServerFSProgramDirectory.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/repository/LangServerFSProjectDirectory.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/repository/WorkspacePackageRepository.java
Labels: Area/LanguageServer, Team/Tooling, Type/Task

#27113 Improve package resolver to integrate with central repository
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/EnvironmentBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
Labels: Component/ProjectAPI

#27125 Update package resolution algorithm
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BaloWriter.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DocumentContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Package.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ModuleLoadRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ResolutionRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSPackageLoader.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_cache/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_cache/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_cache/modules/mod_c1/mod1.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_cache/modules/mod_c1/tests/tests1.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_cache/modules/mod_c2/mod2.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_cache/tests/main_tests.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_http/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_http/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_http/modules/mod_c1/mod1.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_http/modules/mod_c1/tests/tests1.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_http/modules/mod_c2/mod2.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_http/tests/main_tests.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_io_1_4_2/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_io_1_4_2/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_io_1_5_0/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_io_1_5_0/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_jsonutils/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_jsonutils/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_runtime/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/ultimate_package_resolution/package_runtime/main.bal
Labels: Component/ProjectAPI

#27082 Refactor Central Client and Central related commands
  cli/ballerina-cli/build.gradle
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PullCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/SearchCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/BrowserLauncher.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/CentralUtils.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/TokenUpdater.java
  cli/ballerina-cli/src/main/java/module-info.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/PullCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/PushCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/SearchCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/utils/TestCentralUtils.java
  cli/ballerina-cli/src/test/resources/test-resources/central-utils/Settings.toml
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-pull.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-push.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-search.help
  cli/central-client/build.gradle
  cli/central-client/src/main/java/module-info.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/BrowserLauncher.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/CentralClientConstants.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/exceptions/CentralClientException.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/exceptions/NoPackageException.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/exceptions/PackageAlreadyExistsException.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/exceptions/UnauthorizedException.java
  cli/central-client/src/test/java/org/ballerinalang/central/client/TestCentralApiClient.java
  cli/central-client/src/test/java/org/ballerinalang/central/client/TestUtils.java
  compiler/ballerina-lang/build.gradle
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectConstants.java
  compiler/ballerina-lang/src/main/java/module-info.java
Labels: Component/ProjectAPI, Team/DevTools

#27116 Fix Bindgen tool with Project API and other changes
  distribution/zip/jballerina-tools/build.gradle
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindingsGenerator.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenMvnResolver.java
  misc/ballerina-bindgen/src/main/resources/templates/bridge_class.mustache
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/Ballerina.toml
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/Ballerina.toml
Labels: Component/Bindgen, Team/DevTools

#27128 Add BallerinaUserHome and RemotePackageRepository
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PullCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/SearchCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/CentralUtils.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/utils/TestCentralUtils.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/EnvironmentBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/BallerinaUserHome.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/RemotePackageRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/RepoUtils.java
Labels: Component/ProjectAPI, Team/DevTools

#27140 Add Central prod URL to Repo Utils
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/RepoUtils.java
Labels: Component/ProjectAPI, Team/DevTools

#27154 Fix a null pointer exception when updating the Ballerina.toml
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenMvnResolver.java
Labels: Component/Bindgen, Team/DevTools, Type/Bug

#27164 Remove entry point validation from Ballerina commands
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunExecutableTask.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/RunCommandTest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/EnvironmentBuilder.java
Labels: Component/ProjectAPI

#27160 Show invalid token error & Fix token updater issue in Push Command
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/CentralUtils.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/exceptions/UnauthorizedException.java
  cli/central-client/src/test/java/org/ballerinalang/central/client/TestCentralApiClient.java
Labels: Component/ProjectAPI, Team/DevTools

#27174 Add build options and fix source symbol filtering in semantic model
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaModule.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer

#27184 Fix concurrent compilation issue in langserver
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer, Priority/Blocker, Team/Tooling, Type/Bug

#27188 Fix getPackage in RemoteRepository
  cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java
  cli/central-client/src/test/java/org/ballerinalang/central/client/TestUtils.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/RemotePackageRepository.java
Labels: Component/ProjectAPI, Team/DevTools

#27202 Change user home balo-cache to balo
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PullCommand.java
Labels: Component/ProjectAPI, Team/DevTools

#27217 Add package other properties to package.json of balo
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BaloWriter.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BallerinaTomlProcessor.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBaloWriter.java
Labels: Component/ProjectAPI, Team/DevTools

#27208 Add first get local versions in remote repo 'getPackageVersions'
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/RemotePackageRepository.java
Labels: Component/ProjectAPI, Team/DevTools

#27218 Disable the optimize import code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/OptimizeImportsCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/OptimizeImportsTest.java
Labels: Area/LanguageServer

#27228 Fix resolving java11 balos in file system repo
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/FileSystemRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/FileSystemRepositoryTests.java
  compiler/ballerina-lang/src/test/resources/test-repo/balo/hevayo/package_a/0.1.2/hevayo-package_a-any-0.1.2.balo
  compiler/ballerina-lang/src/test/resources/test-repo/balo/hevayo/package_a/0.1.5/hevayo-package_a-any-0.1.5.balo
  compiler/ballerina-lang/src/test/resources/test-repo/balo/hevayo/package_b/0.2.0/hevayo-package_b-any-0.2.0.balo
  compiler/ballerina-lang/src/test/resources/test-repo/balo/hevayo/package_c/0.2.0/hevayo-package_c-java11-0.2.0.balo
Labels: Component/ProjectAPI, Priority/Blocker

#27168 Refactor BIRVarToJVMIndexMap
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmErrorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/BIRVarToJVMIndexMap.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ModuleStopMethodGen.java
Labels: Team/jBallerina
