Repository ballerina-platform/ballerina-lang, pull requests merged in 2020-12, with the labels that each got.

#27257 Fix central prod url
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/RepoUtils.java
Labels: Component/ProjectAPI, Team/DevTools

#27240 Fix diagnostics duplication and perf issue
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/OptimizeImportsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer, Team/Tooling, Type/Bug

#27248 Fix benchmark tests module and add test snippets for loop benchmarks
  langlib/lang.query/src/main/ballerina/types.bal
  tests/jballerina-benchmark-test/benchmarkFunctions.txt
  tests/jballerina-benchmark-test/build.gradle
  tests/jballerina-benchmark-test/src/main/ballerina/benchmark-loops.bal
  tests/jballerina-benchmark-test/src/main/ballerina/register-functions.bal
Labels: Lang/Type/Streams, Team/CompilerFE

#27287 Add support for the new service design
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BaseVisitor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaModule.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaServiceSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeDefinitionSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ModuleSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/Qualifier.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ServiceSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/SymbolKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/SymbolUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/completion/QNameReferenceUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BlockNodeContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ErrorTypeParamsNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ListenerDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModulePartNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RecordTypeDescriptorNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SortingUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ServiceSemanticAPITest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInServiceDeclTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/service_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_flag_to_qualifier_mapping_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#27325 Consider service constructor expression as a service attach point
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentPointTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annots_with_invalid_consts.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annots_with_list_consts.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/var_name_field.bal
Labels: Team/CompilerFE, Type/SpecDeviation

#27265 Restructure debugger test utils
  tests/jballerina-debugger-integration-test/build.gradle
  tests/jballerina-debugger-integration-test/spotbugs-exclude.xml
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/BallerinaTestDebugPoint.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/DebugHitListener.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/DebugServerEventHolder.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/DebugTestRunner.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/DebugUtils.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/FileUtils.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/client/DAPClient.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/client/DAPRequestManager.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/client/TestDAPClientConnector.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/client/connection/TestProcessStreamConnectionProvider.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/client/connection/TestSocketStreamConnectionProvider.java
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/client/connection/TestStreamConnectionProvider.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/BaseTestCase.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/CallStackDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/ControlFlowDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/LanguageConstructDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/ModuleBreakpointTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/ServiceDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/build/MultiModuleBuildDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationBaseTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationNegativeTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/run/MultiModuleRunDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/run/SingleBalFileRunDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/test/MultiModuleTestDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/remote/BallerinaBuildRemoteDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/remote/BallerinaRunRemoteDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/remote/BallerinaTestRemoteDebugTest.java
Labels: Component/Debugger, Team/DevTools

#27388 Fix call expr capturing issue in expr statements
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expressions_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#27342 Remove listeners() API from the module symbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaModule.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ModuleSymbol.java
Labels: Area/SemanticAPI, Team/CompilerFE

#27376 Move rest-binding-pattern to SeparatedNodeList in syntax API
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STFieldBindingPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STListBindingPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STMappingBindingPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STTreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/FieldBindingPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ListBindingPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/MappingBindingPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_04.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_01.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_03.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_04.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_07.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_08.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_09.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_14.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_15.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_16.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_17.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_18.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_19.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/list_binding_pattern_assert_01.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/list_binding_pattern_assert_02.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/mapping_binding_pattern_assert_01.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_10.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_12.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_14.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_15.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_18.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_19.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_20.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_21.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_23.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_05.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_07.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_08.json
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
Labels: Area/Parser, Team/CompilerFE

#27397 Parameterize resource paths
  tests/jballerina-debugger-integration-test/src/main/java/org/ballerinalang/debugger/test/utils/DebugTestRunner.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/BaseTestCase.java
Labels: Component/Debugger, Team/DevTools, Type/Improvement

#27347 Add missing annotation support for service objects and improve listener
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/AnnotationUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BObjectType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BServiceType.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/Flag.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/Flags.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/servicetests/ServiceValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ServiceDeclTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/var_name_field.bal
  tests/jballerina-unit-test/src/test/resources/test-src/klass/simple_service_class.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/abstract-object-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_negative.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE, Type/Bug

#27422 Cache bir and thin jar in the distribution cache location for tests
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/DeprecatedAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/ErrorsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/FieldLevelDocsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MultilineDocsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/ObjectFieldDefaultValueTest.java
Labels: Component/ProjectAPI, Team/DevTools

#26882 Add support for included record parameters
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/Flag.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/Flags.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STRequiredParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STTreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/RequiredParameterNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/FunctionParamsTest.java
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_09.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_10.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_11.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_12.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_13.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_14.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_09.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_10.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_11.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_12.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_13.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_14.bal
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionWithIncludedRecordParam.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal
Labels: Team/CompilerFE

#27345 Handle union of streams with type params
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
Labels: Lang/Type/Streams, Team/CompilerFE

#27433 Use log output files & enable windows ballerina CLI tests
  .github/workflows/CI_windows.yml
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/FileUtils.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/CommandOutputUtils.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/PushCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/RunCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/TestCommandTest.java
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-bal-project-override-build-options.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-bal-project-with-tests.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-bal-project.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-bal-with-absolute-jar-path.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-bar-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-foo-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-hello-world-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-multi-module-project-winery-storage.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-multi-module-project-winery.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-project-default-build-options.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-syntax-err-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/run-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/test-project.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-bal-project-override-build-options.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-bal-project-with-tests.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-bal-project.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-bal-with-absolute-jar-path.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-bar-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-foo-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-hello-world-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-multi-module-project-winery-storage.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-multi-module-project-winery.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-project-default-build-options.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-syntax-err-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/run-bal.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/test-project.txt
Labels: Component/ProjectAPI, Team/DevTools

#27438 Fix annotation entry ordering with service constructors
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
Labels: Team/CompilerFE

#27392 Support pre-release versions in Ballerina packages
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/SemanticVersion.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BallerinaTomlProcessor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/SemanticVersionComparisonTests.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/SemanticVersionTests.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBallerinaTomlProcessor.java
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_l_with_stable_dep/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_l_with_stable_dep/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_l_with_unstable_dep/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_l_with_unstable_dep/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_m_with_unstable_dep/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_m_with_unstable_dep/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_GA/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_GA/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_GA/modules/mod_k1/mod1.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_GA/modules/mod_k2/mod2.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_alpha/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_alpha/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_alpha/modules/mod_k1/mod1.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_alpha/modules/mod_k2/mod2.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_beta/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_beta/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_beta/modules/mod_k1/mod1.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_unstable_k_beta/modules/mod_k2/mod2.bal
Labels: Component/ProjectAPI

#27440 Add a test for service constructor re-ordering for annotations
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java
  tests/testerina-integration-test/src/test/resources/project-based-tests/annotation-access/tests/main_test.bal
Labels: Team/CompilerFE

#27454 Disable windows cli tests
  .github/workflows/CI_windows.yml
Labels: Component/ProjectAPI, Team/DevTools

#27460 Fix included record parameter issue with non-basic types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionWithIncludedRecordParam.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal
Labels: Team/CompilerFE

#27394 Use PackageID in all places
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/PackageID.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/BIRFunctionWrapper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JFieldFunctionWrapper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodFunctionWrapper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JavaMethodCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/OldStyleExternalFunctionWrapper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/FrameClassGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/InitMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/LambdaGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ModuleStopMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRWriterUtils.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BFileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
Labels: Team/jBallerina

#27497 Add goto definition support in language server
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/definition/DefinitionUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/definition/DefinitionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/definition/StandardLibraryDefinitionTest.java
  language-server/modules/langserver-core/src/test/resources/definition/expected/project/defProject1.json
  language-server/modules/langserver-core/src/test/resources/definition/expected/project/defProject2.json
  language-server/modules/langserver-core/src/test/resources/definition/expected/project/defProject3.json
  language-server/modules/langserver-core/src/test/resources/definition/expected/project/defProject4.json
  language-server/modules/langserver-core/src/test/resources/definition/expected/project/defProject5.json
  language-server/modules/langserver-core/src/test/resources/definition/expected/project/defProject6.json
  language-server/modules/langserver-core/src/test/resources/definition/sources/projectls/.gitignore
  language-server/modules/langserver-core/src/test/resources/definition/sources/projectls/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/definition/sources/projectls/defmodsource1.bal
  language-server/modules/langserver-core/src/test/resources/definition/sources/projectls/defmodsource2.bal
  language-server/modules/langserver-core/src/test/resources/definition/sources/projectls/modules/lsmod1/lsmod1.bal
  language-server/modules/langserver-core/src/test/resources/definition/sources/projectls/modules/lsmod1/source1.bal
  language-server/modules/langserver-core/src/test/resources/definition/sources/projectls/modules/lsmod2/lsmod2.bal
  language-server/modules/langserver-core/src/test/resources/definition/sources/projectls/modules/lsmod3/lsmod3.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Area/LanguageServer

#27328 Fix empty metadata node creation when top-level recovery is a KEEP
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_10.json
  compiler/ballerina-parser/src/test/resources/misc/resiliency/resiliency_assert_03.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_22.json
  compiler/ballerina-parser/src/test/resources/types/singleton-type/singleton_type_assert_07.json
Labels: Team/CompilerFE

#27512 Create a class symbol for class generated for raw templates
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/CompilerFE

#27467 Export identifier encoder class to APIs
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/IdentifierUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java
  cli/ballerina-tool/src/main/java/org/ballerinalang/tool/util/BFileUtil.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JarResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/FieldNameHashComparator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/InitMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/LambdaGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/SuspendedContext.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/IdentifierModifier.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/utils/PackageUtils.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/BCompoundVariable.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/BSimpleVariable.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TesterinaFunction.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BFileUtil.java
Labels: Team/jBallerina

#27511 Fix testerina functions getting stuck due to dynamic listeners
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TesterinaFunction.java
Labels: Team/jBallerina

#27452 Improve --tests flag to support wildcards and module wise execution
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/ModuleExecutionTest.java
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-tests/.gitignore
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-tests/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-tests/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-tests/modules/Module1/Module1.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-tests/modules/Module1/tests/Module1_test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-tests/tests/main_test.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Component/Testerina, Team/TestFramework, Type/Improvement

#27514 Enable tests which were disabled with service change
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ClassDefContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ExpressionContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/signature/ExpressionsTest.java
  language-server/modules/langserver-core/src/test/resources/completion/new/class_def/config/config10.json
  language-server/modules/langserver-core/src/test/resources/completion/new/class_def/config/config11.json
  language-server/modules/langserver-core/src/test/resources/completion/new/class_def/config/config9.json
  language-server/modules/langserver-core/src/test/resources/completion/new/class_def/source/source10.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/class_def/source/source9.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/object_constructor_expr_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/object_constructor_expr_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/object_constructor_expr_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/object_constructor_expr_ctx_source12.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/object_constructor_expr_ctx_source13.bal
  language-server/modules/langserver-core/src/test/resources/signature/expressions/expressions.bal
Labels: Area/LanguageServer

#27290 Make ListenerDeclarationNode's type optional in syntax API
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ListenerDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_01.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_01.bal
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImplicitNewExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ListenerDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SortingUtil.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
Labels: Team/CompilerFE

#27537 Update performance test results for Ballerina Swan Lake Preview 7
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Team/StandardLibs, Type/Task

#27509 Remove unnecessary check for intersection type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
Labels: Team/CompilerFE

#27552 Fix service template cli
  cli/ballerina-cli/src/main/resources/create_cmd_templates/service/service.bal
Labels: Priority/Blocker, Team/DevTools

#27559 Add utility to workspace manager to get relative file path
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TypeGuardCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/AbstractDocumentServiceContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/definition/DefinitionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer

#27561 Change 'validatePackageVersion' to use semver library
  cli/central-client/build.gradle
  cli/central-client/src/main/java/module-info.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/CentralClientConstants.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java
  cli/central-client/src/test/java/org/ballerinalang/central/client/TestUtils.java
Labels: Component/ProjectAPI, Team/DevTools

#27568 Fix dependency resolution that fails when loading a BaloProject
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java
Labels: Component/ProjectAPI

#27576 Fix Object methods relelated debug issues
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java
Labels: Component/Debugger, Team/DevTools, Type/Bug

#27597 Fix a formatting issue and enable some disabled test cases
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_11.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_11.bal
  compiler/ballerina-parser/src/test/resources/expressions/anon-func/anon_func_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/anon-func/anon_func_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/anon-func/anon_func_source_01.bal
  compiler/ballerina-parser/src/test/resources/expressions/anon-func/anon_func_source_02.bal
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_14.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_source_14.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_14.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_15.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_16.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_17.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_19.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_14.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_15.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_16.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_17.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_19.bal
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/mapping_binding_pattern_assert_01.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/mapping_binding_pattern_source_01.bal
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_18.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_19.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_source_18.bal
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_source_19.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_05.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_05.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_02.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_03.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_04.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_06.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_09.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_11.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_01.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_02.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_03.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_04.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_06.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_09.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_11.bal
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  misc/formatter/modules/formatter-core/src/test/resources/types/behavioural/assert/function_type_2.bal
Labels: Component/Formatting, Team/Tooling, Type/Bug

#27100 Fix TypeConverter error
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionWithStampTypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal
Labels: Team/CompilerFE

#27229 Fix 'lang.array:reverse()' creates a new array
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BArray.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/AbstractArrayValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Reverse.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Team/jBallerina

#27320 Fix issue in optional field access
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/OptionalFieldAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access_negative.bal
Labels: Team/CompilerFE

#27599 Remove Content on IntelliJ and ANTLR from the Contributing Guide
  CONTRIBUTING.md
Labels: Type/Docs

#27620 Fix included record parameter issue with `init` function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionWithIncludedRecordParam.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal
Labels: Team/CompilerFE

#27406 Fix top level service qualifier with readonly and distinct
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ClassDefinitionTest.java
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_15.json
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_source_15.bal
Labels: Team/CompilerFE

#26931 Refactor Interop validation into separate phase
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BuildOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/CompilerPhaseRunner.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/CompilerPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropValidator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JBIRFunction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JFieldBIRFunction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JFieldFunctionWrapper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodBIRFunction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodRequest.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/OldStyleExternalFunctionWrapper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/CompilerUtils.java
  docs/bir-spec/build.gradle
  docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java
Labels: Team/jBallerina

#27632 Add missing part relate to `RequiredParameterNode` class
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/RequiredParameterNode.java
Labels: Area/Parser, Team/CompilerFE
