Repository ballerina-platform/ballerina-lang, pull requests merged in 2020-10, with the labels that each got.

#25882 Add support for value:toBalString()
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/CycleUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/api/BStringUtils.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/api/values/BLink.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/api/values/BValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractArrayValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/BmpStringValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/DecimalValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FPValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/FutureValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/HandleValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/IteratorValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/NonBmpStringValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamingJsonValue.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TupleValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TypedescValueImpl.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLComment.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLNonElementItem.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLQName.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java
  langlib/lang.value/src/main/ballerina/src/lang.value/value.bal
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/ToBalString.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_toBalString_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/optional_field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/optional_field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/optional_field_access_ctx_config3.json
  stdlib/mime/src/main/java/org/ballerinalang/mime/util/MultipartDataSource.java
Labels: Team/CompilerFE

#26010 Add Balo Writer
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Package.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageConfig.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageOrg.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageVersion.java
  project-api/ballerina-projects/build.gradle
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/directory/PackageLoader.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/env/CustomPackageResolver.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/model/BallerinaToml.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/model/BallerinaTomlProcessor.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/model/BaloJson.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/model/Dependency.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/model/Package.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/model/PackageJson.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/model/PlatformLibrary.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/model/adaptors/JsonCollectionsAdaptor.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/model/adaptors/JsonStringsAdaptor.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/utils/ProjectConstants.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/utils/ProjectUtils.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/writers/BaloWriter.java
  project-api/ballerina-projects/src/test/java/io/ballerina/projects/test/TestBallerinaTomlProcessor.java
  project-api/ballerina-projects/src/test/java/io/ballerina/projects/test/writers/TestBaloWriter.java
  project-api/ballerina-projects/src/test/java/io/ballerina/projects/test/writers/TestUtils.java
  project-api/ballerina-projects/src/test/resources/ballerinatoml/Ballerina.toml
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/Ballerina.toml
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/Module.md
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/Package.md
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/libs/ballerina-io-1.0.0-java.txt
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/main.bal
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/services/Module.md
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/services/resources/config.json
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/services/resources/invalidProject/Ballerina.toml
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/services/resources/invalidProject/main.bal
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/services/resources/invalidProject/tests/main_tests.bal
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/services/svc.bal
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/services/tests/svc_tests.bal
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/storage/Module.md
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/storage/db.bal
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/storage/resources/db.json
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/modules/storage/tests/db_tests.bal
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/resources/main.json
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/tests/main_tests.bal
  project-api/ballerina-projects/src/test/resources/balowriter/projectOne/utils.bal
  project-api/ballerina-projects/src/test/resources/balowriter/projectTwo/Ballerina.toml
  project-api/ballerina-projects/src/test/resources/balowriter/projectTwo/main.bal
  project-api/ballerina-projects/src/test/resources/myproject/Ballerina.toml
  project-api/ballerina-projects/src/test/resources/test_projects_temporary/http/Ballerina.toml
Labels: Team/DevTools

#26195 Improve type resolving for query expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-var-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/xml-query-expression.bal
Labels: Language/Streams, Team/CompilerFE

#26156 Add BaloProject
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/balo/BaloFiles.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/balo/BaloPackageLoader.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/balo/BaloProject.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/directory/PackageLoader.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/directory/ProjectFiles.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/utils/ProjectUtils.java
  project-api/ballerina-projects/src/test/java/io/ballerina/projects/test/balo/TestBaloProject.java
  project-api/ballerina-projects/src/test/resources/baloloader/foo-winery-java8-0.1.0.balo
Labels: Team/DevTools

#26203 Restrict zero match clauses in match statement
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/MatchStatementTest.java
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_16.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_16.bal
Labels: Team/CompilerFE

#26229 Fix position issue in empty package alias for function calls
  compiler/ballerina-compiler-api/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  compiler/ballerina-compiler-api/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
Labels: Area/SemanticAPI, Team/CompilerFE

#26232 Add APIs for getting the defaultable params and param kinds
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/FunctionTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/Parameter.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/ParameterKind.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/symbols/SymbolFactory.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaFunctionTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaParameter.java
Labels: Area/SemanticAPI, Team/CompilerFE

#26233 Fix the JDBC Driver Path
  examples/jdbc-client-batch-update/jdbc_client_batch_update.description
  examples/jdbc-client-call-procedures/jdbc_client_call_procedures.description
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.description
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/Module.md
Labels: Type/Docs

#26231 Fix the JDBC/MySQL Driver File Path
  examples/jdbc-client-batch-update/jdbc_client_batch_update.description
  examples/jdbc-client-call-procedures/jdbc_client_call_procedures.description
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.description
  examples/jdbc2-complex-type-queries/jdbc2_complex_type_queries.description
  examples/jdbc2-execute-operation/jdbc2_execute_operation.description
  examples/jdbc2-init-options/jdbc2_init_options.description
  examples/jdbc2-query-operation/jdbc2_query_operation.description
  examples/mysql-complex-type-queries/mysql_complex_type_queries.description
  examples/mysql-execute-operation/mysql_execute_operation.description
  examples/mysql-init-options/mysql_init_options.description
  examples/mysql-query-operation/mysql_query_operation.description
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/Module.md
Labels: Type/Docs

#26245 Change `alias` to `prefix` in the Module BBE
  examples/modules/modules.bal
  examples/modules/modules.description
Labels: Type/Docs

#26237 Fix NPE issue in retrieving the return type from a function type
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaFunctionTypeDescriptor.java
Labels: Area/SemanticAPI, Team/CompilerFE

#26246 Fix failure during running uber jar
  bvm/ballerina-rt/build.gradle
  distribution/zip/jballerina-tools/build.gradle
  distribution/zip/jballerina/build.gradle
  gradle/baseNativeStdLibProject.gradle
  gradle/javaLibsProject.gradle
  langlib/ballerina-java/src/main/ballerina/Ballerina.toml
  langlib/java/build.gradle
  langlib/java/src/main/ballerina/Ballerina.toml
  langlib/java/src/main/ballerina/src/java/JObject.bal
  langlib/java/src/main/ballerina/src/java/Module.md
  langlib/java/src/main/ballerina/src/java/annotations.bal
  langlib/java/src/main/ballerina/src/java/ballerina_values_to_Java.bal
  langlib/java/src/main/ballerina/src/java/error.bal
  langlib/java/src/main/java/module-info.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/Cast.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/CreateNull.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/FromString.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/GetArrayElement.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/GetArrayLength.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/IsNull.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/JValues.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/JavaUtils.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/SetArrayElement.java
  langlib/java/src/main/java/org/ballerinalang/langlib/java/ToString.java
  langlib/lang.__internal/build.gradle
  langlib/lang.array/build.gradle
  langlib/lang.boolean/build.gradle
  langlib/lang.decimal/build.gradle
  langlib/lang.error/build.gradle
  langlib/lang.float/build.gradle
  langlib/lang.future/build.gradle
  langlib/lang.int/build.gradle
  langlib/lang.map/build.gradle
  langlib/lang.object/build.gradle
  langlib/lang.query/build.gradle
  langlib/lang.stream/build.gradle
  langlib/lang.string/build.gradle
  langlib/lang.table/build.gradle
  langlib/lang.test/build.gradle
  langlib/lang.transaction/build.gradle
  langlib/lang.typedesc/build.gradle
  langlib/lang.value/build.gradle
  langlib/lang.xml/build.gradle
  langlib/langlib-test/build.gradle
  language-server/modules/langserver-stdlib/build.gradle
  misc/ballerinalang-data-mapper/build.gradle
  misc/testerina/modules/testerina-core/build.gradle
  observelib/observe/build.gradle
  settings.gradle
  stdlib/cache/build.gradle
  tests/jballerina-integration-test/build.gradle
  tests/jballerina-unit-test/build.gradle
  tests/observability-test-utils/build.gradle
Labels: Team/jBallerina

#26286 Update supported platform to Java 11 in observability test case resources
  tests/jballerina-integration-test/src/test/resources/observability/metrics/Ballerina.toml
  tests/observability-test-utils/src/test/resources/listener/Ballerina.toml
Labels: Team/Build

#26257 Fix typedesc issues in semantic API
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/ErrorTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/FunctionTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/FutureTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/MapTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/ObjectTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/RecordTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/StreamTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/TupleTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/TypeDescTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/api/types/UnionTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/TypesFactory.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaErrorTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaFunctionTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaFutureTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaMapTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaObjectTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaRecordTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaStreamTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaTupleTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaTypeDescTypeDescriptor.java
  compiler/ballerina-compiler-api/src/main/java/io/ballerina/compiler/impl/types/BallerinaUnionTypeDescriptor.java
  compiler/ballerina-compiler-api/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  compiler/ballerina-compiler-api/src/test/resources/test-src/typedesc_test.bal
  compiler/ballerina-compiler-api/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#26234 Fix the JDBC Driver Path in 1.0.x
  examples/jdbc-client-batch-update/jdbc_client_batch_update.description
  examples/jdbc-client-call-procedures/jdbc_client_call_procedures.description
  examples/jdbc-client-crud-operations/jdbc_client_crud_operations.description
  stdlib/jdbc/src/main/ballerina/src/java.jdbc/Module.md
Labels: Type/Docs

#25708 Add the "meta.json" File to the "/examples" Folder - 1.0.x
  examples/meta.json
Labels: Type/Docs

#25652 Change the Edit links of BBEs of 1.0.x
  examples/index.json
Labels: Type/Docs

#25407 Rename the Protocol BBEs with Dots in Their Titles for 1.0.x
  examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.bal
  examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.client.out
  examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.description
  examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.server.out
  examples/http-1-1-to-2-0-protocol-switch/tests/http_1.1_to_2.0_protocol_switch_test.bal
  examples/http-2-0-server-push/http_2_0_server_push.description
  examples/http-2-0-server-push/http_2_0_service.bal
  examples/http-2-0-server-push/http_2_0_service.out
  examples/http-2-0-server-push/http_client.bal
  examples/http-2-0-server-push/http_client.out
  examples/http-2-0-server-push/tests/http-2.0-server-push_test.bal
  examples/index.json
Labels: Type/Docs

#26259 Allow `new` as a valid constructor for `stream`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/lang.__internal/src/main/ballerina/src/lang.__internal/stream-utils.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Language/Streams, Team/CompilerFE

#26216 Map internal symbol flags to qualifiers in public symbol API
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaAnnotationSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaConstantSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMethodSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaVariableSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/AnnotationSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/Deprecatable.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/FunctionSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/Qualifiable.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/Qualifier.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/SymbolKind.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/TypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/VariableSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangService.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_flag_to_qualifier_mapping_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#26312 Remove use of optional values for typedescs in symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMethodSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaVariableSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/BallerinaObjectTypeDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/FunctionSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/TypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/VariableSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#26316 [Formatter] Add several node implementations
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
Labels: Component/Formatting, Type/Improvement

#26274 Refactor http filter desugar and Add function to get annotation keys
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/AnnotatableType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
Labels: Component/HTTP, Team/StandardLibs, Type/Task

#26315 Change the NodeResolver to return the symbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/AnnotationAttachmentNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/AnnotationNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/ClassDefinition.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/IdentifiableNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/ImportPackageNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/InvokableNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/TypeDefinition.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/VariableNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/VariableReferenceNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangAnnotation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangAnnotationAttachment.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangClassDefinition.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangImportPackage.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangInvokableNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangService.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangTypeDefinition.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangVariable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangConstant.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangVariableReference.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerFlushExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerReceive.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerSyncSendExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangWorkerSend.java
Labels: Area/SemanticAPI, Team/CompilerFE

#26347 [Formatter] Add several node implementations
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
Labels: Component/Formatting

#26345 Revert "Refactor http filter desugar and Add function to get annotation keys"
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/AnnotatableType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
Labels: Team/StandardLibs, Type/Task

#26333 Filter symbols of nodes added by the parser
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/missing_node_filtering_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#26352 [Formatter] Add several node implementations
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
Labels: Component/Formatting

#26339 [Formatter] Implement some methods in NewFormattingTreeModifier
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/actions/send-receive/assert/send_receive_action_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/send-receive/assert/send_receive_action_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/send-receive/source/send_receive_action_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/send-receive/source/send_receive_action_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/send-receive/source/send_receive_action_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/sequence/assert/xml_type_6.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/sequence/source/xml_type_6.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/structured/source/array_type_1.bal
Labels: Component/Formatting, Team/Tooling

#26338 Make positions 0-based in the compiler
  cli/ballerina-tool/src/main/java/org/ballerinalang/tool/util/BAssertUtil.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/Compiler.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/FileSystemSourceInput.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/Parser.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DiagnosticsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_lookup_in_assignment.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BAssertUtil.java
Labels: Area/SemanticAPI, Team/CompilerFE

#26344 Validate missing key expr in invalid member access expressions in parser
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access_negative.bal
Labels: Area/Parser, Team/CompilerFE

#26302 Restrict invalid expressions starting with a simple type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteArrayValueNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/typedesc/TypedescTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/typedesc/typedesc_negative.bal
Labels: Team/CompilerFE

#26334 Update Docs for the JDK 11 Migration
  misc/build-scripts/README.md
Labels: Type/Docs

#26306 Fix issue in BLangIsLikeExpr
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal
Labels: Team/CompilerFE

#26335 Add support to read custom fields of OAuth2 introspection response
  stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/auth/OAuth2ServiceTest.java
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/21_oauth2_service_test.bal
  tests/jballerina-integration-test/src/test/resources/auth/src/authservices/oauth2-mock-server.bal
Labels: Component/OAuth2, Team/StandardLibs, Type/Improvement

#26358 [Formatter] Implement the missing node transform methods in NewFormattingTreeModifier and fix some failing formatter related tests
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/declarations/ClassDefinitionDeclarationsTest.java
  misc/formatter/modules/formatter-core/src/test/resources/actions/query/assert/query_action_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/start/assert/start_action_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/type-cast/assert/type_cast_action_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/class-definition/assert/class_definition_declaration_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/class-definition/assert/class_definition_declaration_4.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/module-enumeration/assert/module_enumeration_declaration_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/expressions/range/assert/range_expression_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/expressions/range/assert/range_expression_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/call/assert/call_statement_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/do/assert/do_statement_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/do/assert/do_statement_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/foreach/assert/foreach_statement_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/foreach/assert/foreach_statement_4.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/if-else/assert/if_else_statement_4.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/lock/assert/lock_statement_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/match/assert/match_statement_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/match/assert/match_statement_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/while/assert/while_statement_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/statements/while/assert/while_statement_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/behavioural/assert/function_type_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/behavioural/assert/object_type_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/other/assert/json_type_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/other/assert/json_type_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/other/assert/readonly_type_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/structured/assert/map_type_2.bal
Labels: Component/Formatting, Team/Tooling

#26368 [Formatter] Remove the addition of missing tokens after formatting
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/FormatterTest.java
Labels: Component/Formatting

#26370 Introduce formatting env to hold the state-variables
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingEnv.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingOptions.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/misc/LineWrappingTest.java
  misc/formatter/modules/formatter-core/src/test/resources/misc/linewrapping/assert/line_wrapping_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/linewrapping/source/line_wrapping_1.bal
Labels: Component/Formatting, Team/Tooling

#26319 Fix issue when calling function with error return in service
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/MockListener.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/Timer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/serializer/json/JsonSerializerTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ErrorReturnTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/services/error_return_function.bal
  tests/jballerina-unit-test/src/test/resources/testng-new-parser.xml
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#26353 Support fail within nested on fail in do statement
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangOnFailClause.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/dostatement/do-stmt.bal
Labels: Team/CompilerFE

#26375 [Formatter] Remove the previous formatter implementation
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeIndentation.java
Labels: Component/Formatting, Team/Tooling

#26383 Fix qualfiers and object constructor indentations
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/statements/IfElseStatementsTest.java
  misc/formatter/modules/formatter-core/src/test/resources/declarations/class-definition/assert/class_definition_declaration_15.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/class-definition/assert/class_definition_declaration_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/class-definition/assert/class_definition_declaration_9.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/class-definition/source/class_definition_declaration_15.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/behavioural/assert/object_type_1.bal
Labels: Component/Formatting, Team/Tooling

#26384 [Formatter] Fix test cases and exception handling
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NewFormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/declarations/class-definition/assert/class_definition_declaration_17.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/class-definition/assert/class_definition_declaration_5.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/class-definition/source/class_definition_declaration_5.bal
  misc/formatter/modules/formatter-core/src/test/resources/expressions/query/assert/query_expression_4.bal
  misc/formatter/modules/formatter-core/src/test/resources/expressions/query/source/query_expression_4.bal
Labels: Component/Formatting, Team/Tooling

#26101 Add support to import predeclared langlibs manually for testable packages
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BaseTestCase.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/ImportTest.java
  tests/testerina-integration-test/src/test/resources/project-based-tests/predeclared-import-tests/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/project-based-tests/predeclared-import-tests/src/importTests/tests/imports-tests.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#26413 Fix service declaration context completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/SymbolUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ExplicitNewExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ListenerDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ServiceDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/ModuleVariableContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/ServiceBodyTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/XMLTypeDescContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/new/module_var_context/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/module_var_context/config/config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/module_var_context/config/config4.json
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Area/LanguageServer

#26172 Remove XML functional constructors
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/symbols/SymbolKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/FunctionalConstructorBuilder.java
  langlib/lang.__internal/src/main/ballerina/src/lang.__internal/xml-internal.bal
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/CommentCtor.java
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/ElementCtor.java
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/ProcessingInstructionCtor.java
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/TextCtor.java
  langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateText.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/CompletionTestNew.java
Labels: Team/CompilerFE

#26003 Capture dependencies of global variables
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/cyclefind/GlobalVariableRefAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BVarSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangPackage.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangLock.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/lock/LocksInMainTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/lock/parallel-run-lock.bal
Labels: Team/CompilerFE

#26396 Align mapping constructor spread-expr analysis with the spec
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/lang.query/src/main/ballerina/src/lang.query/types.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor_infer_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field_code_analysis_negative.bal
Labels: Team/CompilerFE

#26173 Add missing similarity criteria between array and tuple types
  bvm/ballerina-core/src/main/java/org/ballerinalang/core/model/types/BArrayType.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/core/model/values/BNewArray.java
  bvm/ballerina-core/src/main/java/org/ballerinalang/core/model/values/BValueArray.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ArrayType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/types/BArrayType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/values/ArrayValueImpl.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BArrayType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/BArrayState.java
  compiler/ballerina-lang/src/test/resources/node-tree/basic-literals.json
  compiler/ballerina-lang/src/test/resources/node-tree/expr.json
  compiler/ballerina-lang/src/test/resources/node-tree/function-def.json
  compiler/ballerina-lang/src/test/resources/node-tree/function-invoc.json
  compiler/ballerina-lang/src/test/resources/node-tree/records.json
  compiler/ballerina-lang/src/test/resources/node-tree/stmt.json
  compiler/ballerina-lang/src/test/resources/node-tree/types.json
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
Labels: Team/CompilerFE

#25966 Unify object method scope and object field scope
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachErrorBindingPatternsTests.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/documentation/DocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/function-pointers.bal
Labels: Team/CompilerFE

#25935 Add support for `ensureType` langlib function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/lang.value/src/main/ballerina/src/lang.value/value.bal
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/EnsureType.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibNegativeTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/langlib_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/optional_field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/optional_field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/optional_field_access_ctx_config3.json
Labels: Team/CompilerFE

#26035 Fix issues with final fields
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/FinalObjectFieldTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/final_object_fields.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/final_object_fields_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/final_object_fields_semantics_negative.bal
Labels: Team/CompilerFE

#26113 Introduce the `@isolatedParam` annotation
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/Flags.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/lang.annotations/src/main/ballerina/src/lang.annotations/annotations.bal
  langlib/lang.array/src/main/ballerina/src/lang.array/array.bal
  langlib/lang.map/src/main/ballerina/src/lang.map/map.bal
  langlib/lang.stream/src/main/ballerina/src/lang.stream/stream.bal
  langlib/lang.table/src/main/ballerina/src/lang.table/table.bal
  langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/IsolatedParamTest.java
  langlib/langlib-test/src/test/resources/test-src/isolated-param/isolated_param.bal
  langlib/langlib-test/src/test/resources/test-src/isolated-param/isolated_param_negative.bal
  langlib/langlib-test/src/test/resources/test-src/isolated-param/isolated_param_semantic_negative.bal
  langlib/langlib-test/src/test/resources/testng.xml
  language-server/modules/langserver-core/src/test/resources/completion/new/annotation_ctx/config/paramAnnotation1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/annotation_ctx/config/paramAnnotation2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/annotation_ctx/config/paramAnnotation5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/annotation_ctx/config/paramAnnotation7.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
Labels: Team/CompilerFE

#26141 Fix several deviations in isolation analysis
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/immutable_module_def_access_in_isolated_contexts.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis_negative.bal
Labels: Team/CompilerFE

#26427 [Formatter] Fix bugs and enable parser test cases
  compiler/ballerina-parser/src/test/resources/actions/start-action/start_action_assert_03.json
  compiler/ballerina-parser/src/test/resources/actions/start-action/start_action_source_03.bal
  compiler/ballerina-parser/src/test/resources/actions/wait-action/wait_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/wait-action/wait_action_source_02.bal
  compiler/ballerina-parser/src/test/resources/expressions/anon-func/anon_func_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/anon-func/anon_func_source_01.bal
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_20.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_source_20.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_06.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_14.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_15.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_17.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_19.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_06.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_14.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_15.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_17.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_19.bal
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/mapping_binding_pattern_assert_01.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/mapping_binding_pattern_source_01.bal
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_12.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_18.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_19.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_source_12.bal
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_source_18.bal
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_source_19.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_01.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_05.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_08.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_14.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_01.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_05.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_08.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_14.bal
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingEnv.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  misc/formatter/modules/formatter-core/src/test/resources/types/behavioural/assert/streams_type_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/structured/assert/table_type_1.bal
Labels: Component/Formatting

#26357 Introduce support for isolated objects
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_semantic_negative.bal
Labels: Team/CompilerFE

#26428 Fix field access expression issues
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FieldAccessContext.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/ExpressionContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/new_expr_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/new_expr_ctx_config4.json
Labels: Area/LanguageServer

#26407 Cause program to exit when there are service definitions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/listener/LaunchListenerTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/ServiceTest.java
  tests/jballerina-integration-test/src/test/resources/service/listener/service_only.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/listener/ListenerBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/execution/ModuleExecutionFlowTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ListenerLifeCycleTest.java
Labels: Team/jBallerina

#26377 Fix Decimal value comparison
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/GreaterLessThanOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/greater-less-than-operation.bal
Labels: Team/jBallerina

#26448 Change the match-clause cloner
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementSyntaxErrorsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Priority/Blocker, Team/CompilerFE

#26435 Fix optional attributes in parser nodes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/EnumDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ModuleVariableDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModuleVariableDeclarationNodeContext.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
Labels: Area/Parser, Component/Formatting

#26454 Set annotation values readonly, if only attach points contain dual attach point without source
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/CompilerFE

#26457 Allow accessing final isolated object vars in isolated functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis_negative.bal
Labels: Team/CompilerFE

#26447 Disallow samenamed object field and method
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  stdlib/cache/src/main/ballerina/src/cache/cache.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/ObjectProject/src/pkg1/pkg1.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/ObjectProject/src/pkg2/pkg2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_field_with_same_name_as_method_neg.bal
Labels: Team/CompilerFE

#26473 Fix the incorrect mandatory attribute in parser node `FlushActionNode`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/FlushActionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
Labels: Area/Parser, Component/Formatting

#26474 Fix the incorrect mandatory attribute in parser node `ServiceDeclarationNode`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ServiceDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
Labels: Area/Parser, Component/Formatting

#26480 Fix JSON 'mergeJson' functionality
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/values/MapValueImpl.java
Labels: Priority/Blocker, Team/jBallerina

#26467 Fix remote action suggestions
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/completion/CompletionKeys.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FieldAccessContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RightArrowActionNodeContext.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/ExpressionContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/FunctionBodyTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/StatementContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/field_access_ctx_source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/field_access_ctx_source6.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/assignment_stmt_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/async_send_action_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/foreach_stmt_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/foreach_stmt_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/remote_action_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/wait_action_ctx_config1.json
Labels: Area/LanguageServer

#26484 Fix appending additional newline after formatting
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
Labels: Component/Formatting, Team/Tooling

#26493 Disable the maven resolver component in the bindgen tool
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-bindgen.help
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/MavenSupportTest.java
Labels: Component/Bindgen, Team/DevTools

#26504 Fix completion issue within qualified name reference
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/latest/StatementContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/assignment_stmt_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/source/assignment_stmt_ctx_source4.bal
Labels: Area/LanguageServer

#26508 Fix code action issue for function-invocations
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/VariableAssignmentRequiredCodeActionProvider.java
Labels: Area/LanguageServer, Priority/Blocker, Team/Tooling, Type/Bug

#26514 Fix docs duplication for document-all code-action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocumentationGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddAllDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddDocumentationExecutor.java
Labels: Area/LanguageServer, Priority/Blocker, Team/Tooling, Type/Bug

#26512 Fix issue with example and project service not working
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
Labels: Area/LanguageServer

#26510 Fix SO error in copy in analysis
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
Labels: Priority/Blocker, Team/CompilerFE

#26533 Allow using a compatible map as a record at runtime
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal
Labels: Priority/Blocker

#26546 Introduce the temporary fix to get the langlib tests passing
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BaloWriter.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Module.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleConfig.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Package.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageConfig.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java
  misc/lib-creator/src/main/java/org/ballerinalang/stdlib/utils/BuildLangLib.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/balo/BaloFiles.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/directory/ModuleData.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/directory/PackageLoader.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/env/BuildEnvContext.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/env/LangLibResolver.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java
Labels: Component/ProjectAPI

#26543 Fix the NoClassDefFoundError when running the built jar from a bal file which contains a transaction block
  bvm/ballerina-rt/build.gradle
Labels: Priority/Blocker

#26542 Refactor debug logs in transactions module
  stdlib/transactions/src/main/ballerina/src/transactions/2pc_participant.bal
  stdlib/transactions/src/main/ballerina/src/transactions/2pc_transaction.bal
  stdlib/transactions/src/main/ballerina/src/transactions/commons.bal
  stdlib/transactions/src/main/ballerina/src/transactions/service_initiator.bal
  stdlib/transactions/src/main/ballerina/src/transactions/service_participant_2pc.bal
  stdlib/transactions/src/main/ballerina/src/transactions/transaction_block.bal
Labels: Language/Transaction

#26556 Fix error-type-desc signature returning empty type-name
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/BallerinaErrorTypeDescriptor.java
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_join_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_join_clause_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_join_clause_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_limit_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_limit_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_onconflict_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_orderby_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_orderby_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_select_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_select_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/trap_expression_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/var_ref_ctx_config5.json
Labels: Area/SemanticAPI, Priority/Blocker, Team/CompilerFE, Type/Bug

#26572 Fix lang.* import resolution issue
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DocumentContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageName.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageOrg.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ModuleLoadRequest.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/repos/PackageCache.java
Labels: Component/ProjectAPI

#26573 Run df analysis, isolation analysis, and constant propagation for langlib modules
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  langlib/lang.__internal/src/main/ballerina/src/lang.__internal/int-range.bal
  langlib/lang.__internal/src/main/ballerina/src/lang.__internal/stream-utils.bal
  langlib/lang.array/src/main/ballerina/src/lang.array/array.bal
  langlib/lang.array/src/main/ballerina/src/lang.array/internal.bal
  langlib/lang.map/src/main/ballerina/src/lang.map/internal.bal
  langlib/lang.query/src/main/ballerina/src/lang.query/helpers.bal
  langlib/lang.query/src/main/ballerina/src/lang.query/types.bal
  langlib/lang.stream/src/main/ballerina/src/lang.stream/internal.bal
  langlib/lang.stream/src/main/ballerina/src/lang.stream/stream.bal
  langlib/lang.string/src/main/ballerina/src/lang.string/internal.bal
  langlib/lang.table/src/main/ballerina/src/lang.table/internal.bal
  langlib/lang.xml/src/main/ballerina/src/lang.xml/internal.bal
Labels: Team/CompilerFE

#26604 Modify function type descriptor API to include default parameters
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/AbstractTypeDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/BallerinaFunctionTypeDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/types/FunctionTypeDescriptor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/FunctionCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/new/class_def/config/config7.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/anon_func_expr_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/check_expression_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/check_expression_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/check_expression_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/fail_expr_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/list_constructor_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/mapping_expr_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/mapping_expr_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/mapping_expr_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/mapping_expr_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/member_access_expr_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/member_access_expr_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/object_constructor_expr_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_join_clause_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_join_clause_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_limit_clause_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_onconflict_clause_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_orderby_clause_config2a.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_select_clause_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_where_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/trap_expression_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/trap_expression_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/typeof_expression_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/typeof_expression_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/var_ref_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/var_ref_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/var_ref_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/var_ref_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/assignment_stmt_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/do_stmt_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/remote_action_config1.json
  language-server/modules/langserver-stdlib/src/main/ballerina/src/module1/clients/source1.bal
  language-server/modules/langserver-stdlib/src/main/ballerina/src/module1/functions/source1.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
Labels: Area/LanguageServer

#26422 Revamp ballerina parser qualifier parsing
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/FunctionDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ObjectMethodTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ObjectTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/AmbiguityResolutionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/FunctionTypeTest.java
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_42.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_25.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_source_25.bal
  compiler/ballerina-parser/src/test/resources/declarations/isolated-object-methods/isolated_object_method_assert_02.json
  compiler/ballerina-parser/src/test/resources/declarations/isolated-object-methods/isolated_object_method_source_02.bal
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_19.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_20.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_33.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_42.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_source_33.bal
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_31.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_source_31.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_10.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_12.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_10.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_12.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ResilientParserTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/parser/resilient-parsing-class-defn.bal
Labels: Team/CompilerFE

#26456 Add benchmark tests for language related features
  gradle/javaProject.gradle
  settings.gradle
  tests/jballerina-benchmark-test/README.md
  tests/jballerina-benchmark-test/benchmarkFunctions.txt
  tests/jballerina-benchmark-test/build.gradle
  tests/jballerina-benchmark-test/executor
  tests/jballerina-benchmark-test/spotbugs-exclude.xml
  tests/jballerina-benchmark-test/src/main/ballerina/Ballerina.toml
  tests/jballerina-benchmark-test/src/main/ballerina/src/benchmark/benchmark-loops.bal
  tests/jballerina-benchmark-test/src/main/ballerina/src/benchmark/benchmark-type-float.bal
  tests/jballerina-benchmark-test/src/main/ballerina/src/benchmark/benchmark-type-string.bal
  tests/jballerina-benchmark-test/src/main/ballerina/src/benchmark/executor.bal
  tests/jballerina-benchmark-test/src/main/ballerina/src/benchmark/register-functions.bal
  tests/jballerina-benchmark-test/src/main/ballerina/src/benchmark/utils/benchmark-utils.bal
  tests/jballerina-benchmark-test/src/main/ballerina/src/benchmark/utils/math-utils.bal
  tests/jballerina-benchmark-test/src/main/ballerina/src/benchmark/utils/print-utils.bal
  tests/jballerina-benchmark-test/src/main/ballerina/src/benchmark/utils/time-utils.bal
  tests/jballerina-benchmark-test/src/main/java/module-info.java
  tests/jballerina-benchmark-test/src/main/java/org/ballerinalang/benchmark/nativeimpl/Utils.java
  tests/jballerina-benchmark-test/src/test/java/org/ballerinalang/benchmark/BenchmarkUtilTest.java
  tests/jballerina-benchmark-test/src/test/resources/test-src/benchmark/benchmark-util-test.bal
  tests/jballerina-benchmark-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#26613 Update performance test results for Ballerina Swan Lake Preview 3
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Team/StandardLibs, Type/Task

#26619 Initial attempt to decouple compilation from the backend specific aspects
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilerBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/EmitResult.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JdkVersion.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ProjectJarResolver.java
  misc/lib-creator/src/main/java/org/ballerinalang/stdlib/utils/BuildLangLib.java
  project-api/ballerina-projects/src/main/java/io/ballerina/projects/env/BuildProjectEnvContext.java
  project-api/ballerina-projects/src/test/java/io/ballerina/projects/test/TestBaloWriter.java
  project-api/ballerina-projects/src/test/java/io/ballerina/projects/test/TestBirWriter.java
  project-api/ballerina-projects/src/test/java/io/ballerina/projects/test/TestJarWriter.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
Labels: Component/ProjectAPI

#26581 Fixed parameter types of Syntax API factory methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STOrderByClauseNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STXMLItemNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/AbstractNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/OrderByClauseNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TemplateExpressionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TemplateMemberNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TypeCastParamNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/XMLItemNode.java
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
Labels: Area/SyntaxAPI

#26627 Fix error-type-desc signature returning empty type-name
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/BallerinaErrorTypeDescriptor.java
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_join_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_join_clause_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_join_clause_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_limit_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_limit_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_onconflict_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_orderby_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_orderby_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_select_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_select_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/trap_expression_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/var_ref_ctx_config5.json
Labels: Area/SemanticAPI, Team/Tooling, Type/Bug

#26566 Handle missing tokens in the formatter
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STAbstractNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/AbstractNodeFactory.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/SyntaxTreeJSONGenerator.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/TestParser.java
  compiler/ballerina-parser/src/test/resources/test1.bal
  compiler/ballerina-parser/src/test/resources/test2.bal
  compiler/ballerina-parser/src/test/resources/test3.bal
  compiler/ballerina-parser/src/test/resources/test4.bal
  compiler/ballerina-parser/src/test/resources/test5.bal
  compiler/ballerina-parser/src/test/resources/test_parser.bal
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/expressions/query/assert/query_expression_4.bal
Labels: Component/Formatting, Team/Tooling

#26638 Re-organize syntax errors
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_07.json
Labels: Area/Parser, Team/CompilerFE

#26465 Change the formatter API to return an exception
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java
  misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterException.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/FormatterTest.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Component/Formatting, Team/Tooling, Type/Improvement

#26365 Make LS Config-API extensible for extension devs
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/config/ClientConfigListener.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/config/LSClientConfig.java
  language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/config/LSClientConfigHolder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/LSCodeLensesProviderHolder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/DocsCodeLensesProvider.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeAction.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/config/DataMapperConfig.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/config/LSClientExtendedConfig.java
Labels: Area/LanguageServer, Team/CompilerFE, Type/NewFeature

#26666 Update performance test results for Ballerina Swan Lake Preview 5
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Team/StandardLibs, Type/Task

#26250 Update the Config API in 1.2.x Similar to Swan Lake
  examples/config-api/config_api.bal
  examples/config-api/config_api.description
  examples/config-api/config_api.out
  examples/config-api/sample.conf
  examples/config-api/tests/config_api_test.bal
Labels: Type/Docs

#26395 Enable language and runtime tests which disable with JDK 11 migration
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/ErrorCreator.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/functions/FunctionSignatureInBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/object/ObjectInBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/object/ReadOnlyObjectBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/object/RemoteObjectBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/AccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/OptionalFieldAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/rawtemplate/RawTemplateLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/VariableReturnTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/primitivetypes/PrimitiveConversionsInFunctionParamsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/varargs/JavaVarargsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/FinalObjectFieldTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectEquivalencyTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ReadonlyObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ReadonlyRecordFieldTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/CaptureBindingPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/returnstmt/ReturnStmtNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/VarDeclrSemanticTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/ByteAsIntTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralWithNamespacesTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerCallingFunction.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#26687 Update performance test results for Ballerina v1.2.7
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Team/StandardLibs, Type/Task

#26690 Update performance test results for Ballerina v1.2.8
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Team/StandardLibs, Type/Task
