Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-04, with the labels that each got.

#29718 Fix operand processing issues
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/cli/CliSpec.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/cli/CliUtil.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/cli/Option.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/cli/OperandTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/cli/OperandTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/cli/operand_complex.bal
  tests/jballerina-unit-test/src/test/resources/test-src/cli/operand_default_array.bal
  tests/jballerina-unit-test/src/test/resources/test-src/cli/operand_default_only.bal
  tests/jballerina-unit-test/src/test/resources/test-src/cli/operand_int_and_default.bal
  tests/jballerina-unit-test/src/test/resources/test-src/cli/operand_rest_param_only.bal
  tests/jballerina-unit-test/src/test/resources/test-src/cli/operand_rest_param_without_value.bal
Labels: Team/jBallerina

#29719 Deprecate parameters() and introduce params() as the alternative
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/AbstractTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMethodSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaParameterSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaResourceMethodSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/FunctionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ParameterKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/FunctionCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/InvocationArgProcessor.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ParameterSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/param_symbols_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#29699 Make "always evaluate to true" error a hint
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DiagnosticResult.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Diagnostics.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLog.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/test/java/org/ballerinalang/util/DiagnosticCodeTest.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BAssertUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/CompileResult.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/errorconstructorexpr/ErrorConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
Labels: Team/CompilerFE

#29709 Introduce a separate symbol kind for enum members
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaConstantSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/SymbolKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/Flag.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/Flags.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/SymbolUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ConstantCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ArrayTypeDescriptorNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BlockNodeContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ConstantDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MatchStatementContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/match_stmt_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/match_stmt_ctx_config5.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/AnnotationsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByEnumTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#29773 Map service decl node start location to the location of the service keyword
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_service_decl_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#29780 Fix issue in parsing BacktickString
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractTokenReader.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/TokenReader.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/incremental/HybridTokenReader.java
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_24.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java
Labels: Area/Parser, Team/CompilerFE

#29661 Fix LS suggestions when func-body close-brace is missing
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_23.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_23.bal
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionBodyBlockNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/local_var_decl_stmt_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/source/local_var_decl_stmt_ctx_source1.bal
Labels: Area/Completion, Area/Parser, Team/CompilerFE

#29641 Fix NPE thrown from semantic-api for `iterator().next()`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction42.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariable7.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_lookup_with_record_field_imports_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#29809 Set the location of a var ref to the position of the var name
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/rename/ProjectRenameTest.java
  language-server/modules/langserver-core/src/test/resources/rename/expected/project/rename_global_var_result.json
  language-server/modules/langserver-core/src/test/resources/rename/sources/project/modules/module1/module1.bal
  language-server/modules/langserver-core/src/test/resources/rename/sources/project/modules/module2/module2.bal
Labels: Area/Rename, Area/SemanticAPI, Team/CompilerFE, Team/LanguageServer

#29782 Add APIs for getting deprecated doc info
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaDocumentation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/Documentation.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/MarkdownDocAttachment.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkDownDocumentationDeprecationAttributeNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangMarkDownDeprecationDocumentation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/ProgramFileConstants.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocAttachmentInfo.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DocumentationTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/documentation_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#29660 Fix bug in predeclared qualified identifier parsing
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_01.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_02.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_01.json
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
Labels: Area/Parser, Team/CompilerFE

#29708 Enable option to initiate a lightweight LS instance
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
Labels: Team/LanguageServer

#29837 Add support for looking up path param symbols by node
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByServiceDeclTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#29850 Fix issue in XMLLexer when end GT is missing in XMLElement
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLLexer.java
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_source_03.bal
Labels: Area/Parser, Team/CompilerFE

#29295 Fix a few compiler crashing issues
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
Labels: Team/CompilerFE

#29830 Fix issue in parsing typed binding pattern
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/UnionTypeTest.java
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_assert_02.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_assert_02.json
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_01.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_02.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_03.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_04.bal
Labels: Area/Parser, Team/CompilerFE

#29841 Fix no error for remote method call action with non-remote methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/endpoint/ClientObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/endpoint/new/remote_basic_negative.bal
Labels: Team/CompilerFE

#29869 Fix completion Issues
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RightArrowActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config27.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/field_access_ctx_source21.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/field_access_ctx_source22.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source26.bal
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/remote_action_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/source/remote_action_source5.bal
Labels: Team/LanguageServer

#29832 Fix NPE when invoking lang-lib functions on semantically incorrect tables
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/tablelib_test_negative.bal
Labels: Area/Compiler, Lang/Tables, Team/CompilerFE

#29726 Normalize xml attribute values
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attributes.bal
Labels: Team/CompilerFE

#29673 Fix error duplication with tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BaseTestCase.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/negative/UnusedVarWithErrorTestCase.java
  tests/testerina-integration-test/src/test/resources/project-based-tests/unused-var-with-error-test/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/project-based-tests/unused-var-with-error-test/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/unused-var-with-error-test/tests/main_test.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#29770 Fix symbols dropped in match statement
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_lookup_in_match.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#29720 Decode record field name value
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/MapToRecordAssignabilityTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal
Labels: Team/CompilerFE

#29803 Update hashcode for `BFunction` type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFunctionType.java
Labels: Team/CompilerFE

#29733 Add `boolean|int|float|decimal|string` union support for expr of string template
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTemplateLiteralNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTemplateLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-template-literal-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-template-literal.bal
Labels: Team/CompilerFE

#29868 Improve performance of object set on initialization method
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
Labels: Team/jBallerina

#29820 Remove PureType from lang.array
  langlib/lang.array/src/main/ballerina/array.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test_negative.bal
Labels: Team/CompilerFE

#29785 Fix SO for equality check with cyclic union
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/CyclicTypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions-cyclic-negative.bal
Labels: Team/CompilerFE

#29934 Merge #29803 and #29733
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFunctionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/function/AnyFunctionTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTemplateLiteralNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTemplateLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/function/test_any_function_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-template-literal-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-template-literal.bal
Labels: Team/CompilerFE

#29931 Fix issue in recovering var decl statement with complex binding pattern
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_07.json
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_42.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_09.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_12.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_13.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_09.bal
Labels: Area/Parser, Team/CompilerFE

#29155 Add support for writing multiple xml items in xml template expression
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/XmlFactory.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_method_gen.bal
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/InstructionEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangXMLSequenceLiteral.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration_negative.bal
Labels: Team/CompilerFE

#29681 Fix issue with different field visibility qualifiers in object inclusions
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  misc/ballerina-bindgen/src/main/resources/templates/empty_jclass.bal
  misc/ballerina-bindgen/src/main/resources/templates/jclass.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/constructors.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/fields.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/methods.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTypeReferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_object_type_inclusion_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/object_type_inclusion_overrides.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/object_type_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_inclusion_with_qualifiers_negative.bal
Labels: Team/CompilerFE

#29899 Add update documentation warning for non-public functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/UpdateDocumentationTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/update-documentation/config/updateDocumentationConfig3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/update-documentation/source/updateDocumentation3.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_negative.bal
Labels: Team/CompilerFE

#29957 Fix xmllib_test.bal
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
Labels: Team/CompilerFE

#29874 Fix type descriptor as an expression parsing
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypesAsExprTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/MatchStatementTest.java
  compiler/ballerina-parser/src/test/resources/misc/types-as-expr/types_as_expr_assert_01.json
  compiler/ballerina-parser/src/test/resources/misc/types-as-expr/types_as_expr_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/types-as-expr/types_as_expr_source_01.bal
  compiler/ballerina-parser/src/test/resources/misc/types-as-expr/types_as_expr_source_02.bal
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_assert_03.json
  compiler/ballerina-parser/src/test/resources/statements/do-stmt/do_stmt_assert_07.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_09.json
  docs/bir-spec/src/test/resources/test-src/values.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/assert/ranges_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/assert/ranges_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/range-test-config.json
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/source/ranges_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/source/ranges_2.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/anydata-stamp-expr-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/negative/array-stamp-expr-negative-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/negative/json-stamp-expr-negative-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/negative/map-stamp-expr-negative-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/negative/object-stamp-expr-negative-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/negative/record-stamp-expr-negative-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/negative/tuple-stamp-expr-negative-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/union-stamp-expr-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/xml-stamp-expr-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_bir_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typedesc/typedesc_positive.bal
Labels: Area/Parser, Team/CompilerFE

#29880 If the attach-point is not provided, the argument provided for the name parameter of attach method should be ()
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ServiceDeclTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_attach_test.bal
Labels: Team/CompilerFE

#29865 Fix "No such record" error at runtime with configurable variable
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/configLibProject/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configLibProject/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configLibProject/Package.md
  tests/jballerina-integration-test/src/test/resources/configurables/configLibProject/lib.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configLibProject/modules/mod1/lib.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/mod1/mod1.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/mod2/mod2.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configurableCliProject/main/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/main/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/envVarPkg/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/invalidDefaultable/main/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/recordModuleProject/main/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testErrorProject/configPkg/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/Dependencies.toml
Labels: Team/jBallerina

#29973 Fix method flags not being set for readonly and class intersection
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ReadonlyObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/readonly_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/readonly_objects_negative.bal
Labels: Team/CompilerFE

#29788 Add BallerinaSymbol as a parent class of BallerinaMethodSymbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMethodSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaResourceMethodSymbol.java
Labels: Area/SemanticAPI, Team/CompilerFE, Team/LanguageServer

#29905 Fix subtyping rules with `never`
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkpanicexpr/CheckPanicExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/function/AnyFunctionTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_operator_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_semantics_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/function/test_any_function_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/function/test_any_function_type_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal
Labels: Team/CompilerFE

#29765 Fix issues in the bindgen mappings generated
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/BFunction.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JClass.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JConstructor.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JField.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JMethod.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JParameter.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenConstants.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenEnv.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenFileGenerator.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenMvnResolver.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenTreeModifier.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenUtils.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/BindgenUnitTest.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/FieldsTestResource.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/InterfaceTestResource.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/MethodsTestResource.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/RestrictedTestResource.java
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/Ballerina.toml
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/constructors.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/dependentClass.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/fields.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/innerClass.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/methods.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/moduleMapping.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/throwableMapping.bal
Labels: Area/Bindgen, Team/DevTools, Type/Bug

#29955 Fix lang-streams `CompletionType` related spec-deviations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  langlib/lang.query/src/main/ballerina/helpers.bal
  langlib/lang.query/src/main/ballerina/types.bal
  langlib/lang.stream/src/main/ballerina/internal.bal
  langlib/lang.stream/src/main/ballerina/stream.bal
Labels: Lang/Streams, Team/CompilerFE

#29675 Fix several issues with `ensureType` function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test_negative.bal
Labels: Team/CompilerFE

#29998 Fix the `withinBlock()` check in `PositionUtil`
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_service_decl_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#29982 Fix several issues related to unary expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/unaryoperations/UnaryExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/unaryoperations/unary-operation-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/unaryoperations/unary-operation.bal
Labels: Team/CompilerFE

#29792 Improve runtime anonymous type resolution
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ValueCreator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/TypeHashComparator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangAnonymousModelHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeHashVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BTypeSymbol.java
Labels: Team/CompilerFE, Team/jBallerina

#30007 Deprecate `typeParameter()` in `MapTypeSymbol` and introduce a new method with the correct return type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMapTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/MapTypeSymbol.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/completion/BLangRecordLiteralUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#29848 Add proper support for match statement and binding patterns
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BaseVisitor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/MapTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangMatchGuard.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangMatch.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangMatchStatement.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/BindingPatternTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInMatchStmtTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/statements/SymbolsInMatchStmtTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/binding_patterns_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_ref_match_stmt_context.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/statements/match_stmt.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#29908 Fix Rename issue for Cyclic unions
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/rename/RenameTest.java
  language-server/modules/langserver-core/src/test/resources/rename/expected/single/rename_with_cursor_at_end3.json
  language-server/modules/langserver-core/src/test/resources/rename/expected/single/rename_with_cursor_at_end4.json
  language-server/modules/langserver-core/src/test/resources/rename/sources/single/testSource.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/CyclicUnionRefsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_cyclic_unions.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFE, Team/LanguageServer

#29985 Update error message for invalid rest field inside inclusive record type desc
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_27.json
Labels: Area/Parser, Team/CompilerFE

#29872 Fix issues in isolation analysis
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedVariableTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_semantic_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables_isolation_negative.bal
Labels: Team/CompilerFE

#29059 Improve error constructor CET handling
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangErrorConstructorExpr.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibErrorTest.java
  langlib/langlib-test/src/test/resources/test-src/errorlib_error_ctor_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/RemoteObjectBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/endpoint/ClientObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/errorconstructorexpr/ErrorConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsAndNilTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableArguments.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/InitFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectInitializerTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExpressionIterableObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/SimpleQueryExpressionWithDefinedTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleErrorVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAnyActionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFlushTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerSyncSendTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_client_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/endpoint/TestEndpointProject/pkg-b.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_operator_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/errorconstructorexpr/error-constructor-expr-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/errorconstructorexpr/error-constructor-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions-with-nil/functions_with_nil_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_init_project/object-initializer.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-exp-iterable-objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/fail/fail-statement.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/flush-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/sync-send.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-for-any-actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Team/CompilerFE

#29922 Implement isolated inference - phase I
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/EvaluatorMiscTest.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/EmitterUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByServiceDeclTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bir/BirVariableOptimizationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationInferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/mapInits
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference_isolation_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference_type_checking_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/function/test_any_function_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typedesc/typedesc_positive.bal
Labels: Team/CompilerFE

#29752 Improve same type check for ordered types in relational expressions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueComparisonUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/GreaterLessThanOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/greater-less-than-operation-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/greater-less-than-operation.bal
Labels: Team/CompilerFE

#29814 Improve diagnostics and support for `never` type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachRecordTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-record-typed-binding-patterns.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type-runtime.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal
Labels: Team/CompilerFE

#29835 Fix issue with wildcard match pattern when the type of the matched `action-or-expr` includes `error`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtErrorMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtListMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/error_match_pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/list-match-pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/mapping-match-pattern.bal
Labels: Team/CompilerFE

#30024 Block mapping binding in foreach and query for anydata and any type collections
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachNegativeTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-semantics-negative.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/finaltypes/final-typed-binding-patterns-negative.bal
Labels: Team/CompilerFE

#29937 Improve the java cast function
  langlib/jballerina.java/src/main/ballerina/ballerina_values_to_Java.bal
  langlib/jballerina.java/src/main/java/org/ballerinalang/langlib/java/Cast.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/java_cast_test.bal
Labels: Area/JavaInterop, Team/DevTools, Type/Improvement

#29959 [LS] Add support for collecting feature usage statistics via telemetry
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/spi/LSCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/module-info.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSClientLogger.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSTelemetry.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementMethodCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/MarkAsUntaintedCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TypeGuardCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleInsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/IgnoreReturnCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/AddAllDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/AddDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/UpdateDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/OptimizeImportsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/PullModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/ReportFeatureUsageExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/telemetry/LSErrorTelemetryEvent.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/telemetry/LSFeatureUsageTelemetryEvent.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/telemetry/LSTelemetryEvent.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/telemetry/TelemetryUtil.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeAction.java
Labels: Team/LanguageServer

#29921 Add compilation checks for command line parsing
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/cli/CliSpec.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/cli/CliUtil.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/cli/Option.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/cli/OperandTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/cli/OptionTest.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/MainFunctionValidator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/MainParameterVisitor.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/MainFunctionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/OperandCompilationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/OptionCompilationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/FunctionCallTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/operand/invalid.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/operand/invalid_array.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/operand/successful.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/operand/successful_array.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/options/invalid.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/options/successful.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/without_public.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/expressions/func_call.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/expressions/func_call_negative.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#30014 Add const expr support for bitwise operations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-expression.bal
Labels: Team/CompilerFE

#30031 Allow access on grouped expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangBinaryExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangCheckedExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangElvisExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangIntRangeExpression.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangRawTemplateLiteral.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangStringTemplateLiteral.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTernaryExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTypeConversionExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangUnaryExpr.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/AccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/access.bal
Labels: Team/CompilerFE

#30036 Fix module init not running for tests when there are warnings or hints
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecated_construct_usage_with_warning.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type_guard_with_always_true_hint.bal
Labels: Team/CompilerFE

#28846 Improve generateDependencyList performance
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
Labels: Team/jBallerina

#30012 Fix issue in finding module prefix references in annotations
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindModulePrefixRefsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_module_prefix.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testproject/annotations.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testproject/type_defs.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#29909 Restrict calling langlib functions for objects
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  docs/bir-spec/src/test/resources/test-src/values.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromBalString_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_toBalString_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinfunctions/FreezeAndIsFrozenTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/StampInbuiltFunctionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects_type_reference_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_readonly_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/object_type_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion--compile-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-success.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/negative/object-stamp-expr-negative-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/java_cast_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_langlib_function_invocation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_langlib_inclusion.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/bstring-tostring-test.bal
Labels: Team/CompilerFE

#28960 Remove BLangCompilerException with a warning for invalid settings
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PullCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/SearchCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/CentralUtils.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/utils/TestCentralUtils.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/BallerinaUserHome.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/exceptions/SettingsTomlException.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/parser/SettingsProcessor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/TomlParserUtils.java
  compiler/ballerina-lang/src/test/java/org/ballerinalang/toml/InvalidSettingsTomlTest.java
  compiler/ballerina-lang/src/test/resources/invalid-settings.toml
Labels: Area/ProjectAPI, Team/DevTools

#29940 Improve package version selection algorithm
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/SemanticVersion.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/DependencyVersionKind.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/SemanticVersionTests.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/VersionConflictResolutionTests.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/BaseTest.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PreReleaseVersionResolutionTests.java
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/balas/missing_transitive_deps/samjs-package_k-any-1.0.0.bala
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/balas/missing_transitive_deps/samjs-package_kk-any-1.0.0.bala
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_l_with_stable_dep/Dependencies.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_m_with_unstable_transitive_dep/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_m_with_unstable_transitive_dep/Dependencies.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_m_with_unstable_transitive_dep/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_missing_transitive_dep/Dependencies.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_missing_transitive_dep/main.bal
Labels: Area/ProjectAPI, Team/Tooling

#29997 Remove locking pre-release versions from Dependencies.toml
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/SemanticVersion.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java
Labels: Area/ProjectAPI, Team/DevTools

#30043 Fix record hash mismatch
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeHashVisitor.java
Labels: Team/CompilerFE

#29977 Address TODO for UnicodePatternSyntaxChar check in Lexer
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/basics.quoted.json
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/misc/identifiers/unicode_char_identifier_assert.json
  compiler/ballerina-parser/src/test/resources/misc/identifiers/unicode_char_identifier_source.bal
  compiler/ballerina-parser/src/test/resources/trivia/trivia_assert_02.json
  compiler/ballerina-parser/src/test/resources/trivia/trivia_source_02.bal
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationBaseTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/variable-tests/main.bal
Labels: Area/Parser, Team/CompilerFE

#30055 Improve parseing expression RHS
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ServiceDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_20.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_20.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/Parser, Team/CompilerFE

#30063 Handle global function pointer as global variable in dataflow analyzer
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/cyclefind/GlobalVariableRefAnalyzer.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/global-function-pointers.bal
Labels: Team/CompilerFE

#30071 Fix record intersection and type checking with never rest type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Team/CompilerFE

#30067 Fix predeclared-qualifier parsing in xmlns-decl
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_01.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_02.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_01.json
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
Labels: Area/Parser, Team/CompilerFE

#29668 Handle data mapper codeaction failing scenarios
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeAction.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/DataMapperNodeVisitor.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/utils/DefaultValueGenerator.java
  misc/ballerinalang-data-mapper/src/test/java/org/ballerinalang/datamapper/codeaction/CodeActionTest.java
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper11.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper12.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper13.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper14.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper15.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper16.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper17.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper2.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper3.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper4.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/dataMapper6.json
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/source/dataMapper11.bal
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/source/dataMapper12.bal
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/source/dataMapper13.bal
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/source/dataMapper14.bal
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/source/dataMapper15.bal
  misc/ballerinalang-data-mapper/src/test/resources/codeaction/source/dataMapper17.bal
Labels: Area/CodeAction, Team/LanguageServer

#30099 Fix incorrect type symbol setting issue for BLangTypeInit nodes
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction41.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByClassTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_class_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30076 Fix type test record intersection with default values and add tests for invalid cyclic record type inclusion
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/ClosedRecordTypeReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/OpenRecordTypeReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record_type_reference_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_reference_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Team/CompilerFE

#30096 Improve the error which gives, when it passes `string` to `decimal:fromString` function
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/constants/RuntimeConstants.java
  bvm/ballerina-runtime/src/main/java/module-info.java
  langlib/lang.decimal/src/main/java/org/ballerinalang/langlib/decimal/FromString.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibDecimalTest.java
  langlib/langlib-test/src/test/resources/test-src/decimallib_test.bal
Labels: Team/CompilerFE

#30082 Fix casting issue with immutable-typed fields of record type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ReadonlyRecordFieldTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal
Labels: Team/CompilerFE

#30119 Fix NPE when calling closures within resource functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closures_in_resource.bal
Labels: Team/CompilerFE

#30132 Fix configurable-module-var-decl recovery against EOF token
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_15.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_15.bal
Labels: Area/Parser, Team/CompilerFE

#30154 Fix incorrect type symbol setting issue for BLangTypeInit nodes
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction41.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByClassTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_class_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30104 Mark package as java if platform libs are given in `Ballerina.toml`
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-project-with-platform-libs.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-project-with-platform-libs.txt
  cli/ballerina-cli/src/test/resources/test-resources/validProjectWithPlatformLibs/Ballerina.toml
  cli/ballerina-cli/src/test/resources/test-resources/validProjectWithPlatformLibs/libs/one-1.0.0.jar
  cli/ballerina-cli/src/test/resources/test-resources/validProjectWithPlatformLibs/main.bal
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBalaWriter.java
Labels: Area/ProjectAPI, Team/DevTools

#30177 Add a version of `references()` for getting references without definition location
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/AnnotationRefsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/CyclicUnionRefsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindModulePrefixRefsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsAcrossFilesTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInLambdasTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInMatchStmtTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInServiceDeclTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInTestsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInWorkersTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/XMLRefsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_cyclic_unions.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30201 Add test to cover querying error detail and cause using query-expr
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/ErrorQueryTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_expr_with_errors.bal
Labels: Lang/Errors, Lang/Streams, Team/CompilerFE

#30188 Invalidate more type descriptors after rest descriptor in typle type desc
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_20.json
  compiler/ballerina-parser/src/test/resources/expressions/error-constructor-expr/error_constructor_expr_assert_04.json
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_assert_04.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
Labels: Area/Parser, Team/CompilerFE

#30224 Create user defined type for `distinct error`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error_intersection_type.bal
Labels: Team/CompilerFE

#30223 Add an API for getting the annots attached to return types of functions
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/FunctionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JBIRFunction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BInvokableTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/ProgramFileConstants.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/FunctionSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/function_symbols_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#29884 Add variable location to config variable error messages
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigResolver.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/VariableKey.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/exceptions/ConfigException.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliConfigException.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigToml.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlConfigException.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlContentProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlFileProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/Utils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/diagnostics/Diagnostic.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/diagnostics/RuntimeDiagnostic.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/diagnostics/RuntimeDiagnosticLocation.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/diagnostics/RuntimeDiagnosticLog.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BLangExceptionHelper.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/RuntimeDiagnosisTests.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/CliConfigProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/ConfigTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/CliProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  langlib/lang.array/build.gradle
  langlib/lang.value/build.gradle
  langlib/lang.xml/build.gradle
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
Labels: Team/jBallerina

#30192 Fix "Incorrect error with object that is both an Iterator and an Iterable"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachIterableObjectTest.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-iterable-objects.bal
Labels: Team/CompilerFE

#30243 Fix new expression suggestions for module variables
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/CheckExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config5.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config6.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config7.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config8.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/source/source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/source/source6.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/source/source7.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/source/source8.bal
Labels: Team/LanguageServer

#30126 Add 'this' to the local variable table.
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
Labels: Team/jBallerina

#29902 Add exit codes for errors in central related commands
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PullCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/SearchCommand.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/PullCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/PushCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/SearchCommandTest.java
Labels: Area/ProjectAPI, Team/DevTools

#30258 Send access token if available in all central commands
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PullCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/SearchCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/CentralUtils.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/utils/TestCentralUtils.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java
  cli/central-client/src/test/java/org/ballerinalang/central/client/TestCentralApiClient.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/RemotePackageRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java
Labels: Area/Central, Area/ProjectAPI, Team/DevTools
