Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-08, with the labels that each got.

#31975 Fix NPE when referring to a listener declaration
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationInferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference_flags.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference_with_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference_with_objects_runtime_negative_2.bal
Labels: Team/CompilerFE

#31968 Fix field symbol position issue in intersected record types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/FieldSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/field_symbols_test.bal
Labels: Area/SemanticAPI, Team/CompilerFETools

#31970 Fix `2.toString()` and `<-3>-3` parsing
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/AccessExpressionsTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/TypeCastExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/method_call_expr_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/method_call_expr_source_01.bal
  compiler/ballerina-parser/src/test/resources/expressions/type-cast-expr/type_cast_expr_assert_20.json
  compiler/ballerina-parser/src/test/resources/expressions/type-cast-expr/type_cast_expr_source_20.bal
Labels: Area/Parser, Team/CompilerFE

#31684 Introduce !is operator
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTypeTestExpr.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/IsExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/UnaryExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_08.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_09.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_10.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_11.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_assert_12.json
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_source_09.bal
  compiler/ballerina-parser/src/test/resources/expressions/is-expr/is_expr_source_12.bal
  compiler/ballerina-parser/src/test/resources/expressions/unary-expr/unary_expr_assert_12.json
  compiler/ballerina-parser/src/test/resources/expressions/unary-expr/unary_expr_assert_13.json
  compiler/ballerina-parser/src/test/resources/expressions/unary-expr/unary_expr_source_13.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/NegativeTypeTestExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/negative-type-test-expr-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/negative-type-test-expr.bal
Labels: Team/CompilerFE

#31818 Fix issues with string unescaping
  bvm/ballerina-runtime/build.gradle
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/IdentifierUtils.java
  bvm/ballerina-runtime/src/main/java/module-info.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  gradle/javaProject.gradle
  misc/toml-parser/build.gradle
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTemplateLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/UnicodeNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/UnicodeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-template-literal.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/unicode.bal
Labels: Team/CompilerFE

#31927 Update string index access return type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringValueBasicsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-value-test.bal
Labels: Team/CompilerFE

#31801 Add xml type support for configurable TOML configuration
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigResolver.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/Utils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/negative/Empty.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/UnionAmbiguousType.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_xml.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configComplexXml/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configComplexXml/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configComplexXml/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/configUnionTypes/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/configUnionTypes/modules/imported_unions/imported_unions.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/configUnionTypes/modules/type_defs/type_defs.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/configUnionTypes/modules/union_ambiguity/union_ambiguity.bal
Labels: Team/jBallerina

#31723 Fix Error Message for Accessing Incorrect Field Name of Closed Records
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DiagnosticsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/AccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionWithIncludedRecordParam.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal
Labels: Team/CompilerFE, Team/CompilerFETools

#31989 Fix CCE when check is used in a let expression in a field initializer
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_field_initializer_with_check_negative.bal
Labels: Team/CompilerFE

#31929 [Shell] Update `\help TOPIC` command
  ballerina-shell/modules/shell-cli/build.gradle
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/PropertiesLoader.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/handlers/HelpCommand.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/handlers/help/BbeHelpProvider.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/handlers/help/BbeRecord.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/handlers/help/BbeTitle.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/handlers/help/BbeTopicsProvider.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/handlers/help/RemoteBbeHelpProvider.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/JlineSimpleCompleter.java
  ballerina-shell/modules/shell-cli/src/main/java/module-info.java
  ballerina-shell/modules/shell-cli/src/main/resources/commands.help.topics.txt
  ballerina-shell/modules/shell-cli/src/main/resources/shell.properties
Labels: Area/Shell, Team/CompilerFETools

#31990 Fix Symbol Position of SimpleNameReferenceNode
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_position_test.bal
Labels: Area/SemanticAPI, Team/CompilerFETools

#31675 Allow enum declarations to have duplicate members reusing same constants
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/enums/EnumTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/enums/enums-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/enums/enums.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal
Labels: Team/CompilerFE

#31882 Fix string:char iterator for large codepoints
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BString.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/BmpStringValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/CharIterator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/NonBmpStringValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/StringValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/TypeEmitter.java
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/Next.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringUtilsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-utils.bal
Labels: Team/jBallerina

#31969 Fix NPE in Desugar
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_operator_basics.bal
Labels: Team/CompilerFE

#31926 Support narrowing variables defined in let clause
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Team/CompilerFE

#31996 Add check for function type parameters in `SymbolFactory.getBCompiledSymbol`
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/function_call_expression_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/function_call_expression_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/assignment_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/assignment_stmt_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_ctx_config15.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ParameterSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/param_symbols_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32030 [Sematic API] Fix CCE when Enum is Used in a Type Definition
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32043 [Shell] Update shell invalid command message
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java
Labels: Team/CompilerFETools, Area/Shell

#31892 Fix cloneReadonly behavior for recursive tuple
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTupleType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/tuple-type-definitions-cyclic.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
Labels: Team/CompilerFE

#32068 Add API to get the syntax tree from a given context
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxTree.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/TreeTraversalAPITest.java
Labels: Team/CompilerFE, Area/SyntaxAPI

#31820 Handle array size greater than 2,147,483,637 issue
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArraySizeDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_size_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_size_test_negative.bal
Labels: Team/CompilerFE

#31982 Prevent unresolved user defined types causing NPE
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
Labels: Team/CompilerFE

#31997 [LS] Refactor language client capability usages to honor optional capabilities
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/RenameContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/LSClientUtil.java
Labels: Team/LanguageServer

#31836 Fix issues with using expressions of `never` type
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-record-typed-binding-patterns.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkpanicexpr/CheckPanicExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/never_type_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/different_function_signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_operator_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_semantics_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkpanicexpr/check_panic_expr_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkpanicexpr/check_panic_expr_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never_type_runtime.bal
Labels: Team/CompilerFE

#31731 Fix distinct type spec deviations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangAnonymousModelHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTypeIdSet.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  langlib/lang.typedesc/src/main/java/org/ballerinalang/langlib/typedesc/TypeIds.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/TypeIds.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTypedescTest.java
  langlib/langlib-test/src/test/resources/test-src/typedesclib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/DistinctTypeDefTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/distinct-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/distinct_error_intersection_negative.bal
Labels: Team/CompilerFE, Lang/Distinct

#32088 Fix Class cast exception try to get clone readonly type with enum
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/Type.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal
Labels: Team/jBallerina

#32116 Fix invalid function type qualifier stored location in ST
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/ErrorTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/FunctionTypeTest.java
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_18.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_18.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/function/AnyFunctionTypeTest.java
Labels: Team/CompilerFE, Area/Parser

#31840 Relax static type requirements for == and !=
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/XmlFactory.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlComment.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlPi.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/ConfigTest.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/http/sample/SerializeComplexXmlTestCase.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation_negative.bal
Labels: Team/CompilerFE

#31985 Fix issues parsing xml keyword in expression context
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/ArrayTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/OptionalTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/ParameterizedTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/ParenthesisedTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/SingletonTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/StreamTypeTest.java
  compiler/ballerina-parser/src/test/resources/actions/start-action/start_action_assert_04.json
  compiler/ballerina-parser/src/test/resources/actions/wait-action/wait_action_assert_04.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_29.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_30.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_09.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_07.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_09.json
  compiler/ballerina-parser/src/test/resources/expressions/let-expr/let_expr_assert_06.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_08.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_13.json
  compiler/ballerina-parser/src/test/resources/expressions/mapping-constructor/mapping_constructor_assert_14.json
  compiler/ballerina-parser/src/test/resources/expressions/new-expr/new_expr_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_23.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_49.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_50.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_65.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_66.json
  compiler/ballerina-parser/src/test/resources/expressions/string-template/string_template_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/type-cast-expr/type_cast_expr_assert_12.json
  compiler/ballerina-parser/src/test/resources/expressions/type-cast-expr/type_cast_expr_assert_15.json
  compiler/ballerina-parser/src/test/resources/expressions/unary-expr/unary_expr_assert_09.json
  compiler/ballerina-parser/src/test/resources/expressions/unary-expr/unary_expr_assert_10.json
  compiler/ballerina-parser/src/test/resources/expressions/unary-expr/unary_expr_assert_11.json
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_14.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_03.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_05.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_07.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_08.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_09.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_10.json
  compiler/ballerina-parser/src/test/resources/misc/types-as-expr/types_as_expr_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/types-as-expr/types_as_expr_source_02.bal
  compiler/ballerina-parser/src/test/resources/statements/compound-assignment-stmt/compound_assignment_stmt_assert_10.json
  compiler/ballerina-parser/src/test/resources/statements/if-else/if_else_assert_05.json
  compiler/ballerina-parser/src/test/resources/statements/panic-stmt/panic_stmt_assert_5.json
  compiler/ballerina-parser/src/test/resources/statements/return-stmt/return_stmt_assert_4.json
  compiler/ballerina-parser/src/test/resources/statements/transaction-stmt/rollback_stmt_assert_02.json
  compiler/ballerina-parser/src/test/resources/types/parenthesised-type/parenthesised-type_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/parenthesised-type/parenthesised-type_assert_02.json
  compiler/ballerina-parser/src/test/resources/types/parenthesised-type/parenthesised-type_source_01.bal
  compiler/ballerina-parser/src/test/resources/types/parenthesised-type/parenthesised-type_source_02.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/start/StartActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementSyntaxErrorsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/VarDeclrSemanticTest.java
Labels: Team/CompilerFE, Area/Parser

#31546 Fix runtime SO related to filler value check with recursive tuples
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/CyclicTypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/tuple-type-definitions-cyclic.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions-cyclic-negative.bal
Labels: Team/CompilerFE

#31934 Add diagnostic for unhandled exception from compiler
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/CompilerPhaseRunner.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/CompilerBadSadDiagnostic.java
Labels: Team/CompilerFE

#32089 Remove the "this function can be marked as isolated" warning logged for ballerina/ballerinax modules
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticWarningCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
Labels: Team/CompilerFE

#32000 Fix issue when a referred constant cannot be resolved
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal
Labels: Team/CompilerFE

#31900 Decode typename at compile time
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/TypeCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
Labels: Team/jBallerina

#32037 Improve self variable reference check
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/let/LetExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/TupleVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/var/VarDeclaredAssignmentStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/tuple-variable-reference-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/var/var-duplicate-variable-ref-lhs-negative.bal
Labels: Team/CompilerFE

#32165 Fix issue in parsing nil literal inside match guard
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/NilLiteralTest.java
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/nil_literal_assert_11.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/nil_literal_source_11.bal
Labels: Team/CompilerFE, Area/Parser

#31874 Fix 'fromCodePointInt() should return error for invalid codePoints' and 'Char' /'String' incompatibility in langlib calls on literals
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/FromCodePointInt.java
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/FromCodePointInts.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibSubTypeTest.java
  langlib/langlib-test/src/test/resources/test-src/subtypes/char_subtypes_test.bal
Labels: Team/CompilerFE

#32103 Relax query expression keywords
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractTokenReader.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/KeywordMode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/TokenReader.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/incremental/HybridTokenReader.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/AccessExpressionsTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/IdentifierTest.java
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_16.json
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/annot_access_expr_assert_11.json
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/optional_field_access_expr_assert_08.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object_constructor_assert_11.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object_constructor_source_11.bal
  compiler/ballerina-parser/src/test/resources/misc/identifiers/keywords_as_identifiers_assert.json
  compiler/ballerina-parser/src/test/resources/misc/identifiers/keywords_as_identifiers_source.bal
  compiler/ballerina-parser/src/test/resources/statements/do-stmt/do_stmt_assert_07.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_07.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_13.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_07.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_13.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/StringQueryExpressionTest.java
Labels: Team/CompilerFE, Area/Parser

#31725 Implement pull module code action
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/ExecuteCommandContext.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/capability/InitializationOptions.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/capability/LSClientCapabilities.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSClientCapabilitiesImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSContextOperation.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/PullModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/PullModuleExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/ExecuteCommandContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/AbstractExtendedLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/task/BackgroundTaskService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/task/Task.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/task/TaskExecutionException.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/PullModuleCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/PullModuleExecutorTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/config/packagePull1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/config/packagePull2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/config/packagePull3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/config/packagePull4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/source/packagePull.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/source/packagePull2.bal
  language-server/modules/langserver-core/src/test/resources/command/pull-module/source/pull_module_source1.bal
  language-server/modules/launchers/stdio-launcher/src/main/java/org/ballerinalang/langserver/launchers/stdio/Main.java
Labels: Team/LanguageServer

#32071 Fix floating point numerical comparisons
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibDecimalTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibFloatTest.java
  langlib/langlib-test/src/test/resources/test-src/decimallib_test.bal
  langlib/langlib-test/src/test/resources/test-src/floatlib_test.bal
Labels: Team/jBallerina

#32164 Fix record type inclusion with finite type field
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/ClosedRecordTypeInclusionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record_type_inclusion.bal
Labels: Team/jBallerina

#32167 Fix issue with query expression constructing a table with no contexually expected type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExpressionWithVarTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-var-type.bal
Labels: Team/CompilerFE

#32128 Fix CCE when value:ToJson fails
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/ToJson.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#32106 Remove duplicated stack trace elements from error cause stack traces
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/PrintableStackTraceTest.java
Labels: Team/jBallerina

#32178 Refactor manifest API methods and change dependency resolution types
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DependencyManifest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DependencyResolutionType.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DocumentContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageManifest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ResolvedPackageDependency.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ModuleLoadRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BalaFiles.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ManifestBuilder.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/BallerinaTomlTests.java
Labels: Points/0.25, Area/ProjectAPI, Area/BuildTools

#32166 Record ballerina dist short version in `Ballerina.toml`
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/CommandUtil.java
  cli/ballerina-cli/src/main/resources/new_cmd_defaults/manifest-lib.toml
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/InitCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageManifest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BalaFiles.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ManifestBuilder.java
Labels: Area/ProjectAPI, Area/BuildTools

#32045 Improve runtime function parameter API
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/FunctionType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/Parameter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/RemoteMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ResourceMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/StringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFunctionType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BRemoteMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BResourceMethodType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetFilterFunc.java
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetMapFunc.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/ObjectMock.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPITest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_service_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/types/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/types/modules/objects/objects.bal
  tests/observability-test-utils/src/main/java/org/ballerina/testobserve/listenerendpoint/Resource.java
Labels: Team/jBallerina

#32207 Improve version conflict resolution logic
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ResolutionResponseDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BlendedManifest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/NewPackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ResolutionEngine.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/FileSystemRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/LocalPackageRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/VersionConflictResolutionTests.java
  tests/jballerina-integration-test/src/test/resources/packaging/versions/websub/Dependencies.toml
Labels: Area/ProjectAPI

#32184 Set textRange information to BLangNode
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java
Labels: Team/CompilerFE

#32200 Fix Variable Definition Node Position of `OnFailClauseNode`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
Labels: Team/CompilerFETools, Team/CompilerFE, Area/SemanticAPI, Area/AST

#32082 Add spec conformance tests for type descriptors
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/FunctionTypeSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ObjectTypeSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ParameterSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/RecordTypeSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/function_type_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/object_type_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/record_type_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/type_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#32186 Fix issue with match expression var name used in desugar
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/CompilerFE

#32192 Pass compilation options to package compilation
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Package.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
Labels: Area/ProjectAPI, Area/BuildTools

#32143 Fix toString() method for tuples
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/values.tuples.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.tuples.json
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/StringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BalStringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachMapTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachRecordTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromBalString_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromJson_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_toBalString_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementStaticPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredErrorPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredTuplePatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/BStringToStringTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleRestDescriptorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/error_match_pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/error_binding_pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/union-type-definitions-cyclic.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_key_field_value_test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/assertions-diff-error/tests/assertions-diff-error-messages.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/assertions-error-messages/tests/assertions-error-messages.bal
Labels: Team/jBallerina

#31794 Fix issue when an object constructor is part of a type cast expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/function/AnyFunctionTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/var/VarDeclaredAssignmentStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/function/test_any_function_type_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/var/var-type-assign-stmt.bal
Labels: Team/CompilerFE

#32217 [LS]Fix renaming NPE
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/RenameContextImpl.java
Labels: Team/LanguageServer

#32126 Fix type resolving issue with both Elvis and Ternary operators
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/elvis/ElvisExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/ternary/TernaryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/elvis/elvis-expr-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/elvis/elvis-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal
Labels: Team/CompilerFE

#32199 Remove return statement from LVT
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
Labels: Team/jBallerina

#32144 Fix wrong owner of the symbols in user-defined stream types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testprojmodules/Ballerina.toml
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testprojmodules/main.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testprojmodules/modules/module1/module1.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32127 Reset type narrowing for all assignments to a variable of a narrowed type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/IfElseStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/if-stmt-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Team/CompilerFE

#32229 Add expression always false hint for `!is` operator
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/NegativeTypeTestExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/negative-type-test-expr-negative.bal
Labels: Team/CompilerFE

#32105 Fix `typeof` expression providing wrong outputs
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BMap.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BRefValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/FPValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/FutureValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/HandleValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/IteratorValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/StreamValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TypedescValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlComment.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlPi.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlQName.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlValue.java
  langlib/lang.error/src/main/java/org/ballerinalang/langlib/error/StackTrace.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MemberAccessExpressionEvaluator.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/utils/EvaluationUtils.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BJson.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BMap.java
  misc/debug-adapter/modules/debug-adapter-runtime/src/main/ballerina/utils.bal
  misc/debug-adapter/modules/debug-adapter-runtime/src/main/java/org/ballerinalang/debugadapter/runtime/DebuggerRuntime.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/GenericMockObjectValue.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/ControlFlowDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationNegativeTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typeof/TypeofOverLiteralExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor_infer_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typeof/typeof.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/tuple-variable-reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typedesc/typedesc_positive.bal
Labels: Team/jBallerina

#32228 Fix float:fromHexString
  langlib/lang.float/src/main/java/org/ballerinalang/langlib/floatingpoint/FromHexString.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibFloatTest.java
  langlib/langlib-test/src/test/resources/test-src/floatlib_test.bal
Labels: Team/jBallerina

#32046 [Semantic API] Add Support for Markdown Documentation Parameter Symbol Lookup
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DocumentationTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/documentation_symbol_position_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_position_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32238 [LS] Add sticky build option in ws manager
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Team/LanguageServer

#32243 Add 'distribution' to ballerina toml spec
  compiler/ballerina-lang/src/main/resources/ballerina-toml-schema.json
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/BallerinaTomlTests.java
  compiler/ballerina-lang/src/test/resources/ballerina-toml/valid-ballerina.toml
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/toml/ballerinatoml/completion/BallerinaTomlCompletionTest.java
  language-server/modules/langserver-core/src/test/resources/toml/ballerina_toml/completion/config/table_context/config1.json
  language-server/modules/langserver-core/src/test/resources/toml/ballerina_toml/completion/config/table_context/config2.json
Labels: Points/0.25, Area/ProjectAPI, Area/BuildTools

#32248 Handle immutable typedesc within toStream
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Team/CompilerFE

#32251 Fix BIR symbol enter failing when multiple dependencies define a read-only intersection with the same record
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/readonly/ReadOnlyIntersectionViaMultipleModulesTest.java
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_bar/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_bar/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_bar/Package.md
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_bar/constructs.bal
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_baz/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_baz/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_baz/Package.md
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_baz/constructs.bal
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_foo/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_foo/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_foo/Package.md
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_foo/constructs.bal
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_qux/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_qux/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_qux/Package.md
  tests/jballerina-integration-test/src/test/resources/packaging/readonly/test_project_immutable_qux/constructs.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#32179 Fix incorrect results for the equality of floating points with non-simple types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
Labels: Team/jBallerina

#32260 Refactor PackageRepository classes and prepare them for unit tests
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/EnvironmentBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageMetadataResponse.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ResolutionRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/NewPackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ResolutionEngine.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/AbstractPackageRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/FileSystemRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/LocalPackageRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/RemotePackageRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/RemotePackageRepositoryTests.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/VersionConflictResolutionTests.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/connector/BallerinaConnectorServiceImpl.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/DependencyGraphTests.java
Labels: Area/ProjectAPI

#32281 Introducing the package resolution test framework
  compiler/ballerina-lang/build.gradle
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ResolutionEngine.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/AbstractPackageResolutionTest.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/ResolutionWithNoDepsTomlTest.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/Constants.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/DefaultPackageRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/DotGraphUtils.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/GraphComparisonResult.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/GraphUtils.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/LocalPackageRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/PackageContainer.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/PackageRepositoryBuilder.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/PackageResolutionTestCase.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/PackageResolutionTestCaseBuilder.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/RepositoryKind.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/TestCaseFilePaths.java
  compiler/ballerina-lang/src/test/resources/package-resolution/suite-001/case-0001/app.dot
  compiler/ballerina-lang/src/test/resources/package-resolution/suite-001/case-0001/dependencies.dot
  compiler/ballerina-lang/src/test/resources/package-resolution/suite-001/case-0001/expected-graph-nosticky.dot
  compiler/ballerina-lang/src/test/resources/package-resolution/suite-001/case-0001/expected-graph-sticky.dot
  compiler/ballerina-lang/src/test/resources/package-resolution/suite-001/case-0001/repositories/central.dot
  compiler/ballerina-lang/src/test/resources/package-resolution/suite-001/case-0001/repositories/dist.dot
  compiler/ballerina-lang/src/test/resources/package-resolution/suite-001/case-0001/repositories/local.dot
  gradle/javaProject.gradle
Labels: Area/ProjectAPI

#32210 Fix the Xml iterator next value changes between next invocations of the same iterator
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BXml.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlValue.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Next.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
Labels: Team/jBallerina

#32325 Move union creation to a different class and split union population methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmUnionTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmAnnotationsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmBStringConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/enums/bigEnum.bal
Labels: Team/jBallerina

#32328 Implement uniqueId for `ServiceDeclarationSymbol`
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaServiceDeclarationSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  langlib/lang.annotations/src/main/ballerina/annotations.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments.bal
Labels: Team/CompilerFE

#32292 Add toString() for runtime finite type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFiniteType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type_cast_expr.bal
Labels: Team/jBallerina

#32108 [LS] Refactor `getDefaultValueForType` API
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractImplementMethodCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonKeys.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CreateFunctionCommandExecTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/implement-all/config/implementAllObj1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/implement-all/config/implementAllObj2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/implement-all/source/implementAllObj.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/implement-functions/config/implementFuncObj1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/implement-functions/config/implementFuncObj2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/implement-functions/config/implementFuncObj3.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/createUndefinedFunction17.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/createUndefinedFunction18.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_which_returns_record2.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/createUndefinedFunction7.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/createUndefinedFunction8.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config37.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config45.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config46.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config47.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source45.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source46.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source47.bal
Labels: Team/LanguageServer

#32428 Update resolution algorithm to consider locked dependencies in "Dependencies.toml" file
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ResolutionEngine.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/AllInOneResolutionTests.java
  compiler/ballerina-lang/src/test/resources/package-resolution/suite-all_in_one/case-0002/app.dot
Labels: Area/ProjectAPI

#32379 [LS] Update pull module to use new compilation API
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/capability/InitializationOptions.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSClientCapabilitiesImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/PullModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/PullModuleExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/task/BackgroundTaskService.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/config/packagePull1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/config/packagePull2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/config/packagePull3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/pull-module/config/packagePull4.json
Labels: Team/LanguageServer

#32433 Fix clearing diagnostics of unrelated projects
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
Labels: Team/LanguageServer

#32315 Fix source pruning when getting ST from expression context
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STBalPartNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STTreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/parser/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/parser/diagnostics/DiagnosticWarningCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/BalPartNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxTree.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/java/module-info.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/SyntaxTreeJSONGenerator.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/diagnostics/DiagnosticCodeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/errorhandler/ErrorHandlerValidationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/actions/AbstractActionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/AbstractDeclarationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/AbstractExpressionsTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/AbstractMiscTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/AbstractStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/trivia/AbstractTriviaTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/AbstractTypesTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/DiagnosticsAPITest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/TreeTraversalAPITest.java
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
Labels: Team/CompilerFE, Area/SyntaxAPI

#32449 Fix issue with invalid qualifier order
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/VarDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/statements/var-decl-stmt/local_var_decl_assert_16.json
  compiler/ballerina-parser/src/test/resources/statements/var-decl-stmt/local_var_decl_source_16.bal
Labels: Team/CompilerFE, Area/Parser

#32095 Fix compiler crash due to overriden record type inclusion
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/TypeNameWithSpecialCharsBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/TypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/record-type-field-resolving.bal
Labels: Team/CompilerFE

#32455 Improve BALA graph resolution logic
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DependencyGraph.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ResolutionRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ResolutionResponse.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ResolutionEngine.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/VersionConflictResolutionTests.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/PackageResolutionTestCase.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/connector/BallerinaConnectorServiceImpl.java
Labels: Area/ProjectAPI

#32451 Fix clone readonly issue in records with enums
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal
Labels: Team/jBallerina

#32447 Add common BDD ops
  semtypes/spotbugs-exclude.xml
  semtypes/src/main/java/io/ballerina/semtype/BddCommonOps.java
  semtypes/src/main/java/io/ballerina/semtype/BddMemo.java
  semtypes/src/main/java/io/ballerina/semtype/Common.java
  semtypes/src/main/java/io/ballerina/semtype/Env.java
  semtypes/src/main/java/io/ballerina/semtype/FunctionAtomicType.java
  semtypes/src/main/java/io/ballerina/semtype/MappingAtomicType.java
  semtypes/src/main/java/io/ballerina/semtype/OpsTable.java
  semtypes/src/main/java/io/ballerina/semtype/TypeAtom.java
  semtypes/src/main/java/io/ballerina/semtype/TypeCheckContext.java
  semtypes/src/main/java/io/ballerina/semtype/definition/FunctionDefinition.java
  semtypes/src/main/java/io/ballerina/semtype/subtypedata/BddAllOrNothing.java
  semtypes/src/main/java/io/ballerina/semtype/subtypedata/BddBoolean.java
  semtypes/src/main/java/io/ballerina/semtype/subtypedata/BddNode.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/BddCommonOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/CommonOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/ErrorOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/FunctionOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/ListTypeRWOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/ListTypeRwOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/MappingCommonOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/MappingRwOps.java
Labels: Team/CompilerFE

#32452 Fix java interop FieldSet & FieldGet invalid parameter errors
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropValidator.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/fieldget_error1.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/fieldget_error2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/fieldget_error3.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/fieldset_error1.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/fieldset_error2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/fieldset_error3.bal
Labels: Team/jBallerina
