Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-01, with the labels that each got.

#27343 Fix unreachable pattern issue in nested match-stmt
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/clauses/MatchClauseNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangMatchClause.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtListMatchPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal
Labels: Team/CompilerFE

#27472 Add isolation tests to test the BIR
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/isolation/IsolationAnalysisBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/object/ReadOnlyObjectBaloTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/isolation/test_isolation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/isolation/test_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/object/test_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project_isolation/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project_isolation/isolated_constructs.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project_two/Ballerina.toml
Labels: Team/CompilerFE

#27648 Fix context not ended issue in parsing record field
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/TableTypeTest.java
  compiler/ballerina-parser/src/test/resources/types/table-type/table_type_assert_09.json
  compiler/ballerina-parser/src/test/resources/types/table-type/table_type_source_09.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/Parser, Team/CompilerFE

#27649 Fix OAuth2 service example [1.2.x]
  examples/secured-service-with-oauth2/secured_service_with_oauth2.bal
Labels: Team/StandardLibs

#27391 Fix object type inclusion
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTypeReferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_inclusion_with_qualifiers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_inclusion_with_qualifiers_negative.bal
Labels: Team/CompilerFE

#27564 Implement equals() and hashCode() for symbols
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/AbstractTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaModule.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolEquivalenceTest.java
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#27382 Fix syntax API for receive-action
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ReceiveActionNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/multiple-receive-action.bal
Labels: Team/CompilerFE

#27428 Improve `configurable` variable support for basic types
  bvm/ballerina-rt/build.gradle
  bvm/ballerina-runtime/build.gradle
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigToml.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigurableConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/TomlParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/exceptions/TomlException.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  bvm/ballerina-runtime/src/main/java/module-info.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/configTest.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/configuration.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configuration.toml
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_global_var_decl_negative.bal
Labels: Team/jBallerina

#27659 Fix HTTP2 inbound response headers getting mixed up with trailer validation logic
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
Labels: Team/StandardLibs

#27315 Recursively set readonly flag for runtime types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TableJsonDataSource.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TableOmDataSource.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BArrayType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BField.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BMapType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BRecordType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTableType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTupleType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BXmlType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/MappingInitialValueEntry.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/MockListener.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinfunctions/FreezeAndIsFrozenTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/DeepReadOnlyTest.java
  tests/jballerina-unit-test/src/test/resources/testng-jballerina.xml
  tests/jballerina-unit-test/src/test/resources/testng-new-parser.xml
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#27319 Fix context stack of complex type descriptor
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/RecordTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/ArrayTypeTest.java
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_26.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_26.bal
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_assert_20.json
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_source_02.bal
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_source_08.bal
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_source_16.bal
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_source_17.bal
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_source_20.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Team/CompilerFE

#27679 Remove inclusive() method in record type symbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaRecordTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/RecordTypeSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#27678 Add configurable qualifier
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/Qualifier.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_flag_to_qualifier_mapping_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#27674 Remove compiler.api.impl from exported modules list
  compiler/ballerina-lang/src/main/java/module-info.java
  misc/diagram-util/src/main/java/org/ballerinalang/diagramutil/SyntaxTreeMapGenerator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/docs/BallerinaDocGenerator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/ModuleDoc.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Type.java
Labels: Area/SemanticAPI, Team/CompilerFE

#27677 Remove special-cased isolation warnings for stdlibs
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticWarningCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
Labels: Team/CompilerFE

#27414 Disallow non-readonly service access in isolated functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ReadonlyObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/readonly_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/readonly_objects_negative.bal
Labels: Team/CompilerFE

#27626 Introduce display annotation
  langlib/lang.annotations/src/main/ballerina/annotations.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/query_expr_ctx_join_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/service_decl/config/config11.json
  language-server/modules/langserver-core/src/test/resources/completion/new/service_decl/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/new/service_decl/config/config16.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DisplayAnnotationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/display_annot.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/display_annot_negative.bal
Labels: Team/CompilerFE

#27464 Duplicate object type for object constructor at object init site
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/MethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ObjectType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/RemoteMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ResourceMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ServiceType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/StringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/AnnotationUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BObjectType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BRemoteMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BResourceMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BServiceType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java
  compiler/ballerina-backend-jvm-old/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-backend-jvm/src/main/ballerina/src/compiler_backend_jvm/jvm_type_gen.bal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/lang.error/src/main/java/org/ballerinalang/langlib/error/StackTrace.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/ObjectMock.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/servicetests/ServiceValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/LocalAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ServiceClassTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/local_annot.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl.bal
  tests/observability-test-utils/src/main/java/org/ballerina/testobserve/listenerendpoint/Resource.java
  tests/observability-test-utils/src/main/java/org/ballerina/testobserve/listenerendpoint/WebServer.java
Labels: Lang/ServicesListenerDeclaration, Lang/Type/Objects, Team/CompilerFE

#27544 Allow `readonly` intersection types with classes and allow `readonly class` types in `readonly` record fields
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/object/ReadOnlyObjectBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ReadonlyObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ReadonlyRecordFieldTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/SelectivelyImmutableTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/object/test_readonly_objects_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/readonly_objects_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type_negative.bal
Labels: Team/CompilerFE

#27410 Service resource methods are not considered for subtyping
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ServiceClassTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ServiceObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/service_constructor_expression.bal
  tests/jballerina-unit-test/src/test/resources/test-src/klass/service_class_resource_remote_function_references_neg.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_service_object_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_service_name_literal.bal
Labels: Lang/ServicesListenerDeclaration, Team/CompilerFE

#27672 Allow creating a readonly record with initial values
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/StaticMethodTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
Labels: Team/jBallerina

#26770 Enable Intersection of error types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTypeIdSet.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error_intersection_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error_intersection_type_negative.bal
Labels: Team/CompilerFE

#27731 Enable variable declaration semantics tests
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/VarDeclrSemanticTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/incomplete_var_decl.bal
Labels: Team/CompilerFE

#27565 Improve type checker performance
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
Labels: Team/jBallerina

#27772 Fix redeclared symbol error for intersection types when tests are present
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/VarDeclrSemanticTest.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java
  tests/testerina-integration-test/src/test/resources/project-based-tests/intersection-type-test/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/project-based-tests/intersection-type-test/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/intersection-type-test/tests/main_test.bal
Labels: Team/CompilerFE

#27282 Add parameters passed when logging to diagnostics
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnostic.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLog.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/properties/BCollectionProperty.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/properties/BNumericProperty.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/properties/BStringProperty.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/properties/BSymbolicProperty.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/properties/NonCatProperty.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/SyntaxDiagnostic.java
  compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/diagnostics/Diagnostic.java
  compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/diagnostics/DiagnosticInfo.java
  compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/diagnostics/properties/DiagnosticProperty.java
  compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/diagnostics/properties/DiagnosticPropertyKind.java
  compiler/ballerina-tools-api/src/main/java/module-info.java
  misc/toml-parser/src/main/java/io/ballerina/toml/internal/diagnostics/SyntaxDiagnostic.java
  misc/toml-parser/src/main/java/io/ballerina/toml/semantic/diagnostics/TomlDiagnostic.java
Labels: Area/DiagnosticAPI, Team/CompilerFE

#27543 Move and Codegen string constants to separate class
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmBStringConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/InitMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/LambdaGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ModuleStopMethodGen.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/too-large-method.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/too-large-object-field.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/too-large-object-method.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/too-large-package-variable.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#27801 Temporary Disallow module level list binding pattern
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
Labels: Team/CompilerFE

#27327 Remove the need of initial quoted module prefix for predeclared prefixes
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/PreDeclaredModulePrefixTest.java
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_01.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_02.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_01.json
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/Parser, Team/CompilerFE

#27793 Add overloaded version of symbol() which accepts syntax tree nodes
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByAnnotationTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByClassTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByConstantTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByEnumTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByImportTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByNodeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByObjectTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByRecordTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByVarDeclNegativeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByVarDeclTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByWorkerTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByXMLNSTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_annotation_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_class_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_constant_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_enum_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_function_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_import_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_object_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_record_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_worker_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_xmlns_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/var_decl_symbol_negative_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/var_decl_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#26599 Add module level list binding pattern support
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/PackageNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangAnonymousModelHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/cyclefind/GlobalVariableRefAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangPackage.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachArrayTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachMapTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-arrays-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-maps-typed-binding-patterns.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/DataflowAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/AbstractObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ErrorVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments.bal
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/uninitialized_local_tuple_variable.bal
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl_annotation_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl_taint_analysis_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/uninitialized_module_tuple_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition.bal
Labels: Team/CompilerFE

#27727 Add test for creating readonly array
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/StringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/JsonUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/servicetests/ServiceValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/VariableReturnType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/StaticMethodTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/DeepReadOnlyTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/ReadonlyArrayCreator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/ReadonlyArrayTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/array_creation.bal
  tests/jballerina-unit-test/src/test/resources/testng-jballerina.xml
  tests/jballerina-unit-test/src/test/resources/testng-new-parser.xml
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#26689 Add support for empty XML value
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BXmlType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable-with-variable-mutability.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_text_to_string_conversion.bal
Labels: Team/CompilerFE

#27825 Fix Method too large exception when module contains large no of string constants
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmBStringConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/too-large-string-constants.bal
Labels: Team/jBallerina

#27637 Fix runtime hangs
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/AsyncUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
Labels: Team/jBallerina

#27820 Fix http filter desugar aligned with new service type changes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
Labels: Team/PCModules, Team/StandardLibs

#27670 Add Test API support for configurable variables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/BTestRunner.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/Main.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TestSuite.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TesterinaFunction.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/modules/util.foo/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/modules/util.foo/tests/configuration.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/modules/util.foo/tests/module_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/tests/configuration.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/tests/main_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configuration.toml
Labels: Team/jBallerina

#27833 Fix cyclic dependency issue with transaction tests
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DocumentContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
Labels: Priority/Blocker, Team/CompilerFE

#27780 Improve double and triple backtick documentation parsing
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_06.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_10.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_11.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_12.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_17.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
Labels: Area/Parser, Team/CompilerFE

#27840 Enable code lenses for add documentation
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codelenses/spi/LSCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionProvidersHolder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/LSCodeLensesProviderHolder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/AbstractCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/DocsCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/LSCommandExecutorProvidersHolder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocAttachmentInfo.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocumentationGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/UpdateDocumentationExecutor.java
Labels: Area/LanguageServer, Team/Tooling, Type/NewFeature

#27829 Create transaction branch for new strands created within transactional scope
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionLocalContext.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/EmitterUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
Labels: Team/jBallerina

#26825 Update XML iterator return type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlComment.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlPi.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/lang.xml/src/main/ballerina/internal.bal
  langlib/lang.xml/src/main/ballerina/xml.bal
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Concat.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Next.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-xml-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-xml.bal
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config4.json
  tests/ballerina-spec-conformance-tests/src/S05_values_types_variables/tests/iterable_types.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration_negative.bal
Labels: Team/CompilerFE

#27819 Break error intersection analysis in to two phases
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error_intersection_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/test_intersection_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/test_intersection_type_negative.bal
Labels: Team/CompilerFE

#27138 Add type narrowing to the match-stmt
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangMatchClause.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtTypeNarrowingTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match-stmt-type-narrow.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#27609 Allow field access on structural constructors
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangAccessExpression.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangAccessibleExpression.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangGroupExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangListConstructorExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangQueryExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangRecordLiteral.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTableConstructorExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangVariableReference.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangAssignment.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangCompoundAssignment.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/group/GroupExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/group/group-expr.bal
Labels: Component/Compiler, Team/CompilerFE

#27842 Add change variable type code-action
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/CodeActionContext.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/spi/LSCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/MarkAsUntaintedCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleInsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/IgnoreReturnCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/UpdateDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/OptimizeImportsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/PullModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/CodeActionContextImpl.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeAction.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java
Labels: Area/LanguageServer, Team/Tooling, Type/NewFeature

#27826 Add the custom maven repository support and enable an integration test
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/ResolveMavenDependenciesTask.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageManifest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BallerinaTomlProcessor.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/MavenTestCase.java
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/main.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/Module.md
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/bindings/java.io/FileInputStream.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/bindings/java.io/InputStream.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/bindings/java.util/Map.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/bindings/org.yaml.snakeyaml/Yaml.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.io/File.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.io/FileDescriptor.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.io/Reader.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.io/Writer.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.lang/Class.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.lang/Iterable.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.lang/Object.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.nio.channels/FileChannel.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.util.function/BiConsumer.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.util.function/BiFunction.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.util.function/Function.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.util.regex/Pattern.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.util/Collection.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.util/Iterator.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.util/List.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/java.util/Set.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/org.yaml.snakeyaml.constructor/BaseConstructor.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/org.yaml.snakeyaml.introspector/BeanAccess.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/org.yaml.snakeyaml.nodes/Node.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/org.yaml.snakeyaml.nodes/Tag.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/org.yaml.snakeyaml.representer/Representer.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/org.yaml.snakeyaml.resolver/Resolver.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/org.yaml.snakeyaml/DumperOptions.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/dependencies/org.yaml.snakeyaml/FlowStyle.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/utils/ArrayUtils.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/utils/Constants.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/utils/JObject.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/utils/error_types/FileNotFoundException.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/utils/error_types/IOException.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/ballerina_bindings/utils/error_types/InterruptedException.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/main.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/resources/.keep
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/tests/main_test.bal
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/src/jyaml/tests/resources/.keep
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Component/Packerina, Team/DevTools

#27777 Implement support for module level mappings in the bindgen tool
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-bindgen.help
  misc/ballerina-bindgen/build.gradle
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindingsGenerator.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JClass.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JConstructor.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JError.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JField.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JMethod.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JParameter.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenConstants.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenUtils.java
  misc/ballerina-bindgen/src/main/resources/templates/bridge_class.mustache
  misc/ballerina-bindgen/src/main/resources/templates/exception.mustache
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/MavenSupportTest.java
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/assert-files/Ballerina.toml
  misc/ballerina-bindgen/src/test/resources/testng.xml
  misc/ballerina-formatter/src/main/java/module-info.java
Labels: Component/Bindgen, Team/DevTools

#27650 Cache the public type symbols for internal types
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypeCacheTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type_cache_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#27762 Update langserver into latest LSP version
  gradle/javaProject.gradle
  language-server/modules/langserver-core/build.gradle
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/test/resources/diagnostics/configs/single_file_diagnostics1.json
  misc/ballerinalang-data-mapper/src/main/java/module-info.java
Labels: Area/LanguageServer, Team/Tooling, Type/Task

#27827 Add tests for query expr with multiple order by clauses
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/MultipleOrderByClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/multiple-order-by-clauses.bal
Labels: Team/CompilerFE

#27605 Allow expression in listener declaration to return an error
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangService.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/listener/ListenerBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/execution/ModuleExecutionFlowTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ServiceDeclTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/execution/listener_return_error_project/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/execution/listener_return_error_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/execution/listener_return_error_project/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_service_name_literal.bal
Labels: Team/CompilerFE

#27443 Add parameter defaultability information to resource function type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ResourceMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BResourceMethodType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/servicetests/ServiceValue.java
  tests/jballerina-unit-test/src/test/resources/test-src/klass/simple_service_class.bal
Labels: Team/CompilerFE, Team/jBallerina

#27875 Validate filter desugar for HTTP package only
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
Labels: Team/PCModules, Team/StandardLibs

#27823 Replace the string filename param with Document param
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TypeGuardCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocumentationGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/UpdateDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/AbstractDocumentServiceContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/connector/BallerinaConnectorServiceImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/connector/ConnectorNodeVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentServiceImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaTreeModifyUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaTriggerModifyUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/visitor/UnusedSymbolsVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/definition/DefinitionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/ReferencesUtil.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/utils/LangLibUtils.java
  misc/diagram-util/src/main/java/org/ballerinalang/diagramutil/DiagramUtil.java
  misc/diagram-util/src/main/java/org/ballerinalang/diagramutil/SyntaxTreeMapGenerator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/docs/BallerinaDocGenerator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Type.java
  misc/observability-symbol-collector/src/main/java/org/ballerinalang/observability/anaylze/DefaultObservabilitySymbolCollector.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/AnnotationsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DocumentationTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ServiceSemanticAPITest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolEquivalenceTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TestSourcesTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypeAssignabilityTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypeCacheTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/AnnotationRefsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindModulePrefixRefsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsAcrossFilesTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInLambdasTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInServiceDeclTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInTestsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInWorkersTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/XMLRefsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/util/SemanticAPITestUtils.java
Labels: Area/SemanticAPI, Team/CompilerFE

#27880 Fix issue in creating type ref symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
Labels: Area/SemanticAPI, Team/CompilerFE

#27838 Fix isOptional() in FieldSymbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFieldSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_flag_to_qualifier_mapping_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#27882 Fix filter invocation only with HTTP caller and HTTP request temporarily
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
Labels: Team/PCModules, Team/StandardLibs

#27877 Override langlibMethods() for intersection type symbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/langlib_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#27892 Fix duplicate-field class verify error
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/execution/ModuleExecutionFlowTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/execution/service_decl_listener_return_error_project/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/execution/service_decl_listener_return_error_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/execution/service_decl_listener_return_error_project/main.bal
Labels: Priority/Blocker, Team/CompilerFE

#27887 Implement on-demand diagnostics request
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSContextOperation.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentServiceImpl.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/diagnostics/DiagnosticsTest.java
Labels: Area/LanguageServer, Team/Tooling, Type/NewFeature

#27915 Bump bir version to 54
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/ProgramFileConstants.java
Labels: Team/CompilerFE

#27925 Move langserver into package diagnostics
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer, Team/Tooling, Type/NewFeature

#27905 [Bindgen] Fix an issue when generating exception names of constructors
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JConstructor.java
Labels: Component/Bindgen, Team/DevTools

#27894 Desugar filter hook into http resource method
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangResourceFunction.java
Labels: Team/CompilerFE

#27735 Update bir-spec tests
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/NullBackend.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java
  docs/bir-spec/src/test/resources/test-src/annotations.bal
  docs/bir-spec/src/test/resources/test-src/documentations.bal
  docs/bir-spec/src/test/resources/test-src/flow_control.bal
  docs/bir-spec/src/test/resources/test-src/types_and_operations.bal
  docs/bir-spec/src/test/resources/test-src/values.bal
  settings.gradle
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
Labels: Area/BIR, Team/CompilerFE, Team/jBallerina

#27716 Modify configurable TOML file specification
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigurableConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/ConfigFiles/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/NegativeTests/InvalidOrgName/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/NegativeTests/InvalidTomlFile/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/NegativeTests/InvalidType/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/NegativeTests/RequiredNegative/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/envVarPkg/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/envVarPkg/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/multiModuleProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/modules/util.foo/tests/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testProject/configPkg/tests/Config.toml
Labels: Team/jBallerina

#27921 Allow object type inclusion with `readonly` and object intersections
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTypeReferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/object-type-reference-2-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_func_reference_neg.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_inclusion_with_qualifiers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_inclusion_with_qualifiers_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/test_intersection_type.bal
Labels: Team/CompilerFE

#27946 Deprecate name() method in Symbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/Symbol.java
Labels: Area/SemanticAPI, Team/CompilerFE

#27942 [Bindgen] Improve the user defined error definitions
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JMethod.java
  misc/ballerina-bindgen/src/main/resources/templates/bridge_class.mustache
  misc/ballerina-bindgen/src/main/resources/templates/exception.mustache
Labels: Component/Bindgen, Team/DevTools

#27954 Update the ballerina command name
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-bindgen.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-encrypt.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-format.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-grpc.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-help.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-home.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-openapi.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-run.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-test.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-uninstall.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-version.help
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatCmd.java
Labels: Team/DevTools

#27584 Refactor documentation lexer and parser
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticWarningCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractTokenReader.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserMode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/TokenReader.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/incremental/HybridTokenReader.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/DocumentationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/QuotedIdentifierTest.java
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_24.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_06.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_19.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_source_19.bal
  compiler/ballerina-parser/src/test/resources/misc/quoted-identifiers/incomplete_identifier_assert.json
  compiler/ballerina-parser/src/test/resources/misc/quoted-identifiers/incomplete_identifier_source.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/IdentifierLiteralTest.java
Labels: Area/Parser, Team/CompilerFE

#27956 Notify user when project-api load call fails in langserver
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer, Priority/High, Team/Tooling, Type/Improvement

#27927 Use projRoot and documentId computations in project-apis
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer, Team/Tooling, Type/Task

#27963 Add cyclic type reference for OrderedType type in array.bal
  langlib/lang.array/src/main/ballerina/array.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
Labels: Team/CompilerFE

#27971 Fix issue in conditional expr parsing with predeclared prefix
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/ternary/TernaryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal
Labels: Area/Parser, Team/CompilerFE

#27973 Rename moduleLevelSymbols() to moduleSymbols()
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSAnnotationCache.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/BallerinaTypeResolver.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/FunctionInvocationExpressionEvaluator.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/MethodCallExpressionEvaluator.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/WorkspaceSymbolLookupTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#27975 Fix issue with cursor position checking logic
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#27937 Override the included record type properly
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-iterable-object-negative.bal
  language-server/modules/langserver-core/src/test/resources/completion/function/source/errorUnionSuggestion1.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/record/ClosedRecordTypeReferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/test_project_errors/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/distinct_error_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/distinct_error_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_destructure_binding_pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_operator_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/checked_expr_operator_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record_type_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record_type_reference_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Team/CompilerFE

#27962 Fix the new line separation after annotations in module variable declarations
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/actions/start/assert/start_action_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/start/source/start_action_2.bal
Labels: Component/Formatting, Team/Tooling

#27909 Change value.cloneReadonly argument and return type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java
  langlib/lang.value/src/main/ballerina/value.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/field_access_ctx_config9.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinfunctions/FreezeAndIsFrozenTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen-semantics-negative.bal
Labels: Team/CompilerFE

#28005 Introducing hierarchical package names
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/InitCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/NewCommand.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BallerinaToml.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BaloFiles.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ImportModuleRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ImportModuleResponse.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/VersionConflictResolutionTests.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentServiceImpl.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/HierarchicalPackageNameTests.java
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_a.b/Ballerina.toml
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_a.b/main.bal
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_a.b/modules/c/modc.bal
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_a/Ballerina.toml
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_a/main.bal
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_a/modules/c/modc.bal
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_app1/Ballerina.toml
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_app1/main.bal
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_x.y.z/Ballerina.toml
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_x.y.z/main.bal
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_x.y.z/modules/a/moda.bal
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_x.y.z/modules/b/modb.bal
  project-api/project-api-test/src/test/resources/hierarchical_pkg_names/package_x.y.z/modules/c/modc.bal
Labels: Component/ProjectAPI

#27985 Add snippet for http service
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RecordFieldNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ModulePartNodeContextUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/Snippet.java
  language-server/modules/langserver-core/src/test/resources/completion/new/module_part_context/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/module_part_context/config/config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/module_part_context/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/service_decl/config/config7.json
Labels: Area/LanguageServer

#28008 Fix record implicit readonly-ness with inclusion and fix cyclic union comparison
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ReadonlyRecordFieldTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/CyclicTypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions-cyclic.bal
Labels: Priority/Blocker, Team/CompilerFE

#27911 Fix signature() of union type symbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#28014 Make taint error emitting a build option
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-build.help
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BallerinaToml.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BuildOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/ProjectLoader.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/SingleFileProject.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/CompilerOptionName.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/BallerinaTomlTests.java
  compiler/ballerina-lang/src/test/resources/ballerina-toml/valid-ballerina.toml
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/MarkUntaintedTest.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
Labels: Priority/Blocker, Team/CompilerFE

#27710 Fix broken tests
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bir/BirVariableOptimizationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/taintchecking/TaintedStatusPropagationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/$lambda$_0
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/complexAddition
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/globalVarsAndAnonFunctions
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/mapInits
  tests/jballerina-unit-test/src/test/resources/test-src/bir/biroptimizer.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/param-status-with-native-invocations-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/param-status-with-native-invocations.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#28024 Make taint checking a build option
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-run.help
Labels: Team/CompilerFE

#28010 Modify return type of fieldDescriptors() and methods() to Map<String, *FieldSymbol> and Map<String, MethodSymbol>
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaClassSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaRecordTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ClassSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/RecordTypeSymbol.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/SymbolUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/completion/BLangRecordLiteralUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FieldAccessContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RightArrowActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/MethodCallExpressionEvaluator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DocumentationTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ServiceSemanticAPITest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypeCacheTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/util/SemanticAPITestUtils.java
Labels: Area/SemanticAPI, Team/CompilerFE

#27996 Fix code-actions invalid module prefix issue and doc generation issues
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/AddDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/UpdateDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocAttachmentInfo.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocumentationGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddAllDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/AddDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/UpdateDocumentationExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
Labels: Area/LanguageServer, Priority/High, Team/Tooling, Type/Bug

#28030 Fix member access on nilable record
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal
Labels: Team/CompilerFE

#27998 Fix builtin error classified as type
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/ErrorsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/errors_project/errors.bal
Labels: Component/Docerina, Team/DevTools

#28047 Improve invalid import declaration handling in single file projects
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
Labels: Component/ProjectAPI

#27596 Add support for mapping type rest arguments
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/DynamicArgNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/LambdaGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/InstructionEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/ArgumentState.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRArgument.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangDynamicArgExpr.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithRestArguments.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordEquivalencyRulesTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/MapToRecordAssignabilityTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_mapping_type_rest_argument.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_mapping_type_rest_argument_negative.bal
Labels: Team/CompilerFE

#28063 Make dynamic listener register, deregister as isolated functions
  langlib/lang.runtime/src/main/ballerina/runtime.bal
Labels: Team/jBallerina

#28055 Deprecate moduleID() method
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/Symbol.java
Labels: Area/SemanticAPI, Team/CompilerFE

#28065 Fix invalid identifier starting with a "\" parsing
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationLexer.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ModuleVarDeclTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/DocumentationTest.java
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_16.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_16.bal
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_20.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_source_20.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/Parser, Team/CompilerFE

#28084 Fix using check with union containing readonly
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_operator_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expression_with_readonly_in_union_negative.bal
Labels: Team/CompilerFE

#28083 Update the jarrays module name to java.arrays
  misc/ballerina-bindgen/src/main/resources/templates/bridge_class.mustache
Labels: Component/Bindgen, Team/DevTools

#28054 Restrict loop alteration from separate functions
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/breakstatement/BreakStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/continuestatement/ContinueStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/breakstatement/break-stmt-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/continuestatement/continue-stmt-negative.bal
Labels: Team/CompilerFE

#28102 Fix Ballerina.toml compilation issues
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Package.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ManifestBuilder.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
  project-api/project-api-test/src/test/resources/myproject_minimalist/Ballerina.toml
  project-api/project-api-test/src/test/resources/myproject_minimalist/main.bal
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/services/Module.md
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/services/resources/config.json
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/services/resources/invalidProject/Ballerina.toml
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/services/resources/invalidProject/main.bal
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/services/resources/invalidProject/tests/main_tests.bal
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/services/svc.bal
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/services/tests/svc_tests.bal
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/storage/db.bal
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/storage/resources/db.json
  project-api/project-api-test/src/test/resources/myproject_minimalist/modules/storage/tests/db_tests.bal
  project-api/project-api-test/src/test/resources/myproject_minimalist/resources/main.json
  project-api/project-api-test/src/test/resources/myproject_minimalist/tests/main_tests.bal
  project-api/project-api-test/src/test/resources/myproject_minimalist/util/file-util.bal
  project-api/project-api-test/src/test/resources/myproject_minimalist/utils.bal
Labels: Priority/Blocker

#28104 Fix Compiler Extensions diagnostic displaying issue
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
Labels: Component/ProjectAPI, Priority/Blocker

#28096 Fix taint-check flag not picking from CLI
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptions.java
Labels: Team/CompilerFE

#28092 Strict file operation checks in langserver
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer, Priority/Blocker, Team/Tooling, Type/Bug

#28111 Make taint-checking a build option
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-build.help
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-run.help
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BuildOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/ProjectLoader.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/SingleFileProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BallerinaTomlProcessor.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/CompilerOptionName.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/MarkUntaintedTest.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
Labels: Team/CompilerFE

#28108 Fix package instance fails for .toml file path
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer, Priority/Blocker, Team/Tooling, Type/Bug

#28113 Fix incorrect syntax tree API usage
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Document.java
Labels: Component/ProjectAPI

#28101 Fix langlib empty package summaries
  misc/docerina/src/main/java/org/ballerinalang/docgen/docs/BallerinaDocGenerator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/docs/utils/BallerinaDocUtils.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/ModuleDoc.java
Labels: Component/Docerina, Team/DevTools

#28131 Remove invalid exception throw on ballerina.toml open
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer

#28140 Remove invalid exception throw on ballerina.toml open
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Area/LanguageServer, Priority/Blocker

#28137 Fix Invalid Resource Code Action Snippet issue
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/kubernetes/AbstractInvalidResourceCodeAction.java
Labels: Priority/Blocker

#28173 Fix context stack for parameter doc with missing description
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationLexer.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/DocumentationTest.java
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_21.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_source_21.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/Parser, Team/CompilerFE

#28025 Refactor error component of ballerina streams
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/visitors/TypeSignatureTransformer.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaStreamTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/StreamTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/TypeEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BStreamType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ResolvedTypeBuilder.java
  langlib/lang.__internal/src/main/ballerina/stream-utils.bal
  langlib/lang.array/src/main/ballerina/array.bal
  langlib/lang.query/src/main/ballerina/helpers.bal
  langlib/lang.query/src/main/ballerina/types.bal
  langlib/lang.query/src/main/java/org/ballerinalang/langlib/query/Print.java
  langlib/lang.stream/src/main/ballerina/internal.bal
  langlib/lang.stream/src/main/ballerina/stream.bal
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-exp-iterable-objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Lang/Type/Streams, Team/CompilerFE

#28141 Add any param type support for function mocking
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/Executor.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/FunctionMock.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/MockTest.java
  tests/testerina-integration-test/src/test/resources/project-based-tests/function-mocking-tests/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/function-mocking-tests/tests/main_test.bal
Labels: Component/Testerina, Team/TestFramework

#28257 Prioritize predeclared prefix in ballerina error handler
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_02.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
Labels: Area/Parser, Team/CompilerFE
