Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-02, with the labels that each got.

#28031 Add an overloaded version of type() which takes syntax tree nodes as the arg
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByAccessExprTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByAnonFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByCallExprTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByConstructorExprTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByErrorHandlingExprTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByLiteralTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByMiscExprTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByNodeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByReferenceTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByTemplateExprTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByTypeExprTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_access_expr.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_anon_function.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_call_expr.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_constructor_expr_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_error_handling_exprs.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_literal.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_misc_exprs.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_reference_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_template_expr.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_type_exprs.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE

#28369 Fix issue in parseing error or const match pattern
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_04.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_04.bal
Labels: Area/Parser, Team/CompilerFE

#28294 Persist enum symbol info in BIR
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaModule.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ModuleSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/ProgramFileConstants.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  docs/bir-spec/src/test/resources/test-src/typedefs.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testproject/type_defs.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#27933 Refactor error handler rules for qualifiers
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/FunctionDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ModuleVarDeclTest.java
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_05.json
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_35.json
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_source_35.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_28.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_source_28.bal
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_15.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_17.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_17.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
Labels: Area/Parser, Team/CompilerFE

#27945 Fix bad sad error when assigning a constant value to an enum member
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/jballerina-unit-test/src/test/resources/test-src/enums/enums.bal
Labels: Team/CompilerFE

#28011 Update type checker to use context information when deriving type of a let expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/let/LetExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal
Labels: Team/CompilerFE

#28293 Fix NPE when using error binding pattern with no message
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ResilientParserTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ErrorVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt.bal
Labels: Team/CompilerFE

#28426 Fix pull packages with snapshot versions
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PullCommand.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/PullCommandTest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectConstants.java
Labels: Area/ProjectAPI, Team/DevTools

#27970 Incorporate suggestions in PR #27464 and #27410
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BServiceType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ServiceClassTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/klass/service_type_resource_method_decl_neg.bal
Labels: Team/CompilerFE

#28288 Add Custom error message support for Toml Schema validator
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/toml/TomlSchemaVisitor.java
  misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/SchemaValidator.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/schema/AbstractSchema.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/schema/ArraySchema.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/schema/BooleanSchema.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/schema/NumericSchema.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/schema/ObjectSchema.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/schema/Schema.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/schema/SchemaDeserializer.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/schema/SchemaVisitor.java
  misc/toml-parser/src/main/java/io/ballerina/toml/validator/schema/StringSchema.java
  misc/toml-parser/src/test/java/toml/parser/test/validator/CustomErrorTest.java
  misc/toml-parser/src/test/java/toml/parser/test/validator/TomlValidateTest.java
  misc/toml-parser/src/test/resources/validator/basic/c2c-clean.toml
  misc/toml-parser/src/test/resources/validator/basic/c2c-invalid-additional-properties.toml
  misc/toml-parser/src/test/resources/validator/basic/c2c-invalid-min-max.toml
  misc/toml-parser/src/test/resources/validator/basic/c2c-invalid-regex.toml
  misc/toml-parser/src/test/resources/validator/basic/c2c-invalid-type.toml
  misc/toml-parser/src/test/resources/validator/basic/c2c-schema.json
  misc/toml-parser/src/test/resources/validator/custom-error/clean.toml
  misc/toml-parser/src/test/resources/validator/custom-error/regex.toml
  misc/toml-parser/src/test/resources/validator/custom-error/schema.json
  misc/toml-parser/src/test/resources/validator/custom-error/table.toml
  misc/toml-parser/src/test/resources/validator/custom-error/type.toml
Labels: Area/TOMLParser, SwanLakeDump, Team/DevTools

#28322 Fix nested access on nilable mapping when the final access is for an unavailable optional field or nil value
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangFieldBasedAccess.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/OptionalFieldAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access.bal
Labels: Team/CompilerFE

#28328 Improve runtime error messages for anonymous types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRecordType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BStructureType.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/MapToRecordAssignabilityTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/readonly_field.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/assertions-error-messages/tests/assertions-error-messages.bal
Labels: Team/jBallerina

#28450 Embed rest match pattern to match pattern list in SyntaxAPI
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STListMatchPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STMappingMatchPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STTreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ListMatchPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/MappingMatchPatternNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_08.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_10.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_11.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_12.json
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
Labels: Area/Parser, Team/CompilerFE, Type/Improvement

#28463 Fix issue with member access on tables
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/TypeByAccessExprTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_access_expr.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/RecordConstraintTableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableWithRecordKeySpecifierTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableWithXMLKeySpecifierTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/clone-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/record-constraint-table-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/record-type-table-key.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/xml-type-table-key.bal
Labels: Team/CompilerFE

#28475 Add service attachpoint to display annot
  langlib/lang.annotations/src/main/ballerina/annotations.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DisplayAnnotationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/display_annot.bal
Labels: Team/CompilerFE

#28368 Fix NPE with fromJsonWithType
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonWithType.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/CompilerFE

#28465 Fix issues with fromBalString
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/StringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BalStringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromBalString.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromBalString_test.bal
Labels: Team/CompilerFE

#28487 Fix duplicate existing node diagnostic in Toml Parser
  misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java
Labels: Area/TOMLParser

#28143 Fix annotation not getting set for functions with special characters in their name
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BErrorType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFunctionType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BMethodType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BObjectType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BRecordType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/servicetests/ServiceValue.java
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl.bal
Labels: Team/CompilerFE

#28462 Remove casts to imported anonymous types and add a validation to disallow the same
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/CompilerFE

#28350 Fix several issues with tuples
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTupleType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/types/TupleTypeBaloTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleRestDescriptorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/types/test_tuple_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_balo/types/test_tuple_type_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/tuple_type_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/balo/test_projects/tuple_type_project/f unctions_returning_tuples.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal
Labels: Team/CompilerFE

#28506 Fix build failures due to parallel merges
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/TupleTypeBalaTest.java
Labels: Team/CompilerFE

#28303 Fix Ballerina CLI evaluation logic to use `toBalString`
  ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/integration/SimpleEvaluatorTest.java
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/flow.control.elvis.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/function.anon.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/json.access.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/json.json.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/json.objects.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/operations.cast.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/record.basic.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/values.basic.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/values.enum.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/values.literals.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/values.maps.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/values.strings.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/values.tuples.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/xml.attributes.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/xml.basic.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/xml.namespaces.json
  ballerina-shell/modules/shell-core/build.gradle
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/Evaluator.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/StringUtils.java
  ballerina-shell/modules/shell-core/src/main/java/module-info.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/SimpleEvaluatorTest.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/EvaluatorMiscTest.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/basics.quoted.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/errors.handling.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/flow.control.elvis.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/function.anon.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/java.interop.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/json.access.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/json.arrays.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/json.json.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/json.objects.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/object.assign.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/object.constructor.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/object.init.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/object.methods.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/object.readonly.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/object.ref.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/object.type.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/operations.cast.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/operations.optional.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/query.expr.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/record.basic.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/regression.same.import.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.basic.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.enum.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.let.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.literals.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.maps.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.raw.template.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.strings.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.table.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.tuples.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/xml.access.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/xml.attributes.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/xml.basic.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/xml.function.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/xml.literal.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/xml.namespaces.json
Labels: Area/Shell, Team/CompilerFE

#28441 Stop considering isolated variable access as an attempt to transfer a value into a lock statement
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedVariableTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables_isolation_negative.bal
Labels: Team/CompilerFE

#28175 [Ballerina Shell] Change the templates in shell-core to use mustache
  ballerina-shell/modules/shell-core/build.gradle
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/Invoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/ClassLoadContext.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/StatementContext.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/StringUtils.java
  ballerina-shell/modules/shell-core/src/main/java/module-info.java
  ballerina-shell/modules/shell-core/src/main/resources/template.declaration.ftl
  ballerina-shell/modules/shell-core/src/main/resources/template.declaration.mustache
  ballerina-shell/modules/shell-core/src/main/resources/template.execution.ftl
  ballerina-shell/modules/shell-core/src/main/resources/template.execution.mustache
  ballerina-shell/modules/shell-core/src/main/resources/template.import.ftl
  ballerina-shell/modules/shell-core/src/main/resources/template.import.mustache
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/AbstractEvaluatorTest.java
  distribution/zip/jballerina-tools/build.gradle
Labels: Area/Shell

#27808 Enable `testIncompleteListenerDecl` test
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ObjectTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_44.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_source_44.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/VarDeclrSemanticTest.java
Labels: Team/CompilerFE

#28461 Support configurable variables of `record` & `table` types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigToml.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigurableConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/InitMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/TestConstant.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/config_files/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/additionalField/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/additionalField/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/additionalField/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidMapType/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidMapType/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidMapType/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidOrgName/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidOrgName/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidOrgName/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidRecordField/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidRecordField/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidRecordField/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidTomlFile/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidTomlFile/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidTomlFile/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidType/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidType/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidType/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/missingRequiredField/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/missingRequiredField/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/missingRequiredField/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/missingTableKey/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/missingTableKey/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/missingTableKey/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/noModuleConfig/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/noModuleConfig/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/noModuleConfig/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/noModuleConfig/main/modules/foo/foo.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/no_config.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/requiredNegative/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/requiredNegative/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/requiredNegative/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/recordModuleProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/recordModuleProject/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/recordModuleProject/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/recordModuleProject/main/modules/employee/employee.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_global_var_decl_negative.bal
Labels: Team/jBallerina

#28372 Fix type match for nil type initialized as finite type and finite type inside union
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finite/FiniteTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/finite/finite-type.bal
Labels: Area/RuntimeTypeChecker, Team/jBallerina

#28498 Support encrypted values for String Configurable variables
  bvm/ballerina-config/src/main/java/org/ballerinalang/config/cipher/AESCipherTool.java
  bvm/ballerina-rt/build.gradle
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigSecurityUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigurableConstants.java
  bvm/ballerina-runtime/src/main/java/module-info.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/Main.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/PackageID.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BLangCompilerConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/CompilerDriver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  distribution/zip/jballerina-tools/build.gradle
  distribution/zip/jballerina/build.gradle
  langlib/lang.config/build.gradle
  langlib/lang.config/src/main/ballerina/Ballerina.toml
  langlib/lang.config/src/main/ballerina/Module.md
  langlib/lang.config/src/main/ballerina/config.bal
  langlib/lang.config/src/main/java/module-info.java
  langlib/lang.config/src/main/java/org/ballerinalang/langlib/config/DecryptUtils.java
  settings.gradle
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/ConfigFiles/InvalidEncryptedConfig.toml
  tests/jballerina-integration-test/src/test/resources/configurables/Secrets/correctSecret.txt
  tests/jballerina-integration-test/src/test/resources/configurables/Secrets/emptySecret.txt
  tests/jballerina-integration-test/src/test/resources/configurables/Secrets/incorrectSecret.txt
  tests/jballerina-integration-test/src/test/resources/configurables/encryptedConfigProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/encryptedConfigProject/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/encryptedConfigProject/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/encryptedSingleBalFile/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/encryptedSingleBalFile/encryptedConfig.bal
Labels: Team/jBallerina

#28495 Invalidate record rest descriptor inside open record
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/RecordTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_27.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_27.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/Parser, Team/CompilerFE, Type/Improvement

#28513 Deprecate name() and kind() APIs in ParameterSymbol
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/visitors/TypeSignatureTransformer.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaParameterSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ParameterSymbol.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/FunctionCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/InvocationArgProcessor.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#28522 Fix and enable match statement tests for the formatter
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_assert_02.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_source_02.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_01.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_05.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_08.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_10.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_12.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_14.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_01.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_05.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_08.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_10.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_12.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_14.bal
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/Formatting, Team/Tooling

#28535 Add annotations to BIR type-defs
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
Labels: Team/CompilerFE

#28529 Read version & lang spec from properties file
  cli/ballerina-cli-module/src/main/java/org/ballerinalang/cli/module/Pull.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BalaWriter.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/model/Module.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/SourceDirectoryManager.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/converters/URIConverter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/repo/HomeBalaRepo.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ProjectDirConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/ProgramFileConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/RepoUtils.java
  compiler/ballerina-lang/src/test/java/org/wso2/ballerinalang/compiler/SourceDirectoryManagerTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/DependencyScopeTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/DirectoryTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/LockFileTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/ModulePushTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/MultipleVersionsModuleTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/NativePackagingTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PackagingNegativeTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PackagingTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PackerinaTestUtils.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PathDependencyTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/SingleBalFileTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/SpiServicesTestCase.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Area/ProjectAPI, Team/DevTools

#28539 Fix invalid iteration type for `xml` in `from` clause
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/lang.query/src/main/ballerina/types.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/inner-queries.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/order-by-clause.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/xml-query-expression.bal
Labels: Team/CompilerFE

#28530 Add completion support within function call expressions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BasicLiteralNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionCallExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/function_call_expression_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/function_call_expression_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/function_call_expression_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/function_call_expression_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/function_call_expression_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/function_call_expression_ctx_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/string_literal_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/function_call_expression_ctx_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/function_call_expression_ctx_source2.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/function_call_expression_ctx_source3.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/function_call_expression_ctx_source4.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/function_call_expression_ctx_source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/function_call_expression_ctx_source6.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/source/string_literal_ctx_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/new/statement_context/config/xmlns_ctx_config1.json
Labels: Area/LanguageServer

#28227 Add module level error and mapping binding pattern support
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangAnonymousModelHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachArrayTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachMapTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-arrays-typed-binding-patterns.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-maps-typed-binding-patterns.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/DataflowAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleErrorVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleRecordVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleTupleVariableTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments.bal
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/uninitialized_local_complex_variables.bal
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl_annotation_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl_taint_analysis_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl_annotation_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl_taint_analysis_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/uninitialized_module_record_var_decl.bal
Labels: Area/Compiler, Team/CompilerFE, Type/NewFeature

#28555 Make additional properties true in ballerina toml schema
  compiler/ballerina-lang/src/main/resources/ballerina-toml-schema.json
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/BallerinaTomlTests.java
  compiler/ballerina-lang/src/test/resources/ballerina-toml/additional-props-ballerina.toml
Labels: Area/ProjectAPI, Team/DevTools

#28560 Add missing lang spec version to package.json of .bala
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BalaWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ProjectDirConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/RepoUtils.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBalaWriter.java
Labels: Area/ProjectAPI, Team/DevTools

#28344 Improve Ballerina Shell CLI parser to support some partial snippets
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/ReplShellApplication.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/JlineBallerinaParser.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/JlineParsedLine.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/parser/ParserState.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/parser/ParserStateMachine.java
  ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/parser/ParserStateMachineTest.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/preprocessor/SeparatorPreprocessor.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/preprocessor.separator.json
Labels: Area/Shell, Team/CompilerFE

#28538 Update the 1.2 BBE and API Docs Links to "/1.2/learn"
  examples/config-api/config_api.description
  examples/http-cookies/http_cookies.description
  examples/testerina-assertions/testerina_assertions.description
  examples/testerina-before-and-after-each/testerina_before_and_after_each.description
  examples/testerina-before-and-after-suite/testerina_before_and_after_suite.description
  examples/testerina-before-and-after-test/testerina_before_and_after_test.description
  examples/testerina-data-driven-tests/testerina_data_driven_tests.description
  examples/testerina-group-tests/testerina_group_tests.description
  examples/testerina-guarantee-test-execution-order/testerina_guarantee_test_execution_order.description
  examples/testerina-mocking-functions/testerina_mocking_functions.description
  examples/testerina-mocking-objects/testerina_mocking_objects.description
  stdlib/auth/src/main/ballerina/src/auth/Module.md
  stdlib/cache/src/main/ballerina/src/cache/Module.md
  stdlib/crypto/src/main/ballerina/src/crypto/Module.md
  stdlib/email/src/main/ballerina/src/email/Module.md
  stdlib/file/src/main/ballerina/src/file/Module.md
  stdlib/filepath/src/main/ballerina/src/filepath/Module.md
  stdlib/grpc/src/main/ballerina/src/grpc/Module.md
  stdlib/http/src/main/ballerina/src/http/Module.md
  stdlib/io/src/main/ballerina/src/io/Module.md
  stdlib/java.arrays/src/main/ballerina/src/java.arrays/Module.md
  stdlib/java/src/main/ballerina/src/java/Module.md
  stdlib/jwt/src/main/ballerina/src/jwt/Module.md
  stdlib/ldap/src/main/ballerina/src/ldap/Module.md
  stdlib/log-api/src/main/ballerina/src/log/Module.md
  stdlib/math/src/main/ballerina/src/math/Module.md
  stdlib/messaging/kafka/src/main/ballerina/src/kafka/Module.md
  stdlib/messaging/nats/src/main/ballerina/src/nats/Module.md
  stdlib/messaging/rabbitmq/src/main/ballerina/src/rabbitmq/Module.md
  stdlib/mime/src/main/ballerina/src/mime/Module.md
  stdlib/oauth2/src/main/ballerina/src/oauth2/Module.md
  stdlib/socket/src/main/ballerina/src/socket/Module.md
  stdlib/task/src/main/ballerina/src/task/Module.md
  stdlib/time/src/main/ballerina/src/time/Module.md
  stdlib/websub/src/main/ballerina/src/websub/Module.md
  stdlib/xslt/src/main/ballerina/src/xslt/Module.md
Labels: Type/Docs

#28568 Synchronize compile() in PackageCompilation
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
Labels: Priority/Blocker, Team/CompilerFE, Team/DevTools

#28617 Improve the synchronization of the compiler context in PackageCompilation
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
Labels: Team/CompilerFE, Team/DevTools

#28402 Fix chained invocations with rest args
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibIntTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/intlib_test.bal
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
Labels: Area/Desugar, Lang/LangLib, Team/CompilerFE

#28638 Add User-Agent header to push & search of Central client and Change staging url of the central
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/SearchCommand.java
  cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java
  cli/central-client/src/test/java/org/ballerinalang/central/client/TestCentralApiClient.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/RepoUtils.java
Labels: Team/DevTools

#28523 Fix tuple reverse and filter functions
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.arrays.json
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/AbstractArrayValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Filter.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Reverse.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Slice.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/utils/ArrayUtils.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Team/jBallerina

#28644 [Formatting] Add space after colon in mapping binding patterns
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_07.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_08.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_source_02.bal
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_source_07.bal
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_source_08.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_14.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_15.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_16.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_17.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_19.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_14.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_15.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_16.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_17.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_19.bal
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_assert_02.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_source_02.bal
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/mapping_binding_pattern_assert_01.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/mapping_binding_pattern_source_01.bal
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_18.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_19.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_22.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_source_18.bal
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_source_19.bal
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_source_22.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_05.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_05.bal
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/expressions/let/assert/let_expression_1.bal
Labels: Area/Formatting, Team/Tooling

#28651 Fix code-action imports duplication issue
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/ImportsAcceptor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
Labels: Area/LanguageServer, Team/Tooling, Type/Bug

#28652 Fix code actions getting duplicated issue
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/CodeActionContextImpl.java
Labels: Area/LanguageServer, Team/Tooling, Type/Bug

#28653 Fix invalid suggestion for code fixes
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
Labels: Area/LanguageServer, Team/Tooling, Type/Bug

#28659 Fix CCE in TreeModifier when modifying error message match pattern
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_12.json
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/Parser, Team/CompilerFE

#28392 Remove the use of a Security Manager in Ballerina Shell
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/DiagnosticReporter.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/Evaluator.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/EvaluatorBuilder.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/Invoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/ShellSnippetsInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/NoExitVmSecManager.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/visitors/ElevatedTypeTransformer.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/base/TestInvoker.java
  bvm/ballerina-runtime/src/main/java/module-info.java
Labels: Area/Shell, Team/CompilerFE

#28623 Introduce a fail-safe mechanism for the parser error recovery
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java
Labels: Area/Parser, Team/CompilerFE, Type/Improvement

#28689 Fix signature() in singleton types to consider ()
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSingletonTypeSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Priority/Blocker, Team/CompilerFE

#28144 Fix Ballerina shell CLI tests to remove some special characters
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java
  ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestCase.java
  ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/ShellCommandTest.java
Labels: Area/Shell, Team/CompilerFE

#28703 Fix issues in dependently-typed functions with defaultable parameters
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ResolvedTypeBuilder.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/VariableReturnType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/functions/VariableReturnTypesBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/VariableReturnTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/variable_return_type_bir_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/variable_return_type_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/variable_return_type_test.bal
Labels: Priority/Blocker, Team/CompilerFE

#28447 Enable annotation tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  langlib/lang.test/src/main/ballerina/MockListener.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationRuntimeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annotation_access_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annotation_readonly_types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annotations_constant_propagation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/annotations/annotation.bal
Labels: Team/CompilerFE

#28323 Handle casting errors
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/JavaFieldAccessMutate.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/FieldAccessMutateTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/field_access_mutate_tests.bal
Labels: Team/jBallerina

#28505 Fix code review suggestions for PR 27995
  docs/bir-spec/src/test/resources/test-src/values.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
Labels: Team/CompilerFE

#28321 Improve error messages in Ballerina Shell
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/Diagnostic.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/ShellSnippetsInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/GetErrorMessageTrial.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ParserTrialFailedException.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/factory/SnippetFactory.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/StringUtils.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/StringUtilsTest.java
Labels: Area/Shell, Team/CompilerFE

#27824 Add module level typed binding pattern support
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/PackageNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangAnonymousModelHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/cyclefind/GlobalVariableRefAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangPackage.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/DataflowAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/AbstractObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleErrorVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleRecordVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleTupleVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ErrorVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments.bal
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/uninitialized_local_complex_variables.bal
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl_annotation_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl_taint_analysis_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl_annotation_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl_taint_analysis_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl_annotation_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl_taint_analysis_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/uninitialized_module_record_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/uninitialized_module_tuple_var_decl.bal
Labels: Area/Compiler, Team/CompilerFE, Type/NewFeature

#28589 Add ComplexTypeDesc support in bracketed list start
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_26.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_source_26.bal
Labels: Area/Parser, Team/CompilerFE

#28650 Implement LSP client-side file-watcher for langserver
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSContextOperation.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/config/LSClientConfig.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/TestWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/WorkspaceTest.java
  language-server/modules/langserver-core/src/test/resources/project/myproject2/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/project/myproject2/main.bal
  language-server/modules/langserver-core/src/test/resources/project/myproject2/modules/services/svc.bal
  language-server/modules/langserver-core/src/test/resources/project/myproject2/modules/storage/db.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Area/LanguageServer, Team/Tooling, Type/NewFeature

#28712 Set BType for function related BInvokableTypeSymbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
Labels: Team/CompilerFE

#28751 Fix Null Pointer Exception thrown when resolving paths in ProjectPaths utils
  .github/workflows/CI_ubuntu_windows.yml
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectPaths.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/BallerinaTomlTests.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/ProjectPathsTest.java
Labels: Priority/Blocker

#28761 Fix optimize-imports code-action issues
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/CodeActionContext.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/spi/DiagBasedPositionDetails.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/spi/LSCodeActionProvider.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/spi/NodeBasedPositionDetails.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/DiagBasedPositionDetailsImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/NodeBasedPositionDetailsImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractCodeActionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddConfigsToK8sCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddResourceToK8sCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/MarkAsUntaintedCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TypeGuardCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleInsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/IgnoreReturnCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/AddAllDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/AddDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/UpdateDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/OptimizeImportsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/PullModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/CodeActionContextImpl.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeAction.java
  misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java
Labels: Area/LanguageServer, Team/Tooling, Type/Bug

#28763 Fix issue in parsing transaction as predeclared prefix
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_01.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_02.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_01.json
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
Labels: Area/Parser, Team/CompilerFE

#28727 Add transaction as a pre-declared module
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/imports/PredeclaredImportsTestProject/predeclared-modules.bal
Labels: Team/CompilerFE

#28643 Fix XML template not properly working with query expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/xml-query-expression.bal
Labels: Team/CompilerFE

#28724 Do not allow non-mapping type to be a constraint type in a table returned from a query expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
Labels: Team/CompilerFE

#28547 Support byte and byte[] for configurable variables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigurableConstants.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidByteRange/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidByteRange/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/negative_tests/invalidByteRange/main/main.bal
Labels: Team/jBallerina

#28773 Add diagnostic for missing tokens in ballerina documentation
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticWarningCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_13.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_21.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_22.json
Labels: Area/Diagnostics, Area/Parser, Team/CompilerFE

#28553 Update the manifest used to retrieve platform dependencies and add unit tests
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindingsGenerator.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JClass.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JConstructor.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JField.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JMethod.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JParameter.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenConstants.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenEnv.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenMvnResolver.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/BindgenCommandTest.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/CommandTest.java
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/assert-files/Ballerina.toml
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/Ballerina.toml
Labels: Area/Bindgen, Team/DevTools

#28631 Constraint arguments to the error constructor
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_errors.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ErrorVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/clone-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error_intersection_type.bal
Labels: Team/CompilerFE, Type/SpecDeviation

#28793 Address TODOs in the invalid token process in BallerinaLexer
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/test/resources/trivia/trivia_assert_02.json
  compiler/ballerina-parser/src/test/resources/trivia/trivia_source_02.bal
Labels: Area/Parser, Team/CompilerFE

#28636 Replace `default` with `function` to refer function's default worker
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangInvokableNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/resources/actions/flush-action/flush_action_assert_01.json
  compiler/ballerina-parser/src/test/resources/actions/flush-action/flush_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/flush-action/flush_action_source_01.bal
  compiler/ballerina-parser/src/test/resources/actions/flush-action/flush_action_source_02.bal
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_01.json
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_source_01.bal
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_source_02.bal
  compiler/ballerina-parser/src/test/resources/actions/remote-method-call-action/remote_method_call_assert_09.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_assert_01.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_assert_03.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_assert_04.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_source_01.bal
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_source_02.bal
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_source_03.bal
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_source_04.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/flush-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-receive-before-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-send-before-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-send-in-lambda.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker-cancelled.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker-in-action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker-peer-communication-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Team/CompilerFE

#28608 Remove unused stamping related code and fix annotation errors
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DisplayAnnotationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments_negative.bal
Labels: Team/CompilerFE

#28805 Fix `Document This` code action is suggested for irrelevant positions
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/DocumentServiceContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TypeGuardCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/UpdateDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/OptimizeImportsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/AbstractDocumentServiceContext.java
Labels: Area/LanguageServer, Team/Tooling, Type/Bug

#28704 Fix Compilation error occurs for external object methods with environment and default values
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/ConstructorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/ObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/StaticMethodTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/constructor_tests.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/object_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
Labels: Team/jBallerina

#28062 Remove error type from pure data internal compiler type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsPureTypeUniqueVisitor.java
  docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java
  docs/bir-spec/src/test/resources/test-src/values.bal
  langlib/langlib-test/src/test/resources/test-src/booleanlib_test.bal
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_bound_type_as_cet.bal
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_narrowing_for_union_return.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromBalString_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  misc/testerina/modules/testerina-core/src/main/ballerina/assert.bal
  misc/testerina/modules/testerina-core/src/main/ballerina/mock.bal
  tests/jballerina-integration-test/src/test/resources/configurables/envVarPkg/main.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/anydata/AnydataNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/anydata/AnydataTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/functions/test_different_function_signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/clone-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/null_literal_usage.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_expression.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/instance_method_tests.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/error_return_function.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_negative_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/sync-send.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/assertions-structural-types/tests/assert-test-structural-types.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/assertions/tests/assert-test.bal
Labels: Priority/Blocker, Team/CompilerFE

#28819 Fix compiler crashing for invalid match pattern
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementSyntaxErrorsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match-stmt-syntax-errors.bal
Labels: Team/CompilerFE

#28794 Fix inconsistency in typed binding patterns with var for lists
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleTupleVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/BasicTupleTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_basic_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_negative_test.bal
Labels: Team/CompilerFE

#28802 Fix locations bugs in Toml Parser AST
  misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlKeyNode.java
  misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java
  misc/toml-parser/src/test/java/toml/parser/test/ParserTestUtils.java
  misc/toml-parser/src/test/java/toml/parser/test/api/core/KeyValueTest.java
  misc/toml-parser/src/test/java/toml/parser/test/api/core/TableTest.java
Labels: Area/TOMLParser

#28561 Incoperate 'Dependencies.toml' to get updated with the build
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CompileTask.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java
  compiler/ballerina-lang/build.gradle
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Project.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/bala/BalaProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/SingleFileProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java
  compiler/ballerina-lang/src/main/java/module-info.java
Labels: Area/ProjectAPI, Priority/Blocker, Team/DevTools

#28548 Make XMLText.stringValue go through XMLSerializer
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLTextToStringConversionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_text_to_string_conversion.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#28870 Fix version matching issue for stdlibs in langserver
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
Labels: Area/LanguageServer, Team/Tooling, Type/Bug

#28488 Improve import declaration recovery
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ImportDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_assert_03.json
  compiler/ballerina-parser/src/test/resources/declarations/annot-decl/annot_decl_assert_06.json
  compiler/ballerina-parser/src/test/resources/declarations/enum-decl/enum_decl_assert_04.json
  compiler/ballerina-parser/src/test/resources/declarations/enum-decl/enum_decl_source_04.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_06.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_07.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_11.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_24.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_source_24.bal
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_43.json
  compiler/ballerina-parser/src/test/resources/expressions/anon-func/anon_func_assert_10.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_assert_03.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_15.json
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/IdentifierLiteralTest.java
Labels: Area/Parser, Team/CompilerFE

#28591 Throw error when complete is called twice
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Environment.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Future.java
  langlib/lang.runtime/src/main/java/org/ballerinalang/langlib/runtime/Sleep.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/AsyncInterop.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/AsyncTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/async_test.bal
Labels: Team/jBallerina

#28556 Add support for index access on all xml subtypes
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/InstructionEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/TypeEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/IsText.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal
Labels: Team/CompilerFE
