Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-09, with the labels that each got.

#32444 Fix iterator for immutable values from imported types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BRecordType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/api/IntersectionTypeApiTests.java
  tests/jballerina-integration-test/src/test/resources/configurables/configLibProject/modules/util/util.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configMapType/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configMapType/modules/imported_maps/imported_maps.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configOpenRecord/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configOpenRecord/modules/rest_fields/rest_fields.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configOpenRecord/record_collection_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configOpenRecord/record_map_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configRecordArray/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configRecordArray/modules/imported_records/imported_records.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configRecordType/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configRecordType/modules/imported_records/imported_records.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configRecordType/records.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configTableType/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configTableType/modules/imported_records/imported_records.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/defaultValuesRecord/main.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/readonly/ImmutabilityBalaTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_selectively_immutable/constructs.bal
Labels: Team/jBallerina

#32492 Add lock statement to the LVT
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
Labels: Team/jBallerina

#32390 [Semantic API] Fix the Symbol Lookup of Error Type Descriptor Symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config22.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config19.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeSymbolTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#32331 [Shell] Improve the error message related to reserved functions
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/InvalidMethodException.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.dcln.init.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.dcln.main.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.dcln.underscore.json
Labels: Team/CompilerFETools, Area/Shell

#32453 Return singleton type symbol for symbol() when used on singleton types
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeSymbolTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#32450 Fix signature() of ConstantSymbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaConstantSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeSymbolTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#32424 Implement equals and hashCode functions in NodeLocation
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeLocation.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/NodeLocationTest.java
Labels: Team/DevTools

#32436 Fix incorrect results with `toJson()` conversion
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TableJsonDataSource.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#32516 Port ListDefinition and ListTypeRoOps, ListTypeRwOps methods
  semtypes/spotbugs-exclude.xml
  semtypes/src/main/java/io/ballerina/semtype/BddMemo.java
  semtypes/src/main/java/io/ballerina/semtype/Common.java
  semtypes/src/main/java/io/ballerina/semtype/ListAtomicType.java
  semtypes/src/main/java/io/ballerina/semtype/definition/ListDefinition.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/ListCommonOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/ListTypeRoOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/ListTypeRwOps.java
Labels: Team/CompilerFE, Area/SemtypePort

#32502 Cleanup both PackageResolver and PackageRepository APIs to reduce potential API usages related bugs
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ResolutionOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ResolutionRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ImportModuleRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ModuleResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ResolutionEngine.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/DefaultPackageResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/AbstractPackageRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/FileSystemRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/RemotePackageRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/FileSystemRepositoryTests.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/RemotePackageRepositoryTests.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/AbstractPackageResolutionTest.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/DefaultPackageRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/PackageResolutionTestCase.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/PackageResolutionTestCaseBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/connector/BallerinaConnectorServiceImpl.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/DependencyGraphTests.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/HierarchicalPackageNameTests.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java
Labels: Area/ProjectAPI

#32530 Revert `typeof` changes done for immutable values.
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlValue.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typeof/typeof.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typedesc/typedesc_positive.bal
Labels: Team/jBallerina

#32529 Port missing error type functions
  semtypes/src/main/java/io/ballerina/semtype/Core.java
  semtypes/src/main/java/io/ballerina/semtype/Error.java
  semtypes/src/main/java/io/ballerina/semtype/PredefinedType.java
Labels: Team/CompilerFE, Area/SemtypePort

#32256 [LS] Add document symbol feature implementation
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/DocumentSymbolContext.java
  language-server/modules/langserver-core/spotbugs-exclude.xml
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/ContextBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/DocumentSymbolContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/HoverContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/documentsymbol/DocumentSymbolResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/documentsymbol/DocumentSymbolUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/documentsymbol/DocumentSymbolTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/test/resources/documentsymbol/config/config1.json
  language-server/modules/langserver-core/src/test/resources/documentsymbol/config/config2.json
  language-server/modules/langserver-core/src/test/resources/documentsymbol/source/project1/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/documentsymbol/source/project1/main.bal
  language-server/modules/langserver-core/src/test/resources/documentsymbol/source/project1/modules/types/types.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Team/LanguageServer

#32486 Port IntOps for Int semtype
  semtypes/spotbugs-exclude.xml
  semtypes/src/main/java/io/ballerina/semtype/subtypedata/IntSubtype.java
  semtypes/src/main/java/io/ballerina/semtype/subtypedata/Range.java
  semtypes/src/main/java/io/ballerina/semtype/subtypedata/RangeUnion.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/IntOps.java
Labels: Team/CompilerFE, Area/SemtypePort

#32544 Implement BooleanOps
  semtypes/spotbugs-exclude.xml
  semtypes/src/main/java/io/ballerina/semtype/subtypedata/BooleanSubtype.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/BooleanOps.java
Labels: Team/CompilerFE, Area/SemtypePort

#32495 Port StringOps for String semtype
  semtypes/spotbugs-exclude.xml
  semtypes/src/main/java/io/ballerina/semtype/EnumerableString.java
  semtypes/src/main/java/io/ballerina/semtype/EnumerableSubtype.java
  semtypes/src/main/java/io/ballerina/semtype/subtypedata/FloatSubtype.java
  semtypes/src/main/java/io/ballerina/semtype/subtypedata/StringSubtype.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/FloatOps.java
  semtypes/src/main/java/io/ballerina/semtype/typeops/StringOps.java
Labels: Team/CompilerFE, Area/SemtypePort

#32498 Use createTypeInstance instead of loadUnion
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmUnionTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
Labels: Team/jBallerina

#32401 Split constant code generating logic
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmBStringConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmBallerinaConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmMethodsSplitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmModuleConstantsGen.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/constants/constants.bal
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/CodeCoverageReportTest.java
Labels: Team/jBallerina

#32527 [Semantic API] Support Symbol Lookup by Syntax Node for Isolated Services
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByIsolatedServiceDeclTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_isolated_service_decl_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#32518 Clear caching of unknown type refs between compilations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/cyclefind/GlobalVariableRefAnalyzer.java
Labels: Team/CompilerFE

#32237 Add APIs to find references within the given document
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsWithinTargetDocumentTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/util/SemanticAPITestUtils.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/findRefProj/Ballerina.toml
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/findRefProj/main.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/findRefProj/modules/refModule/ref1.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/findRefProj/modules/refModule/ref2.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/findRefProj/ref.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#32553 Fix issue when consuming the token with invalid tokens
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/CompletionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/SingletonTypeTest.java
  compiler/ballerina-parser/src/test/resources/declarations/annot-decl/annot_decl_assert_11.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_16.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_20.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_10.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_10.bal
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_14.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_19.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_21.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_05.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_15.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_07.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_08.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_08.bal
  compiler/ballerina-parser/src/test/resources/declarations/type-def/type_def_assert_03.json
  compiler/ballerina-parser/src/test/resources/declarations/type-def/type_def_assert_04.json
  compiler/ballerina-parser/src/test/resources/declarations/type-def/type_def_assert_05.json
  compiler/ballerina-parser/src/test/resources/declarations/type-def/type_def_source_03.bal
  compiler/ballerina-parser/src/test/resources/declarations/type-def/type_def_source_04.bal
  compiler/ballerina-parser/src/test/resources/declarations/type-def/type_def_source_05.bal
  compiler/ballerina-parser/src/test/resources/expressions/byte-array-literal/base64_literal_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/new-expr/explicit-new-with-object-keyword-with-multiple-args.json
  compiler/ballerina-parser/src/test/resources/expressions/new-expr/new_expr_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_17.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_25.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_11.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_11.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_18.json
  compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_assert_12.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_assert_03.json
  compiler/ballerina-parser/src/test/resources/statements/do-stmt/do_stmt_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/do-stmt/do_stmt_source_06.bal
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_17.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_22.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_assert_25.json
  compiler/ballerina-parser/src/test/resources/statements/forEach-stmt/forEach_stmt_source_25.bal
  compiler/ballerina-parser/src/test/resources/statements/lock-stmt/lock_stmt_assert_09.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_09.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_11.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_13.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_17.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_18.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_19.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_19.bal
  compiler/ballerina-parser/src/test/resources/statements/transaction-stmt/retry_stmt_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/transaction-stmt/transaction_stmt_assert_04.json
  compiler/ballerina-parser/src/test/resources/statements/while-stmt/while_stmt_assert_05.json
  compiler/ballerina-parser/src/test/resources/statements/while-stmt/while_stmt_source_05.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_05.json
  compiler/ballerina-parser/src/test/resources/types/parameterized-type/parameterized_type_assert_13.json
  compiler/ballerina-parser/src/test/resources/types/singleton-type/singleton_type_assert_06.json
  compiler/ballerina-parser/src/test/resources/types/singleton-type/singleton_type_assert_07.json
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_assert_04.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DiagnosticsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/RemoteMethodCallActionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/VarDeclrSemanticTest.java
Labels: Team/CompilerFE, Area/Parser

#32581 Add toString() for runtime finite type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFiniteType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type_cast_expr.bal
Labels: Team/jBallerina

#32549 Fix issue in identifying function pointer vars
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/createUndefinedFunction7.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/function_call_expression_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/function_call_expression_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/function_call_expression_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/start_action_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_ctx_config14.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/FunctionTypeSymbolTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#32469 Fix langlib toStream() method issue on tuples
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTupleTest.java
  langlib/langlib-test/src/test/resources/test-src/tuplelib_test.bal
Labels: Team/jBallerina

#32017 Fix type narrowing issue in match statement
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/statements/SymbolsInMatchStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ListBindingPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/MappingBindingPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/list_binding_pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/mapping_binding_pattern.bal
Labels: Team/CompilerFE

#32600 Fix symbol owner bug in union type symbols when it's read from BIR
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config27.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config28.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config29.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config31.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config32.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config33.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config22.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config23.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config24.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/typeguard_stmt_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/typeguard_stmt_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/typeguard_stmt_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/typeguard_stmt_config4.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typeref1.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolOwnerTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_owner_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32413 Fix JSON to union assignability
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/BJSONValueTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/JSONTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/jsontype/json-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/jsontype/json-value-negative.bal
Labels: Team/CompilerFE

#32618 Fix Positional Argument Node Lookup in Semantic API
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByImportTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_import_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32601 Disable testCyclicRecordViaFields temporarily
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordTest.java
Labels: Team/CompilerFE

#32297 Fix unnecessary casting of error detail
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  langlib/langlib-test/src/test/resources/test-src/errorlib_test.bal
Labels: Team/CompilerFE

#32644 Fix isolated inference when a module contains tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/isolated/IsolatedInferenceWithTestsTest.java
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/bar/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/bar/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/bar/main.bal
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/bar/tests/test.bal
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/baz/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/baz/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/baz/main.bal
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/baz/tests/test.bal
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/foo/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/foo/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/foo/main.bal
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/foo/tests/test.bal
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/qux/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/qux/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/qux/main.bal
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/qux/tests/test.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#32598 Fix `symbol()` API for Computed Keys in Mapping Constructors
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32651 Fix inference for classes and variables in tests
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/isolated/IsolatedInferenceWithTestsTest.java
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/qux/main.bal
  tests/jballerina-integration-test/src/test/resources/isolated-inference-projects/qux/tests/test.bal
Labels: Team/CompilerFE

#32564 Add XML CDATA Section support
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserMode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STTreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STXMLCDATANode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/XMLCDATANode.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/XMLTemplateExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_31.json
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_32.json
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_source_31.bal
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_source_32.bal
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals.bal
Labels: Team/CompilerFE, Area/Parser, Lang/XML

#32522 Add io internal module implementation
  gradle/ballerinaStdLibBuild.gradle
  gradle/javaLibsProject.gradle
  misc/io-internal/build.gradle
  misc/io-internal/src/main/ballerina/Ballerina.toml
  misc/io-internal/src/main/ballerina/print.bal
  settings.gradle
  tests/ballerina-spec-conformance-tests/build.gradle
Labels: Team/CompilerFE

#32293 Disallow in loops assignments to variables narrowed outside the loop
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/narrowing/AssignmentToNarrowedVarsInLoopsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/narrowing/assignment_to_narrowed_vars_in_loops.bal
  tests/jballerina-unit-test/src/test/resources/test-src/narrowing/assignment_to_narrowed_vars_in_loops_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/whilestatement/while-stmt-on-fail.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#32593 [Shell] Remove quoted Identifers
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariableSymbol.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ImportsManager.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/types/ImportDeclarationSnippet.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/types/ModuleMemberDeclarationSnippet.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/types/VariableDeclarationSnippet.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/Identifier.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/QuotedImport.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/EvaluatorMiscTest.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/regression.same.import.json
Labels: Team/CompilerFETools, Area/Shell

#32419 Add ls cancelation support
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/DocumentServiceContext.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/LanguageExtension.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LangExtensionDelegator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/CodeLensUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codelenses/providers/DocsCodeLensesProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/PullModuleExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/BallerinaCompletionExtension.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/CompletionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/AbstractDocumentServiceContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaDefinitionContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/CodeActionContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/CompletionContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/ContextBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/FoldingRangeContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/HoverContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/PositionedOperationContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/PrepareRenameContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/ReferencesContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/RenameContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/SemanticTokensContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/SignatureContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentServiceImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/foldingrange/FoldingRangeProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/definition/DefinitionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/rename/RenameUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/diagnostics/DiagnosticsTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/util/TestUtil.java
  misc/ballerinalang-data-mapper/src/test/java/org/ballerinalang/datamapper/util/TestUtil.java
Labels: Team/LanguageServer

#32667 Fix visibility of let expression inner variables
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangBlockStmt.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/ControlFlowDebugTest.java
Labels: Team/jBallerina

#32594 Fix closure issue in nested query clauses
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  langlib/lang.query/src/main/ballerina/types.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/NestedQueriesWithEnclFuncParams.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/rawtemplate/raw_template_literal_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/queries_with_encl_func_params.bal
Labels: Team/CompilerFE

#32688 Add completion suggestions `true` and `false` at while statement condition
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/WhileStatementNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/while_stmt_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/while_stmt_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/while_stmt_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/while_stmt_ctx_config6.json
Labels: Team/LanguageServer

#32649 Add tests to `symbol()` for module level declaration
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/FunctionSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ImportDeclSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ServiceSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/util/SemanticAPITestUtils.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/class_symbols_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/function_symbols_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/module_level/Ballerina.toml
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/module_level/main.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/module_level/modules/bar/bar.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/module_level/modules/baz/baz.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/module_level/modules/foo/foo.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/module_type_def_symbols_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/service_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#32613 [LS] Implement a simulator for language server
  language-server/modules/langserver-core/spotbugs-exclude.xml
  language-server/modules/langserver-core/src/main/java/module-info.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TestUtil.java
  settings.gradle
  tests/language-server-simulator/build.gradle
  tests/language-server-simulator/spotbugs-exclude.xml
  tests/language-server-simulator/src/main/java/module-info.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/Editor.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/EditorOutputStream.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/EditorSimulator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/EditorTab.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/ClassGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/CodeSnippetGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/FunctionGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/Generators.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/MatchStatementGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/ServiceGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/StatementGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/TypeDefinitionGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/VarDeclarationStatementGenerator.java
Labels: Team/LanguageServer

#32616 Add field access completion support for error constructor expression
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config37.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/field_access_ctx_source31.bal
Labels: Team/LanguageServer

#32721 Fix showing change variable type codeaction at positional/named arguments
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/TypeGuardCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeVariableTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeGuardTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/negative_changeVarType1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/negative_changeVarType2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/negative_changeVarType1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/negative_changeVarType2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/config/typeGuardVariableCodeAction1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/config/typeGuardVariableCodeAction2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/source/typeGuardVariable1.bal
Labels: Team/LanguageServer

#32724 Ignore LS simulator module from code coverage
  .codecov.yml
Labels: Team/LanguageServer

#32682 Fix issue in parseing invalid identifier escape sequence
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticWarningCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationLexer.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QuotedStringLiteralTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/DocumentationTest.java
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/quoted_string_literal_assert_04.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_27.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_source_27.bal
  compiler/ballerina-parser/src/test/resources/misc/identifiers/invalid_identifier_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/identifiers/invalid_identifier_source_02.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/IdentifierLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-wrong-character-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string_negative.bal
Labels: Team/CompilerFE, Area/Parser

#32745 Fix issue in parseing invalid identifier escape sequence
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticWarningCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationLexer.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QuotedStringLiteralTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/DocumentationTest.java
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/quoted_string_literal_assert_04.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_27.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_source_27.bal
  compiler/ballerina-parser/src/test/resources/misc/identifiers/invalid_identifier_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/identifiers/invalid_identifier_source_02.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/IdentifierLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-wrong-character-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string_negative.bal
Labels: Team/CompilerFE, Area/Parser

#32751 Support Symbol Lookup by Syntax Node for Isolated Services
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByIsolatedServiceDeclTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol-by-node/symbol_by_isolated_service_decl_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#32746 Fix symbol owner bug in intersection type symbols when it's read from BIR
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolOwnerTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_owner_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#32672 Fix `typeof` expression for immutable values
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlValue.java
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typeof/TypeofOverLiteralExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typeof/typeof.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typedesc/typedesc_positive.bal
Labels: Team/jBallerina

#32768 Introducing "--dump-graph" and "--dump-raw-graph" hidden options to troubleshoot package resolution issues
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BuildOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BuildOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ResolutionOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/DotGraphs.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageVersionContainer.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ResolutionEngine.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/DotGraphsTests.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/VersionConflictResolutionTests.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/DefaultPackageRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/DotGraphUtils.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/LocalPackageRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/PackageRepositoryBuilder.java
  compiler/ballerina-lang/src/test/resources/dot-graphs/all-in-one-graph.dot
Labels: Area/ProjectAPI

#32761 Give detailed errors when converting to record type
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/operations.conv.json
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneUtils.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneWithType.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonWithType.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromJson_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/JSONStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/MapStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/RecordStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/StampInbuiltFunctionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/BJSONValueTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/map/ConstrainedMapTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/var/VarDeclaredAssignmentStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/map-stamp-expr-test.bal
Labels: Team/jBallerina

#32715 Reuse moduleLoadRequests of unchanged modules
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
Labels: Area/ProjectAPI

#32563 Add --sticky flag for build command
  distribution/zip/jballerina-tools/resources/command-completion/command-completion.csv
Labels: Stale

#32775 Remove unnecessary forced clone of the expr in a type cast expr
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
Labels: Team/CompilerFE

#32795 Use locked package compilation instance to avoid concurrent modifications
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/BallerinaPackageServiceImpl.java
Labels: Team/LanguageServer/Extensions

#32801 Fix issues related to Central API calls
  cli/central-client/src/main/java/org/ballerinalang/central/client/model/PackageResolutionRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/RemotePackageRepository.java
Labels: Area/ProjectAPI

#32815 Add .devcontainer.json for new command
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/CommandUtil.java
  cli/ballerina-cli/src/main/resources/new_cmd_defaults/devcontainer
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectConstants.java
Labels: Team/DevTools

#32805 Check local dependency exists before adding to dependency container in `BlendedManifest`
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/BlendedManifest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/AbstractPackageRepository.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/repositories/FileSystemRepository.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/internal/DefaultPackageRepository.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_y_having_dependency_missing_repo/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_y_having_dependency_missing_repo/fee.bal
Labels: Area/ProjectAPI

#32699 [Shell] Improve shell `/imports` command
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ImportsManager.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/EvaluatorMiscTest.java
Labels: Team/CompilerFETools, Area/Shell

#32712 Fix escaping chars in XML texts twice
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals.bal
Labels: Team/jBallerina

#32388 [LS] Add performance tests
  language-server/modules/langserver-core/build.gradle
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AbstractCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionPerformanceTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionPerformanceTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/hover/HoverPerformanceTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/hover/HoverProviderTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/performance/OpenDocumentPerformanceTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/util/PerformanceTestUtils.java
  language-server/modules/langserver-core/src/test/resources/codeaction/performance-codeaction/config/performance_codeaction.json
  language-server/modules/langserver-core/src/test/resources/codeaction/performance-codeaction/source/performance_codeaction.bal
  language-server/modules/langserver-core/src/test/resources/completion/performance_completion/config/performance_completion.json
  language-server/modules/langserver-core/src/test/resources/completion/performance_completion/sources/performance_completion.bal
  language-server/modules/langserver-core/src/test/resources/completion/performance_completion/sources/projectls/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/completion/performance_completion/sources/projectls/main.bal
  language-server/modules/langserver-core/src/test/resources/completion/performance_completion/sources/projectls/modules/module1/module1.bal
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_performance.json
  language-server/modules/langserver-core/src/test/resources/performance/config/performance_open_document/performance_open_document.json
  language-server/modules/langserver-core/src/test/resources/performance/sources/open_document_performance.bal
  language-server/modules/langserver-core/src/test/resources/performance/sources/projectls/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/performance/sources/projectls/main.bal
  language-server/modules/langserver-core/src/test/resources/performance/sources/projectls/modules/module1/module1.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
  tests/jballerina-integration-test/src/test/resources/observability/tracing_tests/Dependencies.toml
Labels: Team/LanguageServer

#32571 Handle readBuildJson exceptions in PackageResolution to disable sticky flag
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/ProjectUtilsTests.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_n/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_n/Dependencies.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_n/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_o_1_0_0/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_o_1_0_0/main.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_o_1_0_2/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_o_1_0_2/main.bal
Labels: Area/ProjectAPI

#32790 Remove invalid code actions in import module
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ImportModuleCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/config/importModule1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/config/importModule1a.json
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/config/importModule1b.json
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/config/importModule2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/source/importModule1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/source/importModule2.bal
Labels: Team/LanguageServer

#32803 Avoid providing completions inside comments
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/CompletionUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CommentContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/comment_context/config/comment_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/comment_context/config/comment_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/comment_context/config/comment_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/comment_context/config/comment_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/comment_context/config/comment_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/comment_context/config/comment_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/comment_context/source/comment_source1.bal
Labels: Team/LanguageServer

#32773 Fix NPE in BallerinaSymbol Occurring in Invocation Args Related Type Cast Code Actions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DiagnosticsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testerrorproject/diagnostic_properties_check.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32704 [Shell] Allow function names starting with `__`
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/ParserConstants.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/basics.functions.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.dcln.underscore.json
Labels: Team/CompilerFETools, Area/Shell

#32821 Support Symbol Reference Finding for Constants as Array Lengths
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32729 Fix records with optional fields type check bug
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromJson_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
Labels: Team/jBallerina

#32823 Add getConstituentTypes API for Intersection type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/IntersectionType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/api/IntersectionTypeApiTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/types/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/types/modules/objects/objects.bal
Labels: Team/jBallerina

#32275 [Semantic API] Create bounded symbols for lang lib functions
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibFunctionBinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/AbstractTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSingletonTypeSymbol.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config28.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config38.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config39.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config40.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config41.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config22.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config24.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config9.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundArrayFunctionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundMapFunctionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundStreamFunctionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundTableFunctionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundXMLFunctionsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type_param_bound_langlib_functions.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#32866 Split record and object inbuit methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmObjectGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmRecordGen.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/records/bigRecord.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/records/bigRecord1.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/records/bigRecord2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/records/bigRecord3.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/records/records.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/unions/unions.bal
Labels: Team/jBallerina

#31705 Fix type narrowing issue in multiple if-else statement
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type_test_type_narrowing_negative.bal
Labels: Team/CompilerFE

#32744 Fix toJson() conversion of table with rest type records
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TableJsonDataSource.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#32776 Add document symbols for all module-level nodes
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/documentsymbol/DocumentSymbolResolver.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/documentsymbol/DocumentSymbolTest.java
  language-server/modules/langserver-core/src/test/resources/documentsymbol/config/config1.json
  language-server/modules/langserver-core/src/test/resources/documentsymbol/config/config2.json
  language-server/modules/langserver-core/src/test/resources/documentsymbol/source/project1/main.bal
Labels: Team/LanguageServer

#32904 Remove class signature lines from Line Number Table
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/DebugInstructionTest.java
Labels: Team/jBallerina

#32552 Populate intersection type's attached functions in common path
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/imported_typedesc_test.bal
Labels: Team/CompilerFE

#32936 Add compiler plugin codeaction extension docs
  language-server/docs/CompilerPluginCodeActionExtensions.md
Labels: Team/LanguageServer

#32937 Fix symbol visibility issue related to type test expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_lookup_with_type_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32942 Fix ambiguous type for nillable union-typed optional record-field
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableForOptionalFieldAccess1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableForOptionalFieldAccess2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableForOptionalFieldAccess1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableForOptionalFieldAccess2.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32929 Add missing magic and BIR version to kaitai file
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/PackageFileWriter.java
  docs/bir-spec/build.gradle
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
Labels: Team/jBallerina

#32869 Set method annotations on service classes
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/AnnotationUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ServiceDeclTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_class_method_annot.bal
Labels: Team/CompilerFE, Lang/Object, Lang/Annotations

#32911 Improve `field-access-expr` recovery
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/AccessExpressionsTest.java
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/field_access_expr_assert_06.json
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/field_access_expr_assert_07.json
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/field_access_expr_source_06.bal
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/field_access_expr_source_07.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config42.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config43.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/field_access_ctx_source36.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/field_access_ctx_source37.bal
Labels: Team/CompilerFE, Area/Parser

#32887 Improve recovery for `named-arg` followed by a `positional-arg`
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/FuncCallExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/error-constructor-expr/error_constructor_expr_with_extra_elements_02.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_09.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_assert_20.json
  compiler/ballerina-parser/src/test/resources/expressions/func-call/func_call_source_20.bal
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/functions/FunctionSignatureInBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
Labels: Team/CompilerFE, Area/Parser
