Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-05, with the labels that each got.

#30239 Fix structures of `never` not considered as subtypes of `anydata`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BNeverType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsPureTypeUniqueVisitor.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type-runtime.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal
Labels: Team/CompilerFE

#30246 Add transaction info record fields to constants
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/constants/RuntimeConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionLocalContext.java
Labels: Team/CompilerFE

#30199 Fix worker spec deviations
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/after-wait-action-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/var-mutability-with-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-deadlock-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Lang/Workers, Team/CompilerFE

#30234 Stop jbal codegen when dependencies have errors
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
Labels: Area/ProjectAPI, Team/CompilerFE, Team/DevTools

#29942 Fix code review suggestion for 28955
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableArguments.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/identifiers/QuotedIdentifierTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal
  tests/jballerina-unit-test/src/test/resources/test-src/identifiers/error_as_identifier.bal
  tests/jballerina-unit-test/src/test/resources/test-src/identifiers/error_as_identifier_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object-field-defaultable.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#30226 Allow retrieving the intersection type from the effective type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/types/ErrorType.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/types/IntersectableReferenceType.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/types/SelectivelyImmutableReferenceType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BAnyType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BArrayType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BErrorType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BIntersectionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BMapType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRecordType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTableType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTupleType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLSubType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expressions_test.bal
Labels: Team/CompilerFE

#30270 Avoid creating types unnecessarily during type param analysis
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_resolution_with_exprs_four.bal
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_resolution_with_exprs_one.bal
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_resolution_with_exprs_three.bal
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_resolution_with_exprs_two.bal
Labels: Team/CompilerFE

#30186 Fix several recovery scenarios triggering fail-safe mechanism
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/FunctionDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ObjectTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QueryExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/MatchStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/ChildNodeListTest.java
  compiler/ballerina-parser/src/test/resources/declarations/annot-decl/annot_decl_assert_06.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_45.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_source_45.bal
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_65.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_66.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_source_65.bal
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_source_66.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_18.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_18.bal
  compiler/ballerina-parser/src/test/resources/statements/block-stmt/block_stmt_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/error_binding_pattern_assert_03.json
  compiler/ballerina-parser/src/test/resources/statements/lock-stmt/lock_stmt_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_04.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_07.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_09.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_11.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_17.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_18.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_19.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_17.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_18.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_19.bal
  compiler/ballerina-parser/src/test/resources/tree/child_node_list_test_01.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_join_clause_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_join_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_let_clause_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_let_clause_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_let_clause_config9.json
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/Parser, Team/CompilerFE

#30257 Fix Value equality checks produce incorrect results at runtime for numeric values of different basic types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/object_override_includes.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/imports/PredeclaredImportsTestProject/predeclared-modules.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_basic_test.bal
Labels: Team/jBallerina

#30080 Update error constructor desugaring
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal
Labels: Team/CompilerFE

#30254 Fix configurable table creation error
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/mod1/mod1.bal
Labels: Team/jBallerina

#30150 Fix casting issue when using var with a table returned from a query
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExpressionWithVarTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/TypeDefinitionsNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-var-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions-semantics-negative.bal
Labels: Team/CompilerFE

#30129 Fix review suggestions for #29814
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never_type_runtime.bal
Labels: Team/CompilerFE

#30121 Fix name and qualified name for certain types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/MapUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTupleType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/utils/ArrayUtils.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/BallerinaTypeCheck.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/TypesProject/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/TypesProject/main.bal
Labels: Team/jBallerina

#30267 Fix Casting a boolean value to a numeric type does not panic
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal
Labels: Team/jBallerina

#30216 Fix cast of readonly array to byte array
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal
Labels: Team/jBallerina

#30302 Address review suggestion for #30226
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BAnyType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BArrayType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BErrorType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BIntersectionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BMapType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRecordType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTableType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTupleType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLSubType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLType.java
Labels: Team/CompilerFE

#30167 Validate the undefined parts in a `Config.toml`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigResolver.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigToml.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ModuleInfo.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlContentProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlFileProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/Utils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/negative/ImportedModuleError.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/InvalidModuleStructure.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/InvalidModuleStructure1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/InvalidModuleStructure2.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/InvalidOrgName.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/InvalidOrgStructure1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/InvalidSubModuleStructure1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/OptionalImportedModule.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/SubModuleError.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/SubModuleError1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/SubModuleError2.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/UnusedTomlParts.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/ValueNotProvidedSubModule.toml
Labels: Team/jBallerina

#30251 Improve the formatting behavior of blocks
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/misc/BlocksTest.java
  misc/formatter/modules/formatter-core/src/test/resources/actions/query/assert/query_action_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/query/assert/query_action_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/send-receive/source/send_receive_action_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/send-receive/source/send_receive_action_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/start/source/start_action_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/expressions/constant/assert/constant_expression_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/expressions/constant/source/constant_expression_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/expressions/let/source/let_expression_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/blocks/assert/blocks_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/blocks/assert/blocks_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/blocks/assert/blocks_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/blocks/source/blocks_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/blocks/source/blocks_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/blocks/source/blocks_3.bal
  misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/source/ranges_4.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/behavioural/assert/handle_type_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/other/source/json_type_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/other/source/json_type_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/structured/assert/table_type_1.bal
Labels: Area/Formatting, Team/Tooling, Type/Improvement

#30159 Fix inconsistencies in `lang.xml:strip()`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  langlib/langlib-test/src/test/resources/test-src/xmllib_test_negative.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinfunctions/FreezeAndIsFrozenTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/SelectivelyImmutableTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type_langlib_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals.bal
Labels: Team/CompilerFE

#30295 Add equals and hashcode methods to diagnostic classes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnostic.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/properties/BCollectionProperty.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/properties/BNumericProperty.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/properties/BStringProperty.java
  compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/diagnostics/DiagnosticInfo.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ListBindingPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
Labels: Team/CompilerFE

#29987 Fix NPE related to record-type-inclusion
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/ClosedRecordTypeInclusionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/OpenRecordTypeInclusionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/AnonymousClosedRecordTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/anon_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record_type_inclusion.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record_type_inclusion_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion_negative.bal
  tests/jballerina-unit-test/src/test/resources/testng-jballerina.xml
  tests/jballerina-unit-test/src/test/resources/testng-new-parser.xml
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#30269 Handle unused and ambiguous command line config arguments
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigResolver.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/VariableKey.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/CliConfigProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/ConfigTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/CliProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
Labels: Team/jBallerina

#30294 Preserve `Dependencies.toml` when building the package
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/build-project-with-dependencies-toml.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/build-project-with-dependencies-toml.txt
  cli/ballerina-cli/src/test/resources/test-resources/validProjectWithDependenciesToml/Ballerina.toml
  cli/ballerina-cli/src/test/resources/test-resources/validProjectWithDependenciesToml/Dependencies.toml
  cli/ballerina-cli/src/test/resources/test-resources/validProjectWithDependenciesToml/main.bal
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java
Labels: Area/ProjectAPI, Team/DevTools

#30227 Fix issue with the order of parameter list
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/VariableReturnType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionWithIncludedRecordParam.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/identifiers/QuotedIdentifierTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/OperandCompilationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/identifiers/error_as_identifier_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/operand/invalid.bal
Labels: Team/CompilerFE

#29964 Present the Original Value Symbols for Quoted Identifiers of Reserved Keywords
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaKeywordsProvider.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectFieldSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaRecordFieldSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionTest.java
  language-server/modules/langserver-core/src/test/resources/completion/function_body/config/config7.json
  language-server/modules/langserver-core/src/test/resources/completion/function_body/source/source7.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_quoted_identifiers_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30181 Enable disabled identifier literal integration test
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/identifier/IdentifierLiteralTest.java
  tests/jballerina-integration-test/src/test/resources/identifier/PackageNameClashProject/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/identifier/PackageNameClashProject/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/identifier/PackageNameClashProject/main.bal
  tests/jballerina-integration-test/src/test/resources/identifier/PackageNameClashProject/modules/b_foo/b_foo.bal
  tests/jballerina-integration-test/src/test/resources/identifier/PackageNameClashProject/tests/test.bal
  tests/jballerina-integration-test/src/test/resources/identifier/testProject/Package.md
Labels: Team/jBallerina

#30213 Fix error when using cloneWithType with a structure that has an immutable value
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/ArrayStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/MapStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/RecordStampInbuiltFunctionTest.java
Labels: Team/jBallerina

#30312 Implement validations for the Dependencies.toml
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ManifestBuilder.java
  compiler/ballerina-lang/src/main/resources/dependencies-toml-schema.json
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/DependenciesTomlTests.java
  compiler/ballerina-lang/src/test/resources/dependencies-toml/dependency-wo-org-value.toml
  compiler/ballerina-lang/src/test/resources/dependencies-toml/dependency-wo-org.toml
  compiler/ballerina-lang/src/test/resources/dependencies-toml/invalid-org-name-value.toml
Labels: Area/ProjectAPI, Team/DevTools

#30328 Fix repeated options not throwing an error
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/cli/Option.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/cli/OptionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/cli/OptionTest.java
Labels: Team/jBallerina

#30342 Apply formatting improvements to the bindings generated
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenNodeFactory.java
  misc/ballerina-bindgen/src/main/resources/templates/empty_jclass.bal
  misc/ballerina-bindgen/src/main/resources/templates/jclass.bal
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/BindgenCommandTest.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/MavenSupportTest.java
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/constructors.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/dependentClass.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/fields.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/innerClass.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/methods.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/moduleMapping.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/throwableMapping.bal
Labels: Area/Bindgen, Team/DevTools, Type/Bug, Type/Improvement

#30400 Fix issues with Arithmetic and Shift Operators when used in Compound Assignment Statement
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal
Labels: Team/CompilerFE

#30410 Remove unused validation of cast to imported anon type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/CompilerFE

#30434 Implement query-expression visit in SymbolFinder
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30453 Fix Bad Sad Error in XML Templates
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal
Labels: Lang/XML, Team/CompilerFE

#30474 Fix xml parsing production to content
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/ConfigTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
Labels: Team/CompilerFE

#30467 [LS] Refactor detail of foreach statement completion item
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ForeachCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ForeachCompletionUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config9.json
Labels: Team/LanguageServer

#30365 Fix ballerina-shell unicode not identifying issue
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/QuotedIdentifier.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/StringUtils.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/basics.quoted.json
Labels: Area/Shell, Team/CompilerFE

#30396 Improve unimplemented method diagnostic error messages given for service-decl and object constructor
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/object/ObjectConstructorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/AbstractObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ServiceDeclTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_expression_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_negative.bal
Labels: Area/Diagnostics, Team/CompilerFE

#30479 Return Null as the Symbol of Wildcard Binding Pattern (`_`)
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BVarSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/BindingPatternTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30256 Fix incorrect symbol returning issue when using `symbol()` for typesdescs
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ImportsManager.java
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config27.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config22.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config23.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/typeguard_stmt_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/typeguard_stmt_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/typeguard_stmt_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/typeguard_stmt_config4.json
  language-server/modules/langserver-core/src/test/resources/extensions/document/syntaxTree/locate/locateModulePartNode.json
  language-server/modules/langserver-core/src/test/resources/extensions/document/syntaxTree/locate/locateNodeList.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typeref1.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#30517 Fix IndexOutOfBoundsException in LS
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
  project-api/project-api-test/src/test/resources/projectForDocumentIdTest/Ballerina.toml
  project-api/project-api-test/src/test/resources/projectForDocumentIdTest/main.bal
  project-api/project-api-test/src/test/resources/projectForDocumentIdTest/modules/winery1/winery1.bal
Labels: Area/ProjectAPI, Team/DevTools

#30469 Improve unsupported worker send error message
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/actions-negative.bal
Labels: Team/CompilerFE

#30355 Allow access expressions on all `BLangExpression`s
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/MockDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangAccessExpression.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangAnnotAccessExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangBinaryExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangCheckedExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangElvisExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangExpression.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangGroupExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangIntRangeExpression.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangInvocation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangListConstructorExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangQueryExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangRawTemplateLiteral.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangRecordLiteral.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangStringTemplateLiteral.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTableConstructorExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTableMultiKeyExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTernaryExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTypeConversionExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangUnaryExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangValueExpression.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangVariableReference.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangXMLElementAccess.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangXMLNavigationAccess.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangCompoundAssignment.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/access.bal
Labels: Team/CompilerFE

#30407 Remove unused classes
  bvm/ballerina-runtime/spotbugs-exclude.xml
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/services/EmbeddedExecutorProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/services/ErrorHandlerUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/services/JVMEmbeddedExecutor.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/services/spi/EmbeddedExecutor.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/ArgumentParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserPositiveTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_function_rest_args.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_rest_args_missing.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_array_param.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_defaultable_param.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_error_or_nil_return.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_float_array_param.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_int_array_param.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_int_param.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_map_param.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_multiple_typed_params.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_nil_return.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_no_params.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_oneD_array_param.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_optional_defaultable_param.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_optional_param.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_params.bal
  tests/jballerina-unit-test/src/test/resources/test-src/main.function/test_main_with_xml_param.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#30346 Fix recursive toString call in intersection types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BIntersectionType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/typedesc/TypedescTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/test_intersection_type.bal
Labels: Team/CompilerFE

#30539 Improve method/remote method name collision diagnostic message
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/test/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLogTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/endpoint/ClientObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/endpoint/new/remote_basic_negative.bal
Labels: Team/CompilerFE

#30553 Add a new API for getting the unflattened member types of a union
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/UnionTypeSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30551 Prevent singleton type true from being return as type of an annotation symbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  compiler/ballerina-lang/src/test/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLogTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/AnnotationsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/annotations_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30526 Improve the formatting of empty records and inline records
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/expressions/range/assert/range_expression_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/behavioural/assert/streams_type_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/structured/assert/record_type_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/structured/source/record_type_1.bal
Labels: Area/Formatting, Team/Tooling, Type/Improvement

#30482 Add recordtype descriptor completion item to error type paramater context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/config/error_typedesc1.json
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/config/error_typedesc2.json
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/config/error_typedesc5.json
Labels: Team/LanguageServer

#30557 Fix review suggestions for PR #30553
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#30386 Fix bad, sad error with error:CallStack
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BObject.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ObjectValue.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibErrorTest.java
  langlib/langlib-test/src/test/resources/test-src/errorlib_test.bal
Labels: Team/jBallerina

#30560 Fix worker acton system index out of bound error
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-deadlock-negative.bal
Labels: Team/CompilerFE

#30309 Add type narrowing support for == and !=
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/elseif_stmt_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/elseif_stmt_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config3.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/IfElseStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/$lambda$_0
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/if-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/whilestatement/while-stmt.bal
Labels: Team/CompilerFE

#30471 Fix equality check with tables and missing final variable assignment check with compound assignment
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromBalString_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableValueAssignTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment_dataflow_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_value_assign_test.bal
Labels: Team/CompilerFE

#30572 Fix rename not working with XML navigation
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30499 Make configurable variables implicitly final and readonly
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_14.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_15.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_17.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_14.bal
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_source_15.bal
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_32.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_source_32.bal
  observelib/observe/src/main/ballerina/commons.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolFlagToQualifierMappingTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/imports/ImportsNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/imports/InvalidImportTestProject/invalid-import-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_global_var_decl_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_global_var_decl_negative_02.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_global_var_decl_negative_03.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_decl.bal
Labels: Team/CompilerFE

#30554 [Bindgen] Make improvements to error handling and output messages
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindingsGenerator.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenEnv.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenFileGenerator.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenMvnResolver.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenNodeFactory.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenTreeModifier.java
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenUtils.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/BindgenCommandTest.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/FieldsTestResource.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/MavenSupportTest.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/MethodsTestResource.java
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/tests/main_test.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/fields.bal
  misc/ballerina-bindgen/src/test/resources/unit-test-resources/methods.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/bindgen/BindgenTestCase.java
Labels: Area/Bindgen, Team/DevTools, Type/Improvement

#30144 Fix issue with local anonymous records and no error when missing variable with user-defined types
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/AnonymousRecordNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/AssignStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/anon_record_isolation_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/anon_record_semantic_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt.bal
Labels: Team/CompilerFE

#30371 Improve xml navigation type checking by using xml subtyping
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-nav-access-type-check-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-navigation-access.bal
Labels: Lang/XML, Team/CompilerFE

#30495 Validate type param on error type-descriptor
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_test_negative.bal
Labels: Team/CompilerFE

#30576 Fix CCE when casting an invocation to a BLangValueExpression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
Labels: Priority/Blocker, Team/CompilerFE

#30534 Add support for map type configurable variables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigResolver.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/Utils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/MapTypeConfig.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/InvalidIntersectionArray.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/MapFieldStructureError.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/MapFieldTypeError.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/MapTypeError.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/UnsupportedArrayType.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/UnsupportedConstraintRecordType.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/UnsupportedMapType.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configLibProject/modules/mod1/lib.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/mod1/mod1.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/mod2/mod2.bal
Labels: Team/jBallerina

#30563 Fix invalid `pattern will not be matched` error
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtListMatchPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/list-match-pattern.bal
Labels: Team/CompilerFE

#30582 Update performance test results for Ballerina Swan Lake Alpha 5
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Team/StandardLibs, Type/Task

#30506 Fix and enable more tests
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ResilientParserTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/StringQueryExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordEquivalencyTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayInitializerExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayLValueFillTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/AssignStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/comment/CommentStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/expressionstmt/ExpressionStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementStaticPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementSyntaxErrorsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtErrorMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtListMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredErrorPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredRecordPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredTuplePatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ListBindingPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/onfail/OnFailClauseTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/packageimport/PackageImportTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ErrorVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ForwardReferencingGlobalDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/VariableScopeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/string-query-expression.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign_stmt_semantic_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/comment/comments.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns_semantics_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_error_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_error_match_patterns_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_error_match_patterns_negative2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_match_patterns_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_record_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/structured_tuple_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/package/sample-project-2/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/statements/package/sample-project-2/foo-impl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/package/sample-project-2/modules/bar/bar.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/globalcycle/viaServiceProject/file01.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/variable-scope-negative.bal
Labels: Team/CompilerFE

#30372 Introduce type-descriptor precedence support to parser
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/OperatorPrecedence.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/TypePrecedence.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/IntersectionTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/TupleTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/TypePrecedenceTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/UnionTypeTest.java
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_12.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_06.json
  compiler/ballerina-parser/src/test/resources/types/intersection-type/intersection_type_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_assert_02.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_assert_03.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_assert_04.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_assert_05.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_source_01.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_source_02.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_source_03.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_source_04.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_source_05.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_assert_01.json
  misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java
  misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Type.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/distinct-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error_intersection_type_negative.bal
Labels: Area/Parser, Team/CompilerFE

#30583 Improve error msg for invalid final qual with configurable
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_15.json
  compiler/ballerina-parser/src/test/resources/declarations/module-var-decl/module_var_decl_assert_17.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_global_var_decl_negative.bal
Labels: Area/Parser, Team/CompilerFE

#30591 [LS] Add record construtor completion item to annotation definition context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AnnotationDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_decl/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_decl/config/config2.json
Labels: Team/LanguageServer

#30600 Enable `testBallerinaTomlWithInvalidOrgNameVersion` on windows
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/BallerinaTomlTests.java
Labels: Area/ProjectAPI, Area/TOMLParser, Team/DevTools

#30610 Add compound assignment and closure negative test cases for type narrowing
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/IfElseStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closure_negative_02.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/if-stmt-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/if-stmt.bal
Labels: Area/Compiler, Area/UnitTest, Team/CompilerFE

#30602 Fix null pointer at invalid record parsing
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/RecordTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_assert_20.json
  compiler/ballerina-parser/src/test/resources/declarations/record-type-def/record_type_def_source_20.bal
Labels: Area/Parser, Team/CompilerFE

#30456 Set error to waitExpr
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  docs/bir-spec/src/test/resources/test-src/types_and_operations.bal
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/maplib_test.bal
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/wait_action_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/wait_action_ctx_config7.json
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/CallStackDebugTest.java
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/callstack-tests/main.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/control-flow-tests/main.bal
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/variable-tests/main.bal
  tests/jballerina-integration-test/src/test/resources/observability/tracing_tests/05_concurrency.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAllActionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/action/nested_actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/action/start/StartTypeCastProject/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/action/start/start_action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/action/typecast_action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/async/basic-async-operations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_with_public_api.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_bir_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/parallelism.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/packageinit/pc.bal
  tests/jballerina-unit-test/src/test/resources/test-src/taintchecking/propagation/global-func-pointer-async-invocation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/future/future_positive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/actions-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/not-so-basic-worker-actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/var-mutability-with-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-actions-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-for-all-actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-for-any-actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-for-one-actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Team/CompilerFE

#30545 Return an error if asked to wait on completed future
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/FutureValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/future/FutureNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/future/FuturePositiveTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/async/basic-async-operations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/future/future_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/future/future_negative_compilation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/future/future_positive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Team/jBallerina

#30630 Fix `fromBalString` omitting key information with keyed tables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BalStringUtils.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromBalString_test.bal
Labels: Team/CompilerFE

#30627 Add support for BLangClassDefinition in GlobalVariableRefAnalyzer
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/cyclefind/GlobalVariableRefAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ForwardReferencingGlobalDefinitionTest.java
Labels: Team/CompilerFE

#30619 Initialize static fields at code-gen level
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
Labels: Team/CompilerFE

#30655 Fix dependently-typed functions with casts
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/readonly/SelectivelyImmutableTypeBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/InferredDependentlyTypeFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/BJSONValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature_negative.bal
Labels: Team/CompilerFE

#30494 Fix jvmCodegen throws an error when lambda is returned from a function that returns a union
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/LambdaGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/function-pointers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
Labels: Team/jBallerina

#30646 Fix issue in parsing conditional expression
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/ConditionalExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_26.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_source_26.bal
Labels: Area/Parser, Team/CompilerFE

#30354 Fix incorrect results with maps and arrays of int and string subtypes
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/anydata/AnydataTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_test.bal
Labels: Team/jBallerina

#30663 Relax restriction on having to access `self` within a lock statement of isolated objects even when safe
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/BallerinaTomlTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
Labels: Team/CompilerFE

#30676 Fix nested access on intersection types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/OptionalFieldAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access_negative.bal
Labels: Team/CompilerFE

#30682 Fix intersection computation with intersection types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Team/CompilerFE

#30703 Fix issue in doc code block
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
Labels: Priority/Blocker, Team/CompilerFE

#30704 Fix incorrect parsing of field access expression
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ClassDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/FunctionDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/FunctionTypeTest.java
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_44.json
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_source_44.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_32.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_source_32.bal
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_assert_17.json
  compiler/ballerina-parser/src/test/resources/types/func-type/func_type_source_17.bal
Labels: Area/Parser, Team/CompilerFE

#30712 Fix validating table key as literal
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableValueAssignTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_value_assign_test.bal
Labels: Team/CompilerFE

#30713 Fix using type refs as the typedesc symbol for vars/fields referring to a function
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/regression-tests/field_with_function_type.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#27234 Stop removing `.bal` from generated method's classes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
Labels: Team/jBallerina

#30727 Fix two issues with isolation analysis
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedVariableTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables_isolation_negative.bal
Labels: Team/CompilerFE

#30748 Fix completion for lang-lib functions with only rest-param
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/AbstractTypeSymbol.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/field_access_ctx_config27.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config13.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
Labels: Area/SemanticAPI, Team/CompilerFE

#30731 Fix NPE
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BuildOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptionsBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/CompilerPhaseRunner.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ManifestBuilder.java
  compiler/ballerina-lang/src/main/java/module-info.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/CompilerOptionName.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TaintAnalyzer.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/CloneOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/ExprBodiedFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleErrorVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleRecordVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleTupleVariableTest.java
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#30744 Return false for public keyword in isEndOfModuleLevelNode inside object member
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ServiceDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_21.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_21.bal
Labels: Area/Parser, Team/CompilerFE

#30647 Improve `annotation-decl` recovery
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STInvalidNodeMinutiae.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STMissingToken.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STToken.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STTreeModifier.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/AnnotationDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/declarations/annot-decl/annot_decl_assert_10.json
  compiler/ballerina-parser/src/test/resources/declarations/annot-decl/annot_decl_assert_12.json
  compiler/ballerina-parser/src/test/resources/declarations/annot-decl/annot_decl_source_10.bal
  compiler/ballerina-parser/src/test/resources/declarations/annot-decl/annot_decl_source_12.bal
  compiler/ballerina-treegen/src/main/resources/internal_tree_modifier_template.mustache
Labels: Area/Parser, Team/CompilerFE

#30762 Set position info to named arg exprs created in Unifier
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expressions_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/inferred_dependently_typed_fn_signature_test.bal
Labels: Area/SemanticAPI, Team/CompilerFE

#30771 Fix Object mocking withArgs for Typedesc params
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/GenericMockObjectValue.java
Labels: Area/Testerina, Team/TestFramework

#30775 Fix codegen for record optional fields
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
Labels: Team/jBallerina

#30801 Introduce several changes/fixed for `isolated`
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticWarningCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/DataflowAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationInferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationWarningTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ForwardReferencingGlobalDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_warnings_for_service_methods.bal
Labels: Team/CompilerFE

#30773 Improve the indentation of object constructors when formatting
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object-constructor-with-annotations.bal
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object-constructor-with-annotations.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object-constructor-with-basic-object-fields.bal
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object-constructor-with-basic-object-fields.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object-constructor-with-client-keyword.bal
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object-constructor-with-client-keyword.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object-constructor-with-type-reference.bal
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object-constructor-with-type-reference.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object_constructor_assert_08.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object_constructor_assert_10.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object_constructor_source_08.bal
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object_constructor_source_10.bal
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/service_object_constructor_assert_01.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/service_object_constructor_assert_02.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/service_object_constructor_source_01.bal
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/service_object_constructor_source_02.bal
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/misc/blocks/assert/blocks_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/behavioural/assert/object_type_1.bal
Labels: Area/Formatting, Team/Tooling, Type/Improvement

#30836 Remove type flags information from generated hash
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeHashVisitor.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/IntegerRangeOperatorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/integer-range-operators-runtime.bal
Labels: Team/CompilerFE

#30850 Fix build from outside of project with maven dependency
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/ResolveMavenDependenciesTask.java
Labels: Team/DevTools

#30885 Allow queries in type narrowed environments - stage-slbeta1
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_where_clause_config1.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExpressionWithinTypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closures_in_resource.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-within-type-guards.bal
Labels: Team/CompilerFE

#30896 Improve distinct type id calculation for type-inclusions and intersection types
  bvm/ballerina-runtime/src/main/java/module-info.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTypeIdSet.java
  docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java
  langlib/lang.typedesc/src/main/ballerina/typedesc_lib.bal
  langlib/lang.typedesc/src/main/java/module-info.java
  langlib/lang.typedesc/src/main/java/org/ballerinalang/langlib/typedesc/TypeIds.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTypedescTest.java
  langlib/langlib-test/src/test/resources/test-src/typedesclib_test.bal
  langlib/langlib-test/src/test/resources/testng.xml
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/DistinctObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/DistinctTypeDefTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/distinct_objects_type_inclusion_test.bal
Labels: Team/CompilerFE
