Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-10, with the labels that each got.

#32868 Support `symbol()` Method for Annotation Tag References
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#32927 Fix equality of byte and int subtypes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
Labels: Team/jBallerina

#32933 Add bad sad error message in missing places
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/constants/RuntimeConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/Main.java
  cli/ballerina-cli/src/main/resources/cli-help/internal-error-message.txt
Labels: Team/jBallerina

#32961 Give detailed errors when casting to record type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromJson_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type_cast_expr.bal
Labels: Team/jBallerina

#32896 Move tuple type creation to a constant class
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTupleTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmUnionTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/BTypeHashComparator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/TypeDefHashComparator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/InstructionEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeHashVisitor.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/tuples/large_tuple.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/tuples/tuple_types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largePackage/modules/tuples/tuples.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/list-match-pattern.bal
Labels: Team/jBallerina

#32988 Add support for create function within if statements
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CreateFunctionCommandExecTest.java
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_expression1.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_if_statement1.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_if_statement2.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_if_statement3.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_if_statement4.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_expression1.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_if_statement1.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_if_statement2.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_if_statement3.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_if_statement4.bal
Labels: Team/LanguageServer

#32923 Remove unnecessary temp variables from method frames
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/FrameClassGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/$lambda$_0
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/complexAddition
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/mapInits
Labels: Team/jBallerina

#33020 Split type creation codegen
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/TypeNamePair.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmMethodsSplitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmValueCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmBStringConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmBallerinaConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmModuleConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmTupleTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmUnionTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmErrorCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmObjectCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmRecordCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmErrorTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmObjectTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmRecordTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmTupleTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmUnionTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/values/JvmObjectGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/values/JvmRecordGen.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/CodeCoverageReportTest.java
Labels: Team/jBallerina

#32986 Do not support single quote for json string
  bvm/ballerina-core/src/main/java/org/ballerinalang/core/model/util/JsonParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/JsonParser.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/JSONLibraryTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/JSONTest.java
Labels: Team/jBallerina

#32915 Fix issues with string concatenation
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/AddOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation.bal
Labels: Team/jBallerina

#32183 Support action invocation with TypeInit
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/start/ObjectFieldFunctionPointerStartActionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/action/start/object_field_start_method_invocation.bal
Labels: Team/CompilerFE

#32947 Fix global variable reordering with object constructor expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_field_initializer_with_check.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/oce_depend_on_global_variable.bal
Labels: Team/CompilerFE, Lang/Expressions/ObjectConstructor

#32812 Add module level components to package service
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/BallerinaPackageServiceImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/DocumentComponentsVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/PackageServiceConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/packages/ComponentsTest.java
  language-server/modules/langserver-core/src/test/resources/packages/components/multiple-packages_expected.json
  language-server/modules/langserver-core/src/test/resources/packages/components/project-other_expected.json
  language-server/modules/langserver-core/src/test/resources/packages/components/single-file-package_expected.json
  language-server/modules/langserver-core/src/test/resources/packages/components/single-package_expected.json
  language-server/modules/langserver-core/src/test/resources/packages/configs/project-other/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/packages/configs/project-other/main.bal
  language-server/modules/langserver-core/src/test/resources/packages/configs/project-other/modules/models/model.bal
  language-server/modules/langserver-core/src/test/resources/packages/configs/project-services/modules/hello_service/hello.bal
  language-server/modules/langserver-core/src/test/resources/packages/configs/single-file/main.bal
Labels: Team/LanguageServer/Extensions

#33082 Disable pull module codeaction
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/PullModuleCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/PullModuleCodeActionTest.java
Labels: Team/LanguageServer

#33019 Add spec conformance tests for `typeOf()`
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfQueryExprTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expressions_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#32763 Add spec conformance tests for module level declaration and annotations
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/AnnotationSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ConstDeclSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/EnumDeclSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/FunctionSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/VarDeclSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/XMLNamespaceDeclSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/annotation_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/const_decl_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/enum_decl_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/var_decl_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/xmlns_decl_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#32941 Set Appropriate Positions of `BLangXMLNavigationAccess` expressions.
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/SymbolsInXMLNavigationExprsTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#33008 Add fine grained error handling to CodeActionManager
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CodeActionManager.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CodeActionResult.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/codeaction/CodeActionException.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/codeaction/PositionedActionContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/codeaction/PositionedActionContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CompilerPluginCodeActionExtension.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/LanguageServerExtensionTests.java
Labels: Team/LanguageServer

#32873 Fix incorrect member types for union type definition
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/UnionTypeSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/union_type_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI
