Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-12, with the labels that each got.

#33947 Find References of `expr` in Annotation Access Expression
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/AnnotationRefsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_ref_annotation_context.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#33945 Disable renaming for self keyword
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/rename/RenameUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/rename/RenameTest.java
  language-server/modules/langserver-core/src/test/resources/rename/expected/single/rename_self.json
Labels: Team/LanguageServer

#34090 Fix change var type code action for record fields
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeVariableTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/negative_changeVarType3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/negative_changeVarType3.bal
Labels: Team/LanguageServer

#34091 Improve service type inference to type-ids
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/lang.typedesc/src/main/java/org/ballerinalang/langlib/typedesc/TypeIds.java
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_distinct_listener_arg.bal
Labels: Team/CompilerFE

#33936 Fix incorrect resulting type of `unary-plus` expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/unaryoperations/UnaryExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/unaryoperations/unary-operation.bal
Labels: Team/CompilerFE

#33807 Deprecate `parseStatements` and introduce `parseBlockStatement` instead
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ExpressionTrial.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/StatementTrial.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/NodeParserLineRangeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseBlockStatementTest.java
  misc/ls-extensions/modules/partial-parser/src/main/java/io.ballerina.parsers/PartialParserService.java
Labels: Team/CompilerFE, Area/SyntaxAPI

#34099 Improve error for unused module prefixes
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/OptimizeImportsCodeAction.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/packageimport/PackageImportTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/package/imports/unused-imports-negative.bal
Labels: Team/CompilerFE

#33821 Fix crash when using let expressions in xml-template-expr
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/let/LetExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal
Labels: Team/CompilerFE

#33964 Fix typedesc resolving for remote methods return type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/VariableReturnType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/DependentlyTypedFunctionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal
Labels: Team/CompilerFE

#33860 Review the 'Module.md' Description
  observelib/observe/src/main/ballerina/modules/mockextension/Module.md
Labels: Stale

#34107 Use same symbol within type definition type and reference type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/TransactionDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/CompilerFE

#34039 Add qname-ref completions to check expression context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/CheckExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/check_expression_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/projectls/defmodsource3.bal
Labels: Team/LanguageServer

#33971 Refactor expression node resolution logic in code actions
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/spi/DiagBasedPositionDetails.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddCheckCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeCastTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/config/add_check_codeaction_config4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/config/add_check_codeaction_config5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/source/add_check_codeaction_source4.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast10.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast11.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast9.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCastNegative4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/typeCast.bal
Labels: Team/LanguageServer

#34100 Add runtime error for out of range exponents in decimal values
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/cli/CliUtil.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/cli/OptionTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/CliProviderNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalUsageTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_usage.bal
Labels: Team/jBallerina

#33806 Split big BIR functions based on instruction type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/functions/helper-functions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/functions/large-init-function.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/functions/large-user-defined-function.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/objects/large-class.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/records/large-record.bal
Labels: Team/jBallerina

#34137 Fix NPE in BIR symbol enter
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTypeReferenceType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/TypeReferenceTypeBalaTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/type_reference_type_bala_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/type_reference_type_bala_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_type_reference_types/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_type_reference_types/types.bal
Labels: Team/CompilerFE

#34130 Flatten type reference union type members
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/config/typeGuardVariableCodeAction3.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config39.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/UnionTypeSymbolTest.java
Labels: Team/CompilerFE

#34149 Fix parsing `Foo[]|Bar? [a, b] = expr;`
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_26.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_26.bal
Labels: Team/CompilerFE, Area/Parser

#34117 Fix `slice()` returning fixed size array for tuples
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Slice.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Team/jBallerina

#34065 Improve printed error for error returning `main` function
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/execution/ModuleExecutionFlowTests.java
Labels: Team/jBallerina

#34148 Update unnecessary `check`s as warnings
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticWarningCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/linter-plugin/src/main/java/io/ballerina/compiler/linter/impl/codeactions/Constants.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkpanicexpr/CheckPanicExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/trap/TrapOperatorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_semantics_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkpanicexpr/check_panic_expr_negative.bal
Labels: Team/CompilerFE

#33668 Fix "Type param analysis doesn't seem to be happening properly for infer-anonymous-function-expr"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal
  langlib/langlib-test/src/test/resources/test-src/tablelib_test_negative.bal
Labels: Team/CompilerFE

#34112 Support finite types in string template expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTemplateLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-template-literal.bal
Labels: Team/CompilerFE

#33829 Add resolve dependency extension to LS
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentServerCapabilities.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentServiceServerCapabilitySetter.java
Labels: Stale

#33774 Fix ignoring rest field in record literals while inferring table constraint type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/map-constraint-table-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/record-constraint-table-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-negative.bal
Labels: Team/CompilerFE

#34153 Add the file scheme validation API
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/LanguageExtension.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LangExtensionDelegator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/BallerinaCompletionExtension.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/toml/ballerinatoml/completion/BallerinaTomlCompletionExtension.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/exprscheme/TestExpressionFileScheme.java
Labels: Team/LanguageServer

#34167 Add toml document selector
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
Labels: Team/LanguageServer

#34147 Update workspace proxy to handle bala uri scheme
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/definition/DefinitionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/references/ReferenceTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/references/ReferencesTest.java
Labels: Team/LanguageServer

#34177 Fix bug in multi-level type referencing chains
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config55.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config56.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typedescriptors/TypeReferenceTSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedescriptors/typeref_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#34084 Obtain the Determine Type of Start Action Invocations
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#34214 Fix issue 34199 for optimize imports code actions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/OptimizeImportsCodeAction.java
Labels: Team/LanguageServer

#34220 Fix several issues with type reference types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_analysis_with_type_reference_types_test_1.bal
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_analysis_with_type_reference_types_test_2.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/object/ObjectConstructorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_expression.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_expression_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition.bal
Labels: Team/CompilerFE

#34134 Fix function names in class symbol hover and hover over new expressions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_classdef1.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_classdef2.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_classdef3.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_classdef4.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_new_expr1.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_new_expr2.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_new_expr3.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_new_expr4.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_new_expr5.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_performance.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typedef4.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typedef5.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typeref1.json
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_classdef.bal
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_new_expr1.bal
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_new_expr2.bal
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_new_expr3.bal
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_new_expr4.bal
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_new_expr5.bal
Labels: Team/LanguageServer

#34223 Fix support for braced expressions in add check code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddCheckCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/config/add_check_with_parantheses_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/source/add_check_with_parantheses_source1.bal
Labels: Team/LanguageServer

#34215 [beta6] Support check expression inside split BIR function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/functions/helper-functions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/functions/large-user-defined-function.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/objects/large-class.bal
Labels: Team/jBallerina

#34209 Fix codegen for int subtype field in records
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/values/JvmRecordGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/integer/BIntegerValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value.bal
Labels: Team/jBallerina

#34246 Fix type reference types across modules
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/TypeReferenceTypeBalaTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/type_reference_type_bala_test_2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_type_reference_types_2/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_type_reference_types_2/types.bal
Labels: Team/CompilerFE

#34053 Set `NONE` Type Descriptor Kind for `NONE` and `OTHER` Type Kinds
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  language-server/modules/langserver-core/src/test/resources/completion/listener_decl/config/config7.json
  language-server/modules/langserver-core/src/test/resources/completion/listener_decl/config/config8.json
  language-server/modules/langserver-core/src/test/resources/completion/module_const_context/config/config2.json
  language-server/modules/langserver-core/src/test/resources/extensions/document/syntaxTree/locate/locateImportsNode.json
  language-server/modules/langserver-core/src/test/resources/extensions/document/syntaxTree/locate/locateMemberNode.json
  language-server/modules/langserver-core/src/test/resources/extensions/document/syntaxTree/locate/locateModulePartNode.json
  language-server/modules/langserver-core/src/test/resources/extensions/document/syntaxTree/locate/locateNodeList.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DiagnosticsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testerrorproject/diagnostic_properties_check.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#34185 Fix not considering variable initializations within a `while` loop as partial initializations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/DataflowAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finaltypes/FinalAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/dataflow-analysis-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/dataflow_analysis_initialized_var_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/finaltypes/test_final_var_negative.bal
Labels: Team/CompilerFE

#34180 Improve `call-stmt` recovery for partially written `method-call-expr`
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/CallStatementTest.java
  compiler/ballerina-parser/src/test/resources/statements/call-stmt/call_stmt_assert_10.json
  compiler/ballerina-parser/src/test/resources/statements/call-stmt/call_stmt_source_10.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/check_expression_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/check_expression_ctx_source8.bal
Labels: Team/CompilerFE, Area/Parser

#34206 Update LS simulator workflow to exit on timeout gracefully
  .github/workflows/language_server_simulator.yml
  tests/language-server-simulator/build.gradle
  tests/language-server-simulator/spotbugs-exclude.xml
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/EditorSimulator.java
Labels: Team/LanguageServer

#34231 Fix crash when analyzing exportable types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/access/SymbolExposureTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/access/symbol_exposure.bal
Labels: Team/CompilerFE

#34173 [Shell] Allow multiple expressions in the same line
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ExpressionListTrial.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/basics.modules.json
Labels: Team/CompilerFETools, Area/Shell

#34182 Fix completion item sorting in start action context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/StartActionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/start_action_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/start_action_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/start_action_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/start_action_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/start_action_ctx_config5.json
Labels: Team/LanguageServer

#34123 Fix issue in tracking field references in index-based access exprs
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#33880 Fix illegal cyclic reference identified in a custom listener with service reference
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/listener/ListenerBalaTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/listener/custom_listener_with_service.bal
Labels: Team/CompilerFE

#34191 Fix create variable code actions with tuple with a rest type descriptor
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTupleTypeSymbol.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeGuardTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableWithTuple1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithTuple1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/config/typeGuardWithTuple1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/source/typeGuardWithTuple1.bal
Labels: Team/LanguageServer

#34261 Fix additional space at the end of the documentation generated
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocAttachmentInfo.java
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addObjectFunctionDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addResourceFunctionDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleFunctionDocumentation1.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleFunctionDocumentation2.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleObjectDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleRecordDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleServiceDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/add_single_documentation_with_deprecated1.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/add_single_documentation_with_deprecated2.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/serviceDocumentationWithAnnotations.json
Labels: Team/LanguageServer

#34257 Fix service definition context completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModuleVariableDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config5.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config6a.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config6b.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config6c.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config6d.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config6e.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config6f.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config6g.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config6h.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/source/source6a.bal
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/source/source6b.bal
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/source/source6c.bal
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/source/source6d.bal
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/source/source6e.bal
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/source/source6f.bal
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/source/source6g.bal
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/source/source6h.bal
Labels: Team/LanguageServer

#34192 Fix handling integer overflows in `lang.int:sum` function
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/MathUtils.java
  langlib/lang.int/src/main/java/org/ballerinalang/langlib/integer/Sum.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibIntTest.java
  langlib/langlib-test/src/test/resources/test-src/intlib_test.bal
Labels: Team/CompilerFE

#34184 Fix issue in member access expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal
Labels: Team/CompilerFE, Area/TypeChecker

#34262 Fix nested conditional expr ambiguity resolution
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/utils/ConditionalExprResolver.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/ConditionalExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_27.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_28.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_29.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_30.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_source_27.bal
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_source_28.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Team/CompilerFE, Area/Parser

#34249 Fix issue in parsing tuple type or list constructor
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/UnionTypeTest.java
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_assert_21.json
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_assert_07.json
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_01.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_06.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_07.bal
Labels: Team/CompilerFE, Area/Parser

#33973 Fix inferred type in `table-constructor` for fields with same name but different types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/RecordConstraintTableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/map-constraint-table-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/record-constraint-table-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-negative.bal
Labels: Team/CompilerFE, Area/TypeChecker

#34305 Remove deprecated and marked for removal `parseStatements()` for GA
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseStatementsTest.java
Labels: Team/CompilerFE, Area/SyntaxAPI

#33898 Fix symbol type of `Constants`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/var_ref_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/assignment_stmt_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/start_action_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_ctx_config6.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/EnumDeclSymbolTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal
Labels: Team/CompilerFE

#34295 Set method params to invokable symbol of object intersection's methods in BIR symbol enter
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/readonly/ImmutabilityBalaTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_selectively_immutable_type_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_selectively_immutable/constructs.bal
Labels: Team/CompilerFE

#34110 Fix missing in-scope symbols issue for expressions/actions with scope
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/config/let_expr_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/config/let_expr_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/config/let_expr_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/config/let_expr_ctx_config7.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInExpressionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInQueryActionsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/symbol_lookup_in_query_actions.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/visible_symbols_in_exprs_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#34290 Update optional record field direct access suggestions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/RecordFieldCompletionItem.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/FieldCompletionItemBuilder.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config1a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config2a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config35.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config36.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config3a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5b.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5c.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_within_param_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config4.json
Labels: Team/LanguageServer

#34344 Add `decodeIdentifier()` runtime API for log module
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/IdentifierUtils.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPITest.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/util/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/util/main.bal
Labels: Team/jBallerina

#34329 Add/read param annotation attachment symbols to/from the BIR
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/annotations/param_annot_attachments_bala_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_annotation_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_annotation_project/annotations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_annotation_usage_project/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_annotation_usage_project/annotations_usage.bal
Labels: Team/CompilerFE

#34079 Disallow optional fields in record binding pattern
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/statements/SymbolsInAssignmentStatementsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/VarDeclSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/statements/symbols_in_assignment_stmt.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/var_decl_symbol_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/RecordVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleRecordVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleTupleVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finaltypes/FinalTypedBindingPatternsNegative.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/negative/record-destructure-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_record_var_decl_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_tuple_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/finaltypes/final-typed-binding-patterns-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_basic_test.bal
Labels: Team/CompilerFE

#34350 Add WorkDoneProgress notification for service template generator
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ServiceTemplateGenerator.java
Labels: Team/LanguageServer

#34324 Fix MatchedExpressionNodeResolver returning null
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddCheckCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/config/negative_add_check_external_treenode_list.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/source/negative_add_check_external_treenode_list.bal
Labels: Team/LanguageServer

#34328 Fix symbol lookup issues in type refs
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ErrorTypeSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typedescriptors/TypeReferenceTSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/error_type_symbol_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedescriptors/typeref_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#34386 [Shell] Update ModuleMemberTrial
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/basics.variables.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.moduledcln.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.statement.json
Labels: Team/CompilerFETools, Area/Shell

#33989 [Shell] Provide a mechanism for auto importing modules
  ballerina-shell/modules/shell-cli/build.gradle
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/TerminalAdapter.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/JlineTerminalAdapter.java
  ballerina-shell/modules/shell-cli/src/main/java/module-info.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/Evaluator.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/EvaluatorImpl.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ExceptionStatus.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ShellCompilation.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ShellReturnValue.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/ShellSnippetsInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/ModuleImporter.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/AbstractEvaluatorTest.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/RegressionEvaluatorTest.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/EvaluatorMiscTest.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/InvokerTest.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/basics.modules.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/regression.qualifiers.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/invoker.final.function.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/invoker.final.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/invoker.function.name.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/invoker.no.module.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/invoker.same.prefix.json
  ballerina-shell/modules/shell-core/src/test/resources/testcases/invoker.variable.name.json
Labels: Team/CompilerFETools, Area/Shell

#34371 Fix type related issues of constant maps
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/MapConstantInBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/MapConstantPanicInBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantPanicTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant_map_spread_field_negative.bal
Labels: Team/CompilerFE

#34393 Update H2 driver version
  gradle.properties
Labels: Priority/Blocker

#34355 [Shell] Provide newline for incomplete user inputs
  ballerina-shell/modules/shell-cli/build.gradle
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/JlineBallerinaParser.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/ExpressionValidator.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/InputValidator.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/ModuleMemberValidator.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/StatementValidator.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/Validator.java
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/utils/IncompleteInputFinder.java
  ballerina-shell/modules/shell-cli/src/main/java/module-info.java
  ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/validator/ValidatorTest.java
Labels: Team/CompilerFETools, Area/Shell

#34310 Fix `typeOf()` working for the whole named-arg node
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/statements/SymbolsInCallStatementsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfInCallStatementsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/statements/symbols_in_call_stmt.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#34406 Check array capacity before `unshift()`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Team/jBallerina

#34370 Improve error message for relative resource path
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ServiceDeclarationTest.java
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_assert_23.json
  compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_23.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ServiceDeclTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_relative_resource_path_negative.bal
Labels: Team/CompilerFE, Area/Parser
