Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-07, with the labels that each got.

#31495 Remove type cache in TypesFactory
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypeCacheTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type_cache_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFETools

#31443 Improve check expr type checking
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_operator_basics.bal
Labels: Team/CompilerFE

#31522 Avoid defining new types for error intersections that define already-existing types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error_intersection_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error_intersection_type_negative.bal
Labels: Team/CompilerFE

#31400 Fix wildcard binding pattern issue in Query expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/MultipleLetClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/multiple-let-clauses.bal
Labels: Team/CompilerFE

#31425 Remove secret env variable support for configurable
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/ShellSnippetsInvoker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlDetails.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/BTestRunner.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/Config-secrets.toml
  tests/jballerina-integration-test/src/test/resources/configurables/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/config_files/Config.toml
Labels: Team/jBallerina

#31277 Support multiple configurable TOML sections to represent module
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ModuleInfo.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/CliConfigProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/DifferentModuleSections.toml
  bvm/ballerina-runtime/src/test/resources/config_files/DifferentModuleSections_clash1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/DifferentModuleSections_clash2.toml
  bvm/ballerina-runtime/src/test/resources/config_files/DifferentModuleSections_imported.toml
  bvm/ballerina-runtime/src/test/resources/config_files/DifferentModuleSections_record.toml
  bvm/ballerina-runtime/src/test/resources/config_files/DifferentModuleSections_root.toml
  bvm/ballerina-runtime/src/test/resources/config_files/DifferentModuleSections_sub.toml
Labels: Team/jBallerina

#31519 Avoid creating new types for read-only intersections with immutable types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/readonly/ImmutabilityBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/imports/ImportsNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ReadonlyRecordFieldTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_intersection_with_inherently_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_immutable/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_immutable/constructs.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal
Labels: Team/CompilerFE

#31392 Support configurable open record values to have additional fields
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/Utils.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderRecordTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/OpenRecordConfig.toml
  bvm/ballerina-runtime/src/test/resources/config_files/RestFieldConfig.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/RestFieldNegative.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_maps.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_open_records.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_records.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_tables.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/array_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/map_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/imported_records/imported_record_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/imported_records/record_array_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/imported_records/record_map_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/imported_records/record_table_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/open_records/record_collection_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/open_records/record_map_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/open_records/record_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/open_records/rest_field_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/type_defs/type_defs.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/modules/util/util.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/record_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/table_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configStructuredTypes/types.bal
Labels: Team/jBallerina

#31276 Fix SO issue of BObject and BIntersection toString
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BObjectType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTupleType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ReadonlyObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/CyclicTypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/readonly_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/tuple-type-definitions-cyclic.bal
Labels: Team/CompilerFE

#31515 Improve incomplete object field recovery
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ObjectTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_37.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_46.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_source_46.bal
Labels: Area/Parser, Team/CompilerFE

#31445 Fix effective type not resolving correctly in intersection type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Area/SemanticAPI, Team/CompilerFETools

#31424 Handle java.lang.OutOfMemoryError
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java
Labels: Points/1, Team/jBallerina

#31446 Fix missing key issue in member access
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/ArrayTypeTest.java
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_assert_21.json
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_source_21.bal
Labels: Team/CompilerFE

#31141 [Semantic API] Add NoneType symbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaNoneTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/NoneTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/TypeDescKind.java
Labels: Area/SemanticAPI, Team/CompilerFETools

#31428 Fix unreachable pattern error ignoring guard in match pattern
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtTypeNarrowingTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/mapping-mach-pattern-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match-stmt-type-narrow.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_stmt_type_narrow_negative.bal
Labels: Team/CompilerFE

#31488 Add Test Cases to Recognize Enums in Recursive Array Type
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/enums/EnumTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/enums/enums.bal
Labels: Team/CompilerFE, Team/CompilerFETools

#31594 Fix "This function must return a result" diagnostic location
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectFunctionCodeAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/dostatement/DoStmtsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/IfElseStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementStaticPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/returnstmt/ReturnStmtNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/whilestatement/WhileStmtTest.java
Labels: Team/CompilerFE

#31544 Fix incorrect types set for error detail fields in match patterns
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtErrorMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ErrorBindingPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/error_match_pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/error_binding_pattern.bal
Labels: Team/CompilerFE

#31573 Fix isolation analysis for query expressions and on fail clauses
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedVariableTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables_isolation_negative.bal
Labels: Team/CompilerFE

#31634 Reduce lookahead limit to 4 in ErrorHandler
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/AnnotationDeclarationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ClassDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/FunctionDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ImportDeclarationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ObjectTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/RecordTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ServiceDeclarationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/TypeDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/AnonymousFuncExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/ByteArrayLiteralTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/ConditionalExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/ListConstructorTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/NewExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/NilLiteralTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QueryExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/TableConstructorTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/XMLNavigateExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/XMLTemplateExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/PreDeclaredModulePrefixTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/ResiliencyTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/AssignmentStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/DoStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/ForEachStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/LockStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/MatchStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/TransactionStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/WhileStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/FunctionTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/TableTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/TupleTypeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/TreeTraversalAPITest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ExpressionContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/QueryExpressionContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/StatementContextTest.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/IdentifierLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementStaticPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementSyntaxErrorsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/VarDeclrSemanticTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/structs/StructNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/StringTemplateLiteralNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/var/VarDeclaredAssignmentStmtTest.java
Labels: Area/Parser, Team/CompilerFE

#31639 Fix diagnostics when metadata not attached to a construct
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_43.json
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_source_43.bal
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_46.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_source_46.bal
  compiler/ballerina-parser/src/test/resources/misc/annotations/annotations_assert_10.json
  compiler/ballerina-parser/src/test/resources/misc/annotations/annotations_source_10.bal
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_assert_26.json
  compiler/ballerina-parser/src/test/resources/misc/documentation/doc_source_26.bal
Labels: Area/Parser, Team/CompilerFE

#30957 [Shell] Remove initial import statements
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ImportsManager.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/EvaluatorMiscTest.java
Labels: Area/Shell, Team/CompilerFETools

#31626 Update performance test results for Ballerina Swan Lake Beta 2
  performance/benchmarks/summary.csv
  performance/benchmarks/summary.md
Labels: Team/StandardLibs, Type/Task

#31242 Fix issue with query expressions having anonymous functions
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/Flag.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/Flags.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithAnonFunctionExprs.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-anon-func-exprs.bal
Labels: Team/CompilerFE

#31468 Assign xml<xml:Text> to a xml:Text
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals.bal
Labels: Team/CompilerFE

#31661 Fix "Incorrect order of fields in the record value created from an invocation of a function that has an included record param"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/CompilerFE

#31617 Add `pkg-toml-semantic-analyzer` compiler plugin to report diagnostics after compilation phase
  distribution/zip/jballerina-tools/build.gradle
  misc/compiler-plugins/modules/package-semantic-analyzer/build.gradle
  misc/compiler-plugins/modules/package-semantic-analyzer/spotbugs-exclude.xml
  misc/compiler-plugins/modules/package-semantic-analyzer/src/main/java/module-info.java
  misc/compiler-plugins/modules/package-semantic-analyzer/src/main/java/org/ballerinalang/pkgsemanticanalyzer/PackageSemanticAnalyzerPlugin.java
  misc/compiler-plugins/modules/package-semantic-analyzer/src/main/resources/META-INF/services/io.ballerina.projects.plugins.CompilerPlugin
  project-api/project-api-test/build.gradle
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBalaWriter.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/CompilerPluginTests.java
  project-api/project-api-test/src/test/resources/balawriter/projectOne/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_invalid_exported_modules/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_invalid_exported_modules/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_valid_exported_modules/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_valid_exported_modules/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_valid_exported_modules/modules/abc/abc.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_valid_exported_modules/modules/xyz/xyz.bal
  settings.gradle
Labels: Area/BuildTools, Area/ProjectAPI

#31310 Implement diagnostic reporting in package resolution phase
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/DocumentContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/ModuleLoadRequest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/exceptions/InvalidBalaException.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDiagnostic.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ProjectDiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ProjectFiles.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/balas/invalid/bash-soap-any-0.1.0.bala
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/balas/invalid/hello-2020r1-any-0.1.0.balo
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/balas/invalid/zip-2020r1-java8-1.0.4.balo
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_x_with_invalid_bala_dep/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_x_with_invalid_bala_dep/bar.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_x_with_invalid_bala_dep/foo.bal
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_xx_with_invalid_transitive_bala_dep/Ballerina.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_tests/package_xx_with_invalid_transitive_bala_dep/foo.bal
Labels: Area/ProjectAPI, Team/DevTools

#31566 Allow service-decl to have init method returning error
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleListenerDeclTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_listener_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_listener_decl_negative.bal
Labels: Team/CompilerFE

#31584 Update equality check between empty xml sequence and xml<never>
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsPureTypeUniqueVisitor.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
Labels: Team/CompilerFE

#31695 Improve parser completions at close brace
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParserErrorHandler.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/errorhandler/ErrorHandlerValidationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/ObjectTypeDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/CompletionTest.java
  compiler/ballerina-parser/src/test/resources/declarations/class-def/class_def_assert_10.json
  compiler/ballerina-parser/src/test/resources/declarations/enum-decl/enum_decl_assert_08.json
  compiler/ballerina-parser/src/test/resources/declarations/enum-decl/enum_decl_source_08.bal
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_10.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_43.json
  compiler/ballerina-parser/src/test/resources/expressions/new-expr/new_expr_assert_03.json
  compiler/ballerina-parser/src/test/resources/expressions/object-constructor/object_constructor_assert_11.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_65.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_66.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_01.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_03.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_04.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_05.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_06.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_07.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_08.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_09.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_10.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_01.bal
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_02.bal
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_03.bal
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_04.bal
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_05.bal
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_06.bal
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_07.bal
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_08.bal
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_09.bal
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_10.bal
  compiler/ballerina-parser/src/test/resources/statements/block-stmt/block_stmt_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/lock-stmt/lock_stmt_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_04.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_11.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_19.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_11.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_19.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/IdentifierLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/AbstractObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/structs/StructNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
Labels: Area/Parser, Team/CompilerFE

#31541 Fix map configurable variable clashing with modules
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/main/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/main/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/main/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/test/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/test/Package.md
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/test/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/tests/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/tests/Package.md
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/tests/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/multipleSubModuleClash/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/multipleSubModuleClash/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/multipleSubModuleClash/modules/mod1.test/mod1.test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/multipleSubModuleClash/modules/mod1/mod1.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/multipleSubModuleClash/multipleSubModuleClash.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/subModuleClash/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/subModuleClash/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/subModuleClash/modules/test/test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/subModuleClash/subModuleClash.bal
Labels: Team/jBallerina

#31752 Fix intermittent failing integration test
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/main/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/main/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/main/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/tests/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/tests/Package.md
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/importedModuleClash/tests/main.bal
Labels: Team/jBallerina

#31754 Fix the use of non-existant `handleRuntimeErrors`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#31766 Fix direct call to config map get()
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
Labels: Team/jBallerina

#30710 Fix incorrect results with cloneWithType for finitetype integer sub types arrays
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneWithType.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#31596 Fix var-name location set to null for params in function types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Team/CompilerFE, Team/CompilerFETools

#31478 Enable compatible tuple assignment to JSON
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config14.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/RefEqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/StampInbuiltFunctionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/BasicTupleTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/ref_equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/ref_equal_and_not_equal_operation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/stamp/negative/tuple-stamp-expr-negative-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_basic_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_negative_test.bal
Labels: Team/CompilerFE

#31762 Add API to get leading and trailing invalid tokens
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/Node.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/errorhandler/ErrorHandlerValidationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/MinutiaeListAPITest.java
  compiler/ballerina-parser/src/test/resources/tree/invalid_token_minutiae_test_01.bal
  compiler/ballerina-parser/src/test/resources/tree/invalid_token_minutiae_test_02.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Area/SyntaxAPI, Team/CompilerFE

#31832 Improve desugar implementation for grpc auth
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/DeclarativeAuthDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
Labels: Area/Desugar, Team/CompilerFE

#31674 Fix setting nil type manually to stream completion when completion is given
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/streams.streams.json
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  docs/bir-spec/src/test/resources/test-src/types_and_operations.bal
  misc/syntax-api-calls-gen/src/test/resources/bbe-examples/grpc_bidirectional_streaming_service.bal
  misc/syntax-api-calls-gen/src/test/resources/bbe-examples/jdbc_batch_execute_operation.bal
  misc/syntax-api-calls-gen/src/test/resources/bbe-examples/jdbc_complex_type_queries.bal
  misc/syntax-api-calls-gen/src/test/resources/bbe-examples/jdbc_parameterized_query.bal
  misc/syntax-api-calls-gen/src/test/resources/bbe-examples/jdbc_query_operation.bal
  misc/syntax-api-calls-gen/src/test/resources/bbe-examples/mysql_call_stored_procedures.bal
  misc/syntax-api-calls-gen/src/test/resources/bbe-examples/mysql_complex_type_queries.bal
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/variable-tests/main.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/InferredDependentlyTypeFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-var-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Team/CompilerFE

#31656 Validate usage of `check` in record field default values and object field initializers
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_field_initializer_with_check.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_field_initializer_with_check_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/negative/record_field_default_value_negative.bal
Labels: Team/CompilerFE

#31570 Optimize type checking for unions with error or nil
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeTestGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typechecker/ErrorOptimizationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typechecker/NilOptimizationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/DistinctTypeDefTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typechecker/error_optimizations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typechecker/nil_optimizations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/distinct-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#31798 [Shell] Fix incorrect error about isolated
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/function.anon.json
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/types/VariableDeclarationSnippet.java
  ballerina-shell/modules/shell-core/src/main/resources/template.declaration.mustache
  ballerina-shell/modules/shell-core/src/main/resources/template.execution.mustache
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/function.anon.json
Labels: Area/Shell, Team/CompilerFETools

#31861 Fix equality checks with intersections with a union
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/RefEqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/ref_equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/ref_equal_and_not_equal_operation_negative.bal
Labels: Team/CompilerFE

#31809 [Semantic API] Suggest Function Arguments in Expression-bodied Functions
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config8.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ParameterSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/param_symbols_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_lookup_with_exprs_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_position_test.bal
Labels: Area/SemanticAPI, Team/CompilerFETools

#31806 Associate mapping constructor keys with their relevant field symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/SymbolsInMappingConstructorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbols_in_mapping_constructor_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFE, Team/CompilerFETools

#31796 Allow function pointer invocation on object fields
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/start/ObjectFieldFunctionPointerStartActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/ObjectFieldFunctionPointerInvocationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/action/start/object_field_start_action_method_invocation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/action/start/object_field_start_method_invocation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/object_field_method_invocation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/object_field_method_invocation_negative.bal
Labels: Lang/Objects, Team/CompilerFE

#31863 Fix several issues with built-in sub-types and finite types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibDecimalTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibFloatTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibIntTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibNegativeTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibSubTypeTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/decimallib_test.bal
  langlib/langlib-test/src/test/resources/test-src/floatlib_test.bal
  langlib/langlib-test/src/test/resources/test-src/intlib_test.bal
  langlib/langlib-test/src/test/resources/test-src/langlib_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
  langlib/langlib-test/src/test/resources/test-src/subtypes/char_subtypes_test.bal
  langlib/langlib-test/src/test/resources/test-src/subtypes/char_subtypes_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/subtypes/int_subtype_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/subtypes/int_subtypes_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type_cast_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Team/CompilerFE

#31616 Fix incorrect code generated with const
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-expression.bal
Labels: Team/jBallerina

#31910 Fix symbol finding issue in object constructors
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/SymbolsInObjectConstructorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbols_in_object_constructor_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Area/SemanticAPI, Team/CompilerFETools

#31890 Fix `binary-bitwise-expr`s not working with some int subtypes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/BinaryBitwiseOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/unaryoperations/UnaryExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary_bitwise_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary_bitwise_operation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/unaryoperations/unary-operation-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/unaryoperations/unary-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_operations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-expression.bal
Labels: Team/CompilerFE

#31902 [Debugger] Fix minor issues related to XML value presentation
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/utils/EvaluationUtils.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BXmlItem.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BXmlItemAttributeMap.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BXmlSequence.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BXmlText.java
  misc/debug-adapter/modules/debug-adapter-runtime/src/main/java/org/ballerinalang/debugadapter/runtime/DebuggerRuntime.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
Labels: Team/DevTools

#31779 Fix issues with tuple type conversion
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion.bal
Labels: Team/jBallerina

#31761 Fix resource method related compiler crashes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ServiceClassTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/service_test_project/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/service_test_project/modules/A/source.bal
  tests/jballerina-unit-test/src/test/resources/test-src/klass/resource-method-assignability-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/klass/resource_function_with_invalid_path_param_type_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/klass/service_type_resource_method_decl_neg.bal
Labels: Team/CompilerFE

#31909 Fix scope finding logic in `EnvironmentResolver`
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/object_constructor_expr_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/object_constructor_expr_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/object_constructor_expr_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/object_constructor_expr_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/object_constructor_expr_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/object_constructor_expr_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/object_constructor_expr_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config15.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_lookup_in_object_constructor.bal
Labels: Area/SemanticAPI, Team/CompilerFETools

#31924 Fix type alias support for classes
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/class_symbols_test.bal
Labels: Area/SemanticAPI, Team/CompilerFETools

#31949 Enable disabled match statement recovery tests
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/MatchStatementTest.java
  compiler/ballerina-parser/src/test/resources/actions/flush-action/flush_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/flush-action/flush_action_source_02.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_07.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_11.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_assert_13.json
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_11.bal
  compiler/ballerina-parser/src/test/resources/statements/match-stmt/match_stmt_source_13.bal
Labels: Area/Parser, Team/CompilerFE
