Repository ballerina-platform/ballerina-lang, pull requests merged in 2021-11, with the labels that each got.

#33489 Fix lang.array sort to return a new array
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/values.arrays.json
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Sort.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Team/CompilerFE, Team/jBallerina, Lang/LangLib

#33468 Avoid providing completions after `function` keyword in anon function expression
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ExplicitAnonymousFunctionExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/anon_func_expr_ctx_source12.bal
Labels: Team/LanguageServer

#33480 Fix object type descriptor signature
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction39.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction42.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/xml_attribute_access_expr_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/xml_attribute_access_expr_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config1a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config28.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config2a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config33.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config34.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config35.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config36.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config38.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config39.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config3a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config40.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config41.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config43.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5b.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5c.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_within_param_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config22.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config23.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config24.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/service_body/config/config4.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config13.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#33509 Implement the Annotation Access Express Lookup Method
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#33518 Lookup for Annotation Attachments in Simple Variable Nodes
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#33251 Fix using broader type instead of finite type when creating union types
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/langlib_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#33519 Enable `xml` Step Expression Related Test Cases
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#33442 Fix completion item sorting in function-type-desc
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/config/function_typedesc1.json
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/config/function_typedesc12.json
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/config/function_typedesc4.json
Labels: Team/LanguageServer

#33384 Fix type cast code action for `xml:Text`
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeCastTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/typeCast.bal
Labels: Team/LanguageServer

#33515 Revert #32103 and allow join as identifier only in method call expression
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/misc/identifiers/keywords_as_identifiers_assert.json
  compiler/ballerina-parser/src/test/resources/misc/identifiers/keywords_as_identifiers_source.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibNegativeTest.java
Labels: Team/CompilerFE, Area/Parser

#33450 Add type param to `xml:get` return type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  langlib/lang.xml/src/main/ballerina/xml.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/xml_attribute_access_expr_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/xml_attribute_access_expr_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config38.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config39.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config40.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config41.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config24.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundXMLFunctionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration_negative.bal
Labels: Team/CompilerFE, Lang/LangLib

#33537 Fix invalid assignment error for some variables narrowed by loops
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/narrowing/AssignmentToNarrowedVarsInLoopsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/narrowing/assignment_to_narrowed_vars_in_loops.bal
  tests/jballerina-unit-test/src/test/resources/test-src/narrowing/assignment_to_narrowed_vars_in_loops_negative.bal
Labels: Team/CompilerFE

#33479 Fix `float:min` and `float:max` functions for `NaN` values
  langlib/lang.float/src/main/java/org/ballerinalang/langlib/floatingpoint/FromHexString.java
  langlib/lang.float/src/main/java/org/ballerinalang/langlib/floatingpoint/Max.java
  langlib/lang.float/src/main/java/org/ballerinalang/langlib/floatingpoint/Min.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibFloatTest.java
  langlib/langlib-test/src/test/resources/test-src/floatlib_test.bal
Labels: Team/jBallerina

#33481 Fix `IllegalStateException` when quote is missing in XML attribute val
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/XMLTemplateExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_35.json
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_source_35.bal
Labels: Team/CompilerFE, Area/Parser

#33502 Fix NPE for undefined unary operations in constant declaration
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-expression-negative.bal
Labels: Team/CompilerFE

#33533 Fix `isolated` for `range-expr`
  langlib/lang.__internal/src/main/ballerina/int-range.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction39.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/IntegerRangeOperatorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/integer_range_operators.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-variables/isolated_variables.bal
Labels: Team/CompilerFE

#33469 Fix signature deviation in `map` function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  langlib/lang.table/src/main/ballerina/table.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal
  langlib/langlib-test/src/test/resources/test-src/tablelib_test_negative.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config18.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundTableFunctionsTest.java
Labels: Team/CompilerFE, Lang/LangLib

#33552 Fix dataflow and isolated issues in langlib
  langlib/jballerina.java/src/main/ballerina/stackFrameImpl.bal
  langlib/lang.query/src/main/ballerina/helpers.bal
  langlib/lang.query/src/main/ballerina/types.bal
  langlib/lang.runtime/src/main/ballerina/runtime.bal
  langlib/lang.transaction/src/main/ballerina/transaction.bal
  langlib/lang.transaction/src/main/ballerina/transaction_errors.bal
  langlib/langlib-test/src/test/resources/test-src/runtimelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/nativeimpl/functions/RuntimeTest.java
Labels: Team/CompilerFE

#33546 Allow using the wildcard binding pattern in the typed binding patterns of foreach statements and from clauses
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachArrayTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachMapTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachNegativeTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-arrays.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-maps.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_wildcard_binding_pattern_negative.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QuerySemanticNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/SimpleQueryExpressionWithDefinedTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_wildcard_binding_pattern_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal
Labels: Team/CompilerFE

#33557 Improve error msg in places where metadata is not allowed
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_on_disallowed_constructs.bal
Labels: Team/CompilerFE, Area/Diagnostics

#33401 Fix issue with type narrowing in `if-else-stmt`
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/narrowing_with_if_without_else_not_completed_normally_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/reachability_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/unreachability_test.bal
Labels: Team/CompilerFE

#33374 Fix issue in validating binding pattern
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/list_binding_pattern_assert_02.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/list_binding_pattern_source_02.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleDestructureTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_invalid_syntax.bal
Labels: Team/CompilerFE, Area/Parser

#33562 Run all compiler phases for langlibs
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/CompilerPhaseRunner.java
Labels: Team/CompilerFE

#33560 Fix "Not giving a compile error for negative index array access"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayAccessExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/incorrect-array-access.bal
Labels: Team/CompilerFE

#33570 Address review suggestions for #33401
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/unreachability_test.bal
Labels: Team/CompilerFE

#33302 Fix string unescaping with `\u{5C}`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/IdentifierUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-template-literal.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/unicode.bal
Labels: Team/CompilerFE

#33376 Check invalid contextually expected type for error ctor
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/errorconstructorexpr/ErrorConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/errorconstructorexpr/error-constructor-expr-negative.bal
Labels: Team/CompilerFE

#33541 Fix incorrect behaviour of resulting type in `bitwise-or-expr`
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/operations.bitwise.json
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  docs/bir-spec/src/test/resources/test-src/types_and_operations.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibSubTypeTest.java
  langlib/langlib-test/src/test/resources/test-src/subtypes/int_subtypes_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/BinaryBitwiseOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary_bitwise_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary_bitwise_operation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal
Labels: Team/CompilerFE

#33549 Fix completion issue in field access context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config46.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source46.bal
Labels: Team/LanguageServer

#33573 Add "remove unreachable code" code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/RemoveUnreachableCodeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/RemoveUnreachableCodeCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/config/remove_unreachable_code1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/config/remove_unreachable_code2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/config/remove_unreachable_code3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/config/remove_unreachable_code4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/config/remove_unreachable_code5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/source/remove_unreachable_code1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/source/remove_unreachable_code2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/source/remove_unreachable_code3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/source/remove_unreachable_code4.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-unreachable-code/source/remove_unreachable_code5.bal
Labels: Team/LanguageServer

#33603 Fix incorrect behaviour with negative array length
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArraySizeDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_size_test_negative.bal
Labels: Team/CompilerFE

#33608 Run data flow analysis for the then/else expressions of ternary expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/DataflowAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/UnusedVariableTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/dataflow-analysis-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/unused_variable_analysis_test.bal
Labels: Team/CompilerFE

#33482 Add bulk watched file change event handling and project reloading
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/DidChangeWatchedFilesContext.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/ContextBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/DidChangeWatchedFilesContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/TestDidChangeWatchedFiles.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/WorkspaceTest.java
  language-server/modules/langserver-core/src/test/resources/testng.xml
  language-server/modules/langserver-core/src/test/resources/workspace/project/.ballerina/readme.txt
  language-server/modules/langserver-core/src/test/resources/workspace/project/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/workspace/project/src/pkg1/Module.md
  language-server/modules/langserver-core/src/test/resources/workspace/project/src/pkg1/pkg1Source.bal
  language-server/modules/langserver-core/src/test/resources/workspace/project/src/pkg2/Module.md
  language-server/modules/langserver-core/src/test/resources/workspace/project/src/pkg2/pkg2Source.bal
  language-server/modules/langserver-core/src/test/resources/workspace/project/src/pkg3/Module.md
  language-server/modules/langserver-core/src/test/resources/workspace/project/src/pkg3/pkg3Source.bal
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/.devcontainer.json
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/.gitignore
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/main.bal
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod1/Module.md
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod1/Package.md
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod1/mod1.bal
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod1/mod12.bal
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod1/resources/.keep
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod1/tests/lib_test.bal
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod2/Module.md
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod2/Package.md
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod2/mod2.bal
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod2/resources/.keep
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod2/tests/lib_test.bal
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod3/Module.md
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod3/Package.md
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod3/mod3.bal
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod3/resources/.keep
  language-server/modules/langserver-core/src/test/resources/workspace/projects/prj_ws_did_change/modules/mod3/tests/lib_test.bal
Labels: Team/LanguageServer

#33472 Fix finite type creation with decimal members
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/uniontypes/UnionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/uniontypes/union_types_basic.bal
Labels: Team/jBallerina

#33458 Fix converting json to immutable open record type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#33606 Fix missing quotes for string literals in `SingletonTypeSymbol` and use finite type when creating singleton-type symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSingletonTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/TypesFactory.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  language-server/modules/langserver-core/src/test/resources/completion/enum_decl_ctx/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/enum_decl_ctx/config/config4.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config51.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config52.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config53.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config54.json
  language-server/modules/langserver-core/src/test/resources/completion/module_xml_namespace_decl/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/module_xml_namespace_decl/config/config2.json
  language-server/modules/langserver-core/src/test/resources/completion/module_xml_namespace_decl/config/config8.json
  language-server/modules/langserver-core/src/test/resources/completion/record_type_desc/config/config5.json
  language-server/modules/langserver-core/src/test/resources/completion/record_type_desc/config/config6.json
  language-server/modules/langserver-core/src/test/resources/completion/record_type_desc/config/config7.json
  language-server/modules/langserver-core/src/test/resources/completion/record_type_desc/config/config8.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/match_stmt_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/match_stmt_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/xmlns_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/xmlns_ctx_config4.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/UnionTypeSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/langlib_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/union_type_symbol_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#33513 Change the unused config value warnings to error
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/CliProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
Labels: Team/jBallerina

#33579 Add "Ignore unused variable" code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/IgnoreUnusedVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/ReferencesUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/IgnoreUnusedVariableCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/config/ignore_unused_var1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/config/ignore_unused_var2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/config/ignore_unused_var3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/config/ignore_unused_var4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/config/ignore_unused_var5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/config/ignore_unused_var6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/config/ignore_unused_var_assignment1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/config/ignore_unused_var_assignment2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/config/ignore_unused_var_tuple1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/source/ignore_unused_var1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/source/ignore_unused_var2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/source/ignore_unused_var3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/source/ignore_unused_var4.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/source/ignore_unused_var5.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/source/ignore_unused_var6.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/source/ignore_unused_var_assignment1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/source/ignore_unused_var_assignment2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/ignore-unused-var/source/ignore_unused_var_tuple1.bal
Labels: Team/LanguageServer

#33584 Add code actions for language changes
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/linter-plugin/build.gradle
  compiler/linter-plugin/src/main/java/io/ballerina/compiler/linter/impl/CompilerLinter.java
  compiler/linter-plugin/src/main/java/io/ballerina/compiler/linter/impl/codeactions/CheckUsageCodeAction.java
  compiler/linter-plugin/src/main/java/io/ballerina/compiler/linter/impl/codeactions/Constants.java
  compiler/linter-plugin/src/main/java/io/ballerina/compiler/linter/impl/codeactions/FloatingPointLiteralCodeAction.java
  compiler/linter-plugin/src/main/java/io/ballerina/compiler/linter/impl/codeactions/LinterCodeAction.java
  compiler/linter-plugin/src/main/java/io/ballerina/compiler/linter/impl/codeactions/QualifiedIdentifierCodeAction.java
  compiler/linter-plugin/src/main/java/module-info.java
  compiler/linter-plugin/src/main/resources/META-INF/services/io.ballerina.projects.plugins.CompilerPlugin
  compiler/linter-plugin/src/test/java/io/ballerina/compiler/linter/codeactions/test/CodeActionTests.java
  compiler/linter-plugin/src/test/java/io/ballerina/compiler/linter/codeactions/test/CodeActionUtils.java
  compiler/linter-plugin/src/test/resources/source/check1.bal
  compiler/linter-plugin/src/test/resources/source/check1.bal.new
  compiler/linter-plugin/src/test/resources/source/check2.bal
  compiler/linter-plugin/src/test/resources/source/check2.bal.new
  compiler/linter-plugin/src/test/resources/source/floatingNumber1.bal
  compiler/linter-plugin/src/test/resources/source/floatingNumber1.bal.new
  compiler/linter-plugin/src/test/resources/source/floatingNumber2.bal
  compiler/linter-plugin/src/test/resources/source/floatingNumber2.bal.new
  compiler/linter-plugin/src/test/resources/source/floatingNumber3.bal
  compiler/linter-plugin/src/test/resources/source/floatingNumber3.bal.new
  compiler/linter-plugin/src/test/resources/source/floatingNumber4.bal
  compiler/linter-plugin/src/test/resources/source/floatingNumber4.bal.new
  compiler/linter-plugin/src/test/resources/source/floatingNumber5.bal
  compiler/linter-plugin/src/test/resources/source/floatingNumber5.bal.new
  compiler/linter-plugin/src/test/resources/source/floatingNumber6.bal
  compiler/linter-plugin/src/test/resources/source/floatingNumber6.bal.new
  compiler/linter-plugin/src/test/resources/source/qname1.bal
  compiler/linter-plugin/src/test/resources/source/qname1.bal.new
  compiler/linter-plugin/src/test/resources/source/qname2.bal
  compiler/linter-plugin/src/test/resources/source/qname2.bal.new
  compiler/linter-plugin/src/test/resources/source/qname3.bal
  compiler/linter-plugin/src/test/resources/source/qname3.bal.new
  compiler/linter-plugin/src/test/resources/source/qname4.bal
  compiler/linter-plugin/src/test/resources/source/qname4.bal.new
  compiler/linter-plugin/src/test/resources/testng.xml
  distribution/zip/jballerina-tools/build.gradle
  settings.gradle
Labels: Team/CompilerFE

#33613 Add pull module code action with project.clearCaches() support
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/PullModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/PullModuleExecutor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/task/BackgroundTaskService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/task/Task.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/task/TaskExecutionException.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/PullModuleCodeActionTest.java
Labels: Team/LanguageServer

#33617 Fix context stack recovery when error handler fails with an exception
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java
Labels: Team/CompilerFE, Area/Parser

#33578 Fix parsing when first member of tuple is parenthesised type array
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/TupleTypeTest.java
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_assert_07.json
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_source_07.bal
Labels: Team/CompilerFE, Area/Parser

#33647 Make StackFrame's toString() isolated
  langlib/jballerina.java/src/main/ballerina/stackFrameImpl.bal
  langlib/lang.error/src/main/ballerina/error.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibErrorTest.java
  langlib/langlib-test/src/test/resources/test-src/errorlib_test.bal
Labels: Team/CompilerFE

#33631 Fix xml sequence exact equality checks
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/RefEqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/ref_equal_and_not_equal_operation.bal
Labels: Team/jBallerina

#33556 Fix never field type checking in record variable
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never_type_runtime.bal
Labels: Team/jBallerina

#33642 Remove else statement right curly brace position
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/TestReportTest.java
Labels: Team/jBallerina

#33467 Fix `references(symbol)` for List Binding Patterns
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#33661 Improve compiler plugin codeaction docs
  language-server/docs/CompilerPluginCodeActionExtensions.md
Labels: Team/LanguageServer

#33662 Fix completion sorting within the type-cast context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeCastExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/typecast_expr_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/typecast_expr_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/typecast_expr_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/typecast_expr_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/typecast_expr_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/listener_decl/config/config12.json
Labels: Team/LanguageServer

#33547 Fix field access against type definitions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config45.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source45.bal
Labels: Team/LanguageServer

#33684 Api to access Informations of Type Inclusions at the Runtime
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ObjectType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BObjectType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTypeIdSet.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Errors.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/modules/errors/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/types/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/types/modules/objects/objects.bal
Labels: Team/jBallerina

#33708 Return the effective type of `BIntersectionType`s in `org.wso2.ballerinalang.compiler.semantics.analyzer.Types#getIntersection`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtListMatchPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/list-match-pattern-negative-semantics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/list-match-pattern.bal
Labels: Team/CompilerFE

#33679 Add unit test for type guard code action
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeGuardTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/config/typeGuardVariableCodeAction3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/source/typeGuardVariable2.bal
Labels: Team/LanguageServer

#33612 Revamp type cast code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeCastTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCastNegative2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCastNegative3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_function_param_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/typeCast.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/type_cast_function_param_config1.bal
Labels: Team/LanguageServer

#33712 Fix diagnostic not showing in single file projects
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
Labels: Team/LanguageServer

#33710 Fix CCE when generating variable completions for fields
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
Labels: Team/LanguageServer

#33735 Fix original-name not getting assigned a value
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#33744 Update unused variable analysis
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/UnusedVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/narrowing/AssignmentToNarrowedVarsInLoopsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/FinalObjectFieldTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/SealedArrayTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/structs/StructNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/unused_variable_analysis_test.bal
Labels: Team/CompilerFE

#33611 Fix compiler crashing while using variable-name field for key and spread field with table constructor
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/RecordConstraintTableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/record-constraint-table-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/record-type-table-key.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-value-negative.bal
Labels: Team/CompilerFE

#33729 Fix unreachability with `while-stmt` not completed normally
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  langlib/lang.stream/src/main/ballerina/internal.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/narrowing_with_if_without_else_not_completed_normally_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/reachability_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/unreachability_test.bal
Labels: Team/CompilerFE

#33664 Fix auto triggering completion for sync-send
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/CompletionUtil.java
Labels: Team/LanguageServer

#33762 Fix the node cloner not cloning the match guard expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
Labels: Team/CompilerFE

#33761 Clean unnecessary envs
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
Labels: Team/CompilerFE

#33772 Desugar configurable variable's expression while visiting init function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/elvis/ElvisExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/ternary/TernaryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/elvis/elvis-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal
Labels: Team/CompilerFE

#33766 Fix type checking issues of Ternary and Elvis expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/elvis/ElvisExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/ternary/TernaryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/elvis/elvis-expr-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/elvis/elvis-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal
Labels: Team/CompilerFE

#33767 Fix defaults from the applicable contextually-expected type not being used when a mapping constructor has `readonly` fields
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/ReadOnlyMappingConstructorFieldBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ReadonlyRecordFieldTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/modules/records/records.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/mapping_constructor_with_readonly_fields_in_bala.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal
Labels: Team/CompilerFE

#33752 Introduce new methods to `NodeParser`
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/NodeParserAPITest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/NodeParserLineRangeTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseActionOrExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseBindingPatternTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseFunctionBodyBlock.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseImportDeclarationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseModuleMemberDeclarationTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseStatementTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseStatementsTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseTypeDescriptorTest.java
Labels: Team/CompilerFE, Area/SyntaxAPI

#33720 Add tests for module-level Ternary expressions
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/ternary/TernaryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal
Labels: Team/CompilerFE

#33702 Fix runtime:sleep for large decimal values
  langlib/lang.runtime/src/main/java/org/ballerinalang/langlib/runtime/Sleep.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRuntimeTest.java
  langlib/langlib-test/src/test/resources/test-src/runtimelib_test.bal
Labels: Team/jBallerina

#33777 Change deprecation documentation errors to warnings
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticWarningCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/UpdateDocumentationCodeAction.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationNegativeTest.java
Labels: Team/CompilerFE

#33619 Fix issue in validating duplicate fields in record literal
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/IdentifierUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor_duplicate_fields.bal
Labels: Team/CompilerFE

#33778 Deprecate `value:isReadOnly`
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/operations.immutable.json
  ballerina-shell/modules/shell-cli/src/test/resources/testcases/values.basic.json
  langlib/lang.value/src/main/ballerina/value.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/is_readonly_deprecated_warning.bal
Labels: Team/CompilerFE

#33794 Fix unused variable analysis for resource path params
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/UnusedVariableTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/unused_variable_analysis_test.bal
Labels: Team/CompilerFE

#33643 Fix semantic changes related to numeric literals
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangNumericLiteral.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/GreaterLessThanOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/NumericLiteralAssignmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalBFloatComparisonTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finite/FiniteTypeNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finite/FiniteTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/floattype/BFloatValueTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/uniontypes/UnionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary_bitwise_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/numeric_literal_assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_float_comparison.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/finite/finite-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/finite/finite_type_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/float/float-value-negative.bal
Labels: Team/CompilerFE

#33770 Fix issue in foreach scope when there is error binding pattern
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachErrorBindingPatternsTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_errors.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_errors_scope_negative.bal
Labels: Team/CompilerFE

#33688 Fix completion within the let expression node context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/CompleteExpressionValidator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/LetExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/config/let_expr_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/config/let_expr_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/source/let_expr_ctx_source13.bal
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/source/let_expr_ctx_source14.bal
Labels: Team/LanguageServer

#33260 Fix "Bad Sad error when the tuple has an array of a record"
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/TupleTypeTest.java
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_assert_07.json
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_assert_08.json
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_source_07.bal
  compiler/ballerina-parser/src/test/resources/types/tuple-type/tuple_type_source_08.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/BasicTupleTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleLValueFillTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_lvalue_fill_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_negative_test.bal
Labels: Team/CompilerFE, Area/Parser

#33698 Fix `int:abs()` to panic for overflow values
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  langlib/lang.int/src/main/java/org/ballerinalang/langlib/integer/Abs.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibIntTest.java
  langlib/langlib-test/src/test/resources/test-src/intlib_test.bal
Labels: Team/jBallerina

#33740 Fix map<json> map access negative cases
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/BJSONValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/jsontype/json-value.bal
Labels: Team/jBallerina

#33675 Fix CCE and NPE for Diagnostics in Anonymous Functions Params
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/DiagnosticsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testerrorproject/syntax_errors.bal
Labels: Area/Compiler, Team/CompilerFETools, Team/CompilerFE

#33840 Fix `iterator.next` invoked twice before invoking `foreach` body
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachIterableObjectTest.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-iterable-objects.bal
Labels: Team/CompilerFE, Area/Desugar

#33816 Pickup the identifier node of named-arg node when typeOf() is called
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfInCallStatementsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/statements/symbols_in_call_stmt.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#33865 Add missing flags in var symbols created for params in an arrow function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ParameterSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/param_symbols_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#33809 Fix compiler crash when using anonymous record type with tuple variable
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition.bal
Labels: Team/CompilerFE

#33804 Remove deprecated SyntaxTree methods for beta5
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxTree.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/TreeTraversalAPITest.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/ExpressionAsProgramEvaluator.java
Labels: Team/CompilerFE, Area/SyntaxAPI

#33739 Fix visibility of local variables which are inside block statements in debugger view
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangBlockStmt.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/variable-tests/main.bal
Labels: Team/jBallerina

#33826 Fix `isIsolated()` API for runtime object type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ObjectType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BObjectType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Async.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/async/main.bal
Labels: Team/jBallerina

#33751 Fix CCE in Add Check Code action
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/spi/DiagBasedPositionDetails.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/DiagBasedPositionDetailsImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
Labels: Team/LanguageServer

#33686 Fix type descriptors not being suggested after annotations in parameter context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AnnotationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/paramAnnotation10.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/paramAnnotation11.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/paramAnnotation4.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/paramAnnotation9.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/source/paramAnnotation10.bal
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/source/paramAnnotation11.bal
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/source/paramAnnotation9.bal
Labels: Team/LanguageServer

#33648 Fix several issues with match statement
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchGuardAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/MappingBindingPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/mapping-match-pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_guard_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_guard_function_method_call_mutability_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/mapping_binding_pattern.bal
Labels: Team/CompilerFE

#33764 Fix several `readonly` intersection issues
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/ReadonlyArrayCreator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/ReadonlyArrayTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/SelectivelyImmutableTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/array_creation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type_negative.bal
Labels: Team/CompilerFE

#33759 Fix clone() for array fields
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/UnionTypeConfig.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/configUnionTypes/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/configUnionTypes/modules/imported_unions/imported_unions.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/CloneOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/clone-operation.bal
Labels: Team/jBallerina

#33946 Fix several issues with match statements
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchGuardAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/MappingBindingPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/mapping-match-pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_guard_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_guard_function_method_call_mutability_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/mapping_binding_pattern.bal
Labels: Team/CompilerFE

#33635 Fix crash when access is on module level variable
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
Labels: Team/CompilerFE

#33736 Fix issue in getBindingPattern for named arg binding pattern
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_20.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_20.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition.bal
Labels: Team/CompilerFE, Area/Parser

#33614 Support unary plus and minus for numeric user defined sub types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/unaryoperations/UnaryExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/division-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/subtract-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/unaryoperations/unary-operation-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/unaryoperations/unary-operation.bal
Labels: Team/CompilerFE

#33917 Fix sorting in mapping constructor context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/functionAnnotation5.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/functionAnnotation6.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config22.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config23.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config24.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config25.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config27.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config27a.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config28.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config29.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config30.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config31.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config32.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config32a.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config32b.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config32c.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config33.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config34.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config35.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config36.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config37.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config38.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config38_negative.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config39.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config40.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config41.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config42.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config43.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config44.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config45.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config46.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config47.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config48.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config49.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config50.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config51.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config52.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config53.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config54.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config59.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config60.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config61.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config62.json
Labels: Team/LanguageServer

#33977 Merge language changes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_20.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_20.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/unaryoperations/UnaryExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchGuardAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/MappingBindingPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/division-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/subtract-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/unaryoperations/unary-operation-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/unaryoperations/unary-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/mapping-match-pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_guard_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_guard_function_method_call_mutability_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/mapping_binding_pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition.bal
Labels: Team/CompilerFE

#33970 Add github action to simulate language server
  .github/workflows/language_server_simulator.yml
  tests/language-server-simulator/build.gradle
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/EditorSimulator.java
Labels: Team/LanguageServer

#33925 Fix XML serialization of namespace prefix of an Element
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlQName.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributeAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-syntax.bal
Labels: Team/CompilerFE

#33950 Add missing completions in order-by-clause context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/IndexedExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/OrderByClauseNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_orderby_clause_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_orderby_clause_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_orderby_clause_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_orderby_clause_source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_orderby_clause_source6.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_orderby_clause_source7.bal
Labels: Team/LanguageServer

#33921 Add support for missing int subtypes in range-expr
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/IntegerRangeOperatorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/integer_range_operators.bal
Labels: Team/CompilerFE

#33799 Add type precedence support for `optional-type-descriptor`
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/TypePrecedence.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/TypePrecedenceTest.java
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_assert_04.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type-precedence_source_04.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_02.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_03.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_04.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_05.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_06.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_07.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_08.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_09.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_assert_10.json
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_01.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_02.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_03.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_04.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_05.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_06.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_07.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_08.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_09.bal
  compiler/ballerina-parser/src/test/resources/types/type-precedence/type_precedence_source_10.bal
Labels: Team/CompilerFE, Area/Parser

#33883 Fix type checking for error binding pattern type ref
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ErrorBindingPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/error_type_ref_negative.bal
Labels: Team/CompilerFE, Area/TypeChecker, Lang/BindingPatterns

#33874 [beta4] Fix blocked scheduler items not getting reschedule
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
Labels: Team/jBallerina

#33942 Improve `call-stmt` recovery
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/CallStatementTest.java
  compiler/ballerina-parser/src/test/resources/statements/call-stmt/call_stmt_assert_09.json
  compiler/ballerina-parser/src/test/resources/statements/call-stmt/call_stmt_source_09.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
Labels: Team/CompilerFE, Area/Parser

#33760 Fix completion issues with escaped chars and anon functions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/CompletionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_ctx_with_escape_char_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_with_anon_func_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_with_anon_func_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_with_anon_func_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_with_anon_func_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/source/var_def_ctx_with_escape_char_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/source/var_def_with_anon_func_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/source/var_def_with_anon_func_source2.bal
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/source/var_def_with_anon_func_source3.bal
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/source/var_def_with_anon_func_source4.bal
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_escaped_identifier_config1.json
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_escaped_identifier_source1.bal
Labels: Team/LanguageServer

#33998 Fix issue in tracking record fields in a wait-for-all expression
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWaitForAllExpr.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/actions/SymbolsInWaitActionsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/actions/symbols_in_wait_actions_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#33959 Fix wrong enclosed node picking issue in NodeFinder
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfRegressionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/regression-tests/typeof_listener_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#33828 [LS] Add completion support for mapping match pattern
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingMatchPatternNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/match_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/match_stmt_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/source/match_stmt_ctx_source12.bal
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/source/match_stmt_ctx_source13.bal
Labels: Team/LanguageServer

#34015 Fix parser test failure in master
  compiler/ballerina-parser/src/test/resources/statements/call-stmt/call_stmt_assert_09.json
Labels: Team/CompilerFE

#33986 Filter out Visible Worker Symbols within their Declaration Body
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/async_send_action_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/async_send_action_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/flush_action_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/flush_action_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/receive_action_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/receive_action_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/sync_send_action_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/sync_send_action_ctx_config2.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInWorkersTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/symbol_lookup_with_workers_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI, Area/Completion

#33418 Add initial expression editor workspace support
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/service/spi/ExtendedLanguageServerService.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManagerProxy.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/AbstractExtendedLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/toml/ballerinatoml/completion/BallerinaTomlCompletionExtension.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/LSClientUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManagerProxy.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManagerProxyImpl.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AbstractCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/diagnostics/DiagnosticsTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/exprscheme/TestExpressionFileScheme.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/TestWorkspaceManager.java
  language-server/modules/langserver-core/src/test/resources/project/myproject2/main.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
  misc/ballerinalang-data-mapper/src/test/java/org/ballerinalang/datamapper/util/DataMapperTestUtils.java
Labels: Team/LanguageServer

#33997 Fix completions inside `binary-expr` in `while-clause`
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/IntermediateClauseNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_where_clause_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_where_clause_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_where_clause_source3.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_where_clause_source4.bal
Labels: Team/LanguageServer

#34022 Fix issue with missing annotations in var symbols
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/VarDeclSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/var_decl_symbol_test.bal
Labels: Team/CompilerFETools, Team/CompilerFE, Area/SemanticAPI

#34040 Check referred invocation type in a type def
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/TypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal
Labels: Team/CompilerFE

#34042 Fix several issues related to type reference types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/VariableReturnType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/DependentlyTypedFunctionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ServiceDeclTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_with_listener_returning_custom_error.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant.bal
Labels: Team/CompilerFE
