Repository ballerina-platform/ballerina-lang, pull requests merged in 2022-02, with the labels that each got.

#34806 Add tests for the type of constants
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/MapConstantBalaNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/MapConstantInBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/SimpleConstantBalaNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/constant-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/map-literal-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/map_constant_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/map-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_negative/simple-literal-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant_code_analysis_negative.bal
Labels: Team/CompilerFE

#34913 Refactor context type resolver
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ErrorConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/error_constructor_expr_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/error_constructor_expr_ctx_source12.bal
Labels: Team/LanguageServer

#34555 Remove unicode code point validation on top of `BacktickString`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/UnicodeNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/xml.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/string-template-literal.bal
Labels: Team/CompilerFE

#34872 Add tests for object constructor expressions with closures
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/object/ObjectConstructorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_closures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_closures_annotations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_closure_unsupported_negative.bal
Labels: Team/CompilerFE

#34900 Refactor match-stmt tests
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchGuardAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementOnFailTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtListMatchPatternTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtTargetActionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ErrorBindingPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_guard_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match_target_actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/matchstmt_on_fail.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/capture-binding-pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/error_binding_pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/error_binding_pattern_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/list_binding_pattern.bal
Labels: Team/CompilerFE, Lang/Statements/Match

#34923 Fix runtime crashing for certain module names with configurable variables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ModuleInfo.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/ConfigClashingModule11.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/moduleNamedBallerina/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/moduleNamedBallerina/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testAmbiguousCases/moduleNamedBallerina/main.bal
Labels: Team/jBallerina

#34790 Add validation for assignability of Object types to Ballerina types when using runtime APIs
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ErrorCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Errors.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/modules/errors/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/records/records.bal
Labels: Team/jBallerina

#34977 Fix create function in return statement and fail expression
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CreateFunctionCommandExecTest.java
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_fail1.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_return1.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_fail1.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_return1.bal
Labels: Team/LanguageServer

#34201 Fix not showing arrow-function's params as completions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_with_anon_func_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_with_anon_func_config2.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInExpressionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInModuleLevelDeclsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/visible_symbols_in_exprs_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/visible_symbols_in_module_level_decls_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#35056 [`master`] Fix bug in named arg reference finding
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInErrorConstructorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_ref_in_error_ctr.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#34955 Update LS to use SyntaxInfo API and prevent renaming invalid qualified name references
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/PatternConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/rename/RenameUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/common/utils/CommonUtilTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/rename/RenameTest.java
  language-server/modules/langserver-core/src/test/resources/rename/expected/single/rename_identifier_with_escaped_char1.json
  language-server/modules/langserver-core/src/test/resources/rename/expected/single/rename_invalid_qname_ref.json
  language-server/modules/langserver-core/src/test/resources/rename/sources/single/rename_identifier_with_escaped_char1.bal
  language-server/modules/langserver-core/src/test/resources/rename/sources/single/rename_invalid_qname_ref.bal
Labels: Team/LanguageServer

#34958 Fix no field completions within mapping constructor inside a new expression
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingMatchPatternNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config38_negative.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config51.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config52.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config54.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config63.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source63.bal
Labels: Team/LanguageServer

#34907 Add tests for type reference
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/TypeReferenceTypeBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/typereftype/TypeReferenceTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/type_reference_type_bala_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/type_reference_type_bala_test_2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/type_reference_type_bala_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_type_reference_types/types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_type_reference_types_2/types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/type_reference.bal
Labels: Team/CompilerFE

#34921 Add Unreachability tests
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/reachability_analysis2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/unreachability_test2.bal
Labels: Team/CompilerFE

#35063 Fix missing `SimpleNameReferenceNode` wrapper for missing annotReference
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_21.json
  compiler/ballerina-parser/src/test/resources/declarations/object-type-def/object_type_def_assert_10.json
  compiler/ballerina-parser/src/test/resources/misc/annotations/annotations_assert_04.json
  compiler/ballerina-parser/src/test/resources/misc/annotations/annotations_assert_05.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_03.json
Labels: Team/CompilerFE, Area/Parser

#35082 Fix wrong code coverage for return statements
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/DebugInstructionTest.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/TestReportTest.java
Labels: Team/jBallerina

#35104 Fix wrong code coverage for return statements in master
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/DebugInstructionTest.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/TestReportTest.java
Labels: Team/jBallerina

#35066 Improve suggestion for `in` keword in let expression
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/LetExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/let-expr/let_expr_assert_14.json
  compiler/ballerina-parser/src/test/resources/expressions/let-expr/let_expr_assert_15.json
  compiler/ballerina-parser/src/test/resources/expressions/let-expr/let_expr_source_14.bal
  compiler/ballerina-parser/src/test/resources/expressions/let-expr/let_expr_source_15.bal
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_03.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_16.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_18.json
  compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_assert_13.json
  compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_source_13.bal
  compiler/ballerina-parser/src/test/resources/types/array-type/array_type_assert_21.json
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/config/let_expr_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/config/let_expr_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/source/let_expr_ctx_source15.bal
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/source/let_expr_ctx_source16.bal
Labels: Team/CompilerFE, Area/Parser, Area/Completion

#34470 Fix wrong code coverage for return statements in master
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/DebugInstructionTest.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/TestReportTest.java
Labels: Team/jBallerina

#35036 Fix debugger incorrect behavior with while loop
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/ControlFlowDebugTest.java
Labels: Team/jBallerina

#34967 Fix missing completions for field names in MappingConstructorExpressionNodeContext
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config64.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source64.bal
Labels: Team/LanguageServer

#34978 Introduce new API for getting string representation of a constant
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaConstantSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ConstantSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BConstantSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ConstDeclSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/const_decl_symbol_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#34996 Fix CCE in Function Calls with Future Return Types
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expressions_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#35034 Use stack to adjust yield depth dynamically
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ModuleStopMethodGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-stmt.bal
Labels: Team/jBallerina

#35103 Support enum types in JsonUtils API
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/JsonUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Jsons.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPITest.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/utils/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/utils/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/utils/modules/jsons/jsons.bal
Labels: Team/jBallerina

#35165 Fix type ID comparison
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTypeIdSet.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/distinct/TypeIdViaDifferentVersionsTest.java
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_bar/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_bar/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_bar/Package.md
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_bar/constructs.bal
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_baz/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_baz/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_baz/Package.md
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_baz/constructs.bal
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_foo/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_foo/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_foo/Package.md
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_foo/constructs.bal
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_foo_patch/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_foo_patch/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_foo_patch/Package.md
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_foo_patch/constructs.bal
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_qux/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_qux/Dependencies.toml
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_qux/Package.md
  tests/jballerina-integration-test/src/test/resources/packaging/distinct/test_project_distinct_qux/constructs.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/types/main.bal
Labels: Team/CompilerFE

#35164 [`2201.0.x`] Introduce new API for getting string representation of a constant
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaConstantSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/ConstantSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BConstantSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ConstDeclSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/const_decl_symbol_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#35007 Fix throwing NPE when table-type is defined without type-param
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#34287 Fix not retrieving class method members in `visibleSymbols()`
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BClassSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ServiceSemanticAPITest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolLookupTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInClassesAndObjectsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInExpressionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInModuleLevelDeclsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/visible_symbols_in_classes_and_objects.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#35196 Rename semtype test module
  settings.gradle
  tests/jballerina-semtype-port-test/build.gradle
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/types/SemTypeTest.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/basic.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/boolean-subtype.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/contextual.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/decimal-singleton.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/error1.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/error2.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/float-singleton.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/float-singleton2.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/function.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/hard.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/int-singleton.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/int-singleton2.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/int-subtype.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/never.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/readonly1.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/readonly2.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/string-all-subtypes.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/string-char.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/string-singleton-same-shape.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/string-singleton.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/table.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/tuple1.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/xml-never.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/xml-sequence.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/xml-singleton.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/xml.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/localVar/func.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/simple-type/float-altered.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/simple-type/function-altered.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/simple-type/int-singleton-altered.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/simple-type/list-type-test.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/simple-type/map-type-test.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/simple-type/type-test.bal
  tests/jballerina-semtype-port-test/src/test/resources/testng.xml
Labels: Team/CompilerFE, Area/SemtypePort

#35132 Fix completion issue within mapping expressions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingMatchPatternNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config36.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config40.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config65.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source65.bal
Labels: Team/LanguageServer

#35166 Add support to show error lang-lib methods for all-member error union type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/langlib_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#35238 Remove stage-swan-lake and add 2201.0.x to LS simulator workflow
  .github/workflows/language_server_simulator.yml
Labels: Team/LanguageServer

#35200 Remove adding the line number for `$init$` function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/jBallerina

#35021 Remove unnecessary GOTO basic blocks
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGenEnv.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIRBasicBlockOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/$lambda$_0
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/complexAddition
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/failLockWithinLock
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/failWithinOnFail
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/globalVarsAndAnonFunctions
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/mapInits
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/simpleAddition
  tests/jballerina-unit-test/src/test/resources/test-src/bir/biroptimizer.bal
Labels: Team/jBallerina

#35250 Remove adding the line number for `$init$` function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/jBallerina

#34984 Fix unhandled compiler exceptions being not result in test failures
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java
Labels: Team/CompilerFE

#35259 Enable build run for renamed `nutcracker` branch
  .github/workflows/pull_request_ubuntu_build.yml
  .github/workflows/pull_request_windows_build.yml
Labels: Team/CompilerFE, Area/SemtypePort

#35147 Fix self variable completions inside object constructor
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_in_obj_constructor_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/source/var_def_in_obj_constructor_source1.bal
Labels: Team/LanguageServer
