Repository ballerina-platform/ballerina-lang, pull requests merged in 2022-11, with the labels that each got.

#38477 Exclude import module compleiton items for generated modules
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
Labels: Team/LanguageServer

#38433 [2201.3.x] Add expression bodied function snippet completion item
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionDefinitionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModulePartNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModuleVariableDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ModulePartNodeContextUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/Snippet.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SnippetGenerator.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_decl/config/config21.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config22.json
  language-server/modules/langserver-core/src/test/resources/completion/enum_decl_ctx/config/config5.json
  language-server/modules/langserver-core/src/test/resources/completion/module_client_declaration_context/config/module_client_declaration_client_keyword.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config13.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config15_client_declaration.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config2.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config6.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_annotation_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_class_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_const_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_enum_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_funciton_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_import_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_listener_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_service_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_type_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_var_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_xmlns_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_annotation_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_class_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_const_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_enum_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_function_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_import_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_listener_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_service_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_type_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_var_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_xmlns_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config11.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config12.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config17.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config18.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config7.json
Labels: Team/LanguageServer

#38213 Remove escape characters in observability data
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
Labels: Team/jBallerina

#38479 [2201.2.3-stage] Remove non-public symbols warning in service-decl methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ServiceDeclTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/client_object_decl_with_non_public_symbols.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/service_class_decl_with_non_public_symbols.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_no_warnings.bal
Labels: Team/CompilerFE

#38428 [2201.3.x] Add fill record fields code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionContextTypeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/FillRecordFieldsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/NameUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/TypeResolverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingMatchPatternNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/FillRecordFieldsCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config10.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config11.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config12.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config9.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source4.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source5.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source6.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source7.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source8.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source9.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_binary_operation8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config29.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config59.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config60.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config62.json
Labels: Team/LanguageServer

#38476 [2201.3.0-stage] Remove non-public symbols warning in service-decl methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ServiceDeclTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/client_object_decl_with_non_public_symbols.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/service_class_decl_with_non_public_symbols.bal
  tests/jballerina-unit-test/src/test/resources/test-src/services/service_decl_no_warnings.bal
Labels: Team/CompilerFE

#38370 [master] Improve obj field mapping constructor completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source2.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source3.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source4.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source6.bal
Labels: Team/LanguageServer

#38367 [2201.3.x] Improve obj field mapping constructor completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source2.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source3.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source4.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source6.bal
Labels: Team/LanguageServer

#38495 [2201.3.0-stage] Remove re from reserved words
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/FunctionDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/RegExpConstructorExprTest.java
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_36.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_source_36.bal
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_26.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_40.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_41.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_42.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_43.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_40.bal
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_41.bal
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_42.bal
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_43.bal
  langlib/lang.regexp/src/main/ballerina/regexp.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Team/CompilerFE

#38409 Fix stackoverflow of tuples with self referencing
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/CyclicTypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/tuple-type-definitions-cyclic.bal
Labels: Team/jBallerina

#38268 Add tests where queries being used as function arguments
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/InnerQueryTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/inner-queries.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
Labels: Team/CompilerFE

#38284 [Master] Improve error message to convey proper meaning when the typedesc argument cannot be inferred for a dependently-typed function
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/InferredDependentlyTypeFunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature_negative.bal
Labels: Team/CompilerFE

#38527 [Master] Remove re from reserved words
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/FunctionDefinitionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/RegExpConstructorExprTest.java
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_assert_36.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_def_source_36.bal
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_26.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_40.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_41.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_42.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_43.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_40.bal
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_41.bal
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_42.bal
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_43.bal
  langlib/lang.regexp/src/main/ballerina/regexp.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Team/CompilerFE

#38371 Fix SO errors on inclusion of same record via field
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRecordType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordTypeInclusionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/test_record_cyclic_inclusion_via_field.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/test_record_cyclic_inclusion_via_field_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never_code_analysis_negative.bal
Labels: Team/CompilerFE

#38506 [2201.3.0-stage] Fix ModuleUtil to not add import statements for generated modules
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/ModuleUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AbstractCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction46.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/testProject2/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/testProject2/generated/idl-plugin-cache.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/testProject2/generated/myapi/idl_client.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/testProject2/main.bal
Labels: Team/LanguageServer

#38456 Use type from type cast and type param to construct values of specific expression kinds
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/arraylib_test_negative.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type_cast_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type_cast_expr_negative.bal
Labels: Team/CompilerFE

#38563 Fix completions for quote identifier given without the quote
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config29.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config59.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config60.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config62.json
Labels: Team/LanguageServer

#38172 Handle decimal subnormal and underflow cases
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java
  langlib/lang.decimal/src/main/java/org/ballerinalang/langlib/decimal/FromString.java
  langlib/langlib-test/src/test/resources/test-src/decimallib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/MultiplyOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/RefEqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserPositiveTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/equal_and_not_equal_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/ref_equal_and_not_equal_operation.bal
Labels: Team/jBallerina

#37823 Check decimal overflow at compile time
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalUsageTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_large_exponent_literal.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_usage.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_value_negative_literal.bal
Labels: Team/CompilerFE

#38525 [2201.3.0]Sync lang.regexp module with spec
  langlib/lang.regexp/src/main/ballerina/regexp.bal
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Find.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/RegexUtil.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Replace.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Split.java
  langlib/lang.string/src/main/ballerina/string.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
Labels: Team/CompilerFE

#38422 [2201.3.x] Improve type cast code action to consider union of numeric types
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeCastTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_assignment1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_conditional_expr1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_conditional_expr2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_conditional_expr3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_numeric1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/type_cast_in_assignment1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/type_cast_in_conditional_expr.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/type_cast_numeric.bal
Labels: Team/LanguageServer

#38416 [expected-type-api] Get the expected type for a given ST node position
  .github/workflows/pull_request_ubuntu_build.yml
  .github/workflows/pull_request_windows_build.yml
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/util/SymbolUtils.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ErrorConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImplicitNewExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/NamedArgumentNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/NodeWithRHSInitializerProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RemoteMethodCallActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RightArrowActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ExpressionContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/FieldAccessExpressionContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ModuleConstantContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/QueryExpressionContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/StatementContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/TypeDescContextTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/VariableDeclarationContextTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/ExpressionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/FunctionCallExpressionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/ListenerDeclarationTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/QueryExpressionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/RemoteActionNodeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/StatementTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/TableConstructorExpressionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/VariableDeclarationTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/expression_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/function_call_expression_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/listener_declaration_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/query_expression_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/remote_action_node_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/statement_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/table_constructor_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/variable_declaration_tests.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#38242 [master] Implement change sub type of raw template code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionContextTypeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeValidator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ConvertToXmlOrStringTemplateCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/TypeResolverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RemoteMethodCallActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ConvertToXmlOrStringTemplateCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config10.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config11.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config12.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config13.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config9.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/source/positional_args_source.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/source/source.bal
Labels: Team/LanguageServer, Area/CodeAction

#38589 Disable change parameter type code action on field accesses of a record type parameter
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeParamTypeTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-param-type/config/changeParamTypeInFieldAccess.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-param-type/source/changeParamTypeInFieldAccess.bal
Labels: Team/LanguageServer

#38318 Add runtime APIs to escape/unescape characters in identifiers
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/IdentifierUtils.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPITest.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/util/main.bal
Labels: Team/jBallerina

#38429 Remove injecting observability checkPointCall for desugared code
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/jBallerina, Area/GraalVM

#38620 [2201.3.0] Remove injecting observability checkPointCall for desugared code
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
Labels: Team/jBallerina

#38246 Add new basic block only for possible failures inside stmt-with-on-fail
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/onfail/OnFailClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause-negative-v2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/retrystmt/retry_stmt_with_on_fail.bal
Labels: Team/CompilerFE

#38590 Fix missing Fill required fields code action when invoking remote methods for records
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionContextTypeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/FillRecordFieldsCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config13.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source10.bal
Labels: Team/LanguageServer

#38232 Infer type-binding in outer join as nillable.
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_expr_with_errors.bal
Labels: Team/CompilerFE

#38597 Ignore create variable code actions when the variables type is compilation error
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleInsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableNegative5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableNegative6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableNegative7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableNegative3.bal
Labels: Team/LanguageServer

#37982 Implement visitors of start and wait action nodes in `SyntaxNodeToLocationMapper`
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typebynode/newapi/TypeByActionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/type-by-node/type_by_action.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#37606 Fix errors thrown from query clauses other than from/join being propagated to query result
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/lang.query/build.gradle
  langlib/lang.query/src/main/ballerina/helpers.bal
  langlib/lang.query/src/main/ballerina/types.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInQueryActionsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/symbol_lookup_in_query_actions.bal
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/LangLibDebugTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/narrowing/AssignmentToNarrowedVarsInLoopsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/ErrorQueryTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/InnerQueryTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryTypeNarrowingTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/narrowing/assignment_to_narrowed_vars_in_loops_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/inner-queries-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/inner-queries.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-query-construct-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-type-narrowing-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-type-narrowing.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_with_action_or_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_dataflow_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_expr_with_errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/reachability_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/unreachability_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-with-namespaces.bal
Labels: Team/CompilerFE

#38624 Fix completions in the field access expressions when the type is narrowed
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/foreach_stmt_ctx_source24.bal
Labels: Team/LanguageServer

#38667 [2201.3.0]Infer type-binding in outer join as nillable
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_expr_with_errors.bal
Labels: Team/CompilerFE

#38662 Fix master build failure due to parallel merge
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_expr_with_errors.bal
Labels: Team/CompilerFE

#38407 [master] Fix convert to query code action not suggesting for field access expressions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ConvertToQueryExpressionCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ConvertToQueryExpressionCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-query-expr/config/convert_to_query_expr_lhs_record_field3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-query-expr/source/convert_to_query_expr_lhs_record_field3.bal
Labels: Team/LanguageServer

#38362 Rename `org.ballerinalang.test.runtime.Main` class
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/FunctionMock.java
  misc/testerina/modules/testerina-runtime/spotbugs-exclude.xml
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/BTestMain.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java
Labels: Team/jBallerina

#38226 [master] Update LSPackageLoader to consider the modules of the current package
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/ModuleUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportOrgNameNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ServiceTemplateGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/eventsync/subscribers/PullModuleSubscriber.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/AbstractLSTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/lspackageloader/LSPackageLoaderTest.java
  language-server/modules/langserver-core/src/test/resources/completion/enum_decl_ctx/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/type_test_expression_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config23.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/projectls/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config11.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config12.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config13.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config21.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config24.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config26.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config8.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config16.json
Labels: Team/LanguageServer

#38397 Fix panicking when a new strand is created inside `lock`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BLock.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BLockStore.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/lock/LocksInMainTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-functions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks_in_functions_down_the_chain.bal
  tests/jballerina-unit-test/src/test/resources/test-src/lock/parallel-run-lock.bal
  tests/jballerina-unit-test/src/test/resources/test-src/lock/simple-lock.bal
Labels: Team/jBallerina

#38680 Increase timeout in strand dump test for `bal test`
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/troubleshoot/StrandDumpTest.java
Labels: Team/jBallerina

#38228 Update LSPackageLoader to consider the modules of the current package [2201.3.x]
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/ModuleUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportOrgNameNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ServiceTemplateGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/eventsync/subscribers/PullModuleSubscriber.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/AbstractLSTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/lspackageloader/LSPackageLoaderTest.java
  language-server/modules/langserver-core/src/test/resources/completion/enum_decl_ctx/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/type_test_expression_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config23.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/projectls/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config11.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config12.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config13.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config21.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config24.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config26.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config8.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config16.json
Labels: Team/LanguageServer

#38769 [2201.3.x] Fix compiler crash when using resource access actions in query expressions/actions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionWithActionOrExpr.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_with_action_or_expr.bal
Labels: Team/CompilerFE

#38459 Fix typo in DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
Labels: Stale

#38776 Fix OOM issue in ConstantValueResolver
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
Labels: Team/CompilerFE

#38282 [master] Refactor workspace service to gracefully access documents of generated folder with didOpen event
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Team/LanguageServer

#38748 [2201.3.0-stage] Allow unary expressions in const annotation attachments
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentSymbolsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments_negative.bal
Labels: Team/CompilerFE

#38749 [master] Allow unary expressions in const annotation attachments
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentSymbolsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments_negative.bal
Labels: Team/CompilerFE

#38446 Fix default values in fill required fields completions
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/SnippetContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/AnnotationUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config25.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config27.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config27a.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config28.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config30.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config31.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config32.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config32a.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config33.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config37.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config42.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config43.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config44.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config46.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config76.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source76.bal
Labels: Team/LanguageServer

#38781 [2201.3.0-stage] Fix encoding global variables in imported modules
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableArguments.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/testPackage/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/functions/testPackage/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/functions/testPackage/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/testPackage/modules/testModule/testModule.bal
Labels: Team/jBallerina

#38432 Fix `WaitForAnyActions` tests intermittent failures
  langlib/lang.runtime/src/main/ballerina/runtime.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/SymbolsWithinExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAnyActionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-for-any-actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Team/jBallerina

#37726 [Master] Fix incorrect results for panic in `module-const-declaration` with arithmetic operators
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangConstantValue.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-expression.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal
Labels: Team/CompilerFE

#38267 [master] Add create variable with type code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableWithTypeTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_for_remote_method_call_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_for_remote_method_call_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_for_resource_action_config.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_negative_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_negative_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_negative_config3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/source/negative_source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/source/negative_source2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/source/negative_source3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/source/source1.bal
Labels: Team/LanguageServer, Area/CodeAction

#38687 Stop sending diagnostics when LS in lightweight mode
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/capability/InitializationOptions.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSClientCapabilitiesImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/eventsync/subscribers/PublishDiagnosticSubscriber.java
Labels: Team/LanguageServer, Area/Diagnostics

#38771 Add documentation code action for enums and constants
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeAnalyzer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/AddAllDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/AddDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocumentationGenerator.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddDocumentationTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/add-documentation/config/singleDocGeneration11.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-documentation/config/singleDocGeneration12.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-documentation/source/singleDocGeneration.bal
Labels: Team/LanguageServer

#38295 [master] Refactor DocumentServiceContext visibleSymbols() method and completions in import declaration node
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/DocumentServiceContext.java
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/HoverContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportOrgNameNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/AbstractDocumentServiceContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaDefinitionContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/CompletionContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/HoverContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/PositionedOperationContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/ReferencesContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/SignatureContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/toml/ballerinatoml/completion/BallerinaTomlCompletionContext.java
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_no_module_name1.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_partial_module_name1.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_partial_module_name2.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/source/import_decl_with_no_module_name1.bal
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/source/import_decl_with_partial_module_name1.bal
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/source/import_decl_with_partial_module_name2.bal
Labels: Team/LanguageServer
