Repository ballerina-platform/ballerina-lang, pull requests merged in 2022-05, with the labels that each got.

#35957 Implement the Types API Builder of `ARRAY` type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/BallerinaArrayTypeBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/BallerinaTypeBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/TypeBuilder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypeBuildersTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#35997 Fix positional arg context type resolving logic (Sending #35986 to 2201.1.x)
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
Labels: Team/LanguageServer

#35992 Fix strand annotation completion in var-def
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/StatementContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/typeof_expression_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/typeof_expression_ctx_source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/start_action_ctx_config4a.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/source/start_action_ctx_source4a.bal
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/config/var_def_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/source/var_def_ctx_source18.bal
  language-server/modules/langserver-core/src/test/resources/completion/variable-declaration/source/var_def_ctx_source19.bal
Labels: Team/LanguageServer

#35938 Fix short-circuiting on operand evaluation in nil-lifted operations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/AddOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/BinaryBitwiseOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/BitwiseShiftOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/DivisionOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/ModOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/MultiplyOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/SubtractOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary_bitwise_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/bitwise_shift_operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/division-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/mod-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/subtract-operation.bal
Labels: Team/CompilerFE

#35977 Add toString() implementation for typedesc
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTypedescType.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type_cast_expr.bal
Labels: Team/jBallerina

#35981 Fix readonly check for in-built union type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BAnydataType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BJsonType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/TypeEmitter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/SelectivelyImmutableTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
Labels: Team/jBallerina

#35978 Fix hashcode method for cyclic types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTupleType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/CyclicTypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/tuple-type-definitions-cyclic.bal
Labels: Team/jBallerina

#35969 [Duplicate] Fix NPEs when passing null or empty maps for error details in error creator APIs
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ErrorCreator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Errors.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/modules/errors/errors.bal
Labels: Team/jBallerina

#35971 Fix incorrect type checking and conversion of numeric singletons
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/JsonUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finite/FiniteTypeNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/finite/finite_type_negative.bal
Labels: Team/jBallerina

#36005 Throw exception for unresolvable module imports at BIR
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
Labels: Team/CompilerFE

#35823 Allow calling a function from a different module in the module `init` function when there are uninitialized module-level variables
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/global_variable_init.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/global_variable_init_with_invocation_negative.bal
Labels: Team/CompilerFE

#36025 Add runtime API to create an enum type from the native code
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/TypeCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Enums.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/enums/enums.bal
Labels: Team/jBallerina

#35303 Fix completions for table type descriptor and table constructor expressions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RawTypeSymbolWrapper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TableTypeDescriptorNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/table_constructor_expr_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/table_constructor_expr_ctx_source9.bal
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/config/table_typedesc11.json
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/config/table_typedesc12.json
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/config/table_typedesc13.json
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/source/table_typedesc11.bal
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/source/table_typedesc12.bal
  language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/source/table_typedesc13.bal
Labels: Team/LanguageServer

#35999 Fix signature help and code action issues
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FieldAccessContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/ContextBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/SignatureContextImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverObjectResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/Parameter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/ParameterInfoModel.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureInfoModelBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/MarkupUtils.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/signature/IncludedRecordParameterTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableWithRemoteMethodInvocation.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config1a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config2a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config3a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config51.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5b.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5c.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config23.json
  language-server/modules/langserver-core/src/test/resources/signature/included_record/config/config1.json
  language-server/modules/langserver-core/src/test/resources/signature/included_record/config/config2.json
  language-server/modules/langserver-core/src/test/resources/signature/included_record/config/config3.json
  language-server/modules/langserver-core/src/test/resources/signature/included_record/source1.bal
Labels: Team/LanguageServer

#36004 Disallow additive expression with operands that contain a union of basic types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/AddOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation-negative.bal
Labels: Team/CompilerFE

#36010 Add document this code action to annotation declarations
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/codeaction/CodeActionNodeType.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeAnalyzer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/AddAllDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/AddDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocumentationGenerator.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddDocumentationTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/AddDocumentationCommandExecTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/add-documentation/config/singleDocGeneration10.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleAnnotationDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/document_already_documented_config7.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/source/commonDocumentation.bal
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/source/document_already_documented1.bal
Labels: Team/LanguageServer

#36071 Backport #36005 to 2201.0.x branch
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
Labels: Team/CompilerFE

#35917 Fix BIR/JAR mismatch for anon types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
Labels: Team/CompilerFE

#35925 Fix issue with BRecordType fields in BSameTypeVisitor
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordAssignabilityTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/record_assignability_negative.bal
Labels: Team/CompilerFE

#36044 Fix NPE when variable of undefined type used in from and join clauses
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
Labels: Team/CompilerFE

#36085 Allow `int, floating point` multiplication with singleton types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/MultiplyOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/division-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/mod-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation.bal
Labels: Team/CompilerFE

#35718 Port function semtype changes
  semtypes/src/main/java/io/ballerina/types/typeops/FunctionOps.java
Labels: Team/CompilerFE, Stale, Area/SemtypePort

#36093 Fix NPE on subsequent compilation when immutable type is unset
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/defns/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/main.bal
Labels: Team/CompilerFE

#36115 Refactor mock function replacement logic to fix issues related to callOriginal cases
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/FunctionMock.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/MockConstants.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/Main.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/MockFunctionReplaceVisitor.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/MockTest.java
  tests/testerina-integration-test/src/test/resources/project-based-tests/function-mocking-tests/tests/main_test.bal
Labels: Team/jBallerina

#36143 Update the spec version to 2022R2
  gradle.properties
Labels: Team/CompilerFE

#35460 Handle typeParam when parameter type is not availabe in function
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal
Labels: Team/CompilerFE

#36043 Fix `WorkerFlushTest#errorBeforeFlush` intermittent failure
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WorkerDataChannel.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFlushTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/flush-workers.bal
Labels: Team/jBallerina

#35976 Fix non-worker thread calling to `FromJsonWithType()`
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonWithType.java
  tests/jballerina-unit-test/build.gradle
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/records/records.bal
Labels: Team/jBallerina

#36042 Validate invalid `UTF-8` values for `fromBytes()` langlib method
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/FromBytes.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
Labels: Team/jBallerina

#35951 Fix union type array filler values
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BArrayType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFiniteType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayFillTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/SealedArrayTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-fill-test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_listexpr_negative.bal
Labels: Team/jBallerina

#35772 Fix NPE occures for object-constructor in DataFlowAnalyser
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/object/ObjectConstructorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_expression.bal
Labels: Team/CompilerFE

#36051 Address review suggestions for #36004
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
Labels: Team/CompilerFE

#35709 Add validations to code actions
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/CodeActionContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeValidator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractImplementMethodCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddAccessModifierCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddExplicitReturnToFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddOnFailCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ConvertToReadonlyCloneCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/IgnoreUnusedVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementAllCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/MakeConstructPublicCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ModVarToListenerDeclCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/RemoveUnreachableCodeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleInsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/IgnoreReturnCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/UpdateDocumentationCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/CodeActionContextImpl.java
Labels: Team/LanguageServer

#36026 Enable error type rename test in ProjectRenameTest
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/AbstractCommandExecutionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/rename/ProjectRenameTest.java
Labels: Team/LanguageServer

#36120 Fix pruning issue in `block-stmt` parsing
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/BlockStatementTest.java
  compiler/ballerina-parser/src/test/resources/statements/block-stmt/block_stmt_assert_08.json
  compiler/ballerina-parser/src/test/resources/statements/block-stmt/block_stmt_source_08.bal
Labels: Team/CompilerFE, Area/Parser

#36007 Fix xml subtypes not being suggested in xml type param
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterContextProvider.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/XMLTypeDescContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/xml_typedesc_context/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/xml_typedesc_context/config/config2.json
Labels: Team/LanguageServer

#36117 Add more details to createRecordValue method javadoc
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java
Labels: Team/jBallerina

#35990 Add missing completion items in QE context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/LetVariableDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_let_clause_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_let_clause_source15.bal
Labels: Team/LanguageServer

#35928 Fix impConversionExpr type for checking-expr with no error type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangCheckedExpr.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkpanicexpr/CheckPanicExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_with_no_error_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkpanicexpr/check_panic_expr_with_no_error_type.bal
Labels: Team/CompilerFE

#36250 Fix LSPackage loader to avoid duplicate packages
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java
Labels: Team/LanguageServer

#36275 Introduce `checking-stmt`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/statements/call-stmt/call_stmt_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/call-stmt/call_stmt_assert_09.json
  compiler/ballerina-parser/src/test/resources/statements/call-stmt/call_stmt_assert_10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/check_expression_ctx_config9.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/checkingstatement/CheckingStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/expressionstmt/ExpressionStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/checkingstatement/checking-stmt-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/checkingstatement/checking-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/expression/expression-stmt2-negative.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#36226 Add default package org, name & version to `Ballerina.toml` when creating and initiating new project
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/CommandUtil.java
  cli/ballerina-cli/src/main/resources/new_cmd_defaults/manifest-app.toml
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/InitCommandTest.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java
Labels: Priority/High, Team/DevTools, Points/0.25, Area/ProjectAPI

#36066 Fix spec conformance test runner chat link
  .github/workflows/daily_spec_conformance_test_runner.yml
Labels: Team/CompilerFE

#36312 Support propagating failures returned from query clauses
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  langlib/lang.query/src/main/ballerina/helpers.bal
  langlib/lang.query/src/main/ballerina/types.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/ErrorQueryTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_expr_with_errors.bal
Labels: Team/CompilerFE

#36177 Fix issue cloning BLangLiteral
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ClassTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/klass/class_def_test.bal
Labels: Team/CompilerFE

#36202 Send same PR #36177 to `2201.1.x`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ClassTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/klass/class_def_test.bal
Labels: Team/CompilerFE

#36214 Add import statement generator to LSSimulator
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/EditorSimulator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/Generators.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/ImportStatementGenerator.java
Labels: Team/LanguageServer

#36189 Add completions for configurable qualifier
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModuleVariableDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/source/source14.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/source/source15.bal
Labels: Team/LanguageServer

#36121 Fix `ImmutableTypeCloner` not setting the correct origin for virtual symbols
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testproject/type_defs.bal
Labels: Team/CompilerFE

#35860 Port list semtype changes
  semtypes/src/main/java/io/ballerina/types/typeops/ListCommonOps.java
  semtypes/src/main/java/io/ballerina/types/typeops/ListProj.java
  semtypes/src/main/java/io/ballerina/types/typeops/TwoTuple.java
Labels: Area/SemtypePort

#35963 Code action to make annotation declaration constant
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/MakeAnnotationDeclConstantCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/MakeAnnotDeclarationConstantCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/make-annot-declaration-const/config/annotationDeclaration.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-annot-declaration-const/source/annotationDeclaration.bal
Labels: Team/LanguageServer

#36011 Avoid PA estimations for scenarios that has workers with connector calls
  misc/ls-extensions/modules/performance-analyzer-services/src/main/java/io/ballerina/EndpointsFinder.java
  misc/ls-extensions/modules/performance-analyzer-services/src/main/java/io/ballerina/PerformanceAnalyzerNodeVisitor.java
  misc/ls-extensions/modules/performance-analyzer-services/src/test/java/io/ballerina/PerformanceAnalyzerTest.java
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/project/Ballerina.toml
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/project/forEach.bal
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/project/ifElse.bal
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/project/main.bal
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/project/modules/http/http_client_endpoint.bal
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/project/modules/http/http_service_endpoint.bal
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/project/noData.bal
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/project/while.bal
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/worker/Ballerina.toml
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/worker/main.bal
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/result/worker.json
Labels: Team/LanguageServer/Extensions

#36205 Avoid renaming on a compilation error
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/ReferencesUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/rename/RenameUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/rename/RenameTest.java
  language-server/modules/langserver-core/src/test/resources/rename/expected/single/rename_with_compilation_error.json
  language-server/modules/langserver-core/src/test/resources/rename/sources/single/rename_with_compilation_error.bal
Labels: Team/LanguageServer

#36175 Fix compiler crashing when on-fail used within anonymous definitions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause.bal
Labels: Team/CompilerFE

#35960 Fix "Incorrect behaviour when using a table constructor expression with any"
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableValueAssignTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-value-any-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_key_field_value_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_value_assign_test.bal
Labels: Team/CompilerFE

#36000 Remove BLangMatch
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/statements/MatchNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClassClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/SimpleBLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangMatchExpression.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangMatch.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/mapInits
Labels: Team/CompilerFE

#35996 Add tests for annotation attachments on enum
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments_negative.bal
Labels: Team/CompilerFE

#35859 Fix NPE in readonly intersection
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Team/CompilerFE

#36188 Add tests to test visibility of non-public symbols
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/visibility/Visibility.java
  tests/jballerina-unit-test/src/test/resources/test-src/visibility/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/visibility/modules/mod/mod.bal
  tests/jballerina-unit-test/src/test/resources/test-src/visibility/modules/mod/tests/test.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#35911 Stop reading templates when there are no errors
  tests/ballerina-spec-conformance-tests/src/test/java/org/ballerinalang/test/ReportGenerator.java
Labels: Team/CompilerFE, Stale, Area/SpecConformanceTestRunner

#36012 Propagate XMLNS to query scope
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralWithNamespacesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-with-namespaces.bal
Labels: Team/CompilerFE

#35946 Fix compiler crash for table multi-key-expression
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BaseVisitor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/TableMultiKeyExpressionNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClassClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/SimpleBLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTableMultiKeyExpr.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableCastTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-negative.bal
Labels: Team/CompilerFE
