Repository ballerina-platform/ballerina-lang, pull requests merged in 2022-04, with the labels that each got.

#35483 Fix intermittent failing in PkgResIntTests
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionIntegrationTests.java
  project-api/project-api-test/src/test/resources/projects_for_resolution_integration_tests/project_o_local_dependency/resources/Dependencies.toml
  project-api/project-api-test/src/test/resources/projects_for_resolution_integration_tests/project_o_with_import/resources/Dependencies.toml
Labels: Stale

#35534 Fix showing wrong method name in completions for methods in abstract objects
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/ProgramFileConstants.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_import_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testproject/type_defs.bal
Labels: Team/CompilerFETools, Team/CompilerFE, Area/SemanticAPI

#35618 Fix references API for error binding patterns
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangErrorVariable.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInErrorBindingPatternsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_ref_in_error_binding_patterns.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#35579 Fix signature of array type symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaArrayTypeSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#35505 Add tests for casting JSON to map<anydata>
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal
Labels: Team/CompilerFE

#35469 Check if import statement only available
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/visitor/UnusedSymbolsVisitor.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/extensions/document/SyntaxTreeModifyTest.java
  language-server/modules/langserver-core/src/test/resources/extensions/document/ast/modify/removeImportExpected.bal
Labels: Stale

#35698 Fix completions in on fail node context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/OnFailClauseNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/onfail_clause_ctx_config2b.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/onfail_clause_ctx_config2c.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/source/onfail_clause_ctx_source2b.bal
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/source/onfail_clause_ctx_source2c.bal
Labels: Team/LanguageServer

#35601 Add type checker support for spread operator in `list-constructor-expr`
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/SimpleBLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangListConstructorExpr.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorSpreadOperatorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/TupleVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/CyclicTypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/BasicTupleTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_spread_op_inference_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_spread_op_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_spread_op_self_ref_negative.bal
Labels: Team/CompilerFE

#35374 New code action to make construct public
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/MakeConstructPublicCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/definition/DefinitionUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/MakeConstructPublicCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/make-construct-public/config/convert_to_public_class_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-construct-public/config/convert_to_public_record_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-construct-public/source/publicCodeAction/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/make-construct-public/source/publicCodeAction/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-construct-public/source/publicCodeAction/modules/module1/convert_to_public_class_source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-construct-public/source/publicCodeAction/modules/module2/convert_to_public_record_source2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-construct-public/source/publicCodeAction/modules/module2/convert_to_public_record_source2_test.bal
Labels: Team/LanguageServer

#35688 Fix issues related to endBB of local variables
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGenEnv.java
Labels: Team/jBallerina

#35496 Support for array:some langlib function
  langlib/lang.array/src/main/ballerina/array.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/arraylib_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/arraylib_test_negative_semantic.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config28.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config34.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config22.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config9.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
Labels: Team/CompilerFE

#35746 Add tearDown methods and Override annotations for few locations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibBooleanTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibDecimalTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibErrorTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibFloatTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibIntTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibMapTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibNegativeTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRecordTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRuntimeTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStreamTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTupleTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTypedescTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachArrayTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachArrayTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachComplexTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachErrorBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachErrorHandlingTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachIterableObjectTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachJSONTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachJSONTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachMapTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachMapTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachOnFailTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachRecordTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachStringTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachTableTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachTupleTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachXMLTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachXMLTypedBindingPatternsTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/NestedForeachTest.java
Labels: Team/CompilerFE, Area/CompilerInternal

#35353 Introduction of the new Types API for getting all the built-in types and type definitions
  compiler/ballerina-lang/build.gradle
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/SemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/Types.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaTypes.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BEnumSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BTypeDefinitionSymbol.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypesTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/types-project/Ballerina.toml
  tests/ballerina-compiler-api-test/src/test/resources/test-src/types-project/main.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/types-project/modules/bar/more_typedefs.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/types-project/modules/bar/types.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/types-project/modules/foo/type_defs.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typesbir/Ballerina.toml
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typesbir/type_def.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Type/NewFeature, Team/CompilerFETools, Area/SemanticAPI

#35594 Add missing create function code action in several contexts
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/IsolatedBlockResolver.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateFunctionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CreateFunctionCommandExecTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeActionInObjectField1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeActionInRecordField1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/createUndefinedFunctionInObjectField.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/createUndefinedFunctionInRecordField.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/createUndefinedFunctionInObjectField1.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/createUndefinedFunctionInRecordField1.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/createUndefinedFunctionInObjectField.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/createUndefinedFunctionInRecordField.bal
Labels: Team/LanguageServer

#35722 Add function last line as return statement pos
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
Labels: Team/jBallerina

#35583 Improve filler value check for xml sub-types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayFillTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-fill-test.bal
Labels: Team/jBallerina

#35239 Improve filler value check for xml sub-types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayFillTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-fill-test.bal
Labels: Team/jBallerina

#35616 Allow int varref with other numeric operands in a multiplicative expression
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/DivisionOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/ModOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/MultiplyOperationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/division-operation-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/division-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/mod-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/mod_operation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation.bal
Labels: Team/CompilerFE, Area/TypeChecker

#35598 Add `padStart`, `padEnd`, `padZero` langlib functions to `string.bal`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  langlib/lang.string/src/main/ballerina/string.bal
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/PadEnd.java
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/PadStart.java
  langlib/lang.string/src/main/java/org/ballerinalang/langlib/string/PadZero.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/stringlib_negative_test.bal
  langlib/langlib-test/src/test/resources/test-src/stringlib_panic_test.bal
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config33.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config43.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config53.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config13.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/completions/DebugCompletionTest.java
Labels: Team/CompilerFE, Lang/LangLib

#35468 Add support for tuple type configurable variables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigResolver.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/Utils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/ConfigTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/CliProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/ArrayConfig.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/ArrayWrongSize.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/MapArrInlineTypeError1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/MapArrInlineTypeError2.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/MapInlineTypeError1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/MapInlineTypeError2.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/RecordArrInlineTypeError1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/RecordArrInlineTypeError2.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/RecordInlineTypeError1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/RecordInlineTypeError2.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TableInlineTypeError1.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TableInlineTypeError2.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TableInlineTypeError3.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TupleByteRange.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TupleElementStructure.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TupleElementType.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TupleRestTypeMisMatch.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TupleStructureError.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TupleTypeError.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/TupleWrongSize.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/UnsupportedCliConfig.toml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlInlineTableValueNode.java
  misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTableNode.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_default_values_inline.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_maps_inline.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_open_records_inline.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_record_arrays_inline.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_records_inline.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_tables_inline.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_tuples.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_tuples_inline.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/Config_xml_inline.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configTupleType/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configStructuredTypesProject/configTupleType/main.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_global_var_decl_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_positive.bal
Labels: Team/jBallerina

#35531 Support array:every langlib function
  langlib/lang.array/src/main/ballerina/array.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/arraylib_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/arraylib_test_negative_semantic.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config28.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config34.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config22.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config9.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
Labels: Team/CompilerFE

#35751 Add more tests for int varref with other numeric operands
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/division-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/mod-operation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation.bal
Labels: Team/CompilerFE

#35703 Add support for float:toFixedString() and float:toExpString()
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/FloatUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  langlib/lang.float/src/main/ballerina/float.bal
  langlib/lang.float/src/main/java/org/ballerinalang/langlib/floatingpoint/ToExpString.java
  langlib/lang.float/src/main/java/org/ballerinalang/langlib/floatingpoint/ToFixedString.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibFloatTest.java
  langlib/langlib-test/src/test/resources/test-src/floatlib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config18.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
Labels: Team/CompilerFE

#35681 Implementation for `decimal.round` with `fractionDigits`
  langlib/lang.decimal/src/main/ballerina/decimal.bal
  langlib/lang.decimal/src/main/java/org/ballerinalang/langlib/decimal/Round.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibDecimalTest.java
  langlib/langlib-test/src/test/resources/test-src/decimallib_test.bal
Labels: Team/CompilerFE

#35742 Add support for decimal:quantize() langlib function
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  langlib/lang.decimal/src/main/ballerina/decimal.bal
  langlib/lang.decimal/src/main/java/org/ballerinalang/langlib/decimal/Quantize.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibDecimalTest.java
  langlib/langlib-test/src/test/resources/test-src/decimallib_test.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
Labels: Team/CompilerFE

#35696 Implement bir, codegen and runtime changes for spread operator
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ListInitialValueEntry.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/listconstructor/ListConstructorSpreadOperatorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_spread_op.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_spread_op_inference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_spread_op_inference_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_spread_op_negative.bal
Labels: Team/CompilerFE

#35758 Improve decimal round tests
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibDecimalTest.java
  langlib/langlib-test/src/test/resources/test-src/decimallib_test.bal
Labels: Team/CompilerFE

#35606 Support new float:round langlib function
  langlib/lang.float/src/main/ballerina/float.bal
  langlib/lang.float/src/main/java/org/ballerinalang/langlib/floatingpoint/Round.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibFloatTest.java
  langlib/langlib-test/src/test/resources/test-src/floatlib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config17.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config18.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/return_stmt_ctx_config18.json
Labels: Team/CompilerFE

#34817 Allow additive-expr with operands of a union type containing builtin subtypes of string and xml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/AddOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation.bal
Labels: Team/CompilerFE

#35614 Add support for simple union type configurable variables via CLI
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/CliProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/CliProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
Labels: Team/jBallerina

#35535 Move mock functions replacement from BIRGen to test runtime
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangTestablePackage.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/MockAnnotationProcessor.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TesterinaRegistry.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/FunctionMock.java
  misc/testerina/modules/testerina-runtime/spotbugs-exclude.xml
  misc/testerina/modules/testerina-runtime/src/main/java/module-info.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/CustomClassLoader.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/Main.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/MockFunctionReplaceVisitor.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TestSuite.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java
Labels: Team/jBallerina

#35766 Fix the NPE when a worker is defined after an if block without an else block
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/narrowing_with_if_without_else_not_completed_normally_test.bal
Labels: Team/CompilerFE

#35715 Split large start and stop methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/LargeMethodSplitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Constants.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/large-number-of-listeners.bal
Labels: Team/jBallerina

#35243 Add validation for runtime APIs
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ErrorCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Errors.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/modules/errors/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/records/records.bal
Labels: Team/jBallerina

#35778 Fix BFunctionType toString method
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFunctionType.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
Labels: Team/jBallerina

#35708 Refactor compiler backend to avoid running bir and codegen twice for module sources when running tests
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/ModuleID.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaModuleID.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JarResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleDescriptor.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/PackageID.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/utils/DebugSourceLocation.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/utils/PackageUtils.java
  misc/testerina/modules/testerina-core/spotbugs-exclude.xml
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/FunctionMock.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/BTestRunner.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/Main.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TestSuite.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/CodeCoverageReportTest.java
Labels: Team/jBallerina

#35189 Add annotation attachments to the BIR
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibFunctionBinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaFunctionTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectFieldSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaPathParameterSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaRecordFieldSymbol.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/symbols/Annotatable.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/symbols/AnnotationAttachmentSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGenEnv.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/AnnotationProc.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRBinaryWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BAnnotationAttachmentSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BAnnotationSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BClassSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BEnumSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BInvokableSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BInvokableTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BTypeDefinitionSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BVarSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/SymTag.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangAnnotationAttachment.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java
  langlib/lang.annotations/src/main/ballerina/annotations.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentSymbolsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/annotations/annot_attachments_bala_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_annotation_project/annotations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_annotation_usage_project/annotations_usage.bal
Labels: Team/CompilerFE

#35781 Address review suggestions for #35703
  langlib/lang.float/src/main/java/org/ballerinalang/langlib/floatingpoint/ToExpString.java
  langlib/langlib-test/src/test/resources/test-src/floatlib_test.bal
Labels: Team/CompilerFE

#35807 Overwrite the immutable type when recompiled
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/CompilerPluginTests.java
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/records/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/records/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/CompilerPlugin.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/main.bal
Labels: Team/CompilerFE

#35809 Overwrite the immutable type when recompiled
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/CompilerPluginTests.java
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/records/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/records/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/CompilerPlugin.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/main.bal
Labels: Team/CompilerFE

#34940 Fix accessing symbols introduced within immediate from clause, through the frame symbol
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/InnerQueryTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/inner-queries-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/inner-queries.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal
Labels: Team/CompilerFE

#35646 Fix issue when exponent indicator of floating-point literal is not followed by a digit
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/NumericLiteralSupport.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_assert_08.json
  compiler/ballerina-parser/src/test/resources/expressions/basic-literals/float_literal_source_08.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/FloatingPointLiteralInvalidSyntaxTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/floating_point_literal_syntax_negative.bal
Labels: Team/CompilerFE

#35796 Fix issue in let expressions with lambda functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/let/LetExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal
Labels: Team/CompilerFE

#35637 Restrict using empty init for unbounded streams
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Team/CompilerFE

#35799 Fix `anydata` casting with any value
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeTestGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmConstantsGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/anydata/AnydataTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_test.bal
Labels: Team/jBallerina

#35849 Fix readonly check for in-built union type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BAnydataType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BJsonType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/TypeEmitter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/SelectivelyImmutableTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
Labels: Team/jBallerina

#35797 Fix NPEs when passing null or empty maps for error details in error creator APIs
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ErrorCreator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Errors.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/errors/modules/errors/errors.bal
Labels: Team/jBallerina

#34612 Disallow inferring array sizes from the contexts that are not permitted
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/SealedArrayTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/arraysofarrays/SealedArraysOfArraysTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/global_arrays.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/arraysofarrays/code_analysis_negative_sealed_arrays_of_arrays.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/arraysofarrays/negative-sealed-arrays-of-arrays.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/arraysofarrays/sealed-arrays-of-arrays.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/sealed_array_semantics_negative.bal
Labels: Team/CompilerFE

#35475 Improve type resolution
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangClassDefinition.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangTypeDefinition.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangObjectTypeNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangRecordTypeNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangStructureTypeNode.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/RecordInBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/TypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/modules/records/cyclic_record_inclusions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/complex_record_resolution.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/rest_in_bala.bal
Labels: Team/CompilerFE

#35816 Fix issues with handling empty keyed tables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BTableType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTableTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/TypeEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTableType.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneWithType.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonWithType.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal
  langlib/langlib-test/src/test/resources/test-src/tablelib_test_negative.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/RecordConstraintTableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableCastTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/record-constraint-table-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/tables-cast-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/tables-cast.bal
Labels: Team/CompilerFE

#35326 Fix compiler crash for defualtable params in methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectFunctionsWithDefaultableArguments.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_functions_with_default_parameters_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_functions_with_default_parameters_rt_failure.bal
Labels: Team/CompilerFE

#35830 Fix issues with calling `array:sort` with named arguements
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibArrayTest.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
  langlib/langlib-test/src/test/resources/test-src/arraylib_test_negative.bal
Labels: Team/CompilerFE

#35866 Fix setting immutable type to main module types during test compilation
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java
  tests/testerina-integration-test/src/test/resources/project-based-tests/intersection-type-test/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/intersection-type-test/tests/main_test.bal
Labels: Team/CompilerFE

#35888 Fix issue in parsing singleton type
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/types/singleton-type/singleton_type_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/singleton-type/singleton_type_source_01.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/uniontypes/UnionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/uniontypes/union_types_basic.bal
Labels: Team/CompilerFE, Area/Parser

#35897 Add 2201.1.x and 2201.1.0-stage to LS simulator
  .github/workflows/language_server_simulator.yml
Labels: Team/LanguageServer

#35856 Update resource function snippet default values
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SnippetGenerator.java
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config12.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config13.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config17.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config2.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config4.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config8.json
  language-server/modules/langserver-core/src/test/resources/completion/service_body/config/config5.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config10.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config11.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config15.json
Labels: Team/LanguageServer

#35853 Implement create function with named args
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/CreateFunctionExecutor.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CreateFunctionCommandExecTest.java
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_with_named_args1.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_with_named_args1.bal
Labels: Team/LanguageServer

#35906 Fix invalid type cast code action suggestion
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeCastTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCastNegative5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/typeCast.bal
Labels: Team/LanguageServer

#35747 Implement the Types API Builder for `XML` type
  compiler/ballerina-lang/build.gradle
  compiler/ballerina-lang/spotbugs-exclude.xml
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/Types.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaTypes.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaXMLTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/BallerinaTypeBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/BallerinaXMLTypeBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/types/TypeBuilder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypeBuildersTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/types-project/modules/builder/typedefs.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#35630 Fix error being returned from query exp even when enclosed within on fail
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/ErrorQueryTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_expr_with_errors.bal
Labels: Team/CompilerFE

#35829 Fix compiler crash on assignment to a narrowed variable in a query action
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/narrowing/AssignmentToNarrowedVarsInLoopsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/narrowing/assignment_to_narrowed_vars_in_loops_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-type-narrowing-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_dataflow_negative.bal
Labels: Team/CompilerFE

#35625 Modify record snippet labels
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config22.json
  language-server/modules/langserver-core/src/test/resources/completion/enum_decl_ctx/config/config5.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config2.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config6.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config17.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config18.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config7.json
Labels: Team/LanguageServer

#35529 Add create record and extract type code actions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-type/config/create_type_in_function_body1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-type/config/create_type_in_return_type1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-type/source/create_type_in_function_body1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-type/source/create_type_in_return_type1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/config/extract_type_in_fn_body1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/config/extract_type_in_fn_body2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/config/extract_type_in_fn_body3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/config/extract_type_in_resource_fn1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/config/extract_type_in_return_type_desc1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/config/extract_type_in_return_type_desc2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/source/extract_type_in_fn_body1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/source/extract_type_in_fn_body2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/source/extract_type_in_fn_body3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/source/extract_type_in_resource_fn1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-type/source/extract_type_in_return_type_desc1.bal
Labels: Team/LanguageServer

#35916 Remove std lib imports from LS unit tests
  language-server/modules/langserver-core/src/test/resources/codeaction/change-param-type/source/changeParamTypeInService.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/test-gen/source/testgen/src/module1/functions.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/test-gen/source/testgen/src/module2/services.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/source/typeGuard.bal
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/source/addAllDocumentationWithAnnotations.bal
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/source/addSingleFunctionDocumentation2.bal
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/source/commonDocumentation.bal
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/source/serviceDocumentationWithAnnotations.bal
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/source/async_send_action_ctx_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/source/async_send_action_ctx_source2.bal
  language-server/modules/langserver-core/src/test/resources/docsymbol/source/docSymbol.bal
  language-server/modules/langserver-core/src/test/resources/documentsymbol/source/project1/main.bal
  language-server/modules/langserver-core/src/test/resources/execpositions/configs/project/main.bal
  language-server/modules/langserver-core/src/test/resources/execpositions/configs/project/modules/module/hello.bal
  language-server/modules/langserver-core/src/test/resources/execpositions/configs/single-file/main.bal
  language-server/modules/langserver-core/src/test/resources/foldingrange/source/function.bal
  language-server/modules/langserver-core/src/test/resources/foldingrange/source/service.bal
  language-server/modules/langserver-core/src/test/resources/implementation/source/gotoImplProject/src/pkg1/tests/main_test.bal
  language-server/modules/langserver-core/src/test/resources/signature/source/endpointActions.bal
  language-server/modules/langserver-core/src/test/resources/signature/source/functionInBuiltinPackage.bal
  language-server/modules/langserver-core/src/test/resources/signature/source/functionsAndTypeDefs.bal
  language-server/modules/langserver-core/src/test/resources/signature/source/signatureWithinAnnotations.bal
  language-server/modules/langserver-core/src/test/resources/signature/source/signatureWithinCheckPanic.bal
  language-server/modules/langserver-core/src/test/resources/signature/source/signatureWithinObjectFunctions.bal
  language-server/modules/langserver-core/src/test/resources/signature/source/signatureWithinResources.bal
  language-server/modules/langserver-core/src/test/resources/signature/source/signatureWithinTransaction1.bal
  language-server/modules/langserver-core/src/test/resources/stnode/stnode_test.bal
Labels: Team/LanguageServer

#35801 Improve parser recovery for partially written annotations in expressions
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/AnnotationsTest.java
  compiler/ballerina-parser/src/test/resources/expressions/list-constructor/list_constructor_assert_09.json
  compiler/ballerina-parser/src/test/resources/misc/annotations/annotations_assert_11.json
  compiler/ballerina-parser/src/test/resources/misc/annotations/annotations_source_11.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/object/ObjectConstructorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_expression_negative.bal
Labels: Team/CompilerFE, Area/Parser

#35941 Fix referring to immutable types without type definitions when code modifier plugins are used
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/types/SelectivelyImmutableReferenceType.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/types/ServiceType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BAnyType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BArrayType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BIntersectionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BMapType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRecordType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTableType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTupleType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLSubType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/CompilerPluginTests.java
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/defns/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/defns/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/records/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/main.bal
Labels: Team/CompilerFE

#35484 Infer stream parameters when not given
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStreamTest.java
  langlib/langlib-test/src/test/resources/test-src/streamlib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Team/CompilerFE

#35910 Fix annotations on direct bound method access
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationRuntimeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/annotations/annotation.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/annotations.bal
Labels: Team/CompilerFE

#35961 Fix OOM issue when running LS tests
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/AbstractLSTest.java
Labels: Team/LanguageServer

#35967 Fix possible NPE in SymbolResolver
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
Labels: Team/CompilerFE

#35962 Fix OOM issue of LS tests
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/AbstractLSTest.java
Labels: Team/LanguageServer

#35952 Send same PR #35801 to `2201.1.x`
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/AnnotationsTest.java
  compiler/ballerina-parser/src/test/resources/expressions/list-constructor/list_constructor_assert_09.json
  compiler/ballerina-parser/src/test/resources/misc/annotations/annotations_assert_11.json
  compiler/ballerina-parser/src/test/resources/misc/annotations/annotations_source_11.bal
  compiler/ballerina-parser/src/test/resources/misc/predeclared-module-prefix/predeclared-module-prefix_assert_02.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/object/ObjectConstructorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_expression_negative.bal
Labels: Team/CompilerFE

#35924 Spec conformance test runner
  .github/workflows/daily_spec_conformance_test_runner.yml
Labels: Team/CompilerFE

#35943 Allow skipping tests with certain labels in spec conformance test runner
  tests/ballerina-spec-conformance-tests/src/test/java/org/ballerinalang/test/TestRunner.java
  tests/ballerina-spec-conformance-tests/src/test/java/org/ballerinalang/test/TestRunnerUtils.java
Labels: Team/CompilerFE

#35861 Restrict using included record parameter as rest parameter
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/declarations/FunctionParamsTest.java
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_26.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_27.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_28.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_assert_29.json
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_26.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_27.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_28.bal
  compiler/ballerina-parser/src/test/resources/declarations/func-definition/func_params_source_29.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Team/CompilerFE

#35210 Fix optional field access in referenced lax type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config29.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config63.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config64.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/typereftype/TypeReferenceTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/type_reference.bal
Labels: Team/CompilerFE

#35986 Fix positional arg context type resolving logic
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
Labels: Team/LanguageServer
