Repository ballerina-platform/ballerina-lang, pull requests merged in 2022-10, with the labels that each got.

#38005 [2201.1.x] Fix unhandled exception in match statement when there is a type guard
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal
Labels: Team/CompilerFE

#38015 Change jvm max heap size for jballerina unit tests
  tests/jballerina-unit-test/build.gradle
Labels: Team/jBallerina

#37648 [2201.2.x] Fix suggesting completions with invalid prefix for already imported packages
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/module_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/module_ctx_source5.bal
Labels: Team/LanguageServer, Area/Completion

#38010 Avoid providing refactor extract code actions for the service uri in client declaration
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToLocalVarCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToConstantTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToFunctionCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToLocalVarTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-constant/config/extractServiceUriInClientDeclarationToConstant.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-constant/config/extractServiceUriInModuleClientDeclToConstant.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-constant/source/extractToConstantClientDeclarationsNegative.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config/neg_extract_to_function_exprs_pos_service_uri_in_client_declaration.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config/neg_extract_to_function_exprs_pos_service_uri_in_module_client_declaration.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/source/neg_extract_to_function_exprs_pos_service_uri_in_client_declaration.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/source/neg_extract_to_function_exprs_pos_service_uri_in_module_client_declaration.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config/extractToVariableInClientDeclNegative.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config/extractToVariableInModuleClientDeclNegative.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/source/extractToVariableInClientDecl.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/source/extractToVariableInXmlnsDecl.bal
Labels: Team/LanguageServer

#38006 [2201.2.x] Fix unhandled exception in match statement when there is a type guard
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal
Labels: Team/CompilerFE

#38007 [Master] Fix unhandled exception in match statement when there is a type guard
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal
Labels: Team/CompilerFE

#38051 [2201.3.0-stage] Update pos of resource path segments
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/ClientResourceAccessActionNegativeTest.java
Labels: Team/CompilerFE

#38050 [2201.2.x] Update pos of resource path segments
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/ClientResourceAccessActionNegativeTest.java
Labels: Team/CompilerFE

#38081 Change using `*` in the resource method name to `^`
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaResourceMethodSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/resourcepath/BallerinaPathSegmentList.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BResourceFunction.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ServiceSemanticAPITest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ServiceClassTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/klass/simple_service_class.bal
Labels: Team/CompilerFE

#38061 Fix handling invalid insertions in regular expressions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/RegExpAtomQuantifier.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ParameterDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/regexp/RegExpConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/regexp/RegExpValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_test.bal
Labels: Team/CompilerFE

#38059 Fix NPE for strand metadata at `dumpState` method
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
Labels: Team/jBallerina

#38101 Fix CCE when a type reference is used for stream types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Team/CompilerFE

#38125 Fix test runner for unspecified Labels header or typo in Labels header
  tests/ballerina-spec-conformance-tests/src/test/java/org/ballerinalang/test/TestRunnerUtils.java
Labels: Team/CompilerFE

#38122 Disallow accessing remote methods using field access
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal
Labels: Team/CompilerFE

#38123 [master] Fix NPE for strand metadata at `dumpState` method
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
Labels: Team/jBallerina

#38106 [2201.2.x] Fix NPE for strand metadata at `dumpState` method
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
Labels: Team/jBallerina

#38000 [2201.2.x] Fix setting record type flags from cached BIR
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/PublicAndPrivateTypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/public_and_private_types_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/module_public_and_private_types.bal
Labels: Team/jBallerina

#37768 [2201.1.x] Fix NPE at `BError` constructor
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ErrorCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BError.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Constants.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/StaticMethodTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
Labels: Team/jBallerina

#37839 Fix interop functions returning `decimal` values
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal
Labels: Team/jBallerina

#38084 Introduce loadProject API to the workspace manager using a file path [Master]
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSContextOperation.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/TestWorkspaceManager.java
Labels: Team/LanguageServer

#38164 Introduce loadProject API to the workspace manager using a file path [2201.3.0-stage]
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSContextOperation.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/TestWorkspaceManager.java
Labels: Team/LanguageServer

#38133 Migrate Axiom dependency version to `1.4.0`
  bvm/ballerina-runtime/build.gradle
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlComment.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlPi.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  bvm/ballerina-runtime/src/main/java/module-info.java
  distribution/zip/jballerina-tools/LICENSE
  distribution/zip/jballerina/LICENSE
  gradle.properties
  tests/ballerina-test-utils/build.gradle
  tests/jballerina-unit-test/build.gradle
Labels: Team/jBallerina

#38168 [2201.3.0-stage] Migrate Axiom dependency version to 1.4.0
  bvm/ballerina-runtime/build.gradle
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlComment.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlPi.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  bvm/ballerina-runtime/src/main/java/module-info.java
  distribution/zip/jballerina-tools/LICENSE
  distribution/zip/jballerina/LICENSE
  gradle.properties
  tests/ballerina-test-utils/build.gradle
  tests/jballerina-unit-test/build.gradle
Labels: Team/jBallerina

#37833 [Master] Add test to NPE when tuple matched with rest pattern
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtListMatchPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/list-match-pattern.bal
Labels: Team/CompilerFE

#37908 [Master] Set member type of empty tuple to never type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachTupleTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach_tuples.bal
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/tuple_with_no_member_test_negative.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_empty_tuple_negative.bal
Labels: Team/CompilerFE

#38141 [2201.3.0-stage] Fix reference type check for object and table
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmValueCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/DeclarativeAuthDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/typereftype/TypeReferenceTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/type_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/typeref_negative.bal
Labels: Team/CompilerFE

#38173 Sync parameter names and function types with spec
  langlib/lang.regexp/src/main/ballerina/regexp.bal
  langlib/lang.string/src/main/ballerina/string.bal
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config33.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config43.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config53.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config13.json
Labels: Team/CompilerFE

#38143 Add a test for readonly propagation to type from readonly field with code modifiers
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/1_annot.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/2_main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/3_types.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/immutable_type_definition_with_code_modifier_test/usage/main.bal
Labels: Team/CompilerFE

#37986 Fix worker only scenario in performance forecaster
  misc/ls-extensions/modules/performance-analyzer-services/src/main/java/io/ballerina/EndpointsFinder.java
  misc/ls-extensions/modules/performance-analyzer-services/src/main/java/io/ballerina/PerformanceAnalyzerNodeVisitor.java
  misc/ls-extensions/modules/performance-analyzer-services/src/main/java/io/ballerina/PerformanceAnalyzerService.java
  misc/ls-extensions/modules/performance-analyzer-services/src/test/java/io/ballerina/PerformanceAnalyzerTest.java
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/ballerina/worker/workerOnly.bal
  misc/ls-extensions/modules/performance-analyzer-services/src/test/resources/result/workerOnly.json
Labels: Team/VSCode

#37719 Remove superfluous `flagSet` attribute
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangObjectTypeNode.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedesc_test.bal
Labels: Team/CompilerFETools, Team/CompilerFE, Area/SemanticAPI, Lang/Object

#38138 [Master] Fix typeOf() giving incorrect typeSymbol for basic literal type
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfRegressionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/regression-tests/typeof_listener_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#38158 [2201.3.x] Fix typeOf() giving incorrect typeSymbol for basic literal type
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfRegressionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/regression-tests/typeof_listener_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#37838 [2201.2.x] Fix typeOf() giving incorrect typeSymbol for basic literal type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfRegressionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/regression-tests/typeof_listener_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#38160 Fix CCE in Extract to Function Code Action [2201.2.x]
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java
Labels: Team/LanguageServer

#38127 [Master] Fix CCE when a type reference is used for stream types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/stream/BStreamValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal
Labels: Team/CompilerFE

#38189 [Master] Fix reference type check for object and table
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmValueCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/DeclarativeAuthDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/typereftype/TypeReferenceTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/type_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/typeref_negative.bal
Labels: Team/CompilerFE

#38142 [2201.2.x] Log error for table-ctr assignment to non table type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/TableCtrAssignmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/AssignStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/SelectivelyImmutableTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/table_ctr_assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-query-construct-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal
Labels: Team/CompilerFE

#38195 Fix unused prefix analysis for client declarations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BClientDeclarationSymbol.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/IDLClientCompilerTests.java
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetesttwo/unused_prefix.bal
Labels: Team/CompilerFE

#38197 [Master] Fix unused prefix analysis for client declarations and add tests for underscore as prefix
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BClientDeclarationSymbol.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/IDLClientCompilerTests.java
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetesttwo/unused_prefix.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/module/declarations/ClientDeclarationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/clientdeclstmt/ClientDeclarationStatementTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/module.declarations/client-decl/client_decl_underscore_as_prefix_negative_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/clientdeclstmt/client_decl_stmt_underscore_as_prefix_negative_test.bal
Labels: Team/CompilerFE

#38193 Fix failing module part completion test by adding a wait [2201.3.0-stage]
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ModuleClientDeclarationContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/module_client_declaration_context/config/module_client_declaration_client_keyword.json
Labels: Team/LanguageServer

#38191 Fix failing module part completion test by adding a wait [master]
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ModuleClientDeclarationContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/module_client_declaration_context/config/module_client_declaration_client_keyword.json
Labels: Team/LanguageServer

#38190 Fix NoClassDefFound error and mention lang.regexp as experimental
  langlib/lang.regexp/src/main/ballerina/Ballerina.toml
  langlib/lang.regexp/src/main/ballerina/Module.md
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/RegexUtil.java
Labels: Team/CompilerFE

#38008 Fix interop `FieldGet` & `FieldSet` methods with default parameters
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/JavaFieldAccessMutate.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/FieldAccessMutateTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/field_access_mutate_tests.bal
Labels: Team/jBallerina

#38218 [Master] Fix access to semantic model when compilation is incomplete
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/ExecutorPositionsUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Team/LanguageServer

#38198 [Master] Fix "pattern will not be matched" in match statement when iterating over characters of string in foreach loop."
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-xml-typed-binding-patterns.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/dostatement/DoStmtsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/fail/FailStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementStaticPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns_negative.bal
Labels: Team/CompilerFE

#37334 [2201.2.x] Fix "pattern will not be matched" in match statement when iterating over characters of string in foreach loop."
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-xml-typed-binding-patterns.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/dostatement/DoStmtsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/fail/FailStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementStaticPatternsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtConstPatternTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/static_match_patterns_negative.bal
Labels: Team/CompilerFE

#37927 [Master] Fix stackoverflow when iterating an empty table
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config18.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config17.json
  language-server/modules/langserver-core/src/test/resources/semantictokens/config/project/main.bal
  language-server/modules/langserver-core/src/test/resources/semantictokens/config/project/modules/module1/model.bal
  language-server/modules/langserver-core/src/test/resources/semantictokens/config/single-file/check.bal
  language-server/modules/langserver-core/src/test/resources/semantictokens/config/single-file/main.bal
Labels: Team/CompilerFE

#38236 [2201.3.x] Fix access to semantic model when compilation is incomplete
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/ExecutorPositionsUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Team/LanguageServer

#38216 [Master]Fix no class def found error with lang.regex
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/RegexUtil.java
Labels: Team/CompilerFE

#38251 [2201.3.0-stage] Simplify the return type descriptor for verbose module IDs in refactor extract code actions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToLocalVarCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToFunctionCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToLocalVarTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config/extract_to_function_exprs_mapping_constructor_imported_module.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/source/extract_to_function_exprs_mapping_constructor_imported_module.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config/extractToVariableInMappingConstructor4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/source/extractToVariableInMappingConstructor2.bal
Labels: Team/LanguageServer

#38196 [Master]Sync lang.regexp parameter names and function mods with spec
  langlib/lang.regexp/src/main/ballerina/regexp.bal
  langlib/lang.string/src/main/ballerina/string.bal
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config26.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config33.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config43.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config53.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config13.json
Labels: Team/CompilerFE

#38272 [2201.3.0-stage] Refactor workspace service to gracefully access documents of generated folder with didOpen event
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
Labels: Team/LanguageServer

#38264 Update LS docs index page with subsections
  docs/language-server/README.md
Labels: Team/LanguageServer

#38230 Update LS simulator workflow
  .github/workflows/language_server_simulator.yml
Labels: Team/LanguageServer

#38043 [master] Fix missing quote in completion item for keywords in annotation completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/AnnotationUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/AnnotationContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/anonFuncExprAnnotation6.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/source/anonFuncExprAnnotation6.bal
Labels: Team/LanguageServer

#38086 Improve annotation access expression completions for records and objects
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AnnotationAccessExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/annotation_access_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/annotation_access_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/annotation_access_ctx_source7.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/annotation_access_ctx_source8.bal
Labels: Team/LanguageServer

#38337 [2201.3.0] Fix freeze exception thrown for `RegExpValue`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/RegExpValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/regexp/RegExpValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_test.bal
Labels: Team/jBallerina

#38335 [master] Fix freeze exception thrown for `RegExpValue`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/RegExpValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/regexp/RegExpValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_test.bal
Labels: Team/jBallerina

#38057 Add validation for decimal values at runtime
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/constants/RuntimeConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/cli/OperandTest.java
  langlib/langlib-test/src/test/resources/test-src/decimallib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_value.bal
Labels: Team/jBallerina

#38385 [2201.3.x] Fix NPE in SymbolFinder and ReferenceFinder in worker-flush expression when worker is missing
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInWorkersTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/symbol_lookup_with_workers_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#38386 [master] Fix NPE in SymbolFinder and ReferenceFinder in worker-flush expression when worker is missing
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInWorkersTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/symbol_lookup_with_workers_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#36837 [2201.2.x] Fix NPE in SymbolFinder and ReferenceFinder in worker-flush expression when worker is missing
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInWorkersTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/symbol_lookup_with_workers_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#37659 Optimize BIR by reusing temporary variables created for observability instrumentation
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIConstructorCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIMethodCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodCallInstruction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JTermKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JavaMethodCall.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/checked_expr_method_too_large.bal
Labels: Team/jBallerina

#38342 [2201.3.x] Fix missing quote in completion item for keywords in annotation completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/AnnotationUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/AnnotationContextTest.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/anonFuncExprAnnotation6.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/source/anonFuncExprAnnotation6.bal
Labels: Team/LanguageServer

#38281 [2201.3.x] Fix LS packageloader not picking up pulled modules
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/PullModuleExecutor.java
Labels: Team/LanguageServer

#38280 [master] Fix LS packageloader not picking up pulled modules
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/PullModuleExecutor.java
Labels: Team/LanguageServer

#38410 Fix "NPE in 2201.3.0 SNAPSHOT when building nballerina"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ParameterDesugar.java
Labels: Team/CompilerFE

#38398 [master] Avoid logging cancellation exps code actions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
Labels: Team/LanguageServer

#38399 [2201.3.x] Avoid logging cancellation exps code actions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionRouter.java
Labels: Team/LanguageServer

#38249 [master] Handle var-decl initializer not present case in `ConvertToQueryExpressionCodeAction`
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ConvertToQueryExpressionCodeAction.java
Labels: Team/LanguageServer

#38411 Fix "NPE in 2201.3.0 SNAPSHOT when building nballerina"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ParameterDesugar.java
Labels: Team/CompilerFE

#38003 [2201.2.x] Add fill record fields code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionContextTypeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/FillRecordFieldsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/NameUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/TypeResolverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingMatchPatternNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/FillRecordFieldsCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config10.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config11.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config12.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config9.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source4.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source5.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source6.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source7.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source8.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source9.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_binary_operation8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config29.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config59.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config60.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config62.json
Labels: Team/LanguageServer

#38394 [2201.2.x] Add expression bodied function snippet completion item
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionDefinitionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModulePartNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModuleVariableDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ModulePartNodeContextUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/Snippet.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SnippetGenerator.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_decl/config/config21.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config22.json
  language-server/modules/langserver-core/src/test/resources/completion/enum_decl_ctx/config/config5.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config13.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config2.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config6.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config11.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config12.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config17.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config18.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config7.json
Labels: Team/LanguageServer

#38244 [master] Add fill record fields code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionContextTypeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/FillRecordFieldsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/NameUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/TypeResolverUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingMatchPatternNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/FillRecordFieldsCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config10.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config11.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config12.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config9.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source4.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source5.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source6.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source7.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source8.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source9.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_binary_operation8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config29.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config59.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config60.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config62.json
Labels: Team/LanguageServer

#38285 [master] Improve type cast code action to consider union of numeric types
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeCastTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_assignment1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_conditional_expr1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_conditional_expr2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_conditional_expr3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_numeric1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/type_cast_in_assignment1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/type_cast_in_conditional_expr.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/type_cast_numeric.bal
Labels: Team/LanguageServer

#38419 [2201.2.x] Fix NPE for field access expression on record json field
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/mapInits
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
Labels: Team/CompilerFE

#38424 [master] Fix typeOf() giving incorrect typeSymbol for basic literal type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfRegressionTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#38439 Log error for when a module generated for a client declaration is imported and fix analysis for usage of unquoted client keyword
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/IDLClientCompilerTests.java
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestfive/Ballerina.toml
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestfive/main.bal
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestsix/Ballerina.toml
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestsix/main.bal
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestsix/modules/foo/foo.bal
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestsix/oth.bal
Labels: Team/CompilerFE

#38454 [Master] Log error for when a module generated for a client declaration is imported and fix analysis for usage of unquoted client keyword
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/IDLClientCompilerTests.java
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestfive/Ballerina.toml
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestfive/main.bal
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestsix/Ballerina.toml
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestsix/main.bal
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestsix/modules/foo/foo.bal
  project-api/project-api-test/src/test/resources/idl_client_compiler_tests/simpleclientnegativetestsix/oth.bal
Labels: Team/CompilerFE

#38425 [2201.3.0]Improve handling unmatched capture groups evaluating regexp expression
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Find.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Matches.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/RegexUtil.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Replace.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Team/CompilerFE

#38140 Improve Change Parameter Type Code Action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeParameterTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeParamTypeTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-param-type/config/changeParamTypeRestParam.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-param-type/config/changeParamTypeWithDefaultable.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-param-type/source/changeParamTypeRestParam.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-param-type/source/changeParamTypeWithDefaultable.bal
Labels: Team/LanguageServer

#38393 [master] Add expression bodied function snippet completion item
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionDefinitionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModulePartNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModuleVariableDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ModulePartNodeContextUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/Snippet.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SnippetGenerator.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_decl/config/config21.json
  language-server/modules/langserver-core/src/test/resources/completion/class_def/config/config22.json
  language-server/modules/langserver-core/src/test/resources/completion/enum_decl_ctx/config/config5.json
  language-server/modules/langserver-core/src/test/resources/completion/module_client_declaration_context/config/module_client_declaration_client_keyword.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config1.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config13.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config15_client_declaration.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config2.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config3.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config6.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_annotation_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_class_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_const_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_enum_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_funciton_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_import_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_listener_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_service_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_type_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_var_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_xmlns_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_annotation_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_class_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_const_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_enum_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_function_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_import_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_listener_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_service_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_type_defn_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_var_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_before_xmlns_decl_config.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config11.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config12.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config17.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config18.json
  language-server/modules/langserver-core/src/test/resources/completion/service_decl/config/config7.json
Labels: Team/LanguageServer
