Repository ballerina-platform/ballerina-lang, pull requests merged in 2022-01, with the labels that each got.

#34454 Disallow in query actions assignments to variables narrowed outside the loop
  .github/workflows/pull_request_ubuntu_build.yml
  .github/workflows/pull_request_windows_build.yml
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/narrowing/AssignmentToNarrowedVarsInLoopsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/narrowing/assignment_to_narrowed_vars_in_loops.bal
  tests/jballerina-unit-test/src/test/resources/test-src/narrowing/assignment_to_narrowed_vars_in_loops_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/unreachability_test.bal
Labels: Team/CompilerFE

#34445 Quick fix for local variable shadowing
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  docs/bir-spec/src/test/resources/test-src/types_and_operations.bal
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/tracing/MainFunctionTestCase.java
  tests/jballerina-integration-test/src/test/resources/observability/tracing_tests/01_main_function.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/IterableOperationsTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/object/ObjectConstructorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/ExprBodiedFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/variable/shadowing/ShadowingNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closure-semantic-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/dataflow-analysis-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/fps_hiding_block_scope_symbols.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable-with-variable-mutability.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/iterable-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_closures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_constructor_redeclared_symbols_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/expr_bodied_functions_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions-with-nil/functions_with_nil_basics.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_bir_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record_iteration.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_iteration.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/map/map-access-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/typeref_negative.bal
Labels: Team/CompilerFE

#34313 Fix few parsing issues
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/ConditionalExpressionTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/types/UnionTypeTest.java
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_31.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_32.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_33.json
  compiler/ballerina-parser/src/test/resources/expressions/conditional-expr/conditional_expr_assert_34.json
  compiler/ballerina-parser/src/test/resources/types/intersection-type/intersection_type_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/intersection-type/intersection_type_source_01.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_assert_01.json
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_assert_07.json
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_assert_08.json
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_01.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_07.bal
  compiler/ballerina-parser/src/test/resources/types/union-type/union_type_source_08.bal
Labels: Team/CompilerFE, Area/Parser

#34477 Log warnings when metadata is specified on more than one duplicate enum member
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticWarningCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/enums/EnumTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/enums/enum_metadata_test.bal
Labels: Team/CompilerFE

#34476 Update LS simulator to run on stage-swan-lake branch as well
  .github/workflows/language_server_simulator.yml
Labels: Team/LanguageServer

#34447 Fix create function code action issues
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SyntaxNodeToLocationMapper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/command/CreateFunctionCommandExecTest.java
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_if_statement5.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_var_decl1.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_var_decl2.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_var_decl3.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_var_decl4.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_while_statement1.json
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_if_statement5.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_var_decl1.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_var_decl2.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_var_decl3.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_var_decl4.bal
  language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_while_statement1.bal
Labels: Team/LanguageServer

#34505 Fix field access completions for the method call expression
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config34.json
Labels: Team/LanguageServer

#34500 Fix indexed expression completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config35.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config36.json
Labels: Team/LanguageServer

#34443 Refactor type cast code action and type test completion provider
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeTestExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeCastTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCast13.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/typeCast.bal
Labels: Team/LanguageServer

#34524 [Shell] Remove incorrect new lines related to multiple functions
  ballerina-shell/modules/shell-cli/build.gradle
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/ModuleMemberValidator.java
  ballerina-shell/modules/shell-cli/src/main/java/module-info.java
  ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/validator/ValidatorTest.java
Labels: Team/CompilerFETools, Area/Shell

#34484 Make Closure Vars Visible in Anonymous Functions
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/anon_func_expr_ctx_config8.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInExpressionsTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#34427 Address review suggestions in PR #34371
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type.bal
Labels: Team/CompilerFE

#34321 Fix create variable code action for `byte-array-literal`
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/ExpressionStatementTest.java
  compiler/ballerina-parser/src/test/resources/statements/expression-stmt/expression_stmt_assert_01.json
  compiler/ballerina-parser/src/test/resources/statements/expression-stmt/expression_stmt_source_01.bal
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction44.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction45.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariable8.bal
Labels: Team/CompilerFE, Area/Parser, Area/CodeAction

#34468 Fix overriding class symbol with type alias info
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/TypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/type_reference_type_bala_test_2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_type_reference_types_2/types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal
Labels: Team/CompilerFE

#34387 Fix query expression parsing inside other expressions
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QueryExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_assert_70.json
  compiler/ballerina-parser/src/test/resources/expressions/query-expr/query_expr_source_70.bal
Labels: Team/CompilerFE, Area/Parser

#34340 Address last suggestion in PR #33973
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/record-constraint-table-value.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table-negative.bal
Labels: Team/CompilerFE

#34510 Visit annotation attachments in invocation expression
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  language-server/modules/langserver-core/src/test/resources/semantictokens/expected/default-module_expected.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolAtCursorTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
Labels: Team/LanguageServer

#34527 Remove special case handling in Semantic API of keywords used in lang libs
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaClassSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaModule.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaServiceDeclarationSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/check_expression_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/xml_attribute_access_expr_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/xml_attribute_access_expr_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config1a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config28.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config2a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config34.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config38.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config39.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config3a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config40.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config41.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config50.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5a.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5b.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config5c.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_within_param_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config20.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config22.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config23.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config24.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config25.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/foreach_stmt_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/optional_field_access_ctx_config4.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundArrayFunctionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundMapFunctionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundStreamFunctionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundTableFunctionsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/langlib/TypeParamBoundXMLFunctionsTest.java
Labels: Team/CompilerFETools, Area/SemanticAPI

#34529 Update ls simulator workflow to not fail fast
  .github/workflows/language_server_simulator.yml
Labels: Team/LanguageServer

#34478 Improve recovery for field access expression at the statement level
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/AccessExpressionsTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/AssignmentStatementTest.java
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/field_access_expr_assert_08.json
  compiler/ballerina-parser/src/test/resources/expressions/access-expr/field_access_expr_source_08.bal
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_06.json
  compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_assert_11.json
  compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_assert_13.json
  compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_source_13.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config51.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source51.bal
Labels: Team/CompilerFE, Area/Parser

#34554 Update type narrowing to consider readonly difference - phase I
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_1.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_2.bal
Labels: Team/CompilerFE

#34550 Fix field access completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config52.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config53.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source52.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source53.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_source28.bal
Labels: Team/LanguageServer

#34543 Fix completion in union type descriptor context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ReturnTypeDescriptorNodeContext.java
Labels: Team/LanguageServer

#34558 Fix adding type cast at member access expression
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeCastTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCastInMemberAccess1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/typeCastInMemberAccess1.bal
Labels: Team/LanguageServer

#34449 Fix issue with associating symbols being type narrowed with envs
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInStatementsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/var_symbol_lookup_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/comment/CommentStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/narrowing_with_if_without_else_not_completed_normally_test.bal
Labels: Team/CompilerFE

#34567 Fix type narrowing with subtypes of `readonly`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_1.bal
Labels: Team/CompilerFE

#34584 Fix several issues with type narrowing
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_1.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_3.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_4.bal
Labels: Team/CompilerFE

#34502 Fix issue in tuple var def contains error BP
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition.bal
Labels: Team/CompilerFE, Area/Desugar

#34583 Add runtime-swanlake-update-fixes to build workflows
  .github/workflows/pull_request_ubuntu_build.yml
  .github/workflows/pull_request_windows_build.yml
Labels: Team/jBallerina

#34594 Fix "undefined symbol" error for captured variable after an if check
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/basic-worker-actions.bal
Labels: Team/CompilerFE

#34574 [Port]Fix issue with associating symbols being type narrowed with envs
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/visiblesymbols/VisibleSymbolsInStatementsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/visiblesymbols/var_symbol_lookup_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/comment/CommentStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/narrowing_with_if_without_else_not_completed_normally_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/basic-worker-actions.bal
Labels: Team/CompilerFE

#34616 Check for referred expected type while resolving binary expression type
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ServiceDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConditionResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/MainFunctionValidator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/Symbols.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/TypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal
Labels: Team/CompilerFE

#34618 Stop setting the readonly flag for classes with immutable fields
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/FinalObjectFieldTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTypeReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/modules/selectively_immutable/constructs.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_selectively_immutable/constructs.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/final_object_fields.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/final_object_fields_semantics_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_inclusion_with_qualifiers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_inclusion_with_qualifiers_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_5.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_6.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type_negative.bal
Labels: Team/CompilerFE

#34599 [Shell] FIx auto import feature failing on windows
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/ModuleImporter.java
Labels: Team/CompilerFETools, Area/Shell

#34429 Disallow compound assignments with nullable operands
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment_negative.bal
Labels: Team/CompilerFE, Area/Desugar

#33984 Add configurable support for union of singletons
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigResolver.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliConfigValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlConfigValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/Utils.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/TestUtils.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/CliConfigProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/CliProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/FiniteTypeConfig.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/FiniteNegative.toml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
Labels: Team/jBallerina

#33815 Fix `never` type rest field type checking
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never_type_runtime.bal
Labels: Team/jBallerina

#34302 Remove supporting `NaN` and `Infinity` for decimal values
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/DecimalValueKind.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueComparisonUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/NumericConversionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/numeric_conversion.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_value.bal
Labels: Team/jBallerina

#34251 Fix array conversion without filler values
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#34602 Fix the code-gen crash for value creation of not defined types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmErrorCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmObjectCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmRecordCreatorGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPITest.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/invalid_values/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/invalid_values/main.bal
Labels: Team/jBallerina

#34564 Revamp service template generator
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionModuleId.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/ImportsAcceptor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ServiceTemplateGenerator.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/projectVariableAssignmentRequiredCodeAction1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/projectVariableAssignmentRequiredCodeAction2.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/source/lsproject/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/source/lsproject/modules/module1/module1.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/source/lsproject/modules/module2/module2.bal
Labels: Team/LanguageServer

#34590 Fix few issues in annot processing in testerina TestProcessor
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java
  tests/testerina-integration-test/src/test/resources/single-file-tests/disabled-tests/disable-test.bal
Labels: Team/CompilerFE, Area/TestFramework

#34446 Disallow binding non-required detail fields in an error binding pattern
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_lookup_destructure_var_exclusion_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/ErrorVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModuleErrorVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ErrorVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/uninitialized_local_complex_variables.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/error_binding_pattern_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/error_variable_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/error_variable_reference_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/error_variable_reference_semantics_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/multiple-let-clauses.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/module_error_var_decl_negetive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/vardeclr/uninitialized_module_error_var_decl.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt_negative.bal
Labels: Team/CompilerFE

#34582 Fix issue in toString() for decimal zero
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
Labels: Team/CompilerFE

#34645 Fix CCE issue when checking the lang lib methods of XML sub types
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/langlib_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#34655 Fix several issues related to type narrowing
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/whilestatement/WhileStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/narrowing_with_if_without_else_not_completed_normally_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/reachability_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/whilestatement/while-stmt.bal
Labels: Team/CompilerFE

#34589 [Shell] Fix shell diagnostics not showing issue
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java
Labels: Team/CompilerFETools, Area/Shell

#34664 Fix several issues related to type narrowing
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/reachability/ReachabilityAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/whilestatement/WhileStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/narrowing_with_if_without_else_not_completed_normally_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/reachability-analysis/reachability_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/whilestatement/while-stmt.bal
Labels: Team/CompilerFE

#34578 Fix NPE in TypeHashVisitor when use null in union-type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/UnionTypeWithNullLiteralBalaTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/union_type_with_null_literal_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/union_type_with_null_literal_test_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test-union-type-with-null-literal/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test-union-type-with-null-literal/test_type.bal
Labels: Team/CompilerFE

#34638 [Shell] Update text outputs
  ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/handlers/HelpCommand.java
  ballerina-shell/modules/shell-cli/src/main/resources/command.help.txt
Labels: Team/CompilerFETools, Area/Shell

#34677 Add Semtype test runner
  settings.gradle
  tests/jballerina-semtype-test/build.gradle
  tests/jballerina-semtype-test/src/test/java/io/ballerina/test/SemTypeTest.java
  tests/jballerina-semtype-test/src/test/java/io/ballerina/test/utils/Constants.java
  tests/jballerina-semtype-test/src/test/resources/test-src/anydata1.bal
  tests/jballerina-semtype-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#34688 Fix narrowing when removing unions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_1.bal
Labels: Team/CompilerFE

#34699 Add semtype relations for anydata
  tests/jballerina-semtype-test/src/test/java/io/ballerina/test/SemTypeTest.java
  tests/jballerina-semtype-test/src/test/resources/test-src/anydata1-f.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/anydata2-f.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/anydata2.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/anydata3.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/anydata4.bal
Labels: Team/CompilerFE

#34709 Improve type narrowing
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_1.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/test_type_guard_sem_types_2.bal
Labels: Team/CompilerFE

#34136 Fix issues regarding cloneWithType() with int subtypes
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneUtils.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#34534 Enclose strings with "" in error messages
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BFiniteType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BFiniteType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java
  langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/enums/EnumTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantAccessNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finite/FiniteTypeNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/BasicTupleTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/typedesc/TypedescTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLTextToStringConversionNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/unsupported_intersection_negative.bal
Labels: Team/jBallerina

#34718 Fix Runtime crash when calling reduce function on keyless tables
  langlib/lang.table/src/main/java/org/ballerinalang/langlib/table/Reduce.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal
Labels: Team/CompilerFE

#34716 Fix table lookup doesn't check when there is only one candidate issue
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal
Labels: Team/CompilerFE

#34726 Add some disabled semtype tests
  tests/jballerina-semtype-test/src/test/resources/test-src/not1-d.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/proj2-d.bal
Labels: Team/CompilerFE

#34736 Add subtype relations for table
  tests/jballerina-semtype-test/src/test/resources/test-src/table1-d.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/table1-f.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/table1.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/table2.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/table3.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/table4.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/table5.bal
Labels: Team/CompilerFE

#34738 Add subtype realtions for table
  tests/jballerina-semtype-test/src/test/resources/test-src/table2-d.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/table2-f.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/table6.bal
Labels: Team/CompilerFE

#34739 Add more semtype tests
  tests/jballerina-semtype-test/src/test/resources/test-src/bdddiff1.bal
Labels: Team/CompilerFE

#34741 Add subtype relations for tuple
  tests/jballerina-semtype-test/src/test/resources/test-src/tuple-d.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/tuple1.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/tuple2.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/tuple3.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/tuple4.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/tuple5.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/tuple6.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/tuple7.bal
Labels: Team/CompilerFE

#34742 Update the spec version to 2022R1
  gradle.properties
Labels: Team/CompilerFE

#34754 Fix OCE annotation desugar issue
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/object/ObjectConstructorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/object/object_closures_annotations.bal
Labels: Team/CompilerFE

#34755 Handle decimal toString output when value input is zero
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
Labels: Team/CompilerFE

#34761 Add semtype relations for xml
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-complex-ro1-d.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-complex-ro2-d.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-complex-ro3-d.bal
Labels: Team/CompilerFE

#34764 Fix NPE when defining a type definition for an intersection type with a builtin type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/SelectivelyImmutableTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type_negative.bal
Labels: Team/CompilerFE

#34768 Add semtype xml error
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-error1-d.bal
Labels: Team/CompilerFE

#34777 [Shell] Fix incorrect error messages related to imports
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/GetErrorMessageTrial.java
Labels: Team/CompilerFETools, Area/Shell

#34778 Add subtype test for xml with readonly bit
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-readonly1-d.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-readonly1.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-readonly2.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-readonly3.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-readonly4.bal
Labels: Team/CompilerFE

#34780 Add subtype relations for xml-sequence
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-sequence1.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-sequence2.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-sequence3.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-sequence4.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-sequence5.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-sequence6.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-sequence7.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-sequence8.bal
Labels: Team/CompilerFE

#34759 Add semtype relations for xml
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-complex-rw1-d.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-complex-rw1-f.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-complex-rw1.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-complex-rw2.bal
Labels: Team/CompilerFE

#34795 Add subtype relations for xml-never
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-never1.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-never2.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-never3.bal
  tests/jballerina-semtype-test/src/test/resources/test-src/xml-never4.bal
Labels: Team/CompilerFE

#34791 Ignore package symbols that are not imported to the current file
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  language-server/modules/langserver-core/src/test/resources/completion/enum_decl_ctx/config/config3.json
Labels: Team/CompilerFETools, Area/SemanticAPI

#34666 Split up error binding pattern and destructuring mixed test case
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorDestructureNegetiveTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/ErrorVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/error/error_destructure_field_binding_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/error_binding_pattern_negative.bal
Labels: Team/CompilerFE

#34658 Add runtime async API object method call tests
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Async.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/async/main.bal
Labels: Team/jBallerina

#34131 Fix local variable visibility in debugger view
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangBlockStmt.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java
  tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/variable-tests/main.bal
Labels: Team/jBallerina

#34837 Fix incorrectly referring to types across modules
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
Labels: Team/CompilerFE

#34547 Fix cloneWithType issues on ambiguity
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneUtils.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneWithType.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonWithType.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromJson_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/StampInbuiltFunctionNegativeTest.java
Labels: Team/jBallerina

#34843 Backport fix overriding class symbol with type alias info #34468
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/TypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/type_reference_type_bala_test_2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_type_reference_types_2/types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal
Labels: Team/CompilerFE

#34877 Clear retaining Env in ReachabilityAnalyzer
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java
Labels: Team/CompilerFE

#34888 Fix lang-lib warnings
  langlib/jballerina.java/src/main/ballerina/ballerina_values_to_Java.bal
  langlib/lang.boolean/src/main/ballerina/boolean.bal
  langlib/lang.decimal/src/main/ballerina/decimal.bal
  langlib/lang.float/src/main/ballerina/float.bal
  langlib/lang.int/src/main/ballerina/int.bal
  langlib/lang.map/src/main/ballerina/map.bal
  langlib/lang.stream/src/main/ballerina/stream.bal
  langlib/lang.table/src/main/ballerina/table.bal
  langlib/lang.transaction/src/main/ballerina/transaction.bal
  langlib/lang.value/src/main/ballerina/value.bal
  langlib/lang.xml/src/main/ballerina/xml.bal
Labels: Team/CompilerFE

#34690 Add result information into error log of `waitTest17`
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAllActionsTest.java
Labels: Team/jBallerina
