Repository ballerina-platform/ballerina-lang, pull requests merged in 2022-12, with the labels that each got.

#38765 Support defining distinct error types inside functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmErrorTypeConstantsGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
Labels: Team/jBallerina

#38942 [master] Update LS simulator to use main branch of nBallerina
  .github/workflows/language_server_simulator.yml
  tests/language-server-simulator/build.gradle
Labels: Team/LanguageServer

#38697 Fix table with multiple keys with recursive type-reference type
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/cli/Option.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmArrayTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmRefTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmTupleTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmUnionTypeConstantsGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/TypeReference.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/types/modules/typeref/typeAPIs.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/types/modules/typeref/typeref.bal
Labels: Team/jBallerina

#38770 Add support typedesc for tuples at runtime
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TypedescValueImpl.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/InstructionEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/ProgramFileConstants.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/failLockWithinLock
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/mapInits
Labels: Team/jBallerina

#38340 Enable intermittently failed dynamic listener test
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/ModuleExecutionFlowTests.java
  tests/jballerina-integration-test/src/test/resources/packaging/dynamic_listener_async_call_test_project/main.bal
Labels: Team/jBallerina

#38785 Fix encoding global variables in imported modules
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableArguments.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/testPackage/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/functions/testPackage/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/functions/testPackage/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/testPackage/modules/testModule/testModule.bal
Labels: Team/jBallerina

#38830 Fix incorrect results with type-test of type-reference errors
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeTestGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typechecker/ErrorOptimizationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typechecker/error_optimizations.bal
Labels: Team/jBallerina

#39028 Update FieldAccessCompletionResolver simple name ref type finding logic
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
Labels: Team/LanguageServer

#38965 [2201.3.x] Add missing resource access action path segment completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source18.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source19.bal
Labels: Team/LanguageServer

#39031 [2201.3.x] Fix NPE in ArrayTypeSymbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaArrayTypeSymbol.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction46.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithMethodCall1.bal
Labels: Team/LanguageServer, Area/SemanticAPI

#38849 Fix warning and remove target jar from native
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CreateExecutableTask.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
Labels: Stale

#39032 [master] Fix NPE in ArrayTypeSymbol
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaArrayTypeSymbol.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction46.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithMethodCall1.bal
Labels: Team/LanguageServer, Area/SemanticAPI

#39058 [2201.3.x] Fix change variable type code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeVariableTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarType5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarType2.bal
Labels: Team/LanguageServer

#39046 [2201.3.x] Add missing order direction keywords in order by context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/QueryPipelineNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_orderby_clause_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_orderby_clause_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_orderby_clause_source10.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_orderby_clause_source11.bal
Labels: Team/LanguageServer

#38975 Fix extract to function code action and CCE in create type code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToFunctionCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-type/config/create_type_in_record_type.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-type/source/create_type_in_record_type.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config/extract_to_function_stmts_foreach_stmt2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/source/extract_to_function_stmts_foreach_stmt2.bal
Labels: Team/LanguageServer

#39064 [2201.3.x] Fix extract to function code action and CCE in create type code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToFunctionCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-type/config/create_type_in_record_type.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-type/source/create_type_in_record_type.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config/extract_to_function_stmts_foreach_stmt2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/source/extract_to_function_stmts_foreach_stmt2.bal
Labels: Team/LanguageServer

#39044 [master] Add missing order direction keywords in order by context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/QueryPipelineNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_orderby_clause_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_orderby_clause_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_orderby_clause_source10.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_orderby_clause_source11.bal
Labels: Team/LanguageServer

#39074 [2201.3.x] Add examples for the error langlib
  langlib/lang.error/src/main/ballerina/error.bal
Labels: Team/CompilerFE

#38954 Change generated frame class names
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/CodeCoverageUtils.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/CodeCoverageReportTest.java
Labels: Team/jBallerina

#38956 Remove unused classes
  compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/parser/LockFileProcessor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BinaryFileWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/ByteArrayBasedCompiledPackageEntry.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/DependencyTree.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/InMemoryCompiledPackage.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/LockFileConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/LockFileWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/PathBasedCompiledPackageEntry.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/TypeCreator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/TypeSignatureReader.java
Labels: Team/jBallerina

#38426 [master] Sync lang.regexp module with spec and handle unmatched capture groups
  langlib/lang.regexp/src/main/ballerina/regexp.bal
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Find.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Matches.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/RegexUtil.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Replace.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Split.java
  langlib/lang.string/src/main/ballerina/string.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibStringTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
  langlib/langlib-test/src/test/resources/test-src/stringlib_test.bal
Labels: Team/CompilerFE

#39102 [master] Add examples for the error langlib
  langlib/lang.error/src/main/ballerina/error.bal
Labels: Team/CompilerFE

#39073 [2201.3.x] Add examples for the array langlib
  langlib/lang.array/src/main/ballerina/array.bal
  language-server/modules/langserver-core/src/test/resources/definition/expected/stdlib/inter_stdlib_config1.json
  language-server/modules/langserver-core/src/test/resources/references/expected/ref_within_stdlib_config1.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
Labels: Team/CompilerFE

#39075 [2201.3.x] Add examples for the future and function langlibs
  langlib/lang.function/src/main/ballerina/function.bal
  langlib/lang.future/src/main/ballerina/future.bal
Labels: Team/CompilerFE

#38357 [master] Add missing completions in conditional expressions and Fix extract to function code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToFunctionCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config/extract_to_function_exprs_conditional_expr.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/source/extract_to_function_exprs_conditional_expr.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config54.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source54.bal
Labels: Team/LanguageServer

#39103 [master] Add examples for the array langlib
  langlib/lang.array/src/main/ballerina/array.bal
  language-server/modules/langserver-core/src/test/resources/definition/expected/stdlib/inter_stdlib_config1.json
  language-server/modules/langserver-core/src/test/resources/references/expected/ref_within_stdlib_config1.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
Labels: Team/CompilerFE

#39110 [master] Add examples for the future and function langlibs
  langlib/lang.function/src/main/ballerina/function.bal
  langlib/lang.future/src/main/ballerina/future.bal
Labels: Team/CompilerFE

#39117 [2201.3.x] Add missing completions in conditional expressions and Fix extract to function code action #
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToFunctionCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config/extract_to_function_exprs_conditional_expr.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/source/extract_to_function_exprs_conditional_expr.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config54.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source54.bal
Labels: Team/LanguageServer

#39119 [2201.3.x] Restrict providing type cast code action that provided for Constants and Enums causing runtime errors
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeCastTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/typeCastNegative6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/source/type_casts_in_constants.bal
Labels: Team/LanguageServer

#38947 [master] Improve record field completions in named args
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_in_named_arg.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/new_expr_ctx_config24.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_in_named_arg.bal
Labels: Team/LanguageServer

#38946 [2201.3.x] Add missing completion items for record fields
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_in_named_arg.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/new_expr_ctx_config24.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_in_named_arg.bal
Labels: Team/LanguageServer

#39007 [master] Fix change variable type code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeVariableTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarType5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarType2.bal
Labels: Team/LanguageServer

#38870 [Master] Add lang library examples for boolean langlib apidocs
  langlib/lang.boolean/src/main/ballerina/boolean.bal
Labels: Team/CompilerFE

#39109 [2201.3.x] Add examples for `lang.int` langlib functions
  langlib/lang.int/src/main/ballerina/int.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachErrorHandlingTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_field_initializer_with_check.bal
Labels: Team/CompilerFE, Lang/LangLib

#39124 [2201.3.x] Add examples for `lang.runtime` langlib functions
  langlib/lang.runtime/src/main/ballerina/runtime.bal
  langlib/langlib-test/src/test/resources/test-src/runtimelib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/nativeimpl/functions/RuntimeTest.java
Labels: Team/CompilerFE, Lang/LangLib

#39091 [2201.3.x] Add langlib examples for decimal
  langlib/lang.decimal/src/main/ballerina/decimal.bal
Labels: Team/CompilerFE

#38917 [Master] Add examples for `lang.int` langlib functions
  langlib/lang.int/src/main/ballerina/int.bal
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachErrorHandlingTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_field_initializer_with_check.bal
Labels: Team/CompilerFE, Lang/LangLib
