Repository ballerina-platform/ballerina-lang, pull requests merged in 2023-03, with the labels that each got.

#39583 [2201.4.x] Fix regular expressions not working with table keys and query expressions/actions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TableUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/RegExpValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/SimpleQueryExpressionWithDefinedTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableKeyFieldValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_key_field_value_test.bal
Labels: Team/CompilerFE

#39718 Fix issue with using mapping binding with a single variable name field in a destructuring assignment
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/DestructuringAssignmentStatementTest.java
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/mapping_binding_pattern_assert_02.json
  compiler/ballerina-parser/src/test/resources/statements/destructuring-assignment/mapping_binding_pattern_source_02.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/RecordVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal
Labels: Team/CompilerFE

#39734 [2201.4.x] Fix issue with resolving closures in langlib calls with arrow expressions in query expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/InnerQueryTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/SimpleQueryExpressionWithDefinedTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/inner-queries.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal
Labels: Team/CompilerFE

#39466 Correct Node location of `regExpTemplateLiteral.reDisjunction`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expressions_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#39691 Add compilation error when ignoring the error cause using `_` in error binding pattern
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/ErrorVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/error_binding_pattern_negative.bal
Labels: Team/CompilerFE

#39517 Fix compiler crash in regex with back-tick
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/utils/ConditionalExprResolver.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/RegExpConstructorExprTest.java
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_44.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_assert_45.json
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal
  compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_45.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/regexp/RegExpValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_negative_test.bal
Labels: Team/CompilerFE, Lang/Regexp

#39719 Port fix to master from #37812
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmObjectCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmRecordCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
Labels: Team/CompilerFE

#39722 Port fix to 2201.3.x from #37812
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmObjectCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmRecordCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
Labels: Team/CompilerFE

#39726 Port to 2201.4.x from fix for #37812
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmObjectCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmRecordCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
Labels: Team/CompilerFE

#38725 Fix remove re-declared import code action is not suggested for modules in the current package
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/RemoveImportCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/RemoveImportCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-import/config/remove_redeclared_import_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-import/config/remove_redeclared_import_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-import/source/remove_redeclared_import_source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-import/source/testproject/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-import/source/testproject/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/remove-import/source/testproject/modules/module1/module1.bal
Labels: Team/LanguageServer

#39808 Fix inferring isolated for infer-anonymous-function-expr when there's type narrowing for a parameter
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationInferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference_isolation_analysis_negative.bal
Labels: Team/CompilerFE

#39720 Update service class check in NodeFinder
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ClassSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/class_symbols_test.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#39350 Add quick pick for infer sub expressions in extract to function and extract to local variable code actions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/ExpressionNodeValidator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToLocalVarCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/IsolatedBlockResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AbstractCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToFunctionCodeActionWithPositionalRenameAndQuickPickTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToFunctionCodeActionWithQuickPickTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToLocalVarCodeActionWithPositionalRenameAndQuickPickTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToLocalVarCodeActionWithQuickPickTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-positional-rename-and-quickpick/extractToFunctionExpr1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-positional-rename-and-quickpick/extractToFunctionExpr2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-positional-rename-and-quickpick/extractToFunctionExpr3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-positional-rename-and-quickpick/extractToFunctionExpr4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-positional-rename-and-quickpick/extractToFunctionExpr5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-positional-rename-and-quickpick/extractToFunctionExpr6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-positional-rename-and-quickpick/extractToFunctionExpr7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-positional-rename-and-quickpick/extractToFunctionExpr8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-quick-pick-capability/extractToFunctionExpr1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-quick-pick-capability/extractToFunctionExpr2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-quick-pick-capability/extractToFunctionExpr3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-quick-pick-capability/extractToFunctionExpr4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-quick-pick-capability/extractToFunctionExpr5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-quick-pick-capability/extractToFunctionExpr6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-quick-pick-capability/extractToFunctionExpr7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config-quick-pick-capability/extractToFunctionExpr8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/source/extract_to_function_exprs_with_quickpick.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-positional-rename-and-quickpick/extractToLocalVarExpr1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-positional-rename-and-quickpick/extractToLocalVarExpr2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-positional-rename-and-quickpick/extractToLocalVarExpr3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-positional-rename-and-quickpick/extractToLocalVarExpr4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-positional-rename-and-quickpick/extractToLocalVarExpr5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-positional-rename-and-quickpick/extractToLocalVarExpr6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-positional-rename-and-quickpick/extractToLocalVarExpr7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-positional-rename-and-quickpick/negativeExtractToLocalVarExpr.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-quick-pick-capability/extractToLocalVarExpr1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-quick-pick-capability/extractToLocalVarExpr2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-quick-pick-capability/extractToLocalVarExpr3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-quick-pick-capability/extractToLocalVarExpr4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-quick-pick-capability/extractToLocalVarExpr5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-quick-pick-capability/extractToLocalVarExpr6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-quick-pick-capability/extractToLocalVarExpr7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config-quick-pick-capability/negativeExtractToLocalVarExpr.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config/extractToVariableInObjectField.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config/extractToVariableInvalidExpressionStatement.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/source/extractToLocalVariableExprsWithQuickPick.bal
Labels: Team/LanguageServer, Area/CodeAction

#39827 Support getting function name & path params details from environment API
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Environment.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
Labels: Team/jBallerina

#39782 Fix `TypeChecker.isSameType` method
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
Labels: Team/jBallerina

#39444 Improve Regexp validations with early returns and graceful handling of `PatternSyntaxException`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Find.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Matches.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/RegexUtil.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Type/Improvement, Team/CompilerFE, Lang/Regexp

#39613 Refactor `visitMaxs()` asm calls to handle errors
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmErrorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/ShutDownListenerGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/InitMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/LambdaGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ModuleStopMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmAnnotationsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmValueCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmArrayTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmBStringConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmBallerinaConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmConstantGenCommons.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmErrorTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmModuleConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmRefTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmTupleTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmUnionTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmErrorCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmObjectCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmRecordCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmObjectTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmRecordTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmTupleTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/values/JvmObjectGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/values/JvmRecordGen.java
Labels: Team/jBallerina

#39847 Revert "Consider on-fail as an execution branch when possible failure is reached"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/onfail/OnFailClauseTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause-negative-v2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/global_variable_init_with_onfail_negative.bal
Labels: Team/CompilerFE

#39843 Add tests for `Environment` runtime API
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Environment.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Environments.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPITest.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/environment/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/environment/main.bal
Labels: Team/jBallerina

#39509 Add code action support for regexp
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaRegexpTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeVariableTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateFunctionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableWithPositionalRenameSupportCapabilityTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/FillRecordFieldsCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/FixReturnTypeTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarType6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarType3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/create_function_in_var_decl5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/create_function_in_var_decl6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/create_function_in_var_decl5.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/create_function_in_var_decl6.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/variableAssignmentRequiredCodeAction46.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/variableAssignmentRequiredCodeAction47.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariable10.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config14.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config15.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config16.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source11.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source12.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source13.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/fixReturnType6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/fixReturnType7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/fixReturnType8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/source/fixReturnType2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/source/fixReturnType3.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/regexp/RegExpValueTest.java
Labels: Team/LanguageServer, Area/CodeAction, Lang/Regexp

#39855 Revert "Consider on-fail as an execution branch when possible failure is reached"
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/onfail/OnFailClauseTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause-negative-v2.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/global_variable_init_with_onfail_negative.bal
Labels: Team/CompilerFE

#39573 Fix inferred argument validation with type reference types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_for_resource_action_with_check2.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config5.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_client.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_performance.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typeref1.json
  language-server/modules/langserver-stdlib/src/main/ballerina/clients_source1.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/InferredDependentlyTypeFunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature_negative.bal
Labels: Team/CompilerFE

#39854 [persist-improvement] Bundle resource path parameters of external functions into anydata array
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIConstructorCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIMethodCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethod.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodRequest.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/ResourcePathArgumentsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/variable_number_of_resource_paths.bal
Labels: Team/jBallerina

#39707 Disable suggesting extract to function and local variable code actions in match clause
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToLocalVarCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToFunctionCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToLocalVarTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/config/negative_extract_to_function_exprs_match_clause.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-function/source/extract_to_function_exprs_match_clause.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config/extractToVariableInMatchClauseNegative.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/source/extractToVariableInMatchClause.bal
Labels: Team/LanguageServer

#39889 [persist-improvement] Refactor parameter type validation logic
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/ResourcePathArgumentsTest.java
Labels: Team/jBallerina

#39820 Fix incorrect behaviour in regex split langlib function
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Split.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Lang/Regexp

#39429 [master] Address review suggestions related to expectedType API
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java
Labels: Area/SemanticAPI

#39551 Fix adding empty char set atoms in Regexp TreeBuilder of `:fromString()` method
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Team/CompilerFE, Lang/Regexp

#38265 [Master] Add tests for field access on record json field
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
Labels: Team/CompilerFE

#39879 Add field access completions for template expressions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config62.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config63.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config64.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source62.bal
Labels: Team/LanguageServer, Lang/Regexp

#39848 Handle Compilation Errors & Runtime mappings for empty regexp
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Find.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Matches.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/RegexUtil.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_empty_test_negative.bal
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromBalString_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromJson_test.bal
Labels: Team/CompilerFE, Lang/Regexp

#39866 Fix incorrect behaviour in `regex:groups` for regexp langlib functions
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Find.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/RegexUtil.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Lang/Regexp

#39857 [Master] Fix visiting expressions in resource access action
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_with_action_or_expr.bal
Labels: Team/CompilerFE

#39838 Fix JSON access with check when the CET is a subtype of simple basic types and string
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExpressionOperatorTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/check_expr_with_json_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/check_expr_with_json_access_negative.bal
Labels: Team/CompilerFE

#39875 [master] Optimize typedesc creation for ballerina values
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BXml.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BXmlItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/XmlTreeBuilder.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/AbstractObjectValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/AttributeMapValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/FPValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/FutureValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/HandleValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/IteratorValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/RegExpValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/StreamValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TypedescValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlComment.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlPi.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlQName.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlValue.java
Labels: Team/jBallerina

#39898 Sync persistance_improvement branch with master
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Environment.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIConstructorCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIMethodCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethod.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodRequest.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Environments.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/ResourcePathArgumentsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPITest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/variable_number_of_resource_paths.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/environment/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/environment/main.bal
Labels: Team/jBallerina

#39840 Remove `version` keyword
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/LexerTerminals.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/IdentifierTest.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/SyntaxInfoAPITest.java
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_04.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_05.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_06.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_08.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_14.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_16.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_19.json
  compiler/ballerina-parser/src/test/resources/declarations/import-decl/import_decl_assert_21.json
  compiler/ballerina-parser/src/test/resources/misc/identifiers/version_as_identifier_assert_01.json
  compiler/ballerina-parser/src/test/resources/misc/identifiers/version_as_identifier_assert_02.json
  compiler/ballerina-parser/src/test/resources/misc/identifiers/version_as_identifier_assert_03.json
  compiler/ballerina-parser/src/test/resources/misc/identifiers/version_as_identifier_source_01.bal
  compiler/ballerina-parser/src/test/resources/misc/identifiers/version_as_identifier_source_02.bal
  compiler/ballerina-parser/src/test/resources/misc/identifiers/version_as_identifier_source_03.bal
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ItemResolverConstants.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/Snippet.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SnippetGenerator.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config10.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source7.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config29.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source29.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Team/CompilerFE, Area/Parser

#39878 Fix errors with non-capturing group runtime parsing
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeTraverser.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Lang/Regexp

#39906 Improve empty regexp compile-time error capturing
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_test.bal
Labels: Team/CompilerFE, Lang/Regexp

#39913 [2201.4.1-stage] Fix converting reference type values to `json`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#39212 Revamp `cloneWithType` and `fromJsonWithType`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/TypeCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/StringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/XmlUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BalStringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/JsonInternalUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/XmlFactory.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/commons/TypeValuePair.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/Utils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/ConfigTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/UnionTypeConfig.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/InvalidUnionType.toml
  bvm/ballerina-runtime/src/test/resources/config_files/negative/UnionAmbiguousType.toml
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/Clone.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneReadOnly.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/CloneWithType.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonWithType.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromBalString_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configUnionTypesProject/configUnionTypes/modules/union_ambiguity/union_ambiguity.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/var/VarDeclaredAssignmentStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typeof/typeof.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/records/records.bal
Labels: Team/jBallerina

#39683 Fix compiler crashes when arguments are provided for both the parameter and the rest field of an included record parameter
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionWithIncludedRecordParam.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/identifiers/IdentifierTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/identifiers/error_as_identifier.bal
Labels: Team/CompilerFE

#39727 Add runtime error and compile time diagnostics for empty character class in regexp ([])
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal
  langlib/langlib-test/src/test/resources/test-src/valuelib_toBalString_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/regexp/RegExpValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_negative_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_key_field_value_test.bal
Labels: Team/CompilerFE, Lang/Regexp

#39915 Add basic positive test cases for group by
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/GroupByClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/group_by_clause.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/group_by_clause_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/group_by_clause_with_invocation.bal
Labels: Team/CompilerFE

#39460 [2201.4.x]Fix completions in named args with included record params context
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config77.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config78.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source77.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source78.bal
Labels: Team/LanguageServer

#39885 [master] Fix getType() API change that causing runtime crash
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/values/BObject.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/AbstractObjectValue.java
  langlib/lang.error/src/main/java/org/ballerinalang/langlib/error/StackTrace.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/GenericMockObjectValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Async.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/TypeReference.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/servicetests/ServiceValue.java
Labels: Team/jBallerina

#39924 [1.2.x] Fix NPE with Ballerina errors when file name is null
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaErrors.java
Labels: Team/jBallerina

#39728 Fix imports being added before licence header
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ImportModuleCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/config/importModuleWithLicenceHeader1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/config/importModuleWithLicenceHeader2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/source/importModuleWithLicenceHeader1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/source/importModuleWithLicenceHeader2.bal
Labels: Team/LanguageServer

#39811 Replace CodeActionContextTypeResolver with expectedType API
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionContextTypeResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/FillRecordFieldsCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ConvertToXmlOrStringTemplateCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/TypeCastNumericExpression.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/FillRecordFieldsCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config17.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config18.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source14.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source15.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/type-cast/config/type_cast_in_binary_operation8.json
Labels: Team/LanguageServer

#39831 Improve map with query expression code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ConvertToQueryExpressionCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ConvertToQueryExpressionCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-query-expr/config/convert_to_query_expr_lhs_record_field3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-query-expr/config/convert_to_query_expr_rhs_function_call.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-query-expr/config/convert_to_query_expr_rhs_method_call.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-query-expr/source/convert_to_query_expr_rhs_function_call.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-query-expr/source/convert_to_query_expr_rhs_method_call.bal
Labels: Team/LanguageServer

#39909 Fix converting reference type values to `json`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#38199 [Master] Fix CCE for method access on union type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/UndefinedFunctionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/undefined-functions.bal
Labels: Team/CompilerFE

#39950 Fix incomplete runtime error message in regex matches
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Find.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Matches.java
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/RegexUtil.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal
Labels: Team/CompilerFE

#39762 Fix several closures in query expressions/actions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithClosuresTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_closures.bal
Labels: Team/CompilerFE

#39819 Remove invalid `variable assignment is required` error for certain function invocations without variable assignments
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function_call_negative.bal
Labels: Team/CompilerFE

#39973 [master] Fix invalid Typedesc values in tuple and arrays
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typeof/TypeofOverLiteralExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typeof/typeof.bal
Labels: Team/jBallerina

#39979 [4.x] Fix invalid Typedesc values in tuple and arrays
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typeof/TypeofOverLiteralExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/typeof/typeof.bal
Labels: Team/jBallerina

#39990 [master] Increase max types and field count for splitted methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
Labels: Team/jBallerina

#39911 Fix NPE in Reference Finding of Semantically invalid symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  language-server/modules/langserver-core/src/test/resources/semantictokens/expected/single-file_expected.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
Labels: Team/CompilerFETools, Team/CompilerFE, Area/SemanticAPI

#39999 Create Invokable type symbols when defining operator types in Symbol Table
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/langAnnotations1.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/source/langAnnotations1.bal
Labels: Team/CompilerFE

#39989 [2201.5.0-stage] Increase max types and field count for splitted methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
Labels: Team/jBallerina

#39929 Fix `TypeChecker.checkIsLikeOnValue` for xml subtypes
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BalStringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#39746 [2201.4.x] Update langlib:regexp examples with correct result
  langlib/lang.regexp/src/main/ballerina/regexp.bal
Labels: Stale

#39937 Disallow assigning nil to a record field with member access lv expressions when there are no nilable fields
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/LValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/lvalue-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/lvalue.bal
Labels: Team/CompilerFE
