Repository ballerina-platform/ballerina-lang, pull requests merged in 2023-07, with the labels that each got.

#40929 [Master] Populate distinct type-ids properly for error intersection
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/ErrorTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/error_type_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_errors/errors.bal
Labels: Team/CompilerFE

#40935 [2201.7.x] Fix recurring loading from distribution
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/definition/DefinitionUtil.java
Labels: Team/LanguageServer

#40502 Add a method to request ballerina central packages
  cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/CentralPackageDescriptorLoader.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportOrgNameNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/connector/CentralPackageListResult.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/AbstractLSTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ImportDeclarationTest.java
  language-server/modules/langserver-core/src/test/resources/central/centralPackages.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_ballerinax_org.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/source/import_decl_with_ballerinax_org.bal
Labels: Team/LanguageServer

#40607 Fix compiler crash for interpolations inside regex char sets
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/RegExpParser.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_test.bal
Labels: Team/CompilerFE, Area/Parser, Lang/Regexp

#40891 Add completions for init function
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/FunctionDefinitionTest.java
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config24.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config25.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config26.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config27.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config28.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config29.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config30.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config31.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config32.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config33.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config34.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/config/config35.json
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source23.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source24.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source25.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source26.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source27.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source28.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source29.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source30.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source31.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source32.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source33.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_def/source/source34.bal
Labels: Team/LanguageServer

#40923 Remove unnecessary methods in frame classes
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/FunctionFrame.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/FrameClassGen.java
Labels: Team/jBallerina

#40952 [2201.6.1-stage]Propagate transactional mode properly in between strands
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
Labels: Team/CompilerFE

#40778 [LS] Improve record field completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/RecordField.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source7.bal
Labels: Team/LanguageServer

#40621 [Master] Support list-constructor-expr in module constant declaration
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  misc/ls-extensions/modules/bal-shell-service/src/test/resources/testcases/getResult/basics.arrays.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantAssignmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ListConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ListConstantTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-assignment-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/list_constant_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/list_constructor_expr_as_constant_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/map-literal-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal
Labels: Team/CompilerFE

#40936 Fix "Runtime assignment of () to string"
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/errors/ErrorCodes.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetAttribute.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attributes.bal
Labels: Team/CompilerFE, Lang/XML

#40868 Improve inlayHint support
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/capability/InitializationOptions.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSClientCapabilitiesImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/inlayhint/InlayHintProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/test/resources/inlayhint/config/config3.json
  language-server/modules/langserver-core/src/test/resources/inlayhint/config/config4.json
  language-server/modules/langserver-core/src/test/resources/inlayhint/config/config5.json
  language-server/modules/langserver-core/src/test/resources/inlayhint/config/config6.json
  language-server/modules/langserver-core/src/test/resources/inlayhint/config/config7.json
  language-server/modules/langserver-core/src/test/resources/inlayhint/config/config8.json
  language-server/modules/langserver-core/src/test/resources/inlayhint/source/inlayhint.bal
  language-server/modules/langserver-core/src/test/resources/inlayhint/source/inlayhint3.bal
  language-server/modules/langserver-core/src/test/resources/inlayhint/source/inlayhint4.bal
  language-server/modules/langserver-core/src/test/resources/inlayhint/source/inlayhint5.bal
  language-server/modules/langserver-core/src/test/resources/inlayhint/source/inlayhint6.bal
  language-server/modules/langserver-core/src/test/resources/inlayhint/source/inlayhint7.bal
  language-server/modules/langserver-core/src/test/resources/inlayhint/source/inlayhint8.bal
Labels: Team/LanguageServer

#40041 Fix several CCE issues in query expressions that has string and xml types as the expected type.
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/StringQueryExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/string-query-expression-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/string-query-expression.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/xml-query-expression-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/xml-query-expression.bal
Labels: Team/CompilerFE

#40866 [7.x]Propagate transactional mode properly in between strands
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
Labels: Team/CompilerFE

#40799 [Master] Correct error msgs for map constants negative cases
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationExpressionCodeAnalysisNegative.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/map/MapInitializerExprNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/map-literal-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/map_constant_negative.bal
Labels: Team/CompilerFE

#40793 [2201.7.x] Correct error msgs for map constants negative case
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationExpressionCodeAnalysisNegative.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/MapConstantTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/map/MapInitializerExprNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/map-literal-constant.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/map_constant_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal
Labels: Team/CompilerFE

#40532 Replace template name with package name in module imports
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/CommandUtil.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java
  cli/ballerina-cli/src/test/resources/test-resources/balacache-template/testorg/centralSample/1.0.2/any/bala.json
  cli/ballerina-cli/src/test/resources/test-resources/balacache-template/testorg/centralSample/1.0.2/any/dependency-graph.json
  cli/ballerina-cli/src/test/resources/test-resources/balacache-template/testorg/centralSample/1.0.2/any/docs/Package.md
  cli/ballerina-cli/src/test/resources/test-resources/balacache-template/testorg/centralSample/1.0.2/any/docs/modules/centralSample.mod1/Module.md
  cli/ballerina-cli/src/test/resources/test-resources/balacache-template/testorg/centralSample/1.0.2/any/modules/centralSample.mod1/mod1.bal
  cli/ballerina-cli/src/test/resources/test-resources/balacache-template/testorg/centralSample/1.0.2/any/modules/centralSample/main.bal
  cli/ballerina-cli/src/test/resources/test-resources/balacache-template/testorg/centralSample/1.0.2/any/package.json
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/FileUtils.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectConstants.java
Labels: Type/Improvement, Area/CLI-BuildTools

#40975 Improve compiler plugin completion manager to provide completions only in valid contexts
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompletionManager.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/LanguageServerExtensionTests.java
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_1/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_1/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_2/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_2/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_3/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_3/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_4/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_4/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_5/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_5/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_6/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions_6/main.bal
Labels: Team/LanguageServer

#40877 Sync `2201.5.x` branch after `2201.5.1` release
  gradle.properties
Labels: Stale

#40964 [Master] Reduce creating unwanted type definitions for const annotations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRWriterUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/Flags.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ConstAnnotationAttachmentSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ConstDeclSymbolTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DisplayAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/TypeDefinitionsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal
Labels: Team/CompilerFE

#41042 [Master] Make ballerina shell experimental
  ballerina-shell/README.md
  ballerina-shell/modules/shell-cli/src/main/resources/command.header.txt
  ballerina-shell/modules/shell-cli/src/main/resources/command.help.txt
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-help.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-shell.help
Labels: Team/CompilerFE

#41045 Fix match statement giving compiler crash in side the do clause
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/match-stmt-in-do-clause.bal
Labels: Team/CompilerFE, Area/Desugar, Lang/Actions/Query

#41048 Add test for regexp langlib usage in query actions and query expressions
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal
Labels: Team/CompilerFE, Lang/Regexp

#38448 Fix not showing function parameters as references in named arguments
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/rename/ProjectRenameTest.java
  language-server/modules/langserver-core/src/test/resources/rename/expected/project/rename_function_named_arg_result.json
  language-server/modules/langserver-core/src/test/resources/rename/sources/project/main.bal
  language-server/modules/langserver-core/src/test/resources/rename/sources/project/modules/module2/module2.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInExprsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
Labels: Team/LanguageServer, Team/CompilerFETools, Area/SemanticAPI

#41060 Fix completions for module indentifier with check keyword
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/check_expression_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/check_expression_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/check_expression_ctx_source10.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/check_expression_ctx_source9.bal
Labels: Team/LanguageServer

#41092 Handle NPE in ExpectedTypeFinder
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_remote_action_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_remote_action_source4.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/check_expression_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/check_expression_ctx_source11.bal
Labels: Team/LanguageServer

#41082 Support change var type code action with let-expr
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeVariableTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarBasedOnLetExpr1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarBasedOnLetExpr2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarBasedOnLetExpr3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarBasedOnLetExpr4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarBasedOnLetExpr5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarBasedOnLetExpr6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarBasedOnLetExpr7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarBasedOnLetExpr1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarBasedOnLetExpr2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarBasedOnLetExpr3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarBasedOnLetExpr4.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarBasedOnLetExpr5.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarBasedOnLetExpr6.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarBasedOnLetExpr7.bal
Labels: Team/LanguageServer

#41080 Differentiate branched transaction context using strand ID
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
Labels: Team/CompilerFE

#40386 Fix reading params incorrectly in attach-functions in BIR
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/readonly/ImmutabilityBalaTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/object_override_includes.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_object_type_inclusion_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/object_definitions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_two/object_definitions.bal
Labels: Area/Compiler, Team/CompilerFE
