Repository ballerina-platform/ballerina-lang, pull requests merged in 2023-06, with the labels that each got.

#40546 Fix issue in renaming symbols in groupby clause
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/rename/RenameTest.java
  language-server/modules/langserver-core/src/test/resources/rename/expected/single/rename_in_groupby_clause.json
  language-server/modules/langserver-core/src/test/resources/rename/sources/single/rename_in_groupby_clause.bal
Labels: Team/LanguageServer

#40599 Support create function code action in groupby clause
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateFunctionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeAction24.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/create_function_in_groupby_clause.bal
Labels: Team/LanguageServer

#40503 Fix the documentation generated by `Document this` and `Update documentation` code actions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/docs/DocumentationGenerator.java
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addObjectFunctionDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addResourceFunctionDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleAnnotationDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleFunctionDocumentation1.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleFunctionDocumentation2.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleModuleVarDocumentation1.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleModuleVarDocumentation2.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleObjectDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleRecordDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/addSingleServiceDocumentation.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/add_single_documentation_with_deprecated1.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/add_single_documentation_with_deprecated2.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/document_already_documented_config3.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/document_already_documented_config7.json
  language-server/modules/langserver-core/src/test/resources/command/add-documentation/config/serviceDocumentationWithAnnotations.json
  language-server/modules/langserver-core/src/test/resources/command/update-documentation/config/updateDocumentationConfig1.json
  language-server/modules/langserver-core/src/test/resources/command/update-documentation/config/updateDocumentationConfig2.json
  language-server/modules/langserver-core/src/test/resources/command/update-documentation/config/updateDocumentationConfig4.json
  language-server/modules/langserver-core/src/test/resources/command/update-documentation/config/updateDocumentationWithDeprecatedConfig2.json
  language-server/modules/langserver-core/src/test/resources/command/update-documentation/config/updateDocumentationWithDeprecatedConfig3.json
Labels: Team/LanguageServer

#40608 Improve Service Template Generator
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/SnippetContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ServiceTemplateGenerator.java
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config17.json
Labels: Team/LanguageServer

#40628 Add LS initialization related overview docs
  docs/language-server/Overview.md
  docs/language-server/README.md
Labels: Team/LanguageServer

#40542 [2201.6.x] Fix getting syntax tree for symbol in defaultable parameter hover logic
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverObjectResolver.java
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_function_call_with_defaultable_param1.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_function_call_with_defaultable_param2.json
  language-server/modules/langserver-core/src/test/resources/hover/source/projectls/defmodsource2.bal
  language-server/modules/langserver-core/src/test/resources/hover/source/projectls/modules/lsmod2/source1.bal
Labels: Team/LanguageServer

#40629 Fix getting syntax tree for symbol in defaultable parameter hover logic
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverObjectResolver.java
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_function_call_with_defaultable_param1.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_function_call_with_defaultable_param2.json
  language-server/modules/langserver-core/src/test/resources/hover/source/projectls/defmodsource2.bal
  language-server/modules/langserver-core/src/test/resources/hover/source/projectls/modules/lsmod2/source1.bal
Labels: Team/LanguageServer

#38064 [Master] Fix Incomplete code sample causes CCE in VariableDeclarationNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_28.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_assert_29.json
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_28.bal
  compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_29.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition-syntax-negative.bal
Labels: Team/CompilerFE

#40585 [master] Improve resource path completions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config18.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config19.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config34.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config35.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config36.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config37.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source27.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source28.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source29.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source30.bal
Labels: Team/LanguageServer

#39027 [master] Add unit tests for field access completions
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_on_method_call_expression_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_on_method_call_expression_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_on_method_call_expression_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_on_method_call_expression_source2.bal
Labels: Team/LanguageServer

#40568 Support change variable type code action for collect clause
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeVariableTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarType_in_collect_clause.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarType_in_collect_clause2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarType_in_collect_clause.bal
Labels: Team/LanguageServer

#39887 Fix Query Actions in Ballerina Shell
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/factory/BasicSnippetFactory.java
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/factory/SnippetFactory.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/QueryEvaluatorTest.java
  ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/BasicSnippetFactoryTest.java
  ballerina-shell/modules/shell-core/src/test/resources/testcases/evaluator/query.action.json
Labels: Stale

#38705 Add tests for closure with `forEach`
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal
Labels: Team/CompilerFE

#40657 Fix incorrect diagnostic codes related to RegExp errors
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
Labels: Team/CompilerFE

#40517 Update snakeYaml
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-bindgen.help
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java
  cli/ballerina-cli/src/test/resources/test-resources/balacache-template/admin/lib_project/0.1.0/java11/package.json
  gradle.properties
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/BindgenCommandTest.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/MavenSupportTest.java
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/assert-files/Ballerina.toml
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/Ballerina.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/bindgen/BindgenTestCase.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/MavenTestCase.java
  tests/jballerina-integration-test/src/test/resources/packaging/maven/jyaml/Ballerina.toml
Labels: Stale

#40486 Change and enable strand dump tests to wait on logs
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BServerInstance.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/LogLeecher.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/Utils.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/troubleshoot/StrandDumpTest.java
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/singleBalFiles/balProgram1.bal
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testOutputs/balProgram1SteadyStateOutput.txt
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testOutputs/balProgram1StrandDumpRegEx.txt
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testOutputs/balTestSteadyState.txt
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testOutputs/balTestStrandDumpRegEx.txt
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testOutputs/testPackageWithModulesSteadyState.txt
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testOutputs/testPackageWithModulesStrandDumpRegEx.txt
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testPackageWithModules/main.bal
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testPackageWithModules/modules/anotherutils/anotherutils.bal
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testPackageWithModules/modules/utils/utils.bal
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testPackageWithModules/tests/main_test.bal
Labels: Team/jBallerina

#40538 Fix included record field signature help
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureInfoModelBuilder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/common/utils/FunctionGeneratorTest.java
  language-server/modules/langserver-core/src/test/resources/signature/included_record/config/config2.json
  language-server/modules/langserver-core/src/test/resources/signature/included_record/config/config3.json
  language-server/modules/langserver-core/src/test/resources/signature/included_record/config/config5.json
  language-server/modules/langserver-core/src/test/resources/signature/included_record/source3.bal
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Team/LanguageServer

#40630 Fix inlay hint support when included record params are present
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/inlayhint/InlayHintProvider.java
  language-server/modules/langserver-core/src/test/resources/inlayhint/config/config1.json
  language-server/modules/langserver-core/src/test/resources/inlayhint/config/config2.json
  language-server/modules/langserver-core/src/test/resources/inlayhint/config/inlayhint.json
  language-server/modules/langserver-core/src/test/resources/inlayhint/source/inlayhint.bal
Labels: Team/LanguageServer

#40410 Fix isolated analysis for function pointer calls
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis_negative.bal
Labels: Team/CompilerFE

#40271 Perform silent expr checks in QueryTypeChecker when resolving selectTypes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_ambiguous_type_negative.bal
Labels: Team/CompilerFE, Lang/Expressions/Query, Lang/Actions/Query

#40064 Set the FIELD flag to fields with default values
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/open_record.bal
Labels: Team/CompilerFE

#40014 [Master] Fix closure variables related compiler crash inside do clause in query expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithClosuresTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_closures.bal
Labels: Team/CompilerFE, Lang/Actions/Query

#40473 Improve configurable module structure error
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/errors/ErrorCodes.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/ConfigNegativeTest.java
  bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/negative/TomlProviderNegativeTest.java
  bvm/ballerina-runtime/src/test/resources/config_files/negative/ValueNotProvidedSubModule.toml
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
  tests/jballerina-integration-test/src/test/resources/configurables/testModuleStructureProject/configPkg/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testModuleStructureProject/configPkg/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testModuleStructureProject/configPkg/modules/util.foo/main.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testModuleStructureProject/configPkg/modules/util.foo2/tests/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/testModuleStructureProject/configPkg/modules/util.foo2/tests/lib_test.bal
  tests/jballerina-integration-test/src/test/resources/configurables/testModuleStructureProject/configPkg/modules/util.foo2/util.foo2.bal
Labels: Team/jBallerina, BreakingChange

#40307 Fix NPE with ballerina.observe.StartSpan #startSpan due to observability not enabled
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java
Labels: Team/jBallerina

#40276 Fix incorrect results for interop of Java instance methods with Ballerina client resource methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/InstanceMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/InstanceMethodResourceClientTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/instance_method_resource_client_test.bal
Labels: Team/jBallerina

#40396 Fix java.lang.StringIndexOutOfBoundsException when unexpected chars in Json string
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/JsonParser.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromJson_test.bal
Labels: Team/jBallerina

#40284 Add completion support for compiler plugins
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilerPluginContextIml.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilerPluginManager.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompletionManager.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompletionResult.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/CompilerPluginContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/completion/CompletionContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/completion/CompletionContextImpl.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/completion/CompletionException.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/completion/CompletionItem.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/completion/CompletionProvider.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/completion/CompletionUtil.java
  compiler/ballerina-lang/src/main/java/module-info.java
  docs/language-server/CompilerPluginCodeActions.md
  docs/language-server/CompilerPluginCompletions.md
  docs/language-server/images/compiler-plugin-completions-1.png
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/CompilerPluginCompletionExtension.java
  project-api/project-api-test/build.gradle
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/plugins/LanguageServerExtensionTests.java
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_comp_plugin_with_completions/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_comp_plugin_with_completions/CompilerPlugin.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_comp_plugin_with_completions/Package.md
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_comp_plugin_with_completions/main.bal
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions/Ballerina.toml
  project-api/project-api-test/src/test/resources/compiler_plugin_tests/package_plugin_user_with_completions/main.bal
  project-api/test-artifacts/compiler-plugin-with-completion-providers/build.gradle
  project-api/test-artifacts/compiler-plugin-with-completion-providers/src/main/java/io/ballerina/plugins/completions/CompilerPluginWithCompletionProviders.java
  project-api/test-artifacts/compiler-plugin-with-completion-providers/src/main/java/io/ballerina/plugins/completions/ServiceBodyContextProvider.java
  project-api/test-artifacts/compiler-plugin-with-completion-providers/src/main/java/module-info.java
  settings.gradle
  tests/language-server-integration-tests/build.gradle
  tests/language-server-integration-tests/src/test/java/org/ballerinalang/langserver/test/completion/CompilerPluginCompletionTests.java
  tests/language-server-integration-tests/src/test/resources/compiler_plugin_tests/package_comp_plugin_with_completions/Ballerina.toml
  tests/language-server-integration-tests/src/test/resources/compiler_plugin_tests/package_comp_plugin_with_completions/CompilerPlugin.toml
  tests/language-server-integration-tests/src/test/resources/compiler_plugin_tests/package_comp_plugin_with_completions/Package.md
  tests/language-server-integration-tests/src/test/resources/compiler_plugin_tests/package_comp_plugin_with_completions/main.bal
  tests/language-server-integration-tests/src/test/resources/completion/compiler-plugins/config/compiler_plugin_completion_single_file_config1.json
  tests/language-server-integration-tests/src/test/resources/completion/compiler-plugins/config/compiler_plugin_with_completions_config1.json
  tests/language-server-integration-tests/src/test/resources/completion/compiler-plugins/config/compiler_plugin_with_completions_config2.json
  tests/language-server-integration-tests/src/test/resources/completion/compiler-plugins/source/package_plugin_user_with_completions/Ballerina.toml
  tests/language-server-integration-tests/src/test/resources/completion/compiler-plugins/source/package_plugin_user_with_completions/main.bal
  tests/language-server-integration-tests/src/test/resources/completion/compiler-plugins/source/source1.bal
  tests/language-server-integration-tests/src/test/resources/testng.xml
Labels: Team/LanguageServer

#40832 Disable bala scheama definition test
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/definition/BalaSchemeDefinitionTest.java
Labels: Team/LanguageServer

#40836 Use 'java-library' plugin instead of Gradle 'java' plugin
  build.gradle
  bvm/ballerina-rt/build.gradle
  cli/ballerina-cli/build.gradle
  gradle.properties
  gradle/javaProject.gradle
  misc/lib-creator/build.gradle
Labels: Team/jBallerina

#40844 Enable disabled few tests cases from ParserTestRunner
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java
Labels: Area/Parser

#40813 [master]Propagate transactional mode properly in between strands
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
Labels: Team/CompilerFE
