Repository ballerina-platform/ballerina-lang, pull requests merged in 2023-11, with the labels that each got.

#41541 Fix xml `toString()` error for modified name space attributes
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/ClosedRecordTypeInclusionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/OpenRecordTypeInclusionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/FunctionPointersWithOptionalArgsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/LimitClauseTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/OrderByClauseTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ClosedRecordOptionalFieldsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/OpenRecordNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDocumentationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/SealedArrayTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/integer/BIntegerValueNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/map/MapAccessExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/var/VarDeclaredAssignmentStmtTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributesTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralWithNamespacesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/xml-query-expression.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-with-namespaces.bal
Labels: Team/jBallerina

#41519 Remove duplicate composite keys from tables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableKeyFieldValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_key_field_value_test.bal
Labels: Team/jBallerina

#41562 Create `init` functions in multiple classes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Constants.java
Labels: Team/jBallerina

#41612 Fix NPE with 'toString' method of FutureValue
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/FutureValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/string/BStringToStringTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/string/bstring-tostring-test.bal
Labels: Team/jBallerina

#41673 [2201.8.x] Fix OOM error when parsing XML CData
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/XmlTreeBuilder.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
Labels: Team/jBallerina

#41658 Remove OldStyleExternalFunctionWrapper class
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalFunctionWrapper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/OldStyleExternalFunctionWrapper.java
Labels: Team/jBallerina

#41545 Fix throwing unnecessary configurable compilation error
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/globalvar/GlobalVarNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_global_var_decl_negative.bal
Labels: Team/jBallerina

#41693 Fix compiler crash in invalid xml with missing closing tag
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/XMLTemplateExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_36.json
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_source_36.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal
Labels: Team/CompilerFE

#41731 [2201.8.x] Fix compiler crash in invalid xml with missing closing tag
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/XMLTemplateExpressionTest.java
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_assert_36.json
  compiler/ballerina-parser/src/test/resources/expressions/xml-template/xml_template_source_36.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal
Labels: Team/CompilerFE

#41628 Provide completions after a variable resource path parameter in a resource access action
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config44.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source37.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfInResourceAccessActionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/actions/resource_access_action.bal
Labels: Team/LanguageServer

#41409 Move object method bodies into a separate class when original class is too large
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/ShutDownListenerGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ExternalMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ConfigMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/FrameClassGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmAnnotationsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmArrayTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmBStringConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmBallerinaConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmErrorTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmModuleConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmRefTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmTupleTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmUnionTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmErrorCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmFunctionCallsCreatorsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmObjectCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmRecordCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmErrorTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmObjectTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmRecordTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmTupleTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/types/JvmUnionTypeGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/tooLargeFileTest/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/tooLargeFileTest/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/tooLargeFileTest/main.bal
Labels: Team/jBallerina

#41534 Fix invalid stream signature in `CreateVariableWithTypeCodeAction`
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableWithTypeTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_for_resource_action_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/source/source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config5.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_client.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_performance.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typeref1.json
  language-server/modules/langserver-stdlib/src/main/ballerina/clients_source1.bal
  language-server/modules/langserver-stdlib/src/main/java/org/ballerinalang/langserver/stdlib/ClientAction.java
Labels: Team/LanguageServer

#41745 [2201.7.x] Fix OOM error when parsing XML CData
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/XmlTreeBuilder.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
Labels: Team/jBallerina

#41679 Fix default worker crash with error return
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmErrorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/services/ErrorReturnTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/services/error_union_return_with_default_worker.bal
Labels: Team/jBallerina

#41640 Fix value conversion error for inline record creation with special characters
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#41663 Improved the order of completions provided for resource access paths
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ResourcePathCompletionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AsyncSendActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config16.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config22.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action__with_check_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action__with_check_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/async_send_action_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/async_send_action_ctx_config2.json
Labels: Team/LanguageServer

#41767 [Worker Change] Fix failing worker `on fail` parser test
  compiler/ballerina-parser/src/test/resources/misc/worker-decl/worker_decl_assert_06.json
  compiler/ballerina-parser/src/test/resources/misc/worker-decl/worker_decl_assert_07.json
Labels: Team/CompilerFE, Area/Parser

#41680 Fix invalid error in using spread field with never-typed optional field
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field_semantic_analysis_negative.bal
Labels: Team/CompilerFE

#41678 Fix query expressions with mismatched expected types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-with-mismatch-return.bal
Labels: Team/CompilerFE, BreakingChange
