Repository ballerina-platform/ballerina-lang, pull requests merged in 2023-04, with the labels that each got.

#40082 [2201.5.0-stage] Consider target array size during type conversion
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#40088 [graalvm-non-reducible-loops] Fix tests hang due to listeners are not stopped
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java
Labels: Team/jBallerina

#39861 Handle the union of never types in function return
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/never/never_code_analysis_negative.bal
Labels: Team/CompilerFE

#40100 Update ls simulator workflow to include 2201.5.x branches
  .github/workflows/language_server_simulator.yml
Labels: Team/LanguageServer

#39965 Remove service template initialization from light weight mode
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
Labels: Team/LanguageServer

#40016 Upgrade snakeYaml and woodstox versions
  bvm/ballerina-core/build.gradle
  bvm/ballerina-rt/build.gradle
  bvm/ballerina-runtime/build.gradle
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaXMLSerializer.java
  cli/ballerina-tool/src/main/resources/cli-help/ballerina-bindgen.help
  distribution/zip/jballerina-tools/LICENSE
  distribution/zip/jballerina-tools/build.gradle
  distribution/zip/jballerina/LICENSE
  gradle/javaLibsProject.gradle
  gradle/javaProject.gradle
  misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java
  misc/ballerina-bindgen/src/test/java/org/ballerinalang/bindgen/MavenSupportTest.java
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/Ballerina.toml
  misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/Ballerina.toml
  misc/testerina/modules/testerina-core/src/main/ballerina/Ballerina.toml
  stdlib/grpc/src/main/ballerina/Ballerina.toml
  stdlib/http/src/main/ballerina/Ballerina.toml
  stdlib/mime/src/main/ballerina/Ballerina.toml
  stdlib/websub/src/main/ballerina/Ballerina.toml
  tests/ballerina-spec-conformance-tests/build.gradle
  tests/ballerina-test-utils/build.gradle
  tests/jballerina-bstring-unit-test/build.gradle
  tests/jballerina-bstring-unit-test/src/test/java/org/ballerinalang/test/types/string/StringValueXmlTest.java
  tests/jballerina-unit-test/build.gradle
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeWithBValueAPITests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/main/function/ArgumentParserPositiveTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableLiteralSyntaxTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLParserNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLSecurityTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/sampleXML.txt
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-with-namespaces.bal
Labels: Team/CompilerFE

#40139 Handle nested character classes being added during traslation
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/RegExpCharSet.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Team/CompilerFE

#40044 Correct node pos of empty XML template expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config63.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expressions_test.bal
Labels: Team/CompilerFETools, Team/CompilerFE, Area/SemanticAPI, Lang/Expressions/XmlTemplate

#39349 Address review Suggestions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TypedescValueImpl.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnonymousTupleAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/LocalRecordAnnotationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableArguments.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/anonymous_tuple_annotation_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal
Labels: Team/CompilerFE

#40182 [irreducible-loops] Generate Main method for testable JARs
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/testable/TestArguments.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/testable/TestConfigArguments.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunNativeImageTestTask.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/NativeUtils.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleDescriptor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ModuleContextDataHolder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/PackageID.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIMethodCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JTermKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/InitMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNode.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/BTestMain.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TestArguments.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TestSuite.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TesterinaFunction.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java
  tests/jballerina-integration-test/src/test/resources/troubleshoot/strandDump/testOutputs/balTestStrandDumpRegEx.txt
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/ModuleExecutionFlowTest.java
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/ModuleExecutionFlowTest-test-listener-shutdown.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/ModuleExecutionFlowTest-test-listener-shutdown.txt
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-flow-tests/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-flow-tests/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-flow-tests/modules/moduleA/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-flow-tests/modules/moduleA/tests/test_moduleA.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-flow-tests/tests/test_main.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#40089 Consider target array size during type conversion
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#39928 Update importModule code action to consider ignored imports
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/ImportModuleCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ImportModuleCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/config/importModuleWithIgnoredImport.json
  language-server/modules/langserver-core/src/test/resources/codeaction/import-module/source/importModuleWithIgnoredImport.bal
Labels: Team/LanguageServer

#39988 Fix multiple signature help, completion and completion sorting issues
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/FieldCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/FunctionCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/NamedArgCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ParameterCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/TypeCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/VariableCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/WorkerCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingConstructorExpressionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverObjectResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config50.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config69.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source50.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_with_special_chars_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_with_special_chars1.bal
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config20.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/config4.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_partial_module_name1.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_partial_module_name2.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_with_missing_param_in_doc1.json
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_with_missing_param_in_doc1.bal
Labels: Team/LanguageServer

#39969 Add missing change variable type code action in let clause and add a test case for select clause
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeVariableTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarType_in_let_clause.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarType_in_select_clause.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarType_in_query_expr.bal
Labels: Team/LanguageServer

#39994 Add missing completions in let variable declaration node context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/LetVariableDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/config/let_expr_ctx_config17.json
  language-server/modules/langserver-core/src/test/resources/completion/let_expression_context/source/let_expr_ctx_source17.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config24.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_let_clause_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_let_clause_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_let_clause_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_let_clause_config8.json
Labels: Team/LanguageServer

#39779 Encode function parameter identifiers at runtime
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/main.bal
Labels: Team/jBallerina

#40112 [2201.4.2] Fix new-line support for config environment variables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlContentProvider.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
Labels: Team/jBallerina, BreakingChange

#40206 [Master] Handle nested character classes being added during translation
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/RegExpCharSet.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Team/CompilerFE

#40235 [master] Populate transaction branch with connection contexts
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionLocalContext.java
Labels: Team/CompilerFE

#40179 Log errors for invalid usages of sequence variables
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/GroupByClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/group_by_clause_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/group_by_clause_with_invocation.bal
Labels: Team/CompilerFE

#40106 [master] Fix error during bal test when test files are present but commented
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/TestCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunNativeImageTestTask.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/NativeUtils.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/TestUtils.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/BTestMain.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/PathVerificationTest-verifyMissingTestsDirectory.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/PathVerificationTest-verifyMissingTestsDirectory.txt
Labels: Stale

#40285 Add 2201.6.x branches to LS simulator workflow
  .github/workflows/language_server_simulator.yml
Labels: Team/LanguageServer

#40203 [2201.5.x] Fix new-line support for config environment variables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlContentProvider.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
Labels: Team/jBallerina

#40110 Fix new-line support for config environment variables
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlContentProvider.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
Labels: Team/jBallerina

#40259 [1.2.x] Use SecureRandom for XID generator
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/transactions/XIDGenerator.java
Labels: Team/jBallerina

#40282 [ballerina-1.2.x] Fix xml parser error messages
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLFactory.java
  bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLTreeBuilder.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLParserNegativeTest.java
Labels: Team/jBallerina

#40261 [1.2.x] Fix config module vulnerability with `LogConfigReader`
  bvm/ballerina-logging/src/main/java/org/ballerinalang/logging/util/LogConfigReader.java
Labels: Team/jBallerina
