Repository ballerina-platform/ballerina-lang, pull requests merged in 2023-12, with the labels that each got.

#41738 [master] Fix XML parser truncating large texts
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/XmlTreeBuilder.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/xml_values/xml_values.bal
Labels: Team/jBallerina

#41739 Split `init` functions in to multiple classes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/LargeMethodSplitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Constants.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/execution/LargeInitBuildTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/modules/mod/mod.bal
Labels: Team/jBallerina

#41538 Fix performance drop drastically while profiling a Ballerina program
  bvm/ballerina-profiler/build.gradle
  bvm/ballerina-profiler/spotbugs-exclude.xml
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/Profiler.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/NonStrandCheckAdapter.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/ProfilerClassVisitor.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/ProfilerMethodWrapper.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/StrandCheckAdapter.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/runtime/Data.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/runtime/ProfileAnalyzer.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/runtime/StackTraceMap.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/FileUtils.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/FrontEnd.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/HttpServer.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/JsonParser.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/util/Constants.java
  bvm/ballerina-profiler/src/main/java/module-info.java
  bvm/ballerina-profiler/src/main/resources/profiler_output.html
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  bvm/ballerina-runtime/src/main/java/module-info.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunProfilerTask.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/ProfileCommandTest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/profiler/ProfilerTest.java
  tests/jballerina-integration-test/src/test/resources/profiler/projectForProfile/package_a/main.bal
  tests/jballerina-integration-test/src/test/resources/profiler/projectForProfile/package_b/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/profiler/projectForProfile/package_b/Config.toml
  tests/jballerina-integration-test/src/test/resources/profiler/projectForProfile/package_b/main.bal
  tests/jballerina-integration-test/src/test/resources/profiler/projectForProfile/package_b/modules/mod_a1/mod1.bal
Labels: Team/jBallerina

#41799 Fix parsing map keys in `fromBalString` method
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BalStringUtils.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromBalString_test.bal
Labels: Team/jBallerina

#41809 Revamp annotation support for `NodeFinder`
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/functionAnnotation6.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/recordFieldAnnotation5.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/source/recordFieldAnnotation5.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/AnnotationNodeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfInCallStatementsTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/annotation_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/LanguageServer

#41278 Notify users when memory is exceeding
  language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/capability/InitializationOptions.java
  language-server/modules/langserver-core/src/main/java/module-info.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSClientCapabilitiesImpl.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/MemoryUsageMonitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TestUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/memoryusagemonitor/MemoryUsageMonitorTest.java
  language-server/modules/langserver-core/src/test/resources/testng.xml
Labels: Team/LanguageServer

#41741 Add semantic support for worker `on fail` clause
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerOnFailTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker-on-fail.bal
Labels: Team/CompilerFE

#41797 Add runtime support for alternate receive
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ErrorUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/errors/ErrorCodes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/errors/ErrorReasons.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WorkerDataChannel.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/InstructionKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIRBasicBlockOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIRLockOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/SimpleBLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangAlternateWorkerReceive.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangMultipleWorkerReceive.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_01.json
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_03.json
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_04.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_assert_04.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_08.json
  langlib/lang.__internal/src/main/ballerina/auto-close-channels.bal
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/AutoCloseChannels.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerAlternateReceiveTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerConditionalSendTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/actions-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-send-in-if.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-sync-send-in-fork.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-sync-send-in-if.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers_alt_receive.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers_conditional_send.bal
Labels: Team/jBallerina

#41455 Resolve TypeParams in ExpectedTypeFinder
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibFunctionBinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/util/SymbolUtils.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config5.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config6.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config7.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/lang_lib_func_expr_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source1.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source10.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source2.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source3.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source4.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source5.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source6.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source7.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source8.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/lang_lib_func_expr_ctx_source9.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/FunctionCallExpressionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/function_call_expression_test.bal
Labels: Team/LanguageServer

#41882 Add tests to check the symbol of error references
  language-server/modules/langserver-core/src/test/resources/completion/function_body/config/config18.json
  language-server/modules/langserver-core/src/test/resources/completion/function_body/source/source18.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ErrorTypeSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/error_type_symbol_test.bal
Labels: Team/LanguageServer

#41880 [Worker Change] Fix formatting of multiple receive actions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STReceiveFieldNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STTreeModifier.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeFactory.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeTransformer.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/NodeVisitor.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ReceiveFieldNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/ReceiveFieldsNode.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/ParserTestUtils.java
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_01.json
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_03.json
  compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_assert_04.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_assert_02.json
  compiler/ballerina-parser/src/test/resources/actions/send-action/send_action_assert_04.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_assert_08.json
  compiler/ballerina-parser/src/test/resources/misc/completion/completion_source_08.bal
  compiler/ballerina-treegen/src/main/resources/syntax_node_metadata.json
  compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/actions/send-receive/assert/send_receive_action_4.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/send-receive/source/send_receive_action_4.bal
  misc/syntax-api-calls-gen/src/main/resources/api_gen_syntax_tree_descriptor.json
Labels: Team/CompilerFE

#41743 Look up closure symbols with the original symbol
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/UnionTypeBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/BinaryExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/elvis/ElvisExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/ternary/TernaryExpressionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtTypeNarrowingTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/test_union_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/union_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/closures/closure_negative_02.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/elvis/elvis-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/match-stmt-type-narrow.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal
Labels: Team/CompilerFE

#41494 Fix invalid completions for a precise resource parameter type
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ResourcePathCompletionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config38.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config39.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config40.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config41.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config42.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config43.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source31.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source32.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source33.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source34.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source35.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/source/client_resource_access_action_source36.bal
Labels: Team/LanguageServer

#41756 Generate notifications for cyclic dependencies to the LS client
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/diagnostics/CyclicDependenciesTest.java
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_multi/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_multi/modules/abc/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_multi/modules/def/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_multi/modules/ghi/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_multi/modules/jkl/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_multi/modules/mno/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_multi/modules/pqr/main.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_simple/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_simple/modules/mod1/mod1.bal
  language-server/modules/langserver-core/src/test/resources/diagnostics/sources/cyclic_simple/modules/mod2/mod2.bal
Labels: Team/LanguageServer

#41482 Add required resources locally for offline html report generation of Ballerina profiler
  .gitignore
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/Profiler.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/FrontEnd.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/HttpServer.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/util/Constants.java
  cli/ballerina-cli/build.gradle
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunProfilerTask.java
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-profile.help
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/ProfileCommandTest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/model/Target.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectConstants.java
  distribution/zip/jballerina-tools/build.gradle
  distribution/zip/jballerina-tools/resources/profiler/ballerina-profiler-report-logo.svg
  distribution/zip/jballerina-tools/resources/profiler/css/flamegraph.css
  distribution/zip/jballerina-tools/resources/profiler/css/maxcdn_bootstrap_min.css
  distribution/zip/jballerina-tools/resources/profiler/favicon.ico
  distribution/zip/jballerina-tools/resources/profiler/js/cdn_flamegraph_min.js
  distribution/zip/jballerina-tools/resources/profiler/js/d3js_v7.js
  distribution/zip/jballerina-tools/resources/profiler/profiler_output.html
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/profiler/ProfilerTest.java
Labels: Team/jBallerina

#41556 Fix overloaded method interop calls when parameter types are not specified
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/overloading/OverriddenMethodTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/overloading/pkg/Car.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/overloading/pkg/SportsCar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/overloading/pkg/Vehicle.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/instance_method_tests.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/method_resolve_error.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/overloaded_methods.bal
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/overloading/overridden_method_test.bal
Labels: Team/jBallerina

#41810 Fix issue when using xml navigation with an element containing escape character
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-navigation-access.bal
Labels: Team/CompilerFE

#41665 Fix NPE in anon record type field access
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/semantictokens/SemanticTokensTest.java
  language-server/modules/langserver-core/src/test/resources/semantictokens/config/single-file/record.bal
  language-server/modules/langserver-core/src/test/resources/semantictokens/expected/record_expected.json
Labels: Team/CompilerFE

#41913 Implement new worker semantics - Part III
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerConditionalSendTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
Labels: Team/CompilerFE
