Repository ballerina-platform/ballerina-lang, pull requests merged in 2023-08, with the labels that each got.

#41130 Add completions after final keyword
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModuleVariableDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config20.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config21.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/source/source20.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/source/source21.bal
Labels: Team/LanguageServer

#41145 Remove LS simulator
  .github/workflows/language_server_simulator.yml
  tests/language-server-simulator/build.gradle
  tests/language-server-simulator/spotbugs-exclude.xml
  tests/language-server-simulator/src/main/java/module-info.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/Editor.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/EditorOutputStream.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/EditorSimulator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/EditorTab.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/ClassGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/CodeSnippetGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/FunctionGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/Generators.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/ImportStatementGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/MatchStatementGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/ServiceGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/StatementGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/TypeDefinitionGenerator.java
  tests/language-server-simulator/src/main/java/org/ballerinalang/langserver/simulator/generators/VarDeclarationStatementGenerator.java
Labels: Team/LanguageServer

#41161 Suggest clauses after type test
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeTestExpressionNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config32.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config33.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config34.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config35.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/config/query_expr_ctx_config36.json
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_source32.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_source33.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_source34.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_source35.bal
  language-server/modules/langserver-core/src/test/resources/completion/query_expression/source/query_expr_ctx_source36.bal
Labels: Team/LanguageServer

#41131 Fix `map` keyword using as an identifier when it is followed by `<`
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QualifiedIdentifierTest.java
  compiler/ballerina-parser/src/test/resources/expressions/qualified-identifier/qualified_identifier_assert_09.json
  compiler/ballerina-parser/src/test/resources/expressions/qualified-identifier/qualified_identifier_source_08.bal
  compiler/ballerina-parser/src/test/resources/expressions/qualified-identifier/qualified_identifier_source_09.bal
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
Labels: Team/CompilerFE, Area/Parser

#41079 Add semantic support for on fail check expr
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ASTBuilderUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BCheckedOnFailSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/SymTag.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/SimpleBLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangCheckedOnFailExpr.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/chekedonfailexpr/CheckedOnFailExprNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/chekedonfailexpr/CheckedOnFailExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedonfailexpr/check_on_fail_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedonfailexpr/check_on_fail_expr_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedonfailexpr/check_on_fail_in_module_level.bal
  tests/jballerina-unit-test/src/test/resources/testng.xml
Labels: Team/CompilerFE

#40026 Fix NPE in `SemanticModel.typeOf()` API for resource path access action nodes
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfRegressionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/regression-tests/typeof_resource_path_action.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testproject/client.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#40577 Fix codegen crashing for `readonly` table value returning
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableValueAssignTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_value_assign_test.bal
Labels: Area/JVMCodeGen, Team/jBallerina

#41178 Add missing completion test cases
  language-server/modules/langserver-core/src/test/resources/completion/function_body/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/function_body/config/config17.json
  language-server/modules/langserver-core/src/test/resources/completion/function_body/source/source16.bal
  language-server/modules/langserver-core/src/test/resources/completion/function_body/source/source17.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/config18.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/source/source19.bal
Labels: Team/LanguageServer

#41184 Bump `mime4j` and `woodstox` transitive dependency versions
  build.gradle
  bvm/ballerina-core/build.gradle
  bvm/ballerina-runtime/build.gradle
  gradle/javaProject.gradle
  stdlib/email/build.gradle
  stdlib/io/build.gradle
  stdlib/mime/build.gradle
  stdlib/stringutils/build.gradle
  stdlib/xmlutils/build.gradle
  stdlib/xslt/build.gradle
  tests/ballerina-test-utils/build.gradle
Labels: dependencies

#40811 Fix incorrect array initialisation with simultaneously changing global variables
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGenEnv.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/BIROptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/ControlFlowGraph.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/optimizer/LivenessAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bir/BirVariableOptimizationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayInitializerExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/$lambda$_0
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/failLockWithinLock
  tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-initializer-expr.bal
Labels: Team/jBallerina

#41191 Add `copyToLib` dependency for benchmark tests
  tests/jballerina-benchmark-test/build.gradle
Labels: Team/jBallerina

#41062 Update Okio version
  gradle.properties
Labels: dependencies

#41171 Suggest ballerina central packages when they're partially typed
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/CentralPackageDescriptorLoader.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/SymbolUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/CompletionSearchProvider.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_ballerinax_org.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_ballerinax_org2.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_ballerinax_org3.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/config/import_decl_with_ballerinax_org4.json
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/source/import_decl_with_ballerinax_org2.bal
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/source/import_decl_with_ballerinax_org3.bal
  language-server/modules/langserver-core/src/test/resources/completion/import_decl/source/import_decl_with_ballerinax_org4.bal
Labels: Team/LanguageServer

#41170 Add create function CA for var type decleration and select-expr
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateFunctionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeAction25.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeAction26.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeAction27.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeAction28.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeAction29.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeAction30.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/config/undefinedFunctionCodeAction31.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/createUndefinedFunction14.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/createUndefinedFunction15.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/createUndefinedFunction16.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/createUndefinedFunction17.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/createUndefinedFunction18.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/createUndefinedFunction19.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-function/source/createUndefinedFunction20.bal
Labels: Team/LanguageServer

#41194 Add required dependency from `copyToLib` for test packages
  tests/jballerina-integration-test/build.gradle
Labels: Team/jBallerina

#41053 Fix fill record field code action and fill record filed completions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/FillRecordFieldsCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config19.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config20.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config21.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config22.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/config/fill_record_fields_config23.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fill-record-fields/source/fill_record_fields_source16.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config10.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config11.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config12.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config13.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config14.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config9.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source8.bal
Labels: Team/LanguageServer, Team/CompilerFE, Area/CodeAction, Area/Completion

#40545 Implement logging warnings for deprecated param usages in funcion call and fix inconsistent behaviour in warnings in deprecated record fields
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/deprecation_annotation.bal
Labels: Team/CompilerFE

#41146 Add local module dependency to Ballerina.toml
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/AddModuleToBallerinaTomlCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddModuleToBallerinaTomlCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module10.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module9.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module_negative_1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/config/add_module_negative_2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject1/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject1/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject10/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject10/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject11/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject11/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject12/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject12/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject2/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject2/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject3/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject3/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject4/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject4/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject5/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject5/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject6/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject6/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject7/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject7/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject8/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject8/main.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject9/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/codeaction/add-module-ballerina-toml/source/testproject9/main.bal
  language-server/modules/langserver-core/src/test/resources/local_projects/pkg1/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/local_projects/pkg1/main.bal
  language-server/modules/langserver-core/src/test/resources/local_projects/pkg1/modules/mod1/mod1.bal
  language-server/modules/langserver-core/src/test/resources/local_projects/pkg2/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/local_projects/pkg2/main.bal
  language-server/modules/langserver-core/src/test/resources/local_projects/pkg2/modules/mod1/mod1.bal
  language-server/modules/langserver-core/src/test/resources/local_projects/x.y/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/local_projects/x.y/main.bal
  language-server/modules/langserver-core/src/test/resources/local_projects/x.y/modules/mod1/mod1.bal
  language-server/modules/langserver-core/src/test/resources/local_projects/x/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/local_projects/x/main.bal
  language-server/modules/langserver-core/src/test/resources/local_projects/x/modules/y/y.bal
Labels: Team/LanguageServer

#41172 Handle possible error completions when aggregation clause is used
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/CollectClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/collect_clause.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/collect_clause_negative.bal
Labels: Team/CompilerFE

#40971 Improve uninitialised variable analysis for statements with on-fail
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/onfail/OnFailClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause-negative-v2.bal
Labels: Team/CompilerFE

#39600 Throw error when field access is used with a map of `xml`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/OptionalFieldAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributeAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-lax-behavior.bal
Labels: Team/CompilerFE

#38245 [Master] Make async-send an action
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BaseVisitor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/NodeKind.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/WorkerSendExpressionNode.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/WorkerSendSyncExpressionNode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClassClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/SimpleBLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerAsyncSendExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerFlushExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerSyncSendExpr.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/actions/StartActionTest.java
  compiler/ballerina-parser/src/test/resources/actions/start-action/start_action_assert_06.json
  compiler/ballerina-parser/src/test/resources/actions/start-action/start_action_source_06.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/start/StartActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/action/start/start-action-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr_code_analysis_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker_async_send_as_expression.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker_async_send_negative.bal
Labels: Team/CompilerFE

#40774 Fix issue with global variable as default value for class field and function parameter
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/object/object-with-defaultable-field.bal
Labels: Team/CompilerFE

#37832 [Master] Fix compiler crashes when a union is used within multiple wait
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-actions-negative.bal
Labels: Team/CompilerFE

#41017 Support large list and mapping constructors
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/LargeStructureUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/HandleValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmSignatures.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIConstructorCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIMethodCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JInsKind.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JInstruction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JLargeArrayInstruction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JLargeMapInstruction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodCallInstruction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JavaMethodCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/BIREmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/EmitterUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/emit/InstructionEmitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRAbstractInstruction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRNonTerminator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/model/BIRTerminator.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BCompileUtil.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/failLockWithinLock
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/failWithinOnFail
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/globalVarsAndAnonFunctions
  tests/jballerina-unit-test/src/test/resources/test-src/bir/bir-dump/mapInits
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/functions/large-functions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/functions/large-init-function.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/functions/large-user-defined-function.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods/modules/functions/workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods2/modules/records/query-large-record-array.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods2/modules/records/record-with-annotations.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods3/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods3/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods3/main.bal
Labels: Team/jBallerina

#40074 Disallow annotations with mutable objects
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationDeclarationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annotation_readonly_types.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annots_with_invalid_consts.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annots_with_invalid_type.bal
Labels: Team/CompilerFE

#40757 Update isolated analysis in the init method
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationInferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolated-objects/isolated_objects_isolation_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_inference.bal
Labels: Team/CompilerFE

#40581 [Master] Fix incorrect cyclic function detection
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/functions/FunctionSignatureInBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/functions/test_different_function_signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/different_function_signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/cyclic-functions-negative.bal
Labels: Team/CompilerFE

#40835 [Master] Fix issues when there is union type in the select clause
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr_semantic_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_ambiguous_type_negative.bal
Labels: Team/CompilerFE

#40582 [2201.6.x] Fix incorrect cyclic function detection
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/functions/test_different_function_signatures.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/different_function_signatures.bal
Labels: Team/CompilerFE

#38029 [Master] Fix Invalid type inferring for literal expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/SimpleConstantBalaNegativeTests.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/literals/NumericLiteralNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/literals/NumericLiteralAssignmentTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finite/FiniteTypeNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/floattype/BFloatValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/literals/test_numeric_literal_negative_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_numeric_literals/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_numeric_literals/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/numeric_literal_assignment.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/numeric_literal_assignment_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type-negative.bal
Labels: Team/CompilerFE

#39477 Add semantic API support for resource path symbols
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaPathParameterSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaResourceMethodSymbol.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/resourcepath/BallerinaPathRestParam.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/resourcepath/BallerinaPathSegmentList.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/resourcepath/util/BallerinaNamedPathSegment.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/SymbolKind.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/resourcepath/util/NamedPathSegment.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/resourcepath/util/PathSegment.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BResourcePathSegmentSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangResourcePathSegment.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/FunctionCompletionItemBuilder.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/rename/RenameUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/rename/RenameTest.java
  language-server/modules/langserver-core/src/test/resources/rename/expected/single/rename_resource_method_path_segment.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ServiceSemanticAPITest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/actions/SymbolsInResourceAccessActionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInResourceAccessActionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByIsolatedServiceDeclTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbolbynode/SymbolByServiceDeclTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/SymbolsInResourceMethodsTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typeof/TypeOfInResourceAccessActionTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/util/SemanticAPITestUtils.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/actions/resource_access_action.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_resource_access_action.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/resource_method_symbols.bal
  tests/ballerina-compiler-api-test/src/test/resources/testng.xml
Labels: Team/CompilerFETools, Area/SemanticAPI

#41132 Introduce Ballerina profiler
  bvm/ballerina-profiler/build.gradle
  bvm/ballerina-profiler/spotbugs-exclude.xml
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/Main.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/Profiler.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/NonStrandCheckAdapter.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/ProfilerClassLoader.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/ProfilerClassVisitor.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/ProfilerClassWriter.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/ProfilerMethodWrapper.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/StrandCheckAdapter.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/runtime/Data.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/runtime/ProfileAnalyzer.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/runtime/ProfilerRuntimeException.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/FrontEnd.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/HttpServer.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/JsonParser.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/util/Constants.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/util/ProfilerException.java
  cli/ballerina-cli/build.gradle
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/Constants.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/ProfileCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/LauncherUtils.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/util/BalToolsUtil.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunProfilerTask.java
  cli/ballerina-cli/src/main/resources/META-INF/services/io.ballerina.cli.BLauncherCmd
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-help.help
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-profile.help
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/ProfileCommandTest.java
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/unix/run-project-with-profile.txt
  cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/run-project-with-profile.txt
  cli/ballerina-cli/src/test/resources/test-resources/projectForProfile/package_a/Ballerina.toml
  cli/ballerina-cli/src/test/resources/test-resources/projectForProfile/package_a/main.bal
  cli/ballerina-cli/src/test/resources/test-resources/projectForProfile/package_a/modules/mod_a1/mod1.bal
  cli/ballerina-cli/src/test/resources/testng.xml
  distribution/zip/jballerina-tools/build.gradle
  misc/identifier-util/src/main/java/module-info.java
  settings.gradle
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/profiler/ProfilerTest.java
  tests/jballerina-integration-test/src/test/resources/profiler/profiler_single_file.bal
  tests/jballerina-integration-test/src/test/resources/profiler/projectForProfile/package_a/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/profiler/projectForProfile/package_a/main.bal
  tests/jballerina-integration-test/src/test/resources/profiler/projectForProfile/package_a/modules/mod_a1/mod1.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#41185 Refactor LS Workspace Manger
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/workspace/TestWorkspaceManager.java
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_duplicate_files1/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_duplicate_files1/gen1.bal
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_duplicate_files1/generated/gen1.bal
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_duplicate_files1/main.bal
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_duplicate_files2/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_duplicate_files2/generated/mod1/mod1.bal
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_duplicate_files2/main.bal
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_duplicate_files2/modules/mod1/mod1.bal
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_generated_sources1/Ballerina.toml
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_generated_sources1/generated/mod1/mod1.bal
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_generated_sources1/main.bal
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_generated_sources1/modules/mod1/test.bal
  language-server/modules/langserver-core/src/test/resources/project/pkg_with_generated_sources1/modules/mod2/mod2.bal
Labels: Team/LanguageServer
