Repository ballerina-platform/ballerina-lang, pull requests merged in 2023-02, with the labels that each got.

#39251 [2201.3.x] Fix hint for native build
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
Labels: Stale

#39427 Introduce QueryDesugar changes related to group by
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangGroupByClause.java
  langlib/lang.query/src/main/ballerina/types.bal
Labels: Team/CompilerFE

#39474 [2201.4.0-stage] Fix incorrect rename popup on create var
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableWithCheck7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableWithRemoteMethodInvocation.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithCheck2.bal
Labels: Team/LanguageServer

#39480 Increase max types and field count for splited methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
Labels: Team/jBallerina

#39472 [2201.4.0-stage] Fix no such type error when anonymous error types in imported modules are used
  .github/workflows/pull_request_full_build.yml
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/PublicAndPrivateTypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/public_and_private_types_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/modules/parser/Module.md
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/modules/parser/records.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/records.bal
Labels: Team/jBallerina

#38813 Allow valid list constructor expressions in annotation attachments for const annotations defined with non-source-only attachment points
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationAttachmentSymbolsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationDeclarationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationRuntimeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/annotation/AnnotationTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_attachments_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annots_with_invalid_consts.bal
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annots_with_list_consts.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_annotation_usage_project/annotations_usage.bal
Labels: Team/CompilerFE

#39240 Fix the isolated analyzer for when a fixed-length array rest argument specifies arguments for required parameters
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/IsolatedParamTest.java
  langlib/langlib-test/src/test/resources/test-src/isolated-param/isolated_param.bal
  langlib/langlib-test/src/test/resources/test-src/isolated-param/isolated_param_negative.bal
Labels: Team/CompilerFE

#39329 Fix mapping field binding patterns with identifiers that include identifier escapes
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/RecordVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal
Labels: Team/CompilerFE

#38388 Fix list and mapping binding patterns with immutable types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/ErrorVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/RecordVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/TupleVariableReferenceTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/ErrorVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/error_variable_reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/tuple-variable-reference-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/tuple-variable-reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/error_variable_definition_stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition.bal
Labels: Team/CompilerFE

#39319 Fix union member types not being set for immutable `json` and `anydata` types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/readonly/SelectivelyImmutableTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type_negative.bal
Labels: Team/CompilerFE

#38615 Add Semantic API test cases for function type param symbols
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolBIRTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_lookup_with_function_types_test.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testproject/functions.bal
  tests/ballerina-compiler-api-test/src/test/resources/test-src/testproject/type_defs.bal
Labels: Team/CompilerFETools, Area/SemanticAPI

#39473 Fix incorrect rename popup on create var
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableWithCheck7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableWithRemoteMethodInvocation.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithCheck2.bal
Labels: Team/LanguageServer

#39564 Fix suggesting incorrect completions in statement context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/assignment_stmt_ctx_config9.json
Labels: Team/LanguageServer

#39582 [Master] Fix regular expressions not working with table keys and query expressions/actions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TableUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/RegExpValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/SimpleQueryExpressionWithDefinedTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableKeyFieldValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_key_field_value_test.bal
Labels: Team/CompilerFE

#38706 [2201.3.x] Fix regular expressions not working with table keys and query expressions/actions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TableUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/RegExpValue.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/SimpleQueryExpressionWithDefinedTypeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/table/TableKeyFieldValueTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_key_field_value_test.bal
Labels: Team/CompilerFE

#39326 [master]Fix completions in named args with included record params context
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config77.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_expr_ctx_config78.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source77.bal
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source78.bal
Labels: Team/LanguageServer

#39602 Fix LS high priority bugs
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModulePartNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/QueryPipelineNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SortingUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddCheckCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeGuardTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/config/add_check_on_field_access_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/config/add_check_on_field_access_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/source/add_check_on_field_access_source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/source/add_check_on_field_access_source2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithRemoteMethodInvocation.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableWithRemoteMethodInvocation.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/config/typeGuardErrorType1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/source/typeGuardErrorType.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_configurable_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_configurable_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_configurable_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/source/source17.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config18.json
Labels: Team/LanguageServer

#39238 Throw Runtime exceptions for invalid find indexes in Regexps
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/BallerinaErrorReasons.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  langlib/lang.regexp/src/main/java/org/ballerinalang/langlib/regexp/Find.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibRegexpTest.java
  langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal
Labels: Type/Improvement, Team/CompilerFE, Lang/Regexp

#39587 [2201.4.x] Fix suggesting incorrect completions in statement context
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java
  language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/assignment_stmt_ctx_config9.json
Labels: Team/LanguageServer

#39614 [2201.4.x] Fix LS high priority bugs
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddCheckCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModulePartNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/QueryPipelineNodeContext.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/SortingUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddCheckCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/TypeGuardTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/config/add_check_on_field_access_config1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/config/add_check_on_field_access_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/source/add_check_on_field_access_source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-check/source/add_check_on_field_access_source2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithRemoteMethodInvocation.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/createVariableWithRemoteMethodInvocation.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/config/typeGuardErrorType1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/type-guard/source/typeGuardErrorType.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_configurable_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_configurable_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/config/module_level_after_configurable_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/module_part_context/source/source17.bal
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config14.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config15.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config16.json
  language-server/modules/langserver-core/src/test/resources/completion/module_var_context/config/config18.json
Labels: Team/LanguageServer

#39549 Fix StackOverflow in Inner Join Function
  langlib/lang.query/src/main/ballerina/types.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause.bal
Labels: Team/CompilerFE

#38390 Fix Closure issue when a query expression is used in a let clause of another query expression.
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  misc/ls-extensions/modules/bal-shell-service/src/test/resources/testcases/getResult/query.expressions.json
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationNegativeTest.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/MultipleLetClauseTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryNegativeTests.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/multiple-let-clauses.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-negative.bal
Labels: Team/CompilerFE

#39535 Improve convert to `xml` or `string` code action to support regex template
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/Types.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ConvertToXmlOrStringTemplateCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ConvertToXmlOrStringTemplateCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config14.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config15.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/config/config6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/convert-to-str-xml-tmplt/source/source.bal
Labels: Team/LanguageServer

#39580 Fix elvis expression for type reference types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/elvis/ElvisExpressionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/elvis/elvis-expr-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/elvis/elvis-expr.bal
Labels: Team/CompilerFE

#38633 Update LSP4J version to 0.15.0
  gradle.properties
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaNotebookDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java
Labels: Team/LanguageServer

#39620 [master] Improve ExpectedType API for function call expression context
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/function_call_expression_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/function_call_expression_ctx_config22.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/FunctionCallExpressionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/function_call_expression_test.bal
Labels: Team/LanguageServer

#39621 [2201.4.x] Improve ExpectedType API for function call expression context
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/function_call_expression_ctx_config15.json
  language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/function_call_expression_ctx_config22.json
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/FunctionCallExpressionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/function_call_expression_test.bal
Labels: Team/LanguageServer

#39400 Fix `LocksInMainTest.throwErrorInsideLock` test
  tests/jballerina-unit-test/src/test/resources/test-src/lock/locks-in-functions.bal
Labels: Team/jBallerina

#39518 [master] Fix `No such function error` thrown for default functions with special characters
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Async.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/async/main.bal
Labels: Team/jBallerina

#39623 Fix `never` type included record fields shown in signature help
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureInfoModelBuilder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/signature/AbstractSignatureHelpTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/signature/IncludedRecordParameterTest.java
  language-server/modules/langserver-core/src/test/resources/signature/included_record/config/config4.json
  language-server/modules/langserver-core/src/test/resources/signature/included_record/source2.bal
Labels: Team/LanguageServer

#39608 Fix issue with resolving closures in langlib calls with arrow expressions in query expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/InnerQueryTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/SimpleQueryExpressionWithDefinedTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/inner-queries.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal
Labels: Team/CompilerFE

#39681 Fix incorrectly creating a union with one member as the inferred parameter type with tuples
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/ArrowExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/arrow-expression-semantics-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/arrow-expression.bal
Labels: Team/CompilerFE

#39662 Fix bugs in regex:replaceAll function with index parameter
  langlib/lang.regexp/src/main/ballerina/regexp.bal
  langlib/langlib-test/src/test/resources/test-src/regexp_test.bal
Labels: Team/CompilerFE

#39520 Fix getting langlib methods for intersection types
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config31.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config32.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config56.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config59.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config60.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/config/field_access_ctx_config61.json
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source59.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source60.bal
  language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source61.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/langlib_test.bal
Labels: Team/LanguageServer, Team/CompilerFETools, Area/Completion, Lang/Regexp

#39687 [2201.4.x] Fix never type included record fields shown in signature help
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureInfoModelBuilder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/signature/AbstractSignatureHelpTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/signature/IncludedRecordParameterTest.java
  language-server/modules/langserver-core/src/test/resources/signature/included_record/config/config4.json
  language-server/modules/langserver-core/src/test/resources/signature/included_record/source2.bal
Labels: Team/LanguageServer

#39702 Fix incorrectly creating a union with no members as the inferred parameter type with empty tuples
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/lambda/ArrowExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/arrow-expression-semantics-negative.bal
Labels: Team/CompilerFE

#38900 Fix visiting expressions in resource access action
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_with_action_or_expr.bal
Labels: Team/CompilerFE

#39531 Fix no such type error when anonymous error types in imported modules are used
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeHashVisitor.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/PublicAndPrivateTypesTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/public_and_private_types_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/errors.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/modules/parser/Module.md
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/modules/parser/records.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_types/records.bal
Labels: Team/jBallerina

#39713 [2201.4.x] Fix broken View API Docs urls
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/APIDocReference.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverSymbolResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/hover/HoverProviderTest.java
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_annotation.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_class.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_client.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_constant.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_enum.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_error.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_function1.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_function2.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_listener.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_objecttype.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_record.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_type.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_variable.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_performance.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typeref1.json
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_for_api_docs.bal
  tests/language-server-integration-tests/src/test/java/org/ballerinalang/langserver/test/hover/ApiDocsUrlTest.java
  tests/language-server-integration-tests/src/test/resources/testng.xml
Labels: Team/LanguageServer

#39725 Fix additive expression when one operand is a union that is a subtype of a single basic type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/AddOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation-negative.bal
Labels: Team/CompilerFE

#39675 Introduce `some` and `every` functions
  langlib/lang.boolean/src/main/ballerina/boolean.bal
  langlib/lang.boolean/src/main/java/org/ballerinalang/langlib/bool/Every.java
  langlib/lang.boolean/src/main/java/org/ballerinalang/langlib/bool/Some.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibBooleanTest.java
  langlib/langlib-test/src/test/resources/test-src/booleanlib_test.bal
Labels: Team/CompilerFE

#38649 Return type if already visited while visiting recursive records
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecursiveRecordTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/record/recursive_record.bal
Labels: Team/CompilerFE, Stale

#39688 Implement typedesc for mapping binding pattern with anonymous record type
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/RecordVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/tuple-variable-definition.bal
Labels: Team/CompilerFE
