Repository ballerina-platform/ballerina-lang, pull requests merged in 2024-01, with the labels that each got.

#41800 Remove the strandId when doing `generateCombinedTransactionId` in `TransactionResourceManager`
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
Labels: Team/CompilerFE

#41762 Start listening phase even when listeners are only in imported modules
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
Labels: Team/jBallerina

#41722 Fix invalid behavior in `TableIterator` with hash-collided keys
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java
  langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/table/table_key_field_value_test.bal
Labels: Team/jBallerina

#41504 [2201.8.x] Fix TypeCastError in concurrent transactions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionLocalContext.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
Labels: Stale

#41506 [master] Fix TypeCastError in concurrent transactions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionLocalContext.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
Labels: Team/CompilerFE, Stale

#41505 [2201.7.x] Fix TypeCastError in concurrent transactions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionLocalContext.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
Labels: Stale

#41925 [Worker Change] Fix result type for multiple receive action
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
Labels: Team/CompilerFE

#41823 Fix profiler crashes in windows
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/Profiler.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/codegen/ProfilerMethodWrapper.java
  bvm/ballerina-profiler/src/main/java/io/ballerina/runtime/profiler/ui/HttpServer.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunProfilerTask.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/profiler/ProfilerTest.java
Labels: Team/jBallerina

#41922 [Woker Change] Add no message error type for worker interactions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  langlib/lang.error/src/main/ballerina/error.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerConditionalSendTest.java
Labels: Team/CompilerFE

#41932 Fix computed field node formatting
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_assert_05.json
  compiler/ballerina-parser/src/test/resources/misc/ambiguity/ambiguity_source_05.bal
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/resources/types/structured/assert/map_type_2.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/structured/assert/record_type_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/types/structured/source/record_type_1.bal
Labels: Area/Formatting, Team/CompilerFE

#41944 [Worker Change] Fix semanitc API visitors for alternate and multiple receive nodes
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
Labels: Team/CompilerFE

#41890 Add display annotation support for worker and external function bodies
  langlib/lang.annotations/src/main/ballerina/annotations.bal
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/externalFunctionAnnotation1.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/externalFunctionAnnotation2.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/startActionAnnotation1.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/startActionAnnotation2.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/workerDeclAnnotation1.json
  language-server/modules/langserver-core/src/test/resources/completion/annotation_ctx/config/workerDeclAnnotation2.json
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DisplayAnnotationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/display_annot.bal
Labels: Team/CompilerFE

#41872 [Master] Update component fetch logic
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/BallerinaPackageService.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/packages/ComponentsTest.java
  language-server/modules/langserver-core/src/test/resources/packages/components/project-exception_expected.json
Labels: Stale

#41873 [2201.8.x] Update component fetch logic
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/BallerinaPackageService.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/packages/ComponentsTest.java
  language-server/modules/langserver-core/src/test/resources/packages/components/project-exception_expected.json
Labels: Stale

#41417 Fix removal of whitespace between invalid tokens in formatter
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java
  misc/formatter/modules/formatter-core/src/test/resources/actions/query/assert/query_action_4.bal
  misc/formatter/modules/formatter-core/src/test/resources/actions/query/source/query_action_4.bal
Labels: Area/Formatting, Team/CompilerFE

#41863 Fix zero exit code when init failures during test execution
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/SingleTestExecutionWithInitFailuresTest.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/TestExecutionWithInitFailuresTest.java
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/SingleFileTestExecutionWithInitFailure.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/TestExecutionWithInitFailures.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/SingleFileTestExecutionWithInitFailure.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/TestExecutionWithInitFailures.txt
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleA/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleA/tests/test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleB/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleB/tests/test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleC/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleC/tests/test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleD/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleD/tests/test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/tests/test_main.bal
  tests/testerina-integration-test/src/test/resources/single-file-tests/single-test-execution/bal-test-with-init-failure.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#38353 Consider RHS true possibility when narrowing false path in a binary exp with logical AND
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/ifelse/TypeGuardTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal
Labels: Team/CompilerFE, Stale

#41943 Fix ArrayIndexOutOfBoundsException at parameter count validation of Java interop methods
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/negative/method_not_found7.bal
Labels: Team/jBallerina

#41773 Add hover support for resource paths
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverObjectResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_function1.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_negative.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_resource_path1.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_resource_path2.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_resource_path3.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_resource_path4.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_resource_path5.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_resource_path6.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_function_call_with_defaultable_param2.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_function_def1.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_function_def2.json
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_for_api_docs_negative.bal
  language-server/modules/langserver-core/src/test/resources/hover/source/hover_for_resource_path.bal
Labels: Team/LanguageServer

#41999 Improve error message for mismatch in worker send-receive pairing
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-worker-send-receive.bal
Labels: Team/CompilerFE

#41885 Fix accessing resource-path-name with escaped dot characters
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/ClientResourceAccessActionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/action/client_resource_access_action.bal
Labels: Team/jBallerina

#41905 Use '&' character for encoding-decoding identifiers to avoid clashes
  .codecov.yml
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BMethodType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  misc/identifier-util/src/main/java/io/ballerina/identifier/Utils.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Async.java
  tests/jballerina-unit-test/src/test/resources/test-src/klass/simple_service_class.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/async/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/main.bal
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/CodeCoverageReportTest.java
Labels: Team/jBallerina

#41844 Make function rest parameters final
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/finaltypes/FinalAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/finaltypes/test_implicitly_final_negative.bal
Labels: Team/CompilerFE, BreakingChange

#42050 [Worker Change] Add `error:NoMessage` iff all receives have it in the alternate receive
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerAsyncSendExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerReceive.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerSendExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerSendReceiveExpr.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangWorkerSyncSendExpr.java
  langlib/lang.error/src/main/ballerina/error.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerAlternateReceiveTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers_alt_receive_negative.bal
Labels: Team/CompilerFE

#42033 Fix rename position in `Extract to local variable` and `Extract to constant` code actions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToLocalVarCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractToConstantTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-constant/config/extractTwoLinesToConstant.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-constant/source/extractToConstant.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config/extractToVariableInQueryExpression.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config/extractToVariableInTableConstructor.json
  language-server/modules/langserver-core/src/test/resources/codeaction/extract-to-local-variable/config/extractToVariableInTableConstructor2.json
Labels: Team/LanguageServer
