Repository ballerina-platform/ballerina-lang, pull requests merged in 2024-10, with the labels that each got.

#43417 Fix query not working inside arrow functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithClosuresTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_closures.bal
Labels: Team/CompilerFE

#41984 Fix module constant usage in xml attribute access
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BaseVisitor.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/model/TreeBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeTransformer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeVisitor.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/SimpleBLangNodeAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangFieldBasedAccess.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/XMLAttrAccessWithModulePrefixTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLLiteralTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/xml_attribute_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/types/xml_attribute_access_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/xml-const.bal
Labels: Team/CompilerFE

#43443 [2201.8.x] Fix zero exit code when init failures during test execution
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/SingleTestExecutionWithInitFailuresTest.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/TestExecutionWithInitFailuresTest.java
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/SingleFileTestExecutionWithInitFailure.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/TestExecutionWithInitFailures.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/SingleFileTestExecutionWithInitFailure.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/TestExecutionWithInitFailures.txt
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleA/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleA/tests/test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleB/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleB/tests/test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleC/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleC/tests/test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleD/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/modules/moduleD/tests/test.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/test-execution-with-init-failure/tests/test_main.bal
  tests/testerina-integration-test/src/test/resources/single-file-tests/single-test-execution/bal-test-with-init-failure.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#43436 Fix `CCE` for annotation symbols in tests in SymbolFinder
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/AnnotationSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/annotations_in_tests_project/Ballerina.toml
  tests/ballerina-compiler-api-test/src/test/resources/test-src/annotations_in_tests_project/tests/tests.bal
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/BasicCasesTest-testAnnotationAccess.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/BasicCasesTest-testAnnotationAccess.txt
Labels: Team/CompilerFE

#43444 Revert back to using Stack
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/ItemGroup.java
Labels: Team/CompilerFE

#43440 Fix defaultable error message when an invalid named argument is used
  compiler/ballerina-lang/src/main/resources/compiler.properties
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/NodeBasedArgProcessor.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/SymbolBasedArgProcessor.java
  tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/ClientResourceAccessActionNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureNegativeTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionWithIncludedRecordParam.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/DependentlyTypedFunctionsTest.java
Labels: Team/CompilerFE

#43460 [2201.10.x] Fix json string to record with union fields conversion
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/JsonParser.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromJson_test.bal
Labels: Team/jBallerina

#43421 Fix XML member access type and allow XML langlib calls with unions
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  langlib/langlib-test/src/test/resources/test-src/xmllib_test_negative.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/XmlMemberAccessTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/xml_member_access.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/xml_member_access_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration_negative.bal
Labels: Team/CompilerFE

#43355 Fix compiler crash with nested queries in select as a field
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithClosuresTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_closures.bal
Labels: Team/CompilerFE

#43476 Enhance the `ballerinaPackage/components` API
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/DocumentComponentTransformer.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/ModuleObject.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/PackageServiceConstants.java
Labels: Team/LanguageServer, Team/LanguageServer/Extensions

#43529 Add functions to services in the `ballerinaPackage/components` API
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/DocumentComponentTransformer.java
Labels: Team/LanguageServer
