Repository ballerina-platform/ballerina-lang, pull requests merged in 2024-06, with the labels that each got.

#42839 [2201.9.x] Revise the definition API of the TypeReferenceTypeSymbol to exclude searching for virtual symbols in the scope
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typedescriptors/TypeReferenceTSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedescriptors/typeref_test.bal
Labels: Team/LanguageServer

#42840 [Master] Revise the definition API of the TypeReferenceTypeSymbol to exclude searching for virtual symbols in the scope
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typedescriptors/TypeReferenceTSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedescriptors/typeref_test.bal
Labels: Team/LanguageServer

#42709 Fix NoSuchFieldError for escaped identifiers during bal test
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/EscapedIdentifiersValidationTest.java
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/EscapedIdentifiersValidationTest-validateEscapedIdentifiersTest.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/EscapedIdentifiersValidationTest-validateEscapedIdentifiersTest.txt
  tests/testerina-integration-test/src/test/resources/project-based-tests/validate-escaped-identifiers/Ballerina.toml
  tests/testerina-integration-test/src/test/resources/project-based-tests/validate-escaped-identifiers/main.bal
  tests/testerina-integration-test/src/test/resources/project-based-tests/validate-escaped-identifiers/tests/test_main.bal
  tests/testerina-integration-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#42747 Remove org.apache.commons.lang3 usage from Ballerina Runtime
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/StateMachine.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/launch/LaunchUtils.java
  bvm/ballerina-runtime/src/main/java/module-info.java
Labels: Team/jBallerina

#42589 [Master] Fix record generation for xml with multiple namespaces
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordConverter.java
  misc/xml-to-record-converter/src/test/java/io/ballerina/xmltorecordconverter/XMLToRecordConverterTests.java
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_28.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_29.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_30.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_31.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_32.bal
  misc/xml-to-record-converter/src/test/resources/xml/sample_28.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_29.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_30.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_31.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_32.xml
Labels: Team/LanguageServer

#42846 [2201.9.x] Fix record generation for xml with multiple namespaces
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordConverter.java
  misc/xml-to-record-converter/src/test/java/io/ballerina/xmltorecordconverter/XMLToRecordConverterTests.java
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_28.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_29.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_30.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_31.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_32.bal
  misc/xml-to-record-converter/src/test/resources/xml/sample_28.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_29.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_30.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_31.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_32.xml
Labels: Team/LanguageServer

#42671 [master] Fix file too large due to many record default functions
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/MapValueImpl.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/AsyncDataCollector.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/JavaClass.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/LambdaClass.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/LambdaFunction.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/InitMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/LambdaGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/ModuleStopMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmMethodsSplitter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmValueCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmStrandMetadataConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmUnionTypeConstantsGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmObjectCreatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/creators/JvmRecordCreatorGen.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods2/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods2/modules/records/many-records.bal
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/CodeCoverageReportTest.java
Labels: Team/jBallerina

#42834 Refactor `unescapeJava()` usage in ballerina-lang
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/AnnotationDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  misc/identifier-util/src/main/java/module-info.java
  misc/toml-parser/build.gradle
  misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java
  misc/toml-parser/src/main/java/module-info.java
Labels: Team/jBallerina

#41955 Fix XAER_RMFAIL error on transaction rollback
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionLocalContext.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
Labels: Team/CompilerFE, Lang/Transactions, Stale

#42899 Fix redundant casts
  ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/StringUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/JsonUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BParameterizedType.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/AbstractNodeFactory.java
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/SelectDescendants.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Elements.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Get.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/GetAttributes.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/GetContent.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Select.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/SelectDescendants.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Slice.java
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Strip.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/imports/AddModuleToBallerinaTomlCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ForEachStatementNodeContext.java
  misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/jdi/StackFrameProxyImpl.java
  misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/io/StringUtils.java
  misc/toml-parser/src/main/java/io/ballerina/toml/syntax/tree/AbstractNodeFactory.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Async.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/ArrayStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/stamp/MapStampInbuiltFunctionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/NumericConversionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/primitivetypes/PrimitiveConversionsInFunctionParamsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/BJSONValueTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerSyncSendTest.java
Labels: Team/CompilerFE

#42845 [2201.9.x] Fix xml to record conversion for default value node
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordConverter.java
  misc/xml-to-record-converter/src/test/java/io/ballerina/xmltorecordconverter/XMLToRecordConverterTests.java
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_33.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_34.bal
  misc/xml-to-record-converter/src/test/resources/xml/sample_33.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_34.xml
Labels: Team/LanguageServer

#42901 Replace lambda statements with expression lambdas where applicable
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BLockStore.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/LauncherUtils.java
  cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/TestCommandTest.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaRecordTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/model/Manifest.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/test/java/io/ballerina/projects/ProjectUtilsTests.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CompilerPluginCodeActionExtension.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ServiceTemplateGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/documentsymbol/DocumentSymbolResolver.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/connector/BallerinaConnectorService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/ExecutorPositionsUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/visitor/UnusedSymbolsVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/BallerinaPackageService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/BallerinaSymbolService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/semantictokens/SemanticTokensVisitor.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/TestUtil.java
  misc/diagram-util/src/main/java/org/ballerinalang/diagramutil/SyntaxTreeMapGenerator.java
  misc/semver-checker/modules/semver-checker-core/src/main/java/io/ballerina/semver/checker/comparator/FunctionComparator.java
  misc/testerina/modules/testerina-compiler-plugin/src/main/java/org/ballerinalang/testerina/compiler/TesterinaCodeAnalyzer.java
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TestSuite.java
  project-api/test-artifacts/compiler-plugin-with-two-dependencies/src/main/java/io/samjs/plugins/twodependencies/CompilerPluginWithTwoDependencies.java
  project-api/test-artifacts/function-node-analyzer-compiler-plugin/src/main/java/io/samjs/plugins/funcnodeanalyzer/FunctionNodeAnalyzerPlugin.java
  project-api/test-artifacts/function-node-analyzer-compiler-plugin/src/main/java/io/samjs/plugins/lifecycle/CompilationEventPlugin.java
  project-api/test-artifacts/init-function-codegen-compiler-plugin/src/main/java/io/samjs/plugins/init/codegen/CodegenFunctionPlugin.java
  project-api/test-artifacts/log-creator-in-built-code-analyzer/src/main/java/io/luhee/plugins/inbuilt/analyzer/LogCodeAnalyzerInBuiltPlugin.java
  project-api/test-artifacts/log-creator-in-built-code-generator/src/main/java/io/luhee/plugins/inbuilt/generator/LogCodeGeneratorInBuiltPlugin.java
  project-api/test-artifacts/log-creator-in-built-code-modifier/src/main/java/io/luhee/plugins/inbuilt/modifier/LogCodeModifierInBuiltPlugin.java
  project-api/test-artifacts/log-creator-pkg-provided-code-analyzer/src/main/java/io/luhee/plugins/pkg/analyzer/LogCodeAnalyzerPkgPlugin.java
  project-api/test-artifacts/log-creator-pkg-provided-code-generator/src/main/java/io/luhee/plugins/pkg/generator/LogCodeGeneratorPkgPlugin.java
  project-api/test-artifacts/log-creator-pkg-provided-code-modifier/src/main/java/io/luhee/plugins/pkg/modifier/LogCodeModifierPkgPlugin.java
  project-api/test-artifacts/simple-code-gen-plugin-with-resource-gen/src/main/java/io/asmaj/plugins/simple/codegen/CodegenFunctionPlugin.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java
Labels: Team/CompilerFE

#42699 [Master] Fix xml to record conversion for default value node
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordConverter.java
  misc/xml-to-record-converter/src/test/java/io/ballerina/xmltorecordconverter/XMLToRecordConverterTests.java
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_33.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_34.bal
  misc/xml-to-record-converter/src/test/resources/xml/sample_33.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_34.xml
Labels: Team/LanguageServer

#42964 Address review suggestions of #42950
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java
Labels: Team/CompilerFE

#42941 Integrate XML semtype into compiler
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemTypeHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLSubType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BXMLType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  semtypes/src/main/java/io/ballerina/types/Atom.java
  semtypes/src/main/java/io/ballerina/types/PredefinedType.java
  semtypes/src/main/java/io/ballerina/types/RecAtom.java
  semtypes/src/main/java/io/ballerina/types/subtypedata/XmlSubtype.java
  semtypes/src/main/java/io/ballerina/types/typeops/XmlOps.java
Labels: Team/CompilerFE

#42853 [2201.9.x] Reorder the desugaring of type definitions before the desugaring of global variables and configurables in the desugar phase
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/main/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_decl.bal
Labels: Team/CompilerFE

#42977 Update treegen for the `@override` changes in the current master
  compiler/ballerina-treegen/src/main/resources/internal_node_template.mustache
  compiler/ballerina-treegen/src/main/resources/internal_tree_modifier_template.mustache
Labels: Team/CompilerFE, Area/Parser

#42960 Integrate handle and regexp semtypes into compiler
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemTypeHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BAnydataType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BBuiltInRefType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BHandleType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRegexpType.java
  semtypes/src/main/java/io/ballerina/types/BasicTypeCode.java
  semtypes/src/main/java/io/ballerina/types/Core.java
  semtypes/src/main/java/io/ballerina/types/OpsTable.java
  semtypes/src/main/java/io/ballerina/types/PredefinedType.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/anydata.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/anydata/anydata_test.bal
Labels: Team/CompilerFE

#42992 Integrate future and typedesc semtypes into compiler
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/type/builders/BallerinaFutureTypeBuilder.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/type/builders/BallerinaTypeDescTypeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemTypeHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BFutureType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BJSONType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTypedescType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java
  semtypes/src/main/java/io/ballerina/types/OpsTable.java
  semtypes/src/main/java/io/ballerina/types/PredefinedType.java
  semtypes/src/main/java/io/ballerina/types/SemTypes.java
  semtypes/src/main/java/io/ballerina/types/subtypedata/FutureSubtype.java
  semtypes/src/main/java/io/ballerina/types/subtypedata/TypedescSubtype.java
  semtypes/src/main/java/io/ballerina/types/typeops/FutureOps.java
  semtypes/src/main/java/io/ballerina/types/typeops/TypedescOps.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/future-subtype.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/typedesc-subtype.bal
Labels: Team/CompilerFE

#42815 Add checks and logic to implement shift operation in tuples at runtime
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/errors/ErrorCodes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Shift.java
  langlib/langlib-test/src/test/resources/test-src/arraylib_test.bal
Labels: Team/jBallerina
