Repository ballerina-platform/ballerina-lang, pull requests merged in 2024-05, with the labels that each got.

#42656 [2201.9.0] Fix file too large due to many record default functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/AsyncDataCollector.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/internal/RecordDefaultValueDataCollector.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/InitMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/LambdaGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods2/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods2/modules/records/many-records.bal
  tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/CodeCoverageReportTest.java
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/DataProviderTest-testValidDataProviderWithAfterFailing.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/unix/DataProviderTest-testValidDataProviderWithBeforeFailing.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/DataProviderTest-testValidDataProviderWithAfterFailing.txt
  tests/testerina-integration-test/src/test/resources/command-outputs/windows/DataProviderTest-testValidDataProviderWithBeforeFailing.txt
Labels: Team/jBallerina

#42676 [2201.9.0] Fix adding namespaces when the option is not selected
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordConverter.java
  misc/xml-to-record-converter/src/test/java/io/ballerina/xmltorecordconverter/XMLToRecordConverterTests.java
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_20.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_26.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_27.bal
  misc/xml-to-record-converter/src/test/resources/xml/sample_26.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_27.xml
Labels: Team/LanguageServer

#42517 [2201.8.x] Fix incorrect convertible types resolved from type-value pair set for union of records
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#42668 Update location of extension points file
  language-server/README.md
Labels: Team/LanguageServer

#42663 Port nBallerina readonly and error types
  semtypes/src/main/java/io/ballerina/types/Error.java
  semtypes/src/main/java/io/ballerina/types/PredefinedType.java
  semtypes/src/main/java/io/ballerina/types/typeops/ErrorOps.java
  semtypes/src/test/java/io/ballerina/types/SemTypeCoreTest.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeTest.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/fixed-length-array.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/fixed-length-array-large-t.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/fixed-length-array-t.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/xml-complex-ro-tv.bal
Labels: Team/CompilerFE, Area/SemtypePort

#42677 [Master] Fix adding namespaces when the option is not selected
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordConverter.java
  misc/xml-to-record-converter/src/test/java/io/ballerina/xmltorecordconverter/XMLToRecordConverterTests.java
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_20.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_26.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_27.bal
  misc/xml-to-record-converter/src/test/resources/xml/sample_26.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_27.xml
Labels: Team/LanguageServer

#42701 Fix fixed length array size overflowing
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeAssertionTransformer.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeTest.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/fixed-length-array-too-large-te.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/fixed-length-array-large-t.bal
Labels: Team/CompilerFE, Area/SemtypePort

#42708 Provide code actions to fix the invalid access of mutable storage in an isolated function
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddIsolatedQualifierCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/MakeVariableImmutableCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddIsolatedQualifierCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/MakeVariableImmutableCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/config/add_isolated_qualifier_config10.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/config/add_isolated_qualifier_config11.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/config/add_isolated_qualifier_config13.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/config/add_isolated_qualifier_config14.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/config/add_isolated_qualifier_config15.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/config/add_isolated_qualifier_config16.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/config/add_isolated_qualifier_config17.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/config/add_isolated_qualifier_config18.json
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/source/isolatedFunctionCodeAction/modules/module2/add_isolated_qualifier_source5.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/source/isolatedFunctionCodeAction/modules/module2/add_isolated_qualifier_source6.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable16.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable17.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable18.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable19.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable20.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable21.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable22.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable16.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable17.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable18.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable19.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable20.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable21.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable22.bal
Labels: Team/LanguageServer

#42688 [2201.8.x] Fix the wrong help message
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-run.help
Labels: Stale

#42744 Update lang version
  gradle.properties
Labels: Team/CompilerFE

#42738 Fix file too large error due to unnecessary node cloning
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/CodegenErrorsTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods4/.gitignore
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods4/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/largeMethods4/main.bal
Labels: Team/CompilerFE

#42791 Fix porting bug in mappingInhabited method
  semtypes/src/main/java/io/ballerina/types/ComplexSemType.java
  semtypes/src/main/java/io/ballerina/types/MappingAtomicType.java
  semtypes/src/main/java/io/ballerina/types/typeops/BddCommonOps.java
  semtypes/src/main/java/io/ballerina/types/typeops/MappingOps.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/mapping1.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/mapping2.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/mapping-record-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/mapping-t.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/mapping1-t.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/mapping2-t.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/mapping3-t.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/mappingIntersect-tv.bal
Labels: Team/CompilerFE, Area/SemtypePort

#42768 Enable function pointer byte default value test
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal
Labels: Team/jBallerina

#42810 Fix compiler crash on lang lib xml iterable operations on union types
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
Labels: Team/CompilerFE

#42649 Fix redirect url when running "push"
  cli/ballerina-cli/src/main/java/io/ballerina/cli/utils/CentralUtils.java
Labels: Stale

#42813 Fix xml map operation on xml element sequence returning nested xml
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLIterationTest.java
Labels: Team/CompilerFE

#42826 Fix `xml:filter` return type on non `xml:Element` singleton values
  langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Filter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java
  langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal
Labels: Team/CompilerFE

#42626 [2201.8.x] Revise the definition API of the `TypeReferenceTypeSymbol` to exclude searching for virtual symbols in the scope
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typedescriptors/TypeReferenceTSymbolTest.java
  tests/ballerina-compiler-api-test/src/test/resources/test-src/typedescriptors/typeref_test.bal
Labels: Team/CompilerFE
