Repository ballerina-platform/ballerina-lang, pull requests merged in 2024-04, with the labels that each got.

#42363 Add runtime APIs to call module init, start, stop and function invocations from a Ballerina project
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/constants/RuntimeConstants.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BalEnvironment.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BalRuntime.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/errors/ErrorCodes.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java
  bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties
  misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java
  tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BFileUtil.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/runtime/api/ModuleStartCallNegative.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPICall.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPICallNegative.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPITest.java
  tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/util/SQLDBUtils.java
  tests/jballerina-integration-test/src/test/resources/runtime.api/function_invocation/Ballerina.toml
  tests/jballerina-integration-test/src/test/resources/runtime.api/function_invocation/foo.bal
  tests/jballerina-integration-test/src/test/resources/runtime.api/function_invocation/main.bal
  tests/jballerina-integration-test/src/test/resources/runtime.api/function_invocation/modules/moduleA/main.bal
  tests/jballerina-integration-test/src/test/resources/testng.xml
Labels: Team/jBallerina

#42448 Fix never frame assignment throwing `NoSuchField` error
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java
Labels: Team/jBallerina

#41816 Fix compiler crash when accessing previous parameter in default expression with lambda expression
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/CompilerUtils.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableArguments.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal
Labels: Team/CompilerFE

#42187 Implement input stream parser that create anydata values
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/Type.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/JsonUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/JsonParser.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ParserException.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/StateMachine.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueConverter.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/AbstractArrayValue.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/MapValueImpl.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TupleValueImpl.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonDecimalString.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonFloatString.java
  langlib/lang.value/src/main/java/org/ballerinalang/langlib/value/FromJsonStringWithType.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_fromJson_test.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/JsonValues.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Stream.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/runtime/api/RuntimeAPITest.java
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/json/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/json/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/stream/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/stream/largeJsonString.bal
  tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/stream/main.bal
Labels: Team/jBallerina

#41841 Fix invalid error for inaccessible module definitions in mapping constructor
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/expressions/MappingConstructorExprBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/expressions/mapping_constructor_expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/expressions/mapping_constructor_expr_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/mapping_constructor.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor_negative.bal
Labels: Team/CompilerFE

#42429 Support mapping the Ballerina external function args to jBallerina BArray
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmConstants.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIConstructorCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JIMethodCall.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethod.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/StaticMethodTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
Labels: Team/jBallerina

#41481 Fix formatting of comments above import declarations
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java
  misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java
  misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/declarations/ImportDeclarationsTest.java
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/assert/import_declaration_1.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/assert/import_declaration_10.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/assert/import_declaration_11.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/assert/import_declaration_5.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/assert/import_declaration_6.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/assert/import_declaration_7.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/assert/import_declaration_8.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/assert/import_declaration_9.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/source/import_declaration_10.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/source/import_declaration_11.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/source/import_declaration_6.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/source/import_declaration_7.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/source/import_declaration_8.bal
  misc/formatter/modules/formatter-core/src/test/resources/declarations/import/source/import_declaration_9.bal
Labels: Area/Formatting, Team/CompilerFETools

#41733 Add `on conflict` clause to query pipeline
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java
  langlib/lang.query/src/main/ballerina/helpers.bal
  langlib/lang.query/src/main/ballerina/types.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal
Labels: Team/CompilerFE, Area/Desugar, Lang/Expressions/Query

#42341 Provide code actions to fix invalid non-private mutable field
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddPrivateQualifierCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/MakeVariableImmutableCodeAction.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/constants/CommandConstants.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AddPrivateQualifierCodeActionTest.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/MakeVariableImmutableCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/config/change_field_private1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/config/change_field_private2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/config/change_field_private3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/config/change_field_private4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/config/change_field_private5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/config/change_field_private6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/source/change_field_private1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/source/change_field_private2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/source/change_field_private3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/source/change_field_private4.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/source/change_field_private5.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/change-field-private/source/change_field_private6.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable10.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable11.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable12.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable13.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable14.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable15.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable7.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable8.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/config/make_variable_immutable9.json
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable10.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable11.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable12.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable13.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable14.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable15.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable3.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable4.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable5.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable6.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable7.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable8.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/make-variable-immutable/source/make_variable_immutable9.bal
Labels: Team/LanguageServer

#42025 Fix `readonly` intersection with type reference for readonly
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/test_intersection_type.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/test_intersection_type_negative.bal
Labels: Team/CompilerFE

#42366 Fix isolation analysis for start actions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationAnalysisTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolationWarningTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_analysis_for_async_actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/isolation-analysis/isolation_warnings_for_service_methods.bal
Labels: Team/CompilerFE

#42336 Add 'remoteManagement' compiler option through build-options of Ballerina.toml
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java
  cli/ballerina-cli/src/main/resources/cli-help/ballerina-build.help
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/BuildOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/CompilationOptions.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageResolution.java
  compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ManifestBuilder.java
  compiler/ballerina-lang/src/main/java/org/ballerinalang/compiler/CompilerOptionName.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/values/JvmObjectGen.java
  misc/semver-checker/modules/semver-checker-core/src/main/java/io/ballerina/semver/checker/util/PackageUtils.java
  project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
  project-api/project-api-test/src/test/resources/projectWithBuildOptions/Ballerina.toml
Labels: Team/jBallerina

#42498 [Master] Fix `error:NoMessage` for `worker-on-fail-clause`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerOnFailTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker-on-fail-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker-on-fail.bal
Labels: Team/CompilerFE

#42486 [Master] Add new options in xml conversion service
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordConverter.java
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordConverterService.java
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordRequest.java
  misc/xml-to-record-converter/src/test/java/io/ballerina/xmltorecordconverter/XMLToRecordConverterTests.java
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_25.bal
  misc/xml-to-record-converter/src/test/resources/xml/sample_25.xml
Labels: Team/CompilerFE

#42500 [2201.9.x] Fix `error:NoMessage` for `worker-on-fail-clause`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerOnFailTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker-on-fail-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/worker-on-fail.bal
Labels: Team/CompilerFE

#42503 Disallow error binding patterns in on fail clauses temporarily (for U9)
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachNegativeTests.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachOnFailTests.java
  langlib/langlib-test/src/test/resources/test-src/statements/foreach/foreach-on-fail.bal
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/dataflow/analysis/UnusedVariableTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/lock/LocksWithOnFailTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStatementOnFailTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/onfail/OnFailClauseTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/retrystmt/RetryStmtWithOnFailTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/whilestatement/WhileStmtTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/dataflow/analysis/unused_variable_analysis_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/lock/lock-on-fail.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/matchstmt_on_fail.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/onfail/on-fail-clause.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/retrystmt/retry_stmt_with_on_fail.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/whilestatement/while-stmt-on-fail.bal
Labels: Team/CompilerFE

#42516 [2201.9.x] Fix `autoClose()` langlib invocation when current strand is root strand
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/WorkerChannels.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/ForkInFunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/fork-within-if-condition.bal
Labels: Team/CompilerFE, Team/jBallerina

#42519 [Master] Fix autoClose() invocation when current strand is root strand
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/WorkerChannels.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/ForkInFunctionTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/fork-within-if-condition.bal
Labels: Team/CompilerFE, Team/jBallerina

#42478 [Master] Fix worker receive when the receiver successfully completes prior to the sync send
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-receive-before-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-receive-with-workers.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/send-receive-allowed-positions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers_conditional_send.bal
Labels: Team/CompilerFE

#42525 [2201.9.x] Fix CheckCast generation for bundling function args into 'any[]'
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
Labels: Team/jBallerina

#42518 [2201.9.x] Fix incorrect convertible types resolved from type-value pair set for union of records
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#42581 [interop-param-mapping] Fix mapping of array parameters clashes with rest-parameters in interop functions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
Labels: Team/jBallerina

#42573 [2201.9.x] Fix CheckCast generation for bundling function args into 'any[]'
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java
  tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal
Labels: Team/jBallerina

#42576 [2201.9.x] Fix creating redundant future values for default value function calls
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
Labels: Team/jBallerina

#42608 [2201.9.0] Add the relevant new import text edits via the `Create variable with type code` action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableWithPositionalRenameSupportCapabilityTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_for_resource_action_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/source/source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithInferredType1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithInferredType2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithInferredType3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithInferredType4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithInferredType.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config5.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_client.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_performance.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typeref1.json
  language-server/modules/langserver-stdlib/src/main/ballerina/clients_source1.bal
  language-server/modules/langserver-stdlib/src/main/ballerina/modules/mod2/mod2.bal
Labels: Team/LanguageServer

#42635 [2201.9.0-stage] Add dummy strand for non strand cases
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TypedescValueImpl.java
Labels: Team/jBallerina

#42568 [2201.8.x] Fix gradle syntax errors in setting versions
  misc/ballerinalang-data-mapper/build.gradle
  misc/ls-extensions/modules/performance-analyzer-services/build.gradle
  misc/toml-parser/build.gradle
Labels: Team/jBallerina

#42574 [Master] Add the relevant new import text edits via the `Create variable with type` code action
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableWithPositionalRenameSupportCapabilityTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/config/type_infer_for_resource_action_config2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-var-with-type/source/source1.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithInferredType1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithInferredType2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithInferredType3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config-rename-positional-capability/createVariableWithInferredType4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithInferredType.bal
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config21.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config8.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config1.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config2.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config3.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config4.json
  language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/remote_action_config5.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_for_api_docs_client.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_performance.json
  language-server/modules/langserver-core/src/test/resources/hover/configs/hover_typeref1.json
  language-server/modules/langserver-stdlib/src/main/ballerina/clients_source1.bal
  language-server/modules/langserver-stdlib/src/main/ballerina/modules/mod2/mod2.bal
Labels: Team/LanguageServer

#42634 [master] Use daemon strand for non strand threads
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueUtils.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TypedescValueImpl.java
Labels: Team/jBallerina

#42496 Fix incorrect convertible types resolved from type-value pair set for union of records
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java
  langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java
  langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal
Labels: Team/jBallerina

#42511 Port nBallerina function type
  semtypes/src/main/java/io/ballerina/types/Context.java
  semtypes/src/main/java/io/ballerina/types/Env.java
  semtypes/src/main/java/io/ballerina/types/definition/FunctionDefinition.java
  semtypes/src/test/java/io/ballerina/types/SemTypeCoreTest.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeAssertionTransformer.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeTest.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/simple-type/function-altered.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/function-intersection-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/function-param-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/function-rec-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/function-rest-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/function-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/function-union-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/function2-tv.bal
Labels: Team/CompilerFE, Area/SemtypePort

#42650 Fix multidimensional lists not being resolved correct to semtypes
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/list1-tv.bal
Labels: Team/CompilerFE, Area/SemtypePort

#42661 [2201.9.0] Remove the message shown during package indexing
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java
Labels: Team/LanguageServer

#42660 [Master] Remove the message shown during package indexing
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java
Labels: Team/LanguageServer
