Repository ballerina-platform/ballerina-lang, pull requests merged in 2024-07, with the labels that each got.

#43000 Integrate stream semtypes into compiler
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/type/builders/BallerinaStreamTypeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemTypeHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BStreamType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java
  semtypes/src/main/java/io/ballerina/types/Env.java
  semtypes/src/main/java/io/ballerina/types/OpsTable.java
  semtypes/src/main/java/io/ballerina/types/PredefinedType.java
  semtypes/src/main/java/io/ballerina/types/TypeAtom.java
  semtypes/src/main/java/io/ballerina/types/definition/StreamDefinition.java
  semtypes/src/main/java/io/ballerina/types/typeops/StreamOps.java
  semtypes/src/test/java/io/ballerina/types/EnvInitTest.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/stream-recursive.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/stream-subtype.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/data/stream-subtype2.bal
Labels: Team/CompilerFE, Area/SemtypeIntegration

#42966 Fix annotation values with mapping values panic at runtime for const annotations
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationRuntimeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal
Labels: Team/CompilerFE

#42997 Fix 'no such method' error for imported resource method
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/LambdaGen.java
Labels: Team/jBallerina

#42852 Reorder the desugaring of type definitions before the desugaring of global variables and configurables in the desugar phase
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/Config.toml
  tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/main/main.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_decl.bal
Labels: Team/CompilerFE

#42925 [2201.9.x] Fix getting non-accessible symbol error for error intersections with details
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/intersection/IntersectionTypeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error-intersection-access/Ballerina.toml
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error-intersection-access/error_intersection_access_test.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/intersection/error-intersection-access/modules/error_intersection_mod/error_intersection_mod.bal
Labels: Area/Compiler, Team/CompilerFE

#43018 Refactor type environment initialization
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  semtypes/src/main/java/io/ballerina/types/CellAtomicType.java
  semtypes/src/main/java/io/ballerina/types/Core.java
  semtypes/src/main/java/io/ballerina/types/Env.java
  semtypes/src/main/java/io/ballerina/types/PredefinedType.java
  semtypes/src/main/java/io/ballerina/types/PredefinedTypeEnv.java
  semtypes/src/main/java/io/ballerina/types/TypeAtom.java
  semtypes/src/test/java/io/ballerina/types/EnvInitTest.java
Labels: Team/CompilerFE, Area/SemtypeIntegration

#43056 [2201.9.x] Remove adding default namespaces in xml to record generation
  misc/xml-to-record-converter/src/main/java/io/ballerina/xmltorecordconverter/XMLToRecordConverter.java
  misc/xml-to-record-converter/src/test/java/io/ballerina/xmltorecordconverter/XMLToRecordConverterTests.java
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_27.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_35.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_36.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_37.bal
  misc/xml-to-record-converter/src/test/resources/ballerina/sample_9.bal
  misc/xml-to-record-converter/src/test/resources/xml/sample_35.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_36.xml
  misc/xml-to-record-converter/src/test/resources/xml/sample_37.xml
Labels: Team/LanguageServer

#42565 [2201.9.x] Fix worker send hangs when worker early return within if stmt
  bvm/ballerina-runtime/src/main/java/module-info.java
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/WorkerChannels.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerConditionalSendTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/basic-worker-actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers_conditional_send.bal
Labels: Team/jBallerina, Stale

#42745 Fix worker send hangs when worker early return within if stmt
  bvm/ballerina-runtime/src/main/java/module-info.java
  langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/WorkerChannels.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerConditionalSendTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/workers/basic-worker-actions.bal
  tests/jballerina-unit-test/src/test/resources/test-src/workers/workers_conditional_send.bal
Labels: Team/jBallerina, Stale

#42975 Port object semtype to jBallerina
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  semtypes/src/main/java/io/ballerina/types/OpsTable.java
  semtypes/src/main/java/io/ballerina/types/PredefinedType.java
  semtypes/src/main/java/io/ballerina/types/PredefinedTypeEnv.java
  semtypes/src/main/java/io/ballerina/types/definition/Member.java
  semtypes/src/main/java/io/ballerina/types/definition/ObjectDefinition.java
  semtypes/src/main/java/io/ballerina/types/definition/ObjectQualifiers.java
  semtypes/src/main/java/io/ballerina/types/typeops/ObjectOps.java
  semtypes/src/test/java/io/ballerina/types/EnvInitTest.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/object-binaryops-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/object-qulifiers-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/object-rec-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/object-simple-tv.bal
Labels: Team/CompilerFE, Area/SemtypePort

#43010 Use object semtype in compiler type checker
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamResolver.java
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/type/builders/BallerinaObjectTypeBuilder.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemTypeHelper.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java
  semtypes/src/main/java/io/ballerina/types/CellAtomicType.java
  semtypes/src/main/java/io/ballerina/types/Core.java
  semtypes/src/main/java/io/ballerina/types/SemTypes.java
  semtypes/src/main/java/io/ballerina/types/definition/MappingDefinition.java
  semtypes/src/main/java/io/ballerina/types/definition/ObjectDefinition.java
  semtypes/src/main/java/io/ballerina/types/typeops/ObjectOps.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/object-distinct-tv.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal
  tests/jballerina-unit-test/src/test/resources/test-src/jvm/objects_subtyping.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/ObjectEquivalencyProject/object-equivalency.bal
Labels: Team/CompilerFE, Area/SemtypeIntegration

#43139 Fix function qualifier not being included in semtype
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BInvokableType.java
  docs/bir-spec/src/main/resources/kaitai/bir.ksy
  semtypes/src/main/java/io/ballerina/types/FunctionAtomicType.java
  semtypes/src/main/java/io/ballerina/types/definition/FunctionDefinition.java
  semtypes/src/main/java/io/ballerina/types/definition/FunctionQualifiers.java
  semtypes/src/main/java/io/ballerina/types/typeops/FunctionOps.java
  semtypes/src/test/java/io/ballerina/types/SemTypeCoreTest.java
  tests/jballerina-semtype-port-test/src/test/java/io/ballerina/semtype/port/test/SemTypeResolver.java
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/func-quals-tv.bal
  tests/jballerina-semtype-port-test/src/test/resources/test-src/type-rel/object-simple-tv.bal
Labels: Team/CompilerFE, Area/SemtypeIntegration

#42926 Fix providing invalid fix return type code action for anonymous functions
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/FixReturnTypeTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/fixReturnTypeOfAnonymousFunc1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/fixReturnTypeOfAnonymousFunc2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/fixReturnTypeOfAnonymousFunc3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/fixReturnTypeOfAnonymousFunc4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/fixReturnTypeOfAnonymousFunc5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/negativeFixReturnTypeOfAnonymousFunc1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/negativeFixReturnTypeOfAnonymousFunc2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/negativeFixReturnTypeOfAnonymousFunc3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/negativeFixReturnTypeOfAnonymousFunc4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/config/negativeFixReturnTypeOfAnonymousFunc5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/source/fixReturnTypeOfAnonymousFunc.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/source/fixReturnTypeOfAnonymousFunc2.bal
  language-server/modules/langserver-core/src/test/resources/codeaction/fix-return-type/source/fixReturnTypeOfAnonymousFuncNegative.bal
Labels: Team/LanguageServer, Area/CodeAction

#42930 Fix change var type code action not working for wild card bindings
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ChangeVariableTypeCodeActionTest.java
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarTypeOfWildcardBindings1.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarTypeOfWildcardBindings2.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarTypeOfWildcardBindings3.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarTypeOfWildcardBindings4.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarTypeOfWildcardBindings5.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarTypeOfWildcardBindings6.json
  language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarTypeOfWildcardBindings.bal
Labels: Team/LanguageServer, Area/CodeAction

#43165 Fix object type ingnoring distinct type inclusion
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java
Labels: Team/CompilerFE, Area/SemtypeIntegration

#43133 [2201.9.x] Add org name to the package metadata response
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/BallerinaPackageService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/PackageMetadataResponse.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/packages/MetadataTest.java
  language-server/modules/langserver-core/src/test/resources/packages/metadata/project-functions_expected.json
  language-server/modules/langserver-core/src/test/resources/packages/metadata/project-services_expected.json
Labels: Team/LanguageServer

#43149 Support navigation/references for init functions
  compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/references/ReferencesTest.java
  language-server/modules/langserver-core/src/test/resources/references/expected/init_function_references.json
  language-server/modules/langserver-core/src/test/resources/references/sources/projectls/class_def.bal
  language-server/modules/langserver-core/src/test/resources/references/sources/projectls/union_types.bal
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindRefsInClassObjectTest.java
Labels: Team/LanguageServer

#43121 Fix method annotations for object types
  bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/AnnotationUtils.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/servicetests/ServiceValue.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationRuntimeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal
Labels: Team/CompilerFE

#43132 Add org name to the package metadata response
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/BallerinaPackageService.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/PackageMetadataResponse.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/packages/MetadataTest.java
  language-server/modules/langserver-core/src/test/resources/packages/metadata/project-functions_expected.json
  language-server/modules/langserver-core/src/test/resources/packages/metadata/project-services_expected.json
Labels: Team/LanguageServer

#42968 Fix NPE in lambda functions with check expressions
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/statements/dostatement/do-stmt.bal
Labels: Team/CompilerFE

#42580 Fix addition of xml with strings
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/AddOperationTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/add-operation.bal
Labels: Team/CompilerFE

#43197 Allow parameter names to differ with object type inclusion
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/DependentlyTypedFunctionsTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTypeReferenceTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_object_type_inclusion_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object-type-reference.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_func_reference_neg.bal
Labels: Team/CompilerFE

#43185 Disallow `check` in parameter defaults
  compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
  compiler/ballerina-lang/src/main/resources/compiler.properties
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableParametersTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/check_in_parameter_default_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal
  tests/jballerina-unit-test/src/test/resources/test-src/object/object_field_initializer_with_check_negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/record/negative/record_field_default_value_negative.bal
Labels: Team/CompilerFE
