Repository ballerina-platform/ballerina-lang, pull requests merged in 2025-02, with the labels that each got.

#43641 Provide a Ballerina command to display the API specifications of all active LS APIs
  cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/Constants.java
  cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/util/BalToolsUtil.java
  language-server/modules/langserver-cli/src/main/java/module-info.java
  language-server/modules/langserver-cli/src/main/java/org/ballerinalang/langserver/cmd/LangServerSpecCmd.java
  language-server/modules/langserver-cli/src/main/resources/META-INF/services/io.ballerina.cli.BLauncherCmd
  language-server/modules/langserver-core/spotbugs-exclude.xml
  language-server/modules/langserver-core/src/main/java/module-info.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/apispec/ApiSpecGenerator.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/apispec/MethodSchema.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/apispec/ParameterSchema.java
  language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/apispec/TypeSchema.java
  language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/apispec/ApiSpecificationGeneratorTest.java
  language-server/modules/langserver-core/src/test/resources/apispec/config1.json
  language-server/modules/langserver-core/src/test/resources/apispec/config10.json
  language-server/modules/langserver-core/src/test/resources/apispec/config2.json
  language-server/modules/langserver-core/src/test/resources/apispec/config3.json
  language-server/modules/langserver-core/src/test/resources/apispec/config4.json
  language-server/modules/langserver-core/src/test/resources/apispec/config5.json
  language-server/modules/langserver-core/src/test/resources/apispec/config6.json
  language-server/modules/langserver-core/src/test/resources/apispec/config7.json
  language-server/modules/langserver-core/src/test/resources/apispec/config8.json
  language-server/modules/langserver-core/src/test/resources/apispec/config9.json
  language-server/modules/langserver-core/src/test/resources/testng.xml
  language-server/modules/launchers/stdio-launcher/src/main/java/module-info.java
  language-server/modules/launchers/stdio-launcher/src/main/java/org/ballerinalang/langserver/launchers/stdio/Main.java
Labels: Team/LanguageServer

#43782 [Master] Desugar field access expression to if statement expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
Labels: Team/CompilerFE

#43776 [2201.10.x] Desugar field access expression to if statement expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal
Labels: Team/CompilerFE

#43798 Fix invalid token diagnostic in NodeParser
  compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java
  compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/tree/nodeparser/ParseExpressionTest.java
Labels: Team/CompilerFE, Area/Parser

#43758 Reset `unknownTypeRefs` after silent type checking
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/typedefs/TypeDefinitionsNegativeTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions-semantics-negative.bal
Labels: Team/CompilerFE, Area/TypeChecker

#43810 Add support for string template expression as constant expression
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantAnalyzer.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/StringTemplateConstantTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/string-template-constant-negative.bal
  tests/jballerina-unit-test/src/test/resources/test-src/types/constant/string-template-constant.bal
Labels: Team/CompilerFE

#43589 Fix `Resource access that are not ambiguous are reported as ambiguous access`
  compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java
  tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/actions/SymbolsInResourceAccessActionTest.java
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/action/ClientResourceAccessActionNegativeTest.java
Labels: Team/CompilerFE

#43799 Fix compiler crashes for raw template with interpolations when used as a default value of a parameter
  tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableParametersTest.java
  tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal
Labels: Team/CompilerFE
